### ISSUE TITLE
Test navigation to accessibility content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10009]
**What is the problem to solve?**

People don't always know where to look for access-related content on the site.

**What are the objectives?**

- Identify navigation paths to specific types of accessibility information 

**What are the assumptions?**

Users look for an 'Accessibility' page
Users expect exhibition-related information to be found with the exhibition

**What research technique is required?**

Tree testing (Optimal sort)

**Optimal number of participants**

50

**Deadline for results/dependencies:**

Q4 2023

**Background**
Linked to #10036

**Comment by jennpb** [comment]
Visual stories research questions: https://docs.google.com/document/d/1gHrTvpDCSN_dWHqOPzZk5LZhsg4t8p7y2kpSQ5-lEWU/edit?usp=sharing

**Comment by DominiqueMarshall** [comment]
Results from the tree test available here: [Access content navigation tree test](https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/Shared%20Documents/Design/Design%20Docs%20from%20Dom/Access%20Content%20Navigation%20Tree%20Test/Access%20Content%20navigation%20tree%20test.pptx?d=w2402da86e49546bd88815400ce3c3036&csf=1&web=1&e=ewWJhw)

**Comment by jennpb** [comment]
@jennpb to share findings with Accessible Messaging Workgroup and Digital Editorial team

**Comment by jennpb** [comment]
All documents moved to https://wellcomecloud.sharepoint.com/:f:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Whole%20site/Access%20content%20navigation%20Aug%202023?csf=1&web=1&e=0h60of
