### ISSUE TITLE
Add TextAndImage and TextAndIcons to Gitbook documentation

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10016]
Once we're done modifying the two new components, we should ensure they are added to [the Gitbook Prismic Slice documentation](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/451yLOIRTl5YiAJ88yIL/custom-slices) with all valuable information and (ideally) examples linked in.

**Comment by davidpmccormick** [comment]
Done, although there's a `TODO:` for an example of the 'Text and image', which we currently only have on a Visual story behind a toggle.
