### ISSUE TITLE
Discovery: Automatic audio

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10020]
Explore something similar to what Wellcome has done where the text of a page is read in an audio player.
https://wellcome.org/news/what-link-between-climate-change-and-infectious-disease

They've apparently used [Amazon Polly](https://aws.amazon.com/polly/)

Try it out at first in articles.

**Comment by rcantin-w** [comment]
Back to Next as waiting for meeting next Thursday with a dotOrg team who's already integrated it

**Comment by rcantin-w** [comment]
Next steps:
- Determine which top 10 article should have a test player on them. Do we want to test it on some recent ones that have the potential to be more high profile as well? We also discussed these should probably be articles, not webcomics or In Pictures ( @jennpb )
- Determine where the audio player should be on the page. It can't be in the middle of the content, but top/bottom will probably have an impact. ( @DominiqueMarshall, any thoughts?)
- Determine which components should be made into [SSML](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#:~:text=SSML%20is%20a%20markup%20language,listed%20in%20Supported%20SSML%20Tags.). First gut feeling says just Text components (no quotes, images or videos). (Dev)
- Determine what we want to track for analytics and what the KPIs look like ( @jennpb and @taceybadgerbrook ?)
- Create the audio file for these 10 articles and display them on the page. (Dev)

**Comment by jennpb** [comment]
[Meeting notes](https://docs.google.com/document/d/1htcvjx-VukktZaqKYelITUDYByjhMX0mpxWm9sUEuP0/edit?usp=sharing)

Test brief to be filled in by team: https://docs.google.com/document/d/1Ikg-12FfuvE7ph2p2IGaMBVPmaGfpHN12FyG-ceFOLs/edit?usp=sharing

I propose using the top ten articles (GA4 12 Apr-12 July 2023): 

- A brief history of tattoos https://wellcomecollection.org/articles/W9m2QxcAAF8AFvE5
- History of condoms https://wellcomecollection.org/articles/W88vXBIAAOEyzwO_
- Shocking treatment https://wellcomecollection.org/articles/XhWjZhAAACUAOpV2
- Nymphomania https://wellcomecollection.org/articles/W_v8XxQAACgA_WKS
- Getting sexy with cinnamon https://wellcomecollection.org/articles/WilSbykAANoWFUhP
- Befriending heavy breathers https://wellcomecollection.org/articles/XqKkYxAAACMATUnN
- Side effects of lithium mining https://wellcomecollection.org/articles/YTdnPhIAACIAGuF3
- Drugs in Victorian Britain https://wellcomecollection.org/articles/W87wthIAACQizfap
- What is hysteria https://wellcomecollection.org/articles/W89GZBIAAN4yz1hQ 
- Race, religion and the Black Madonna https://wellcomecollection.org/articles/WpmW_yUAAKUUF6mV

**Comment by rcantin-w** [comment]
Thanks both!

Great stuff @jennpb ! How would we like to fill the brief, a quick session (a lot of things say "team agrees")? 
I've created two draft tickets in the Next column, but the tracking one will definitely depends on the brief.

**Comment by jennpb** [comment]
Team to work on test brief together early next week

**Comment by rcantin-w** [comment]
The [brief](https://docs.google.com/document/d/1Ikg-12FfuvE7ph2p2IGaMBVPmaGfpHN12FyG-ceFOLs/edit?usp=sharing) is being completed as we speak, a monitoring ticket was created ( #10045 ) and the dev work continues in #10020 so the Discovery can be considered complete.
