### ISSUE TITLE
Review Editorial Looker Studio dashboard

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10030]
The Data Studio Editorial dashboard has been rebuilt using Looker Studio and linked to the wellcomecollection [default] GA4 Property by Duga Digital. https://lookerstudio.google.com/u/0/reporting/8b09ce41-5256-42ee-846f-f6661f5f91fd/page/93HO

Before Duga move on to other work, I am going to be checking that all functionality has been replicated where possible. Any comments will be forwarded to @jennpb to pass on to Duga Digital.

**Comment by taceybadgerbrook** [comment]
## Here are changes for Duga Analytics: ##
  
Create a calculated field landing pageviews / pageviews for page 1
Create calculated field exits / pageviews for top of page 7, filtered by editorial (without /stories) and include in table.
Add calculated field exits / pageviews as metric to table on page 11

**Comment by taceybadgerbrook** [comment]
@dannybirchall Can we delete page 10 of the dashboard? It looks like it was supposed to help with analysis of specific stories but I could add this after Duga Digital have finished doing their work.

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/611c1d97-10f8-40de-9655-34fabf5328d8)

**Comment by jennpb** [comment]
> Create calculated field exits / pageviews for top of page 7, filtered by editorial (without /stories) and include in table.

@taceybadgerbrook Do you mean filtered by `/articles`?

**Comment by taceybadgerbrook** [comment]
@jennpb Yes. The filter is called, "editorial (without /stories)" but what it does is filter for those page urls that contain `/articles`.

**Comment by jennpb** [comment]
I've sent those changes to Duga Digital, cc'd Tacey in email.
