### ISSUE TITLE
Remove hardcoded audience text for youth events

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10040]
# What?

Events tagged with the audience `14 to 19 year-olds` have hardcoded text on the page. 

> For 14 to 19-year-olds
This activity is for people aged 14 to 19 years old and disabled people aged 14 to 25 years old.

The Content team would like to remove this.

Example: https://wellcomecollection.org/events/ZJ03hhAAACEAciDL
<img width="884" alt="Screenshot 2023-07-17 at 15 12 32" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/1446139/1d74b64e-3e05-4869-881d-a2cc2f3c1fcc">

# Why? 

- Information is also included in the body of the event.
- Information's placement below InfoBox makes it less visible anyway.

# Done when
-  Events with the 14-19 audience tag no longer shows the additional text below the InfoBox

**Comment by georgiaewhitney** [comment]
Confirmed changing section to prevent all hardcoded guidance here: [Slack](https://wellcome.slack.com/archives/C3N7J05TK/p1691496054206989)
