### ISSUE TITLE
Exhibition page resource links

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10041]
Relates to #9978 

Create content relationships in Prismic between Exhibitions and their related Exhibition Guides, Visual Stories, PDFs, so that they can be displayed on the exhibition page.

There should also be a text area where additional links can be added.

**Comment by gestchild** [comment]
I've outlined some thoughts about how we could do this. Would appreciate some input.

https://docs.google.com/document/d/1UAf-jU6ofBzkKGm6w0I3J8QwHfmLq0kZzQJECKL6cDE/edit?usp=sharing

**Comment by rcantin-w** [comment]
I can't leave comments on the doc itself but not sure which ones I'd leave anyway. Seems super logical, and am very up for the idea of clearing out the Resources section.

I think the solution for adding an image to the PDF links is indeed complicated - Dom seemed open to not have it, even though we could understand the why of it. Maybe it's time to ask again.

Very clear documentation, thank you!
