### ISSUE TITLE
Investigating Kibana definition of total unique works pages viewed

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10049]
**What is the problem to solve?**
Something in the code base appears to have changed on 31/1/23

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/4cf04766-4d6e-43ab-81fc-11c88add811d)

The definition of unique works pages viewed is page.name:work AND page.query.workId: *, cardinality by page.query.workId

**Comment by taceybadgerbrook** [comment]
The result is that Q2 stats are much lower than Q3 stats. It looks as though additional filtering needs to be in place from 2/3/23 and the numbers for the period 31/1/23 - 1/3/23 need to be estimated.

**Comment by taceybadgerbrook** [comment]
I've just checked the definition with data from the last 20 minutes and all seems in order.

We didn't get a big increase in users in early February: 
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/b849d7da-fcc7-40fd-8104-ed2d5a10cc1d)

**Comment by taceybadgerbrook** [comment]
It looks like the definition page.name:work AND page.query.workId:*, cardinality by page.query.workId is correct and numbers of unique works pages have indeed increased from early February.

@alexwlchan increased works page views looks like the product of spam. Can I use your spam detection code to grab the anonymousIds of spammers and filter them out of the stats?

**Comment by alexwlchan** [comment]
> Can I use your spam detection code to grab the anonymousIds of spammers and filter them out of the stats?

Sure. It looks at the `query` value, then applies a couple of cheap heuristics to decide if they're spam. The code is in TypeScript rather than Python so you might not be able to use it directly, but hopefully the comments are enough to give the general gist: https://github.com/wellcomecollection/wellcomecollection.org/blob/6018f5bdeecd136df04d331d866f7fad1b6a3b3e/catalogue/webapp/utils/spam-detector.ts#L89

Ping me if you have specific questions.

**Comment by taceybadgerbrook** [comment]
To find out if spam is resulting in works page views, Kibana shows 558 queries with ".com" made during the last 15 days:
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/f8815cb9-059a-4720-9ebb-dd05f15fe553)

Values of page.name related to these queries shows that counts of catalogue search, image search, global search and stories search result selected after global search have been affected by this kind of spam.

**Comment by taceybadgerbrook** [comment]
To figure out whether the stats for unique works pages or image modals viewed (used in KPI Tracker) are affected, the anonymousIds of the spammers need to be matched to records where `(page.name:work OR page.name:images)`

The spam filter definition is len("page.query.query")>25 and ord('a') 97. The second part of the code is unicode UTF8.

**Comment by taceybadgerbrook** [comment]
A quick investigation of the anonymousId of an example bot shows that bots potentially affect global search, collections search, stories search stats. 

This larger piece of analysis is now covered in https://github.com/wellcomecollection/wellcomecollection.org/issues/10056

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/4bd2c339-543d-4656-a005-d2f1967094fa)
