### ISSUE TITLE
Append all Eventbrite ticketing links with a campaign parameter

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10055]
# What?

Appending all Eventbrite ticketing links with a campaign parameter that indicates the booking has come from wellcomecollection.org.

The parameter is `?aff=WCWebsitelink` 

URLs will look like this: `[https://www.eventbrite.co.uk/e/relaxed-opening-of-milk-exhibition-tickets-597650788597?aff=WCWebsitelink`

We want to automate this so content editors, when adding the event link in the Prismic content type, don't need to remember to add this parameter each time.

# Why? 

To enable better use of Eventbrite analytics for the Marketing team

# Background  

Requested by Alice Evans

# Done when
- Parameter applied automatically to eventbrite links from wellcomecollection.org
- Editorial team to QA

**Comment by rcantin-w** [comment]
@jennpb : @georgiaewhitney and I are trying to investigate a bit more. From what we get so far, for each event, a tracking link will need to be created in Eventbrite called "WCWebsitelink" in order for it to be tracked, which I think confirms Daniela's comments. ([See documentation here](https://www.eventbrite.co.uk/help/en-gb/articles/835126/how-to-create-promotional-tracking-links/))


The numbers don't update in real time, so it's difficult to confirm some of the results of our tests. Some events that already have the affiliate in their Prismic link are marked as having had 0 views. We decided to wait until Monday and see if any of our testing had come through then, as it's flagged as taking a couple hours.

**Comment by jennpb** [comment]
@rcantin-w @georgiaewhitney On second thought, can we hold off on this until next week? If I have time/energy to follow up with the various other people to try to understand a bit more, it's probably better for everyone. Do you know if there's a way I can get a login to understand the EB interface myself?

**Comment by rcantin-w** [comment]
Oops I've just merged it. I'll revert.

I think you'll have to ask them for access, or have a little ride-a-long with Georgia?

**Comment by jennpb** [comment]
Moving to blocked until @jennpb can talk to Marketing about their requirements

**Comment by jennpb** [comment]
Emailed Alice E on 25/8

**Comment by jennpb** [comment]
Meeting booked for 18/9

**Comment by rcantin-w** [comment]
Now in production
