### ISSUE TITLE
Newsletter signup: integrate marketing consent with Dotdigital

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10071]
# What?

Add a marketing consent checkbox and integration with Dotdigital

Chris Reid may be a good person to talk to about how they did it for wellcome.org. Sally Larsen (Marketing) is also a good go-to for any Dotmailer questions. 

# Why? 

To align our newsletter signups with the rest of Wellcome, and to enable Wellcome Collection's email strategy

# Done when

- [ ] Data input integrated with Dotdigital
- [ ] Add checkbox UI and text to `NewsletterSignup` and `NewsletterPromo`: `Tick this box if you’re happy to receive other emails about Wellcome Collection, upcoming events and exhibitions and/or other relevant opportunities.`

# Background  

Jenn met with Sally Larsen, Rachel Collins and Phoebe Harkins in June 2023 to discuss some ideas for improving marketing email sign-ups.

To support the Wellcome Collection email strategy, they’d like to bring our data collection in line with Wellcome. This will involve first updating marketing consent and privacy information; later adding additional data fields. 

https://www.notion.so/wellcometrust/Newsletter-sign-up-Q1-2023-9395adca3b4e49489af8507a3af5a7c9

**Comment by rcantin-w** [comment]
Ran some tests with Sally just now and she's happy with it, so just waiting on [design review](https://github.com/wellcomecollection/wellcomecollection.org/issues/10070) (if needed!) and [code review](https://github.com/wellcomecollection/wellcomecollection.org/pull/10126) :)

**Comment by rcantin-w** [comment]
So the newsletter now has the Marketing checkbox on both forms, but the Promo I was unable to test locally and doesn't seem to take it into account (even when checked, it doesn't register in DotDigital, so these people wouldn't get marketing emails). I'm aiming to fix now.

**Comment by rcantin-w** [comment]
Now in prod! I've tested With/Without the marketing checkbox checked in both promo and sign-up and it checks out! I will let Sally know as well.
