### ISSUE TITLE
Visual stories: get feedback on Prismic content type with Content team

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10075]
# What?
Work with the Content team to get feedback on using the new Prismic content type, by getting them to create a visual story out of existing content. Can they successfully retrofit a visual story?

We want to ensure we're not building in complexity in Prismic resulting from the content model.

This needs to be usable by all content editors, including the photo editor.

# Done when
- [ ] Content team can create a visual story that meets the design intent

# Dependencies
#9974

**Comment by jennpb** [comment]
@davidpmccormick met with the content team to show them the new content type in Prismic. He's asked them to test it out and send feedback.

We'll want to chase this to ensure something happens before we have a follow-up meeting on 5 September.

**Comment by jennpb** [comment]
Asked Editorial team about their next steps 25/8. Not everyone is aware of the plan.

I summed up next steps in Slack https://wellcome.slack.com/archives/C054304EVL5/p1692960344970689

**Comment by rcantin-w** [comment]
Update from this morning's editorial standup; Lalita says she should have something ready for us this week.

**Comment by pollecuttn** [comment]
6 October: Editorial due to have text and images in Prismic today; still waiting on icons
Source: [Slack](https://wellcome.slack.com/archives/C054304EVL5/p1696584363156609)

**Comment by rcantin-w** [comment]
Moving back to in progress; we (David and I) met with Lalita on the 9th and went through her questions/suggestions. Next steps were:

Lalita:
- Regroup image-less content where it makes sense; there's a lot more of it than in our mockups/past content, so it looks naked as is/too spaced out with a divider in between each of them
- Use the Contact slice where relevant

@davidpmccormick :
- Investigate the slight extra padding showing up on one-liners
- Investigate the missing (i) icon on lower images

**Comment by davidpmccormick** [comment]
Extra padding: we weren't using our `spaced-text` system for this text. This has been fixed in ##10314

Missing TASL: we only display this information if at least one of the `title`, `copyrightHolder` or `sourceName` is present in the `Media details > Copyright` section of the Prismic media viewer ([https://wellcome.slack.com/archives/C3N7J05TK/p1697106061880449](url))
