### ISSUE TITLE
GA data request from a grantholder

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10073]
**What is the problem to solve?**

Request for usage data of The Hidden Persuaders series by a grantholder involved in its creation.

Data needed: Unique and non-unique users/visitors
Note that series was published in autumn 2018

URLs to use:

https://wellcomecollection.org/series/W1boEyYAACgAqwfw
 
https://wellcomecollection.org/articles/W1bjRCYAACcAqvKh (published 6/9/2018)
 
https://wellcomecollection.org/articles/W1bqBSYAACYAqxCK (published 13/9/2018)
 
https://wellcomecollection.org/articles/W1buxiYAACgAqyV9 (published 20/9/2018)
 
https://wellcomecollection.org/articles/W1bwkyYAACUAqy10 (published 27/9/2018)
 
https://wellcomecollection.org/articles/W1byZiYAACgAqzV7 (published 4/10/2018)
 
https://wellcomecollection.org/articles/W1b0QyYAACUAqz23 (published 11/10/2018)

**Background**

Jenn forwarded the email request to @taceybadgerbrook 

**Requested by:**
Jennifer Parkinson (Wellcome) via Katie T

**Comment by jennpb** [comment]
@taceybadgerbrook I'm sure you've done this one. Can you please add the findings and close the issue?

**Comment by taceybadgerbrook** [comment]
I wrote this in ticket #10099.
