### ISSUE TITLE
Viewer scroll bar is the height of the viewer at full screen width for individual pages

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#10097]
**What**

When looking at an individual page in the viewer the scroll bar is the height of the viewer so you don't get a sense of where you are. I only see this when my browser is full-width (1920 on my current screen).

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/b512aa92-09e0-4ccf-8218-e2dc68ea2dd0)

See https://wellcome.slack.com/archives/CUA669WHH/p1691066620912759

**Where**

e.g.
- book https://wellcomecollection.org/works/b4zcvkha/items
- archive https://wellcomecollection.org/works/a222zvge/items

I am seeing this on Chrome/Windows. 

I am not seeing this on Edge nor Firefox on Windows.

This anomaly is not replicated on Safari/Mac nor Chrome/Mac.

NB This is not a problem with thumbnails. When looking at thumbnails for an item the scroll bar is much shorter and does give an indication of where you are in the series of pages.

**Comment by davidpmccormick** [comment]
I've had a look using Chrome 115 and 116 on a PC running Windows 11 (via BrowserStack) and can't reproduce the bug. Could it be an extension you have installed that's doing something strange maybe?

**Comment by pollecuttn** [comment]
I switched off all my extensions and still had the scrollbar the entire height of the viewer.

I've also looked at my viewport size and I only see this kick in above 884 px width. Below that width the scrollbar works as expected when the height is 930px.

However, when the height and width are changed the dimensions at which the scrollbar is the full height of the viewer also changes, e.g. the problem returns when the height is 593px and the width is ~ 1686px. So it looks like some interaction between the dimensions (both height and width) of the viewport and the effect on the scrollbar.

**Comment by pollecuttn** [comment]
Switching off the toggles I had on* made no difference.

* API toolbar
Visual stories prototype
Text-to-speech Amazon Polly

**Comment by pollecuttn** [comment]
I also checked this on my personal laptop (Windows, but with Brave browser this time) and also saw the same issue.

**Comment by davidpmccormick** [comment]
Thanks for the detail – yes, I can replicate when I change screen dimensions in BrowserStack

**Comment by rcantin-w** [comment]
Now in production
