### ISSUE TITLE
Investigate removing spam results from GA4

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#10091]
(written by Raphaelle, if there are any questions)

@taceybadgerbrook requested some solution to be able to identify tracked actions that were made by what we believe to be bots/spam. [See Slack conversation about which solution to go for and what is possible](https://wellcome.slack.com/archives/CUA669WHH/p1690992368716539).

From the thread:

**The Big Four**: GA4, Segment, UA, GTM

**What we currently do:** If someone is on a page that contains a spammy query, we display a NoResult page (400), but we still send a “pageview” to Segment.

**What we think we can do instead:** We don’t know if a user is a bot until they behave like it. In our case, if they submit a spammy query. Once they try to do that, only then can we act. For example, if their journey looks like
1. Land on `/search`
2. Type in a spammy query
3. Submit the spammy query
4. Get directed to `/search?query=[spamQuery]`

Then the first page landing (1) counts as a page visit, as we don’t know at that stage that they are a bot. Only at (4) do we have the information we need.

Then we need to determine what behaviour we’d like:
1. Stop that one page view from being sent but keep The Big Four functioning.
2. Deactivate the Big Four (that’s something we’ll need it later on if people change their cookie/tracking preferences, but from experience it is faffy and not quick, they probably all have their different methods).
3. Send a pageview that has a property that indicates that it is a page view that is likely from a bot. We believe this is the fastest way and according to Harrison, would allow sessions to be tagged as spam as a whole. Tagging sessions as spam in Segment would allow us to calculate the overall proportion of spammy traffic, which would then allow us to normalise the traffic volumes measured by other services (eg GA4).

We went for 3. We'll have to work on 2 once we start work on "better cookies", but it's not necessary for this ticket.

**Comment by rcantin-w** [comment]
This is now live in production, just waiting for this conversation's conclusion to close https://wellcome.slack.com/archives/C3TQSF63C/p1691152590105009

**Comment by rcantin-w** [comment]
[It can be tracked here ](https://c783b93d8b0b4b11900b5793cb2a1865.eu-west-1.aws.found.io:9243/s/search/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(),filters:!(),index:'96f4208e-28c0-4418-9ace-04e9eaa2dcfb',interval:auto,query:(language:kuery,query:'properties.looksLikeSpam%20:%20true'),sort:!(!('@timestamp',desc)))), so I would close this ticket if agreed on with you @taceybadgerbrook ?

**Comment by taceybadgerbrook** [comment]
For some reason, I can't see the property. Could you cut and paste what you can see in Kibana?

**Comment by rcantin-w** [comment]
> Could you cut and paste what you can see in Kibana? 

Do you mean like a screenshot? Also this is for the last 15mins, which might just mean no spam has been sent in the last 15 minutes. [Here it is for the last 7 days](https://c783b93d8b0b4b11900b5793cb2a1865.eu-west-1.aws.found.io:9243/s/search/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d%2Fd,to:now))&_a=(columns:!(),filters:!(),index:'96f4208e-28c0-4418-9ace-04e9eaa2dcfb',interval:auto,query:(language:kuery,query:'properties.looksLikeSpam%20:%20true'),sort:!(!('@timestamp',desc))))

<img width="1698" alt="Screenshot 2023-08-07 at 12 32 01" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/7b653a10-3cd3-443e-a4b7-b360df79c88b">

**Comment by taceybadgerbrook** [comment]
So weird. When I search for properties, I get this:
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/c191cb58-43c2-4c5f-9929-b1ce6454d691)

**Comment by taceybadgerbrook** [comment]
But I can now filter for this (which I couldn't this morning)
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/2fbd7b08-5018-47e5-a062-7fb1e66b40bb)

**Comment by rcantin-w** [comment]
Not sure how it works, maybe there's not enough yet for it to be in the first list? 

As you can see it now, are we ok to close this ticket?

**Comment by taceybadgerbrook** [comment]
It was a hidden field. Sigh.

I think we're ok to close this now...
