### ISSUE TITLE
Does digitisation drive requesting?

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10113]
**What is the problem to solve?**
Library staff sometimes struggle with the requests workload. Online requesting makes it easier to request, increasing the workload. Maybe the workload can be reduced if users are requesting digitised items that can be viewed online.

**What stage of research is it? (discovery/general usability testing/post release)**
discovery

**What are the objectives?**
Identify the percentage of online requests for digitised items, both unique and non-unique.

**What research technique is required?**
Python, catalogue API

**Comment by jennpb** [comment]
For background discussion: https://wellcome.slack.com/archives/C3TQSF63C/p1676370458908619

**Comment by taceybadgerbrook** [comment]
Documentation/discussion doc: https://docs.google.com/document/d/1IvFwTcmUT0G74EKzjx-Z62i0nwjh34bWHth0k_BzCPs/edit

**Comment by taceybadgerbrook** [comment]
Output: would be useful to display as quarterly time series of percentage of digitised items of total non-unique requests.

**Comment by taceybadgerbrook** [comment]
A total of 3,354 items were requested during the period 1/3/23 - 31/7/23. Of those items, 1.6% were available online on 18/6/23.  

Some items were requested more than once. A total of 2,829 unique items were requested during the period 1/3/23 - 31/7/23. Of those items, 1.5% were available online.

**Comment by taceybadgerbrook** [comment]
There was no correspondence between the frequency of item requests and availability online. 

Here are the 10 most-requested items which are also available online:

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/9230f43b-0acc-4ea9-b7c0-414dc0d1d7c7)

Here are the 10 most-requested items which are not available online:

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/7af1b6c4-9ad4-4ac3-a289-803a4f2b9ac4)

**Comment by taceybadgerbrook** [comment]
The analysis does not show any evidence that digitisation encourages users to request physical items.

**Comment by taceybadgerbrook** [comment]
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/ad978415-9f53-4dca-a833-7dd6836aae01)


[The data and analysis can be found here.](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Q4%20202223/10113%20test%20request%20data.xlsx?d=w9de5dddcfdd745a18aa7e4755193e9ee&csf=1&web=1&e=h6rr8P)

**Comment by taceybadgerbrook** [comment]
@jennpb Analysis and next steps for comment in this doc:
https://docs.google.com/document/d/1Xb5-z1dgTQWisuda2baKoXBDspSD182h/edit

**Comment by taceybadgerbrook** [comment]
Production has been notified of items with pixelated areas.
Platform team has been notified of works with discrepancies between api and works pages on location.

Analysis to be picked up in 6 months in ticket #10193
