### ISSUE TITLE
Investigate using fetch links only and removing graph queries

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10129]
Most of the issues we get when there's a difference between the prod codebase and the prismic model is due to graphQuery references to specific fields (that may not exist anymore). 

For that reason, but also in the spirit of using one method of fetching instead of a few, we'd like to see if it's possible to just use fetchLinks.

Timebox discovery and apply if possible.

**Comment by pollecuttn** [comment]
From incident retro actions https://github.com/wellcomecollection/docs/blob/main/incident_retros/2023-06-26_wc.org_intermittently_available.md#actions

**Comment by rcantin-w** [comment]
I had a chat with David last week regarding this and because we need graphqueries for deep linking we can't just replace them with fetchLinks. 

Graphquery is used in `fetchArticles`, `fetchEvents`, and `fetchStoriesLanding`. It looks pretty minimalistic in the latter already, [I'm having a look at `fetchArticles` in another ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/10148) and I'll have a look at `fetchEvents` while I'm at it as well.

This ticket, however, is won't do.
