### ISSUE TITLE
Add to Prismic Deploy Type(s) script

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10128]
Timebox discovery for this, then make a PR if doable.

- Add to script: if your change contains queries is it in production? (Y/n)
- Create Prismic model change log page in Prismic that gets published with a change log and is the publish that’s needed when you change the model
- Modify tool to automatically update the Prismic model change log page

**Comment by LaurenFBaily** [comment]
Closing this as not been an issue since, if similar issues come up in the future we can readdress whether this work is necessary.
