### ISSUE TITLE
Text to speech options

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#10136]
# What

Not everyone uses a screenreader or other assistive tech to use the website, but they may benefit from content being read aloud\. <span data-preserve-white-space></span>

<p></p>

We could investigate text\-to\-speech widgets [https:\/\/www\.readspeaker\.com\/?ref=https%3A%2F%2Fwww\.boijmans\.nl%2Fen%2Fnews%2Fsurrealists\-to\-milan](https://www.readspeaker.com/?ref=https%3A%2F%2Fwww.boijmans.nl%2Fen%2Fnews%2Fsurrealists-to-milan)

<p></p>

<https://www.boijmans.nl/en/collection/in-depth/expressionism-1>

<p></p>

Q4 2023: Testing Amazon Polly <span data-preserve-white-space></span>

**Comment by jennpb** [comment]
https://docs.google.com/document/d/1Ikg-12FfuvE7ph2p2IGaMBVPmaGfpHN12FyG-ceFOLs/edit?usp=sharing

Decision:
Further experimentation needed. Will not implement at this time.
