### ISSUE TITLE
Event series: show all past events in the series

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10131]
# What?
On event series pages, we currently limit the number of past events to 3. 

I propose we remove that limit and show all past events in an event series on the event series page.

The event series page currently does not show any onward journeys, so a long list of past events won't get in the way of casual users; and dedicated users will have access to all of the information they need.

example event series
https://wellcomecollection.org/event-series/ZJsHDhAAACMAauzb
https://wellcomecollection.org/event-series/WlYUDCQAACQAWcdt

# Why? 
If we show all past events on an event series, it'll be a better experience for users because:
- there's only one place to go to see all the events (as opposed to clicking through to an `all past events in this series` index page, or trying to search for more)
- where there are more past events that are available online, users can access them from a single place
- it provides a better archive of past events that can be web archived and referred to in the future

# Background  
https://wellcome.slack.com/archives/C8X9YKM5X/p1692001935787379

# Done when
-  All event series display their full list of past events
- 20 past events shown per page; paginate when >20

**Comment by rcantin-w** [comment]
I think it'd be worth ensuring there is pagination if there's over X events? (à la Series https://wellcomecollection.org/series/WleP3iQAACUAYEoN)

**Comment by jennpb** [comment]
Ok, that works for me. I don't know what the history behind that decision to paginate is (as opposed to a 'show more' functionality).

**Comment by rcantin-w** [comment]
I'm guessing a simple "We already have a pagination but not a show more", [here's the PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/8612).

We have a show more but [just in transcripts AFAIK](https://wellcomecollection.org/articles/XzQWoBEAACMAyEMT) (which seems to be the only usage of the "Discussion" Slice).

**Comment by davidpmccormick** [comment]
I'm not sure how the pagination would look on a page like this. Would we continue to show the featured image, intro text and 'coming up' events on page 2 and beyond?

Do we have any example event series with more than 20 past events (i.e. is this something we need to solve now?)

**Comment by davidpmccormick** [comment]
Done in #10158
