### ISSUE TITLE
Create listing of historic data issues

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10142]
GA4 does not support annotations unlike UA. To help interpret historic data, entries in UA that do not appear in [this listing](https://github.com/wellcomecollection/wellcomecollection.org/wiki/Key-events-or-changes-on-wc.org) need to be copied to a similarly shared resource.

**Comment by taceybadgerbrook** [comment]
[New page in wiki.](https://github.com/wellcomecollection/wellcomecollection.org/wiki/Key-changes-in-wc.org-Segment-data)

**Comment by taceybadgerbrook** [comment]
@davidpmccormick I've just published changes to the GTM container so that server response time can be calculated with GA4. 

[Here are the instructions wellcome.org recommend following. ](https://www.thyngster.com/performance-timing-tracking-with-google-analytics-4)

**Comment by jennpb** [comment]
Is this useful? https://docs.google.com/document/d/1y7KDjXBahNdyKgbjuoxv5WUaw2uHLR5DmgR1iMxWB3E/edit

I note that you're only tracking Segment issues here, rather than anything that might also happen in GA4. Is there a reason for limiting it?

**Comment by taceybadgerbrook** [comment]
I'll add the spam filter to the list, thanks.

I haven't mentioned changes to GA4 because the [website wiki](https://github.com/wellcomecollection/wellcomecollection.org/wiki/Key-events-or-changes-on-wc.org) is sufficient to understand the story behind changes in GA4 metrics (eg behaviour arising from the introduction of global search.)

My main reason for documenting changes in Segment is being able to keep search/works view/item view definitions up to date. While switching to using GA4 and counting based on url structure should make this obsolete, I will still need a record of the Segment changes when I do Python analysis.

**Comment by taceybadgerbrook** [comment]
@jennpb reading do you mean things like changes to the way GA4 has been set up? eg filtering out staging and prismic preview traffic from the main GA4 property? That seems like a sensible thing to add along with custom dimensions/metrics created using GTM.

**Comment by jennpb** [comment]
No, I wasn't thinking of this as documenting the details of implementation, but rather what's gone wrong in the data over time and what was done to resolve it. Wherever we might have put an annotation in the old GA (e.g. 'data outage due to codebase change from Date to Date'. That's why I was suggesting a more holistic approach, rather than a tool-by-tool approach.

**Comment by taceybadgerbrook** [comment]
@jennpb I've moved entries affecting stats we will get from GA4 into the wc.org wiki (eg total user numbers and collections user numbers now reported with deduction for spammers) but kept the Segment wiki because it helps me when I get asked to produce historic data in Kibana.

**Comment by jennpb** [comment]
In summary, data issues are being recorded in these two lists:

https://github.com/wellcomecollection/wellcomecollection.org/wiki/Key-events-or-changes-on-wc.org
https://github.com/wellcomecollection/wellcomecollection.org/wiki/Key-changes-in-wc.org-Segment-data
