### ISSUE TITLE
Create Kibana dashboard to monitor use of 3rd party digitised content

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10140]
Wellcomecollection.org hosts quite a lot of 3rd party material, identifiable by dig codes but how often is this material viewed or the works pages accessed? Is this best use of resources?

**Comment by taceybadgerbrook** [comment]
[Here is a link to a very basic interactive dashboard.
]([url](https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/9e1211d0-5172-11ee-8f60-e5a3c28c72b6?_g=(refreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1d%2Cto%3Anow))))

**Comment by jennpb** [comment]
@taceybadgerbrook I think this is a good time for me to step away and you do some investigation to see what Collections people might find helpful. I can suggest a few people for you to talk to.

And just for extra clarity, what you are currently showing on that dashboard: is it Works pages viewed, or digitised items viewed? The key says 'total works viewed'.

**Comment by taceybadgerbrook** [comment]
@jennpb thanks for the list of people and pointers for investigation.

Re the dashboard, I tried to get items viewed as well as works but it's the works page views that have the dig code data. Before I attempt anything more sophisticated, I wanted to be sure users really needed item page views, too.
