### ISSUE TITLE
Design improvement: how we show/hide secondary content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10143]
# What?

Here's the situation: we currently have two ways to expose/hide secondary content:
- [discussion component](https://cardigan.wellcomecollection.org/?path=/story/components-discussion--basic) : primarily used on /articles. Original purpose was to hide longer pieces of texts formatted as transcripts
- [explanatory text](https://cardigan.wellcomecollection.org/?path=/story/components-explanatorytext--basic) : used on /works pages to hide/expose extra licensing and usage information.

Lalita raised the issue that the current implementation of the `discussion` component on articles makes for a poor experience when there are multiple transcripts, as is the case in an article that's about to be published that has 3 audio player embeds.

## How might we approach iterating on this problem?

- are the two existing components close enough in purpose to combine into one, or to have one component but multiple ways to size it depending on its context?
- what's the optimal experience for audio player + transcript?
- is there any semantic markup in either of our two existing solutions that need to be respected? (i.e. Does 'Discussion' have any semantic structure for SEO purposes?)

## Assumptions

- Audio transcripts should be available with the audio player
- We still need a way to show/hide content

# Background  
https://wellcome.slack.com/archives/C8X9YKM5X/p1692101105813539

**Comment by DominiqueMarshall** [comment]
> are the two existing components close enough in purpose to combine into one, or to have one component but multiple ways to size it depending on its context?

While the two components are close in purpose, I think the pages they feature on (and how often they're used) mean it's probably better to have one component with variant styles.

> what's the optimal experience for audio player + transcript?

I'm surprised to see that a lot of websites **don't** have transcripts available with any embedded audio! My personal opinion is that if there are multiple audio files within a page, it would be ideal to have the transcript next to the relevant audio - which I've explored in the designs below:

----

### Article pages + audio
As a variation to our current `discussion component`, I've adapted it to be more suitable for multiple audio files within a single article by reducing the size and design.

This structure means that the transcript component doesn't become too overpowering (like it would if we used the current discussion component multiple times), and it also doesn't get missed visually, which it might if it was just a text link.


**Component closed:** https://zpl.io/noGY66l



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/60890140/161ad056-2968-4133-ac1b-f9c9d7c332fc)





**Component open:** https://zpl.io/mDgy88K




![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/60890140/2b6e8f97-bde4-4d72-b221-5b4d43a997e6)



### Works page - Can I use this component

Here's an example of how the above component would look on the Works page. I'm not convinced it works as well here:



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/60890140/6e6fb08d-560e-4d3e-98ba-80699e0f648e)


Instead, I propose a small redesign to match the transcript component (same expand/close icons with bold text, minus the outline box). I've also tweaked the copy of the link based on a suggestion made from the accessibility audit: https://zpl.io/8lOPEE6



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/60890140/777062c8-3c2d-4eef-863e-523c0710d1ba)




@jennpb @rcantin-w @gestchild @davidpmccormick open to feedback on the above!

**Comment by jennpb** [comment]
I've added a few comments to the Zeplin files relating to use of colour.

Just to ensure that this component has flexibility and consistency wherever it's used, just a few things to consider:

It would be good to ensure this component can work with the audio player wherever we put it, for example:
- Pages with many audio players, like [exhibition guides](https://wellcomecollection.org/guides/exhibitions/ZD01LBQAAC4ZiY95/audio-without-descriptions) 
- [Works with audio ](https://wellcomecollection.org/works/u9spzdvy)


Is the idea that the two examples (the slightly tweaked `ExplanatoryText` component and the `Discussion` component) become one component with two expressions (large with borders; small without borders)?

And if the above is true, for the sake of consistency, would the +/- icon still be in different places or should the placement be consistent across both versions?

Last thing - while I agree that the 'Can I use this?' label needs changing, I don't think adding the research context is quite right. Some people don't use this stuff for research purposes - they might use it to illustrate a book or a funny blog post. I can anticipate there'd be more questions about whether they could use something for e.g. printing on a poster, especially with image researchers. We can iterate the label though!

**Comment by rcantin-w** [comment]
It might not be necessary, but, if we're making this available for audio players, should we also make it a thing in Embeds (which can be a Soundcloud audio player, for example, I think our podcasts are on it?)?

For Jenn's
> I've added a few comments to the Zeplin files relating to use of colour.
I couldn't see those, but I did wonder about the difference in background colour from when Read the transcript is closed vs open?

Reckon dev-wise, it's just having a new no-repeat Text field in the relevant Slices, I don't see it being a challenge. Maybe just extra a11y considerations that should be very doable.

**Comment by DominiqueMarshall** [comment]
Links to updated designs below. After discussing the designs with Jenn, I've amended the transcript component to match the 'Can I use this' component so they both have the + icon before the text link.

**Article page (transcript closed):** https://zpl.io/mDg9rY9
**Article page (transcript open):** https://zpl.io/7wq5n6W

**Audio works page:** https://zpl.io/8lOpm6w
Update to the "Can I use this" component - change of the label to 'Reuse and licencing', and also moving the Licence information currently above it back into that dropdown: https://zpl.io/noGdZ0Y

This new style component should fit quite well in the above spots on the website, but where it gets tricky will be the exhibition audio guides. Example of the current page design with the transcript component: https://zpl.io/09dRG7E

I recommend that this page be redesigned to move away from the three columns to accommodate the transcripts in a better way, otherwise it could end up feeling quite clunky very quickly, especially on smaller laptops. Here's an example of what the page could look like if we switched it to a singular column list: https://zpl.io/5EnGdLj

On Podcast pages, if we want to move away from the current `discussion` component, I'd recommend removing the button entirely and just having the transcript fully accessible on the page like an article, keeping the background to separate the transcript from the rest of the page content.

@davidpmccormick @rcantin-w @gestchild I'll leave to you to decide whether to deprecate the current discussion component and move to this one everywhere on the website!

**Comment by DominiqueMarshall** [comment]
Update 5 Sept: Confirmed next steps with Gareth and Jenn:

- Switch the discussion component to the new design (except on Podcast pages where the text will be pulled out from the component, and treated like a normal article page).

- Update the "Can I use this" label to "Reuse and licencing", bringing the licence information back into that dropdown component.

- Leave the new discussion component off the exhibition guide audio pages for now, as that page structure needs more work to accommodate full transcripts.

**Comment by jennpb** [comment]
#10182 
#10183 
#10184
