### ISSUE TITLE
Styling required: Stories section in /search

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10151]
I noticed some flukes yesterday on the `/search` page and have double checked with Dom, and these should be changed:
1. The "Stories" heading has extra padding on the left in desktop
2. The cards' label positioning should match the ones in `/articles` 

In search: 
<img width="1147" alt="Screenshot 2023-08-17 at 15 32 14" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/ab5fdb34-a676-42d9-96fb-f976e3190979">
<img width="527" alt="Screenshot 2023-08-17 at 15 32 06" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/5ba71b9f-860f-4d1d-92a8-99fc6700e10b">

----

In articles:
<img width="644" alt="Screenshot 2023-08-18 at 10 25 00" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/a7b48a8f-4424-4818-bcb9-f2cee0cc825f">

<img width="634" alt="Screenshot 2023-08-18 at 10 25 05" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/e753dc48-355c-494e-81aa-c045650d824c">

**Comment by georgiaewhitney** [comment]
I've also found "Comic" has an overhang on the left in `/search/stories` in mobile/responsive view, so will fix that. 



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/81175151/74e361f3-e75e-4db7-b68f-87d3759c21f8)

**Comment by rcantin-w** [comment]
Very eagle eyed of you! 🙌 

Looks like it's due to the image format, with comic images being square, so feel free to treat it separately if it becomes a blocker for this ticket. 
I'm not sure if we can fix or if rendered that way by Prismic 🤔 
![262948430-74e361f3-e75e-4db7-b68f-87d3759c21f8](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/5e1d140b-d7c9-4253-9e66-9a842c739951)
<img width="1463" alt="Screenshot 2023-08-24 at 11 53 49" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/ba8cfa72-da56-4558-bab2-0fa8bddf7cc0">

**Comment by georgiaewhitney** [comment]
Ahh I see! Good shout - I'll tackle the others first and see if it blocks 🤞

**Comment by georgiaewhitney** [comment]
Done with #10171
