### ISSUE TITLE
Only send reproducible errors to the #wc-platform-alerts channel

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#10159]
We have a Lambda that listens for 5xx errors in the CloudFront logs, and posts a list of them to our shared alerting channel (see [send_slack_alert_for_5xx_errors.js](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/cache/send_slack_alert_for_5xx_errors.js)).

Not all the errors detected in our CloudFront logs are reproducible – we see a fair proportion of 5xx errors that seem to be some sort of timeout, e.g. an HTTP 504. This means the Slack alert says "there was an error at this URL", but we can't reproduce it.

It would be useful to introduce some sort of automated check about whether a URL is erroring in a reproducible way, and only send reproducibly failing URLs to the alerts channel (or to label errors which can't be reproduced).

**Implementation note:** to check this, the Lambda would have to re-request all the failing URLs. We'd need to make sure those requests were marked in some way and could be filtered out – otherwise a reproducible failing URL would get the Lambda stuck in an infinite loop of reporting the same failing URL over and over.

**Comment by kenoir** [comment]
Closing in favour of https://github.com/wellcomecollection/platform-infrastructure/issues/436
