### ISSUE TITLE
Get rid of the catalogue app from Terraform

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#10168]
Now the content/catalogue app are merged, we should be able to do away with the catalogue app infrastructure.

**Comment by alexwlchan** [comment]
I had an initial attempt at this in #10169, but it got rolled back when we had the search outages. I don't think it was related to those issues, but it was at the same time and we thought it might be the cause.

I don't want to try finishing this before I leave, so instead some notes for whoever picks this up next:

I think that PR has all the bits you need to remove (Buildkite, ECS services, ECR repos, load balancer rules, etc.). However, doing it all in one go was probably a mistake – it made it quite annoying to roll back. When I deleted the ECR repo, I deleted all the app images.

If I was doing this again, I'd start by removing the load balancer rules from the Terraform. Leave it a few days, make sure you don't need to roll back, and only then move on to removing the rest of the infrastructure.

**Comment by kenoir** [comment]
Not quite done, keeping open to track work.
