### ISSUE TITLE
Remove AWS Polly experiment

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10172]
# What?

Remove Polly audio player and toggle

# Why? 

Experiment concluded - won't implement as is now. https://docs.google.com/document/d/1Ikg-12FfuvE7ph2p2IGaMBVPmaGfpHN12FyG-ceFOLs/edit#heading=h.j7wb5f6nu37i

**Comment by rcantin-w** [comment]
they're gone, as is the toggle @jennpb
