### ISSUE TITLE
Implement explanatoryText component alongside multimedia players in Prismic

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10183]
# What?

Add `explanatoryText` slice in Prismic associated with `AudioPlayer` and `Embed`

Each instance of the `AudioPlayer` and `Embed` should allow for the addition of `explanatoryText` to enable viewing of an audio transcript

Dom's designs:

Article page (transcript closed): https://zpl.io/mDg9rY9
Article page (transcript open): https://zpl.io/7wq5n6W

https://github.com/wellcomecollection/wellcomecollection.org/issues/10143#issuecomment-1698989866

# Why? 
To enable Editorial to add a text transcript to an embedded AudioPlayer so stories can be even more accessible!

This has embedded audio: https://wellcomecollection.org/articles/ZPeIvxEAACYAs2sg
And this has embedded Soundcloud: https://wellcomecollection.org/articles/XzpP-xEAACQA46ss (uses `Discussion` component for transcript)

# Background  
https://github.com/wellcomecollection/wellcomecollection.org/issues/10143

# Done when
-  [ ] Editors can add some text to pair with an embedded audio or video
-  [ ] Editors get a demo of how it works

**Comment by rcantin-w** [comment]
Quick Q should this also be added to Embed as it can contain an audio player (Soundcloud)?

**Comment by jennpb** [comment]
I don't think it needs to be as we're now unlikely to use Soundcloud embeds. No further podcasts planned for the future.

**Comment by rcantin-w** [comment]
Edited the description to include Embed as discussed after requested by Editorial

**Comment by rcantin-w** [comment]
Now available and [exposed to Editorial](https://wellcome.slack.com/archives/C3N7J05TK/p1695223037146799)
