### ISSUE TITLE
Update design of explanatoryText component

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10182]
# What

Implement design changes per @DominiqueMarshall's specs

Article page (transcript closed): https://zpl.io/mDg9rY9
Article page (transcript open): https://zpl.io/7wq5n6W

Also update the version of this that exists in [Exhibition Guides](https://wellcome.slack.com/archives/C3N7J05TK/p1694683156282819) so it's aligned.

# Why
- New design will enable stacking if needed on /works pages
- Modified to enable use with audio player

## Questions
- How tricky would it be to rename this component? `explanatoryText` is too specific; this component should be used generally to show/hide secondary content that supports another component, for example: transcript supporting the audio player; or licensing information supporting a digitised work. This is the time to do it!

# Background

https://github.com/wellcomecollection/wellcomecollection.org/issues/10143#issuecomment-1698989866

# Done when
- [x] Discuss potential naming change with @jennpb 
- [x] Design updated in Cardigan
- [x] Design implemented on existing instances (`/works` 'Can I use this?')
- [x] Design aligned in Exhibition Guides

Relates to https://github.com/wellcomecollection/wellcomecollection.org/issues/10143

**Comment by rcantin-w** [comment]
Edited description to include alignment with Exhibition Guide's collapsed transcripts

**Comment by rcantin-w** [comment]
The new version has a different CTA based on if the content is visible or not.

1. @jennpb What do we want to replace "Can I use with" in both cases?
2. Would you like to change `explanatoryText` to `collapsedContent`?

**Comment by rcantin-w** [comment]
For (2), we've agreed on `collapsibleContent`

**Comment by rcantin-w** [comment]
Changing it on Exhibition Guides to align means changing how it worked a little bit. 

## Before

The first paragraph would be visible and the button would follow the bottom of the text (so after scrolling to the bottom you could chose to hide it again)

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/36bb9b3d-3454-4df5-9e6a-2de6f3de5a40)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/b20b66e0-4354-47c2-a5ee-42811cda3339)

## After

I decided to keep the title visible to make it clearer, but as the button stays on _top_ of the copy itself, I didn't keep the first paragraph and bundled it all together inside the collapsible content.

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/a1503b3f-e153-4179-bbb4-e80de43f165f)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/eb42800a-592f-4e14-bd07-b95fcaf2ac59)

**Comment by jennpb** [comment]
That looks like a good solution @rcantin-w

**Comment by rcantin-w** [comment]
Now in prod
