### ISSUE TITLE
Making the most of Concepts pages

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10195]
**What is the problem to solve?**
Now that we've built them, how can we make the most of these pages?

**What are the objectives?**
Look at traffic sources to pages with format “/concepts/”. If social, would mean editorial might find it worthwhile to tag more stories for concepts. If direct, could indicate these users are researchers.

If the analysis is not conclusive, try using the top concept pages identified in #10194 .

**What research technique is required?**
GA4

**Comment by LaurenFBaily** [comment]
Moving to Icebox as this work is dependent on Concepts being linked to from other pages (aside from Works pages)

**Comment by LaurenFBaily** [comment]
Closing as by the time the lead digital analyst is in post this will need re-looking at.
