### ISSUE TITLE
Update `humanReadableText` for digital content licences

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10208]
# What?

1. Reformat the `humanReadableText` for all of the licences from the catalogue API in https://github.com/wellcomecollection/wellcomecollection.org/blob/2f57526efd2cdd51519fb7434ef4ffae1e21f897/common/utils/licenses.tsx

This should display on the front-end as:

**{Licence label} ({Licence label short})**
{humanReadable text}. Read more about this license`<Licence link>`

for example:

**Creative Commons Attribution (CC BY 4.0)**
You can use this work for any purpose, including commercial uses, without restriction under copyright law. You should also provide attribution to the original work, source and licence. `<a href=”https://creativecommons.org/licenses/by/4.0”>`Read more about this licence`</a>` 

2. Add `humanReadableText` for licences that don't have them (in same file)

Add information for the following licences:
- `cc-by-nd`
- `cc-by-sa`
- `cc-by-nc-sa`
- `ogl`
- `opl`
- `inc`

All texts are [in this sheet in column F](https://docs.google.com/spreadsheets/d/1IKHmOE_zX6Qi0M_Ys5QMx7QKSJfk31OB9a13a0TF-Yg/edit?usp=sharing)

NOTE: `In copyright` follows a slightly different format with the addition of a second link.

# Why? 

Redesigning how we display the licence information relating to digitised works to better accommodate new licences and functionality

# Background 
part of #10134 

# Done when
-  [x] licenses.tsx reviewed by @jennpb 
-  [ ] format of text inside `explanatoryText` component on /works page is presented in new format.

**Comment by rcantin-w** [comment]
Now in prod and tests all pass
