### ISSUE TITLE
Reformat how credit information is presented on works page

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10223]
# What?

Credit information on the works page is currently confusing and potentially misleading.

1. These should be formatted as: `{Title}. {Credit}. {Licence label}. Source: {Attribution}.` - NOTE: not everything has an explicit {Credit}. Devs need to decide from where to grab this data.
2. We should offer the option to Copy the credit line (similar to copyURL)
3. When copying the credit line, the URL for the works page should be included.

To illustrate:

On works page:

> Genetics in the 20th century : essays on the progress of genetics during its first 50 years / edited for the Genetics Society of America by L.C. Dunn. Public Domain Mark. Source: Wellcome Collection.

When copied:

> Genetics in the 20th century : essays on the progress of genetics during its first 50 years / edited for the Genetics Society of America by L.C. Dunn. Public Domain Mark. Source: Wellcome Collection. https://wellcomecollection.org/works/pe22d89x

## Dependencies
Bug https://github.com/wellcomecollection/wellcomecollection.org/issues/10221

# Why? 

To ensure that all users have the most accurate information we can give, so they can provide credit appropriately

# Background

Reworked licence and credit information https://docs.google.com/document/d/1haxvwYphd5dF3dplmTmyN7H5vn7ovJohbi0RHU6AmD0/edit?usp=sharing

**Comment by rcantin-w** [comment]
To confirm: we were removing the URL on the Licence label, is that correct?

**Comment by jennpb** [comment]
Yes, and that's because we've got the licence link in the humanReadableText so no need to duplicate it

**Comment by rcantin-w** [comment]
Another question: I might misunderstand what is Credit and what is Attribution. Currently in [this work](https://wellcomecollection.org/works/b5kqccbb), what I have for Credit _is_ "Wellcome Collection". 


```
  // iiif-image locations have credit info.
  // iiif-presentation locations don't have credit info., so we fall back to the data in the manifest
  const credit = digitalLocation?.credit || iiifCredit;
```

In your example, that looks like it's "Attribution". What would the difference be and where should I place this information?

**Comment by rcantin-w** [comment]
In the current Copy URL component there is a GA event tracking clicks:

```
 trackGaEvent({
       category: 'CopyURL',
       action: 'copy url to clipboard',
       label: id,
     });
```

As I have to modify it/create a new component for copying regular copy, do we want to add tracking there as well?

cc @taceybadgerbrook

**Comment by taceybadgerbrook** [comment]
@jennpb @rcantin-w, references in the code to GA event category, action and label were used by UA and are now obsolete. 

However, there is an event called, "copy_url," tracks when a user clicks this
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/a1256ca3-0218-4088-a6be-7f0feeab0642)

This is triggered when CSS selector matches [data-gtm-trigger="copy_url"], [data-gtm-trigger="copy_url"] * . 

I would love to be able to track when a user copies the credit information. If you let me know what the CSS selector is, I can do the tagging in GTM.

**Comment by rcantin-w** [comment]
[After a conversation with Ashley, Jamie and Jenn](https://wellcome.slack.com/archives/C02ANCYL90E/p1695639321740769) where we determined that credit vs attribution was a bit more complicated to untangle than we'd like, we're putting this under a toggle for now so we can compare various works and images more easily.

**Comment by jennpb** [comment]
We are unable to create an ideal credit line as intended.
 
- For third party material, the `attribution and usage` label includes the `location-of-original` data rather than the attributable source; this means we get text that says "This material has been provided by The Royal College of Surgeons of England. The original may be consulted at The Royal College of Surgeons of England."
- However, material that we've digitised says 'Wellcome Collection'. 
- Credits aren't reliably available. 

When presenting a credit line, we should be able to reliably include:
- {title}
- {credit} - this information is not consistently available. Currently Miro images that have not been reingested are the only digital assets that include an explicit credit line.
- {source} - where source is Wellcome Collection, as that's where the digital item was found
- {licence}

**Comment by rcantin-w** [comment]
- So I moved Licence to end of the sentence, it's the only change I can see from our current instance.
- Credit displays if there is a IIIF Presentation or IIIF Image credit field.
- Attribution displays if there is an "Attribution and usage" label on a IIIF Presentation.
- Should we now remove the "Licence" section above "Licence and re-use"?

If we're happy with this, I'll of course remove the section names.



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/a9db27dd-5a21-4f17-b994-a6718f3fe056)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/19d4aed0-3974-4401-ac6a-4dc6ae382121)

**Comment by jennpb** [comment]
> Credit displays if there is a IIIF Presentation or IIIF Image credit field.

Yes, but if there's a credit, it should not be part of `Source:`

I would expect this example to be formatted as:

`DNA analysis. Paul Griggs. Source: Wellcome Collection. Attribution 4.0 International (CC BY 4.0).`

> Should we now remove the "Licence" section above "Licence and re-use"?

Yes

**Comment by rcantin-w** [comment]
@jennpb the discussed changes are in prod: https://wellcomecollection.org/works/a227dajt

**Comment by jennpb** [comment]
For the record, this was implemented as:

`{Title}. {Credit}. Source: Wellcome Collection. {Licence label}`
AND when item is from a third party, a separate section for Provider which is taken from `Attribution and usage`

**Comment by jennpb** [comment]
@rcantin-w This is fine to remove from toggle! 🛳

**Comment by rcantin-w** [comment]
In prod, from behind the toggle
