### ISSUE TITLE
Add 'Location of original' variable text to explanatoryText block

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10220]
# What?

Some digitised material have information relating to the Location of the Original. This should be added to the `explanatoryText` block for all items with `locationType` = `DigitalLocation` AND a `location-of-original` note, for example: https://api.wellcomecollection.org/catalogue/v2/works/a26jankb?include=identifiers%2Cimages%2Citems%2Csubjects%2Cgenres%2Ccontributors%2Cproduction%2Cnotes
This information should appear under a heading `Provider`

This will appear in a list of sections within the `explanatoryText` component:

- Licence
- Credit this digital item
- Provider

# Why? 
So users understand that Wellcome Collection does not hold the original physical copy, and users know where else they can find it.

# Background  

Tidying up the credit and licence information on works pages.

Reworkings section by section: https://docs.google.com/document/d/1haxvwYphd5dF3dplmTmyN7H5vn7ovJohbi0RHU6AmD0/edit?usp=sharing

**Comment by jennpb** [comment]
Option 1: If we keep it at the bottom under 'Where to find it', it would make it more apparent to people who are looking to request the physical item that it doesn't live at Wellcome Collection.

Option 2: On the other hand, if we move it into the 'Licence and re-use' section, it's more apparent that it's the digital copy that is from that other place.

Having it in both places seems heavy-handed.

Looking at it in that light, I now think Option 1 (current status) is the right thing.

Let's keep as is and close this.

**Comment by rcantin-w** [comment]
@jennpb did you mean to reopen?

**Comment by jennpb** [comment]
Yes - and just to confirm our decision:

- keep `Location of original` at bottom of /works page
- also add it to the 'Licence and re-use' section, under the heading 'Provider'

**Comment by rcantin-w** [comment]
Added it and it's in prod: https://wellcomecollection.org/works/a227dajt

**Comment by jennpb** [comment]
@rcantin-w 🛳 🚀

**Comment by rcantin-w** [comment]
In prod, from behind the toggle
