### ISSUE TITLE
Update labels and headings within explanatoryText component

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10224]
# What?
Update labels and headings within explanatoryText component 

**1. Change the label on the `explanatoryText` component** 
Currently it is labelled 'Can I use this?'.

Change to: Licence and re-use

**2. Create discrete sections within the component**

Add appropriate heading levels for:
- Licence
- Credit this digital item
- Provider (note: this will only be present when there is `location-of-original` data to populate the section - see #10220) 

# Why? 

- Create an information hierarchy
- Improve information scent on a works page

# Background  

Reworked licence and credit information https://docs.google.com/document/d/1haxvwYphd5dF3dplmTmyN7H5vn7ovJohbi0RHU6AmD0/edit?usp=sharing

# Done when
-  [ ] Any design improvements from Jason? 
-  [ ] Headings/bold styling as described above

**Comment by rcantin-w** [comment]
Is this ticket to style the section once we've got all the content in? We've now decided to remove **Provider** I believe.

**Comment by jennpb** [comment]
Yes indeed!

**Comment by j-jaworski** [comment]
If you're clear how this needs to be implemented, I am happy to wait until you have something to share.

**Comment by rcantin-w** [comment]
Now in prod
