### ISSUE TITLE
Update licence and credit information in viewer side panel

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#10226]
# What?

Bring the item viewer in line with works page.

**1. Change label** 

Change from 'Licence and credit' to 'Licence and re-use'

**2. Change order of information and format**

This should be like this:

**Licence**: {Licence label}
**Credit**: {Title}. {Credit}. Source: {Wellcome Collection} {URL}.
**Provider**: {location-of-original} 

# Why? 

To bring this in line with the licence and credit information on works pages.

# Background  

The proposed changes here acknowledge that there will be duplication between the item viewer and the works page. The reason for this is because a user might only ever encounter the digitised item page (direct links, organic search). In the context of using the digital item, users should have access to the information that tells them what they can do with the content.

**Comment by rcantin-w** [comment]
@jennpb reckon this is also affected by the conversations we've had today? Or is "Source: {Wellcome Collection} {URL}."'s "Wellcome Collection" part static content?

**Comment by jennpb** [comment]
@rcantin-w Updated the requirements in the description. This should use the same data and logic as on the works page, but slightly different format to fit the context.

**Comment by rcantin-w** [comment]
To triple check; 

> Credit: {Title}. {Credit}. Source: {Wellcome Collection} {URL}.

1. "Wellcome Collection" is hard coded?
2. Is the URL just a link on "Wellcome Collection" or is it just written as?

**Comment by jennpb** [comment]
Thank you for triple-checking!

> "Wellcome Collection" is hard coded?
Yes

> Is the URL just a link on "Wellcome Collection" or is it just written as?

Make it a link on Wellcome Collection, please.

**Comment by rcantin-w** [comment]
Now in prod
