### ISSUE TITLE
Visual Stories urls

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10275]
The url of visual stories is currently /visual-stories/{id}

This was only meant to be temporary whilst they were under development.

The final url structure has now been decided and needs to be implemented.

Details can be found here:
https://docs.google.com/document/d/17xPEfOFAFzBeFopkKUAWUTyBo89lPzoSSV5o_4Ri8NQ/edit#heading=h.oak9n480cbuy

**Comment by rcantin-w** [comment]
in prod
