### ISSUE TITLE
Review exceptional opening hours behaviour (UX?)

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10271]
[Fedback in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1696257420301189)

> If I say that the shop is closed one Monday, the yellow box pops up on EVERYTHING even if they don't have "unusual hours" - the one with actual unusual hours has Closed in bold but that's the only way to tell at a glance (is that accessible?). I think this causes confusion (it did recently with another closure). Maybe something we can look at?

Answer from Gareth:
>  It is by design that the times for each venue are added to a yellow box when one of them has unusual hours, but it makes much more sense (and was probably designed that way) for particular periods, such as Christmas & New Year. It is strange when it's just a single day and misleading when the title is 'unusual hours' when there aren't any. Definitely something to revisit.

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/eac611f0-2613-49f1-90dd-0524e0426fcf)

**Comment by j-jaworski** [comment]
This looks like a bug to me, or rather, as Gareth has pointed out, the feature is not working in this instance.
I am happy to discuss alternatives, but if I have understood the issue correctly, my suggestion is:
- [ ] Add a global toggle in the BE that applies the `Unusual open times yellow box` to all venues for periods like Christmas and New Year
- [ ] Ensure when the global toggle is off, the `Unusual open times yellow box` only appears next to the venue that has had exceptional open times added

**Comment by LFBaily** [comment]
Agree with those two actions Jason - suggest we create those and close this?
