### ISSUE TITLE
Date filter behaviour in image search not working as it should

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10287]
## It doesn't get displayed when there are no results
- Go to https://wellcomecollection.org/search/images
- Add dates to and from in filters
- Input a nonsense string that won't return results
- See the filters go away

Do the same in works and you see they are still there, as you should be able to remove them to try and get more results.

## It's not considered in `hasFilters`
We have a helper function that checks if there are active filters, which allows certain things to get displayed/hidden. The date range doesn't seem to affect that function and `hasFilters` returns false. 
- Used [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/pages/search/images.tsx#L89)
- Helper function [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/utils/search.ts#L92)

**Comment by georgiaewhitney** [comment]
The initial fix for this has revealed a bug that doesn't feel conducive to introduce to prod. Once the message appears that there are no search results with selected filters, removing the filters doesn't work and automatically redirects to this search. 

To reproduce use latest in branch `date-img-filter-fix`:

- create a search that **will** return a result with no applied filter. search "spaghetti"
- put a filtered search of "From 1600" - search results will be ok
- select "To 1700" - search results will now apply "no results with selected filters message" which applies to above issue. 
- Try to remove or reset filters - the page will display for approx. 1-2 seconds before a URL direct reapplies the filters. 
- `console.log` confirms the filter was removed via the button but reapplied right after.

**Comment by rcantin-w** [comment]
Dependant on[ fixing the search-images tests ](https://github.com/wellcomecollection/wellcomecollection.org/pull/10528)as I can't tell if the tests are flakey because the tests are or because of the changes.

**Comment by rcantin-w** [comment]
in prod
