### ISSUE TITLE
Create Visual Story landing page

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10315]
https://docs.google.com/document/d/17xPEfOFAFzBeFopkKUAWUTyBo89lPzoSSV5o_4Ri8NQ/edit mentions we should have a landing page for VS

As we want current and past VS to be split on the page, I think we could create it so it looks like https://wellcomecollection.org/exhibitions

- Get copy from Editorial for header description + past/current descriptions if needed
- Allow for pagination over a certain number (even though this will take a while to be needed)
- Split by current and past 
- Does this change the breadcrumbs? Maybe generic VS get to have a link to the landing in the breadcrumbs
- Where do we link to this page? "An index page for all visual stories will enable an onward journey to ‘See all visual stories’". Where is that button?

**Comment by rcantin-w** [comment]
[I've started the work on this](https://github.com/wellcomecollection/wellcomecollection.org/pull/10348) but I'll pause it as I have many questions for possibly designers and user researcher/PM, starting with the ones in the description, but to recap:

- Where do we link to this page? "An index page for all visual stories will enable an onward journey to ‘See all visual stories’". Where is that button?
- What determines the order? Do we have to look at their related document and try to get a date from that?
- If we do current and past, does it mean generic pages such as Getting Here are considered "current" forever? Where do they sit?
- What information is displayed on the card? 
- What microcopy do we display? ([I asked Editorial on Slack](https://wellcome.slack.com/archives/C054304EVL5/p1698060527475999)).

As I don't believe this is urgent work considering we don't have visual stories at the moment and there is no strategy outlined for creating generic ones (such as Getting Here), there is time to do this the right way.

I'll close the PR but wanted to create it so we'd have an idea of a starting point once we can hit the ground running.

**Comment by LaurenFBaily** [comment]
Closing as we have decided not to have an index page.
