### ISSUE TITLE
Styled component 6: investigate removing enableVendorPrefixes

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10380]
We had to enable vendor prefixes as they are now [disabled by default](https://styled-components.com/docs/faqs#vendor-prefixes-are-omitted-by-default). This ticket would serve to split the work so it's not all done in the one big ticket.

- Check how things look with the styles disabled (tbh I've only noticed it being an issue [here](https://github.com/wellcomecollection/wellcomecollection.org/pull/10352/commits/2347a4c80e7ab91f3958ee1a106d1350b6cb903c) and in its corresponding Storybook story)
- Have a look at the difference between the CSS with and without, see how much it saves.

**Comment by rcantin-w** [comment]
@gestchild used the very modern method of getting the inline css from the source and saving it, both on this branch on main. There's no statics CSS files, they're just inlined within each page. The files I created off of that (just the css) are definitely always lighter when `enableVendorPrefixes` isn't set.

**Home:**
With vendor prefixes - 91KB
Without vendor prefixes - 75KB **(-16KB)**

**Work (archive)**
With vendor prefixes - 72KB
Without vendor prefixes - 61KB **(-11KB)**

**Search (overview)**
With vendor prefixes - 74KB
Without vendor prefixes - 62KB **(-12KB)**

I'm not sure how much these matter, even though smaller is always better. 
At a glance, all the styles look fine, but I'm guessing it'll mostly be niche details that are affected and they could be treated as they come if raised.

I'd be happy to manually add the vendor prefix in the one instance we found and set it back to its new default of no automatic vendor prefixes, what do you think?

**Comment by gestchild** [comment]
I vote to do it

**Comment by rcantin-w** [comment]
in prod
