### ISSUE TITLE
Copy for deleted works is misleading

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#10385]
Currently, we show the following copy if the catalogue API returns a 410 Gone for a work:
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/4429247/d03beaf1-9cde-4856-a702-25d588b67a83)

This is misleading, as deletions happen as the result of deliberate actions. Suggested new copy would be:
> This work has been deleted from our public catalogue. If that doesn't seem right or isn't what you expected, email us at digital@wellcomecollection.org

**Comment by jamieparkinson** [comment]
See discussion: https://wellcome.slack.com/archives/C1PK7TS0L/p1698411659336029

**Comment by rcantin-w** [comment]
In prod
