### ISSUE TITLE
Refactor e2es

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10409]
[See Slack convo](https://wellcome.slack.com/archives/C3TQSF63C/p1698840059552509), this is becoming a blocker, we need to get them to run smoothly. 

They will very often fail because of time outs. After discussing with Jamie, we decided to refactor the tests so they would use less custom helpers and more of the tools that Playwright offers, with the aim of making the tests more useful, more solid and more readable.

I've outlined the strategy in #10414 so you can go there for more information.

**Comment by rcantin-w** [comment]
From the PR:

### My notes so far:

- [Playwright's auto-retrying assertions](https://playwright.dev/docs/test-assertions#auto-retrying-assertions) should be used as much as possible instead of waitForTimeout, waitForSelector or waitForNavigation, which we currently use a lot but are [deprecated or discouraged](https://playwright.dev/docs/api/class-frame#frame-wait-for-timeout). They would be the key to fix race condition issues.
- When testing sorting, filtering or pagination, we can't depend on the URL change nor the value of the input. As some of the content updates before navigation occurs, or as the state of some inputs doesn't update their value right away, the safest route seems to be to expect content on the page to have loaded.
- Pagination: Check the input[name="page"] value for the page number
- Filters: Still needs work. Currently looks at if they're listed in the hidden span role="status" but I don't love it for the reasons listed in the comments. How should we make it available to the tests both on desktop and mobile?
- Sorting: Look at the value of the Select.
- The selectors we're using should be based on [this recommendation list](https://testing-library.com/docs/queries/about/#priority).

###Next steps:

- Rewrite all tests one by one and only use what Playwright offers without patching it
- This might mean fixing things in the codebase that aren't working as they should, or maybe they need identifiers to be used in tests.
- Clean up all actions and selectors (like playwright/test/actions/search.ts), as a lot of them aren't used anymore.
- Once we make works-search work perfectly, according to all of the above, then it will become a blueprint and we can split the rewrite between us, so do have a look, let us know what you think and get acquainted!

**Comment by rcantin-w** [comment]
Left to review:

- [ ] `api-toolbar.test.ts`
- [ ] `articles.test.ts`
- [ ] `concept.test`
- [ ] `events.test.ts`
- [ ] `exhibition-guides.test.ts`
- [ ] `homepage.test.ts`
- [ ] `landing-pages.test.ts`
- [ ] `media-office.test.ts`
- [ ] `request-items.test.ts`
- [ ] `search-form.test.ts`
- [ ] `search-images.test.ts`
- [ ] `search.test.ts`
- [ ] `view-items.test.ts`
- [ ] `work.test.ts`

I think it'd be great if everyone picked at least one to familiarize themselves with the way we want tests to be written moving forward. I won't assign anyone as I said in the call, and I'll aim to go through them, but it'd be great if you could 🙏

**Comment by rcantin-w** [comment]
For @paul-butcher in January. I think you wrote the concept one and it seems way more advanced than our other ones. If poss, would be good to sit together when we're both at the office to pair on it?

**Comment by davidpmccormick** [comment]
Looking at [these failures](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/3990#018d8008-5810-4125-8981-ae6808c164c1)

**Comment by davidpmccormick** [comment]
All done 🎉
