### ISSUE TITLE
Link to DLQ on AWS from Slack alert

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10429]
When we get errors in the Slack alert channel of the type: "platform-sqs-dlq-not-empty" it would be useful for it to contain a link to the  DLQ in question on AWS

We should also found a way to clarify which pipeline is currently in use, as older pipelines also send errors in the alerts channel but they don't require action. The current ones are listed here https://api-stage.wellcomecollection.org/catalogue/v2/_elasticConfig

**Comment by rcantin-w** [comment]
Just had a chat with @jamieparkinson re this as I wanted to trial it, but it seems it's too complex to just go in and tweak. The outcome being that this is probably part of a higher level picture of what should be alerting in Slack vs what could just be on a monitoring dashboard. An interesting chat for retro/planning? (@jcateswellcome)

**Comment by jcateswellcome** [comment]
@kenoir we can pick this up in platform now, would be good to get up to speed with @jamieparkinson on this. Looks on the face of it to fit with our focus on platform health and just general tidiness of alerts.

**Comment by pollecuttn** [comment]
This would be better addressed with a broader rethink about observability.

@gestchild Robert can show you how to find issues in the dashboard if you need it.
