### ISSUE TITLE
Don't send DLQ alerts to slack during a reindex

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10428]
DLQ alerts "platform-sqs-dlq-not-empty" are known to happen during a reindex and someone will be looking at the dlqs as part of inspecting progress anyway.

When they happen as part of a reindex, these alerts add noise to the slack channel and make it hard to determine when they really need attention.

**Comment by gestchild** [comment]
@paul-butcher please could you fill in the detail of what needs doing?

**Comment by kenoir** [comment]
Closing as we don't do this anymore since removing the DLQ alerts.
