### ISSUE TITLE
Extend the spam detector to cover Hangul

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/wellcomecollection.org#10476]
The [spam detector](https://github.com/wellcomecollection/wellcomecollection.org/blob/029bd75fcbe17487f4cb02a44e0eccccb01d0dc0/content/webapp/utils/spam-detector.ts#L53) quickly rejects URLs with queries that look like Chinese casino spam and we know won't match anything.  We have now started seeing [Korean casino spam](https://wellcome.slack.com/archives/CQ720BG02/p1701620111923489).  We have no Korean content, so these requests can be rejected quickly.

**Comment by rcantin-w** [comment]
@paul-butcher is this still something we want to look into?

**Comment by paul-butcher** [comment]
@kenoir I suspect this is now redundant due to the spam filter work you've done.

**Comment by kenoir** [comment]
Closing as done.
