### ISSUE TITLE
Modelling spammer behaviour

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10485]
**What is the problem to solve?**
Currently spam is identified by Chinese characters and things like, "Buy now." Not all spam is Chinese, though.

**What are the objectives?**
Spammers do more than search. Identifying common behaviour might allow improvements to the spam filter.

**What research technique is required?**
Produce Python dataframe of total queries, total sessions, total page paths
Segment dataframe into spammers/non spammers
Describe spammer behaviour if typical behaviour exists
Collect anonymousIds for similar non-spam behaviour and examine queries
Write up recommendations for further filters

**Comment by taceybadgerbrook** [comment]
Native AWS rules are being switched on to increase the spam filter. These will ensure spammers are served with 403 messages and means user stats will no longer need to subtract spammer numbers.

To check this, when blocking commences, [run this Kibana dashboard](https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/462832a0-610e-11ee-9628-ffac226101a0?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))) to see if spammer numbers fall off compared to 15/12.

**Comment by LFBaily** [comment]
Pausing until new year.

**Comment by taceybadgerbrook** [comment]
Spam activity during December shows firewall rules taking effect.

![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/5393aeec-9069-46e8-baab-95acf21207cb)

**Comment by taceybadgerbrook** [comment]
The January records where looksLikeSpam=true is picking up Googlebots which we need to operate in order to index our content. As the AWS rules appear to be doing a good job of blocking most spam, I am going to stop using lookLikeSpam to subtract spammers from the monthly and quarterly user numbers.
