### ISSUE TITLE
Use new Events endpoints to display events in search

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10540]
The events currently displayed are mock events.

1. Use the /events content api endpoint instead: https://api.wellcomecollection.org/content/v0/events
2. Check pagination works
3. Check if any tests need amending

**Comment by georgiaewhitney** [comment]
`/events` endpoint merged in https://github.com/wellcomecollection/content-api/pull/81

**Comment by rcantin-w** [comment]
in prod
