### ISSUE TITLE
Nothing is the Modal box is selectable

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10544]
1. Go to https://wellcomecollection.org/search/images
2. Click on an image or the "All filters" button
3. Try to select anything; it doesn't work

We should try to fix this, but couldn't figure out quickly what was going on, so creating a ticket.

**Comment by rcantin-w** [comment]
Ohh interesting, you use Firefox right, and PC?
It doesn't work in Safari and Chrome (for me anyway), but does on FF - all Mac. Does it for you?

**Comment by pollecuttn** [comment]
I use Chrome on a PC.

Also checked and I can select images and filter results with Edge on a PC and with Firefox on a PC, too.

**Comment by rcantin-w** [comment]
Alright! Then it'd be good if someone else on a mac could test and see if it's just me 👀

**Comment by pollecuttn** [comment]
> I can select filters, checkboxes and colours work (edited) 
> 

> View expended image works as well when I click on an image (using Chrome) 
> 

> All the above fine on Safari too

Source: [Slack](https://wellcome.slack.com/archives/C3TQSF63C/p1704446004387689?thread_ts=1704445891.053159&cid=C3TQSF63C)

Looks like it might just be you @rcantin-w ?

**Comment by paul-butcher** [comment]
Works for me, Safari, Chrome and Firefox on Mac.  It is a little slow. There is a very noticeable pause between the click and the tick.

**Comment by rcantin-w** [comment]
Thanks all! Will close as it's not replicable.
