### ISSUE TITLE
Meaningful ECS service health checks

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#10545]
Some of our web application / API services expose health check endpoints, but none of these actually perform a meaningful check for service health.

There are 2 primary consequences of this:
- ECS doesn't know that it needs to restart applications that have got into a broken state (we have had to do this manually sometimes)
- During deployments we see a small number of failed requests due to the service not being able to serve requests at the time it receives them (see https://github.com/wellcomecollection/wellcomecollection.org/issues/10513)

Here are the services which need health checks adding/improving:

- [x] Catalogue API: https://github.com/wellcomecollection/catalogue-api/pull/736
- [x] Content API: https://github.com/wellcomecollection/content-api/pull/94
- [x] Items API: https://github.com/wellcomecollection/catalogue-api/pull/739
- [x] Requests API: https://github.com/wellcomecollection/catalogue-api/pull/747
- [x] Concepts API: https://github.com/wellcomecollection/catalogue-api/pull/749
- [x] wc.org:
  - [x] Content (wc.org) webapp: https://github.com/wellcomecollection/wellcomecollection.org/pull/10612
  - [x] Identity (wc.org) webapp: https://github.com/wellcomecollection/wellcomecollection.org/pull/10617
  - [x] https://github.com/wellcomecollection/platform-infrastructure/pull/413
  - [x] https://github.com/wellcomecollection/terraform-aws-ecs-service/pull/52
  - [x] https://github.com/wellcomecollection/wellcomecollection.org/pull/10618
- [ ] Storage service: https://github.com/wellcomecollection/storage-service/pull/1115
- [ ] An RFC for where we might want to end up: https://github.com/wellcomecollection/docs/pull/98

**Comment by kenoir** [comment]
Flagging that for `wellcomecollection.org` the healthcheck endpoints are HTTP but still terminate at the nginx container: https://github.com/wellcomecollection/platform-infrastructure/blob/main/images/dockerfiles/nginx/frontend.nginx.conf#L24
