### ISSUE TITLE
(TODO) AudioList thumbnails placeholders

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10543]
In our FE catchup "TODO of the week", we raised this one in [the AudioList component](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/components/AudioList/AudioList.tsx#L21)
> thumbnail, TODO: add thumbnail once placeholders have been removed from manifests

We weren't sure what it meant exactly, [here's an example work with an AudioList](https://wellcomecollection.org/works/swnacurm) and [its IIIF manifest](https://iiif.wellcomecollection.org/presentation/v3/b31630327). It'd be good to re-figure out what was intended, and if we can't, remove the commented out code in the component and the two TODOs.

Assigning it to @davidpmccormick as he might remember?

**Comment by gestchild** [comment]
This is related to #10606, so picking this up too

**Comment by aray-wellcome** [comment]
I might have some context for this, deep in my memories! 

So Harkiran and I, when we were making the new A/V workflow a few years ago, needed to restore the ability for us to add thumbnails to audio files. We really only had one example of this, I think, which is this one. https://wellcomecollection.org/works/tp9njewm We have a black and white picture of Florence that used to sit alongside of it on Wellcome Library. I don't think we ever really got the ability to do it? 

I've got a Slack message here at least that links to another ticket where it was discussed.  https://wellcome.slack.com/archives/CBT40CMKQ/p1643716990961369

Hope that helps a bit!

**Comment by gestchild** [comment]
I've removed the TODO and commented code in [this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/10648)

As @aray-wellcome mentions, we usually don't have images to render for Audio items
