### ISSUE TITLE
Review reporting June 2024

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10563]
New Looker Studio and GA4 Funnel Exploration reports were set up January 2024 in an attempt to address the issue of onerous Kibana dashboard maintenance. The logic is that url formats change less frequently than Elasticsearch fields and represent only one piece of data compared to criteria in Kibana visualisations which draw on 2-3 different fields.

How are we doing? Should we go back to Kibana dashboards? This would mean setting up a field tracker to identify which Kibana fields have changed to update the associated visualisations (because the dashboards are made up of individual visualisations) instead of updating GA4, Looker Studio and Kibana visualisations.

**Comment by kenoir** [comment]
Closing as lost context.
