### ISSUE TITLE
Reference number not displaying for some works

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#10565]
**What**

Reported for Drawings of an epidural and c-section at John Radcliffe Hospital, Oxford, 4 May 1987. https://wellcomecollection.org/works/hh8dhtur

See [Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1704797224641979)

**Where**

The reference does display on https://wellcomecollection.org/works/hh8dhtur but is missing from lower level works:
- https://wellcomecollection.org/works/vu3mwczx
- https://wellcomecollection.org/works/q38c5mtw
- https://wellcomecollection.org/works/vufpf4ae

Cf e.g. these where the reference is on both the higher and lower level works:
- https://wellcomecollection.org/works/c245ztkp - higher level
- https://wellcomecollection.org/works/g8j7y2xh - lower level
- https://wellcomecollection.org/works/j7exp89z - lower level

I'm don't know if this has always been like this.

**TODO**
Dev to investigate:
- if this is a new problem or if this was always this way
- if it's a new problem to fix the bug

**Comment by rcantin-w** [comment]
The header reference number comes from `work.referenceNumber` whereas the one in the body comes from `work.notes`, which is a list that contains:

```
 {
    contents: [ 'Wellcome Collection 3329263i' ],
    noteType: { id: 'reference', label: 'Reference', type: 'NoteType' },
    type: 'Note'
  }
```

I'm trying to grasp a bit better where these come from but it's API side, so will get back with a clearer answer after I've discussed it with someone that has a better understanding of the Works API and how items relate to each other.

**Comment by paul-butcher** [comment]
As @rcantin-w and I had essentially done the work when we were trying to work out which side of the system this problem is on, I have turned it into [a PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/10599)
