### ISSUE TITLE
Broken Pagination on /events/past

### ISSUE THREAD

**Issue by georgiaewhitney** [wellcomecollection/wellcomecollection.org#10575]
**What**

We have a pagination component that allows a user to navigate directly to a particular page by entering the desired page number in an input field:

<img width="244" alt="Screenshot 2024-01-12 at 12 57 50" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/81175151/ac3b0f0d-dda1-45a7-b179-c4f943018cf1">

When exploring past events at `/events/past` -  the pagination **only** works when using the arrow buttons to go forward/back a page. 

Events pages will **not** list if you manually insert the page number into the input field (as seen and directed in this accessibility ticket #10470) nor if you manually adjust the URL. 

Doing so will one of two things:

- revert back to `/events` 
-  produce a no results page as seen below

<img width="913" alt="Screenshot 2024-01-12 at 13 01 10" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/81175151/1a5047d0-5cba-4b80-bb6e-98b25907b22f">

**Where**

https://wellcomecollection.org/events/past

**Comment by rcantin-w** [comment]
Removed the input #10684
