### ISSUE TITLE
Review design & behaviour of Monday closure messaging in What's On Today

### ISSUE THREAD

**Issue by LFBaily** [wellcomecollection/wellcomecollection.org#10603]
# What?
- Review and update message styling (currently uses title font weight, looks strange) for the Monday closure message
- Re-add the code for Monday closure message back to the site

# Why?
On Mondays the 'Today' section displays 'Exhibitions and Events' sub-header with cards for current exhibitions despite the fact that the galleries are closed that day.

# Background 
Functionality/features were removed during covid closures. Most have been re-added in Oct 22 but this was outstanding.

# Done when
-  [ ] 
-  [ ] 

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/152871676/de3de1ba-6e7c-42f0-b56a-50e15ed7bc27)

**Comment by j-jaworski** [comment]
**Designs on Figma**
https://www.figma.com/file/lp3Wf2aM3bA4h3GgShWRMI/Monday-closure?type=design&node-id=5%3A33&mode=dev&t=sOHHqCggbEXBN8s1-1


<img width="957" alt="Screenshot 2024-01-29 at 09 59 32" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/8ea109d6-d255-4dc6-9678-bff29018d1c6">

**Comment by LFBaily** [comment]
Looks great. I think we just need to remove the 'Exhibitions' header as that's dynamic depending what's on so it should just be the date and then directly below the Monday message block.

The 'Try these **too**' in context doesn't quite work. If we do add a rule to hide the reading room card we could have alternative copy here?

**Comment by rcantin-w** [comment]
Sliding in here for what I think might be good-to-know context about that component. It's called `InfoBox`, we use it at bottom of Event and Exhibition pages, which is probably where you took it from? 
I wanted to share [how Jenn explained its "reason for being"](https://wellcome.slack.com/archives/C3N7J05TK/p1686673971867389?thread_ts=1686663801.814339&cid=C3N7J05TK) to post on here, as I think it does match what you've used it for here.

> An InfoBox was meant to be a persistent element of Exhibitions and Events pages - **showing quick need-to-know information relating to attendance**.

**Comment by j-jaworski** [comment]
> ...remove the 'Exhibitions' header ...
I kept it in so that the page makes sense for screen readers that would be scanning for H1 headings, but can remove if we think that it will still meet our accessibilty standards or if there is a work around. Actually I added it back in this morning...

> The 'Try these too' in context doesn't quite work. If we do add a rule to hide the reading room card we could have alternative copy here?
I know what you mean, I don't completely hate it though, as a section it appears on all the tabs, its likely to be recognised as a pattern to users... maybe? Our options in order from least prefered to most prefered (also least to most work)

1. Keep Reading Room card and "Try these too" heading - Unchanged
2. Keep Reading Room card and change heading to "Try these" - Poor UX
3. Hide Reading Room card and keep "Try these too" heading - Grammatically poor title
4. Hide Reading Room card and change heading to "Try these" - Yay!

**Comment by LFBaily** [comment]
Hmm...I see what you mean re: taking away the h2. Perhaps a front-ender might advise on options? Could 'Exhibitions closed today' be marked as the H2 for example?

Let's do option 4. It's a little bit of work but it supports with the most fundamental user need for this page aka I want to be clear what's on and also I don't want to turn up when everything is closed.

**Comment by rcantin-w** [comment]
Just a few questions for my understanding, and a screenshot for the current view;

1. Current title is "Exhibitions and Events", but that's changed, correct? Oh actually - could there ever be events on Mondays, did we check? In which case what happens to that list of event vs the yellow box about exhibitions? 
2. Currently we have buttons linking to All Exhibitions and All Events from that section, those seem to be removed now but wouldn't they still have value?

`Infobox` titles are already h2s, but they appear above the yellow box, [see how it's used in exhibitions right now](https://wellcomecollection.org/exhibitions/ZJ1zCxAAACMAczPA). I hadn't noticed the difference with the designs earlier. If it works for you Jason, maybe that answers the question?

<img width="872" alt="Screenshot 2024-01-29 at 15 30 55" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/6ecc1f73-e212-41d6-95f6-1c82ad14e49b">

**Comment by LFBaily** [comment]
1. Yes it's currently 'Exhibitions and Events' (even if there are no events and just exhibitions). I had also assumed there were no events on Mondays but I can check that now...
2. Assuming the tabs are well-understood I'm not too worried about these but could still include the two 'All' buttons?

Sounds like that answers the H2 question - we can just make 'Exhibitions closed today' the H2 there, whether it's within or above the yellow box. Seems like it's fine to have a slightly different design treatment for this specific use case? But I defer to you Jason.

**Comment by j-jaworski** [comment]
Okay! Feels like there should be a neat solution.

- Remove the heading (H3?) from inside the `infobox`, and have it as the H2 above the `infobox` 
- Suggest changing the heading to "Exhibitions are closed on Mondays" to be a bit more descriptive
- Include buttons for `View all events` and `View all Exhibitions` as this won't harm the UX and does give a more obvious path out of the unhappy path


**Updated designs on Figma**
https://www.figma.com/file/lp3Wf2aM3bA4h3GgShWRMI/Monday-closure?type=design&node-id=2%3A1721&mode=dev

**Screenshot for reference**
<img width="1137" alt="Screenshot 2024-01-29 at 17 18 53" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/3dcfef75-fbff-4157-ad35-a46db4126340">

**Comment by rcantin-w** [comment]
Sounds good! 
As a note, it _is_ a bit confusing for the naming of the headings but we are very flexible in how to style them. We don't style the `h1/h2/h3` element directly, but use classes to give them [different font-sizes styles](https://cardigan.wellcomecollection.org/?path=/story/global-typography--scale) individually (e.g. `.font-size-1, .font-size-2`, etc.) 
So I can make the `Infobox` a bit more flexible and apply a bigger font-size to the h2 than it has on Exhibition pages and both will still be h2 under the hood 👍

**Comment by LFBaily** [comment]
Fab. Also can confirm that events don't happen on Mondays

**Comment by rcantin-w** [comment]
I'll add this for the dev-ing ticket; sometimes the shop and the cafe are closed exceptionally (the shop was on the 22nd for staff training). When this happens, the Editorial team put up a banner, which displays on 90% of pages, that says so:
<img width="919" alt="Screenshot 2024-01-30 at 09 37 22" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/62990750-5731-43c4-8cb8-61584de090d4">

Maybe we want the code to look at shop/cafe opening hours before it displays some of that information? Or are we ok with keeping it generic and trusting that users have read the banner?

(Also think Christmas hols etc.)

**Comment by LFBaily** [comment]
If the galleries open on a bank holiday Monday (do they?) it will need to check the special opening times.

On your question...for one or two days a year it doesn't feel too important. Unless you disagree Jason I would lean towards keeping it generic and for exceptional cases using the  global banner which has the hierarchy on the page to communicate it.

**Comment by rcantin-w** [comment]
[Conversation continued in Slack](https://wellcome.slack.com/archives/C3TQSF63C/p1706608185334449)

**Comment by j-jaworski** [comment]
**Summary of Slack comments** 
- At times we might have conflicting messages displayed, for example, a global banner announcing that the shop is closed and an `infobox` that says the galleries are closed, but the shop and cafe are open.
- We shouldn't trust users will do what we expect, even if they do read the banner, they could get confused by the conflicting messaging

**Our options:**
1.  If the galleries are closed (because Monday) and the cafe and/or shop are closed (because reasons) then we should ensure that the text in the `Infobox` reflects this - some dev work to implement logic 
2. Ignore the risk, the global banner takes hierarchy on the page and persists across 90% of website - less dev work

FWIW I prefer option 1, but would be interested to understand the scope of the dev work for both

@LFBaily If the galleries are open on bank holiday Mondays, then we should change the title in the current design from "Exhibitions are closed on Mondays" to "Exhibitions are closed today", so please let me know and I will update the designs.

**Comment by LFBaily** [comment]
I'll change this ticket title to 'Design and review behaviour for monday closure message...'(my fault for leaving the 'Done when' section blank!) and open up a dev ticket with what we've agreed.

**Comment by rcantin-w** [comment]
Tbh by testing it/estimating it I'd probably be doing it, so we could just add it as a timeboxed bonus in the ticket?

**Comment by rcantin-w** [comment]
Reckon this can be closed now?
