### ISSUE TITLE
Add a hardcoded banner + toggle to activate in case of widespread issues

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10615]
On 25th January, we had issues across the website due to a fault with the Prismic API ([See here for incident thread](https://wellcome.slack.com/archives/C01FBFSDLUA/p1706178875877089)). Prismic-fed pages would, more often than not, display our generic Internal Server Error/500 (**ISE**) message, which doesn't inform the user on much. Our users would just repeatedly come across ISE pages even though the site otherwise looked OK (menu showing, etc.), which must have been a frustrating experience.

[A PR was created, then merged](https://github.com/wellcomecollection/wellcomecollection.org/pull/10608), which added a link to our status page to the Error page's list of "What you can do". So we have that in now, but [that page was mostly created for internal staff use](https://wellcome.slack.com/archives/C3TQSF63C/p1706265776190519?thread_ts=1706263632.429169&cid=C3TQSF63C), so making it more prominent would not be the way forward.

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/da4705d5-d4e8-482a-b6df-0b5dd0e01f76)

Another thing we thought of doing was adding our yellow banner with a message, but that banner's content also comes from Prismic, and therefore would've risked breaking the then-unaffected pages as well.

We could add a hard-coded banner with a generic "We are aware of current issues across the website, please bear with us as we investigate and fix" message (copy TBC) in the hopes that it would (1) make it clear to colleagues across who weren't aware of the status page, (2) lighten the load of our user-facing staff who might have a lot of emails to reply to and (3) make the other users aware that we are aware, hopefully lessening any frustration they might be feeling should they come across one or multiple ISE pages. 

The ISE page message does say " Looks like something’s not working properly our end. We’ll try to fix it as soon as we can.", but it also says "Refresh the page (sometimes it's a temporary issue)", which feels like mixed messaging than the banner would help alleviate? 

That banner would be hidden behind a Permanent toggle, which means it's easy to make public without a deployment. This is good as deployments were hindered on the day since most e2e tests were failing. It's also faster than deploying!

This ticket stems from [a suggestion in Slack](https://wellcome.slack.com/archives/C3TQSF63C/p1706263632429169) and feedback was positive on the idea so I'm now creating the ticket - do flag if you think this is not necessary/there are other ideas.

**Comment by pollecuttn** [comment]
@rcantin-w Wording for banner: 

> We are experiencing some issues with the website, but we're working to fix them. Please try again later if you can't do something.

**Comment by rcantin-w** [comment]
You mean like change the message once we're happy? We could just use the current Prismic alerts banner?

**Comment by pollecuttn** [comment]
Oh yes, of course!

**Comment by rcantin-w** [comment]
It would be a manual job by ? someone ?, and then to remove it as well, but I reckon it's the easiest way!

**Comment by pollecuttn** [comment]
I would expect that person to be me as I'm also doing the statuspage updates.

**Comment by rcantin-w** [comment]
Up to you then if it feels useful. I'm thinking of making that banner non-dismissable (still investigating that), so if I do that, when it's removed it's maybe kind of obvious it's fixed?

**Comment by pollecuttn** [comment]
Yes, I would hope when the banner is gone it's clear it's fixed if you had problems, and people who never saw the problem to start with don't need to know anything about it.

**Comment by rcantin-w** [comment]
As discussed with Lauren and Gareth, we'll set a 4h expiry on the "dismissed" cookie for this banner.

One for @j-jaworski ; in the very rare cases where both banners are up at the same time, and because they don't _really_ serve the same purpose, should we 
1) consider a different icon at the left hand side for the "Site has issues" banner?
2) have them be a different colour? For now I've set `accent.lightSalmon` for the "Site has issues" banner, but it was semi-at-random, so happy to get your opinion on that! I'd leave it that colour even if it was the only banner that was up as well.



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/3a799249-4b1e-4155-8d5c-29c82c348822)

**Comment by j-jaworski** [comment]
Happy with all of this. Just wanted to suggest some different icons. A calendar for the closure and the info icon from our icon library for the error.

Happy to provide these in any format that you need



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/d08243cd-c0de-480d-b7e4-9763d8f4dd78)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/eac83f1e-6127-481b-9199-203bd42b7cfc)

**Comment by rcantin-w** [comment]
As discussed on a call just now, we'll keep the icon as is for the InfoBanner as it's flexible content and the WebsiteIssues one can use "exclamation" for the time being, looking like:

<img width="1325" alt="Screenshot 2024-02-01 at 16 39 18" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/c327c838-21ed-4502-b1c7-de11549c881d">

**Comment by rcantin-w** [comment]
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/f249e29b-3d34-40d3-bb86-a35ffa69d2a4)

Now available, ready for next time !

**Comment by pollecuttn** [comment]
Documentation for use updated at:
- https://www.notion.so/wellcometrust/Site-problems-Who-to-contact-41d5b3a820a649faa2cdf5982b4a4b25#18f45ef51ad14ea09be9ee7c862ba413
- https://www.notion.so/wellcometrust/How-to-Update-the-global-alert-banner-86edba42bd704d3e8bc4eabd92843470
