### ISSUE TITLE
Improve usability of exhibition guides

### ISSUE THREAD

**Issue by j-jaworski** [wellcomecollection/wellcomecollection.org#10613]
**Summary**

Exhibition guides include audio descriptions, British Sign Language and captions and transcripts for users to use on their own phone or device to enhance the experience of visitors with various access needs.
Guides can be accessed from QR codes in the building.

The scope of this work is to focus on only the aspects that are on wellcomecollection.org 

Some work was done previously to plan how we might conduct some user research on the user journey holistically, but this is now being postponed until we have a user researcher in role. 

https://www.notion.so/wellcometrust/Digital-Exhibition-Guides-cb885d6e98364f2b8d9a90b43ed49133?pvs=4

**Comment by LFBaily** [comment]
@j-jaworski what do you think about removing this ticket and keeping the overview in Notion?

**Comment by j-jaworski** [comment]
Happy to delete things

**Comment by LFBaily** [comment]
Closing - I think everything above is captured in the linked page.
