### ISSUE TITLE
Add Monday closure message to Today tab

### ISSUE THREAD

**Issue by LFBaily** [wellcomecollection/wellcomecollection.org#10629]
### What?

Add closure message to the 'Today' tab (updated design in #10603 ) for Mondays when galleries and reading room are closed.

### Why?

So users are clear on opening times for exhibitions when they are planning a visit. Currently the 'Today' section displays 'Exhibitions and Events' sub-header with cards for current exhibitions despite the fact that the galleries are closed on Mondays.

### Background

Functionality/features were removed during covid closures. Most have been re-added in Oct 22 but this was outstanding.

### Done when

- On Mondays, a closure message with links to opening times, cafe, shop and all exhibitions & events is displayed in place of the exhibitions and event cards in the 'Today' tab of https://wellcomecollection.org/whats-on

- the Monday closure message doesn't display when the Galleries and reading room are Open on a Monday (special opening times)

**Comment by rcantin-w** [comment]
In production, keep an eye on it next week for newfound clarity!

**Comment by pollecuttn** [comment]
Monday 12 February:
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/9902e31d-7ff5-480f-a1da-d35b4522256c)
