### ISSUE TITLE
Hover underline colour is dark when on a dark background

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#10628]
**What**
Where page sections have a dark background, the text colour is white, but the link underline that appears on hover is still dark. Suggest making it the same colour as the text? Ping @j-jaworski 

**Where**
https://wellcomecollection.org/collections

<img width="572" alt="Screenshot 2024-02-05 at 11 02 26" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/1394592/37d2e6f0-417b-4ad1-932a-8850f27f1dd2">

**Comment by rcantin-w** [comment]
Ping @dana-saur @kasiabbb for decision on this one (very backlog non-urgent). Will add "Needs: design" label.

**Comment by davidpmccormick** [comment]
Done in #11272
