### ISSUE TITLE
Put initialisers and events in a condition

### ISSUE THREAD

**Issue by LFBaily** [wellcomecollection/wellcomecollection.org#10623]
# What?
Analytics are currently initialised on first load. If a user doesn't give us permission for those, that step shouldn't even happen. We should wrap initialisation (and event helpers while we're at it) in a conditional that checks if we have consent to do it. I'd do it at the helper level so we only do it once and not bloat the code across.

Something _like_:
```
<Head>
+     {consentForAnalytics && (
          {/* Adding toggles etc. to the datalayer so they are available to events in Google Tag Manager */}
             <Ga4DataLayer
              data={{
                toggles: this.props.toggles,
              }}
            />
           <GoogleTagManager />

          <script
            dangerouslySetInnerHTML={{ __html: renderSegmentSnippet() }}
          />
 +    )}
</Head>
```
```
function track(conversion: Conversion) {
+ if (!consentForAnalytics) return; 

  const debug = Boolean(getCookie(cookies.analyticsDebug));

  // We make toggles available of the dataLayer for GTM, so can use them here too
  const togglesString = window?.dataLayer?.find(data => data.toggles)?.toggles;
  const toggles = togglesString ? togglesString.split(',') : [];
  const sessionId = getSessionId();
  const session: Session = {
    id: sessionId,
    timeout: sessionTimeout,
  };
  const { eventGroup, properties, ...restConversion } = conversion;

  localStorage.setItem(lastTrackedLocalStorageKey, Date.now().toString());

  if (debug) {
    console.info(eventGroup, {
      session,
      properties: { ...properties, toggles },
      ...restConversion,
    });
  }

  window.analytics.track(eventGroup, {
    session,
    properties: { ...properties, toggles },
    ...restConversion,
  });
}

```

I'm not sure exactly what it would look like at this stage as I don't know yet how we'll be checking for consent, but we could do it with a mock variable that is currently always true and then just change that bit with the bulk of the work done.

# Why?
To be in-line with consent laws.

# Background  
Preparatory work to move us to a compliant cookie implementation which doesn't place non-essential cookies until active consent has been granted by user.

# Done when

- [ ] No cookies are added and no events are sent over to our tracking platforms should the consent value be false.

**Comment by LFBaily** [comment]
@rcantin-w Created this on the back of your comment from cookies kick-off

**Comment by rcantin-w** [comment]
I've added some information in the ticket, maybe @kenoir could review when he's back to confirm that's what he was agreeing with when I mentioned it 👍

**Comment by kenoir** [comment]
This makes sense, we also need to think about what happens when a user revokes consent after the page has been loaded after we record consent choice outside of (i.e. they change their mind). 

There is also something for another issue about understanding when re-consent is required and being able to trigger that process, for example if we were to add another analytics cookie or the purpose for which we are using the data collected changes we must be able to ask all users to re-consent. From an engineering point of view we need to be able to trigger a re-consent of users somehow outside of cookie expiration.

**Comment by rcantin-w** [comment]
> This makes sense, we also need to think about what happens when a user revokes consent after the page has been loaded after we record consent choice initially (i.e. they change their mind).

Absolutely. I might leave it as part of the "integrate with 3rd party" part of the work though, as that would affect how we set the condition/detect the change. In the past I'd that action/function on the "Save" button of the "Manage cookie preferences" modal, so we'll have to figure out how it works with whatever solution we end up with?

I believe it'll mostly be about removing the cookies (we use [cookies-next](https://github.com/andreizanik/cookies-next) and they offer [a `deleteCookie()` helper](https://github.com/andreizanik/cookies-next?tab=readme-ov-file#deletecookiekey-options)) and force a page refresh so the conditionals take effect, which should be easy enough (famous last words). It'll also depend on which cookies we need to remove, some offer [some ideas](https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out).

> There is also something for another issue about understanding when re-consent is required and being able to trigger that process, for example if we were to add another analytics cookie or the purpose for which we are using the data collected changes we must be able to ask all users to re-consent. From an engineering point of view we need to be able to trigger a re-consent of users somehow outside of cookie expiration.

Very true again. Last time I did this our consent cookies was actually an stringified object, allowing us to know which cookies had been accepted. I wonder if we could do a check on first load, if there's a change in what the shape should look like, the banner comes up again? Again, I'm not sure how we could utilise the 3rd party to help with this, or if the stringified object idea would be useful still.

**Comment by kenoir** [comment]
> I wonder if we could do a check on first load, if there's a change in what the shape should look like, the banner comes up again?
I like this idea.

**Comment by rcantin-w** [comment]
Doesn't seem to work in staging. It doesn't BLOCK tracking when it should, it always tracks, so I don't see danger in the code making it to production while I debug.

**Comment by rcantin-w** [comment]
We found out it should've worked but it wasn't due to a condition in our Cloudfront policy that ignored all cookies without the `WC_` or `toggle` prefix, so we've change it to be `WC_consentCookie`.

Next steps are to change the `getConsent` function to work for both client and server side, so moving back to in progress.
