### ISSUE TITLE
Stop special opening times box displaying against all venues

### ISSUE THREAD

**Issue by LFBaily** [wellcomecollection/wellcomecollection.org#10640]
### What

Confusing user experience when one or more (but not all) of our venues have unusual opening hours, the normal opening hours for the other venues are displayed in a yellow box with heading 'unusual hours' eg.

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/152871676/da8e9154-43b4-4a26-88e8-5abd4f1f48aa)

### Where

https://wellcomecollection.org/pages/WwQHTSAAANBfDYXU

### To do

When there are 'other' modified opening times for one but not all of our venues (eg. galleries and reading room, shop, cafe, library) the yellow box alerting users to the modified opening times should only be applied next to the venue with a change in hours. Eg. if shop has unusual hours, this is only displayed in the Shop section of the page. 

Relates to #10271

**Comment by gestchild** [comment]
FYI this might need a discussion.

[We used to prevent this from happening](https://github.com/wellcomecollection/wellcomecollection.org/pull/4437) when the unusual hours were of type 'other, but then [that decision was reversed ](https://github.com/wellcomecollection/wellcomecollection.org/pull/8829) presumably for good reasons

**Comment by LFBaily** [comment]
@gestchild thanks for the background. Do bank holiday hours still show in a separate box (so not 'Unusual hours')?

**Comment by LFBaily** [comment]
Don't worry @gestchild I have answered my own question by having a look in Prismic. I've had a look at the conversations and tickets you shared too.

Perhaps not a bug then? But certainly when only one Collection venue has 'other' opening times and therefore the box is shown saying 'unusual hours' that is a confusing user experience.

**Comment by LaurenFBaily** [comment]
The Shop will close on 2nd September so we'll have this come up again. Let's resolve so the unusual hours box only shows next to the venue which is affected.

**Comment by LaurenFBaily** [comment]
When this is fixed please let Editorial know via Slack :)

**Comment by LaurenFBaily** [comment]
To clarify, 'bank holiday hours' logic should stay as it is. This is because users will want to be reassured that the shop is open for example even if the library is closed.
![image](https://github.com/user-attachments/assets/8f4a9890-3993-42eb-badd-8fab02a7bedc)

**Comment by rcantin-w** [comment]
Merged in prod
