### ISSUE TITLE
Add global toggle for unusual hours 

### ISSUE THREAD

**Issue by LFBaily** [wellcomecollection/wellcomecollection.org#10641]
# What?
Allow site editors to easily alert users to unusual hours across the whole venue during periods like Christmas 

# Why?
For periods like Christmas where users expect disruption to usual opening times so want to be very clear when (and which parts) of the venue are open.

# Background
See #10271 and #10640

# Done when
- [ ] Add a global toggle in the BE that applies the Unusual open times yellow box to all venues for periods like Christmas and New Year
- [x] Ensure when the global toggle is off, the Unusual open times yellow box only appears next to the venue that has had exceptional open times added

**Comment by rcantin-w** [comment]
I think we've addressed this in a different way through https://github.com/wellcomecollection/wellcomecollection.org/issues/10640 ([PR has more info](https://github.com/wellcomecollection/wellcomecollection.org/pull/11097)), is that right?

**Comment by LaurenFBaily** [comment]
Agree I think this has been done.
