### ISSUE TITLE
Add filters to front end

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/wellcomecollection.org#10647]
Events filters have been added to the content API 
See PR for sample API response:
https://github.com/wellcomecollection/content-api/pull/102

Much like with Stories, the API requests to /events needs to include aggregations
`aggregations=format%2Caudience%2CisOnline%2Cinterpretation`
This will ensure the response contains the filtering options and the document count for each of them:
```
"format": {
      "buckets": [
        {
          "data": {
            "type": "EventFormat",
            "id": "Wd-QYCcAACcAoiJS",
            "label": "Discussion"
          },
          "count": 27,
          "type": "AggregationBucket"
        },
        ... other formats
     ]
```

The filters are requested using their Prismic id, eg. `interpretation=X2jPiRMAACIA8Vzo`, except for `isOnline`: the mere presence of `isOnline` as a query param (without any value) will result in a response that only includes online events. Since `isOnline` is a binary, it is presented as a checkbox instead of a dropdown of options like the other event filters

NOTE: it's come to my attention that interpretations are duplicated: the label is the same but the id different. 
See https://wellcomecollection.prismic.io/documents/working?k=interpretation-types&l=en-gb 
This results in buckets with the same label. I think the best course of action is to merge the buckets with identical labels and add up their counts. Then send all of the corresponding ids as `interpretation` param if the filter is selected
```
 "interpretation": {
      "buckets": [
        {
          "data": {
            "type": "EventInterpretation",
            "id": "X2jPiRMAACIA8Vzo",
            "label": "Auto-captioned"
          },
          "count": 40,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "W5JXVSYAACYAGtkh",
            "label": "Relaxed"
          },
          "count": 36,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "XkFGqxEAACIAIhNH",
            "label": "British Sign Language"
          },
          "count": 31,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "WmXhziQAACQAnw7i",
            "label": "Audio described"
          },
          "count": 29,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "WmXl4iQAACUAnyDr",
            "label": "Speech-to-text"
          },
          "count": 29,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "X2smLBMAACMA-99Z",
            "label": "British Sign Language"
          },
          "count": 21,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "Wn3STCoAACgAIedR",
            "label": "Hearing loop"
          },
          "count": 17,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "X2jPZRMAACEA8VxE",
            "label": "Audio described"
          },
          "count": 16,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "YqiCnxEAACMA8VLW",
            "label": "Speech-to-text"
          },
          "count": 12,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "X2jP2RMAACIA8V5b",
            "label": "Auto-captioned"
          },
          "count": 10,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "YzGD9hEAAEAKfx0E",
            "label": "Captioned (online)"
          },
          "count": 7,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "XdVIsREAAHH-IrHi",
            "label": "Captioned"
          },
          "count": 4,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "YkRhDBAAACAAvSvl",
            "label": "Wheelchair friendly"
          },
          "count": 3,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "Xz1FCBAAACgAHJ56",
            "label": "Captioned"
          },
          "count": 2,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "YEEDDhAAACUAMRKu",
            "label": "Speech-to-text"
          },
          "count": 2,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "YjnF1BEAACIAeEBy",
            "label": "Speech-to-text"
          },
          "count": 1,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "type": "EventInterpretation",
            "id": "ZW751RIAACUAvsjx",
            "label": "British Sign Language"
          },
          "count": 1,
          "type": "AggregationBucket"
        }
      ],
      "type": "Aggregation"
    },
```

**Comment by rcantin-w** [comment]
Current state of implementation is it raised a few questions that I want to document for next week/the future:

1. Interpretations have a lot of double titles (but with different purposes. Think "Speech-to-text/online" and "Speech-to-text/translation"), so they show up multiple times in the dropdown. [See Slack conversation here](https://wellcome.slack.com/archives/C3N7J05TK/p1708083500927169) and [the rest of the thread here](https://wellcome.slack.com/archives/C3N7J05TK/p1708084076443329). Suggestion by Lauren is to group them into one. I feel like it could/should be done on the API side as is the case with the catalogue API but something to discuss (cc @agnesgaroux, what do you think? Can discuss in Slack and document decision here after if a longer convo.)
2. "Is online" filter, currently debating whether it should be a regular dropdown or the boolean checkbox we were originally suggesting. [See here for conversation](https://wellcome.slack.com/archives/CUA669WHH/p1708091530474339). **If we go ahead with a boolean**, I'll need to discuss design, placement and disabled state with Jason as it would be a brand new style of filter. **If not**, we'll need to make changes to the back-end.

Audiences and Formats are easy/straightforward ones, so I might do a separate PR to get them in faster.

**Comment by rcantin-w** [comment]
Outcomes from catch-up meeting 19/02 with @agnesgaroux @LFBaily and @j-jaworski 

1. "Is online" checkbox to become a "regular" dropdown filter with "Online" and "In person" as label (please confirm wording for what could be more useful). I _think_ this will require changes from the back-end to start with.
2. Most labels for filters to change; @j-jaworski to provide wording
3. Addition of "Available to watch/catch-up event" boolean filter - @agnesgaroux and I will have to discuss what the query for it should look like (I think we need to stick to `=true` as a value as that's the current way it works in the codebase)
4. @LFBaily to create a ticket to make our "relevance"/score better - which fields do we want and what weight do we want for each of them? Possible more can be done, see who could have that expertise to help.

I'll leave this ticket in Blocked for now as we need 1-3 to go ahead.

**Comment by j-jaworski** [comment]
2. Let's go with `Event type` Accessibilty` and `Audience` for now

**Comment by rcantin-w** [comment]
Adding one; @j-jaworski If we add a checkbox filter ("Available to watch"), I'd love to know where it should be/what the unavailable/deactivated state looks like. This would happen when the list of results contains NO "available to watch" events, see current filter behaviour for something similar: https://wellcomecollection.org/search/works?query=very+specific+query

**Comment by j-jaworski** [comment]
**Inactive state checkbox**
Doesn't look like one has been [defined in the storybook](https://cardigan.wellcomecollection.org/?path=/story/components-checkboxradio--checkbox), unless I am missing something.

I have added one to this file on Figma, but I am surprised there isn't already one on the site. 

**Placement **
I don't see any reason not to place it where we have `Future events only` and `Catch-up events only` [on the designs](https://www.figma.com/file/e6Nng9zRjZITtYAZHpF1dB/Events-and-Exhibitions-in-Search?type=design&node-id=117%3A971&mode=dev)

<img width="1140" alt="Screenshot 2024-02-20 at 14 36 21" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/44364115/6345a38d-2b67-4e61-b7e4-3c1076e2692a">

**Comment by rcantin-w** [comment]
It was indeed never defined, I think the only use of checkboxes we have at the moment have never "needed" an deactived state (filters and newsletter sign-up).

**Comment by rcantin-w** [comment]
Audiences, Type (Format) and Accessibility (Interpretations) now available in prod behind the toggle. The work isn't finished though as reflected #10670 , #10668 and other tickets in the content-api repo. 
As tickets for the rest of the work exist, I'll close this one.
