### ISSUE TITLE
Send concept/work page path in Segment pageview event

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10642]
# What?
@taceybadgerbrook would like to be able to tell whether views of a work page have come from a particular concept page and vice versa

We currently send a source property with the page view event, but it is pretty generic e.g. "works_search_result" if we sent the page path (/works/f242ps6b) or (/concepts/fppbxh8b) we would be able to link the journey

**Comment by taceybadgerbrook** [comment]
@gestchild Thank you for this! I can hardly wait for the field to populate!

**Comment by taceybadgerbrook** [comment]
@gestchild I'm not able to see sourcePath in the metrics-conversion-prod space. I've checked in Management/Data views and it's not listed among the fields either.
