### ISSUE TITLE
CMP evaluation - Civic

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10657]
### Description
Evaluate Civic's suitability as a CMP for Wellcome's public-facing websites. This may involve running a free trial, looking at their available documentation and researching how the solution has been implemented by other organisations.

### Done when
Evaluation scorecard for Civic is populated: https://www.notion.so/wellcometrust/Cookie-products-consent-management-evaluation-a800675b44424784be2b6837999ccedb

**Comment by LaurenFBaily** [comment]
Pro license purchased in order to test further inc. styling.

**Comment by rcantin-w** [comment]
A basic version of our Pro license Civic UK integration is now in prod (behind toggle). It doesn't actually block tracking at the moment, meeting with Jamie this afternoon to work on adding their cookie to [our list of allowed cookies](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/cache/modules/cloudfront_policies/locals.tf#L1) and get a terraform refresher. I'll close this ticket once that's done (moving back to in progress in the meantime)

**Comment by rcantin-w** [comment]
I'll close this ticket as generic evaluation was done, and am now focusing on script loading/behaviour, which I'll create a different ticket for.
