### ISSUE TITLE
Use isAvailableOnline as a checkbox filter [FE]

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/wellcomecollection.org#10668]
## Definition of Ready
https://github.com/wellcomecollection/content-api/issues/107 is Done

## What
Add a checkbox filter in the Events search. We don't have those yet, so it will require the creation of a flexible "checkbox/boolean" filter.

## Done when
- New boolean filter is created
- Checkbox has disabled styles
- Query functions well

**Comment by rcantin-w** [comment]
Started a PR here and it works well https://github.com/wellcomecollection/wellcomecollection.org/pull/10704, I just need to discuss a few things with @j-jaworski in terms of placement - more info in PR. Will move to blocked until I can have that chat.

**Comment by rcantin-w** [comment]
Now available in prod (see events search behind toggle)
