### ISSUE TITLE
Create Figma library for styles and components

### ISSUE THREAD

**Issue by j-jaworski** [wellcomecollection/wellcomecollection.org#10667]
I need to build out all the styles and components from the site and cardigan into Figma, so we can quickly build pages and journeys across the site.

This will be ongoing work, as it could take some time, but initially it will just include

- [x] Responsive typographic styles
- [x] Space variables
- [x] Colours (based on Cardigan)
- [x] Buttons, links
- [ ] Icons 

@j-jaworski to rewrite for new designer's start

**Comment by j-jaworski** [comment]
After a discussion with Kasia, we have decided to tackle this together between and during other design tasks. Initially there is some work to get the basics set up, which I will attempt to complete this week

**Comment by pollecuttn** [comment]
Needs epic with tasks coming from that.

**Comment by j-jaworski** [comment]
Closing, will split tasks out into individual tickets under epic: Figma library components and styles
