### ISSUE TITLE
Locations filter [FE]

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/wellcomecollection.org#10670]
## Definition of Ready
-  https://github.com/wellcomecollection/content-api/issues/103 is Done
- Copy confirmed for the name of the options (online & in person?) @LaurenFBaily 

## What
- Adds a new dropdown filter for Online/in person

## Definition of Done
- Works. ;)

**Comment by LaurenFBaily** [comment]
We do 'Online' and 'In our building' on the event cards so I would be consistent with that for labels.

**Comment by rcantin-w** [comment]
In prod
