### ISSUE TITLE
Event search - tracking and understanding usage

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10675]
**We want to know if the following change has improved the user experience**

Added events to the global search (in a separate tab and to the 'All' aggregated page)

**Definition of success is**

**We'll know if we're succeeding if we measure the following metric and this happens**

**Definition of failure is**

**We'll know if we're failing if we measure the following metric and this happens**

**Comment by LaurenFBaily** [comment]
A few things to consider:

- Understand how people navigate to events (clicks and scroll depth on 'All' tab)
- Usage rate of filters (and which ones)
- CTR on SERP
- Use of search tab vs 'Stories'
- Whether we want to (or can) collect any qual feedback

**Comment by LaurenFBaily** [comment]
And hypotheses: https://www.notion.so/wellcometrust/Questions-draft-user-needs-and-hypotheses-3039379fae5840b89f0275cc88dd5299?pvs=4

**Comment by taceybadgerbrook** [comment]
@LaurenFBaily I've create a [table in Notion](https://www.notion.so/wellcometrust/Data-analysis-5d71147f9d8d4d5faeb83e1f73941056) listing requirements against initial ideas on how I could fulfill these and very rough estimates of build time. If you could have a look to make sure I've got the requirement straight and then indicate immediate priorities, would be great.

**Comment by LaurenFBaily** [comment]
Thanks Tacey, appreciate the effort estimates there too. I've added a priority ordering.

**Comment by taceybadgerbrook** [comment]
GA4 [events search funnel](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/nCsm3alYSsunFWwb5B8Qcw) (global search to events view).

**Comment by taceybadgerbrook** [comment]
I've tagged the following in GTM:

- events tab click
- All events button
- search result events card click
- events search All filters

and I've built GA4 Explore reports but I can't test out the Explore report unless there are events firing on the Production site. Could we bring events search out behind the toggle for a couple of hours so I can test what I've done?

**Comment by taceybadgerbrook** [comment]
[GA4 Explore report tracking GTM event search tags](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/cIlniX8rRJucWkEPO32K4Q) now working.

**Comment by taceybadgerbrook** [comment]
All links to GA4 explore reports and Looker Studio reports in the[ Notion document](https://www.notion.so/wellcometrust/Data-analysis-5d71147f9d8d4d5faeb83e1f73941056
).

**Comment by LaurenFBaily** [comment]
@taceybadgerbrook  Is there an index for the GA event names? Struggling with acronyms.

**Comment by taceybadgerbrook** [comment]
@LaurenFBaily indeed there is:
https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/analytics-event-tracking
