### ISSUE TITLE
Toggle: item request dates from itemsAPI

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/wellcomecollection.org#10693]
In order to easily test having the items' available dates returned from the items API, we need to add a toggle around the ItemRequestModal

When the toggle is ON the `options` [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/e2e423d8531d84e63556e058202aad8cf93824ae/content/webapp/components/CalendarSelect/CalendarSelect.tsx#L61) should be the list of `availableDates` returned directly with each requestable item from the items API 
https://github.com/wellcomecollection/catalogue-api/blob/cac7c2ad956e2bd8df1cc8877108b96e6d8fbff1/items/src/main/scala/weco/api/items/services/SierraItemUpdater.scala#L95

**Comment by kenoir** [comment]
Closed as part of https://github.com/wellcomecollection/wellcomecollection.org/pull/10848
