### ISSUE TITLE
Add Manage Cookies to footer

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10707]
### What
Add link to footer (after 'Privacy and terms') which opens the panel for users to manage their cookie/consent preferences with label 'Manage cookies'

### Done when

**Comment by LaurenFBaily** [comment]
Some pages (eg. library sign-in pages and exhibition guides) do not have a footer. Related task to create a minimal footer for these pages so users can still access essential links including cookie consent.

**Comment by rcantin-w** [comment]
Changes made behind toggle available in prod
