### ISSUE TITLE
Archive sector survey

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#10722]
Questions received by email, deadline Thursday 14 March:

Q34. How many page views did your archive services' website get in the last year? Enter '0' if not applicable.
Q35. How many page views on online research resources hosted by external providers (eg Ancestry, NLHF project websites)? Enter '0' if not applicable
Q36. How many page views did your archive service's online archive catalogue get in the last year? Enter '0' if not applicable

**Comment by pollecuttn** [comment]
@taceybadgerbrook Is what any works page with a dig code? A particular works page? Pretty sure we don't put dig codes on works pages though they are in the records used for works pages.

**Comment by pollecuttn** [comment]
Ah, okay. Dig codes could identify some external providers but I'm concerned some might mix Wellcome and non-Wellcome - see [my question in Slack](https://wellcome.slack.com/archives/CGXDT2GSH/p1710422060135039).

Our electronic journals and databases are all hosted by external providers.

**Comment by taceybadgerbrook** [comment]
Here's an example of what I can see in Kibana when I look at a works page linked to the Crichton Collection:
![image](https://github.com/wellcomecollection/wellcomecollection.org/assets/32418070/ed1e0393-33c6-467e-b722-e7a5fad1b025)

**Comment by taceybadgerbrook** [comment]
@pollecuttn ah, right you are. calm-ref-no. It looks like "digasylum" is the wellcome-digcode, though.

**Comment by taceybadgerbrook** [comment]
The total number of page views for the whole of wellcomecollection.org during the calendar year 2023-2024 was 18,256,000. The total number of page views for the collections content area was 10,331,000.

The question regarding page views of third party databases has been passed to Collections and Research
