### ISSUE TITLE
Allow bulleted lists in TextAndIcons/TextAndImage slices

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#10750]
Lists are being created using `.`s and a bunch of spaces because we haven't included the option to render lists in these slices.

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/1394592/65b495a8-ae19-48e1-b9a9-99992f3520ab)

**Comment by rcantin-w** [comment]
Deployed types and merged the code
