### ISSUE TITLE
State of items in Archive tree not updating and showing non-existing content

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10765]
**What**
As flagged by Sara Belingheri in an email to digitial@ with [a screen recording](https://wellcomecloud-my.sharepoint.com/personal/s_belingheri_wellcome_ac_uk/Documents/OH1%20media%20and%20transcript%20issues.mp4)
> Hi Colleagues,
I wanted to flag an issue with digitised audiofiles and transcripts I just came across while checking something for a reader. I’m assuming it’s something to do with cookies, as it solves itself temporarily when going incognito.
Some items in [OH1 (Thalidomide: An Oral History)](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwellcomecollection.org%2Fworks%2Fd32pgtn4&data=05%7C02%7CR.Cantin%40wellcome.org%7C99a6375afd1b4cae6a1f08dc531b4f8e%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C638476623974347518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Ma17XDPgxN4sNLzRXlacUX3bQdHDYy%2BMB3r9y206AeU%3D&reserved=0) are closed for data protection (OH/1/F, K, L, M and Q).  No recordings or transcripts are available for them online (nor should be), however when a user lands on those item records having been on an open record before, they see the recordings and transcripts of the previous record. [...]
Since the closed records are not actually available, it is not a sensitive issue, but it could be confusing (or cause alarm).

**Where**
- Go to https://wellcomecollection.org/works/wdbmggee (no transcript available)
- In the archive tree, click on "Mat Fraser (OH1/E/1)"
- See audio players and downloadable transcript link
- Using the archive tree, click on "Anonymised individual B: interview 1 (OH1/K/1)", which takes you back to the first page.
- Notice there are audio players and a transcript available to download. The copy has changed to refer to the work you are on but if you download it, you see it's Mat Fraser's.

Probably not updating the state properly here.

**Comment by pollecuttn** [comment]
Size: small
