### ISSUE TITLE
Amend slices that use labels, so they work with slice machine

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10791]
Relates to #10789

## Background
We currently make use of [slice labels](https://prismic.io/docs/slice#in-the-legacy-builder) to allow content editors to label a particular slice. We then use this label to choose how the slice should be displayed. For example, a quote slice can be displayed as a 'pull' quote or a 'review' quote.

Labels are not supported by slice machine (it uses the concept of variations, which will allow the editors to see what each variation looks like when making a choice).

It is likely we will eventually move to using variations (issue to come), but in the interim we need to make things work with the current model.

## Task
When we convert our legacy slices to slice machine slices within our custom types all the data should map across (to be verified with our prismic dev environment). However, label data will have nowhere to go.

- [x] Establish which of our slices currently use labels
- [x] Create a select field on those slices with the same API id and choices as the current label field

**Comment by rcantin-w** [comment]
This is where I could find labels, keeping in mind that not selecting any (think it shows as `...`) is also a valid option;
- [Article-body](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/prismic-model/src/parts/bodies/article-body.ts#L14)
  - **editorialImage**: Featured, Supporting, Standalone
  - **gifVideo**: Supporting
  - **iframe**: Supporting, Standalone
  - **editorialImageGallery**: Standalone, Frames
  - **quoteV2**: Pull, Review (as we know, these two seem to be doing the same thing)
- [Body](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/prismic-model/src/parts/bodies/body.ts#L44)
  - **editorialImage**: Supporting, Standalone
  - **quote**: Pull, Review (this one I'm a bit confused by the naming but... it's the same as quoteV2?)
