### ISSUE TITLE
Display transcripts along with the video and audio components of guides

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10823]
Relates to #10820

We need to be able to display transcripts alongside the audio and video players:

https://wellcomecollection.org/guides/exhibitions/ZSaiohAAACMAlJbK/audio-without-descriptions

<img width="1258" alt="Screenshot 2024-04-25 at 14 36 21" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/6051896/cf7fdf1f-6163-420b-a98c-5a4c6047fb5d">

https://wellcomecollection.org/guides/exhibitions/ZSaiohAAACMAlJbK/bsl

<img width="1267" alt="Screenshot 2024-04-25 at 14 36 35" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/6051896/0b984f40-9972-41ac-ac3f-c49fde1e1822">

**Comment by LaurenFBaily** [comment]
Dependent on https://github.com/wellcomecollection/wellcomecollection.org/issues/10914

**Comment by LaurenFBaily** [comment]
Covered by new tickets #11038 and #11043

**Comment by LaurenFBaily** [comment]
Closing as related to above tickets.
