### ISSUE TITLE
Links to exhibition resources from Exhibition page

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10821]
Following #10821, relates to #10822

Update the links on the [Exhibition page](https://wellcomecollection.org/exhibitions/ZJ1zCxAAACMAczPA) to more clearly signpost the different resources.

<img width="919" alt="Screenshot 2024-04-25 at 11 54 19" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/6051896/66517006-fadb-4e4c-aa3e-ba2c43adec7c">

**Comment by LaurenFBaily** [comment]
Can advise on content design/copy for a basic update but worth having @kasiabbb look at the exhibition page hierarchy and 'exhibition access content' grouping, taking into account any insights from the visual stories work.

**Comment by LaurenFBaily** [comment]
Duplicates #10967
