### ISSUE TITLE
Change cookie policy link in cookie banner

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10880]
The current cookie policy which covers wellcome.org and wellcomecollection.org is being replaced with a dedicated cookie policy page for wellcome.org as they are releasing their new cookie consent management today.

Temporarily (until our new cookie policy page and preference centre are live) we need to link to this temporary cookie policy page from our existing cookie banner: https://wellcome.org/wellcome-collection-cookie-policy

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/160641757/549267fa-6421-43a6-a168-544aeed2a6c4)

**Comment by rcantin-w** [comment]
Change is in prod (cache clearing might be needed to get it)
