### ISSUE TITLE
Treat works with non-existing IIIF Manifests

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10907]
Some works are being flagged in the alerts channel when a user tries to access the Item Viewer (https://wellcome.slack.com/archives/CQ720BG02/p1717403402624589).

This is because it can't find the IIIF Manifest 
`Error: Tried to retrieve IIIF Manifest at https://iiif.wellcomecollection.org/presentation/PPROS/K/3/10, but it's 404-ing. To fix, try running the "Rebuild IIIF" task in the iiif-builder dashboard.`
But it does not exist for a known reason: Archivematica fails to characterise the files and therefore we have no dimensions for them. It's something that needs fixing from Archivematica's side and there is an ongoing conversation for this.

On the frontend, what then happens is that the catalogue API tells us there is a IIIF manifest, but when we go and get it it's not there, so the "View Items" button is still offered up to the user. 

As Gareth says in the thread:
> We could do what you suggest [hide the button], but we'd need to default to showing the button if there is a link to the manifest in the catalogue API (so it works without javascript), but we do fetch the manifest client side, so we know to replace the link with video/audio players. At that point, if it fails, we could hide the link. Alternatively, we could rewrite things so that we make both calls server side before rendering the page (although for performance reasons we try not do do this). We'd also still need to be alerted to the fact that the manifest didn't load, so we know to fix it.

If we want to fix this and stop the alerts coming into the channel/make them more useful, we could discuss this ticket and agree to a fix.

**Comment by rcantin-w** [comment]
I _think_ we could filter it out so only Archivemetica alerts are blocked. I _think_ the IIIF rebuilds that Ashley could fix looked like `https://iiif.wellcomecollection.org/presentation/v3/b2945024x` and the ones that couldn't were `https://iiif.wellcomecollection.org/presentation/PPROS/K/3/10` ? So we could try to use that to only implement the "fix" for the latter?

**Comment by rcantin-w** [comment]
Apparently the `https://iiif.wellcomecollection.org/presentation/PPROS/K/3/10` Location URL is valid for Born Digital items. 
I've lost track of BD a bit; should they offer the Available online "view" button?
And if not, does that mean that we can hide that button if we recognise the item as being BD?

**Comment by gestchild** [comment]
It's a bit complicated, but sometimes the view button should be available.

We don't actually detect whether something is born digital or not, we can only tell from the iiif-manifest if it is renderable or not, i.e. a file such as an image, video or audio that iiif has always been used to describe OR some other type of file.

If we detect the presence of one of the other types of file we show the download list and not the view button.

However, if the iiif-manifest contains things that are all renderable, e.g. only images, we show the view button.
There is no way to tell from the manifest that these are born digital in these circumstances.

Interesting, what you say about the url structure for the manifests. I don't know if this is a robust way to distinguish between born digital and non born digital. FYI there is work in the pipeline to make this distinction in the catalogue API

**Comment by rcantin-w** [comment]
Thank you for that! Very clear. 
We could keep an eye on the URL shape but anyway, this confirms we'll have to go a different route for hiding the button/not.

**Comment by rcantin-w** [comment]
Deployed and [communicated](https://wellcome.slack.com/archives/CQ720BG02/p1721908459769039?thread_ts=1717403402.624589&cid=CQ720BG02)
