### ISSUE TITLE
Update Gitbook information with new cookie processes

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10912]
Following the release of the new Cookie consent strategy, we have to update our documentation as per [the release plan](https://www.notion.so/wellcometrust/CMP-release-plan-19c21a38a01945dca6bc85d690c02db9#f1234da1c7aa4a71bd4a116d937ac794).

- [ ]  Update [GitBook](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/cookies) / GSuite
    - [ ]  Add a “How to” on how to add a new cookie/cookie category and what that process looks like on all levels.

**Comment by rcantin-w** [comment]
I added this to the bottom

> **Coding in the new category**
A new category can be added to the preference centre modal through the [CivicUK config file](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/views/components/CivicUK/index.tsx).
Remember that consent updates will need to be sent to Google through gtag , which we do [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/common/views/pages/_app.tsx#L113).
**Custom HTML tags**
Whilst we previously added them through GTM to be owned by the Digital Analyst, we chose to move it to the codebase for a few reasons. We don't currently have a Digital Analyst, and we want to control code that gets injected to insure quality and security.
So if a new Custom HTML tag is to be added, a ticket should get created to get taken on by a developer. They should ensure the consent was given for whatever category it falls into before it fires, and that it does fire when consent changes.

**Comment by LaurenFBaily** [comment]
Perhaps @pollecuttn you could have a quick look through and see if it makes sense to someone who hasn't been immersed in the cookie world.

**Comment by pollecuttn** [comment]
My only comment is on this in [GitBook](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/cookies):

> Whilst we previously added them through GTM

Not sure if 'them' is custom HTML tags or cookies? Could that be made explicit, please @rcantin-w

**Comment by rcantin-w** [comment]
I've just amended the paragraph @pollecuttn  👍

**Comment by pollecuttn** [comment]
This can be closed now?
