### ISSUE TITLE
Upgrade Node: Prismic-model

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10928]
Parent ticket with all information: https://github.com/wellcomecollection/wellcomecollection.org/issues/10846

We're not 100% this is needed since the move to slice machine, but this ticket can be used to investigate and tidy up unnecessary files if that is the case (it does have a Dockerfile at the moment).

If an upgrade is in the cards, then:
- [ ] Node has been updated to the highest possible version
- [ ] `.nvmrc` file has been added/updated

**Comment by davidpmccormick** [comment]
Done in #11001
