### ISSUE TITLE
Custom html tags not firing on first page after consent given

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10953]
### What
Same issue as #10949 but we think a different solution needed for our custom html tags.

### [Possible solutions from Slack chat](https://wellcome.slack.com/archives/CUA669WHH/p1718019997427879?thread_ts=1717758468.480019&cid=CUA669WHH)
1. Create a new event/trigger that looks at the consent state in the data layer eg.https://github.com/Ayudante/gtm-consent-state
2. Move custom html tags out of GA into our codebase and manage triggering them ourselves from the civicuk consent change callbacks

**Comment by rcantin-w** [comment]
Pausing this until I can ask Gareth about the "Performance timing tracking" script, David and I aren't sure what it's used for, wondering if it was pre-Core web vitals.

Also need to ponder a bit more on the scripts not being removed/added **on** consent changes, but on the page next page load. Do we mind?

**Comment by rcantin-w** [comment]
Both the scripts we currently have in GTM can be added in without depending on consent as they do not set any cookies.

**Comment by rcantin-w** [comment]
Changes now in prod, they should fire all the time (unless no javascript) as there is no consent requirements anymore. I will now delete them from GTM.
