### ISSUE TITLE
Infoblock documentation

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10959]
@LaurenFBaily to update the Slice description here https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/451yLOIRTl5YiAJ88yIL/custom-slices#info-block based on #10885 

And consider renaming it.

**Comment by LaurenFBaily** [comment]
Made an update to Gitbook slice documentation to better reflect how this slice is used in practice and be clearer about recommended use. 

Haven't changed the name as there's not really evidence to suggest current naming is an issue and my best suggestion (Info Highlight) doesn't seem distinct/specific enough to make an impact. Could still do this in the future.
