### ISSUE TITLE
Change 'exhibition' to 'display' in subheadings based on exhibition type

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10985]
### What
Change word 'exhibition' to 'display' in hard-coded subheaders for upcoming gallery 3 exhibitions (dynamically based on exhibition format = 'display'?). Optional page sections with headings are: 
- [Exhibition] highlights
- In this [exhibition]
- [Exhibition] access content

### Why
New series of gallery 3 exhibitions will be referred to as 'displays' in order to manage visitor expectations (in terms of scale) and also avoid parallels being drawn with Medicine Man

### Done when

**Comment by LaurenFBaily** [comment]
Suggestion discussed in Planning - could we use exhibition format for other types of exhibitions eg. installation and season (exception of 'permanent exhibition' which should just be exhibition)

**Comment by georgiaewhitney** [comment]
I believe the first [Exhibition] highlights is manually set by the EditorialImageGallery slice.
![Screenshot 2024-07-08 at 15 08 36](https://github.com/wellcomecollection/wellcomecollection.org/assets/81175151/e724c4f0-2b33-448c-b4a3-8102038a2818)
