### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#11016]
## What

Licence information on the METS is not making it's way onto the works page

## Where

PP/DBL/A/1/17
https://wellcomecollection.org/works/qd84awx8
This should be CC-BY-NC

For comparison, items ingested before the one above that is In Copyright does have the license info e.g. SA/REN/B/21/1 https://wellcomecollection.org/works/g7zn5j4n
  
![SARENB211](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/835fb621-bcd9-4d25-95f1-b2f6d295caff)

## To do
- Display licence information on works

From [Ashley](https://wellcomecloud-my.sharepoint.com/:w:/g/personal/a_ray_wellcome_ac_uk/EeeDxW3Cy19Ak7oPBGgoAlMBVleBArNbU9u0vkrT28S_pg?e=DOWCOt&clickparams=eyAiWC1BcHBOYW1lIiA6ICJNaWNyb3NvZnQgT3V0bG9vayIsICJYLUFwcFZlcnNpb24iIDogIjE2LjAuMTY3MzEuMjA3MTYiLCAiT1MiIDogIldpbmRvd3MiIH0%3D&CID=73DFE4CF-7EAB-4534-914D-5FE81653B914&wdLOR=cCCD4194C-C330-47B3-AECA-6D5C100F8FFE)

**Comment by rcantin-w** [comment]
[Slack convo in progress](https://wellcome.slack.com/archives/C02ANCYL90E/p1724408305952489)

**Comment by rcantin-w** [comment]
As discussed in the aforementioned Slack conversation (and here's a bonus [digirati channel convo](https://wellcome.slack.com/archives/CBT40CMKQ/p1724421802356249)), we're moving this ticket to the platform board as it's an issue with the METS transformer.

cc @jcateswellcome @kenoir - this is the one ticket blocking the release of Born Digital work, if it needs prioritising against other work.

**Comment by paul-butcher** [comment]
I've had a quick look and the transformer *should* be getting licence information from the METs files ([here](https://github.com/wellcomecollection/catalogue-pipeline/blob/e4123a9d8b9ba4b6be6708fc26673978042833f0/pipeline/transformer/transformer_mets/src/main/scala/weco/pipeline/transformer/mets/transformers/PremisAccessConditions.scala#L13))

The fault may still lie in the [MetsLicence transformer](https://github.com/wellcomecollection/catalogue-pipeline/blob/fadbc6215144f641909a4a07d6a60981ac31fb9f/pipeline/transformer/transformer_mets/src/main/scala/weco/pipeline/transformer/mets/transformers/MetsLicence.scala) which (I think) assumes that the licence will look the same in both Goobi and Archivematica METS files. That may not be the case.
