### ISSUE TITLE
Add event tracking for born digital downloads

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11012]
### What
Add event tracking to all download links of born-digital files via GTM.

### Why
We can measure usage of new born-digital download feature.

### Background
https://www.notion.so/wellcometrust/Born-digital-files-available-to-download-4b6a311ef48a4ad1bc7428b66d0d3768?pvs=4

**Comment by rcantin-w** [comment]
Moving back to In Progress as we need to fix the `stopPropagation` issue
