### ISSUE TITLE
Change copy of born digital info message

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11013]
Update born-digital information message text to the below:

### This contains born-digital items

Born-digital items are materials created in a digital format, including digital images, documents, websites, audio, video, email, and more.

Our born-digital items cover many file formats, some of which modern computer software may no longer support. **We cannot guarantee that you can view the item once you have downloaded it.**

**Comment by rcantin-w** [comment]
This seems to be in production now so will close.
