### ISSUE TITLE
Global search explorations

### ISSUE THREAD

**Issue by dana-saur** [wellcomecollection/wellcomecollection.org#11025]
- [x] IA - how should functional content be organised?
- [x] Brainstorm
- [x] Design crit with team

https://www.figma.com/design/qssPpJy1lOWSFtuACajkZr/Global-search?node-id=1283-82&t=8p3FfTZ4uMFOghYV-1

**Comment by pollecuttn** [comment]
Blocked whilst Dana is away

**Comment by dana-saur** [comment]
Explorations in Figma: https://www.figma.com/design/qssPpJy1lOWSFtuACajkZr/Global-search?node-id=1283-82

**Team crit #1** 
- Designs: https://www.figma.com/design/qssPpJy1lOWSFtuACajkZr/Global-search?node-id=4381-7957
- Miro board for kick off and feedback: https://miro.com/app/board/uXjVK10sW_o=/?share_link_id=782261235980
