### ISSUE TITLE
Create highlight tour stop page

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11037]
### What
Build highlight tour stop page according to [designs](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&m=dev&t=RuXOgPioiApqd7op-1).
- Breadcrumbs on desktop
- X to close on tablet/mobile breakpoints
- Next & previous (sticky to bottom of screen)
- Title and stop information (sticky to top of screen)
- Stop image (Dependent on #11042)
- For video tour stops display YouTube video
- For audio tour stops display audio player

**Transcripts #11038 & audio player updates captured in separate tickets**:

### Why
Each stop of the highlight tour will now have its own page. This means that transcripts can be displayed easily below the media content, audio/video from multiple stops can no longer play at the same time and each page is lighter (performance-wise).

### Background
[Improve usability of exhibition guides](https://wellcometrust.notion.site/Improve-usability-of-exhibition-guides-e846b1cd33b049c384fcab7ab4b3b05e?pvs=4)

### Done when

**Comment by kasiabbb** [comment]
Design resources: 

https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&m=dev&t=RuXOgPioiApqd7op-1

- UI Element animations (such as buttons) - 150ms, Ease Out. More info: **Spect Tab**
- transitions between stops: 300ms, Ease Out. More info: **Final UX Flow Tab**
- See [Prototype](https://www.figma.com/proto/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?page-id=361%3A382&node-id=1706-10575&viewport=541%2C15214%2C0.53&t=JFPW8qPteS0nIw9L-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1706%3A10575) for how the effects should work in practice


- hover & click states are the same on desktop for now. 
- Hover state on desktop=tap on touch screen. 

![Image](https://github.com/user-attachments/assets/5b2d9bd7-54c6-47b1-901f-280a58f9b7ba)

**Comment by davidpmccormick** [comment]
> Breadcrumbs on desktop

I don't see these in the designs (they're on the list/index, but not the individual stop). Is this a deliberate omission?

**Comment by LaurenFBaily** [comment]
Sorry David, may have been my mistake or designs were updated after I created ticket. Go with designs (no breadcrumbs).

**Comment by dana-saur** [comment]
@davidpmccormick looks great! A few minor spacing and font size bits of feedback and a couple of accessibility things. 

I've left the QA feedback here: https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=1947-1490&m=dev&focus-id=1947-1550

FYI @LaurenFBaily

**Comment by kasiabbb** [comment]
Hello! Final QA: 

Everything seems to look good, apart from one small thing I noticed: seems like there is no margin on the right side of the screen when the transcript is open. I think the margin should be mirroring the left side (left screen edge to left side of the show/hide button)

Current state:
<img width="378" alt="Screenshot 2024-09-10 at 11 21 48" src="https://github.com/user-attachments/assets/c2a6f735-7f77-41b0-bb3e-0b3d1140b07b">
<img width="377" alt="Screenshot 2024-09-10 at 11 22 27" src="https://github.com/user-attachments/assets/ba55f7da-a2f8-4f7c-9017-41805ea5c61f">

Desired: 
<img width="378" alt="Screenshot 2024-09-10 at 11 26 51" src="https://github.com/user-attachments/assets/1b0f1417-ac64-4ee6-aa05-94b4111220d8">

**Comment by rcantin-w** [comment]
Change has been deployed to prod, ready for QA.
