### ISSUE TITLE
Update bsl video tour page header

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11036]
### What
Update header area of [BSL video highlight tour page](https://wellcomecollection.org/guides/exhibitions/Zdcs4BEAACMA6abC/bsl)

Design link to be added.

- [ ] Add breadcrumbs
- [ ] Change subtitle from 'British Sign Language videos' to 'British Sign Language tour with subtitles'
- [ ] Remove blue background & buttons
- [ ] Add icons

### Why
- Make visual design more consistent
- Simplify user navigation by using common pattern of breadcrumbs rather than two buttons

### Done when

**Comment by kasiabbb** [comment]
See design on [Figma](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&t=1YlSKBWbJdNsKy8F-1), Key Screens space

![Image](https://github.com/user-attachments/assets/d5fead90-ccfe-46be-98e1-aaadce964aba)

**Comment by rcantin-w** [comment]
It's in prod, If you turn on the "Exhibition Guides redesign/restructure work" toggle you can see it.

@kasiabbb fyi! Let's catch up after you've reviewed and we can create new tickets off the back of what we discuss.
