### ISSUE TITLE
Updates to Exhibition Text page

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11034]
### What
Update header area to new design & add breadcrumb

Existing page: https://wellcomecollection.org/guides/exhibitions/ZofmZBEAACgA28LP/captions-and-transcripts 

### Background
Part of [Improve usability of exhibition guides](https://wellcometrust.notion.site/Improve-usability-of-exhibition-guides-e846b1cd33b049c384fcab7ab4b3b05e?pvs=4)
 
### Done when

- [ ] Matches design
- [ ] Reviewed by @kasiabbb

**Comment by kasiabbb** [comment]
See the design on [Figma](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&t=1YlSKBWbJdNsKy8F-1) - key screens space, Exhibition text

![Image](https://github.com/user-attachments/assets/8ca44fde-3541-4afb-9a0d-0091c4c874b3)

**Comment by rcantin-w** [comment]
See [Slack conversation for discussion about the scope of this ticket](https://wellcome.slack.com/archives/CUA669WHH/p1721917272984279)

More information can also be found in [the PR description](https://github.com/wellcomecollection/wellcomecollection.org/pull/11058)

I'm sure once it's live and being reviewed we'll make sure small changes (especially to spacing), so won't close the ticket as done once merged.

**Comment by rcantin-w** [comment]
It's in prod, If you turn on the "Exhibition Guides redesign/restructure work" toggle you can see it.

@kasiabbb fyi! Let's catch up after you've reviewed and we can create new tickets off the back of what we discuss.

**Comment by kasiabbb** [comment]
@rcantin-w so the subheading should be "Exhibition text", and should not include any transcripts. I have amended the design below: 

![Image](https://github.com/user-attachments/assets/1089e9b8-7b21-4ae0-b6f5-c22a50485feb)

**Comment by kasiabbb** [comment]
added a QA ticket: https://github.com/wellcomecollection/wellcomecollection.org/issues/11081
