### ISSUE TITLE
Update cookie logic for QR codes

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11039]
### What
1. Stop 1 QR code is just a link to that exhibition guide landing page ([eg. the Jason exhibition guide landing page](https://wellcomecollection.org/guides/exhibitions/Zdcs4BEAACMA6abC)). Links to audio highlight tour or bsl video tour just open those pages (no special behaviour).
2. WC_userPreferenceGuideType cookie is set when either the audio highlight tour card or bsl video tour card is selected. No cookie set when Exhibition Text is selected.
3. All other stops after Stop 1 require additional behaviour. Eg. Url for QR code for Stop 2, when scanned for the first time should take user to digital guide landing page. Once they have selected the audio or bsl tour, that should take them directly to the Audio stop 2 page or the BSL video stop 2 page. If exhibition guide preference cookie has already been set then the QR code will take them straight to the audio stop page 2 or video stop page 2.

See agreed UX flows here: https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&m=dev&t=RuXOgPioiApqd7op-1

### Why
Allows users to choose whether they want an audio or BSL version of the highlight tour and then remember their preference if they use QR codes to access further stops.

### Background
[Improve usability of exhibition guides](https://www.notion.so/wellcometrust/Improve-usability-of-exhibition-guides-e846b1cd33b049c384fcab7ab4b3b05e?pvs=4)

### Done when
- [ ]

**Comment by kasiabbb** [comment]
Design resources: 

https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&m=dev&t=RuXOgPioiApqd7op-1

FInal UX Flow, Accessing the guide board

**Comment by rcantin-w** [comment]
Had initial chats with @davidpmccormick on how we could make this work, I'll write up the start of a suggestion on Monday. We will have to consider how we support current QR codes and legacy exhibitions that won't have a page for each stop.

**Comment by rcantin-w** [comment]
Deployed to prod and seems fine. Will go test in the museum after standup but am closing this ticket.
