### ISSUE TITLE
Update audio highlight tour page header

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11035]
### What

Update header area of [Audio highlight tour page](https://wellcomecollection.org/guides/exhibitions/Zdcs4BEAACMA6abC/audio-without-descriptions)

Example, link to final designs to be added:

![Image](https://github.com/user-attachments/assets/53bba418-ceb7-4ef3-bc88-c70065bcb6e0)

- [ ] Add breadcrumbs
- [ ] Change subtitle from 'Audio' to 'Audio highlight tour with transcripts'
- [ ] Remove red background & buttons
- [ ] Add icons

### Why
- Make visual design more consistent
- Simplify user navigation by using common pattern of breadcrumbs rather than two buttons

### Done when

**Comment by kasiabbb** [comment]
see design on [Figma](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&t=1YlSKBWbJdNsKy8F-1), Key Designs - Mobile space

**Comment by rcantin-w** [comment]
It's in prod, If you turn on the "Exhibition Guides redesign/restructure work" toggle you can see it.

@kasiabbb fyi! Let's catch up after you've reviewed and we can create new tickets off the back of what we discuss.
