### ISSUE TITLE
Add icons to digital exhibition guides listing page

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11033]
### What
Update design of exhibition guides listing page ([this page which displays cards for all current exhibition guides](https://wellcomecollection.org/guides/exhibitions)) to include icons as per designs

Screenshot as example, to be replaced with link to designs:
![Image](https://github.com/user-attachments/assets/a23274be-eed5-470c-92ee-69fa7e5b8399)

Icons logic:
AD = Audio highlight tour is available
TEXT = Always shows, as applicable to Exhibition text guide being available and/or transcripts as part of audio/video content
BSL = BSL video highlight tour is available

### Why
To indicate what resources are available (audio description, BSL, ) as these vary depending now that we allow Exhibition text without a highlight tour for example.

### Background
Part of [Improve usability of exhibition guides](https://wellcometrust.notion.site/Improve-usability-of-exhibition-guides-e846b1cd33b049c384fcab7ab4b3b05e?pvs=4)

**Comment by kasiabbb** [comment]
see design on [Figma](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&t=1YlSKBWbJdNsKy8F-1), Key Designs space

**Comment by rcantin-w** [comment]
@kasiabbb this is now in prod behind the toggle. I also added the missing icons on this page https://wellcomecollection.org/guides/exhibitions/Zdcs4BEAACMA6abC (we originally said we'd wait but it's behind the toggle anyway so I went ahead with it).

Feel free to close ticket or add comments if anything is amiss!

**Comment by rcantin-w** [comment]
Fix in prod  for @kasiabbb to review



![Image](https://github.com/user-attachments/assets/1e3a4a2b-424e-44ae-a2e7-814379e9de89)

**Comment by kasiabbb** [comment]
@rcantin-w one final thing - the padding should be consinstent across the pages, at the moment it is consistent on desktop but not on mobile (screens attached). Could we please have it at 8x16x16 on both pages? that seems to be consistent across other pages

![Image](https://github.com/user-attachments/assets/67ca7ce6-c5c2-4cf0-b038-f7a4688faca0)

![Image](https://github.com/user-attachments/assets/7e093028-ff70-4195-bb5b-1f861464e64e)

**Comment by rcantin-w** [comment]
@kasiabbb ready for further review
