### ISSUE TITLE
Add image field to highlight tour stops

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11042]
Add an optional image field into Prismic Exhibition highlight tour for each Stop slice.

**Comment by kasiabbb** [comment]
Design resources:

https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=1434-16939&t=RuXOgPioiApqd7op-1

Spec tab, Tour stop overview
