### ISSUE TITLE
Get involved page: text in the wrong place

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#11050]
## What

See [Slack](https://wellcome.slack.com/archives/CUA669WHH/p1721297684063939) 

This text is at the bottom of the page and should be at the top per https://web.archive.org/web/20240409063927/wellcomecollection.org/pages/YDaZmxMAACIAT9u8

![image](https://github.com/user-attachments/assets/d22689f9-56f9-4dbf-ba2a-dad3be4c83a1)

Possibly due to the new body/slices and landing pages

## Where

Get involved page: https://wellcomecollection.org/pages/YDaZmxMAACIAT9u8

## To do
- Display text at the top of that page as it was previously

**Comment by rcantin-w** [comment]
Investigation started, [comments here](https://wellcome.slack.com/archives/CUA669WHH/p1725532166935299)

This seems to be a bug for pages of the format `landing`, of which there are currently 6:

   http://wellcomecollection.org/pages/Wuw2MSIAACtd3Stq
   http://wellcomecollection.org/pages/YDaZmxMAACIAT9u8
   http://wellcomecollection.org/pages/YCAVKxIAACIAV1oF
   http://wellcomecollection.org/pages/X8ZTSBIAACQAiDzY
   http://wellcomecollection.org/pages/Wuw2MSIAACtd3Ssg
   http://wellcomecollection.org/pages/YBfeAhMAACEAqBTx

**Comment by davidpmccormick** [comment]
accidentally auto-completed this yesterday by carelessly using the word 'fix' in a comment. This time it is _actually_ fixed, in #11399
