### ISSUE TITLE
Image and 'Whats on this page' hierarchy changed

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11052]
The lead/main image and in-page nav block ('What's on this page') appear to have switched places in the order of the page. The image should come first.

See example here: https://wellcomecollection.org/pages/Wuw19yIAAK1Z3Smk 

Noticed on Thurs 18th July.

**Comment by LaurenFBaily** [comment]
Could be related to #11050 as noticed this change at a similar time.

**Comment by pollecuttn** [comment]
Also see on 1 August on the Databases page: https://wellcomecollection.org/pages/YDaP2BMAACUAT7DS (cf 5 March 2024: https://web.archive.org/web/20240305070745/https://wellcomecollection.org/pages/YDaP2BMAACUAT7DS)

**Comment by davidpmccormick** [comment]
Completed in #11397 

This has also fixed how certain headers appear, as well as how cards on those pages are laid out (e.g. the [collections](https://wellcomecollection.org/collections) page header is more significant as it counts as what we've called a `sectionLevelPage`, and the cards lower down the page are no longer awkwardly aligned offset to the header before them.
