### ISSUE TITLE
301 redirects

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11069]
### What
Create 301 redirects:
https://wellcomecollection.org/pages/Wuw2MSIAACtd3Stq -> wellcomecollection.org/about-us
https://wellcomecollection.org/pages/YDaZmxMAACIAT9u8 -> wellcomecollection.org/get-involved
https://wellcomecollection.org/guides/exhibitions -> wellcomecollection.org/exhibition-guides

### Background
[See epic: Descriptive urls](https://www.notion.so/wellcometrust/Descriptive-urls-ed7cf0014a584b9ab7a9f9b8e96d3742?pvs=4)

### Done when

**Comment by gestchild** [comment]
Maybe not for this, but when we start redirecting stories/events etc. would be worth looking at https://nextjs.org/docs/app/building-your-application/routing/redirecting#redirect-function
