### ISSUE TITLE
Change way urls are created for Page content type

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11072]
[“Pages”](https://docs.google.com/spreadsheets/d/1e12ebSBzxjqJGPRZnrjmBt36jvpQEPMEjJ-B_jibdoM/edit?usp=sharing)

Webpages with the content type “Page” are displayed in a number of areas around the site. Their url structure should reflect where they sit on the site eg.

[www.wellcomecollection.co.uk/visit-us/accessibility](http://www.wellcomecollection.co.uk/visit-us/accessibility)

[www.wellcomecollection.co.uk/collections/accessing-our-collections](http://www.wellcomecollection.co.uk/collections/accessing-our-collections)

[www.wellcomecollection.co.uk/contact-us](http://www.wellcomecollection.co.uk/contact-us)

**Comment by rcantin-w** [comment]
Changes applies in production
