### ISSUE TITLE
Bring born-digital MVP out from toggle

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11076]
As part of removing the toggle, we have a few pieces that have come out that are not blockers, but need doing once we're happy with the work. They weren't officially part of the epic, so listing them here as to not be forgotten. Feel free to add more:

### To do

- [x]  https://github.com/wellcomecollection/wellcomecollection.org/issues/11065

- [x] [Remove cookie from test](https://github.com/wellcomecollection/wellcomecollection.org/blob/13a0f8ffd6d1471ad43d09b0488490f2c3598332/playwright/test/helpers/contexts.ts#L191)

**Comment by pollecuttn** [comment]
https://github.com/wellcomecollection/wellcomecollection.org/issues/11016 is a blocker to born digital being released
