### ISSUE TITLE
Change articles to stories in url structure for articles

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11071]
### What
All individual stories should use /stories/ instead of /articles/ and be redirected eg.

https://wellcomecollection.org/articles/ZpoyNhAAAFyEjk  becomes www.wellcomecollection/stories/the-wishing-tree-of-loch-maree

### Why
Update to match language of the site.

### Background
[See epic: Descriptive urls](https://www.notion.so/wellcometrust/Descriptive-urls-ed7cf0014a584b9ab7a9f9b8e96d3742?pvs=4)

**Comment by LaurenFBaily** [comment]
/stories/comic should point to Stories search with comics format filter.

**Comment by gestchild** [comment]
Changes deployed on 29/10/2024 about 13:35 - added to [Notion Doc](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/changes-affecting-data)
