### ISSUE TITLE
Query content types by UID

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11073]
Query [these content types](https://github.com/wellcomecollection/wellcomecollection.org/issues/11023) by UID

Initially we should do this in a way that allows us to request the pages in the current way (by id) and the new way (by uid) so the same page is viewable at /guides/YL9OAxIAAB8AHsyv and /guides/archives-at-wellcome-collection for example.

We should add a rel="canonical" link element that points to the uid version of the page.

**Comment by gestchild** [comment]
WIP for this https://github.com/wellcomecollection/wellcomecollection.org/tree/fetch-by-uid

**Comment by rcantin-w** [comment]
https://wellcome.slack.com/archives/CUA669WHH/p1725961491619959

> UID urls are now supported in prod (e.g. https://wellcomecollection.org/articles/shadows), although they are not the default and no link yet points to them.
