### ISSUE TITLE
Migrate Jason exhibition to new exhibition guide content types

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11140]
As we'll eventually move away from the deprecated `exhibition-guides` content type and want to support new QR logic only, we'll move the Jason exhibition guide to the new models.

Next step is https://github.com/wellcomecollection/wellcomecollection.org/issues/11131

**Comment by rcantin-w** [comment]
Guides are viewable if you use Prismic staging, where I've assigned them to Kola Nut. I did that to preserve the legacy guides for now, which is sometimes useful for styling/QR code testing purposes.

https://wellcomecollection.org/guides/exhibitions/ZthyQxIAACQALx4_?cachebust=344

Spacing fix: https://github.com/wellcomecollection/wellcomecollection.org/pull/11144
Empty content fixes: https://github.com/wellcomecollection/wellcomecollection.org/pull/11141

**Comment by rcantin-w** [comment]
@LaurenFBaily if you're willing to QA the Jason exhibition guide, turn on Prismic staging (and the EG work toggle as well) and you can see it here: https://wellcomecollection.org/guides/exhibitions/ZthyQxIAACQALx4_ (as "Kola Nut"'s)

**Comment by rcantin-w** [comment]
Also, @LaurenFBaily do we want to add HotJar to the new pages?

**Comment by LaurenFBaily** [comment]
Yes but I've opened a ticket for all the tracking here: #11142

**Comment by rcantin-w** [comment]
For Hard Graft, but these new pages will need it to so could we add them to the ticket?

**Comment by LaurenFBaily** [comment]
Ok, reviewed audio tour, bsl tour and exhibition text and all the content matches.

Will make a note for editorial to add a task to their backlog to add images for each of the audio stops.

**Comment by rcantin-w** [comment]
Nice, so the next steps would be to 
- Get the new QR codes and test them
- Change them in the exhibition, ideally we'd know exactly when it gets done so we can flip over which pages are used for the guides.
- Delete the old one.

**Comment by LaurenFBaily** [comment]
Yes, I think Georgia said she could give us the login details for the account so we can update the links for the QR codes and manage the timings ourselves.
Note to self: add google utm params to urls so we can keep tracking QR code use through looker studio.

**Comment by rcantin-w** [comment]
Closing this as done, #11131 contains next steps
