### ISSUE TITLE
Change audio duration and video duration fields to be minutes:seconds

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11158]
### What
Allow following two fields in 'Exhibition highlight tour'  page type to display minutes and seconds:
- video duration (in minutes)
- audio duration (in minutes)

These currently allow a number eg 3 or 3.5 to be entered which then displays as a duration eg. 3:00 or 03:30. We want to be able to enter minutes and seconds eg. 02:32. I imagine this means the type of field needs to be changed and content re-inputted.

### Why
Request from editorial team to allow the duration  shown on the stop cards to match with the exact duration which is displayed on each stop page.

**Comment by davidpmccormick** [comment]
We currently have a single number field – I think there are two things we could do to meet this requirement

1. add another number field such that we have one for minutes and one for seconds
2. replace the number field with a text field and clearly label that the format should be `xx:xx`

1. feels like it's definitely overkill
2. seems reasonable and we'd be able to lint the fields to check that times are being entered in the right format

Using a number field we would lose any ability to do anything mathematical with the data, but I don't think we were ever going to here in any case so don't see this as a problem

**Comment by LaurenFBaily** [comment]
Agreed. I would be happy to take the risk that no-one is going to start putting sentences into that field. Don't think we need to do anything mathmatical - each clip is designed to be consumed independently so no user need to know what total is, for example.
