### ISSUE TITLE
New triggers/tags for exhibition page tracking

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11159]
Request from marketing to add additional tracking to help improve performance of our ads. New tracking is additional tags/triggers on exhibition and event pages so more actions can be recognised as conversions.

Instructions here: https://docs.google.com/spreadsheets/d/1TXZc9LOhz8k31vRtOQsPNsUmuVCZ6qjiVW_tefwShQ4/edit?usp=sharing

**Comment by LaurenFBaily** [comment]
I gave our marketing agency temporary Edit access on the tag manager container yesterday in order to test some new tags/triggers. There are four new tags for Meta which we discussed adding as Custom html tags with the additional consent check (ad_storage). As these are triggered on an interaction (eg. click to event page) that should be fine? Sense check?

**Comment by rcantin-w** [comment]
I believe we'd landed with not having Custom HTML tags in GTM as it could introduce faulty code that doesn't go through code review and isn't fully owned by anyone as we don't have an analyst owning our Google platforms. I'll tag @kenoir for confirmation, but I believe that's why we moved them all out of GTM and into the code directly.

**Comment by kenoir** [comment]
> I believe we'd landed with not having Custom HTML tags in GTM as it could introduce faulty code that doesn't go through code review

This is my understanding. The experience team need oversight and review of tags added to the site to avoid misconfiguration and conflict.

**Comment by LaurenFBaily** [comment]
Discussed in person. Agreed to temporarily add these as Custom html tags for now, to be reviewed when lead digital analyst is in post (documented here #11160 ). Marketing agency will continue to only have Read access to GTM.

**Comment by LaurenFBaily** [comment]
This is ready so I will QA in GTM. When published I will add below events as 'key events':
- 
- click_to_event_page
- click_to_exhibition_page
- 75_scroll_30s_on_site

And remove the following from 'key events':

- Gads_access
- Gads_event
- Gads_exhibition
- Gads_getting_here
- Gads_opening_times
- Gads_whats_on
