### ISSUE TITLE
Copy updates to Exhibition Guides

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11174]
Update the copy on this page: https://wellcomecollection.org/guides/exhibitions/ZthrZRIAACQALvCC to:

[Exhibition name] digital guides

Find out more about the exhibition with our highlights tour, available in short audio clips with audio description and transcripts, or as British Sign Language videos.

Listen to audio

Watch British Sign Language videos

_Please note: the title is changing to be plural, from [exhibition name] digital guide to [exhibition name] digital guide**s**_

**Comment by rcantin-w** [comment]
In prod
