### ISSUE TITLE
Always get the external service from the V2 auth services in the iiifManifest

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#11235]
Relates to https://github.com/wellcomecollection/platform/issues/5761

Our iiif-presentation manifests contain both V1 and V2 versions of the auth services. We have a toggle that allows us to switch between the two.

Not all manifests currently have V2 services, but the external/restricted login service only works with the V2 version (teh V1 service returns a 404). We should therefore always get the external service from V2 if it is available.

**Comment by rcantin-w** [comment]
Same here, I believe it's all deployed to prod @gestchild
