### ISSUE TITLE
Upgrade to Slice Machine 2

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11230]
Slice Machine is now at 2.8, so we probably want to upgrade our packages to match. 

[Version 2 only seems to break things for GraphQL](https://github.com/prismicio/slice-machine/releases/tag/slice-machine-ui%402.0.0), which we don't use (right?), so I think it's possibly not a huge change, but probably still an upgrade we want to do carefully.

> [!NOTE]
> **Please remember to remove the relevant packages from [Dependabot's ignore list](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/.github/dependabot.yml) once upgraded.**

**Comment by rcantin-w** [comment]
Nominating this for next upgrade as most High Vulnerabilities seem to stem from slice-machine-ui now.

**Comment by gestchild** [comment]
Done in #11381 and #11383
