### ISSUE TITLE
Tidy up the SearchResults component

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#11249]
Since the work to [update the linkResolver](https://github.com/wellcomecollection/wellcomecollection.org/pull/11190), and use it more extensively, it looks like we can do some tidy up of content/webapp/components/SearchResults/SearchResults.tsx

The difference between most of the Compact Cards in that file seemed to be the url and because we are now using the linkResolver function to generate that, we could probably combine these into one.

**Comment by rcantin-w** [comment]
now in prod
