### ISSUE TITLE
Design ticket template for GitHub

### ISSUE THREAD

**Issue by dana-saur** [wellcomecollection/wellcomecollection.org#11254]
### User story

As a [ _persona_ ] 
I want to [ _be able to …_ ]
So that I can [ _achieve this outcome_ ]

 

### UX brief
**Design brief:** _Add link here_
**Project page on Notion:** _Add link here_

### Definition of done
- [ ] Achieves user story
- [ ] Testing approach agreed
- [ ] Passes accessibility (eg colour contrast)
- [ ] Responsive design considered
- [ ] Design critique or review
- [ ] Check with real data (images, copy etc)
- [ ] Flag new elements that might be incorporated into the design system
- [ ] Spec designs (interactions, how it works, logic etc)
- [ ] Does this design have an analytics plan?
- [ ] Agree final designs with product manager
- [ ] Create dev tickets and handover

**Comment by dana-saur** [comment]
@kasiabbb I've cherry picked all the bits I thought worked well from ones I've used in the past to get us started but let me know what you think.

**Comment by dana-saur** [comment]
@rcantin-w We'd like to try this as our Github template (markdown below). Would you mind updating or showing me how to update it?

```
### Description

_Complete/delete as appropriate_

### User story

As a [ _persona_ ] 
I want to [ _be able to …_ ]
So that I can [ _achieve this outcome_ ]

Example:
As a _researcher influencer_
I want to _be able to sign up to the newsletter_
So that _I can better understand Wellcome’s position on x_

### UX brief
**Design brief:** _Add link here_
**Project page on Notion:** _Add link here_

### Definition of done
- [ ] Achieves user story
- [ ] Testing approach agreed
- [ ] Passes accessibility (eg colour contrast)
- [ ] Responsive design considered
- [ ] Design critique or review
- [ ] Check with real data (images, copy etc)
- [ ] Flag new elements that might be incorporated into the design system
- [ ] Spec designs (interactions, how it works, logic etc)
- [ ] Does this design have an analytics plan?
- [ ] Agree final designs with product manager
- [ ] Create dev tickets and handover

```

**Comment by rcantin-w** [comment]
I'm learning too! I'd talk to @pollecuttn about it thinking she would also like to know how to do them, maybe we can have a workshop at some point and work through them all?

**Comment by pollecuttn** [comment]
Meeting to discuss 25/11/24

**Comment by rcantin-w** [comment]
We've updated the template https://github.com/wellcomecollection/wellcomecollection.org/issues/new?assignees=&labels=needs%3A+design&projects=&template=design_template.md&title=
