### ISSUE TITLE
Provide an indication that staff are viewing a restricted item

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#11257]
Relates to wellcomecollection/platform#5761

Once staff are able to view restricted items it would be useful to provide an indication on the page when they are doing this.

In the past there has been confusion when staff are able to see things that members of the public are not and we should make it more obvious why this is the case.

This will be need on the items page, e.g. https://wellcomecollection.org/works/pzmyhgsk/items

and possibly the work page https://wellcomecollection.org/works/pzmyhgsk/

Normally, the work page won't show a link for restricted items, but will do for staff who are logged in

- Because not all iiif manifests have v2 of the external service and (v1 doesn't work) for granting access - we should adapt the message to notify the user that the iiif manifest needs regenerating in order to be able to see it. We should do this for logged in users with a role of 'StaffWithRestricted' when the external service id is pointing to v1, i.e. https://iiif.wellcomecollection.org/auth/restrictedlogin

**Comment by dana-saur** [comment]
Had a chat with Raph, Gareth and Ashley. We agreed that when something is fully restricted, the most appropriate word to describe is `item`.

@rcantin-w updated copy below:

## Item viewer

>**Restricted item**
This item is hidden from the public.

<img width="396" alt="image" src="https://github.com/user-attachments/assets/2e418e94-5c36-4ed3-8fea-ebc31740697b">

## Works page

>**Restricted item**
This item is hidden from the public and can only be viewed by staff.

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/6390a355-74f7-4f21-a491-838fca9dc637">

**Comment by dana-saur** [comment]
Also split out the partially restricted indicator to separate ticket: https://github.com/wellcomecollection/wellcomecollection.org/issues/11278

And updating the existing public facing restricted material copy for consistency with the staff copy changes above: https://github.com/wellcomecollection/wellcomecollection.org/issues/11277

**Comment by rcantin-w** [comment]
Thanks for this @dana-saur ! Pushing the changes now.

**Comment by rcantin-w** [comment]
This is now in production.

**Comment by rcantin-w** [comment]
[Slack conversation regarding this ](https://wellcome.slack.com/archives/CUA669WHH/p1729005415385939)for legacy purposes
