### ISSUE TITLE
Add hotjar tracking to search and concept pages

### ISSUE THREAD

**Issue by dana-saur** [wellcomecollection/wellcomecollection.org#11306]
We want to look at the browse/search/concept page journeys on wellcomecollection.org through Hotjar recordings.

Can we add Hotjar tracking to the following pages:

- https://wellcomecollection.org/collections
- https://wellcomecollection.org/search/...
- https://wellcomecollection.org/concepts/...
- https://wellcomecollection.org/works/...

**Comment by LaurenFBaily** [comment]
Happy to create a separate ticket, but adding here as I think it would be helpful to do this at the same time...

Can we remove the HotJar tracking from the Exhibition and Exhibition Guide pages at the same time? I will also need to make sure the HotJar account upgrade happens.

**Comment by rcantin-w** [comment]
Would like to confirm whether or not `https://wellcomecollection.org/search` also needs HotJar?

**Comment by rcantin-w** [comment]
And sorry for `/works/[id]`, do we _just_ want `/work/[id]` or do we also want it on
- `/work/[id]/items` (item viewer)
- `/work/[id]/images` (e.g. https://wellcomecollection.org/works/xnwrtt3c/images?id=tbtvxxmm, happens when the user is coming from a specific image search)

**Comment by rcantin-w** [comment]
Had a chat with @LaurenFBaily just now and that's a yes on the above

**Comment by rcantin-w** [comment]
In prod
