### ISSUE TITLE
Stop the cache varying on `_ga` cookie

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/wellcomecollection.org#11391]
## What is this?

Follows https://github.com/wellcomecollection/wellcomecollection.org/pull/9431

As that feature is not being used, and it is causing the cache to vary unnecessarily, probably causing unnecessary load and slow response times, we should remove the `_ga` cookie as something we vary the cache on.

See also https://wellcome.slack.com/archives/CUA669WHH/p1731312936795359

## How to test?

- [ ] Measurable improvement in apdex scores

**Comment by gestchild** [comment]
change deployed about 12:43pm 28/11/2024
