### ISSUE TITLE
Promoted stories block

### ISSUE THREAD

**Issue by kasiabbb** [wellcomecollection/wellcomecollection.org#11424]
To-dos 

Build a Promoted Stories element (Figma link) 
- new card design 
- horizontal scroll with designated left/right buttons
- wobbly bottom 

Placement: 
- all Stories except comics and galleries
- after 5 paragraphs 

GA4: 
- set up click event

**Comment by rcantin-w** [comment]
Oops sorry did I create #11425 instead of using this one? Could this one be closed or is it a different piece?

**Comment by kasiabbb** [comment]
Yes, will close this. I set it up initially but don't think we need it anymore!

**Comment by kasiabbb** [comment]
Yes, will close this. I set it up initially but don't think we need it anymore!
