### ISSUE TITLE
Improving newsletter signup flow

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#2703]
## Who's it for?
Users who want to subscribe to the newsletters

## Problems to be solved
- Our newsletter promo is currently getting a miniscule CTR from the `Sign up` button: Avg. 0.3% newsletters/session (See #2559 for full analysis)
- Marketing want to increase the number of signups to What's On ([see their recommendations])(https://github.com/wellcometrust/wellcomecollection.org/issues/2703#issuecomment-558689254) 
- `/newsletter` page styling needs to be updated anyway as we're still on the old base page template

## What does success look like?
- Percentage of site visitors who signed up
- Increase average monthly subscribers by 5%

Compare v1 vs v2 usage against same period last year

## Constraints
- Timeboxed: Finish by Friday 17 January 2020
- Avoid background patterns that are buggy in IE11/Edge

## Where we can improve overall quality?
- Eliminate bugs in IE11
- Responsive design
- Content improvements - wording
- Decoupling from footer
- Form elements
- Design of newsletter page
- Better integration with card system

## Consider
- Success and error states
- Newsletter-specific differentiation
- Brand elements from print assets
- Form validation (that scales to other forms)
- Degradation
- Does it need to be situated at bottom of content above footer?

## Decisions
- Decided not to make it part of the footer because we may want an audience-specific newsletter to be promoted on relevant programme/activity pages

## Testing
We'll AB test content of v2 : v2 (A) vs v2 (B)

**Comment by jennpb** [comment]
[WC-emailsignup-recommendations.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/3892669/WC-emailsignup-recommendations.pdf)

**Comment by pollecuttn** [comment]
Copy recommendation from Aisha:
Sign up to our newsletter by choosing the updates that interest you

with button wording staying as 'Sign up'

**Comment by pollecuttn** [comment]
10 December 2019:
- Copy wording on recommendations is placeholder and can be changed
- Lynn to think at what we call this e.g. newsletter
- Might monitor by e.g. aim to increase sign up by 10%

**Comment by pollecuttn** [comment]
What's On list: 40k
Other lists: 1k - 3k each
(Access, Youth 14-19, Schools, Youth + Community workers)

Potential future newsletter for Research Focus

**Comment by pollecuttn** [comment]
Sign up check box unnecessary as submitting triggers an email to you to confirm sign up (double opt-in)

**Comment by jennpb** [comment]
That's our interpretation - not necessarily our Legal team's interpretation. I suggest we future-proof this (against impending GDPR audit) by following pattern that wellcome.ac.uk uses. I'm 80% certain that this will come up in the next few months.

**Comment by jennpb** [comment]
Keep this open until:
- [ ] A/B test done
- [ ] Findings conveyed to WC Marketing

Going to hand this one over to @taceybadgerbrook for test monitoring

**Comment by jennpb** [comment]
Decisions:
[ ] 100% traffic to Version B @davidpmccormick @gestchild
