### ISSUE TITLE
Create a filter for events with interpretations

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#2765]
This will give us a page to allow us to test with.

The search functionality would be a good place to put this in.
Maybe something like:
```
  type:events
  my.events.interpretations.interpretationType:WlYq1SQAACYAWiuX
  my.events.interpretations.interpretationType:WmXl4iQAACUAnyDr
  my.events.interpretations.interpretationType:WmXhziQAACQAnw7i
  my.events.interpretations.interpretationType:Wn3STCoAACgAIedR
```

## Discussion:
Should this be labelled as "Events with accessible interpretations and translations" or "Event for people with access needs".

Currently the query and the former are conceptually in sync.

We should think about adding an audience for the latter, but will need to remember to mark up all events with interpretations as such creating overhead for the content team.

# Who's it for?

# User story

## Acceptance criteria

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by jennpb** [comment]
Proposed filtering
![IMG_2535](https://user-images.githubusercontent.com/1446139/72719010-f4ef8280-3b6e-11ea-8602-22cac674e7ad.jpg)

**Comment by jennpb** [comment]
This was discussed as part of the Programme + Content work in late 2020. We decided not to deal with filtering until there's time and capacity to investigate using Prismic GraphQL API for querying.
