### ISSUE TITLE
Design System: Date & Time Format Display

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#3008]
## Who is this for
Visitors planning a visit to Wellcome Collection

## Problem to be solved 
Our current date and time format is quite lengthy making it difficult to scan. Also, it doesn't scale well to mobile view.

## Recommendations
- Continue to use : and 24hr clock to display time
- Abbreviate [day] and [month]
- Hide [day] [month] or [year] if the value is same
- Use en dash with spacing to indicate time/date range e.g. 11:00 – 12:00 or 23 Jun – 26 Aug 2018
- Display starting time and duration when events have same duration
- Duration format: 30 min, 45 min, 1 hr, 1.5 hr, 2 hr, etc.
- Apply to Public Program and Editorial content but not Collections.

## Examples
![wc_ds_datetime](https://user-images.githubusercontent.com/29206031/43472218-d92087a2-94e4-11e8-8811-cd2d0add57f1.png)

## Success metric 
In usability testing, users can identify when something is on.

## Open issues
- How to handle the listing of dates and times? e.g. events with multi dates
- How to handle multi time listing with different duration? e.g. Car Radio Live in Handle with Care

## Next steps
- [x] Consult with Content team
- [x] Heesoo to include how the date & time are displayed in Events 
- [x] Gareth O. to incorporate to Cards 
- [x] Team to review the recommendations
- [ ] Dev to implement
- [ ] Document in Cardigan

**Comment by Heesoomoon** [comment]
@jennpb I've updated the ticket with the latest decisions.

**Comment by jennpb** [comment]
Is this something that we're actually going to do? @Heesoomoon
