### ISSUE TITLE
Design system: Feature/Default/Compact Cards

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#3097]
## Who it's for
- Website users, to help see similar content
- Us, because we want more flexibility in the design system to provide visual hierarchy and reflect content prominence

## Problems to be solved
- Scaling cards up or down based on content significance and key messages we want to convey (marketing & promotion)
- Optimise for different breakpoints (full vs. compact)
- Exploring ways to update visual treatment, e.g. replace beige card with background
- Explore ways to handle blank spaces in a dynamic list (filler promo or background)
- Defining card size's relationship to the content (are temporary exhibitions always Large, while Events are Small?)
- Automating the rendering of cards at the agreed sizes

## Definition
Cards are:
- Snapshot of the content types (exhibition, events, article, etc.)
- Reflection of who we are and what we do
- Appear in dynamic lists
- Can be mixed types or single types
- Used in landing and list pages e.g. 'This week' on Homepage, 'Exhibitions and events' on What's on

## Design
https://zpl.io/a8W50n4

## To Do
- [x] Design to abstract out cards in wireframes
- [ ] Construct sample list pages with wireframed components
- [ ] Consult Editorial team re: stories priorities and publishing cycle

**Comment by Heesoomoon** [comment]
@GarethOrmerod The type size for the compact card on mobile doesn't look right. Currently, it's the same size as the group heading. Would you take a look and let @davidpmccormick know?
https://wellcomecollection.org/visit-us

**Comment by pollecuttn** [comment]
5 Sept 2019

## To do
Devs to build hero cards
- [ ] beige
- [ ] charcoal

**Comment by pollecuttn** [comment]
Weighted card logic from design review 5 Sept 2019: https://github.com/wellcometrust/wellcomecollection.org/issues/3097
