### ISSUE TITLE
Segmented controls

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#3542]
We use the segmented control on [`/whats-on`](https://wellcomecollection.org/whats-on) for selecting the date range of exhibitions, and the month range for events.

There have been a few conversations around the low usage of this component, especially around the month selector.

After a [bit](https://www.lukew.com/ff/entry.asp?1950) [of reading](https://medium.theuxblog.com/mobile-dropdowns-revisited-17358ceb5340) around form controls, it seems the point of segmented controls is to allow a more transparent set of options to the user, with fewer interactions to get what they want. Smashing.

While refactoring a bit of the what's on code, I had to reimplement our mobile version of the picker, which is actually just a fancy drop down.
![screencast-wellcomecollection org-2018 10 16-07-39-25](https://user-images.githubusercontent.com/31692/46997090-ac991780-d116-11e8-9e4a-7f20023372e3.gif)

If we then look at the data on how the control is used, we can see it is used quite a lot less proportionally to pageviews on mobile than desktop:

## 2018/02/17 - 2018/10/15

| Device category | Views           | Segemented control click |
| --------------- | --------------- | ------------------------ |
| Desktop         | 125,235(54.71%) | 18,310(71.80%)           |
| Mobile          | 77,178(33.71%)  | 4,980(19.53%)            |
| Tablet          | 18,633(8.14%)   | 2,211(8.67%)             |

The hypothesis is that, pointing in the direction of advice around this, people don't select the other months or date ranges as they don't know they're there because we hide them.

Thought this might be worth baring in mind when developing our form controls for our catalogue discovery.

Not sure whether to put this in cardigan perhaps for further exploration when we get there? Or just leave here and close the issue. Thoughts @wellcometrust/experience?

**Comment by Heesoomoon** [comment]
We've noted how participants easily miss this tab even on the desktop during user research. There's room for improvements in both visual and interaction. It feels little too premature to add to Cardigan. Let's revisit this when we see a need for it in Library collection project or List template #3086. 

Btw, potential solution could be '[Scrollable tabs](https://material.io/design/components/tabs.html#usage)'. Here's how Medium applied to the navigation. 
![screen shot 2018-10-16 at 09 54 15](https://user-images.githubusercontent.com/29206031/47023006-a32f9f80-d156-11e8-9e31-2a83b97551ea.png)

**Comment by jamesgorrie** [comment]
> It feels little too premature to add to Cardigan. 

I reckon we should out it in so we can evolve it when we get to it, and not forget that we have something? All components should live in cardigan as far as I remember the request being?

**Comment by jennpb** [comment]
All components should be in Cardigan so we can have a place from which to iterate. We may want to revisit the tagging so we can flag things as ‘under review’, ‘graduated’ etc

Sent from my pocket computer

On 16 Oct 2018, at 15:53, James Gorrie <notifications@github.com<mailto:notifications@github.com>> wrote:


It feels little too premature to add to Cardigan.

I reckon we should out it in so we can evolve it when we get to it, and not forget that we have something? All components should live in cardigan as far as I remember the request being?
