### ISSUE TITLE
Design System: Consistent use of spacing between components and sections

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#3564]
## Problem to be solved
We want to apply consistent visual elements across the site to present the proper information hierarchy and make it easy to scan information for the users.

## Design guidelines
https://zpl.io/aBqOM9L

## Next steps
- [x] @GarethOrmerod to audit and recommend guidelines
- [x] @GarethOrmerod to review with @davidpmccormick 
- [x] Dev to implement

**Comment by davidpmccormick** [comment]
Discussing this with @GarethOrmerod, it seemed feasible to try and work to a set of pre-defined spacings for various situations. At a first pass, these seemed like they could be:

- breaks between slices in the body
- breaks between 'sections' (header:body, body:stuff-below-the-body)
- space within components

Sketch files so far have these spacings documented for desktop, but Gareth was keen for us to experiment on scaling them down uniformly for mobile.

**Comment by Heesoomoon** [comment]
@davidpmccormick I just noticed this on Events list. This list doesn't have any pagination. Therefore, it should have some padding between the components. Is this something to consider for the system spacing? https://wellcomecollection.org/events
![screen shot 2018-10-26 at 14 28 55](https://user-images.githubusercontent.com/29206031/47569441-8734b680-d92b-11e8-80a7-d4a9cd9bc3e4.png)

**Comment by davidpmccormick** [comment]
I feel like section spacing is currently too big on mobile. @Heesoomoon what do you think?

For example, the space between the exhibition featured image and the quote is currently 78px:
![screen shot 2018-10-26 at 17 01 43](https://user-images.githubusercontent.com/1394592/47578327-07b1e200-d941-11e8-90fd-4cb844954fb0.png)


I'd propose to reduce it to ~54px:
![screen shot 2018-10-26 at 17 01 28](https://user-images.githubusercontent.com/1394592/47578347-139da400-d941-11e8-8186-25d0fea8d009.png)
