### ISSUE TITLE
Trigger a Slack notification when a feature is deployed

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#3696]
We currently have a notification letting us know something is _ready_ to be deployed. It would be nice to be notified when it is _actually_ deployed.

**Comment by jamesgorrie** [comment]
Thinking about safety here, and also the future of potentially having <abbr title="Continuous deplyment">CD</abbr> - maybe we should have:

* Container is built, ready for deployment
* Container is being deployed
* Container is deployed
* Change is seen on website

❓

**Comment by jennpb** [comment]
https://github.com/guardian/prout @wellcometrust/weco-experience-devs
