### ISSUE TITLE
Labelling Material Types

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#3807]
## Problem to solve
`workTypes` in the API use Sierra material types, which have evolved over time to meet the needs of Encore and the III library catalogue. However, they don't accurately reflect the nature of our materials and perpetuate some differences in material that we no longer wish to highlight. 

[The full list is here
](https://github.com/wellcometrust/platform/blob/master/ontologies/Reference%20data/sierra-material-types.csv)

We need to do some work to understand how users use and interpret these types, as they're useful for filtering and faceting. 

The first round of research was conducted in June 2019. https://wellcomecloud.sharepoint.com/:f:/s/wcdigitalexperience/EiMeJK0Hk89Co9jLoPyH0xMBD9qgK2ydh0OmmCajElBfKQ?e=h8MwSK

## To do
- [x] Review search logs for any other helpful info about what types of things people search for #4163 
- [x] Second round of testing to clarify weaker responses
- [x] Come up with supergroups (IA)
- [x] Make recomendations to data team
- [ ] Disseminate initial findings to Collections Info team **25 March 2020**

## Docs
https://docs.google.com/spreadsheets/d/1yx51ejvCJ3B4ZqZWQT77xJ1CumglHO16gncaFQKgS40/edit?usp=sharing

**Comment by jennpb** [comment]
@Heesoomoon The Collections Information team should be part of this discussion, so we'll need to set up a time to talk through the questions and proposals as they may have ideas about how they're intending or hoping to improve the source data.

**Comment by jennpb** [comment]
@Heesoomoon I'm going to remove this from this milestone and suggest that we pick it up in January when we can collaborate with Collections Info colleagues.

**Comment by jennpb** [comment]
Test set of material types on 'Test set' sheet: https://docs.google.com/spreadsheets/d/1yx51ejvCJ3B4ZqZWQT77xJ1CumglHO16gncaFQKgS40/edit?usp=sharing

See also #3955 - we should get some search data first so we can see if there are any other top genres that we should throw into the mix for testing

@hthair

**Comment by hthair** [comment]
- In the process of collection images of the audited material we want to test labels for.
- a couple of them are born digital so we need to work out how to represent that
- digital production team (Holly) have got a lot of photos that they are sharing with me
- Harkiran is checking the difference between several audio-visual labels (she needs to know too).

**Comment by hthair** [comment]
Photos of collections: https://wellcome.tandemvault.com/browse/stock-images-of-collection-items-books-manuscripts-archives-and-paintings?view=1

**Comment by hthair** [comment]
Test is ready to go. 
Due to nature of the test, it's essentially an open card sort - therefore we need at least 15 people to be able to see any patterns emerge. I'd like to promote it both to the user panel and library twitter followers to try and get as many responses as possible though. 
We can then follow up on the test with an in person round (printed material type images) to probe on the 'why would you call it that?' which could better inform our decision on how to use these labels.

**Comment by Heesoomoon** [comment]
@jennpb Based on the analysis, I wonder whether we should go ahead and update the label 'E-books' to 'Books' to make it easy to browse in the search result.
![Screen Shot 2019-06-26 at 09 51 07](https://user-images.githubusercontent.com/29206031/60166004-42ce2300-97f8-11e9-84f3-b5d8108da418.png)

**Comment by jennpb** [comment]
It's already been raised as https://github.com/wellcometrust/wellcomecollection.org/issues/4482
Discussion with @jtweed determined that this should happen on the Data side, but first we need to be certain that other e-book types (e.g. digitised books on 3rd party platforms like Early English Books Online, or PDFs), are ok to be looped in with those.

**Comment by hthair** [comment]
results of label test: https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7Bfc59aa49-c47b-47a0-b4fc-944849cc4ecf%7D&action=edit&uid=%7BFC59AA49-C47B-47A0-B4FC-944849CC4ECF%7D&ListItemId=6604&ListId=%7BFDB19016-1696-44BD-938C-2BC0ED6C539E%7D&odsp=1&env=prod&cid=0c5d8d85-8bb6-495b-afc3-764eb7abde46

- people don't use 'e' words like e-book, e-journal
- good consensus for books, journals, music.
- what we call sound a lot of people called audio
- archive and ephemera had less consensus but since these are proper terms we will still use them but this data may mean we make more effort to explain to our users what these definitions mean in our collection to help new users too.

**Comment by jennpb** [comment]
Second round of testing:

Manuscripts
Moving image

**Comment by jamesgorrie** [comment]
Just confirming, we will be releasing this soon:
https://github.com/wellcometrust/platform/issues/3863

**Comment by jennpb** [comment]
@Elltie 
Can we consider this issue as well when testing material types? https://github.com/wellcometrust/wellcomecollection.org/issues/4662
It's a PDF but classified as a book. I'd like to find more like this and test a hypothesis that people call these 'PDFs' or 'Documents'

**Comment by Elltie** [comment]
@jennpb 
Yes, added to my notes

**Comment by pollecuttn** [comment]
Next step: share outcomes of worktype label testing

**Comment by jennpb** [comment]
https://github.com/wellcometrust/platform/issues/4218

x: e-manuscripts-asian > Manuscripts
b: manuscripts-asian > Manuscripts
n: cinefilm > Film

**Comment by jennpb** [comment]
From meeting with Alexandra:

- `Archives and Manuscripts` type `h` will need to be split into `Archives` and `Manuscripts`. Best place to do this is likely to be with the CALM data. To discuss as part of CALM ingest conversations.
- Rename the e-asian and asian manuscripts both to `Manuscripts`; repurpose one of these Sierra codes for Western manuscripts?
- `Pictures` format we'll keep for now; could come up with an alternative to test in the future, but we know to definitely avoid `Artwork`
- Hold off on making further changes to AV materials; teams are looking at AV cataloguing standards and it make take some time.

**Comment by jennpb** [comment]
Final decisions for existing Sierra matTypes:


Current label | Sierra mat type code | Proposed label 
-- | -- | -- 
Books | a | No change
Ebooks | v | Books
ManuscriptsAsian | b | Manuscripts 
EManuscriptsAsian | x | Manuscripts 
DigitalImages | q | No change 
Ephemera | l | No change 
Maps | e | No change
Pictures | k | No change - not problematic for users, but we may want to change it to reflect current usage
StudentDissertations | w | No change
3DObjects | r | No change 
CDRoms | m | No change 
Sound | i | Audio
ESound | s | Audio
Journals | d | No change 
MixedMaterials | p | Recommend to phase out 
EVideos | f | Video
VideoRecordings | g | Video
ArchivesAndManuscripts | h | Recommend to split into `Archives` and `Manuscripts`
Cinefilm | n | Film   
EJournals | j | Journals 
Music | c | No change
StandingOrder | u | No change

**Comment by jennpb** [comment]
Research docs: https://wellcomecloud.sharepoint.com/:f:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/By%20user%20-%20Collections%20Researchers/Work%20type%20label%20testing_201906?csf=1&web=1&e=knqbXD
