### ISSUE TITLE
Homepage iterations / tests

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#3919]
We'd like to start running some small tests and iterations on the homepage, this issue can track ideas, inspirations and actual implementations (as separate issues).

## Questions:

- [ ] What are the different purposes of the homepage e.g. to lead you to other content, to give a perception of what Wellcome Collection is, etc.
- [ ] What metrics would tell us we're achieving these purposes
- [ ] Could we dashboard ☝️ 
- [ ] What quick qualitative testing can we do?

## Inspirations
[Pinterest board](https://www.pinterest.co.uk/garethormerod/wellcome/homepage/)

**Comment by GarethOrmerod** [comment]
Invitation link to join the Pinterest board - https://pin.it/tfsc3xldewpcge
