### ISSUE TITLE
Add contributors component to content pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#3930]
## Who it's for
Request from content team:

> For the Hub residency pages, we are adding the team members, but there isn't the capability to add them in the standard way with the collaborator component. So right now it looks a bit funny : https://preview.wellcomecollection.org/pages/XBt4MBMAADNIlmtE This feature could be useful for other program-style pages like Youth, etc.

Comment from @jamesgorrie from Trello

> As a note on this, there is discussions around modelling out pages into their more specific types of things, e.g. programs.
If we modelled out a program, 100% it would have contributors.

## Acceptance criteria
- Editors can add contributors to content pages in Prismic
- Contributor component appears on the live site
- Content model reflects relationship of contributor to the program/service

**Comment by jamesgorrie** [comment]
@jennpb given my suggestion about modelling, do we want to still just say "add contributors to pages" or do we want to think about the modelling work before we start this?

**Comment by jamesgorrie** [comment]
Some notes for the modelling.
They want to have people on these two pages:

Created Out Of Mind:
https://wellcomecollection.org/pages/Wuw2MSIAACtd3SsQ

And Hubbub:
https://wellcomecollection.org/pages/Wuw2MSIAACtd3SsS

Interestingly these feel like they fall into organisations (which we have, but haven't fleshed out).

**Comment by jamesgorrie** [comment]
Another thought to this is to have a controlled vocabulary and add `format`s to pages.
Press release being 1, and other that might follow?
