### ISSUE TITLE
Digital content viewer

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4085]
**DETAIL AND USER STORIES TO BE ADDED - THESE ARE MERELY NOTES FOR NOW**

From sprint research:
- Enable ⬆️ ⬇️ ⬅️ ➡️ keyboard navigation
- When in 'reading mode' no need to display bibliographic metadata in context. At this stage the in-book data takes precedence
- Search within as a navigational device: term density; jump to specific passages
- Need persistent page/image references so user can jump back to previously identified sections, pinpoint specific cited passages, etc.

**Design principle:**
Maximise viewing space.

**Preview mode**
- Get sense of object through select images and extent
- Flicking through a book as metaphor: look at table of contents, scan book to ascertain level, read a random page, look at front and back cover
- Include quick actions? e.g. Download whole thing, usage info/licence
- CTA Open full work

**Reading mode**
- Overview of all images/pages
- All available actions
- Isolate and zoom on a page if needed
- Show structure: title page, ToC, chapters, volume, index - all parts found in metadata

**Architecture**
URL for every page - yes.
/works/id/pagenumberorassetnumber

**Comment by jamesgorrie** [comment]
Maybe it's worth distilling this into a document and either storing on cardigan, or in the docs folder?
