### ISSUE TITLE
Archive and shut down alpha.wellcomelibrary.org

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4088]
The Library alpha site (at alpha.wellcomelibrary.org) and its predecessor whatsinthelibrary.com (with it's 4 separate projects) are still racking up costs of around £250/month. It'd be much better to archive what we want to archive for testing and demonstration purposes, and then turn off all Heroku dynos and add-ons.

Our repo: https://github.com/wellcometrust/alpha

Good, Form & Spectacle repo: https://github.com/goodformandspectacle/wellcomelibrary (work with George Oates to make repo public)

JPB to fill in more detail later.

Ideas on how we might do this are welcome!

**Comment by jennpb** [comment]
- [ ] Alpha repo moved over to Wellcome Collection 
- [ ] Rewrite README
- [ ] Redirect alpha.wellcomelibrary.org to `wellcomecollection/alpha`

**Comment by jennpb** [comment]
On hold until key for old library AWS accounts can be retrieved.

**Comment by pollecuttn** [comment]
Robert deleted the cloudfront distros there and deleted that account (there was nothing else in it apart from those distros - none of which pointed anywhere that worked)
https://wellcome.slack.com/archives/C01R944HFTL/p1619434170001700?thread_ts=1619177122.122500&cid=C01R944HFTL
