### ISSUE TITLE
Content page breadcrumbs

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4158]
## Who it's for
- Site users
- Robots

## Problem to be solved

Our breadcrumbs are all over the place! 

The breadcrumb on content pages is a bit random. We need to review all content pages and update.
Examples
https://wellcomecollection.org/pages/Wuw2MSIAACtd3Ssg (update to 'What we do')
https://wellcomecollection.org/pages/Wuw2MSIAACtd3StA (update to 'Young people')
https://wellcomecollection.org/pages/Wuw2MSIAACtd3SsC (update to 'What we do')
https://wellcomecollection.org/pages/Wuw2MSIAACtd3St2 (update to 'Venue hire')

Here's a specific example:
Within the Venue Hire section, we have several locations that form part of venue hire. By that logic, they should be navigable up the tree (`What We Do > Venue Hire > Hire Henry Wellcome Auditorium`)

Right now, we jump straight back to /what-we-do

![venuebreadcrumbs](https://user-images.githubusercontent.com/1446139/53258139-cb5e7a80-36c3-11e9-858c-cd1d3d228a4d.jpg)

**Comment by jamesgorrie** [comment]
Sounds like it's part of #1611?

Might be worth revisiting the site model again? Do we create site sections etc.

Although conceptually (technically will be harder) we could open the conversation that was shelved a few months ago about abstracting out relationships and allowing things to be "part of" things, which sounds more sustainable.

Site sections etc can then be built on that system.

**Comment by jennpb** [comment]
@jamesgorrie Yep, you're right. This will wait til we look at navigation.
