### ISSUE TITLE
Press Release archive

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4169]
Relates to #3237 

## Who it's for
Our Media team

## User story
As Media Lead, I want to be able to refer back to past press releases so I can get an overview of our historical work.

## Problem to solve
- We currently don't surface past press releases.
- When doing a web search for an exhibition or event, it's possible to stumble across a past press release but have no context for its place in the site
- Past press is used by the Media Team to draw in media partners.

Consider:
- `/press/2017`
- linking to All Press Releases
- Display of press release listing is dreadful

**Comment by dannybirchall** [comment]
Hi @jennpb -- checking in on this after it came up in conversation with Kate Moores -- is there any migration work here for the content team to do with old press releases, or is this a dev/design issue of visibility?

**Comment by jennpb** [comment]
No, they're all present and migrated, so no content work.
