### ISSUE TITLE
Works Page: font size audit

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#4259]
The font size for Works page on Mobile view is smaller than other templates making it difficult to read. @GarethOrmerod  should review what's currently being used and make recommendations.

**Works Page**
![IMG_5138](https://user-images.githubusercontent.com/29206031/54344972-f50f1f80-4639-11e9-8456-a4194884aa38.png)

**Exbition Page**
![IMG_5139](https://user-images.githubusercontent.com/29206031/54344969-f50f1f80-4639-11e9-94e1-1892071d78ab.png)

**Comment by jennpb** [comment]
Advice from Google Search Console's mobile usability tool shows that text size on works pages is too small to read.
