### ISSUE TITLE
Making it transparent how results are relevant

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4363]
## Who it's for
Researchers who want to know why the search has given them these results

## Ideas
Based on a few conversations around algorithms and surfacing to users why you're getting what you're getting, [@jamesgorrie noticed](https://github.com/wellcometrust/wellcomecollection.org/issues/4194) the library search does this quite clearly.

http://catalogue.wellcomelibrary.org/search~S12/Y?searchtype=Y&searcharg=mary+bishop&searchscope=12&searchscope=12&SORT=D&words=mary&words=bishop

![Screenshot 2019-03-28 at 16 00 18](https://user-images.githubusercontent.com/31692/55172924-be292580-5172-11e9-9224-d61c0320cef4.png)

The five categories in descending order of relevance/Right Results (c) are:
[search term] found in main title of [entries x of y]
[search term] found in subtitle or author of [entries x of y]
[search term] found in chapter title, imprint, subject heading, or note of [entries x of y]
All search terms found in title field of [entries x of y]
All search terms found in catalogue record of [entries x of y]

**Comment by jamesgorrie** [comment]
Just making a note here about something we spoke about.

We might surface this pre-search by explaining the different query types (`slop`, `justboosted` etc) upfront, potentially with examples of what they're good for e.g. "Use this for finding a book by its title".

**Comment by jennpb** [comment]
Example from eBay
![Screenshot 2019-11-16 at 11 59 39](https://user-images.githubusercontent.com/1446139/69408313-7c02b480-0cfe-11ea-900d-ad461db9bca6.png)
