### ISSUE TITLE
Use specific ID in downloaded filename

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4364]
## Who it's for
Anyone downloading works from the collections

## Problem to be solved
When a user downloads an image or PDF, the filename is either `default.jpg` or `0.pdf`. 

It would be much better for users if the filename had a unique reference so they don't end up with `default(1).jpg` `default(2).jpg` etc.

Users have also noted that because they're using many libraries throughout the course of their research, it can be difficult to trace back an image to its source of download.

### Ideas:
- Use API ID, e.g. `vyua3hdm.jpg`
- Use API ID + institution, e.g. `wellcome_vyua3hdm.jpg` or `vyua3hdm_wellcome.jpg`
- Use truncated title, e.g. `chafingdish.jpg` - This one is problematic, because we could have multiple versions of the same title, or similar titles but different works
- any others?

### Considerations:
- Downloading selected images from a single work - how would we deal with the canvas number?

**Comment by alexwlchan** [comment]
Requires https://github.com/loris-imageserver/loris/issues/18 or similar

**Comment by jennpb** [comment]
Investigate as part of #4848

**Comment by alexwlchan** [comment]
@jennpb Might be a good time to point out we already do a little bit of this. If you download an image, you should get a filename like `s3_L0026000_L0026168.jpg`. Not perfect, but improving!

**Comment by jennpb** [comment]
Ah, in that case we probably want to hold this one back until we can use the work ID.
