### ISSUE TITLE
Search results: filter by online/in library

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4413]
## Who it's for
Researchers who need more control over their search results

## Problem to be solved
We need to help save the time of the user by making it easy to decide whether to come to the physical library to view materials. Given our hybrid collection of digital and physical things, users need a way to include/exclude materials based on whether they're accessible **online** or **in library**.

## Success metrics TBC
Can researchers find material that meets their research needs and availability?
User satisfaction
Task-based usability

## User stories
I want to narrow the result to library materials that are only available in the library. 
I want to look at what I can see online first, before I make a trip to the library

## Tasks
- Display in work card and on work page [UI/UX]
- Mapping physical locations to ‘In library’ >> Data and Coll Info #4269 
- Design and implement a way of filtering

## Acceptance criteria

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by jtweed** [comment]
Superseded by https://github.com/wellcomecollection/platform/issues/4724
