### ISSUE TITLE
Unify React image components

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#4449]
We have several components that render images currently:

- `IIIFResponsiveImage`
- `UiImage`
- `Image`

as well as a few places where we haven't componentised the image rendering at all (just using an `<img>`).

We should consolidate these as much as possible where appropriate.

**Comment by jamesgorrie** [comment]
To explain the want for a `UiImage` and `Image`(as I still think there is a need).

One was used for the data received from a CMS (Prismic) e.g.
```JSX
type Image {
  width: number,
  height: number,
  alt: number,
  src: string
}
```

And the other type was more the components props when you needed to render an image i.e. `srcSizes` etc.

Maybe names like `ImageData` and `Image` make more sense, or more explicitly `ImageData` and `DisplayImage`.

As  a point on having display properties, those are normally controlled by the parent component and thrown down as a string. I do wonder if you could use `Context`s (although I would test the perf first).

e.g.
```JSX
// Layout4Col - the layout that goes from { s: 1, m: 3, l: 4 }
<ImageSizesContext.Provider value={createImageSizes({ s: 1, m: 3, l: 4 })}>
  <Grid>

    {/* Blah blah */}
  </Grid>
</ImageSizesContext.Provider>
``` 

```JSX
// Image.js
<ImageSizesContext.Provider>
  { imageSizes => <img sizes={getImagesSizes()} /> }
</ImageSizesContext.Provider>
```

It would have to be combined work with design / ux / dev though to make sure that what this will make consistent, will also make stricter.

**Comment by alexwlchan** [comment]
Gareth has done this, I believe.
