### ISSUE TITLE
Navigate a manuscript or book's structure by "range" (table of contents, index, list of parts within manuscript)

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4486]
# Who it's for
Collections researchers

## User story
To evaluate a book for relevant content, users 
1. Look for the first 'Contents' page then scan through the chapters list spread through few pages
2. Find a relevant chapter and wants to view the chapter
3. Read few pages to evaluate if it's relevant for their search

## Problems to solve
Current implementation has the following limitations.
- Need to visually identify the content pages
- Require many back and forth to get to the chapter
- Need to zoom in/out then paginate to read a few pages
- Difficult to navigate to the chapter using image number

The digitised materials often come with structural metadata that we want to expose as a way of navigating to a part.

For example,
- Books are marked up with Covers, Table of Contents, Index
- Books may also have multiple volumes
- Manuscripts may be marked up with 'parts'. These work like chapter headings, but they are actually representative of discrete 'works' bound into one volume.

![image](https://user-images.githubusercontent.com/1446139/58497467-eeda0b00-8173-11e9-92d5-2e0070fc8888.png)

These 'parts' need to be demarcated and able to be navigated to, either in the viewer, on the /works page, or both.

View from the UV
<img width="294" alt="image" src="https://user-images.githubusercontent.com/1446139/58014117-fe13e580-7aef-11e9-9be3-d0155fdaf0f9.png">

Multi-volume book: https://wellcomelibrary.org/item/b18031511

Manuscript examples:
https://wellcomelibrary.org/item/b19553146 = https://wellcomecollection.org/works/gftr4sa9
https://wellcomelibrary.org/item/b19241380  

TODO
- [x] Data investigation to understand where data sits and how we might render it on screen

No design until we do this.

# Implementation

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

**Comment by pollecuttn** [comment]
@gestchild and @davidpmccormick to read ticket and ask JPB any questions

**Comment by jennpb** [comment]
Before Heesoo left, she shared a few relevant ideas here with mockups:https://github.com/wellcomecollection/wellcomecollection.org/issues/4589#issuecomment-510952702

**Comment by davidpmccormick** [comment]
@jtweed – are you (or Christy or Ashley) able to provide an exhaustive list of what data we could expect to be able to get out of the METS?

So far, I think we have thumbnails and license information which has been directly added to works in the catalogue api.

We currently also get certain structural information like title page, table of contents, front cover etc. from the IIIF manifest. It's not clear to me whether this information should/could ultimately live directly on a work in the catalogue api, or whether we should continue to fetch it from the IIIF manifest.

We are specifically interested in solving the problem of providing page numbers for books where we currently only provide _image_ numbers.

Also, it would be good to have any information about how manuscript sections are delineated (e.g. [as they are in the uv](https://wellcomelibrary.org/item/b19241380#?c=0&m=0&s=0&cv=0&z=-0.5963%2C0%2C2.1925%2C1.3772)).

**Comment by jtweed** [comment]
Hi @davidpmccormick you should treat the IIIF Presentation API as the source for all data that describes the structure of a digitised item, which will have indeed come from data in the METS files produced during digitisation. We will only add things to the Catalogue API where they are needed for search.

Page numbers are in the IIIF as labels on the canvases, eg in this example:

https://wellcomelibrary.org/iiif/b28083271/manifest

Other sections within the work, eg cover, table of contents, parts of a manuscript will come through as structures that link to a range of canvases, outside of the usual sequence. If it helps there are also an enumerated list of viewing hints in IIIF that will help you to determine if something is paged.

As to how sections are determined and what will be added in what cases, @aray-wellcome may be better placed to answer that.

**Comment by taceybadgerbrook** [comment]
In order to evaluate this feature with respect to overall search experience, we need to agree what success looks like. Is it

- Users use this at all 

or is it

- User use this, find what they need more quickly and so spend less time on /works pages?

**Comment by DominiqueMarshall** [comment]
Link to initial item page mockup: [Navigating a book or manuscript](https://www.figma.com/proto/ZcfHccqfm1sYYyS7MoKssJ/navigating-a-book-or-manuscript?node-id=1%3A2&viewport=809%2C400%2C0.19635304808616638&scaling=scale-down-width)

**Hypothesis:** including key information and ways of navigating on the item page will help researchers navigate through an item if they land here from image search or are viewing an item for the first time. 

Iteration includes:

- Adding the full work title (can possibly be truncated), contributor and date information.
- Adding an accordion to the filmstrip panel that features the license and credit info, table of contents/index, and the option to search within an item.
- Explicit buttons for the different views available + an image zoom slider.


**Next Steps:**
- Mobile/tablet view
- Mockup of each image view when a link in the Contents is selected

**Comment by DominiqueMarshall** [comment]
Initital mobile view prototype: [Item page mobile view](https://www.figma.com/proto/SliIg74U9YXd5LUAaV87Jd/Mobile-navigating-a-book-or-manuscript?node-id=1%3A2&scaling=min-zoom)

cc @davidpmccormick
