### ISSUE TITLE
Display 2-page view for published books

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#4533]
## Who it's for
Users viewing the materials online

## Problem to be solved
During the viewer pop-up research, we learned the majority of users preferred 2-page views when viewing books or manuscripts.
- provide context e.g. caption, annotation, table
- a clear understanding of the material type
- less click and visually less overwhelming

## Acceptance Criteria
- [ ] Display 2-page view in both list and detail views by default for relevant material types. e.g. books, manuscripts, etc.

## Open Issues
- There is some back-end logic we need to sort out to determine what gets displayed as a 2-page view
- Can we ensure the correct two pages are displayed together?
- Some manuscripts have additional pages/inserts which throw of the sequence of recto/verso. Need to follow up with Ashley to investigate these examples.
- Do we know what people are trying to achieve? Can we solve that another way?

Current state (updated April 2021):
We can only display materials tagged as `monographs` in Goobi. This means that archival material (like bound manuscripts) won't fall under the same category. In order to offer 2-page view for bound manuscript material, these will need to be identified in Goobi as having a monograph structure.

**Comment by jennpb** [comment]
Added to Productboard
