### ISSUE TITLE
List & Detail Views: Make it easy to navigate and evaluate for relevant content

### ISSUE THREAD

**Issue by Heesoomoon** [wellcomecollection/wellcomecollection.org#4589]
**JPB TO BREAK THIS DOWN INTO SMALLER CHUNKS**

## Problems to solve
To evaluate a book for relevant content, users 
1. Look for the first 'Contents' page then scan through the chapters list spread through few pages
2. Find a relevant chapter and wants to view the chapter
3. Read few pages to evaluate if it's relevant for their search

Current implementation has the following limitations.
- Need to visually identify the content pages
- Require many back and forth to get to the chapter
- Need to zoom in/out then paginate to read a few pages
- Difficult to navigate to the chapter using image number

## Recommendations
- Make it easier to identify pages by using page labels (title, content, etc.) and numbers
- Increase the default image size for the detail view to be big enough to read
- Allow users to use scroll and paginate using keyboards, mouse or touchpad
- Implement Scrubber #4445 
- CTA on Works page should use total page number instead of image number.

## Success Metrics
TBD

**Comment by Heesoomoon** [comment]
**12 July**
**List view with page labels and number**
![1VIewList](https://user-images.githubusercontent.com/29206031/61143754-fdce1000-a4ca-11e9-8a89-b60a9f395a10.png)

**Contents**
![2ViewContent](https://user-images.githubusercontent.com/29206031/61143760-01619700-a4cb-11e9-91b6-1465ba9278ba.png)

**Chapter**
![3VIewChapter](https://user-images.githubusercontent.com/29206031/61143766-032b5a80-a4cb-11e9-8ffe-444b94d570f3.png)

**Comment by jennpb** [comment]
relates to #4486

**Comment by Heesoomoon** [comment]
@jennpb This could be broken down to separate enhancements.
1. Increase the default image view then allow to scroll down the page and navigate to previous/next pages.
2. Display page label and number (#4486)
3. Implement scrubber (#4445)

**Comment by Heesoomoon** [comment]
**25 September**
### Recommendations 
based on the research findings #4728 
- Use page labels (title, content, etc.) and numbers for text based materials to make it easier to identify and navigate
- Allow users to input the page number to jump to specific page
- Consider placing all controls on top and a/b test with alternate solutions (Note: placing on the bottom in mobile can trigger browser controls. Need to investigate if there's a work around this)
- Group controls by function to make it easy to discover and less overwhelming
Navigation: All pages, Page number, Previous/Next
View: Zoom in/out, Rotate
- Test different orientations for Previous/Next page controls
- Update the link styles to provide visual affordance
- Update 'Download' to 'Save' with a visual indicator to view more options
- Update Cursor to 'hand' once zoomed in
- Investigate if we can make it easier to review/read individual pages by allowing user to scroll using trackpad or mouse wheel and minimise the need to drag 
- Investigate if we can allow user to navigate to previous/next page using trackpad, mouse wheel or touch
- Investigate if we should limit zoom in/out using controls rather than clicking in the image

### Desktop
**Review List**
![Review_list](https://user-images.githubusercontent.com/29206031/65602819-7148cf00-df9c-11e9-92dc-0185fb2c71f0.png)

**Review Detail**
![Review_Detail](https://user-images.githubusercontent.com/29206031/65602834-7574ec80-df9c-11e9-85ff-13315deece9e.png)

### Mobile
**Review List**
![Review_List_M](https://user-images.githubusercontent.com/29206031/65602803-6b52ee00-df9c-11e9-85a8-0184bc0de7b2.png)

**Review Detail**
![Review_Detail_M](https://user-images.githubusercontent.com/29206031/65602776-5e35ff00-df9c-11e9-9275-9d02e6fe7c84.png)

**Comment by jennpb** [comment]
Picked up here #4486
