### ISSUE TITLE
SoundCloud embeds from private a/c not working anymore

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#4644]
SoundCloud used to send a `secret_token` which we could use to embed players from a private (Wellcome Collection) account. They stopped doing so recently, so our SoundCloud embeds won't work.

See #4643 for details and location of the issue.

**Comment by jennpb** [comment]
Picking this one up again as we're going to need to get it working now that we're recording online events _in the covid era_.

From a content editor point of view, when inserting the iframe code into the iframe slice in Prismic, the page breaks on Preview. When I enter the 'share' link as an Embed, that doesn't break the page, but it doesn't appear on page.

We need to ensure that Soundcloud embeds are working for all content (whether we're using embed link or iframe)
