### ISSUE TITLE
Add a page type for "announcements" or similar

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#4711]
Following up a conversation from Slack: https://wellcome.slack.com/archives/C294K7D5M/p1567607810005600

We have pages on the site (e.g. https://wellcomecollection.org/pages/WyjZcCgAAKgALCuN) which are announcing something, but which:

1. Don't have a date
2. Aren't findable except by already knowing the page exists, and finding it via Google

Possibly related: #3237

**Comment by jennpb** [comment]
@alexwlchan Oof, another factor in the #3237 press release model. Are announcements/statements a type or subtype of press releases? 

Will need to give this a think...
