### ISSUE TITLE
Footer dividing line tweaks

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#4742]
Below ~ 958w px the dividing line above the left hand column doesn't line up with the lines above the other two columns

![footer - lines](https://user-images.githubusercontent.com/1446072/65506121-c0223600-dec2-11e9-8860-763e79b4d069.PNG)

Also there is a dividing line below the left hand column but nowhere else.

### To decide

- [ ] What should the line below the left hand column be doing? Extend across all three columns? Be removed? (Dev/designer)

### To do

- [ ] Align the dividers above the three columns
- [ ] As decided per lower dividing line

**Comment by davidpmccormick** [comment]
I'm going to close this as `wontfix` since it seems like unnecessary effort for such a small ui bug on a component that we intend to change.
