### ISSUE TITLE
Index pages for all genres

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4767]
# Who's it for?

# User story

## Acceptance criteria

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by taceybadgerbrook** [comment]
Here is a [link](https://github.com/wellcometrust/wellcomecollection.org/issues/4163#issuecomment-537452299) to genre analysis done for 4163.  It includes a listing of the genres contained in more than 100 searches during period 26/8/19 - 25/9/19.

**Comment by jamesgorrie** [comment]
If it's useful - here's a list of genres that we have in the catalogue:
https://gist.github.com/jamesgorrie/ab775ff142be4b9a75141adac4bbc47a

**Comment by taceybadgerbrook** [comment]
If this genre data is coming from Sierra, what do you make of the non-text values?  These look like dates - see lines 816, 1176 and from 5804 onwards.  Could this be a read error?
