### ISSUE TITLE
Prismic preview cookie not set when sharing preview link

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#4800]
Only logged-in users are currently able to preview changes from Prismic. This is a problem for the content team who need to be able to share previews with people who don't have a Prismic login.

**Comment by jennpb** [comment]
@davidpmccormick @dannybirchall  Is this still a problem or can we close it?

**Comment by dannybirchall** [comment]
We are still experiencing intermittent to serious issues sharing prismic preview links with colleagues and externals in the good form, ie

https://prismic.link/3ekBJCd

which shouldn't require advance cookie-setting, I don't think?
