### ISSUE TITLE
Active consent for cookies

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4816]
## Who it's for
All users

## Problem to be solved
In line with recent GDPR rulings re: cookie consent, we need to make our cookie opt-in process explicit. 
http://eulawanalysis.blogspot.com/2019/10/the-cjeu-rules-on-consent-to-cookies.html

The wellcome.ac.uk  team has already done some good work on this, and we should strive to copy them for organizational alignment.

Relates to #2804 

## Acceptance Criteria
- [ ] Users can manage preferences, opting in or out of specific cookies or categories of cookies
- [ ] A full list of current cookies is provided

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by pollecuttn** [comment]
See:

https://github.com/alphagov/govuk-design-system-backlog/issues/12#issuecomment-860814605 (from https://wellcome.slack.com/archives/C294K7D5M/p1624267888008300 )

**Comment by jennpb** [comment]
Closing this as it's out of date, but will pick up as separate tickets in Q2 2023 as needed
