### ISSUE TITLE
Toggles tidy

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#4846]
There is a few places where toggles are being read / mutated.

We should find a way for all of this to be encapsulated in 1 place as it's getting a bit proliferated.

**Comment by jennpb** [comment]
@jamesgorrie @gestchild @davidpmccormick Does this need further refinement as a ticket, or are there clear ideas about how this might be done?

**Comment by jamesgorrie** [comment]
Nein
