### ISSUE TITLE
Design system: H2 H3 spacing adjustments

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#4860]
Apply spacing from design in code locally to review on screen

**Comment by pollecuttn** [comment]
@GarethOrmerod Please put the zeplin link here

**Comment by GarethOrmerod** [comment]
H2 and H3 spacing adjustments:
https://zpl.io/aN5ND9d
zpl://project?tags=Typography&pid=5aab926b4b6efde01259e959

**Comment by jennpb** [comment]
- [ ] @GarethOrmerod to QA 
- [ ] Inform content team of manual changes to be made

**Comment by jennpb** [comment]
@GarethOrmerod @davidpmccormick I'm assuming that this old issue has been completed as much as is necessary, at least until significant issues are identified. The point above about the content team needing to manually address spacing issues - do we have a list of those that can be handed over to them?

**Comment by davidpmccormick** [comment]
I believe the work in #4893 aligned the code with the designs, so `h2`s and `h3`s in body content from Prismic should be spaced appropriately as long as additional line-breaks etc. haven't been added. I don't have a list of any outstanding issues.

**Comment by jennpb** [comment]
Great, I'll close this baby then.

**Comment by davidpmccormick** [comment]
…I didn't mean to imply that there _weren't_ any outstanding issues.
