### ISSUE TITLE
Audit URL design

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4865]
There's an RFC for URL Design that we need to action: https://github.com/wellcomecollection/docs/tree/master/rfcs/017-url_design

And there's Silver's WIP documentation from a while ago: https://github.com/wellcometrust/platform/blob/master/ontologies/WIP/wellcome%20urls.csv

- [ ] @wellcometrust/weco-experience-devs should read and comment on RFC

- [ ] We then need to work through:
- where we haven't followed this
- why we haven't followed it
- and how to get rid of the hacks

- [ ] Create a list of things we actually have
- [ ] List of things still to be implemented.

**Comment by davidpmccormick** [comment]
Having read through the RFC, there were just a couple of things that stood out for me:

I don't understand 'entropy' in this context (is there another way to phrase?)
> short URLs are therefore preferable while maintaining sufficient entropy to support future growth

I think there are instances where we use fragments that don't rely on client-side JS (in-page linking etc.) Are these cases separate (and should they be called out as such)?
> all fragments SHOULD dereference i.e. .../foo#bar should be addressable at .../foo/bar

**Comment by jennpb** [comment]
will pick up separately as part of digitised content work
