### ISSUE TITLE
Viewer styling

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#4885]
New designs: https://app.zeplin.io/project/5aab926b4b6efde01259e959/dashboard?tag=Works%20Viewer%20Improvements

## general viewer changes:
- [x] colour change to control bar
- [x] colour change to background
- [x] changes to control button styles (top row)
- [x] positioning of control button styles (top row)
- [x] thumbnail selected state
- [x] thumbnails layout
- [x] styling of control buttons (in viewer)
- [x] openseadragon styling

## scrolling viewer changes
- [ ] position (and behaviour) of control buttons (in viewer) (small and large screen differ)

**Comment by jennpb** [comment]
@gestchild @GarethOrmerod @DominiqueMarshall @pollecuttn 

Apart from the last tick box in the todo list, which I still think should be done, are there any other UI changes that need to be considered before you're happy for this to be in a user testable state?

**Comment by gestchild** [comment]
none that I know of
