### ISSUE TITLE
Replace Uptime robot with updown.io

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#4911]
**What**
Uptime robot alerting is too annoying. We want to replace it with updown.io
- [x] Move all alerting to updown
- [x] Remove uptime robot

**Where**
<-- a link, or a screenshot if relevant, as to where the bug is-->

**Comment by jennpb** [comment]
@gestchild Is this something we still want? Uptime robot seems to be in use still and not causing any specific problems.

**Comment by kenoir** [comment]
Closing as done.
