### ISSUE TITLE
Downloading single images from iiif-presentation canvases

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4938]
# Problem to solve
We currently only offer hi-res and lo-res downloads on digitised items where we are using the `iiif-image` `DigitalLocation`

Compare these (`iiif-image` `DigitalLocation` with multiple download options):
[example 1](https://api.wellcomecollection.org/catalogue/v2/works/dmxdvqvs?include=items,identifiers)
[example 2](https://api.wellcomecollection.org/catalogue/v2/works/my3xg75w?include=items,identifiers)

to these (`iiif-presentation` `DigitalLocation` which only offers a PDF download):
[example 3](https://api.wellcomecollection.org/catalogue/v2/works/dxhbd92z?include=items,identifiers)

## Expectations
- All digitised items (excluding video, audio) should be downloadable image by image 
- All digitised items (ex. video, audio) should offer the same set of image downloads - in our case, hi-res and lo-res

# User story
In order to download high or low-resolution images from your site
As a researcher
I expect your system to offer these to me.

## Background research
https://wellcomecloud.sharepoint.com/:p:/s/wcdigitalexperience/ET_fRUahU_lNmsmE0cOZ0lMBIDWA7wOWDOaXXs3n9B3PTg?e=yz9rvx (slide 16+)

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by pollecuttn** [comment]
Add:
- hi res and lo res download links to viewer

**Comment by jennpb** [comment]
Ok, here's what I think we should do - but would like to get @DominiqueMarshall to comment as well because it's more complicated than I initially thought and might require a bit of journey sketching to work out how this works on Works page, Thumbnail view and Main view.

Here are two options for the download text:

OPTION 1
```
Downloads v
Whole item PDF
Full size image JPG
Small image 760 pixels JPG
```

OPTION 2
```
Downloads v
Whole item PDF
This image (Full size) JPG
This image (760 pixels) JPG
```

Option 2 feels better to me because it puts it in context of the image you're looking at in the main view 

But there are other considerations:

What about the 'Download' button on the work page, when you're only looking at 1 representative image? 
Options:
- remove Download button from this stage
- only allow whole item PDF download

What about the 'Download' button when you're looking at the thumbnail view?
Options:
- assume thumbnail in focus is 'this image'

**Comment by DominiqueMarshall** [comment]
@jennpb agreed about the text in option 2 feeling better. It makes it clearer that you'll be downloading that specific image, whereas the text in the first option would only really make sense if there was one image only.

**Download button the work page:** it would be good to find out how often this button is used compared to the download button on the viewer page. If it's used considerably _less_, then that would be an argument to get rid of it. If it's used regularly, then it should be more explicit and say "download the full PDF", as currently it only says "download as PDF".

**The option for the thumbnail view** - the functionality will need to be looked at, as currently when you click a thumbnail it automatically opens the main view. Would we want to get rid of that functionality in order for people to be able to select the thumbnail image they want to download?
