### ISSUE TITLE
Prismic improvements

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4962]
# Who it's for
Content team, users of Prismic

# Problems to solve

There are some usability issues with Prismic that we should investigate and/or submit feature requests to Prismic.

They are:
- Integrating tzitzit into Prismic properly so we can manage copyright metadata
- Better internal Prismic search
- Bring back the 'in this doc' function on images in Prismic
- make date entry in Prismic easier (ie type, not click)

@wellcometrust/weco-experience-devs Are any of these under our control? Have any of these been reported to Prismic already?

**Comment by jamesgorrie** [comment]
> Are any of these under our control?
Unfortunately not

> Integrating tzitzit into Prismic properly so we can manage copyright metadata

This is so specific to how we do attribution and copyright, that they've said it couldn't be rolled out universally. We could model this out into new types, such as image, but then the user flow would be:

- Create new `CreditedImage` type in prismic
- Add image and Wellcome shape of attribution
- create new story
- embed the new story

We could run this past the content team as I am not really sure at what stage they add images to a story.

> Better internal Prismic search

We might need to be more specific?

> Bring back the 'in this doc' function on images in Prismic

Reported, added to their productboard, no feedback

> make date entry in Prismic easier (ie type, not click)

Reported, added to their productboard, no feedback

**Comment by jamesgorrie** [comment]
- List of a where changes happened within a revisions.
- Crops are only used when image is embedded, not associated globally with the image
