### ISSUE TITLE
Investigate self-hosted analytics packages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4976]
What would we need to do to stop using Google Analytics to track usage of our site? 

matomo.org holds lots of possibility.

https://github.com/awesome-selfhosted/awesome-selfhosted#analytics

**Comment by jamesgorrie** [comment]
For what it's worth, I have had a go with Matomo - one consideration is that it's written in PHP.

It'd be good to know how much control we'd like extend the code and contribute back, which feels important, and something like Matomo wouldn't allow much room for that.

**Comment by jamesgorrie** [comment]
https://snowplowanalytics.com/ is pretty interesting too.
