### ISSUE TITLE
Search filters: filter by license

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4980]
# What is it

We want to make it easier for people to understand whether images and digitised items are free to use, and under what conditions.

In addition to improving license and download information on /works pages #4549, we can also filter search results by license type.

## User story
In order to find materials that I can download and use for free
As a researcher
I need to be able to filter out stuff that is restrictive or not available for free.

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by jtweed** [comment]
Superseded by https://github.com/wellcomecollection/platform/issues/4724
