### ISSUE TITLE
Add tests to SearchForm

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#4993]
**What**
The `SearchForm` would probably benefit from some unit tests so we aren't relying as much on manual testing and/or reports of things not working as expected from colleagues (e.g. #4989) and to give us confidence that we've not caused regressions when refactoring or adding new filters.

**Comment by jennpb** [comment]
@ishouty @jamesgorrie @gestchild Do we need to keep this issue open or has the work been done with your recent testing work?

**Comment by jamesgorrie** [comment]
Closing in favour of writing user stories and having more e2e tests now we have playwright in place.
