### ISSUE TITLE
Physical description data for multi-format video

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5016]
**What**
The physical description for videos with multiple formats (DVD and video, for example) is merged into one line, like this:

`1 videocassette (VHS) (1 min.) : 1 DVD (1 min.) : sound, color, PAL. sound, color`

It should be like this:

`1 videocassette (VHS) (1 min.) : sound, color, PAL`
`1 DVD (1 min.) : sound, color`

**Where**
Take a look at Antismoking Baby: https://wellcomecollection.org/works/v6q9dnym

**Comment by jtweed** [comment]
Will be fixed by https://github.com/wellcometrust/platform/issues/4201

**Comment by jtweed** [comment]
Closing as a dupe of wellcomecollection/platform#4201
