### ISSUE TITLE
Analysis and optimisation of package bundles

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#5074]
**What**
The catalogue bundles are including things like `prismic.dom` into all page bundles.

[You can see this here](https://dash.wellcomecollection.org/bundles/catalogue.browser.latest.html).

It should probably look more like the [content bundles](https://dash.wellcomecollection.org/bundles/content.browser.latest.html), where commons is large and shared libs are in there.

There's a more general question around why the catalogue app needs prismic.dom in the first place.

**Comment by jamesgorrie** [comment]
Maybe something to look into as when we build we get this warning:
https://github.com/zeit/next.js/blob/master/errors/opt-out-auto-static-optimization.md

**Comment by davidpmccormick** [comment]
We use `getInitialProps` in `_app.js` for `toggles`, `openingTimes`, `globalAlert` and `isPreview` (for Prismic).

Unfortunately I think they _are_ global and, as such, belong where they are (it feels like it would be a mistake to move them into each page's `getInitialProps` instead).

**Comment by jamesgorrie** [comment]
Closing in favour of a whole bunch of opther performance work
