### ISSUE TITLE
Image modal QA

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5080]
# What is it and who's it for?
Researchers using images search

# Improvements
- On modal window, main image should be clickable and go to the main image view (same behaviour as the `View image` button
- Change `Read about this work` to `More about this work` - this sets better expectation of what you're going to see, given that many of these images barely have enough content to read.

- When the visually similar thumbnails wrap to 3 rows, we get this unusable scroll bar in the modal. Can this be improved? 

![imagemodalwithscroll](https://user-images.githubusercontent.com/1446139/74231527-b1e08500-4cbe-11ea-8e79-9cda295d5f34.png)

**Comment by davidpmccormick** [comment]
The left-hand column of the modal will scroll if there's more content than can fit (this could also be as a result of a long title).

A scroll bar will appear as soon as there's not enough space to fit the content completely, but this could (as in the screenshot) be when there's only a few extra pixels of content.

I don't think there's an obvious way to account for that, especially in responsive-design land.

**Comment by jennpb** [comment]
Darn it.

**Comment by jennpb** [comment]
As discussed today, can we move the scroll bar to the right or left instead of middle, so the whole modal becomes scrollable? 
@davidpmccormick @DominiqueMarshall
