### ISSUE TITLE
Potentially not clear enough that you have filters selected on mobile

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5086]
**What**
Once you've closed the filter drawer on mobile, there isn't any visual signifier to let you know that you have filters selected. This might be particularly confusing if you've selected a filter, closed the drawer, then entered a different search term (not necessarily expecting the filter to carry across to the new search).

**Where**
`/works` at screen width < 600px

**Comment by jamesgorrie** [comment]
Have we tried to find a way to not hide filters on mobile?
Or maybe have the filter list (the thing you can cancel filters from) visible?

**Comment by davidpmccormick** [comment]
I think at the least having some way of seeing that you're doing any sort of filtering at all is important, yeah. Probably one for @DominiqueMarshall and @GarethOrmerod.

**Comment by jamesgorrie** [comment]
> at the least having some way of seeing that you're doing any sort of filtering

Seems strange to hide everything and then try to hint at that we're hiding everything... but I am very much aware I am probably missing context and journey we've taken to get here.

**Comment by GarethOrmerod** [comment]
A common pattern for this would be for the filter button to have an altered/highlighted state after a selection has been made. I can work something up.

**Comment by pollecuttn** [comment]
Decision at design review: have `Filters(x)` as the wording on the button that displays to indicate that filters are in use

**Comment by davidpmccormick** [comment]
After not-particularly-rigorous guerilla testing the decision was updated with having the active filter count contained in a yellow box within the button.
