### ISSUE TITLE
Analysis of newsletter promo (deployed 22/1/20)

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5108]
**We think that**
Users are not signing up to the newsletter because:- 
- it's confusing
- it blends into the footer

**Therefore we hypothesise that**
If we change the background and simplifying the sign up process, users will find the newsletter promo more attractive and easier to understand.

**As measured by**
Visit numbers on GA  

**We are right if**
Visits have increased following deployment compared to baseline levels during 2019 up to the day before deployment

**Comment by pollecuttn** [comment]
https://github.com/wellcomecollection/wellcomecollection.org/issues/2703#issuecomment-580128068

**Comment by taceybadgerbrook** [comment]
Unique page views of /newsletter have neither increased in terms of numbers nor in terms of percentage of unique views.  For discussion at User and Data meeting on 24/2.

![image](https://user-images.githubusercontent.com/32418070/74746420-546bab80-525d-11ea-9d60-1266b23f4b22.png)

**Comment by taceybadgerbrook** [comment]
Sharepoint documents:
https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/5108%20Analysis%20of%20newsletter%20promo%20deployed%2022Jan%202020.docx?d=wbbd46c13d3a24bf0af15da5cc19a16eb&csf=1&e=aGVSXA

https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/5108%20newsletter%20analysis.xlsx?d=waa7a48328983494e8c145591c9467f32&csf=1&e=gPNVBm

**Comment by pollecuttn** [comment]
We'll go with option B as that allows for signing up for particular newsletters from particular pages i.e. teachers and schools newsletter on schools page https://wellcomecollection.org/pages/Wuw2MSIAACtd3StS

**Comment by taceybadgerbrook** [comment]
Conclusions:

- Numbers of signups have increased due to implementation of suggested single stage signup
- While A/B testing did not find one version to be more effective than the other in driving signups, Version B was agreed to be deployed as this provides more flexibility for audience-specific signups by page (eg Youth signup on Youth pages) Link to A/B testing here:
https://datastudio.google.com/open/1aDfsiJqf71YKZZMwFTOB6LoW01bRqCjn

- Analysis of Dotdigital data shows numbers of signups increasing steadily regardless of the newsletter promo redesigns
- Dotdigital data also shows a slowly increasing number of unsubscribes.

These conclusions have been shared with Lynn Huynh, Marketing.
