### ISSUE TITLE
Ensure meta description field can be added for every page type in Prismic

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5125]
# What is it and who's it for?
Content team

# User story
So that we're adhering to best practice for SEO
As a content editor
I need editable meta description fields in Prismic for all page types

** if we can add any in-context tips, we should include 'Meta description should be between 155-160 characters`

# Acceptance criteria

**Comment by jamesgorrie** [comment]
By page types, do we mean exhibitions / events / stories etc?

The description for `/stories` is going to be the exception here as it's a automatically generated page, but we can update that in the code as and when until it's a managed page.
