### ISSUE TITLE
As a library member I want to know if an item is available for requesting

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5132]
# What is it and who's it for?
Library users

# User story
Feature: 1. As a library member I want to know if an item is available for requesting

## Acceptance criteria
  Scenario: I'm viewing a work page
    Given the work has a requestable item
    And it’s available to request
    Then I can see a that it's requestable

  Scenario: I'm viewing a work page
    Given the work has a requestable item
    And it’s unavailable to request
    Then I can see a that it's temporarily unavailable

  Scenario: I'm viewing a work page
    Given the work has no requestable items
    Then I can see a that it's not requestable and why (closed or open shelves or unknown)

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
### Links to zeplin wireframes

Scenario 1 (item available): https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35deafd9662acdd215/

Scenario 2 (item temporarily unavailable):
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a3572ead876e1493115/

Scenario 3 (open shelves/closed):
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35f9503e7360d94a55/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35bb57d361c1de3950/

**Comment by pollecuttn** [comment]
@gestchild Can this be closed now?
