### ISSUE TITLE
As a library member I want to request an item

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5133]
# What is it and who's it for?
Library users

# User story
Feature: 2. As a library member I want to request an item

## Acceptance criteria
  Scenario: I'm logged out, viewing a work page
    Given the work has a requestable item
    And it’s available to request
    Then I can see a primary CTA to log in

  Scenario: I'm logged out, viewing a work page
    Given the work has a requestable item
    And it’s unavailable to request
    Then I can't see a primary CTA to log in

  Scenario: I'm logged out, viewing a work page
    Given the work has no requestable items
    Then I can't see a primary CTA to log in

  Scenario: I'm logged in, viewing a work page
    Given the work has a requestable item
    And it’s available to request
    Then I can see a primary CTA to request it

  Scenario: A work has a single requestable item
    Given that I am on a work page that has a single requestable item
    When a user clicks the primary CTA to request the item
    Then I receive feedback as to whether the request succeeded or failed
    And if successful, I can see information about where to pick up the item

  Scenario: A work has multiple requestable items
    Given that I am on a work page that has multiple requestable items
    Then I am able to select which items I want to request
    And click the primary CTA to request the items
    Then I receive feedback as to which item request succeeded or failed
    And if successful, I can see information about where to pick up the items

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
### Links to zeplin wireframes

Logged out scenario 1: 
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35deafd9662acdd215/

Logged out scenario 2 (item unavailable):
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a3572ead876e1493115/

Logged out scenario 3 (open shelves/closed):
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35f9503e7360d94a55/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35bb57d361c1de3950/


Logged in - see requestable item:
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568ca18004be787c89832e/

Logged in - request successful:
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568ca19c2ec1615ab7dfb3/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568ca2762da8697d15f2ae/

Multiple item request & confirmation:
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568db3ae3c7066192f1159/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568db427cd32677b2555ac/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568db44bd744669422b32e/

**Comment by pollecuttn** [comment]
@gestchild Can this be closed now?

**Comment by gestchild** [comment]
@pollecuttn I think so yes
