### ISSUE TITLE
As a library member I need to know how many items I can request

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5134]
# What is it and who's it for?
Library users

# User story
Feature: 3. As a library member I need to know how many items I can request

## Acceptance criteria

  Scenario: I'm logged in and I check my account to see my requests
    Given I view my account
    Then I can see a number indicating how many items I can request (20)
    And how many active requests I have
    And how many requests I can still make

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
Library account wireframe: https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568e26f42eda67d4480f28/

**Comment by alexwlchan** [comment]
Closing as done; you can see the list of available requests in the item request modal and on your account page. If we need more tweaks here, we can open a new ticket.
