### ISSUE TITLE
As a library member I want to see the status of each item I've requested

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5136]
# What is it and who's it for?
Library users

# User story

In order to plan my research time efficiently
As a Researcher
I need to see whether my requests are available for me to pick up.

Feature: 5. As a library member, I want to see the status of each item I've requested

## Acceptance criteria
  Scenario: I view a list of my active requests under my account to see when they’re ready to pick up
    Given that I have placed a number of requests previously
    When I login I can view my account
    Then I can select to see a list of the requests I’ve made
    And see when my active requests are ready to pick up
    And where I need to pick them up from

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
Library account wireframe: https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568e26f42eda67d4480f28/

**Comment by alexwlchan** [comment]
Closing as done; you can see a list of requests on your account page. If we need further tweaks we can open a new ticket.
