### ISSUE TITLE
Javascript temporarily unavailable after deploying

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5141]
**What**
After deploying the site requests a javascript file that is not immediately available. The site therefore renders without javascript - the most obvious consequence of which is lazyLoaded images not loading.

When we deploy the app tries to reference the new file, which isn't available.

# TODO

- [ ] If #5303 works, split cache out into HTML / assets

**Comment by jamesgorrie** [comment]
@gestchild do we know why as the assets should be deployed at the same time?

**Comment by gestchild** [comment]
no idea why

**Comment by davidpmccormick** [comment]
Monitoring this while we see if #5303 looks like it solves the issue. If it _does_, then we should do the work to split the cache out into HTML/assets (as mentioned in the TODO above).

**Comment by alexwlchan** [comment]
I'm going to close this as stale – I don't think it's still an issue, and if it is we can open a new ticket.
