### ISSUE TITLE
Digital Engagement Indicators

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5143]
As an analyst,

I need to agree metrics for monitoring how wellcomecollection.org is doing

so that:
- the Experience team can determine whether its work is having intended effect
- any metrics still requiring work can be identified as such
- Tom can evaluate and communicate work
- reporting is consistent throughout Wellcome

As measured by coverage of areas in 
https://docs.google.com/presentation/d/1EpmYKz9qy80iuqArWHn3-22Ucs-4ZQkPwZc_OE4XcUY/edit#slide=id.g50b7db0256_0_67

**Comment by jennpb** [comment]
@taceybadgerbrook I would add another 'so that':
- Experience team can determine whether its work is having intended effect

**Comment by taceybadgerbrook** [comment]
With the exception of the items below, I have identified metrics for all of the areas in the report.
- number of physical items request (in progress)
- third party use of API (have flagged up)
- stats from Wikimedia (waiting to meet with Alice)
- downtime and error rate (data team Slacked re empty chart)
- engagement with other museums. libraries and archives
- share lessons learnt
- external recognition

While this [Data Studio report](https://datastudio.google.com/reporting/1_3B6nCru6ag09DwMKdSO1bBb_5lP3Ek-/page/YO2N/edit) seems to reflect these areas, it is very long and hard to read.  

I think the next step should be a conversation with the people in DE who would like these metrics so that I can identify the best and most consistent method of reporting (Data Studio/PowerPoint? Graph/headline figures?) and design something fit for purpose.

**Comment by taceybadgerbrook** [comment]
Here is the Data Studio "dashboard" that I am working on:
https://datastudio.google.com/reporting/7f5c0cde-4c10-4a36-9544-8b5a0f6ab723/page/o4wEB/edit

**Comment by taceybadgerbrook** [comment]
@jennpb I've put in placeholder pages in the report for Effectiveness:  Close:  share lessons learnt (internal and external) and Effectiveness:  Deep: external recognition so that no one would think I've just forgotten to include them.

Is there any tracking of lessons learnt?  Re external recognition, I spoke to Dawn Duhaney 19/3/20 about using Reach to identify citations of wellcomecollection.org.  Reach scrapes data from UK Parliament, GOV.uk, NICE, WHO, Medecins sans Frontiers but search box functionality does not support this at 3/20.  Team hopes to make publicly available Beta version May/June 2020.

**Comment by taceybadgerbrook** [comment]
This report is now being built as a Google Sheet.  Here is a link:
https://docs.google.com/spreadsheets/d/1wArVKfs9UCSy4LAJWsjY51Hjj-6MK5I42biRhM4kHmg/edit?usp=sharing

**Comment by taceybadgerbrook** [comment]
A link to the Google Sheet report has been sent to Tom, Jonathan, Danny and Christy with a note that I will be contacting them to discuss improvements to the report.
