### ISSUE TITLE
Menu design: exploring menu option

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5146]
# What is it and who's it for?

Navigation menu design for users of wc.org

# User story
In order to _(why? accomplish a goal/get a benefit)_

As a _(who? user/persona)_

I need/want/expect _(what? to do this thing)_

## Acceptance criteria

# Implementation 

## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
Mobile navigation prototype V1: https://dominiquemarshall6595.invisionapp.com/public/share/SD113T4SVJ#screens/476545362

Mobile navigation prototype v2: https://dominiquemarshall6595.invisionapp.com/public/share/ZC11BTQCWD#screens/476529549

**Comment by DominiqueMarshall** [comment]
Updated Mobile navigation prototype: https://dominiquemarshall6595.invisionapp.com/public/share/ZC11BTQCWD#screens/476529549

Desktop navigation: https://dominiquemarshall6595.invisionapp.com/public/share/UP1214ENDC#screens/476616758
