### ISSUE TITLE
Handle expired access tokens for stacks API requests

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5153]
# What is it and who's it for?

logged in users can continue to make requests after their initial access_token has expired

Need to implement: When the access_token has expired we need to use the `refresh_token` that was sent with the original `access_token` in order to get a new `access_token` before doing a call to any protected resources.

**Comment by jennpb** [comment]
@gestchild Is this still needed?

**Comment by gestchild** [comment]
I think this is outdated now
