### ISSUE TITLE
Alert message on /visit-us only

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5157]
# What is it and who's it for?
Visitors to 183 Euston Road

# User story
In order to _(why? accomplish a goal/get a benefit)_
understand the opening status of the physical WC building

As a _(who? user/persona)_
potential in-person visitor

I need/want/expect _(what? to do this thing)_
know that the building is currently open.

# Context
https://wellcome.slack.com/archives/C3N7J05TK/p1583312234011300

## Acceptance criteria

# Implementation 

## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by jamesgorrie** [comment]
Just wondering, is this the `visit-us` section, or the `visit-us` page only?

**Comment by davidpmccormick** [comment]
Good question – I'm adding a regex property to the global alert to determine which pages it should display on.

**Comment by jamesgorrie** [comment]
Adding regex into a CMS is going to come with a world of pain and feels a little nasty?

It is however something we can change without breaking as it isn't in the core model, so a great for now solution.

**Comment by davidpmccormick** [comment]
I agree it doesn't feel great, but I figured good-enough-for-now.

**Comment by davidpmccormick** [comment]
> Just wondering, is this the visit-us section, or the visit-us page only?

@dannybirchall has confirmed this is just for the page currently.
