### ISSUE TITLE
TODOs when Wellcome Collection reopens

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5180]
- [ ] put back daily tours promo (revert 90b3a6ff6a40fb2958927bce0fd4cb88656ba)
- [x] put back 'this week' on homepage (revert c85e26b03b58224ff8cf16ef9fbf21e14c6efe49)
- [ ] remove intro text (revert 06934155cce199f2550ecf3aef6eff1c1bbc4dbd)
- [x] put back exhibitions and events (revert d4c2ca0af22e070012f834d95e9a5bbbd71c671c)
- [ ] put back cafe and shop message on `whats-on/today` (revert f020b9d8d77f62c421641c91abbb6e17caffd060)

**Comment by jennpb** [comment]
@gestchild @davidpmccormick Can we please revert `c85e26b` ASAP so the new online events and open exhibitions can show up on the homepage once more?

These should be situated below the featured card.

**Comment by davidpmccormick** [comment]
I'm picking up point `1.`
