### ISSUE TITLE
Transcribing old research interviews

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5187]
# Transcribing research sessions that took place in 2019

## Acceptance criteria
All transcripts are written into dovetail and tagged accordingly

**Comment by jennpb** [comment]
@alicerichmond If you know the number of interviews to be transcribed here we could potentially outsource it? What do you think?

**Comment by alicerichmond** [comment]
@jennpb I think with the 15 outstanding project Giles interviews it would cost around £1350 to have them all transcribed with a 3 day turn around. We could potentially get them cheaper if we do say a longer turn around time, which would be adequate for us really, as there is no rush. But this would be the top end of the costs. Potentially you might have some specific interviews that are more insightful that want to be prioritised?

**Comment by jennpb** [comment]
All of the Giles transcripts were in Aurelius and I downloaded them, so we shouldn't re-do those. They can be found here https://wellcomecloud.sharepoint.com/:f:/s/wcdigitalexperience/EtVZ-1BSz7xIqO0Ay3Bb1fwBkt_lRlI9rLcFreaeuakL8Q?e=KxqaLI

**Comment by alicerichmond** [comment]
Thanks for sharing, I need to spend some more time looking into things as I do not have a clear overview of what has and hasnt been transcribed. If there are any projects specifically that you have understanding of that may want transcribing please let me know and I can prioritise

**Comment by jennpb** [comment]
I don't think there's anything urgent. We've got all the Aurelius stuff as backup (I downloaded all the data for all projects), and if we need to refresh our memory on it and get it into Dovetail on a project-by-project basis I'd rather do that. All Aurelius data is here https://wellcomecloud.sharepoint.com/:f:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Aurelius%20projects?csf=1&web=1&e=bzWVxf
