### ISSUE TITLE
Understanding Wellcome collection research programmes with stakeholders

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5208]
As a Wellcome collection researcher I would like to be able to work with researchers from different areas of wellcome collection to establish a unified research process and library

## Acceptance criteria

- Wider understanding of what research is being undertaken and by who in the collection
- Clear idea of whether sharing research more widely would be helpful
- More inclusive access to research output for Wellcome staff
- Understand whether we can improve the consistancy of our accessibility both in the venue and digitally

# Implementation 

- Work with AD&I to start communicating with others in the collection
- 1-2-1 conversations with relevant team members involved in research within wellcome collection
- Workshop to align research expectations and understand what research is already being done with who
- Creation of a unified understanding of research and value

## Testing and tracking

- Regular conversations over time to ensure that the work undertaken if helpful or whether it is causing hinderance

## Measurement

- informal survey at beginning to understand interaction with research from across wellcome collection and then periodic check ins to see if there have been any changes
- Ethnography to understand what different people would find it useful to see research from beyond their team

## Other considerations 

- Who will have access to dovetail over all?
- Will we have standards?
- Who will share the same dovetail instance wellcome trust/collection just collection?
- Will we try and create a regular research sharing event, would anyone be interested in being involved?

**Comment by alicerichmond** [comment]
Wellcome collection data acces/needs flow https://whimsical.com/YLEU9LHCidqEEKxDLs9Bji

**Comment by jennpb** [comment]
Hey @alicerichmond is this something you still want to work on?
