### ISSUE TITLE
Setting up GA4 property

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5214]
As an analyst,

I need to set up a App + Web (GA v2) property,

So that sufficient data is present in App + Web version to evaluate the performance of wellcomecollection.org and we are prepared for the eventual deprecation of Google Analytics.  We also need to evaluate the performance of App + Web itself.

As measured by analytical capability and comparison to other tools.

**Comment by taceybadgerbrook** [comment]
We are considering ways of collecting event-level data but this is what App and Web (aka GA4) does. It seems a wasted opportunity not to investigate this product. An App and Web property can run concurrently with Google Analytics, so any reporting or Marketing work will not be disrupted.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @gestchild @ishouty  In order to collect data, I am connecting the existing GA Account/Property: Collection 55614/[Default] Collection UA-55614-6 to the new GA4 (App and Web) Account/Property: Collection 55614/[Default] Collection App + Web (250634548).

For reference, [here is the link to the instructions](https://analytics.google.com/analytics/web/#/a55614p250634548/admin/streams/table/2130717945) I am following. 

Below is a screenshot of these instructions:

![image](https://user-images.githubusercontent.com/32418070/97599467-f3a58d00-19ff-11eb-9fe8-43e7df9e6b62.png)

**Comment by taceybadgerbrook** [comment]
The ID tag being connected is G-206J7SLYFC, nickname App+Web tag.

**Comment by taceybadgerbrook** [comment]
It's not collecting data because I've got the wrong ID tag. I'm going to delete the GA4 (App and Web) Account/Property: Collection 55614/[Default] Collection App + Web (250634548) and set this up again.

@davidpmccormick @gestchild The new property has gtag.js code that supposed to be pasted onto every page of the site. This seems a huge task or do you have a quick way of doing this?

**Comment by taceybadgerbrook** [comment]
The GA4 property isn't receiving any data because the site hasn't been tagged for it. Here is the code that needs to be pasted immediately after <head> on every page. 
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-206J7SLYFC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-206J7SLYFC');
</script>
```

**Comment by taceybadgerbrook** [comment]
The new tagging won't shut off data going to Google Analytics. Here's a link to an article that says so!
https://developers.google.com/analytics/devguides/collection/ga4/basic-tag?technology=analyticsjs

**Comment by taceybadgerbrook** [comment]
@jennpb @pollecuttn fyi

**Comment by taceybadgerbrook** [comment]
I'm still only seeing 1 user for GA4, so I'm assuming you haven't yet pasted the gtag.js code to <head> and haven't moved analytics.js code to <body>. If you could let me know when you do this and I'll check the data.

**Comment by davidpmccormick** [comment]
Yep, you'll only see data from my machine when I added the script locally. It'll start collecting data from everyone when #5723 is merged (I'll make sure you're informed).

**Comment by taceybadgerbrook** [comment]
Thanks. I thought for a moment things had gone horribly wrong!

**Comment by taceybadgerbrook** [comment]
The GA4 account is showing users from 10 November. However, the custom events that we set up don't get picked up by GA4 automatically. These need to be set up from scratch and GA4 events aren't structured Category/Action/Label.

I am going to investigate to see if I can create these events myself or whether I'll need Experience devs to do anything.

**Comment by davidpmccormick** [comment]
> I am going to investigate to see if I can create these events myself or whether I'll need Experience devs to do anything.

Pretty sure we'd need to update the code to send these (or their equivalents).

**Comment by taceybadgerbrook** [comment]
Looking at the GA events [tracker sheet](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B3DA23EC9-0EA4-4956-9B05-20E035BDA462%7D&file=GA%20annotated%20event%20tracker%20cheatsheet.xlsx&action=default&mobileredirect=true), I think we should stop tracking most of these events. 

A lot of these were set up to evaluate features (eg. link to bookshop from articles or clicks in outtro.) If we need to do this again, we can set them up from scratch. We won't need the engagement event that times users because GA4 automatically counts Engaged Users as those who spend more than 10 seconds on the site. I use some events for analysis of views, downloads and plays but these are shortly to be tracked in the new Elasticsearch index as conversions.

The only event that I do feel we should continue to track are clicks on Eventbrite, so I am going to focus on finding out how to set this up.

@jennpb , are you happy for me to drop existing event tracking with the exception of ticket booking? I am keen on keeping Google Analytics going at least until after wellcomelibrary.org has been closed to maintain continuity of reporting.

**Comment by davidpmccormick** [comment]
Since Eventbrite is an external link, I think you'll be able to track this already (at least to some degree).

**Comment by taceybadgerbrook** [comment]
Following discussion with Jenn, I'm going to park this work pending training.
