### ISSUE TITLE
Write a test for the case that token is undefined in useAuth hook

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5216]
# What is it and who's it for?
## What
A test against the `useAuth` hook that ensures the correct UI is presented if the `getToken` function returns `undefined`.
## For
Everyone (to make sure the site doesn't get into a broken state, such as it could pre #5195).

**Comment by alexwlchan** [comment]
I don't think we even have a `useAuth` hook any more; closing.
