### ISSUE TITLE
Button rationalisation

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5230]
References #4946 

- [ ] Split <Button> component into several new button components (to simplify logic) based on designs in Zeplin 
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e82201816226c6dac859cfc
  - [x] Solid Button
  - [ ] Outlined Button
  - [ ] Inline Button
  - [ ] Floating Buttons
  - [ ] Toggle
  - [ ] Information
- [ ] Add `link` variants for Solid/Outlined/Inline
- [ ] Add new Button components to Cardigan
- [ ] move styles from sass to styled components
- [ ] replace <Button> and other button like things on the site with new components
- [ ] remove old <Button> component and button like components
- [ ] remove old styles

**Comment by davidpmccormick** [comment]
Closing as broken down in #5335, #5336, #5337, #5338 and #5339
