### ISSUE TITLE
Content brief for user research group

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5234]
# What is it and who's it for?
Us, as a discussion document and as a brief for content writer

# User story
In order to get more people signed up to take part in user research
As a product team
I need a purposeful, inviting entry point for people to sign up and take part in research.

# Considerations
- Content design: what people will get from it, what we'll ask, what's our messaging?
- Our promise to participants re: data privacy #5212
- Audiences
- How to drive traffic to the signup 

Once content is drafted, approved etc, we'll publish via Prismic so that Alice, Dom, Jenn can edit the page if necessary, adding links to unmoderated tests.

Examples of companies doing this well : [Atlassian](https://www.atlassian.com/research-group), [First Direct](https://fdesign.firstdirect.com/), [Springer Nature](https://twitter.com/SpringerNature/status/1244942578459574272?s=20)

## Acceptance criteria TBC

# Implementation 

## Measurement
- Consistent user research exposure hours

## Other considerations 

- Impact on URL design

**Comment by jennpb** [comment]
Content brief WIP: https://docs.google.com/document/d/1onjy9vnB3acPVKGaaVG4yVUndQMubeNksSWoKR9nG54/edit?usp=sharing

**Comment by jennpb** [comment]
Will be pair written with Kate & Alice

**Comment by jamesgorrie** [comment]
Not sure if it's a good example:
https://signup.take-part-in-research.service.gov.uk/home

In the audience - do we have any thoughts on D&I? It might be inferred by saying WC's core audiences, but wondered if we had any more specific considerations for the user panel being representative of the people we're aiming to reach?

**Comment by jennpb** [comment]
Yes - D&I is the 'Access Panel' piece. We're working out whether we can combine the Inclusion Team's access panel into the same signup.
