### ISSUE TITLE
Update sentry SDK from version 3.27.2 to version 5.15.4

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5237]
https://docs.sentry.io/platforms/javascript/?_ga=2.109668165.1507980938.1586779002-1090390790.1586779002

**Comment by jamesgorrie** [comment]
As a point on this we also have a new weco non-profit account that we can think about setting up from scratch with the learnings from this account.

I would prefer to architect it out first to avoid us just having another spammy account that's hard to respond to.

**Comment by jennpb** [comment]
@jamesgorrie @gestchild Is this still needed or has it been superseded by other updates?

**Comment by alexwlchan** [comment]
Closing as stale; we don't currently use Sentry.
