### ISSUE TITLE
Adding new content to homepage

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5239]
# What is it and who's it for?
- Requested by content team
- Need a way to add content links to homepage so that activities that fall outside our normal programme can be given some visibility

Danny says:

> I can imagine that over the next few weeks we might be doing some things for which it's a legitimate consideration to have a link to on the home page if we understand that people aren't currently looking anywhere else on the site -- though there are of course other channels to promote them 

Decisions as of 15/4/20:
- This is a throwaway design solution for now; does not represent a massive design change to homepage
- The top-of-page messaging will need to change in response to a phased reopening of Wellcome Collection
- Limit the manual card group to 4 items. 
- Cards won't reflect live status, e.g. if it's an online event, it doesn't need the `fully booked` indicator

# User story
In order to provide a current view of what's on online, 
As a content editor
I need to be able to add links to internal and external content on the homepage.

This mechanism should be manual; the content team should be able to control this via Prismic, rather than hard-coding the links/cards

**Sample content:** 

At the moment we have two hard coded text links:
Read our latest stories -->
Explore our digital collections -->

I can imagine that over the next few weeks we might be doing some things for which it's a legitimate consideration to have a link to on the home page if we understand that people aren't currently looking anywhere else on the site -- though there are of course other channels to promote them 

Such things might be...

A new virtual tour of Play Well linked to from an existing page, text/link thus:
Take a virtual tour of Play Well [link to page on site]

A promo for an instagram zine workshop, text/link thus:
Join our live instagram zine workshop on 4 May [external link to insta story]

A promo for BBC's broadcast of Max Richter's Sleep
Drop off with Max, recorded live at Wellcome Collection [external link to BBC site]

A promo for an individual story on the site, text/link thus:
How did 17th century Londoners isolate themselves during the plague? [internal link to Story]

# Implementation 

- Top-of-page message to be hardcoded; likely to have occasional updates but not frequently enough to make it editable in prism
- Cards are directly editable. 
- Menu card includes Title, Summary, Image and Link (internal path or external link)
- 3 default size; 1 featured size card
- Group header = `What's online`
- Content team should be able to control the order of cards

## Testing and tracking

Will want to monitor CTR from manual links where the link is internal (e.g. link from a card to a story)

## Measurement
- Related KPIs : Total pageviews

**Comment by GarethOrmerod** [comment]
Homepage design on Zeplin:
https://zpl.io/VD0qXLg
zpl://screen?pid=5aab926b4b6efde01259e959&sid=5e970de00f36017ac7f868f3

**Comment by jamesgorrie** [comment]
@gestchild @davidpmccormick re: implementation - Do you have an idea of how you are going to fetch these from Prismic in a performant way given that we already fetch articles?

**Comment by pollecuttn** [comment]
@taceybadgerbrook FYI this is now done in case you are keeping an eye on the home page during our closure
