### ISSUE TITLE
Covid banner + thumbnail grid view is broken

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5244]
**What**
If you open the [viewer](https://wellcomecollection.org/works/qduqfunf/items?canvas=22&langCode=eng&sierraId=b19241653) and click the 'View all' button top left, before having dismissed the yellow banner, the page will appear broken.

![image](https://user-images.githubusercontent.com/1394592/79753734-50681280-830e-11ea-9b91-49265693385d.png)

**Comment by jennpb** [comment]
Dup of #5589
