### ISSUE TITLE
Limited viewer functionality in Safari

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5248]
**What**
Looking at the same item in Safari and Chrome, I noticed that I have limited functionality in Safari:
I'm missing:
- full screen button 
- Download button
- Thumbnail / View all button

**Where**
https://wellcomecollection.org/works/cwptbk56/items?canvas=1&langCode=lat&sierraId=b31889566

Safari:
<img width="1254" alt="Screenshot 2020-04-21 at 13 47 45" src="https://user-images.githubusercontent.com/1446139/79868252-8d4c0c00-83d7-11ea-91a8-210a9ec2fcda.png">

Chrome: 
![image](https://user-images.githubusercontent.com/1446139/79868157-6b528980-83d7-11ea-84d7-d2677b52bccc.png)

**Comment by gestchild** [comment]
@jennpb that looks like the non js version of the viewer you're seeing in Safari, but it's working fine for me. Which version of Safari do you have?

**Comment by jennpb** [comment]
Version 12.0.3 (14606.4.5)

JS is enabled in Preferences. Odd.

**Comment by gestchild** [comment]
@jennpb This behaviour is expected. Safari versions earlier than 12.1 don't support the Intersection Observer API, which we make use of in the viewer and so we fall back to the basic version.

Looking at google analytics for the last year, Safari versions without support for the Intersection Observer API accounted for fewer than 1% of traffic, and this is decreasing. In the last 2 months they've accounted for fewer than 0.5%.

**Comment by jennpb** [comment]
Great, then it's done! Thanks for investigating further.
