### ISSUE TITLE
Clicking outside `DropdownButton` doesn't dismiss dropdown for work downloads

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5249]
Clicking outside the downloads `DropdownButton` on a `/works/{id}` or `/works/{id}/items` page should dismiss the dropdown. Currently it doesn't.

<img width="737" alt="Screenshot 2020-04-21 at 15 11 20" src="https://user-images.githubusercontent.com/1394592/79876089-7fe84f00-83e2-11ea-92e5-e556df65cfca.png">

**Comment by jennpb** [comment]
Doesn't seem to be a problem now.
