### ISSUE TITLE
Search Relevance Research: Iteration 1

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5251]
**We think that**
The search functionality work should be bench marked and that improvements can be measured through a series of conversations with users to understand 

- What their search motivations are
- What the expected outcomes are
- What work arounds are being used to supplement the current functionality

**Therefore we hypothesise that**
Research can confirm the changes to search are providing the user with a succinct and useful search process and highlight any areas of improvement required. 

**As measured by**
Qualitative analysis methods

**Outcomes**

Research brief for all user groups
Research Script for all user groups
Booked research sessions
Session transcriptions in dovetail
Tagging and analysis

**Comment by alicerichmond** [comment]
Transcripts and data can be found here: https://dovetailapp.com/projects/0cac3e6c-1305-4971-bddc-8be9d41e7f93/readme

**Comment by jamesgorrie** [comment]
@alicerichmond are the transcripts in that project?
