### ISSUE TITLE
How/are people using 'guides' content on wellcomelibrary.org?

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5257]
To inform our work on content development for new researchers, we need some information on how existing content is being used on **wellcomelibrary.org**.

I'd like to get Analytics data for the past 12 months on usage of the following. This should include:
- Pageviews
- Users
- Time on page
- Bounce
- Exit

**Archive guides**
- From library website: Anything that falls under this page (including all guides within) https://wellcomelibrary.org/collections/archive-guides/
- From archives catalogue: Anything starting with ref AMS/G/ 
http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Overview.tcl&dsqDb=Catalog&dsqSearch=%28AltRefNo%3D%27AMS%2FG%2F%27%29&dsqNum=50&PF=No&dsqPos=0 (these are pages in the archive catalogue that reference a PDF guide. There are 82 records total. Please ignore any that don't begin with AMS.)

**Subject guides**
Three listed on this page: https://wellcomelibrary.org/collections/subject-guides/
https://wellcomelibrary.org/collections/subject-guides/introduction-to-popular-science-resources/
https://wellcomelibrary.org/collections/subject-guides/biography-and-family-history/
https://wellcomelibrary.org/collections/subject-guides/introduction-to-mortality-statistics-in-england-and-wales/

**Other random guides**
https://wellcomelibrary.org/collections/about-the-collections/archives-and-manuscripts/finding-medical-archives-elsewhere/
https://wellcomelibrary.org/collections/about-the-collections/archives-and-manuscripts/finding-recipe-manuscripts-online/

**Comment by taceybadgerbrook** [comment]
Summary stats including average time on page have been compiled in this Google sheet:
https://drive.google.com/open?id=182Jp6xSBcCwRrXNUfHwAz_o9rc_cGhDSbUjc5ct-dPg

**Comment by jennpb** [comment]
https://wellcomelibrary.org/what-we-do/history-of-wellcome-library/researching-wellcome-work/
https://wellcomelibrary.org/what-we-do/history-of-wellcome-library/wellcome-historical-medical-museum/

Sorry @taceybadgerbrook, I missed these two guides. When you have a moment can you please add them to the sheet? Thank you!

**Comment by taceybadgerbrook** [comment]
Analysis for all guides now available onhttps://docs.google.com/spreadsheets/d/182Jp6xSBcCwRrXNUfHwAz_o9rc_cGhDSbUjc5ct-dPg/edit?usp=sharing
