### ISSUE TITLE
Self service sign research panel participation 

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5271]
# What is it and who's it for?
Prospective user research participants self sign up functionality

# User story
In order to show interest in being part of the Wellcome Collection 

As a proespective user research participant

I need to submit my personal details to Wellcome to be informed of up coming research

## Acceptance criteria

- Content for the user sign up page
- Page design for the participation sign up page
- Airtable sign up form

# Implementation 

## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Do we need a way of filtering who signs up to prevent DDOS attacks? 
- AD&I team needs incorporated into the process

**Comment by alicerichmond** [comment]
First draft of content for sign up page 
https://docs.google.com/document/d/1EbJZ8dm6aamBAHJEvefiS2Y2YM1A3IA2ApZKZgSh-f8/edit?usp=sharing

**Comment by alicerichmond** [comment]
Draft 2 of the sign up page has been created and needs review, and next steps need to be decided

**Comment by DominiqueMarshall** [comment]
@alicerichmond  @jennpb  here's a link to a wireframe using the content linked above: https://zpl.io/aNgD45k

Let me know if there is a more up-to-date content doc that I should be looking at instead

**Comment by jennpb** [comment]
@DominiqueMarshall I think these are the most recent background patterns: https://drive.google.com/file/d/10VXVjfNrcba96p97WcmrmKgP7YmJeQcZ/view?usp=sharing - check with @GarethOrmerod if you have questions

**Comment by DominiqueMarshall** [comment]
@jennpb found one of those patterns in blue, updated design here: https://zpl.io/bLzWDDD

**Comment by jennpb** [comment]
Ok, so what do we need to finish this off?
- [ ] Hero image?
- [ ] Final copy
- [ ] Proofread and test signup form

**Comment by alicerichmond** [comment]
Form in airtable : https://airtable.com/shrGZSipOO4Yz57TT

**Comment by DominiqueMarshall** [comment]
Wireframe with hero image: https://zpl.io/2p6A0ky

**Comment by alicerichmond** [comment]
@davidpmccormick we have had a final change to the wording so that we communicate the different groups we would like to speak to properly the wording is as below


[access_KQ_DB_KQ.docx](https://github.com/wellcomecollection/wellcomecollection.org/files/4868570/access_KQ_DB_KQ.docx)
