### ISSUE TITLE
Appended GA string causes some subscription resources to be unaccessible

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5272]
**What**

Going from https://wellcomelibrary.org/using-the-library/how-to/databases-a-z/ on the library site, three resources are unusable because of the ga strings that get appended to the URLs. If you try to go to any of the resources below  from the above page, their pages do not load.

The resources are:
- Early English Books Online (EEBO)
- Eighteenth Century Collections Online (ECCO)
- Historical Texts

The vendor of those resources isn't offering any short-term fix because we're appending the ga string. Can the GA string not be appended to those three resources?

NB login issues should be resolved by the removal of SSO in May 2020. Login to get past the login screen to see the issue.

**Where**

From: https://wellcomelibrary.org/using-the-library/how-to/databases-a-z/ 

To:
-  https://0-historicaltexts.jisc.ac.uk.catalogue.wellcomelibrary.org/#_ga=2.258236746.1560845606.1588155983-3325431.1558522762
- https://0-historicaltexts.jisc.ac.uk.catalogue.wellcomelibrary.org/#_ga=2.258236746.1560845606.1588155983-3325431.1558522762
- https://0-historicaltexts.jisc.ac.uk.catalogue.wellcomelibrary.org/#_ga=2.258236746.1560845606.1588155983-3325431.1558522762

**Acceptance criteria**
- The ga link is not appended to these three links on the A-Z databases page

**Comment by pollecuttn** [comment]
Slack convos on this:
https://wellcome.slack.com/archives/C294K7D5M/p1588328702088400
https://wellcome.slack.com/archives/C294K7D5M/p1588328847089800

**Comment by davidpmccormick** [comment]
Updated a GTM variable regex to exclude the historical-texts subdomain:

```
function() {
 return function(model) {
   var domainList = [
     /^(?!0-historicaltexts\.jisc\.ac\.uk\.catalogue).+\wellcomelibrary\.org/,
     /^(?!iiif).+\wellcomecollection\.org/,
   ];
   var ga = window[window['GoogleAnalyticsObject']];
   var name = model.get('name');
   ga(name + '.require', 'linker');
   ga(name + '.linker:autoLink', domainList, true);
 };
}
```

Those links should no longer have any GA string appended.
