### ISSUE TITLE
Navigating an archive collection

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5281]
# What is it and who's it for?

Researchers using archive collections

Problems to solve:
How to navigate an archive
Knowing position no matter where you've come from:
- search engine > archive collection
- search engine > item in archive collection
- catalogue search > archive collection or item in archive collection
Knowing what this page is
Knowing where you've been

Identify part of collection + place within it

# User story

As a new researcher, 
I need to be confident I’m in the right place at the right time 
So that I can get a comprehensive overview of the structure of the archive

As an experienced researcher
I need access to the whole archive tree
So I can understand the context of what I’m looking at

# Assumptions
- A well-designed navigational structure will help people know where they are in an archive collection
- That people will use the navigation to browse an archive collection

**Comment by pollecuttn** [comment]
Sketching: 
https://drive.google.com/drive/folders/1oFPe5kh1huXA-2wb4FI_4XXM2kdYcFag

**Comment by pollecuttn** [comment]
14 May 2020:
What to start on:
- Progressively disclosed navigation device 
- Breadcrumbs

Exploring two ideas for how much of structure to expose:
- Expand to full file structure with scrolling nav (Gareth E model)
 -Show only parent + sibling relationships (Jonathan model)
Gareth and David are going to start working on some ideas for the core components: breadcrumbs, nav structure
Dom is looking at content-related things, and how it all fits together with the nav, sections and items

**Comment by pollecuttn** [comment]
zpl://project?tags=Archives&pid=5aab926b4b6efde01259e959

**Comment by jennpb** [comment]
Prototypes behind a toggle:
- navigation tree (pp/cri)
- breadcrumbs (all)
- series folders at bottom of page

Intention is to test this w/c 27 July

**Comment by jennpb** [comment]
Getting ready for round 2 of testing with external users:

**Tree navigation**
- Make tree navigation call updated API
- Expand/collapse tree levels
- Highlight/centre current work on tree nav

**Sibling/parent boxes on works page**
- Design of series/section-level boxes
- Show user where they currently are

Breadcrumbs: leave as is for round 2 of testing

**Comment by DominiqueMarshall** [comment]
Whimsical board showing the user flow for the archives _(work in progress)_: https://whimsical.com/4AJYDgFdeXQjhs5jbZYKTK

**Comment by pollecuttn** [comment]
20 August

For build
- [ ] Archive title above title
- [ ] Collection contents and icon in a box

The styling of the hierarchy tree can wait until we know if it's useful for non-experts

**Comment by DominiqueMarshall** [comment]
Latest page designs for second iteration testing:

- Top level collection page: https://zpl.io/a7MryAW

- Section level page: https://zpl.io/V4W8JmJ

- Item level page: https://zpl.io/Vqopxz5

cc @davidpmccormick
