### ISSUE TITLE
Presentation of information about archive collections

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5282]
# What is it and who's it for?
Researchers using archive collections

Problems to solve: 
- Prioritising information about archive on a /works page
https://alistapart.com/article/priority-guides-a-content-first-alternative-to-wireframes/
- Answer the user question: what will I find here?
- Adapt /works template to accommodate all archive catalogue information

# User story

As a new researcher 
I need clear and understandable information about the archive
So that I can understand what I’m looking at

As a researcher
I need information about the archive collection
So I can understand the context of what I’m looking at

As an experienced researcher
I would like more detailed information about the collection 
So that I can build connections with other material, here or elsewhere

## TODO
- Review works page UX https://github.com/wellcomecollection/wellcomecollection.org/issues/5368

**Comment by DominiqueMarshall** [comment]
Whimsical board of content you'll find at each level of an archive. Includes examples of how the level of content varies: https://whimsical.com/4jnDSBCY5taaVnKxD1Gf8U

**Comment by pollecuttn** [comment]
28 May 2020:
- improve breadcrumbs, incl. don't highlight the final thing on the breadcrumb, move breadcrumbs above title, have everything inside central dropdown if needed
- changes to siblings
- put the above behind a toggle

Then can start showing to colleagues (Dom & Alice)

**Comment by GarethOrmerod** [comment]
Consolidation of Slack discussions regarding breadcrumbs:
zpl://screen?pid=5aab926b4b6efde01259e959&sid=5ed6793a2f84953e0064550a
https://zpl.io/2GJqYKj

**Comment by jennpb** [comment]
In prep for round 2 of testing with external users:

**Breadcrumbs**: leave as is, retest

**Works page**
- Clarify `Identifiers` section and language

Hold off until round 2 testing completed:
- Confirm arrangement of notes; set arrangement of data in API
- Labelling CTA for tree navigation
