### ISSUE TITLE
Usage data gathering for Library website / Codebreakers

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5292]
# What is it and who's it for?

Gathering data for Jenn to help prepare for library website shutdown

Codebreakers was a curated collection of digitised genetics archive collections, digitised books and context-setting articles, collection overviews, and a timeline, created in 2013. 
https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/ 

We don't intend to migrate Codebreakers like-for-like to wellcomecollection.org but it would be useful to know to what extent we'll need to compensate for its functionality. 

First step is to look at how it's been used since it was last evaluated in 2014: https://wellcomecloud.sharepoint.com/:w:/s/wc2/DE/Production/ES3kVMNNuWlIv7L62NtZj5YB-vbljB3agDA_ItiWcBhZgA?e=LMfwH8

# Questions

## Brand recognition
 Is 'Codebreakers' strongly associated with Wellcome Library; do people search Google for Codebreakers? 

## Search queries
Common search terms used to find these archive collections ([full list of archives included in Codebreakers](https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/digitised-archives/))

Any other possible connections? e.g. `genetics timeline`, `history of genetics`, etc

## Site usage

**Pageviews and Average Time on Page for the following pages:**

- https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/digitised-archives/ **+ All 22 child pages of the above**

- https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/history-of-genetics-article/

- https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/genetics-timeline/

**Moving from website to catalogue**
From all individual archive collection pages linked from https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/digitised-archives/, I want to know what % of users then go on to view the archive in Encore as the next step, by using this component (no event tracking on this that I'm aware of)
<img width="555" alt="Screenshot 2020-05-20 at 15 16 22" src="https://user-images.githubusercontent.com/1446139/82468811-28a9cd00-9abb-11ea-8a0d-e4889ae5988b.png">

That would look like going from this page 
https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/digitised-archives/carlos-paton-blacker/ 
to this page https://search.wellcomelibrary.org/iii/encore/search/C__SppLw==cpb%20diggenetics__Ff:facetlocations:dlnk:dlnk:Digitised%20content::__Orightresult?lang=eng&suite=cobalt

**Comment by taceybadgerbrook** [comment]
Codebreakers page views have increased by 15% in actual numbers but decreased by 70% in proportion to wellcomelibrary.org total page views. Only 1% of archive pages are viewed as a result of clicking on links on Codebreakers pages and less than 1% of total visits resulting from Google searches originate from Codebreakers-related topics. 

Here are links:
[Full report](https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B4BBC1D65-B4E6-4C3B-A259-638E7C345915%7D&file=5292%20Codebreakers.docx&action=default&mobileredirect=true)
[Page view analysis](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7BB48960DE-634D-4E18-82CB-27039AA2ADC9%7D&file=5292%20Data%20Studio%20page%20views.xlsx&action=default&mobileredirect=true)
[Google search term analysis](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B4020E5DA-43E6-41A1-B4DD-A325304A5A3B%7D&file=5292%20Google%20search%20terms.xlsx&action=default&mobileredirect=true)
