### ISSUE TITLE
Metric to measure breadth of collection accessed

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5297]
**We think that**
Breadth should encompass numbers of selects as well as numbers of unique workIds selected.

**Therefore we hypothesise that**
A succinct and accessible way to report breadth is the number of most popular unique workIds accessed by a fixed percentage of total selects 

**As measured by**
Python preliminary analysis

**We are right if**
stakeholders understand the metric without additional explanation

**Comment by taceybadgerbrook** [comment]
Illustration of proposed metric to replace skew: number of works viewed by 50% of users:
https://wellcomecollection.invisionapp.com/freehand/increase-breadth-of-collections-accessed-RNXV4trzN

**Comment by taceybadgerbrook** [comment]
I investigated how many works were accessed of 100,000 events (Kibana's limit if not using "scan" function) and found that reproducing the illustration locates the 50% mark amongst works that only attract 1 or 2 views. This is because of the number of works in the "long tail." A more sensitive metric might be the number of works at the point where the long tail begins. Analysis of 100,000 events has this as 5% of views.

I'm going to investigate whether a whole quarter's worth of data confirms 5% as a more useful metric before suggesting this change and producing a graph of quarterly values for wider consumption.

All code will shortly be moved to Github.

**Comment by taceybadgerbrook** [comment]
To get a sense of how sensitive a metric based on 50% of views would be, I used @jamieparkinson 's [calculator](https://wellcome-clicks.glitch.me/) to produce the following time series. The calculator returns the % of works viewed (ie clicked) by 70% of users.

Q1: 3.5
Q2: 10.6
Q3: 7.9
Q4: 3.8

This surprising variation may be a reflection of improvements in search. Results are matching searches more closely and so users are having to search through fewer works?

**Comment by taceybadgerbrook** [comment]
If we value all users and all searches equally, maybe breadth should be simply the total number of works viewed:

Quarterly workIds viewed:
Q1: 50,993
Q2: 75,445
Q3: 72,792
Q4: 56,740

**Comment by jamieparkinson** [comment]
Worth bearing in mind that the calculations don't take into account how many works were available _at the time of the click_ (they use the current number) - so anything from pre-whole-catalogue-search won't be quite right...

**Comment by taceybadgerbrook** [comment]
Ok, good to know although comparing the 2 sets of figures does seem to suggest there is something affecting viewing besides the quality of the catalogue on offer such as improving search. The second set of figures are from Kibana.

**Comment by taceybadgerbrook** [comment]
I am going to put together a presentation on this for the next peer review.

**Comment by taceybadgerbrook** [comment]
This metric will be produced as follows at the end of each quarter beginning with Q1 2020/21:-
- % of all available works attracting 50% of clicks
- Total number of available works (as at end of quarter)

Because the collection API changes each quarter, this will be stored here:
https://wellcomecloud.sharepoint.com/:f:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Breadth%20of%20collection%20accessed?csf=1&web=1&e=CXQr3d
