### ISSUE TITLE
Assumed search intents for testing and further research

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5298]
# What is it and who's it for?
Experience + Data teams, so we can work toward improving search relevance

We need to understand more about what users are trying to do when searching the catalogue. [Assumed intentions and expectations are documented here](https://docs.wellcomecollection.org/catalogue/search/intentions-and-expectations), but we need more information to help flesh out relevant examples, and clarify search intentions based on quant/qual data. 

This information feeds into testing of search queries. 

# How we'll do it
- [x] @taceybadgerbrook to analyse search data to identify search patterns that can inform assumptions (starting with #5296)
- [x] @alicerichmond to extract specific examples from recent round of research with internal users
- [x] @jennpb to mine previous search-related research for examples
- [x] Get some initial feedback on document from Search Relevance crew - shared on 29/6/20, asked for feedback by 6/7/20
- [x] Experience + Data to improve [intentions and expectations doc](https://docs.wellcomecollection.org/catalogue/search/intentions-and-expectations)

**Comment by jennpb** [comment]
@pollecuttn @DominiqueMarshall @taceybadgerbrook @alicerichmond @jamesgorrie 

I've updated this document with all the assumed search intentions as evidenced by existing user research https://docs.google.com/document/d/1aIbE4IAOZb1Cbyp9ei81HtZ5w98AVZHIrudP9RUG1Is/edit?usp=sharing. There's overlap between the Google Doc and the Gitbook docs. Our ultimate aim is to improve the [Gitbook docs](https://docs.wellcomecollection.org/catalogue/search/intentions-and-expectations)

What we need to do next is to work on the Examples and Expectations for each of the search tasks. We can get this data from @taceybadgerbrook and @alicerichmond 's quant and qual research.

We should also go through @taceybadgerbrook's analysis and see whether she's spotted any other behaviours not noted in the documents.

All of this info can be dumped into the Google Doc until we want to start moving things across to Gitbook.

**Comment by alicerichmond** [comment]
Diary Study communicated to 4 Wellcome staff to help define search terms and intentions, this study will close on the 23/06 https://airtable.com/shrrCEJrP3xCevhm4

**Comment by alicerichmond** [comment]
Diary study link https://airtable.com/shrrCEJrP3xCevhm4
