### ISSUE TITLE
Zoomed images getting stuck

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5340]
**What**
Hello! I'm not sure if this is the right channel, but quite often (and now) while I'm looking at something in the player the images gets 'stuck' to my mouse after zooming in/out (it means I can't zoom/in out or centre the image). It's fine after a refresh, but not great if spent time trying to locate a page. Is this a known issue? Or is it me?! Thanks :slightly_smiling_face:

Reported by Nicola Cook

https://wellcome.slack.com/archives/C294K7D5M/p1593446743395400

**Where**

**Comment by pollecuttn** [comment]
This is happening on wellcomelibrary.org's universal viewer.

From Jenn: We can't do any development on the Viewer on wellcomelibrary.org. The version we're using is well out of date, and our in-house team has never done any development work on that site. All we can do it let Digirati know about it, but my assumption is that we can't fix it without upgrading to a newer version, which we're not going to do.
