### ISSUE TITLE
Zooming behaviour on wc.org

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5342]
**What**

Many of the volumes have pages which are too large to fit into the viewing window, even when toggled to full screen. Once you've clicked into the zoom (magnifying glass) button, you can zoom out so that it's possible to scan the whole page at once but then it's not possible to move to the next page without closing the image and starting all over again. I realise there's the thumbnails or the overview but they're usually too small to read. Is this something which testing has reported, or is it just me that finds this problematic?

https://wellcome.slack.com/archives/C294K7D5M/p1593602235437000?thread_ts=1593446743.395400&cid=C294K7D5M

**Where**

**Comment by alicerichmond** [comment]
Comment from user

"It was really just the fact that it moved so quickly. It was not immediately intuitive in the sense that a lot of the time if you’re a Mac user, you use that finger movement to open things up and make them bigger and smaller but if you use them on that, it’s way too sensitive for that and the little thing in the bottom corner that tells you how to do that, obviously you don’t bother finding that for quite a long time, so an element of user uselessness involved, as well. “Oh, that’s how you do it!” but I think in general it works well once you get used to it, it was good.

There was a slight problem trying to show my Research Assistant how to do it but that was to do with the kind of tech I was using at my end. It was nothing to do with it – it was too unstable for that but I’ve not really had any problems with it other than those. It’s not 100% intuitive but it was possibly much easier with a mouse than it is with a pad."
