### ISSUE TITLE
Tagged work not surfacing in search

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5344]
**What**
Googling, "Philadelphia poor guardians" matches to tag, "Philadelphia (Pa.). Board of Guardians of the Poor" but search is not returning the tagged work.

**Where**
Google query:
![image](https://user-images.githubusercontent.com/32418070/86358506-7ba0a380-bc67-11ea-8094-7e1fd0a6b916.png)

Works page results:
![image](https://user-images.githubusercontent.com/32418070/86358611-aab71500-bc67-11ea-8414-f4878c2e9179.png)

**Comment by jennpb** [comment]
This appears to have been resolved by recent changes to the search query. The linked title from Google is picking this up from the subject tag.
cc @jamesgorrie @harrisonpim
