### ISSUE TITLE
Search query, "telephone" returns Aids posters

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5363]
**What**
Typing, "telephone" into search returns works with telephones at 8th place on page. Aids posters appear at top of search results due to absence of boosting subject/title over copyright note.

**Where**
The word, "telephone" appears in the copyright note as part of, "telephone number."

**Comment by jtweed** [comment]
Closing this as it seems massively improved by the recent changes to the search query relevance.
