### ISSUE TITLE
Review prototype with archives team

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5365]
UX review of prototype with devs and user researcher

**Comment by DominiqueMarshall** [comment]
Review the prototype that has been created for archives and check:
 
* What problems are we trying to solve?
* What has been built already?
* Is the data that we want to display showing correctly?
* Are there any refinements we need to do before testing?

**Comment by DominiqueMarshall** [comment]
**Actions:**

@gestchild 
- to look at creation of a user toolbar for the toggles
- amend RefNo's to AltRefNo's
- switch navigation tree to new API data

@alicerichmond 
- Book research testing for the week of 27th July

@DominiqueMarshall 
- review UX of search result cards
- book follow up meeting with team to review journey again before testing

**Comment by alicerichmond** [comment]
Research brief: [here](https://wellcomecloud.sharepoint.com/:w:/s/wcdigitalexperience/Ea0lVVoPTZFEmuTYPSTc964BvUBapKJMj_922xj14FmhSg?e=oSqiJX)

@jennpb and @DominiqueMarshall please could you review and provide comments
