### ISSUE TITLE
Which search results should be exposed for archives?

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5366]
## TODO
- UX and devs to decide on which search results should be exposed, conversation needs to include Jonathan re search
- expose those results

**Comment by jennpb** [comment]
Some thoughts from a discussion in design review. We've got some options, with pros/cons

**Option 1**: Expose `Collection` `Series` and `Items`
**Pros**: Pulls up most relevant _level_ based on your search
**Cons**: Series level may just be a stub record for the items contained within - it's an extra click that a user need not make. Larger number of results increases likelihood of frustration for choosing the 'wrong' one

Option 2: Expose `Collection` and `Items`
**Pros**: Collection can be given priority as promoted result; item is the tangible, requestable thing. By leaving out the Series level we can get people straight to the item to view/request. Item result can display `Part of [Series] in [Archive collection name]'. Clicking through to results from an item brings you to ancestor, which shows this item and all sibling items for added browseability
**Cons**: ?

Option 3: Expose `Collection` and `Series`
**Pros**: Series page contains all child items to be viewed in one place
**Cons**: would need to accommodate item-level snippets on search result card, resulting in additional clutter

**Comment by jennpb** [comment]
After discussion with the Search crew, we're going to go with Option 1: expose all levels in search results. This means we'll need to add `AltRefNo` and `Part of` info to the search result card as described in #5367 

cc @DominiqueMarshall
