### ISSUE TITLE
Review search results card - collections card and archives item card

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5367]
Review search results cards for:
- collections cards
- archives item cards

Decide what changes need to be made to which cards and by whom

**Comment by DominiqueMarshall** [comment]
Work in progress on search result cards: https://zpl.io/aR5D8Ev

**Comment by pollecuttn** [comment]
Next to work on: 

- [ ] promoted result
- [ ] iterating on last result in the examples shown

**Comment by DominiqueMarshall** [comment]
Promoted search result + archive item search result card: https://zpl.io/bJyv8K6

Promoted search result + archive collection search result cards: https://zpl.io/brwEAN7

**Comment by pollecuttn** [comment]
Add to search results cards per zeplin wireframes:
- [ ] reference
- [ ] part of
- [ ] found in

**Comment by jennpb** [comment]
Done with addition of archives reference information to the search result card.

No scope for Promoted Results at present.
