### ISSUE TITLE
Review works page UX for archives collections 

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#5368]
In relation to user tasks:
- read about what the collection is and what's in it
- read arrangement of archive materials (high-level view of arrangement and what's inside)
- view information about connected works / works within the collection
- look through all sections and select
- see which parent archive I am in/how current work relates to this

**Comment by DominiqueMarshall** [comment]
For second iteration of prototype:

- [ ] Rearrangement of content structure in About This Work (can be done in the API)

- [ ] AltRefNo - needs to be added to the header/page design

- [ ] Overview boxes - visual styling and feedback, language/navigational context updates

**Comment by pollecuttn** [comment]
- [ ] Create collections-level page

**Comment by pollecuttn** [comment]
Explore mobile version
Explore combining 2nd and 3rd examples

**Comment by pollecuttn** [comment]
Prep for testing:

- @DominiqueMarshall to upload designs to zeplin
- @gestchild to build collections overview page
