### ISSUE TITLE
Launch DJS audience survey for Marketing & Audiences - 10 August

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5405]
# What is it and who's it for?

Surveying our users as part of the DJS audience segmentation project.

Runs from **10-24 August (take down morning of 24 Aug)**

# Text

Button:`How do you spend your free time?`
Button link: `https://interviewer.djsresearch.com/scripts/Dubinterviewer.dll/Frames?Quest=61601&SurveySMP=1`
Popup heading: `Help us understand your needs`
Popup text:`We'd like to know how you feel about a range of issues, as well as how you spend your free time. Your responses to this survey may inform (among other things) how we adapt our offer in the context of the Covid-19 pandemic. The survey takes around 10-15 minutes.`

**Comment by davidpmccormick** [comment]
My brain wants `(among other things)` to come between `may` and `inform` instead of after `inform` – it's more things like responses rather than more types of informer?

**Comment by jennpb** [comment]
You're right - it reads better as `may (among other things) inform`
