### ISSUE TITLE
Iterate on table style for improved legibility across breakpoints

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5407]
# What is it and who's it for?
Iterating on our [existing table style](https://cardigan.wellcomecollection.org/?path=/story/components--responsivetable) for better legibility across whole site, including content pages and works.

Lots of screenshots here https://www.notion.so/wellcometrust/Table-styles-Q4-2019-20-81382c46e78e45f0ad7db34cd4dbc430 

Where we can improve on this is where we have tables that are 3+ columns and 3+ rows, particularly across different breakpoints (keeping in mind that library researchers often have multiple windows open, which can result in awkward resizing. It can be quite difficult, without any horizontal lines, to track information across a row, or multiple rows.

# Implementation
- [ ] Enable creation of tables on content pages, via Prismic

**Comment by pollecuttn** [comment]
@GarethOrmerod are there zeplin designs that can be added to this issue?

**Comment by GarethOrmerod** [comment]
Proposed designs on Zeplin:
https://zpl.io/a3mvqgl
zpl://project?pid=5aab926b4b6efde01259e959&tags=Tables

**Comment by jennpb** [comment]
closed via https://github.com/wellcomecollection/wellcomecollection.org/pull/5562
