### ISSUE TITLE
Get Involved section development

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#5455]
We are replacing the top-level section `What we do` with a new section called `Get involved`

## Initiatives
- Update global navigation (header menu and footer) with new Get involved section #6345 
- Relocate 'About us' to global navigation #6347
- Improve info hierarchy of 'About us' to build stronger relationships between content within #6348

**Comment by dannybirchall** [comment]
I can't access the productboard to see the feature here

**Comment by jennpb** [comment]
**Get Involved - content**

- [ ] get remaining promo photos from Ben [DB]
- [ ] publish User Panel page in Prismic [JPB] DONE
- [ ] redirect existing /user-panel to new Prismic page [JG] DONE
- [ ] Reinstate marketing redirect for /user-panel to new Prismic page [JG] DONE

**Replace What We Do with Get Involved**

- [ ] publish /pages/YDaZmxMAACIAT9u8/ [DB]
- [ ] redirect /pages/WwLGFCAAAPMiB_Ps to /pages/YDaZmxMAACIAT9u8/ [JG]
- [ ] swap out WWD with Get Involved in global nav and footer as positioned in screenshot [JG] https://github.com/wellcomecollection/wellcomecollection.org/issues/6345

**About Wellcome Collection > About us**

- [ ] Rename About WC to About us [DB]
- [ ] Turn page into Landing page format - tidy up copy and content to suit [DB]
- [ ] About us inherits section-level landing page style as all other top-level sections
- [ ] Put About us in the top nav and footer as positioned in screenshot https://github.com/wellcomecollection/wellcomecollection.org/issues/6347
