### ISSUE TITLE
Supporting timed ticketing

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#5456]
# Background and scope

When Wellcome Collection reopens, we will be offering entry through timed ticketing (via Eventbrite). The scope of this work includes:
- designing a timed ticketing page, with CTAs to book a ticket
- creating a user flow that connects reopening content for visiting to the ticketing flow
- adapting events as needed to accommodate ticketed events

## Measures

- Have we collaborated with the Bookings group?

- Can users identify and access digital events

## Acceptance criteria
- [x]  Page for 'Book your ticket' published (hard-coded)
- [x] Page is linked from 'Welcome back' page
- [x] Active links to Eventbrite pages for two ticket types

**Comment by jennpb** [comment]
https://wellcomecollection.org/covid-book-your-ticket
