### ISSUE TITLE
Content to support safe reopening of the venue

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#5457]
# Background and scope

When Wellcome Collection reopens in October, the website will need to support content that helps users understand what actions we've taken to ensure their safety, and how entry/visiting will work.

Working with the Editorial team, we'll need to:
- Ensure that key messages are understandable and easy to find
- Ensure that the content and design is inclusive
- Adapt the homepage for key reopening messaging
- Use graphics that join up with the in-venue experience, where appropriate and where it adds value

## Measures

- Have we consulted with Editorial, Marketing and Ticket Booking groups?
- Have we tested the content and flow with users with access needs?

**Comment by jennpb** [comment]
23 Sep - Venue bookings go live
 
w/c 14 Sep
- [ ] Finish analysing user research, decide what we can fix before launch
- [ ] Do content or tech fixes
- [ ] QA to ensure everything is ready for launch 
 
w/c 7 Sep (David, Dom not here - Jenn holiday?)
- [ ] Conduct user research (with observers if possible)
- [ ] Begin to analyse results
- [ ] Begin any pre- go-live content/design/tech fixes (UX Designer and Developer on holiday) 
 
 
w/c 31 Aug 
- [ ] Plan for user research
- [ ] Line up observer-notetakers (someone from library, someone for access, someone for ticketing, someone from content)
- [ ] Thurs 3 Sep: Review content design with Danny and Kate; design/dev to pick up any changes
- [ ] Confirm what we’re doing with the homepage
- [ ] Confirm any changes that need to be made to support online events (e.g. event statuses)
- [ ] Confirm any changes or messaging needed on wellcomelibrary.org 
 
 
w/c 24 Aug 
- [ ] Review design and content recommendations from satellite groups
- [ ] Wed 26 Aug: Work with Kate to establish how many pages to create, how content fits together, what design/devs need to prep for (new user interface design components, user flows throughout site)
1 new page for timed entry [NB may need subpages to address library-specific or general process info]
1 new page for how we will protect you (visitors) and what you need to protect others
(2 new images required - HB will let Ben know about new photography required & timeline. Some imagery may need to be replaced elsewhere but the images for new pages should be priority)
Some new info will be reflected across the site (e.g. yellow boxes/exhibition pages) Tania, Lisa(?) and Lalita are discussing this.
 
- [ ] Design timed entry page
- [ ] Plan for user research on ticketing flow - recruitment, research questions
 
w/c 17 Aug 
- [ ] User questions from Bookings Group due by Wednesday 19 Aug [JPB]
- [ ] Review with Dom how ticketing is set up
- [x] Consolidate all incoming documentation into one place on Sharepoint [JPB - share with team] https://wellcomecloud.sharepoint.com/:f:/s/wcdigitalexperience/Eojm1oFoEG1HrS6V-KGnJ2AB7F81BuV1Kwdl3xFF7ZjloA?e=A4cEbe 
- [ ] Discuss recruiting users with access requirements for user research (talk to Orla?)

**Comment by jennpb** [comment]
Decisions 1/9/20:
- Build static pages with actual content first 
- Build editing functionality into Prismic as needed (prioritise by potential frequency of updates)

**Comment by GarethOrmerod** [comment]
Wireframes and design work for reopening will be added to the [Reopening](https://zpl.io/2GZ5LzW) tag on Zeplin

**Comment by pollecuttn** [comment]
14 September review of user testing results 
https://wellcomecollection.invisionapp.com/overview/Reopening-WC-ckel8tvod0ab30179gl0id0i5/screens

### Home page

- [ ] Section header e.g. "Reopening soon" or "We're reopening soon", followed by
- [ ] Featured card
- [ ] Rewrite copy for the featured card to fit the message of needing to book a ticket
- [ ] Select an image for the featured card

### We're open

- [ ] Page flow redesign for signposting, hierarchy, mobile
- [ ] Add links to 'Plan a safe' visit off to the relevant page

**Comment by jennpb** [comment]
General comment on amount of text - 
There is a lot to read and take in. How much of it is essential to know before a visit? Is there any way we could be a bit more demonstrative and directive, for example saying 'Here's what you need to know:' as opposed to a more passive 'Find out more...'? This particularly applies to ticket booking where the user really needs to understand what they can/can't do.

**Comment by pollecuttn** [comment]
Updated behind toggle:
https://wellcomecollection.org/covid-welcome-back
https://wellcomecollection.org/covid-book-your-ticket
