### ISSUE TITLE
Two 'primary' CTAs on digitised work pages

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5460]
**What**
There are two `ButtonSolid` components side by side on work pages with digitised works – 'View' and 'Overview'. This implies two 'primary' actions, which is possibly confusing. Should one of them be `ButtonOutlined`?

**Where**
https://wellcomecollection.org/works/ccq7ac2t

![image](https://user-images.githubusercontent.com/1394592/90244224-3d7ece00-de28-11ea-9790-1b1fb131a1f1.png)

**Comment by jennpb** [comment]
We removed the Overview button so this is no longer an issue.
