### ISSUE TITLE
Improve hierarchy and presentation of search filters, sort options, pagination

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5467]
# What is it and who's it for?
Collections researchers

Let's revisit the order, hierarchy and presentation of the components that make up 'search'.

**Why now?**
- We've observed in user research that users often hover around the filters while talking about narrowing a search, yet fail to spot the filters
- We intend to add around 4 more filters (specific to the type of search: `all collection` or `images only`)
- We intend to test 'pre-filtering' a search (user selects `all collection` or `images only` before entering a query)
- We intend to add a promoted search result for archive collections
- The relationship between the radio buttons and filters is unclear.

![Screenshot 2020-08-18 at 08 21 05](https://user-images.githubusercontent.com/1446139/90483473-a918b200-e12c-11ea-8a7a-28b48a13a592.png)

Annotations:

1. Consider placement of radio buttons above or below search bar
2. Draw a stronger connection between search bar and filters. Consider making filters bar more visually prominent
3. Sort filter should relate more closely to the list of results
4. Number of results seems more prominent than necessary; arguably the filters and sort options are more useful, yet their font size and overall visibility is less
5. Any proposed adjustments to pagination?

Additionally, when we introduced promoted results, their natural position would come _before_ the sort options; we promote a single result, the user can sort the rest of the results.

**Filters to plan for** https://github.com/wellcomecollection/platform/issues/4724

**Comment by jamesgorrie** [comment]
Just a thought from reading through this - is the labels `All collection` and `Images only` misleading in the sense that only feels like a filter, where as it is actually a completely different data set?

Thoughts of how to best explain it from what we're showing is `The collection` and `Images`, but I am also aware what we call it and what's useful are often out of whack.

**Comment by davidpmccormick** [comment]
The 'active filters' probably deserves some attention as part of this piece of work as well.

![image](https://user-images.githubusercontent.com/1394592/90492558-3bbf4e00-e139-11ea-8093-f3f0edebaa8c.png)

**Comment by jennpb** [comment]
As discussed on 25/8, we'll start by exploring using the mobile filters by default as an option to test.

<img width="596" alt="Screenshot 2020-08-25 at 13 52 40" src="https://user-images.githubusercontent.com/1446139/91176579-629df700-e6da-11ea-8fb2-ac20de12f927.png">

**Comment by GarethOrmerod** [comment]
Just for visibility—these are some old designs on Zeplin which aligned the filters closer to the search. 
zpl://project?pid=5aab926b4b6efde01259e959&tags=Search%20Filters
https://zpl.io/VYXEdrM

**Comment by davidpmccormick** [comment]
@DominiqueMarshall would we say this is done? Feels like pretty much all of it has been covered?

**Comment by DominiqueMarshall** [comment]
> @DominiqueMarshall would we say this is done? Feels like pretty much all of it has been covered?

I would agree yeah, it's pretty much covered. The main thing to still look over is any adjustments to the pagination, but that can be part of a future iteration
