### ISSUE TITLE
Access control for digitised content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5470]
# What is it and who's it for?

Collections researchers

Our digitised content is made available to researchers under these four access conditions:
- Open
- Open with advisory
- Restricted
- Closed

Each condition comes with a host of design considerations we need to make in order to make this content as accessible as possible while putting the fewest barriers in the way of researchers. 

The current Universal Viewer on wellcomelibrary.org handles these conditions as follows:
- Open with advisory = Click through Terms and Conditions; sets browser cookie for subsequent visits for a full day
- Restricted = triggers a login; uses patron login to connect pre-approved users to the content
- Closed = displays a padlock icon on closed images; fully closed digitised items not visible to public

Documentation for this feature can be found here https://www.notion.so/wellcometrust/Digitised-content-access-control-Q4-2020-Q1-2021-fa5b296f9507455ab407faeaf5f40a57

## TODO
- Read through documents; clarify any questions with Collections Information team

# User story
As a researcher
I need to know whether there are any access conditions on this material
So that I can use the material responsibly

As a researcher
I want to know why material was given the access restriction it was
So that I can use the material responsibly

**Comment by alicerichmond** [comment]
Workshop materials output for open with advisory 

https://miro.com/app/board/o9J_khSoMc0=/
