### ISSUE TITLE
Assess hyperlinked notes in archives data for future pain-points

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5475]
# What is it and who's it for?

Collections researchers
Us

The archive collections contain many different types of links to material across Wellcome Collection/Library and beyond. Some of these will become dead or redundant once we shut down Encore and wellcomelibrary.org. Others we may just need to verify that redirection will/is happening.

This issue collects the examples:

## API/Search
**Donor searching**
https://search.wellcomelibrary.org/iii/encore/search/C__S%22Donor:%20Medact%22__Orightresult__U?lang=eng&suite=cobalt
"For books, reports and other printed materials from the collection of Medact, please see the main Library catalogue." - Linked to a list of all non-archival materials donated with Medact material.
https://wellcomecollection.org/works/qq7nc5j9

http://catalogue.wellcomelibrary.org/search~S12/?searchtype=Y&searcharg=%22Donor%3A+FPA%2C+formerly+the+Family+Planning+Association%22&searchscope=12&SORT=DZ&extended=0&SUBMIT=Search&searchlimits=&searchorigarg=Ydonor+fpa%26SORT%3DDZ
https://wellcomecollection.org/works/chm5t55w

## General updates to pass on to CI
- Outdated link to NLM for digitised material - Crick collection https://wellcomecollection.org/works/hz43r7re
- References to Codebreakers on Wellcome Library, example from Franklin collection https://wellcomecollection.org/works/hyjxver8

**Comment by pollecuttn** [comment]
**Donor searching**
JT confirmed 591 field, where donor info is (along with other info as it's a general note?) [is in the API](https://github.com/wellcomecollection/catalogue/blob/ae5e68248ccd36e2e958c55a41e48bd7986bd817/pipeline/transformer/transformer_sierra/src/main/scala/uk/ac/wellcome/platform/transformer/sierra/transformers/SierraNotes.scala#L17). Donor info is found in search but comes at the bottom of results as it's not boosted as much as other fields.

**Comment by jennpb** [comment]
@pollecuttn @jtweed As a general note it isn't structured, but it looks like `591 |r` is used specifically for Donors as [in this MARC record](https://catalogue.wellcomelibrary.org/search~S12?/Y%22Donor%3A+FPA%2C+formerly+the+Family+Planning+Association%22&searchscope=12&SORT=DZ/Y%22Donor%3A+FPA%2C+formerly+the+Family+Planning+Association%22&searchscope=12&SORT=DZ&extended=0&SUBKEY=%22Donor%3A+FPA%2C+formerly+the+Family+Planning+Association%22/1%2C655%2C655%2CB/marc&FF=Y%22Donor%3A+FPA%2C+formerly+the+Family+Planning+Association%22&searchscope=12&SORT=DZ&2%2C2%2C):
`591 00 |zCopy 1.|rDonor: FPA, formerly the Family Planning 
       Association. `

By structuring the data we'd be able to bring together all of the materials from that donor which has benefit when the materials aren't strictly Archive collections. Granted, it's probably of more use to staff - and it may be that not all donor information is treated equally from a public-facing point of view.

**Comment by pollecuttn** [comment]
Outdated link to NLM for digitised material - Crick collection
This has been updated to https://profiles.nlm.nih.gov/spotlight/sc
