### ISSUE TITLE
Archives prototype research iteration #3

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5482]
**We think that**

The exploded out heirarchy tree and the re-ordering of the works content pages in the third iteration of the archives works pages will improve the "findability" of archival material within Wellcome Collection.org

**Therefore we hypothesise that**
If we present the archival heirachy tree, novice users will find navigating the heriachy of an archive more intuitive

**As measured by**
- The number of users who succeed in the unmoderated tasks in the shorter amount of time
- A reduction in confusion when presented with the prototypes compared to the previous iteration cohort
- A successfull outcome will be shown with both novice users and archive users locating the information with similar ease

**We are right if**

Users find what they are looking for

- [ ] Create the unmoderated research test
- [ ] Set up validately and share session information with external participants
- [ ] Develop and define the testing tasks
- [ ] Test the tasks with internal team members
- [ ] Create a research script
- [ ] Circulate the validately information for observation
- [ ] Transcribe research sessions
- [ ] Analyse the research data

**Comment by jennpb** [comment]
@pollecuttn @alicerichmond Can this be closed now?
