### ISSUE TITLE
Wireframe for /collections section page

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5484]
# What is it and who's it for?
Collections researchers

The Collections section is the primary landing page on the site for research audiences. It brings together all of the content relating to our collections, the research library, and activities for researchers. It’s also a jumping-off point for searching the collections.

Currently, the Collections section is actually our catalogue search (/works). It features long text explaining the background/history of our collection. This information is no longer the right tone for Wellcome Collection.

**We need to:**
- Confirm search box for /works can be embedded in a Prismic page
- Modify page design/layouts as expressed in these mockups, taking into account user flow from /collections to /works (and other entry points to /works) [Mockups](https://wellcomecollection.invisionapp.com/freehand/Collections-page-xOukrH8LH) [Added note from JPB: we may be able to avoid this entirely; separate blank /works page not necessarily needed for the forseeable future]

Other docs:

[Sitemap](https://octopus.do/flzjefhed2h)

[Design sprint March 2020 ideas](https://wellcomecollection.invisionapp.com/overview/Collections-ck7omy2j40cen0143xu21mi14/screens)

[Current section page card layout](https://zpl.io/VKRj88E)

**Comment by jennpb** [comment]
Chatted with @DominiqueMarshall about this earlier. Now in progress.

**Comment by DominiqueMarshall** [comment]
@jennpb

Wireframes for the search journey from /Collections to /Works (I've also included what the filters could look like, but this needs more work/discussion)

Screens on Zeplin: 
https://zpl.io/2Ze7gr4
zpl://project?pid=5aab926b4b6efde01259e959&tags=Collections%20Search%20Journey

Clickable prototype on Invision: 
https://wellcomecollection.invisionapp.com/overview/Collections-Journey-Wireframe-ckfmfq12u0fc801937yq66o2u/screens
