### ISSUE TITLE
Cannot build common without including catalogue code

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5523]
The following pieces of ostensibly catalogue-specific code need to be included alongside common in order for common to build successfully. This shouldn't be necessary.

`/catalogue/services/catalogue/works`
`/catalogue/components/Download/Download`
`/catalogue/components/DownloadLink/DownloadLink`
`/catalogue/components/MultipleManifestList/MultipleManifestList`

**Comment by jennpb** [comment]
@davidpmccormick Do you know if this is still an issue?

**Comment by alexwlchan** [comment]
Pretty sure this is no longer an issue, so closing as done. If there are still build issues, let's open a new ticket.
