### ISSUE TITLE
Covid pages QA

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5533]
Changes to the hard-coded Covid pages:

- [x] https://wellcomecollection.org/covid-welcome-back#book-your-ticket
Use different button style. The primary button should only be used when we're triggering a primary action (e.g. if this button linked directly to the ticket booking service). Should we try this instead? 
Text should read `Book your ticket`

<img width="214" alt="Screenshot 2020-09-18 at 17 07 08" src="https://user-images.githubusercontent.com/1446139/93620140-7420a900-f9d1-11ea-80fd-59f11a9f415d.png">

**Comment by DominiqueMarshall** [comment]
Typography improvements on "[Book your ticket](https://wellcomecollection.org/covid-book-your-ticket)" page:


- [ ] Amend Eventbrite copy to be 16px (it's currently 20px). Should say "Tickets via Eventbrite" to have clearer context.

![Screen Shot 2020-09-21 at 10 31 19](https://user-images.githubusercontent.com/60890140/93752544-bbd44a00-fbf6-11ea-8a15-75d5cfa77e3c.png)

**Under the 'Library and museum visit' heading:**

- [ ] Increase spacing between the last summary bullet point, and the "Need to know for visiting the library" heading
- [ ] Decrease type size of the "Need to know for visiting the library" content to size 16px (currently 20px). This could help with the type hierarchy issues.

![Screen Shot 2020-09-21 at 10 41 48](https://user-images.githubusercontent.com/60890140/93752988-60ef2280-fbf7-11ea-9b81-aff257573580.png)


- [ ] Increase type size of the heading "Need to know about your ticket" to be 24px.
![Screen Shot 2020-09-21 at 10 32 36](https://user-images.githubusercontent.com/60890140/93753741-8c264180-fbf8-11ea-98b7-c12bac7df8b1.png)

**Comment by jennpb** [comment]
@davidpmccormick A few small details were missed here

1. The secondary CTA to link the user to the 'Booking your ticket' page should read `Book your ticket`(matches the page title)

2. I'm not sure what the logic is in the changes to the font sizes on this page https://wellcomecollection.org/covid-book-your-ticket. The 'need to know' info now looks squished in both the Library ticket section, and the final section on the page.

**Comment by DominiqueMarshall** [comment]
@jennpb The logic behind reducing the font size for the "Need to know about your library visit" section was to help create some visual hierarchy between the summary bullet points and the info beneath. It otherwise looked like one big block of text. 

The copy under "Need to know about your ticket" should be 20px to match the rest of the covid pages

**Comment by davidpmccormick** [comment]
> The copy under "Need to know about your ticket" should be 20px to match the rest of the covid pages

Ah, ok – I'll bump this back up.
