### ISSUE TITLE
Make Covid content pages editable in Prismic

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5552]
# What is it and who's it for?
Us and Editorial team

# User story
As a content editor
I expect pages to be available in the CMS
So that I can edit them when necessary.

# Pages

These pages are all hard-coded and should be converted to editable pages in Prismic:
- [ ] https://wellcomecollection.org/covid-book-your-ticket
- [ ] https://wellcomecollection.org/covid-welcome-back
- [x] ~Popup dialog https://cardigan.wellcomecollection.org/?path=/story/components--popupdialog~ tracked in new ticket #5628 

## Acceptance criteria
- [ ] New components can be added to Prismic pages (What's on this page; Info slices)
- [ ] Pages editable in Prismic
- [ ] Prismic pages redirected to human-readable URLs

**Comment by pollecuttn** [comment]
14 October 2020:

- Popup dialog first, before covid pages
- **Table of contents** automated, but optional to have on or off
