### ISSUE TITLE
Anchor links component

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5561]
# What is it and who's it for?
Editors who want to add navigational structure to a long page

The purpose of this component is to improve navigation of content on long pages. Some content needs better navigation for improved legibility, understanding of content:

- Accessibility https://wellcomecollection.org/pages/Wvm2uiAAAIYQ4FHP
- Visual story format https://wellcomecollection.org/pages/Xeo6OREAAB8A3wTA

The anchor link component lists all of the `h2`s on the page to allow users to jump to that anchor.

# Solution

- Currently in use on the Covid pages
- Will be used on other long content pages like Accessibility 

<img width="643" alt="Screenshot 2020-09-25 at 17 38 10" src="https://user-images.githubusercontent.com/1446139/94293451-2dddc380-ff56-11ea-8665-48be38c8b2a6.png">

To be used in cases where:
- There are more than 3 `h2`s on a content page
- Content page is long and contains discrete nuggets of information; where a user might only be interested in a specific part

Where not to use it:
- Articles
- Events
- Exhibitions

# Implementation 

- Need to mock up on pages with featured images; how does this look? 
- Agree component name with designers + devs + content team

## Acceptance criteria

 - [x] Component displays as intended
 - [x] Editors can add component to a Prismic page
 - [x] Component and usage rules documented in Cardigan

**Comment by davidpmccormick** [comment]
Would we expect `h3`s to appear in the list, inset after the relevant `h2` (as per 'Need to know about your library visit') on the [book your tickets page](https://wellcomecollection.org/covid-book-your-ticket#need-to-know-about-your-library-visit)?

**Comment by jennpb** [comment]
No, I don't think we need to account for `h3`s in general. I know we did with the ticketing information, but I think for all other use cases we should only use `h2` headings in the list.

**Comment by davidpmccormick** [comment]
I've started work on this in the [`anchor-links` branch](https://github.com/wellcomecollection/wellcomecollection.org/tree/anchor-links). It currently adds the `OnThisPageAnchors` component to _every_ page that has three or more h2s. Needs the addition of a Prismic boolean property (default to `false`) to allow editors to turn this on.
