### ISSUE TITLE
Button alignment issue on whats on this weekend or today.

### ISSUE THREAD

**Issue by ishouty** [wellcomecollection/wellcomecollection.org#5588]
**What**

Small cosmetic issue with button alignment issue on whats-on page where the spacing and button are close together. 

Viewed on : 

Chrome - browser
Iphone - chrome 
Android - chrome

**Where**

![Screenshot 2020-10-02 at 15 56 46](https://user-images.githubusercontent.com/9095365/94937757-eb713500-04c7-11eb-8481-ae011b1d3d0c.png)

![Screenshot 2020-10-02 at 15 55 24](https://user-images.githubusercontent.com/9095365/94937639-bfee4a80-04c7-11eb-9db4-dad9b74c2c81.png)

https://wellcomecollection.org/whats-on/today

https://wellcomecollection.org/whats-on/this-weekend

**Comment by davidpmccormick** [comment]
The `MoreLink` component didn't used to have this button styling until recently (it didn't have a border) so it didn't require any extra vertical space. I think converting [this div](https://github.com/wellcomecollection/wellcomecollection.org/blob/d647b2d9d2b2fd25a51d96e46e2979ae504a43ba/common/views/components/CardGrid/CardGrid.js#L105) to a `<Space />` styled-component to add a small amount of vertical space should deal with it.

**Comment by alexwlchan** [comment]
Closing as stale – we now separate out exhibitions and events on the What's On page, so the two buttons are always far apart.
