### ISSUE TITLE
Create tabs component

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5603]
Relates to wellcomecollection/platform#4642 

There's some new UI in the [search wireframes](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5f71e0527d9c854638b91841) that looks like tabs. We don't currently have a frontend component suitable for this so it'll need building.

It probably makes sense for it to be abstract enough to handle future instances where we want to use tabs, rather than being focused specifically on the search interface. That said, we might need to consider at what point we'd expect the results to update when clicking on each tab as part of this work (cc @DominiqueMarshall).

![image](https://user-images.githubusercontent.com/1394592/95365260-cdda0c00-08c9-11eb-9833-c3c0336389b4.png)

**Comment by DominiqueMarshall** [comment]
@davidpmccormick I would expect the results to update when you've clicked the tab, similar to how the radio buttons on our search works now. The tabs are basically just a different visual styling to the radio buttons.
