### ISSUE TITLE
Prepare research for the search bar user journey

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5611]
**We think that**

The search and filtering process currently doesnt work for our users, if we change the UX of the search functionality then it will improve the success of users identifying works pages that they are looking for

**Therefore we hypothesise that**
By altering the arrangement and proximity of the components of the search bar and filters it will improve the time it takes for researchers of all backgrounds to find works pages that are relevant to them. 

**As measured by**
Agreement for the measure and process behind the research needs to be confirmed by the team
Accessibility testers need to be identified to help observe any issues when using our site

**We are right if**

If users from all levels of experience and tecnological proficiency can use our search functionality to find items of interest

**Comment by alicerichmond** [comment]
Creation of user empathy maps, areas of opportunity and user journeys here https://miro.com/app/board/o9J_khZNYIw=/

**Comment by pollecuttn** [comment]
11 November

### Images search
- People are missing the Images tab
- Image search filter by colour: some found the choice a bit overwhelming
- Image search filter by colour: some wanted to find a specific hex value/type in a specific value
- No 'no results' messaging
- Nothing to tell you there are relevant results in catalogue tab

Future tbd:
- [ ] Map out user journey for image search/results (UR)
- [ ] Add contributor to image modal

**Comment by pollecuttn** [comment]
@alicerichmond Should this issue also be closed now?
