### ISSUE TITLE
Reduce API requests from the ArchiveTree

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#5616]
## The problem
- The ArchiveTree component is putting too much strain on the catalogue API.
- This is due to the fact that there is no way of telling from the API response if the children of a work have their own children or not.
- So, in order to display the appropriate navigation controls, we are having to make requests to all the children of a work when constructing the tree interface.
- For example, when landing on the Francis Crick archive, knowing whether to show the expansion control for Personal Material etc.
![tree](https://user-images.githubusercontent.com/6051896/95756907-54ae3080-0c9e-11eb-81d6-56be41acc2d0.png)
- The long term solution to this is the addition of the totalParts data to the API, which @warrd is carrying out, and means these additional API calls will not be required.
- However, in the mean time, we will need to make a compromise in the UI to protect the catalogue API.

## The proposed interim solution
- [ ]  Place expansion controls on each tree node, without knowing whether they are needed or not. 
- [ ]  Make a request for the children to populate tree, only when the expansion control is clicked.
- [ ] Expand the tree with the children, if there are some, else remove the control

**Comment by kenoir** [comment]
Link to ticket indicating the longer term solution: https://github.com/wellcomecollection/platform/issues/4673

**Comment by kenoir** [comment]
Resolves: https://github.com/wellcomecollection/wellcomecollection.org/issues/5616
