### ISSUE TITLE
Make User Panel page editable in Prismic

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5631]
# What is it and who's it for?
Us and Editorial team

This page is hard-coded and should be converted to an editable page in Prismic:
https://wellcomecollection.org/user-panel

# User story
As a content editor
I expect pages to be available in the CMS
So that I can edit them when necessary.

# Implementation 

## Acceptance criteria
- Page editable in Prismic
- Prismic page redirected to human-readable URL (`/user-panel`)

**Comment by davidpmccormick** [comment]
The two things that currently prevent this from being controlled by Prismic are 1. the different header background and 2. the button (link to airtalbe) in the body copy. To what extent are either required?
