### ISSUE TITLE
OnThisPageAnchors should render below standfirst

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5656]
When toggled on, the [`OnThisPageAnchors` component](https://cardigan.wellcomecollection.org/?path=/story/components--onthispageanchors) currently renders before the standfirst in the body. It should come after.

![image](https://user-images.githubusercontent.com/1394592/96919949-711f4980-14a4-11eb-83cc-d9d4c5f7a7a1.png)

**Comment by jennpb** [comment]
For @GarethOrmerod to review
