### ISSUE TITLE
Prototype/Wireframe development for "open with advisory"

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5670]
# What is it and who's it for?
Experienced and new users browsing through the Wellcome collection who could come across content that is disturbing or explcit

# Implementation

* Modal window advisory that shows when opening the digitised content on a works page
* The advisory window will show before the viewer renders the digital content
* The modal window to close and show the digitised content when the user interacts with a "show contents" call to action
* Should the user choose not to show the content, then the back button will take them to the works page
* The contents of the modal window should advise that a cookie will be set and this will disable the advisory for the duration of their session 

## Testing and tracking
* Set up testing to monitor the usage and bouce rate from the CTA in the modal window
* Qualitative content research does language impact things
* Qual testing for content clarity

## Measurement
- Numbers of users that see the advisory as a blocker to using content

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
Initial designs for the modal window on the viewer (desktop and mobile): https://zpl.io/VxEkoAx

Content TBC - needs the cookie advisory added.
