### ISSUE TITLE
Monthly stats report

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5719]
A monthly report on the impact and reach of wellcomecollection.org is to be published on Trustnet but first I need to get a better idea of who the intended audience is and what we think they are interested in.

Here is the link to the draft specifications document for discussion purposes:
https://docs.google.com/document/d/1GM7lAfqX3P6ITwYahGaBZCH2XyIXfnZAQQawlrb4VxA/edit

This has been drafted with @jennpb but will be shared with wider team for comments.

**Comment by kenoir** [comment]
Can we get a link to the Trustnet article?
