### ISSUE TITLE
Help Commercial team get new Shopify shopfront set up

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5735]
# What is it and who's it for?
- Wellcome Collection's commercial team are setting up a Shopify shop to sell gifts, books and more (wellcome-collection-shop.myshopify.com)

They want to use the subdomain `shop.wellcomecollection.org` instead. Jenn has the Shopify IP and CNAME info in email.

Commercial team want to get this set up as soon as possible to take advantage of pre-xmas shops.

**Comment by kenoir** [comment]
The domain changes have been made and have been put in code at: https://github.com/wellcomecollection/shop.wellcomecollection.org
