### ISSUE TITLE
Indicate that a search result is available online

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5741]
The `WorkCard`s that display on `/works?query={term}` don't provide any indication of whether or not an item is available online. We should add this.

**Comment by DominiqueMarshall** [comment]
Previous search result card wireframe has the "Available Online" label visible: https://zpl.io/bJyv8K6

Needs input from @GarethOrmerod about colour labelling; would we want to use one colour for online items and another colour for physical (in library) items?
