### ISSUE TITLE
Display the contributor(s) within the image search modal

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5742]
The image search modal displays the title of the work, but not the contributors currently. We should add this similarly to how it displays on the individual work page.

__modal__
![image](https://user-images.githubusercontent.com/1394592/98848403-93740980-2449-11eb-8867-c9a8c6323c1b.png)

__work page__
![image](https://user-images.githubusercontent.com/1394592/98848548-cc13e300-2449-11eb-9ede-0ca2c994acb4.png)

**Comment by DominiqueMarshall** [comment]
Example of the Contributor name being shown on the modal: https://zpl.io/2vxo8Br
