### ISSUE TITLE
Improve colour filter UX

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#5744]
User testing indicated the colour filter on the `/images` route could be friendlier to use.

![image](https://user-images.githubusercontent.com/1394592/98849445-219cbf80-244b-11eb-8f4c-9f28f833608f.png)

**Comment by DominiqueMarshall** [comment]
A potentially more straightforward colour picker (but will need testing to confirm if it is indeed more user friendly): https://zpl.io/V48dnYJ

This structure gives users the option to choose a standard colour swatch, or use the colour slider if they're wanting a more granular choice.
