### ISSUE TITLE
Include archive context on search results

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#5752]
Archive search results need to include a couple of extra bits of information in order to make sense in isolation.

We should:

- Add a format icon to archives and manuscripts results
- Add the reference number and collection underneath the contributor/date line

Like this:

Reference: {ref number}
Part of: {collection name}

To keep the results more compact, include only the highest level in partOf, not intermediate levels.

**Comment by jamieparkinson** [comment]
Some things to resolve re this ticket...

The design has 3 pieces of additional context:
![image](https://user-images.githubusercontent.com/4429247/101809910-0c7d8400-3b10-11eb-85b0-50abf57859c8.png)
Where "part of" refers to the direct parent and "found in" refers to the root ancestor - I think this is a bit fiddly to do so do we want to stick with the `part of` defined above in this ticket?

Additionally we don't currently `include` any of this archive context in the search results and possibly don't want to. We have some options, none of which seem ideal:

- Include `partOf` and take the perf hit of flattening all the ancestors into `partOf` in the API as well as returning all the extra data.
- Do something like we did with `availableOnline` and add a new field to the API called something along the lines of `rootTitle`, where that value is derived at index time
- Derive the whole `DisplayWork` for `partOf` (!!!) at index time and store that in the index
- See if there's some intermediate representation we can derive at index time and convert very easily into a `DisplayWork` (not sure if this is possible)

**Comment by jamieparkinson** [comment]
fao @jtweed

**Comment by jamieparkinson** [comment]
I'm in 2 minds about this because whilst I think it's sound, we didn't apply that reasoning to `availableOnline`... Does this problem not apply here too? https://github.com/wellcomecollection/catalogue/pull/1056#discussion_r524151251

**Comment by warrd** [comment]
The comment you have linked to is to specifically to do with includes and dynamically whitelisting fields in the ES response, and we can still do this for `partOf` with derivation in the API: when `include?=partOf` is present we ask for `ancestors` to be included in the response, and then derive `partOf` from the returned data. So I think the reasoning with `availableOnline` being derived makes sense: in that case we need to derive it for it to be dynamically whitelisted, although it is just a boolean so slightly unsure why I originally made an issue of it :shrug: 

I agree we could go further with "derived" data, such as even deriving the whole display model.

**Comment by jtweed** [comment]
> Where "part of" refers to the direct parent and "found in" refers to the root ancestor - I think this is a bit fiddly to do so do we want to stick with the part of defined above in this ticket?

Let's stick to part of as defined in this ticket. Top level ancestor within partOf only, no intermediate ancestors. There are too many levels within archives to sensibly display within the current search result card.

**Comment by jtweed** [comment]
I'm also with @warrd that I don't think it should be an issue to include the partOf data on search results. At least, I think we should certainly implement like that behind a toggle and measure it, rather than assume it will be an issue.

The difference between this and online availability, is that that would require serialising out many items, each with multiple locations and then parsing that to find a digital location, which might not even be there.

Using the partOf include will also only increase the load for archive search results, not all of them. So I think it's worth trying that way first, then seeing if we need to optimise further.

**Comment by jamieparkinson** [comment]
> Let's stick to part of as defined in this ticket

Too late I'm afraid - I went with how it is in the designs, which would be my preference regardless.

I didn't do it behind a toggle but will make that change now.

**Comment by jtweed** [comment]
Not to late at all @jamieparkinson - there are good reasons for not doing it as it is in the wireframes, which were not considered when the wireframes were created.
