### ISSUE TITLE
Season landing page

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5755]
# What is it and who's it for?

A single point of access for all aggregated content relating to a `season`, so that:
- users can identify and access all of the content relating to a promoted campaign or theme
- marketing and social have a single place to direct people to read/view this content

# Problems to solve
- Promoting 'What does it mean to be human, now?' programme (and reusable/iterate-able for future themes)
- Providing a cohesive presentation of a theme
- Offering a jumping-off point to all of the content related to the theme
- Understanding what the incoming content is and how it will be added to over time

# How we'll do it
~~- Work out whether existing landing page template is suitable by mocking up all possible content as cards with Title, Blurb, Image and any other relevant detail related to content type~~
~~- Decide what additional content blocks need to be enabled (e.g. body text, contributors, standfirst etc)~~

Questions to answer:
- How do we want to handle the expected amount of content links?
- Do we want to include hashtag? - NO sez @dannybirchall 
- How is the list page constructed in Prismic? Is it filterable by type of content? Sort order? How do we create content hierarchy?

# Implementation 

## Acceptance criteria
- Defined as a content type in Prismic
- All agreed content slices available to content type

## What does success look like?
- Programme/landing page and things linked from it are being visited/links are being used
- Success of the promotion of the season: Page views to the season with referrer to tell which channels are working
- Success of the programme promoting pieces of content: Page views to content within that season from season page and other yet to be discussed mechanism e.g. part of on those pages

## Testing and tracking
- Tracking number of users getting to the landing page and where they came from
- Qual testing to find out whether users can understand at a glance the breadth of content, what it is, and what they can do with it.

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

**Comment by jennpb** [comment]
18/11/20:
- Agreed that the existing `landing page` template isn't quite right for handling a growing list of content of multiple types
- @jennpb and @jamesgorrie agreed that the `landing page` isn't the right way to construct the page; instead of adding links to a landing page, we need to be able to add the season to the content pages instead, to enable better linking of content as part of the season, and to enable browsing.
- Need to design for standfirst, body copy and other parts to distinguish a season as a multi-faceted content package.

Next steps:
- Sketch session
- @jamesgorrie and @gestchild to start building model in Prismic

**Comment by jennpb** [comment]
25/11/20:
Now that we have a skeleton Season page ready to use, the next task is to look at 
- card sizing and layout
- possible 'At Wellcome Collection' group and 'At home' grouping, based on whether content is being held in venue or online
- any visual treatment that differentiates it from other types of content pages? Worth connecting with Lindsey P and Ben G for design and/or photographic approaches
@DominiqueMarshall @GarethOrmerod @dannybirchall

**Comment by pollecuttn** [comment]
30 November 2020:

Events
Order by nearest to come

Explore more
Order by most recently published
Catch up events sorted into Explore more

**Comment by jennpb** [comment]
2/12/20 Next steps

Our deadline for this work is 8 December, when the content team need to be able to publish this and make it available from the homepage.

- [ ] Agree which approach is best for the content https://wellcome.slack.com/archives/C294K7D5M/p1606845356188700
- [ ] Firm up design changes including mobile @GarethOrmerod 
- [ ] Implement design

**Comment by pollecuttn** [comment]
2/12/20

- Decided to use Season ideas 2; needs dates for season e.g. November 2020 - March 2021

**Comment by GarethOrmerod** [comment]
Further Season Page ideas based on the chosen [ideas 2]  (https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5fc657f94cffce9a42dc43a3)
https://zpl.io/bz4l0K4
zpl://project?pid=5aab926b4b6efde01259e959&tags=Seasons%20-%20Ideas

**Comment by jennpb** [comment]
Visual design:
Decision to use charcoal + orange for Seasons 

Season page:
zpl://screen?pid=5aab926b4b6efde01259e959&sid=5fc900d1730a385567e0db1c 

Season promo:
zpl://screen?pid=5aab926b4b6efde01259e959&sid=5fc91c085bcf324e9474b084

@gestchild @GarethOrmerod ok to build now!
