### ISSUE TITLE
Promote recorded events on What's On

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5767]
# What is it and who's it for?
People who missed out on attending an in-person or livestreamed event can catch up on the most recent past events

# User story
Given that I wasn't able to attend an event
I want to see what's available online to watch 
So that I can watch what I missed

# Implementation 
- Most recent recorded events promoted from What's On

## Acceptance criteria
- New slice added below Events for recorded events - section header should be `Catch up`
- Recorded events display reverse chronological of the date the original event occurred

## Testing and tracking
- [ ] Setting up additional tracking and monitoring - talk to Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

**Comment by jennpb** [comment]
3 December 2020

Order of What's on:

Exhibitions, Events, catch up events
Catch up events on What's On

catch up events will be a new slice
what do Editorial want to call this section?
order of those past events: reverse chronological of date of original event

**Comment by jennpb** [comment]
Danny wants to use `Catch up` for the section header

**Comment by jamesgorrie** [comment]
@jennpb couple of questions:
* Do we want these segmented by date as we do events?
* If not how many do we want in the list?

**Comment by jennpb** [comment]
> Do we want these segmented by date as we do events?
No, just newest to oldest order

> If not how many do we want in the list?
Max of 6, link to `/events/past` to find additional

**Comment by jamesgorrie** [comment]
This is behind a toggle on the site. Awaiting further instruction.

**Comment by jennpb** [comment]
@jamesgorrie Is the further instruction you're awaiting the question about what to do when there are no catch-up events? Or is there something additional you're waiting for?

**Comment by jamesgorrie** [comment]
@jennpb what I was looking for was the messaging when there are no events, which is currently "There are no upcoming catch up events". There is an event now - so we are going to remove the toggle and make this live.

**Comment by jennpb** [comment]
Super - from now on we'll always have catch up events 🥳
