### ISSUE TITLE
Filtering, sorting and promoting content on What's On and Stories

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5769]
# What is it and who's it for?

All website users - ability to see breadth of content available to them
Us - a more consistent approach to how list pages are organized, sorted and presented.

# Problems to solve
What's On and Stories list pages both regularly refresh their content - new editorial, exhibitions, events, etc are published frequently. 

We also have the desire to promote certain content on these pages - for example, a recent serial, a podcast series, catch up video, etc. 

Currently:
**What's on**
- Current + upcoming exhibitions
- Month-by-month list of upcoming events
- Promoted facilities
- Filter: `Today`, `This Weekend`, `Everything`

The problem with this configuration is that it doesn't deal well with too few or too many upcoming events, it doesn't allow users to target their specific interests.

**Stories**
- Reverse chronological most recent 5 articles
- Promoted 6-part serial
- Books slice with 3 books [this needs to be automated so it shows 3 most recent - see #4960]
- You may have missed - next 6 most recent articles, reverse chron
- No filtering

The problem with this configuration is that it doesn't reflect the breadth of content available (stories of all formats, podcasts, books, comics, and potentially, digital commissions like 'Care Packages' and the possible video series from the VE team). Content drops off the Stories page quickly, and it's harder to explore the archive of stories without alternative ways in. 

## Considerations
- Is there a way we can simplify the logic of these lists so it's more maintainable?
- How much of these list pages need to be dynamically generated as opposed to manual? 
- What kind of manual editorial control is needed?

# Implementation 

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by pollecuttn** [comment]
30 November 2020:

### Events
Order by nearest

### Explore more
Order by most recently published

**Comment by pollecuttn** [comment]
3 December 2020

Catch up events on What's On
- what do Editoral want to call this section?
- order of those past events: reverse chronological of date of original event
