### ISSUE TITLE
Podcast content model

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5792]
# What is it and who's it for?
- Modelling the new Podcast content type so Editors can build Podcast pages and so users can listen and subscribe

This should be modelled as a `series`
- page per Podcast **series**
- individual **episodes** on series page 

![IMG_2997](https://user-images.githubusercontent.com/1446139/101071995-3b867980-3595-11eb-887b-cbd92197df01.jpg)

Users can:
- listen to episodes on the site
- subscribe to podcast series from platforms of their choice

Notion doc: https://www.notion.so/wellcometrust/Podcasts-content-model-design-Q1-2020-21-c22c928343834d5ab34484dc6deb734e

@jamesgorrie is it better to have this as a new `Podcast series` type in Prismic, or should we abstract out all series as a series, and then have series formats of `events` `stories` `podcasts`?

**Comment by pollecuttn** [comment]
5 Jan 2021:
- each episode should appear in most recent section on /stories
- For all I care podcast can be delisted so it doesn't appear on /stories

**Comment by jennpb** [comment]
Per discussion with @jamesgorrie @dannybirchall @gestchild, we've agreed to retain this model:
A `series` is an editorial grouping
A `series` contains `articles` of `{type}`
Therefore, podcasts are `series` where the episodes are `articles` and `podcast` type is applied to all.

The `type` determines page layout and component availability.

**Comment by jennpb** [comment]
Hey @gestchild is this ready to close?

**Comment by gestchild** [comment]
#5976 #5977
