### ISSUE TITLE
Add pageview events to catalogue

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#5808]
It should include the following fields to allow for analysis:

## position
If selected from the results list, where in the results list was it 

## source
We have multiple ways for a person to get to a works page:
* search results
* archive tree
* image modal

## metadata
* `id`
* `workType`
* `identifiers`
* `subjects`

# shape of event
An event would look as follows:
```
{
  "@timestamp": "2020-12-06T11:04:05.000Z",
  "event": "pageview",
  "url": "/works/abc345t",
  "data": {
    "position": 3,
    "source": "works_search_results",
    "id": "abc345t",
    "workType": "a",
    "identifiers": ["sierra-system-number/b24367588", "sierra-identifier/2436758", "miro-image-number/V0042826ER"],
    "subjects": []
  }
}
```

Questions:
- [ ] What should the values in subjects be?
- [ ] Do we want any other metadata?
- [ ] Do we need anything else to start answering the question around breadth of content accessed?

**Comment by harrisonpim** [comment]
> What should the values in subjects be?

I don't think we even need subjects tbh - if we have the work ID we can figure this stuff out afterwards, and the subjects aren't related to any of our everyday questions

> Do we want any other metadata?

No other requests from me at this point

> Do we need anything else to start answering the question around breadth of content accessed?

Nop

**Comment by harrisonpim** [comment]
Just checking my understanding is up to date: These events are going to be shoved into a new index alongside all of the old search relevance data, which we'll also continue to collect, right?

**Comment by jamesgorrie** [comment]
> Just checking my understanding is up to date: These events are going to be shoved into a new index alongside all of the old search relevance data, which we'll also continue to collect, right?

We will continue to collect the search relevance stuff in the old index.

I'll need to reimplement the page tracking on the works / images search as well which will be stored against this data. I would prefer to not track the old relevance data in here.
