### ISSUE TITLE
Assessing the need for journal search

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5817]
**We want users to be able to**
Find journals

**but we hypothesise this is happening**
They don't know how to find them.

**We are right if we measure**
Search text

**and get this result**
Search text contains journal, article or paper.

**Comment by taceybadgerbrook** [comment]
@alicerichmond Of the 2,893,978 searches conducted during the period 24/1/20 - 24/11/20, only 1,704 of them (0.06%) contained the following terms:

- journal
- papers
- report

Of these searches, 1052 were duplicate searches generated by "paging through" results. On the basis of 652 unique journal-related queries, this does not appear to represent a pressing user need.

**Comment by jennpb** [comment]
@taceybadgerbrook @alicerichmond Just out of curiosity, was there any evidence that people might be trying to search for specific article titles? This is a common researcher behaviour (citation chaining) where they copy-paste part of an article title they're trying to find, for example `The role of host defences in Covid 19 and treatments thereof`

I would expect if this were the case there'd be evidence of longer search strings and/or combos with author names and or specific journal names (which would not necessarily have the words `journal` `report` in them.

**Comment by taceybadgerbrook** [comment]
During period 25/6/20 - 25/11/20, there were 6,391 searches with 5 words or more captured in Elasticsearch, of which 3,318 were searches typed in directly by users with quotation marks (ie. not the result of Google searches, clicks on works pages links or duplicate searches produced by paging through results.) The length of the queries and use of quotation marks suggests these are titles of journal articles.

**Comment by taceybadgerbrook** [comment]
During the same period, wellcomelibrary.org reports via GA 4,871 journal searches.

**Comment by taceybadgerbrook** [comment]
@alicerichmond To view the types of queries being entered into wellcomelibrary.org journal search, here are all queries for the 5-month period 24/6/20-24/11/20.  There were 3,930 unique queries entered by a total of 1,819 users during this period. The spreadsheet has the queries containing, "dig" as well.  There were 73 such queries.
https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Q1%20202021/5817%20Assessing%20need%20for%20journal%20search_Page%201_Table.xlsx?d=we60fafd8eaf7476f8baaabdb03c8b736&csf=1&web=1&e=REahAP

**Comment by jennpb** [comment]
@taceybadgerbrook I think this is done for now, so I'm going to go ahead and close it. You can always reopen if you want to add more.
