### ISSUE TITLE
Virtual events model

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#5821]
## Glossary:
* `virtual` - using this to mean that something happens on the internet, and you need to be at a computer to experience it. This only refers to the timeframe of the actual event i.e. `startTime` => `endTime`. I am avoiding using `online` for now as that is overloaded by the fact that we might have other things available online e.g. podcasts, stories, videos etc
* `place` - could also be called a `location`. This is what we call it in Prismic, and I am trying to iterate as opposed to create new things. This can relate to things that are `virtual` or not.
* `available online` - Has a video / audio / something you can consume online at any stage

It feels important to make sure we don't conflate `available online` and `happens online`, albeit it's similar language.

### 1. Making the event `virtual`

We could attach the property to the event that it is virtual. This would be a boolean value.

__JSON__
```jsonc
// Virtual without recording
[
  {
    "id": "1",
    "title": "Virtual event",
    "isVirtual": true,
    "place": {
      "title": "Youtube live"
    }
  },

  // Virtual with recording
  {
    "id": "2",
    "title": "Virtual event with recording",
    "isVirtual": true,
    "place": {
      "title": "Youtube live"
    },
    "media": [
      {
        "title": "Youtube live recording",
        "url": "https://youtube.com/blarp"
      }
    ]
  },

  // In venue without recording
  {
    "id": "3",
    "title": "Event",
    "isVirtual": false,
    "place": {
      "title": "Wellcome Collection"
    }
  },

  // In venue with recording
  {
    "id": "4",
    "title": "Event with recording",
    "isVirtual": false,
    "place": {
      "title": "Wellcome Collection"
    },
    "media": [
      {
        "title": "Youtube recording",
        "url": "https://youtube.com/blarp"
      }
    ]
  }
]
```

__Filters__
| query | returns |
|-------|--------|
| `/events?isVirtual=true` | `[1,2]` |
| `/events?availableOnline=true` | `[2,4]` |
| `/events?availableOnline=true&isVirtual=true` | `[2]` |

### 2. Making the place `virtual`
Pretty much identical to the above, except you would have:
```jsonc
{
// ...
  "place": {
    "title": "Youtube live",
    "isVirtual": true
  }
}
```

And the filter would be `/events?place.isVirtual=true`

This only feels useful if we want to be creating virtual places, and don't want create a blanket place called "online". If we were going to do that latter, I would stick with it being a property on the event.

---

No 1. is definitely simpler and, _I think_, gives us everything we need. If we wanted to create specific virtual places though, No 2. would be the way to go.

**Comment by jennpb** [comment]
@jamesgorrie This makes sense to me. I think you're right that **option 1 is best.** 

But just to clarify:
Would option 2 imply that we would intend to build a filter for a virtual place, e.g. show me all events that happen on YouTube live?
If that's the benefit it would give us, it doesn't seem a necessary one. I can't think off the top of my head of having a virtual place unless we were conducting hundreds of events a month.

**Comment by jamesgorrie** [comment]
>  Would option 2 imply that we would intend to build a filter for a virtual place, e.g. show me all events that happen on YouTube live?

The benefit would be you could do:
```
Gets us events with virtual places
/events?places.isVirtual=true

// gets us events on youtube
/events?places.id=youtube
```

But that granularity doesn't seem useful, and would mean that we need to create places that are virtual. 

Double agreeing, what we are asking if for events that are virtual.

**Comment by jamesgorrie** [comment]
This was finished in #5822
