### ISSUE TITLE
Showing that content is part of a season

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5823]
# What is it and who's it for?
Site visitors who access any part of a Season's content should be offered a way to browse to more content from that Season

# Problems/Questions
- If content in the `season` is also part of a `event-series` or article `series` or `serial`, which relationship is primary?
- What are the onward journeys from a content page to more content in the `season`? 
- Do we want to connect to the season itself, or a selection of content pages within?

# Implementation 

Focus on promo design

Not in scope: `PartOf`

## Acceptance criteria

TBC

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by pollecuttn** [comment]
2 December 2020

Promo design (banner) and relationship of promo to the content
