### ISSUE TITLE
Update explanatory text on search form

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#5831]
Updated text for the search form, to help clarify the coverage of catalogue search and image search.

Catalogue:
- Find thousands of books, manuscripts, visual materials and unpublished archives from our collections, many of them with free online access.

Images:
- Search for free, downloadable images taken from our library and museum collections, including paintings, illustrations, photos and more.

**Comment by DominiqueMarshall** [comment]
@jtweed I'm happy to go with these text updates
