### ISSUE TITLE
Visual refinements to available online label

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#5832]
As part of the new search interface, an available online label has been added to search results that are, er, available online. This is great, but I think it could benefit from a tiny bit of visual refinement.

Example search with some, but not all, available online:

https://wellcomecollection.org/works?query=letters&workType=k

And filtered to only available online:

https://wellcomecollection.org/works?query=letters&workType=k&items.locations.type=DigitalLocation

As is stands currently, the label is the same size as the more important text that it sits beside. It's also on a grey background, which was intended only for the wireframe.

My suggestion is to change the size to `font-size-6` (ie `14px`) and change the background to `cream`.

This is still slightly different from the wireframes, but without making the text even smaller (as it is in the wireframes), the suggested all caps is a bit overbearing and I don't want to push to add a smaller text size to Cardigan right now.

@GarethOrmerod / @DominiqueMarshall to confirm.

**Comment by jennpb** [comment]
@jtweed We're doing some work on `online` labels for events as well and would like to make sure these are somewhat joined up in design. @GarethOrmerod is working on it.

**Comment by jtweed** [comment]
Makes total sense, thanks @jennpb

**Comment by jamesgorrie** [comment]
Just to add my thoughts that i have added to slack. With events we have two different `online` concepts.

1. __Happening online__ - this is an event that you have to be online to partake in between the times that are specified. After that the event is no longer online
1. __Available online__ - this is an event that has been recorded in some way to make it available online in perpetuity. This could be an event similar to `1.` or an event that was recorded in a physical space

Assuming the visual treatments might be different, and the two that should be in sync is "available online"?

**Comment by jtweed** [comment]
Certainly similar - the search page visual treatment I can see being a little more subdued as it’s potentially repeated so many times on the page and it’s secondary info to other fairly subdued content. Will wait and see what it looks it and what @GarethOrmerod and @jennpb reckon.

**Comment by jamesgorrie** [comment]
Are we happy with what we have?
<img width="759" alt="Screenshot 2021-01-13 at 15 46 41" src="https://user-images.githubusercontent.com/31692/104475087-9a88d680-55b6-11eb-8af3-ee795c8c5ecb.png">

**Comment by DominiqueMarshall** [comment]
@jamesgorrie This needs refining still according to the UI work that @GarethOrmerod has been doing on labels
