### ISSUE TITLE
'Project' content model

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5838]
# What is it and who's it for?
Modelling the new Project content type so Editors can build Projects 

**Project Model** https://www.notion.so/wellcometrust/Projects-content-model-design-Q1-2020-21-6e553c4298be41eba3af1761ce7e2727

# Implementation
- set up new `/projects/` path
- replicate `page` content type in Primsic so a project retains all content functionality of a generic `page`
- set up `Project format` type in Prismic (this will be used to label the project format, e.g. Art commission, Youth project, etc)
- work with content team to iterate on model

Other considerations
- Editorial team to identify all `pages` that need to be mapped to `projects` 
- Remap and redirect legacy content to new `/projects/` page

**Comment by pollecuttn** [comment]
5 Jan 2021:

- Danny to get project content in
