### ISSUE TITLE
Understanding Elasticsearch conversion* index

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5850]
Before I can contribute conversion metrics to a dashboard, I need to work through the index's ontology and check that I can identify the requisite events.

@jamesgorrie @harrisonpim Any amendments/improvements to the ontology will be put through Github.

**Comment by taceybadgerbrook** [comment]
@jamesgorrie I don't see the equivalent of the term event. Is it because this index consists only of data following from event = searchResultSelected?

The third column has my best guesses at terms and parameters for measuring conversion.

![image](https://user-images.githubusercontent.com/32418070/101371213-66791200-38a2-11eb-9c1e-1a34341dda2e.png)

**Comment by taceybadgerbrook** [comment]
I found some exceptions to the definitions we discussed last week so took up Jenn's suggestion and used my anonymousId to track my own activity (found my id using the js console for the site) to produce definitions I am using in the conversion dashboard. 

@jamesgorrie if you could review these definitions and let me know if you see any errors, would be much appreciated:

### Users searches:
page.name: works
page.query.query: *
properties.totalResults: *

### Viewing works page:
page.name: work
page.query.id: *

### Clicking on view:
page.name: item
page.query.workId: *

**Comment by taceybadgerbrook** [comment]
Searches by users who find wc.org via search engines are not being captured, inflating view/search metric. I would like to add works page views where source: unknown as proxy for the missing searches. I can't sum counts in visualisations. According to this article, this requires the creation of a scripted field:
https://discuss.elastic.co/t/filter-ratio-in-tsvb/244842

**Comment by taceybadgerbrook** [comment]
Viewing works triggers more than one page view. Rather than use an inflated metric, I would like to using cardinality by workId but page.query.id is not among options available.

**Comment by taceybadgerbrook** [comment]
Conversion dashboard link:
https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/88c2ee40-3b9e-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-5M,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Conversion%20dashboard',viewMode:view)

**Comment by taceybadgerbrook** [comment]
**Definition of search:**
(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*

**Definition of works page view:**
page.name:work 
and
page.query.id:*

**Definition of actual work clicked to view:**
page.name:item - bug producing duplicates needs fixing 
source: _tba_

waiting on https://github.com/wellcomecollection/wellcomecollection.org/issues/5938

**Comment by taceybadgerbrook** [comment]
**Definition of works page selected from archive tree:**
page.name:work
and
page.query.id:*
and
source:archive_tree

_Note that when archives are selected from search results source becomes works_search_result._

**Comment by jamesgorrie** [comment]
@taceybadgerbrook do you want to store any of these in the repo? I do wonder if we could provision the graphs via the API if we did.

**Comment by taceybadgerbrook** [comment]
Updated definitions here. @jamesgorrie can you check that I have these correct? I don't want to count users paging through results or using the viewer to page through a work

**Definition of search:**
(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*
and 
(page.query.page:1 OR NOT page.query.page:*)

**Definition of works page view:**
page.name:work
and
page.query.id:*

**Definition of actual work clicked to view:**
page.name:item 
and
source:NOT viewer/paginator

**Comment by taceybadgerbrook** [comment]
Basic conversion dashboard now finished!
https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/88c2ee40-3b9e-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-5M,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Conversion%20dashboard',viewMode:view)

**Comment by taceybadgerbrook** [comment]
Correction:

**Definition of actual work clicked to view:**
page.name:item
and
source:NOT viewer\/paginator
and 
(page.query.canvas.number:1 or NOT page.query.canvas.number:*)

**Comment by taceybadgerbrook** [comment]
Updated definitions here. 

**Definition of search** 
(counts paging through results served as only 1 search submitted):

(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*
and
(page.query.page:1 OR NOT page.query.page:*)

**Definition of works page view:**
page.name:work
and
page.query.id:*

**Definition of actual work clicked to view** 
(so that does not capture views generated by paging through work. Note that stats for period before source:viewer\/paginator was created 13/1/21 will include when users page back to page 1 - surprisingly common!)

(page.name:item or page.name:image)
and
(page.query.canvas.number:1 or NOT page.query.canvas.number:*)
and
NOT (source:viewer/paginator)

**Comment by taceybadgerbrook** [comment]
https://excalidraw.com/

**Comment by taceybadgerbrook** [comment]
![image](https://user-images.githubusercontent.com/32418070/106271440-715b7d80-6227-11eb-851e-0122b5be173d.png)

**Comment by taceybadgerbrook** [comment]
**Definition of actual work clicked to view**

Users are automatically taken to page 1 when View clicked but Elasticsearch is not capturing this as page.query.canvas.number:1. This field does not start to populate until the user scrolls to a subsequent page. 

Excluding source:viewer/paginator means removing views of users who use bookmarks to access pages.

Amended definition now counts those users who view page 1 as well as those accessing by bookmarks. Dashboard compilations will be changed to cardinality by page.query.workId.keyword and changes recorded here.

(page.name:item or page.name:image)
~~and
(page.query.canvas.number:1 or NOT page.query.canvas.number:*)
and
NOT (source:viewer/paginator)~~

**Comment by taceybadgerbrook** [comment]
**Definition of search**

Users who select successive filters generate a search each time. To remove these from the dashboard counts, aggregation needs to be changed from Count to Cardinality by page.query.query.keyword.

The problem is that the metric is used with filter ratios in the conversion dashboard. Filter ratios only allow cardinality for a field common to both numerator and denominator. 

@jamesgorrie Is it possible to use KQL to specify cardinality in the denominator only?

**Comment by taceybadgerbrook** [comment]
Cardinality can be specified as follows:

(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*
and 
cardinality by page.query.query.keyword

**Comment by taceybadgerbrook** [comment]
Amended definition below should work when aggregation changed from count to session.id, so if someone submits 2 queries and uses 3 filters each time in one session, they will be counted as having 2 queries, won't they? @harrisonpim @jamesgorrie @jamieparkinson what do you think?

**Definition of search**

(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*
and
(page.query.page:1 OR NOT page.query.page:*) # retain this. still works
and
cardinality by page.query.query.keyword

**Comment by taceybadgerbrook** [comment]
**Definition of Percentage total item views/total searches**

Numerator:
(page.name:item or page.name:image)
and
NOT (source:viewer/paginator)

Denominator:
(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*
and
(page.query.page:1 OR NOT page.query.page:*) 
and
_cardinality by page.query.query.keyword_

Problem with last part is that percentages become huge (as in 1000%). Appears to card for all queries, so for example all the many queries for, "anatomy" are counted just once. 

@jtweed ok with you if we drop the percentages metric and stick with Item view/search conversion by session.id? We can still calculate total item views and total searches; we just can't get Kibana to represent this on a dashboard without double counting.

**Comment by harrisonpim** [comment]
I think I'm missing something here - how is the session.id incorporated?

**Comment by taceybadgerbrook** [comment]
Due to the difficulty of removing duplicates in search metrics created by filter usage, it has been agreed that the Kibana dashboards will just have to include these. The dashboards will still be useful for spotting trends and anomalies. When producing statistics for wider consumption or conducting ad hoc analysis, Python or Elasticsearch transforms should be used to remove duplicates.

Here are the definitions that are used in the conversion* index dashboards:

**Definition of search:** 
- counts paging through results served as only 1 search
- includes in counts additional filters used on same search term

(page.name:images or page.name:works)
and
page.query.query:*
and
properties.totalResults:*
and
(page.query.page:1 OR NOT page.query.page:*)

**Definition of works page view:**
- this is understood to be analogous to taking a book down from the shelf

page.name:work
and
page.query.id:*

**Definition of works page selected from archive tree:**
page.name:work
and
page.query.id:*
and
source:archive_tree

**Definition of actual work clicked to view**
- does not include views generated by paging through work. Note that stats for period before source:viewer/paginator was created 13/1/21 will include when users page back to page 1 - surprisingly common!

(page.name:item or page.name:image)
and
NOT (source:viewer/paginator)

**Comment by taceybadgerbrook** [comment]
Analysis of duplication in search metrics is in this ticket:
https://github.com/wellcomecollection/platform/issues/5183

**Comment by taceybadgerbrook** [comment]
**Definition of works page view which includes tei data:**

- this is understood to be analogous to taking a book down from the shelf

page.name:work
and
page.query.id:*
and
properties.identifierTypes.keyword :*tei*
