### ISSUE TITLE
Design podcast series and episodes

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5861]
# What is it and who's it for?
- People who want to find and listen to our podcasts (of which we currently have two)

# Design work
- Series page
- Episodes - decide whether they all go on Series page, or are separate pages linked to from the Series page
- Handling Soundcloud embeds to whichever widget design is best in context
- Handling podcast identity image, typically created as 1:1 ratio to be included on podcast platforms/apps
- Listing contributors (contributor component is overkill for number of possible contributors. we want to avoid extra photography + bio writing work)
- Designing an easy to read transcript format
- Body text on series and episode for describing, including show notes (text + links to things)

Relates to #5792  

# Implementation 

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by pollecuttn** [comment]
14 December 2020:

Series page
- v1 card + v2 heading

Episode page:
- episode number in listed episode titles
- episode number, date and title 
'Part of'

**Comment by DominiqueMarshall** [comment]
Series page wireframe: 
https://zpl.io/adlPxOL

Series page v2 (platform list visually different)
https://zpl.io/2jAP8Bx

Episode page wireframe:
https://zpl.io/aMy9qeo
