### ISSUE TITLE
Enable editors to edit the Books slice on Stories

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5902]
# What is it and who's it for?
For the content editors to change the three books featured on the Stories page.

Currently all changes are hard-coded, making work for the devs. We want to enable editors to add an arbitrary list of books to the list. 

# User story
As an editor
I need to be able to change the promoted books on Stories
So that we're promoting the books that are most recent and/or most valuable to the Publishing team.

# Implementation 

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by alexwlchan** [comment]
David did this. 🎉
