### ISSUE TITLE
Archives: Works page search term analytics

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5919]
**We want users to be able to**
Find the items that they need within an archive collection 

**but we hypothesise this is happening**
Users are landing on an archive page and immediately searching for more content

**We are right if we measure**
The search terms that the users is using in the search bar on an archives works page

**and get this result**
They search for something similar to the page they are on or for another item within that collection without using the archive tree

**The deadline for results is**

**Comment by taceybadgerbrook** [comment]
@alicerichmond would be good to have a chat about this in the new year after archive has been added as an option for source in the conversion* index. I'm thinking measuring success might be tricky without specialist subject knowledge.
