### ISSUE TITLE
Additional tracking required for Elasticsearch conversion* index

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5938]
The conversion dashboard needs to be able to track when users:

- View actual works but just the once (don't want to count when they page through a book)
- View works page after clicking on archive tree (I am checking whether this triggers source=archive)
- View works whose works pages are outbound links to resources held by a third party (if you keep following the links…) (eg https://wellcomecollection.org/works/ar4jveu9) Note: important to distinguish between users who exit the site and users who click on these links.
- Listen to audio files (eg https://wellcomecollection.org/works/s5uyujtx) or view video files (eg https://wellcomecollection.org/works/v6q9dnym)
- the page position when users select works from search results
- start a session (right now we use anonymousIds as a proxy for sessions)

**Comment by taceybadgerbrook** [comment]
conversion* does not record workType except as page.query.workType (when user filters by workType.) Is this possible to surface as part of the work selected so that we can use the dashboard to debug things like image views?

**Comment by jennpb** [comment]
@taceybadgerbrook Is this still relevant? If not, please can you close?
