### ISSUE TITLE
Search within a digitised item

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5945]
# What is it and who's it for?
Researchers using the digitised collections

# User story
As a researcher
I need to be able to search within a digitised book
So that I can more easily identify a source

Feedback passed on from library enquiries:

> I have come across the Second International Congress on School Hygiene: Transactions, 1907 on your website because I believe they may contain a source I am looking for: a report by a Dr. A. S. Arkle to the Liverpool Education Committee called ""Condition of Liverpool School Children"". I believe it was cited in some detail in an address by a Mr Vivian at the  Congress. What I am wondering is whether the Transactions are full-text searchable? I have been poring over the contents of the volumes trying to find Arkle or Vivian or Liverpool but I have not had much luck ... it would be great if someone is able to let me know whether there's a way I can search its full text.

# Implementation 

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by gestchild** [comment]
- [ ] add ellipsis b/w ;need to match hit to resource to get the text
- [ ] add image x/y page z
- [ ] show thumbs highlighted
- [ ] bug main image doesn't load if clicked to from grid view
- [ ] style search form
- [ ] only show if has search available
- [ ] handle canvas rotation
- [ ] accessibility
  - [ ] keyboard nav works
  - [ ] focus appropriately
  - [ ] aria-live regions
- [ ] use NextLink in SearchWithin?
- loading indicators for search results

**Comment by taceybadgerbrook** [comment]
I've had a play with Search within and while I can see it works really nicely, it would be good to know whether anyone uses this feature or is it just taking up valuable space in the sidebar.

Regarding tracking, are we confident that this feature will work equally well with pdfs and born digital?

**Comment by jennpb** [comment]
No, but that's because we don't currently have the ability to offer searchable PDFs or born digital (the work on BD isn't even started yet).

**Comment by taceybadgerbrook** [comment]
In that case, I think tracking on search result link clicks in Elasticsearch would be good so I can include this in the conversion* dashboard. One for @jamesgorrie.
