### ISSUE TITLE
Card Label refinements

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#5956]
Refinements to the implemented card designs incorporating interpretation labels and listen/play icons.

Reference for designs with spacing:
https://zpl.io/VkggO4M
zpl://screen?sid=5ff4937eb5deda15eb851f89&pid=5aab926b4b6efde01259e959

![Label placement + spacing : Card](https://user-images.githubusercontent.com/36885440/104214636-9bdbc700-542f-11eb-9208-f43fd385e1b8.png)

Play button assett (SVG):
[Play button.svg.zip](https://github.com/wellcomecollection/wellcomecollection.org/files/5797292/Play.button.svg.zip)

- [x] Reduce width of white divider
- [x] Remove rounded corners of labels
- [x] Align labels left edge with rest of card content
- [x] Reduce vertical spacing
- [x] Update 'online' label in line with new design
- [x] Replace play icon with svg above

**Comment by davidpmccormick** [comment]
Speaking with @GarethOrmerod about the play icon inside the yellow circle, seems like it would make sense to use the same play icon (the triangle part) everywhere, with the addition of the yellow background when it is being used as a label. I think this would make sense as a separate PR from #6142 above.
