### ISSUE TITLE
Investigate poor performance of image loading in viewer

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5983]
**What**
From [Digirati channel in Slack](https://wellcome.slack.com/archives/CBT40CMKQ/p1610988413039700), discussion of poor loading performance of images in viewer.

> This isn't related either perhaps but may be something to do with the kinds of requests being issued - looking at the link Natalie sent:
> https://wellcomecollection.org/works/xqdmhupu/items?canvas=12&langCode=eng&sierraId=b20086210&source=viewer%2Fpaginator
> ...If you have the Network tab open in Chrome, then even a minor scroll movement triggers dozens of requests for the text (not the images)
> It took a while for it to settle down and return the /880,/ page image to replace the thumbnail

**Where**
wellcomecollection.org viewer

**Comment by jamesgorrie** [comment]
@gestchild this is pretty serious - I looked at 1 page with text on, and had 50+ requests of +16kb, leading to almost 1mb of data being dropped down the pipes, mostly duplicate.

**Comment by jennpb** [comment]
@jamesgorrie can this be closed now?

**Comment by jamesgorrie** [comment]
This is done in #5984
