### ISSUE TITLE
Document methodology for compiling search and view item statistics

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5996]
**We want stakeholders to be able to**
rely on quarterly searching and item viewing statistics and not be presented with discontinuity following creation of the images API.

**but we hypothesise this is happening**
Counting views currently relies on GA Event Category workDetails. It is now possible to view images without triggering workDetails. 

Counting searches currently relies on Kibana index search relevance implicit event search result selected. This index was set up before the images API was introduced and so may not be return accurate counts.

This means an alternative ways of counting searches and views are required and the methodology needs to be documented so that they are reproducible.

**We are right if we measure**
the compiled searches and views percentages 

**and get this result**
percentages are similar to those before the images API was created.

**The deadline for results is**
25/1/20

**Comment by taceybadgerbrook** [comment]
Can use Data Studio to compile numbers of unique views for 1-6 December, point at which event category = workDetails ceases to include image views.  

For data 7-31 December, have exported Kibana views into csv. To produce unique workIds viewed for quarter, need to combine with Data Studio data and dedupe by workId.

Have identified and reported 2 bugs:
1. [system producing duplicate page views, .01s apart](https://github.com/wellcomecollection/wellcomecollection.org/issues/5998)
3. [workIds not accessible in reporting facility](https://github.com/wellcomecollection/wellcomecollection.org/issues/6000)

**Comment by taceybadgerbrook** [comment]
Both of 5998 and 6000 have been resolved and closed.

**Comment by taceybadgerbrook** [comment]
### Methodology for counting: 

**Searches**

Period 13-22/11/21:
- Segment not tracking search. Can only impute numbers

Before 1/12/20 and continuing:
- Kibana index search_relevance_implicit
- event = Search 

After 1/12/20:
- Kibana index conversion*
- (page.name:images or page.name:works) and page.query.query:* and properties.totalResults:* and (page.query.page:1 OR NOT page.query.page:*)

After 13/1/21:
- session.id available for cardinality

**Views of work pages**
Before 1/12/20:
- Kibana index search_relevance_implicit
- event = Search result selected

After 1/12/20:
- Kibana index conversion*
- page.name:work and page.query.id:*
- note that works pages arrived at by clicking on link, "More about this work" on the image search results page are counted in this definition but otherwise possible to go direct from image search to page.name = image without viewing a /works page

**Views of unique workIds**
Before 7/12/20:
- [Page 6 of Data studio report](https://datastudio.google.com/u/0/reporting/7f5c0cde-4c10-4a36-9544-8b5a0f6ab723/page/dD22)
- Event category = workDetails
- Event label = workId

After 7/12/20:
- GA event does not count when "View image" button clicked on image search results so need to get stats from Kibana
- Kibana index conversion*
- (page.name:item or page.name:image) and (page.query.canvas.number:1 or NOT page.query.canvas.number:*) and NOT (source:viewer/paginator)
- dedupe by page.query.workId = workId

After 12/1/21:
- duplicate problem fixed. Can use View definition without deduping

**Comment by taceybadgerbrook** [comment]
Diagram showing user flow from search to /works page view to actual view:

https://excalidraw.com/

**Comment by pollecuttn** [comment]
@taceybadgerbrook It doesn't look like the diagram is above - maybe you have to download it from excalidraw and upload to GH?

**Comment by taceybadgerbrook** [comment]
So when you click on the link, it doesn't show you the diagram?

**Comment by pollecuttn** [comment]
@taceybadgerbrook No diagram, I just see a blank excalidraw page at excalidraw.com. Maybe it's got something cached for you.

**Comment by taceybadgerbrook** [comment]
![image](https://user-images.githubusercontent.com/32418070/106156049-fb004200-6178-11eb-936a-c000ad4f09cb.png)
