### ISSUE TITLE
Duplicates in conversion* view definition

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#5998]
**What**
The new definition excluding views caused by pagination does not appear to have solved the duplicates problem. Here's the definition of View/View image:

(page.name:item or page.name:image)
and
(page.query.canvas.number:1 or NOT page.query.canvas.number:*)
and
NOT (source:viewer/paginator)

**Where**
Here's what it looks like:
https://reporting.wellcomecollection.org/s/search/app/discover#/view/3ec562d0-5bdf-11eb-81f0-cfa2d1964087?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-12-07T00:00:00.000Z',to:'2020-12-07T00:30:00.000Z'))&_a=(columns:!(_source),filters:!(),index:'217cebc0-334f-11eb-96c7-bfa81aee2c94',interval:auto,query:(language:kuery,query:'(page.name:item%20or%20page.name:image)%20and%20(page.query.canvas.number:1%20or%20NOT%20page.query.canvas.number:*)%20and%20NOT%20(source:viewer%2Fpaginator)'),sort:!())

**Comment by taceybadgerbrook** [comment]
@jamesgorrie happy to chat about this

**Comment by jamesgorrie** [comment]
For my reference - [the bug fix is here](https://github.com/wellcomecollection/wellcomecollection.org/pull/5957), and done on the 12 Jan

**Comment by taceybadgerbrook** [comment]
Have checked that 5957 fixes the duplicates problem by using definition for view item in Discover. All sorted.
