### ISSUE TITLE
No cached mapping for page.query.workId in conversion*

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6000]
**What**
The term page.query.workId = item workId. The field list needs to be refreshed via Management > Index patterns before it can be used in visualisations. Without this, it is not possible to count unique workIds viewed.

**Where**
![image](https://user-images.githubusercontent.com/32418070/105365423-22de2b80-5bf6-11eb-9036-e1f201622b35.png)

**Comment by jamieparkinson** [comment]
Done - fyi I think we all have the permissions to do this, it's entirely within Kibana. It won't have been causing any issues fortunately, it's just a warning (I think they may have added it quite recently).

**Comment by harrisonpim** [comment]
Let me know if you haven't seen how to refresh those index patterns, @taceybadgerbrook. Happy to go through it on a call

**Comment by taceybadgerbrook** [comment]
@jamieparkinson Thanks!

@harrisonpim and thanks! Sounds like good material to our meeting.
