### ISSUE TITLE
Model for parent-child content page relationship

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6004]
# What is it and who's it for?
For website users who need access to a group of related content pages so they can pick and choose what they look at, and can follow onward journeys to related content

# Background

We currently don't have a way to connect a group of content pages together under a single 'parent' page. It's like a series model, but for informational content, not domain objects.

This is problematic in situations where we have multiple pages that relate to each other under a single 'service' area, for example, this set of content pages held together under the main topic of 'Library services and facilities'

```
Library services and facilities
- Library membership
- Copying and imaging services
- Computers and wifi in the library
- Study rooms
```

We have multiple instances of this problem across the website.

## Aims
- Establish 'Part of' relationship for informational content
- Allow nested, parent-child content pages
- Build this so that sibling pages can be included on each other as onward journeys

# TODO
- [ ] 

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
![Parent-child-content-page-relationship](https://user-images.githubusercontent.com/60890140/105689853-2d990900-5ef3-11eb-928f-ebb3f0f14301.jpg)

Initial sketch of how the parent > child content page relationship could work. It's similar to the seasons model, but for informational content only.

**Parent page includes:**
- Hero image?
- Standfirst
- Content about the section
- Cards for child content


**Child page includes:**
- Anchor links
- Page content
- Related child content as cards (onward journeys)


Need to figure out how to describe a group of content pieces in Prismic, and how the 'Part Of' section of the headings could be used to help build the connection between the pages in another way.

**Comment by pollecuttn** [comment]
26 January 2021:

- Parent page: cards are of equal size
- Parent page could be an extension of the landing page
