### ISSUE TITLE
Promo alt text

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6007]
- Images in our promo card links include alt text, which is the first thing read out by screen readers.
- In this context though the alt text is largely irrelevant, and the user has to listen to a detailed description of the image before hearing the title of the thing being promoted (i.e. what the link is for). 
- It would probably be better to use empty alt attributes for promo images.

@alicerichmond I'd be interested to know if what I described above is something that users find annoying in testing, or whether they like the alt text and don't have a problem skipping over it.

**Comment by alicerichmond** [comment]
I think that the best practice behind alt text is that if the image doesn't provide any extra context and is purely decorative then it is ok to not use alt text. I have seen the long alt text before the content on a couple of the promo cards around the site and I think removing them might be the best approach. 

Not all screen reader users are blind and the extra unecessary words could be really problematic for other disabilities.

**Comment by gestchild** [comment]
The DAC accessibility report confirmed this was a problem
