### ISSUE TITLE
Review and set guidelines for use of contact component

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6008]
The `contact` component can be positioned at any arbitrary spot on a content page, but this can lead to inconsistency. By including multiple contacts on a page, it further muddles the page purpose, and is likely to cause confusion by too much choice.

We need to:
- establish whether `contact` is fit for purpose in its current configuration
- write up guidelines that describe when and when not to use the component. 

https://cardigan.wellcomecollection.org/?path=/story/components--contact

**Comment by pollecuttn** [comment]
26 January 2021

- contact block should always be at the bottom of the page (as it's secondary information)

**Comment by jennpb** [comment]
Agreed guidelines https://www.notion.so/wellcometrust/Content-design-guidelines-in-progress-de0681bbd1804d2c89d128ab2f3a64b2#3bc1ef8f9abd4a57821af29ded01653b

## Contact slice

Cardigan component `Contact` [https://cardigan.wellcomecollection.org/?path=/story/components--contact](https://cardigan.wellcomecollection.org/?path=/story/components--contact)

**When to use the contact slice:**

- Use only **once per page** when there is a primary contact (team, individual) that supports the service you're describing on the page.
- The contact shouldn't need to be repeated throughout the text. As long as it's apparent who is the main contact
- Place at bottom of text for consistency across site (NB this is currently editor's control; not baked into page template)

**When not to use the contact slice:**

- When it would be better for readability to mention an email or contact in line with text
- When there's already one on the page.
