### ISSUE TITLE
Review and set guidelines for use of featured image + anchors

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6009]
Where we use a featured image and anchor list, the page is very overwhelming.
![Policies-and-plans-Wellcome-Collection](https://user-images.githubusercontent.com/1446139/105478752-7eaec000-5c9b-11eb-9b5f-c5ac72caccaa.png)

How should we deal with this?
- Recommend not using Featured image when there is an anchor list
- Downscale the image
- Reconsider peristence of anchor list

**Comment by pollecuttn** [comment]
26 January:
- Featured image on parent page
- Anchor list (where needed) on content (child) page

**Comment by DominiqueMarshall** [comment]
[Discussed 28 Jan]
- Have no featured image on informational content pages that have a clear purpose, and are pages that have either a long list of grouped cards or have anchor links.
- If a page has anchor links, this should be shown below the featured text.
- Anchor links are used when there is a minimum of 3 H2s on the page. The advised _maximum_ number of H2s should be no more than 8.

**Comment by jennpb** [comment]
For @GarethOrmerod to consider in the template audit
