### ISSUE TITLE
Exploring 'resource' content chunk

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6010]
# Problem to solve
Across multiple content pages, there is a pattern of content creation that breaks the standard body text + card configuration. This occurs when a content creator wishes to present activities, information resources, or nudges toward other functional content with a call to action. These patterns are inconsistently applied across the site because there is no standard way of doing it; this results in inconsistent CTAs and spacing issues.

[Examples in this Google Doc](https://docs.google.com/document/d/16JzKmY7diBV-hu1bfRxIFS9WHXzUquYe1_iJDdRDoxo/edit?usp=sharing) 

## Proposal
A ‘resource’ is a blob of content comprised of three parts:
- A title
- A short amount of body text that can contain formatted text, e.g. bullets
- A single call to action: linking to an internal page or an external page

~~It optionally has an image.~~
Resources stack together in a list

**How is it different from a card?**
Editor can write the body text so it makes sense in context of the page on which it sits

**Questions**
~~is there a separate link, or is the title the link?~~
~~If an image is provided, is it from the linked page, or selected for each resource separately?~~
~~How would this work in Prismic? 
If modelled as content type: this would imply that we’ll reuse the content elsewhere on the site. I’m not sure this is the case. This would also potentially bloat the list of all content, making it even harder for the content team to search. 
For these reasons, it’s likely better to create as a content slice available to /pages/~~

## Implementation
Prismic model:
`Resource list` can be added to `pages`
`Resource list` comprised of repeating `Resources` 
`Resource` comprised of `Link` `Link label` `Text`

TODO:
- [ ] Design exploration @GarethOrmerod

**Comment by pollecuttn** [comment]
4 February 2021:

Have no gap between link and text so that it's obvious which link goes with which text:

[Link](http://www.example.com)
text text text

Use this a a guide pilot and use for testing (after publishing).

**Comment by GarethOrmerod** [comment]
**Resource component summary of decisions**
A resource component is composed of:

- Short descriptive title, the title also act as the link to the resource
- Description of the resource, 2-3 sentence max
- An identifier which lets the user know if the resource is accessed **online** or **in library**

**Comment by jennpb** [comment]
Prismic slice = `Titled text list`
