### ISSUE TITLE
Accessibility Statement for website

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6015]
# What is it and who's it for?
All site users who want to find out more about our compliance with accessibility standards

# Background

While we are not a public sector body, we should strive to be transparent about accessibility of wellcomecollection.org. 

Sample statement https://www.gov.uk/government/publications/sample-accessibility-statement/sample-accessibility-statement-for-a-fictional-public-sector-website

**Comment by alicerichmond** [comment]
Using the GDS template to create a Wellcome Collection accessibility policy https://docs.google.com/document/d/1l29nvQaXZPgBkAlqWpVw60MbBIRlAvjfSsDITtrUwWo/edit?usp=sharing
