### ISSUE TITLE
Video / Audio tracking

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#6021]
Questions

* Do we mean embedded videos (YouTube etc) or [videos directly on the site](https://wellcomecollection.org/works/ezffer7c)? Same for audio.
* What metrics would we like to collect first?
* What future metrics would we like to collect?

**Comment by taceybadgerbrook** [comment]
We would like to track use of /works pages which contain audio or video content. Metrics would be when a user clicks play.

Here's an example of /works page with video:
https://wellcomecollection.org/works/hduas55q

Here's an example of /works page with audio:
https://wellcomecollection.org/works/avqn5jd8

**Comment by taceybadgerbrook** [comment]
**Do we mean embedded videos (YouTube etc) or videos directly on the site? Same for audio.**

The tracking for video and audio plays is for videos and audio files directly on the site, ie they have their own item number. 

Videos that are on YouTube etc can be tracked using GA4. Podcasts using things like SoundCloud can be tracked using that app.
