### ISSUE TITLE
Wellcome collection heuristic evaluation

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6023]
**We want users to be able to**
be able to use the Wellcome collection site without added cognitive load or negative influence so the team will undertake a heuristic evaluation to ensure that the site meets general usability standards.

Team members will do an evaluation based on https://uxmag.com/articles/psychological-usability-heuristics

Alice and Dominique will do a more extensive evaluation based on Neilson Normans heuristics

**Comment by DominiqueMarshall** [comment]
Link to Notion doc with team notes during the evaluation: https://www.notion.so/wellcometrust/Site-audit-notes-599309ba293941058e2c64d539eba49d
