### ISSUE TITLE
Identifying key user flows

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6030]
**We want users to be able to**
Find their way around wellcomecollection.org

**but we hypothesise this is happening**
users are getting lost/confused

**We are right if we measure**
traffic source volume for list pages and non-list pages

**and get this result**
if traffic source volume drops off between list pages and non-list pages

**The deadline for results is**
end of February

**Comment by pollecuttn** [comment]
https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B9DAA6103-BF06-4E68-8F0B-BB6AE9E2FA38%7D&file=Analysis%20for%20acquisition%20strategy%206030.docx&action=default&mobileredirect=true&cid=1e38cd27-023b-4a16-ada0-9b1b58e7e7a7

**Comment by taceybadgerbrook** [comment]
Additional analysis for users who view pages containing /works or /images. Sharepoint document updated.

**Comment by taceybadgerbrook** [comment]
Latest comments replied to.

https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B48940CE6-7B3A-41B9-9D62-69F98E1DCA89%7D&file=Analysis%20for%20acquisition%20strategy%2010Mar2021%206030%20v2%20.docx&action=default&mobileredirect=true

**Comment by taceybadgerbrook** [comment]
- Re-consolidating Search within Collections content area analysis
- Re-doing tables and creating jpegs for pasting into report

**Comment by taceybadgerbrook** [comment]
Updated report here:
https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Q2%20202021/Analysis%20for%20acquisition%20strategy%2010Mar2021%206030%20v3.docx?d=w38f463cd398842bcb6e7aa50381425f2&csf=1&web=1&e=Nwd5o7

Spreadsheet here:
https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Q2%20202021/Acquisition%20strategy%20(Jan2021%20data)%206030%20v7.xlsx?d=wcdc0b4239dab4d5eb24269f372d96d56&csf=1&web=1&e=TY2dSd
