### ISSUE TITLE
New content type: Guides

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6036]
# What is it and who's it for?
Establishing a new content type in Prismic to support all formats of `guides` being created in collaboration with user-facing teams in the library.

# What's a guide?

**Definition**: A document that helps a user to understand more about our services and collections, generally providing tips and/or how-to instructions for making the most of what we offer. The purpose of a guide is to help users become more independent, particularly in their use of the library and our collections.

**Guides** should have their own index page so we can group all of our guides together. Guides also relate to areas of the collection: for example, a 'How to use archives' guide relates directly to the *Archives and manuscripts* `workType`. We would expect to relate guides to areas of the collection generated from the catalogue API. Eventually we will want to build bidirectional links between `guides` and `works`: Where a work is mentioned in a guide, guide is an onward journey on work page. 

Guide formats:

- How-to guide: answers *how do I...?* type questions, enabling people to be more independent when carrying out research in the library
- Topic guide: gives a starting point for research within a topical area that has strengths in the collection, e.g. Mental health.

Guides have:

- Anchor links
- Body text
- `resources` and `resources lists`
- Captioned image
- GIF video
- Info block
- Contact

# Implementation 
- Use basic page template to support the guide format
- Establish `/guides/` as a resource in Prismic

**Comment by pollecuttn** [comment]
9 February 2021

- content modelling: @jamesgorrie @DominiqueMarshall @gestchild @jennpb Lalita
