### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6052]
# What is it and who's it for?

Ensuring that we have the website as it is audited by an accessibility company before the library site is closed

# User story
As a user I would like to be able to interact with the wellcome collection website without impediment regardles of the accessibility tool that I use

# Implementation 

An external accessibility company are to undertake a review to ensure compliance with WCAG AA

## Acceptance criteria

- Audit carried out on key pages, search, works, viewer involved in the search journey 
- All of the fixes required raised by the audit as high priority are completed

## Testing and tracking
No testing or tracking

**Comment by alicerichmond** [comment]
Quote recieved from DACs for the accessibility audit, this needs to be reviewed by Tom S before we can progress

**Comment by jennpb** [comment]
Order of Procurement signed - ready to go when we have a list of content pages and journeys finalised.

**Comment by jennpb** [comment]
Sent to DAC on 6/4/21.
