### ISSUE TITLE
Search result card improvements: line length, hierarchy

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6084]
As discussed with @DominiqueMarshall @GarethOrmerod @gestchild, improvements to the search results card for consistency and legibility

- Rationalise use of bold text
- Line length
- Order of metadata, and why the date bumps out to the right
<img width="1170" alt="Screenshot 2021-01-28 at 13 53 32" src="https://user-images.githubusercontent.com/1446139/106173454-d9f51c80-618b-11eb-8ca9-cfe85181c704.png">

----
- Spacing between text and thumbnail
- Placement of Available Online label - should it be in context of the thumbnail?
<img width="1236" alt="Screenshot 2021-01-28 at 13 55 05" src="https://user-images.githubusercontent.com/1446139/106173700-22143f00-618c-11eb-8ba2-078a1580d203.png">

----
Mobile view 
- Date property not flowing to next line
- Bold text dominates the card
![MobileSearchResult](https://user-images.githubusercontent.com/1446139/106256724-8c23f700-6213-11eb-81cf-5bd62df0cc36.jpg)

_Originally posted by @jennpb in https://github.com/wellcomecollection/wellcomecollection.org/issues/4687#issuecomment-769239515_

**Comment by DominiqueMarshall** [comment]
Line length and type styling (Desktop): 
https://zpl.io/2Z6E0pL
zpl://screen?sid=6023ee3b4c5ff4b2c2eaac1e&pid=5aab926b4b6efde01259e959

Mobile view:
https://zpl.io/bopq04m
zpl://screen?sid=6023f1a12cd86e0540824618&pid=5aab926b4b6efde01259e959

I've included an option to see how this "_Placement of Available Online label - should it be in the context of the thumbnail?_" could look, but it would be good to get @GarethOrmerod and @jennpb opinion on if it could potentially look out of place, depending on the image orientation (comments on the Zeplin screens)

**Comment by DominiqueMarshall** [comment]
Design Review notes (11th Feb 2021):

- Agreed to reverse the use of bold text on search result cards and on the works page header
- Shorten line length on search result cards (aim for 90 characters max)
- Rearrangement of worktype label as shown in Gareth O's design. Label should sit below the main card content: https://zpl.io/an5Dm1n, zpl://screen?sid=60252789f71153b075c7de8d&pid=5aab926b4b6efde01259e959
