### ISSUE TITLE
Font loading improvement for Wellcome Bold

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6112]
**What**

Wellcome Bold doesn't always load correctly

**Where**

https://wellcome.slack.com/archives/C294K7D5M/p1613062379290700 has the problem and a video demonstrating it at  https://wellcomecollection.org/articles/YCQOsBIAACIAaMEN

**Comment by gestchild** [comment]
Fixed in #6118
