### ISSUE TITLE
Epic: Survey mechanism to gather feedback

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6114]
# What is it and who's it for?
- For users to let us know whether they've found a page useful
- For us, to gather feedback on areas of the site where the content or functionality didn't meet user needs.

We need a mechanism to gather input and put it into a place where we can analyse the responses.

# Success measures

- People are finding the feedback component on the page

- People are giving relevant responses about the website, its content and functionality, not about the programme, customer service, venue itself. This could indicate the copy isn't setting expectations.

# Implementation 

I've investigated whether Hotjar's feedback widget will allow for this type of feedback, but it really only handles feedback on a scale of grumpy to happy. We need a solution that allows for a simple Yes/No response with free text feedback.

We do not want to collect personal data.

@alicerichmond suggested that we could set up an Airtable form to link to.

The solution needs to:
- Ask a straightforward question
- Allow user to input an unambiguous response
- Allow user to provide more information
- Capture which page they were commenting on
- Be implementable on content pages (not index pages, section-level pages or items)

Key questions:
- Does this page tell you what you needed to know?
- Is this page useful? [Y/N] - Free text: Help us understand more about what you were looking for so we can improve the content on this website. What were you expecting to see on this page? Is information missing or incorrect?

GOV.UK handle this with a simple component at the bottom of each page
<img width="1031" alt="Screenshot 2021-02-16 at 11 47 26" src="https://user-images.githubusercontent.com/1446139/108059174-02ff2380-704d-11eb-81f7-3bf1af817bf7.png">

**Comment by pollecuttn** [comment]
https://github.com/wellcomecollection/wellcomecollection.org/issues/8908 for works pages info

**Comment by jennpb** [comment]
I'm going to break this epic down into smaller tasks.

**Comment by jennpb** [comment]
After talking to other stakeholders and considering the implications of a static, site-wide feedback component, I've taken the decision to call this off.

You can read about the factors leading to this decision in [this doc](https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Research%20operations/Feature%20idea%20Feedback%20Component.docx?d=w465c2be4f94243c684f7c79f700431d9&csf=1&web=1&e=6Y0a6a)

### Summary

At this point, we should not build the feedback component that relies on Airtable or email to notify/store responses, because: 

- Multiple use cases and data input fields required, leading to design complexity. 
- Colleagues across Wellcome Collection aren’t Airtable users; we don’t want to create a process that requires additional user access and training. 
- Potential to have conflicts of purpose with other feedback mechanisms (Contact us by email; popup component) 
- Likely to receive comments, questions and feedback that are outside the remit of Digital, and would require timely, regular triage. We can’t commit to that. 

**What can we do instead?** 

- Use existing popupDialog component to trial the approach. How much is it used, how is it used?  
- Use a Hotjar survey on a subset of content (/exhibitions, /events, /pages)
