### ISSUE TITLE
Non-gallery image treatment for content pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6135]
# What is it and who's it for?
- Content editors who want to use images as secondary to text
- Users who find it easier to understand and scan a page with images on it

Starting with the '[What's in the collections](https://wellcomecloud-my.sharepoint.com/:w:/g/personal/l_kaplish_wellcome_ac_uk/EXI7s5rjAWtOsqdIK1i6BtsBHOc92UKCxfZU0ex3iniONg?e=4%3AfeWDZ3&at=9&CID=eed092da-949a-81cd-ee5f-e41173a4d60d)' content we need to find a way to interject images that illustrate the text.

We presently have two ways of displaying images in the body of a page:
- [Image gallery](https://cardigan.wellcomecollection.org/?path=/story/components--imagegallery) - not suitable for this context
- [Captioned image](https://cardigan.wellcomecollection.org/?path=/story/components--captionedimage) that goes as wide as it can. Not suitable for all situations where we want the image to directly relate to the text

# Implementation TBC

**Comment by pollecuttn** [comment]
25 February 2021:
Use variation on captioned image with narrower width

**Comment by GarethOrmerod** [comment]
Agreed designs on Zeplin for **body image**: [Desktop](https://zpl.io/2jgEveQ) • [Mobile](https://zpl.io/b6GRMEW)
