### ISSUE TITLE
Adding e-book/third-party resource links to works pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6137]
# What is it and who's it for?

For researchers using our subscription/third-party online resources, we need to make the links and labels available on the works pages in the most appropriate way.
This builds on https://github.com/wellcomecollection/platform/issues/5037

Background conversation https://wellcome.slack.com/archives/C3TQSF63C/p1613990897009600

For implementation, we'll need to keep the link and label text separate due to hugely variable character lengths.

# Implementation 

## Acceptance criteria
- User can open the e-resource via a link from the works page

## Testing and tracking TBC
- Setting up additional tracking and monitoring - talk to Tacey

## Measurement
- Related KPIs - breadth of collection accessed

**Comment by alexwlchan** [comment]
> For implementation, we'll need to keep the link and label text separate due to hugely variable character lengths.

This will be presented as two different fields in the Catalogue API.

The long text will be in `items.label`, the link text will be `items.label.locations.linkText` – either one or the other will be filled in, depending on what data we have available.

**Comment by DominiqueMarshall** [comment]
Example design for the external resources link list.
- Links to have line breaks
- Follow the same styling as #6010 
- Have included an external link icon, but words may be better suited to make it obvious that the links go to an external site. Wording TBC. 

<img width="1293" alt="Screenshot 2021-03-12 at 14 19 52" src="https://user-images.githubusercontent.com/60890140/110956199-4a25bf00-8342-11eb-9ac4-6779ba6983ce.png">

**Comment by pollecuttn** [comment]
15 March 2021

- Remove 'Online resources' heading
- List the links
- 'View all' link at the bottom that will show all/show less

**Comment by pollecuttn** [comment]
17 March 2021
 - Max number to display: 3
