### ISSUE TITLE
Tracking downloads by Segment

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6147]
# What is it and who's it for?
Tracking when users download items for feature evaluation

# User story
As an analyst

I want to track the conversion rate of total downloads/total item views and identify API/workType where users are getting stuck

So that the Experience team can improve access

# Implementation 

## Acceptance criteria
Field available in conversion* index

## Testing and tracking
To be built into conversion dashboard

## Other considerations

**Comment by jennpb** [comment]
Can we also see what file type they've downloaded?
- large image
- small image
- whole pdf

**Comment by jamesgorrie** [comment]
The event currently looks like:
```TS
{
  "event": "download",
  "width": 760 | 'full' | undefined,
  "mimeType": "application/pdf" | "image/jpeg"
}
```

This covers all bases in your request @jennpb but allows for extending at a future date. Does that give you what you need?

**Comment by taceybadgerbrook** [comment]
So does this mean the following definition

large image = width:full
small image= width: number 
whole pdf = width: undefined

**Comment by jamesgorrie** [comment]
Correcto!

It does. Small is just a label we use on the website for `760`.

Is there anything useful for PDF?

**Comment by taceybadgerbrook** [comment]
whole pdf is for downloading non-images. So would I filter for this by mimeType:application/pdf?

**Comment by harrisonpim** [comment]
the event data itself looks sensible to me :grin:

how will that event appear in kibana? will `width`, `mimetype` etc appear dotted after `properties.event`? or alongside `event` in properties?

**Comment by jamesgorrie** [comment]
@harrisonpim Yip

**Comment by taceybadgerbrook** [comment]
**Definition of small image download:**
page.name = image
properties.width = 760
properties.event = download
properties.mimeType = image/jpeg
type = event

**Definition of large image download:**
page.name = image
properties.width = 'full'
properties.event = download
properties.mimeType = image/jpeg
type = event

**Definition of non-image download:**
page.name = work
properties.event = download
properties.mimeType = application/pdf
type = event

**Comment by jamesgorrie** [comment]
@taceybadgerbrook the page name could be `image | item | work` as it's available on all of those pages.
