### ISSUE TITLE
Adding the hot jar tracking info to the search results page

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6154]
# What is it and who's it for?

Search header research

To complete this research the hotjar code needs adding to the search results pages. Currently the code is only on the archives pages that was being used for previous research.

Note: There is new flexibility in hotjar to have "continous heatmaps". If the code is set on any page, the heat maps can be created and pages filtered within hot jar rather than having to alter the code everytime. The code and info is available if you go to https://insights.hotjar.com/sites/3858/heatmap/view and click the tracking button in the top right corner. 

I am not 100% sure if this differs to what we were using previously. 

<img width="681" alt="Screenshot 2021-02-24 at 17 46 43" src="https://user-images.githubusercontent.com/7315126/109042699-6847ba00-76c8-11eb-9d4e-77fb68f2a109.png">

If you need anymore info the help page is here https://help.hotjar.com/hc/en-us/articles/360034216634-Hotjar-JavaScript-Functions-Reference

**Comment by davidpmccormick** [comment]
> Currently the code is only on the archives pages that was being used for previous research.

Has that research finished now (and can we subsequently remove the code that we'd used to run it)?
