### ISSUE TITLE
Transcript component in podcasts not working as expected

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6191]
# What is it and who's it for?
Content team

When producing a podcast, the Prismic model doesn't work as expected.

**Current behaviour:**
The `Discussion` slice allows editors to input: `Title` and `Repeatable zone: contributors`. There's no space for the transcript text.

**Expected behaviour:** 
Instead, the `Discussion` slice should allow editors to input `Title` (e.g. Transcript) and the text of the transcript. `Contributors` are not required here. 

The transcript text should appear in the collapsible element as shown in this screen: https://zpl.io/bowEEdZ

**Comment by gestchild** [comment]
I think this is working as expected. Each repeatable zone has a contributor **and** a text field (see screenshot below)

![Screenshot 2021-03-09 at 12 33 16](https://user-images.githubusercontent.com/6051896/110471206-c4044100-80d3-11eb-935d-c25feff973fd.png)

The contributor is used to populate the **Speaker 1** etc. in the designs:
![Screenshot 2021-03-09 at 12 36 32](https://user-images.githubusercontent.com/6051896/110471640-47259700-80d4-11eb-8e47-e34883d69ac5.png)

**Comment by jennpb** [comment]
That wasn't the intent. It's extremely onerous to enter contributor details for all contributors, and @dannybirchall finds this unworkable.

The contributors component should relate only to the page, not the transcript.

The transcript should just be body text.
