### ISSUE TITLE
Navigate a manuscript or book's structure by page number

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6192]
# What is it and who's it for?
Collections researchers

Adding in the page label information to the UI so users can jump to a specific published/referenced page number of a book or manuscript. 

# User story
As a researcher
I expect to be able to find a specific page in an online item
So that I can trace the information I have about this item from a citation or other reference.

As a researcher
I need to be able to enter a page number
So I can jump to where I want and save time.

# Implementation

**Comment by jamesgorrie** [comment]
@jennpb is this referring to the page number from IIIF rather than a `0` index of which canvas you're on?

**Comment by jennpb** [comment]
That's correct @jamesgorrie
