### ISSUE TITLE
Navigate a manuscript or book's structure by "manifest" (volume, copy, part)

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6193]
# What is it and who's it for?
Collections researchers

Digitised items have "manifests" in the IIIF world.

We currently display this on the item page in a drop-down button

<img width="1246" alt="Screenshot 2021-03-08 at 17 15 36" src="https://user-images.githubusercontent.com/1446139/110356266-f8272580-8031-11eb-9491-4060a581ad9d.png">

## Problem to solve
Anecdotally, this button is being overlooked or missed. There is a strong possibility that users aren't able to figure out how to navigate to other manifests within the digitised item.

Investigate ways of improving visibility of multiple manifests - either on work page or item page.

Relates to #5948

**Comment by jennpb** [comment]
@taceybadgerbrook Are you able to get any data that shows whether people are clicking on the drop-down button to select  other parts? Is this something we need to try to get a heatmap on, or is there anything in the search data that will help?

**Comment by taceybadgerbrook** [comment]
I can only report on drop-downs if the action is coded in or I use Google Tag Manager. Hotjar sounds like an easy option but I think it only works on individual pages. @alicerichmond your thoughts?

**Comment by jamesgorrie** [comment]
[We have usage on this for the past month](https://reporting.wellcomecollection.org/s/search/app/lens#/edit/7253ce70-80ab-11eb-bcd6-c58220746d65?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1M,to:now))).

This is calculated by looking at how many `pageviews` have the `manifest` or `canvas` property. We split download between `image` and `item` as we use the same viewer for the two different types.

What we don't track is any structure to the item e.g. Does the item have manifests. This is something we could/should do.

We could attach properties such as `manifestCount: 7`, and then see - of all items viewed with more than 1 manifest, do people use the control?

**Comment by taceybadgerbrook** [comment]
@jamesgorrie if you attach a manifestCount property, then I'll build in a data table in the search-only dashboard (as opposed to conversion-everything-and-its-dog dashboard) of pageviews for items with manifestCount>1. If it turns out there are lots of these items being accessed, I will create a time series.

**Comment by jennpb** [comment]
Manifests were moved to accordion. We will still have this issue to address (re: language of volume/copy/part etc) https://github.com/wellcomecollection/wellcomecollection.org/issues/5948
