### ISSUE TITLE
Render format labels on /projects

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6202]
# What is it and who's it for?
All site visitors

We have the option in Prismic to set a Format on `/projects`. However, this label isn't rendering.

The format labels should render on all content types where we offer a `format` option in the model.

Here's an example page https://wellcomecollection.org/pages/YCEq1RIAACMAXBLL

# Implementation 

## Acceptance criteria
- Format labels display on cards and content pages

**Comment by davidpmccormick** [comment]
I think this possibly needs @GarethOrmerod and/or @DominiqueMarshall to suggest label placement

**Comment by DominiqueMarshall** [comment]
@davidpmccormick For consistency purposes, it looks like the label would be best in the same place as the others (so underneath the heading)

**Comment by jennpb** [comment]
@davidpmccormick It doesn't look like the labels are rendering on the cards - is this a separate piece of work? I noted it in the Acceptance Criteria above but can see that it'd be easy to overlook.

**Comment by davidpmccormick** [comment]
Ah, I missed that. I'll reopen this.
