### ISSUE TITLE
No yellow section underline for What we do or Collections

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6206]
**What**

The main nav doesn’t indicate the section you’re in (yellow underline) for ‘What we do’ nor ‘Collections’ (does for other sections and Collections is highlighted when on /works or /images)

**Where**

https://wellcomecollection.org/what-we-do
https://wellcomecollection.org/collections

See https://wellcome.slack.com/archives/C294K7D5M/p1615370133125800

**Comment by jennpb** [comment]
https://wellcome.slack.com/archives/C294K7D5M/p1615385369133900
