### ISSUE TITLE
Rel="canonical" tags for all preview.wellcomecollection.org links

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6218]
# What is it and who's it for?
Web searchers

Search engines are currently indexing `preview.wellcomecollection.org` links, which is not what we want.
https://www.google.com/search?q=site%3Apreview.wellcomecollection.org&rlz=1C5CHFA_enGB857GB857&oq=site%3Apreview.wellcomecollection.org&aqs=chrome..69i57j69i58.5440j0j1&sourceid=chrome&ie=UTF-8

We need to ensure we're using `rel="canonical"` tags on both Prismic pages and Works from the API.

**Comment by alexwlchan** [comment]
We do have canonical links on preview.wellcomecollection.org, but for some reason Google is ignoring them. I’m not sure why – maybe we should get Google Search Console for preview.wc.org?

<img width="692" alt="Screenshot 2022-10-20 at 21 16 46" src="https://user-images.githubusercontent.com/301220/197049372-b6646d70-e1cc-4d2a-944d-6f5a94ec22f8.png">

**Comment by jennpb** [comment]
@alexwlchan @taceybadgerbrook @dannybirchall Is there a reason we'd want `preview.wc.org` to be indexed at all? I can't think of why we would, but maybe there is something I'm missing. Search Console could help us troubleshoot/understand whether this is a problem or not, but my instinct is that only the canonical URLs should be indexable.

**Comment by alexwlchan** [comment]
> Is there a reason we'd want preview.wc.org to be indexed at all? I can't think of why we would, but maybe there is something I'm missing.

No, I think we could just exclude it.

**Comment by taceybadgerbrook** [comment]
I'm very much in favour of excluding preview and staging from the Google Analytics and GA4 data. Best practice is to have one property for staging and one for prod.
