### ISSUE TITLE
Splitting conversion dashboard into search, conversion and collection

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6223]
**We want to know if the following change has improved the user experience**
New features for viewing and filtering

**Definition of success is**
- lower median page position when filters used
- more items viewed
- wider spread of workids viewed

**We'll know if we're succeeding if**
We can actually find what we're looking for in a dashboard

**Definition of failure is**
Information overload...

**Comment by taceybadgerbrook** [comment]
@harrisonpim @jamesgorrie @jtweed here is the new search dashboard based on the conversion* index:
https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/88c2ee40-3b9e-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(description:'uses%20conversion*%20index',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),tags:!(),timeRestore:!f,title:'Search%20dashboard%20',viewMode:view)

Ok if I delete JT version of the search dashboard that used search relevance implicit? I think it's just best practice to draw stats from the same place.
https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/7d2392f0-28e4-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'JT%20dashboard%20created%20for%20a%20screenshot,%20can%20be%20deleted',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),tags:!(),timeRestore:!t,title:'Search%20Metrics',viewMode:view)

**Comment by harrisonpim** [comment]
love the idea of those dropdown filters to control the dashboard! Selecting an api endpoint seems to break some of the metrics though - any idea why?

**Comment by taceybadgerbrook** [comment]
Pretty whizzy if I do say so myself. Thanks for spotting the bits that fall down when selecting works or images. I'll have to look again at the definitions.

**Comment by taceybadgerbrook** [comment]
Dashboard controls are whizzy but not whizzy enough. I've changed the label from API to Type of search and suggested choosing either works or images because it's not possible to limit the choice in the drop down. Filtering using this control will only populate search-related TSVBs. 

Interesting to note that Kibana will allow you to filter by location but it's picky about the time period - the shorter, the better!

**Comment by taceybadgerbrook** [comment]
The dashboard controls have been amended to types of search conducted (page.name:works or images.) Filters which apply to searching are not recognised by item view or works page view actions, so these will appear as blanks if this filter is used in the conversion dashboard.
