### ISSUE TITLE
Public Programme monthly reporting for Rosie Stanbury

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6224]
**Create regular monthly reporting framework to answer:**

- Are these events successful? 
- Should we continue with online events after the building opens or revert to in person? 
- Are some events / some formats more successful than others?

**Set up reporting, links to cover:**

- usage of events (and exhibition pages) i.e. numbers of users or unique pageviews?
- number of people listening/ watch events
- possibly hours watch/listened
- possibly some indication about how people are listening/watching e.g. listen all the way through or just a bit
- possibly subdivide by types of events
- Podcast plays
- exhibitions when we’re open

**Comment by taceybadgerbrook** [comment]
To produce first draft by 16 March.

**Comment by jennpb** [comment]
@taceybadgerbrook Just a wee clarification. This monthly report isn't specifically about Seasons, but about the live programme as a whole. Not all events and exhibitions, online or otherwise, form part of a season. 

The work to analyse the Being Human Now season will be a one-off piece of research and analysis.

**Comment by taceybadgerbrook** [comment]
@jennpb Thank you for the clarification.

So the one-off season work will be the analysis being conducted after April, then?

**Comment by jennpb** [comment]
Being Human Now is the one-off season work.

This ticket (as I read it), is the monthly reporting on live programme content.

**Comment by taceybadgerbrook** [comment]
All metrics up to date until end Feb. To be updated on 1/4 to include March.

**Comment by taceybadgerbrook** [comment]
Total page views | 234,413
Total reading time (h) | 2,869
Total users | 102,981
Total audio/podcast listens | 2,983

Total video plays (detail below) | 82,938
-- | --
being human now part 1 (Audio-described version available) | 51,833
being human now part 2 (video) | 24,040
D/deaf and Disabled Artists on Making Work Now | 1,249
Condoms in the Kitchen | 1,006
empathy in an age of division | 771
curators introduce art (past event) | 649
intensive care with dr gavin Francis | 627
A Different Kind of Future with Heart n Soul | 528
Supporting ourselves in changing times | 477
The Surfaces of Skin and Screens | 461
Changing Our Planet, Changing Our Minds | 395
Monstrous Births in the Middle Ages | 189
Young People, Mental Health and Recipes for Self-care | 188
Faith-based Responses to Epidemics | 169
Is Tear Gas as British as Tea? | 116
Supporting Ourselves While Supporting Our Communities | 109
Young People on Education and What We Learned From Lockdown | 105
Considering the Source of Elizabeth Blackwell's 'A Curious Herbal' | 26

**Comment by taceybadgerbrook** [comment]
The peak in page views and monthly users during October 2020 is due to users visiting the website to check on opening times, etc as the building reopened briefly during that month. The increases across all statistics during January 2021 were due to the launch of the What It Means To Be Human Now season on 18 December 2020.
![Pg views, monthly users (Mar)](https://user-images.githubusercontent.com/32418070/113320240-339fd180-930a-11eb-8f78-2b2d45fdc962.jpg)
![Total reading time (Mar)](https://user-images.githubusercontent.com/32418070/113320252-38648580-930a-11eb-9b7b-34a8353cec7c.jpg)
![Total podcast:audio video plays (Mar)](https://user-images.githubusercontent.com/32418070/113320268-3d293980-930a-11eb-891c-0dfb6978daf5.jpg)

**Comment by taceybadgerbrook** [comment]
Report to be refreshed with April figures first week of May.

**Comment by taceybadgerbrook** [comment]
Sharepoint link to report:
https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/_layouts/15/doc.aspx?sourcedoc={929ce26d-12d6-42a4-bd80-3fadc6998292}&action=edit
