### ISSUE TITLE
Image rotation seems to be broken on all single images (all MIRO ones?) in the wc.org viewer

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6245]
**What**

Image rotation seems to be broken on all single images (all MIRO ones?) in the wc.org viewer.

looks like you can rotate once in deep zoom, but not before

https://wellcome.slack.com/archives/C8X9YKM5X/p1616066408044900

**Where**

https://wellcomecollection.org/works/vvxcss2z/items?langCode=false&canvas=1
https://wellcomecollection.org/works/thbr4x7s/images?id=da3a6tb5

**Comment by gestchild** [comment]
This seems to be an issue with the server:

`https://iiif.wellcomecollection.org/image/M0014002/full/880,/0/default.jpg` - is fine, but when the rotation request parameter is changed the server responds with a 500 error
`https://iiif.wellcomecollection.org/image/M0014002/full/880,/90/default.jpg`

**Comment by gestchild** [comment]
[Digirati are looking into this](https://wellcome.slack.com/archives/CBT40CMKQ/p1617717273294900?thread_ts=1617716548.294200&cid=CBT40CMKQ)

**Comment by gestchild** [comment]
and it's fixed
