### ISSUE TITLE
Requesting: Add holdings to work pages

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#6247]
# What is it and who's it for?

# User story
As a researcher
I need to know what portions of a journal the library has in its collections
So that I can know if they are available for consultation and research

# Examples

## Single holdings, single enumeration, with location:

https://api.wellcomecollection.org/catalogue/v2/works/wtu8srqb?include=holdings

## Single holdings, multiple enumeration, with location:

https://api.wellcomecollection.org/catalogue/v2/works/x84n4jgc?include=holdings

## Single holdings, multiple enumeration, with location with shelfmark:

https://api.wellcomecollection.org/catalogue/v2/works/hqbvmqf3?include=holdings

## Single holdings with no location:

https://api.wellcomecollection.org/catalogue/v2/works/v4g7fk8k?include=holdings

## Multiple holdings, same locations:

https://api.wellcomecollection.org/catalogue/v2/works/gdqt83k2?include=holdings

## Multiple holdings, different locations:

https://api.wellcomecollection.org/catalogue/v2/works/cezwtkb2?include=holdings

## A big example, that is even bigger when you add in items:

https://api.wellcomecollection.org/catalogue/v2/works/m3a4d359?include=holdings,items

**Comment by alexwlchan** [comment]
I should add: currently all the holdings have physical locations, but they will also get digital locations (URLs) in some cases.

See https://github.com/wellcomecollection/platform/issues/5126

**Comment by alexwlchan** [comment]
## Single digital holdings, single enumeration

https://api.wellcomecollection.org/catalogue/v2/works/t3ay8m97?include=holdings

## Multiple digital holdings, single enumeration

https://api.wellcomecollection.org/catalogue/v2/works/jyeangwd?include=holdings

**Comment by DominiqueMarshall** [comment]
Wireframes for the examples above:

1. Single holdings, single enumeration, with location: https://zpl.io/29mw5mp
2. Single holdings, multiple enumerations, with location: https://zpl.io/ad3zA3l
3. Single holdings, multiple enumerations, with location with shelfmark: https://zpl.io/bo38k3m
4. Multiple holdings, same locations: https://zpl.io/2EQgwQ8
5. Multiple holdings, different locations: https://zpl.io/Vx30B33
6. Long list of items, different locations: https://zpl.io/2v3OB3j

With 3 & 6, I've put the label and shelfmark together... @jtweed does it make sense to treat it that way if we want to avoid using the term 'Label'?

**Comment by jtweed** [comment]
Just to bump what @alexwlchan mentioned earlier in the comments, we need to make sure we look at holdings with digital locations when we pick this up again.

These are going to be links to subscription resources that likely require sign in, so we should also possibly bear that in mind when looking at how we signpost them on the page.

**Comment by pollecuttn** [comment]
Holdings label/text misalignment should be solved by https://github.com/wellcomecollection/wellcomecollection.org/issues/6522
