### ISSUE TITLE
Getting Stories into Google Sitelinks

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6248]
# What is it and who's it for?
It's getting Stories into Google's standard 6 Sitelinks so that users can go straight to the page.

# User story
As a reader, I need to see that Stories exists so that if I think it sounds interesting, I can click on the link and start reading.

# Implementation 
To help Google understand how the site is structured, can either add schema or structure the articles urls so that they are linked to Stories. Here's a link to an article that discusses how to do this: https://bloggingwizard.com/google-sitelinks/

## Acceptance criteria
Inclusion in Sitelinks isn't the only benefit. Google will also serve Stories when users Google, "wellcome collection." Currently Stories isn't even in the top 5 pages.

## Testing and tracking
Tacey to produce Google Search Console stats on clicks to Stories per Google query
- Qual test plan - Tacey

## Measurement
- Reading time

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design

**Comment by taceybadgerbrook** [comment]
During the month of February 2021, when users Googled, "wellcome collection," the site was served 11,331 times and clicked 7,630 times. The table below shows that Sitelinks only make up 6% of these clicks but that numbers decline relative to the proximity to the main site link. If we could get Stories to show up second to Collections, it would boost clicks and also boost the Google page position in Google. Right now it's not even in the top 5 pages of results.

![image](https://user-images.githubusercontent.com/32418070/111995438-d4bfa880-8b10-11eb-8e15-be1f5acd28cd.png)

**Comment by taceybadgerbrook** [comment]
Certainly SEO is a factor in that only the most-viewed pages appear as Sitelinks. It occurs to me that one thing that might confused Google is that each story appears as the child of /articles and yet there is no /articles page.

**Comment by jennpb** [comment]
you mean this? https://wellcomecollection.org/articles

**Comment by taceybadgerbrook** [comment]
I didn't know it existed until now.

Since 1/1/21 the articles page has been view 5,534 times compared with /stories which had 14,244 page views. If Google's algorithm depends on page views, it will favour /stories. I guess the question is whether having /stories in article urls would boost /stories and make it even more discoverable.
