### ISSUE TITLE
Titles for main landing pages in Google not synced

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#6253]
Google shows stories title as `Wellcome Collection Stories` instead of `Stories | Wellcome Collection` like the rest of the site and as it it in the code

<img width="667" alt="stories" src="https://user-images.githubusercontent.com/31692/112026949-a05ae500-8b2e-11eb-99e0-3ce622f09767.png">

**Comment by taceybadgerbrook** [comment]
In working on https://github.com/wellcomecollection/wellcomecollection.org/issues/6536 I've found examples of where Google is not displaying the story summaries that Editorial have submitted (see email forwarded to you.)

**Comment by taceybadgerbrook** [comment]
I've done some reading on how Google Search works and it looks like most of the time, Google takes their snippet from the Promo text which Editorial provide. However, in cases where an article contains popular tokens, Google will instead present the sentence containing the token.  I am now working with Editorial to suggest ways they can make the most of the Promo text, Standfirst text and tags.

**Comment by davidpmccormick** [comment]
I just googled "wellcome collection stories" and it looks (at least for now) like they're picking up the page title ("Stories | Wellcome Collection") as the search result heading. So this can probably be closed?

**Comment by taceybadgerbrook** [comment]
@davidpmccormick yes, can definitely be closed. I've confirmed in https://github.com/wellcomecollection/wellcomecollection.org/issues/6617 that Google is crawling the site correctly.
