### ISSUE TITLE
Missing dashes in subject and genre tags

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6257]
**What**
We seem to have lost the dashes between words in subject and genre tags.

I would expect that subjects and genres render the punctuation.

**Where**
https://wellcomecollection.org/works/d5zws93r

<img width="722" alt="Screenshot 2021-03-23 at 12 28 09" src="https://user-images.githubusercontent.com/1446139/112146464-81625e80-8bd3-11eb-9d10-799d6a7b95e5.png">

Browser: Chrome, Safari

**Comment by pollecuttn** [comment]
@alexwlchan Long shot, but can this have been caused by any recent trimming work? I know you were more concentrating on trailing full stops.

**Comment by alexwlchan** [comment]
Let me have a look, it’s certainly possible I messed up the joining character.

**Comment by alexwlchan** [comment]
> Long shot, but can this have been caused by any recent trimming work?

The data in the API has all the dashes, so I don’t think I caused this issue: https://api.wellcomecollection.org/catalogue/v2/works/d5zws93r?include=genres%2Csubjects

**Comment by alexwlchan** [comment]
Okay, I'm less convinced that this isn't an API issue – testing locally, with the front-end rolled back to code from about a fortnight ago, I still don't see the dashes.

**Comment by jamesgorrie** [comment]
@jennpb this happened as a regression as we have applied the rules for contributors (to not have separators) universally across tags on the works page. 

[There's a PR in fr this](https://github.com/wellcomecollection/wellcomecollection.org/pull/6294)
