### ISSUE TITLE
Minimum card height

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6270]
# What is it and who's it for?
Ideally cards would be a standard size but as we need to accommodate a large variety of content it's not feasible. In certain instances there is a large difference in card height per row. This could be mitigated by introducing a minimum card height to encourage more consistency and rhythm.

![card-heights](https://user-images.githubusercontent.com/36885440/112352748-f06ab080-8cc2-11eb-9d85-927ef40fa53d.png)

**Comment by davidpmccormick** [comment]
All cards on any single row will have the same height currently. Is the problem that different rows can have different heights? My concern with adding a minimum height would be that I think we'd add quite a bit of extra beige _most_ of the time.

**Comment by GarethOrmerod** [comment]
**Another option:** for cards which don't have the black labels accessibility labels at the bottom, could we introduce 32px padding bottom. Currently the cards look like they need some extra vertical space at the bottom to balance out the content e.g.

[Zeplin](https://zpl.io/aw5B5xg)

![Cards - 32px bottom padding](https://user-images.githubusercontent.com/36885440/124465620-8667aa00-dd8d-11eb-875e-682725221700.png)

**Comment by davidpmccormick** [comment]
I was thinking along similar lines – this would limit any excess beige.
