### ISSUE TITLE
Reduce label padding and standardise across breakpoints

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6276]
# What is it and who's it for?
The current label sizes are too large and can dominate the information they are associated with.

Suggest reducing the padding to either:

- **6px** (height would be 33px)
- **6px left and right, 4px top and bottom** (this would bring the labels down to 24px height which aligns with the system sizes)

![Label padding](https://user-images.githubusercontent.com/36885440/112490750-911aa800-8d77-11eb-93ff-e747e56a696b.png)

**Comment by davidpmccormick** [comment]
Didn't realise there was a ticket for this, but it was done (`6px` padding everywhere) in #6370. Going to close this.
