### ISSUE TITLE
Green underline link vertical spacing

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6277]
# What is it and who's it for?
The green underline links used on type at 20px e.g. Stories main body copy has too much space below, closer to the line below than the link it relates to.

**Examples:**

<img width="705" alt="Screenshot 2021-03-25 at 14 49 05" src="https://user-images.githubusercontent.com/36885440/112493177-d5a74300-8d79-11eb-95d5-a05757350421.png">

<img width="706" alt="Screenshot 2021-03-25 at 14 48 49" src="https://user-images.githubusercontent.com/36885440/112493189-d9d36080-8d79-11eb-8224-db2785ce3b77.png">

**Comment by davidpmccormick** [comment]
Think this might be related to the Helvetica regular toggle and the vertical position of that font inside the line-height being different to the other cuts of Helvetica that are in use generally (for people who don't have the toggle turned on).

**Comment by GarethOrmerod** [comment]
Could the green link underlines be displayed in the same way as in the cards? They look much better and there's no conflict with descenders touching the underlines.

**Comment by GarethOrmerod** [comment]
Helvetica Regular - Is there anything to learn from the corporate site which has a simpler font stack and uses `font-weight 700` for bold?
