### ISSUE TITLE
Viewer info panel: Colour and design options 

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6279]
# What is it and who's it for?

To improve the usability and distinction of the control/info panel in the material viewer
- user research indicated that users find the similarity to the viewing area and info panel harder too similar causing a lack of disctinction between the two
- having a few different design ideas with different colours may improve this

# User story
As a neurodivergent user the viewer info panel can be hard to read because of the contrast and colours used
As an experienced researcher it is not clear that the viewer info panel contains control options because it blends in with the viewing window

# Implementation 

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by DominiqueMarshall** [comment]
@jennpb @GarethOrmerod  A few links I found for some background research:

https://www.editorx.com/shaping-design/article/what-is-neurodiversity-in-web-design - mentions the black and white combination being too extreme.

https://www.autism.org.uk/what-we-do/website/accessibility - example of a colour mode switch that people can use to toggle between bright and muted colours.

https://www.w3.org/WAI/people-use-web/abilities-barriers/

https://www.w3.org/WAI/cognitive/
