### ISSUE TITLE
Cursor styles while interacting with digitised content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6291]
# What is it and who's it for?

Anyone using digitised materials

How we currently use cursor styles
- **hand pointer** - Currently used for three separate functions: in use while scrolling, used to select image and zoom, and to indicate a button is clickable. This means that a user can inadvertently open the deepzoom image while scrolling. The hand pointer is doing a lot of work it shouldn't!
- **arrow pointer** - used while in zoom mode; clicking it triggers deeper zoom until user hits max zoom depth. This isn't intuitive.

## Problems to solve
We need to refine the UI for our cursor styles to ensure that users don't trigger an action unintentionally.
- Not clear that scrolling up and down is the default behaviour
- Not clear that clicking on an image takes you into deep zoom mode
- When in zoom mode, the cursor doesn't indicate that clicking zooms deeper

There are loads of good examples of switching between scroll / select / zoom on tools like Miro. And Google Maps of course.

**Comment by GarethOrmerod** [comment]
Attached is our **Exit fullscreen** icon

[Exit fullscreen.svg.zip](https://github.com/wellcomecollection/wellcomecollection.org/files/6297971/Exit.fullscreen.svg.zip)

![Exit fullscreen](https://user-images.githubusercontent.com/36885440/114421997-c9aae600-9bad-11eb-97cf-f75ee931cf61.png)
