### ISSUE TITLE
Add licenseDetails to item info panel

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6311]
# What is it and who's it for?
People looking at digitised items

We should add the license detail to the side panel so that users get a brief description of what the license means, so they don't necessarily have to use the licence link for more information.

We currently expose the license type and credit in the side panel 
<img width="333" alt="Screenshot 2021-03-31 at 11 01 23" src="https://user-images.githubusercontent.com/1446139/113127281-7da48c80-9210-11eb-9d01-6ba8da4e030e.png">

We should also expose the information from the LicenseDetail

<img width="577" alt="Screenshot 2021-03-31 at 11 03 11" src="https://user-images.githubusercontent.com/1446139/113127634-e2f87d80-9210-11eb-845e-eede6c0ea54b.png">

# User story
As a researcher
I want to know about the license assigned to this work
So that I can use an item with confidence that I'm using it correctly.

# Implementation 

## Acceptance criteria
- 'human readable' text description for the specific license is displayed under `License: {XXX}`

**Comment by pollecuttn** [comment]
Info from @jennpb:
The credit problem:
When we designed our credit line, we only had Miro images to work with. We followed the recommendations as described here https://wiki.creativecommons.org/wiki/best_practices_for_attribution
Following the TASL format: Title Author Source Licence.
Now that we have more complex titling and the possibility of multiple named contributors (or complete absence of), this template doesn’t work quite right anymore. 
Some examples of where it goes wrong:
https://wellcomecollection.org/works/sat2qh4k - contributor already part of the title; has additional two contributors
Credit: La pratique du jardinage / par m. l'abbé Roger Schabol, ouvrage rédigé après sa mort sur ses mémoires, par M.D*** [i.e. A.N. Dezallier d'Argenville] by  Source: Wellcome Collection Public Domain Mark
Archive - only shows title, no author https://wellcomecollection.org/works/bqd39jxt 
Credit: Fingerprints. Wellcome Library. Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
Third-party attribution
https://wellcomecollection.org/works/jrjc2jb6

https://wellcome.slack.com/archives/G5QLV74NM/p1619798388002300

FYI @jtweed 

This also applies to the 'Can I use this' section of the works page.

**Comment by pollecuttn** [comment]
Another example of an archive that only shows title, no author:

> I notice that when viewing a digitised archive item, the "Credit" line in "Licence and credit" uses the title, but this is often going to be nonsensical, e.g. in this one, we have a credit of "R-W". Anyone wanting to use the Oscar Wilde letter that comes up top of the list will be pretty confused! https://wellcomecollection.org/works/b7deha34/items?canvas=1 (edited) 
https://wellcome.slack.com/archives/C8X9YKM5X/p1625136140058400
