### ISSUE TITLE
Exit fullscreen UI

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6312]
# What is it and who's it for?
People using digitised items.

Need a more intuitive way of exiting full screen mode.

# Problem to solve

We currently don't display a way to exit full screen once you're in full screen. 
Users can `esc` to exit and click on the 'full screen' button, but that's counterintuitive.

<img width="1280" alt="Screenshot 2021-03-30 at 12 03 24" src="https://user-images.githubusercontent.com/1446139/113128796-1556aa80-9212-11eb-8ced-88a2faeb3a12.png">

When in full screen, the button should change to indicate 'Exit full screen'

# Implementation 

## Acceptance criteria
- The UI indicates a user can exit full screen
- Using that button, the user exits full screen
- Label changes to `Exit full screen`

**Comment by GarethOrmerod** [comment]
Attached is our `Exit fullscreen` icon

[Exit fullscreen.svg.zip](https://github.com/wellcomecollection/wellcomecollection.org/files/6298019/Exit.fullscreen.svg.zip)

![Exit fullscreen](https://user-images.githubusercontent.com/36885440/114423050-b51b1d80-9bae-11eb-897f-b618e09b3963.png)
