### ISSUE TITLE
Improving mobile usability of image controls on digitised items

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6332]
# What is it and who's it for?

Anyone using their mobile phone to look at digitised items

Currently the placement of the zoom and rotate controls on mobile causes some interference with the global nav. As shown in this video, the placement at the edge of the navigation means that it's possible to hit the logo and go to the homepage, or to inadvertently zoom the screen.

https://user-images.githubusercontent.com/1446139/113727167-ca92d200-96ec-11eb-9f02-656f3108dca8.mov

**Comment by GarethOrmerod** [comment]
This could possibly be solved by moving the controls to the bottom right, so there would be a consistent placement for controls which manipulate the image. We currently have it so the controls display top right when in zoomed view.

This would highlight another problem though that the browser toolbar across the bottom currently obscures the zoom view controls.
