### ISSUE TITLE
Download image: mismatch between pixel info and image size

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6335]
**What**
For [this item](https://wellcomecollection.org/works/sxts9x35/items), the pixel information given for the full size image download, doesn't match the dimensions of the actual image.

It says the full size image is 2188 x 3222

![Screenshot 2021-04-06 at 17 22 58](https://user-images.githubusercontent.com/6051896/113746551-5a8d4780-96fe-11eb-8cae-ad60f32541f2.png)

but when downloaded, the image is 695 x 1024

**Comment by gestchild** [comment]
I think this is an issue with MIRO images in particular and have [raised it with digirati](https://wellcome.slack.com/archives/CBT40CMKQ/p1618416467373300?thread_ts=1617716548.294200&cid=CBT40CMKQ)

**Comment by donaldgray** [comment]
@gestchild fix deployed and tested.
