### ISSUE TITLE
Requesting library items

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6337]
## Description

Online requesting of physical items in the library is a core service that supports access to our collections. This feature connects with the Single Sign-On service and library account registration in order to provide member-level access to the collections. 

## Objective

Researchers engage with a broader range of our collections

## Measures

- Can existing library members request closed stores materials from wc.org?

- Can non-members set up an account in order to request materials?

## Initiatives

- Request from the catalogue with a library account

- View list of current holds/requests from My Account

- See request status from My Account

- Be notified when holds are ready to pick up

- Select a pickup date

- View list of previous holds

**Comment by jennpb** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4845067

**Comment by jtweed** [comment]
Superseded by https://github.com/wellcomecollection/platform/issues/5221 for boring Productboard integration reasons.
