### ISSUE TITLE
Zoom button throwing 401 errors on 'open with advisory' content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6338]
**What**
From Alexandra:

> The magnifer button in the wc.org viewer still seems a bit hit and miss. This page (win/Chrome) is was a miss (results in a 401 error and a completely black window): https://wellcomecollection.org/works/cqkdm7zb/items?canvas=37 until suddenly the advisory pop-up appeared, and now it's working again.

**Where**
Chrome, Windows

**Comment by davidpmccormick** [comment]
I can't reproduce this, but I think it sound like it could have been related to #6346 (recently fixed).

**Comment by jennpb** [comment]
Ok, let's deprioritise for now but keep it open in case it repeats and we can get more info on it.
