### ISSUE TITLE
Clear search form in 'search within'

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6343]
# What is it and who's it for?
Anyone searching the contents of a digitised work

Users should be able to easily clear the search form so they can run a new search 

# User story
As a researcher
I need to be able to adjust my search keywords
So that I can make sure I've picked up everything relevant.

# Implementation 

## Acceptance criteria
- User can clear search form by clicking the `clear` icon

**Comment by davidpmccormick** [comment]
Would you expect any page highlights from a search to be cleared at the point of clearing the search input? I don't think there's currently a way to do this, beyond searching for something that yields no results. Or is the ability to clear highlights something else again?

**Comment by jennpb** [comment]
No, I don't think clearing highlights or search results is necessary. Similar to how you can clear the search box on the regular search box - it just clears the text so you can type in something new, more easily than using delete key.
