### ISSUE TITLE
Unable to interact with contents panel on digitised item pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6374]
**What**
When clicking on a link within the contents panel of digitised item pages, the users get a blank screen; neither the canvas nor any UI loads. Page becomes unresponsive.

slack convo here https://wellcome.slack.com/archives/C294K7D5M/p1618389039374800

![image](https://user-images.githubusercontent.com/1446139/114681504-228d9200-9d06-11eb-9334-a035460f25ac.png)

**Where**
Safari - desktop
Safari - mobile
Firefox
Chrome

**Comment by alexwlchan** [comment]
Note: if you want to see the web inspector, you need to open the inspector *before* you click a link in the contents panel. The bug causes the browser to lock up and I'm unable to open the web inspector once the bug triggers.
