### ISSUE TITLE
Using UK spelling for licence in UI

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6409]
# What is it and who's it for?
Anyone using our site who wonders why US spellings have crept in.

Thanks to the Americans in the team 🤷‍♀️ , the word 'Licence' has been spelled incorrectly all these years. 

Correct all instances of license to **licence**.

# Where

Three places that need fixing:
Work page:
<img width="305" alt="Screenshot 2021-04-21 at 09 11 24" src="https://user-images.githubusercontent.com/1446139/115519994-9b9a6580-a281-11eb-8636-a77b54de8540.png">

Item page sidebar:
<img width="323" alt="Screenshot 2021-04-21 at 09 12 19" src="https://user-images.githubusercontent.com/1446139/115520088-b371e980-a281-11eb-9012-3a08db3751c2.png">

Download modal:
<img width="521" alt="Screenshot 2021-04-21 at 09 12 59" src="https://user-images.githubusercontent.com/1446139/115520247-def4d400-a281-11eb-9b96-09eb6cb52836.png">

**Comment by alexwlchan** [comment]
A couple more instances: we have "Open Government License" and "Open Parliament License" in both the API and filters, even though the URLs we point to use the British spelling.
