### ISSUE TITLE
Requesting: Display the physical items included in a work

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6410]
# What is it and who's it for?

When a researcher or library visitor interacts with an items work page, they need to clearly see what items are included in a specific work to guide them in knowing what items they need to request.

# User story
As a library member
I need to see where an item is lives 
So that I know if it needs to be requested

## Acceptance criteria

- [ ] All items visible on a works page
- [ ] All location types supported
- [ ] Users understand which items need to be requested

## Other considerations 
- Need an example of every location type to make sure they're all supported
- Everything should be ready apart from "copies on order" but can be done soon
- Some closed store items may have a shelfmark but its not its a label that is in that field, but this is going to be removed over time

**Comment by alexwlchan** [comment]
## Examples

Single item, single closed location without shelfmark:
https://api.wellcomecollection.org/catalogue/v2/works/zmtzwfmp?include=items

Single item, single closed location with shelfmark:
https://api.wellcomecollection.org/catalogue/v2/works/unsu83kt?include=items

Single item, single open location without shelfmark:
https://api.wellcomecollection.org/catalogue/v2/works/rva7zngc?include=items

Single item, single open location with shelfmark:
https://api.wellcomecollection.org/catalogue/v2/works/xm69apdg?include=items

Single item, multiple physical locations:
(No examples of this currently exist)

Single item with a mixture of physical/digital locations:
https://api.wellcomecollection.org/catalogue/v2/works/r9kpkq8e?include=items

Multiple items, different physical locations:
https://api.wellcomecollection.org/catalogue/v2/works/mtt2grge?include=items

Multiple items with a mixture of physical/digital locations:
https://api.wellcomecollection.org/catalogue/v2/works/zf3mph5m?include=items

**Comment by DominiqueMarshall** [comment]
- Digital and physical item works page example: https://zpl.io/V4N8q70
- Open shelves + shelfmark: https://zpl.io/aBzrl4L
- Closed stores example: https://zpl.io/VDge5Yv

**Comment by jtweed** [comment]
I've been talking to @DominiqueMarshall about this and we agreed a next step to try and improve the layout of the info for items.

These are not fully resolved nor available in Zeplin, but are mocks from me in Dom's absence to show the direction. Let's start with spacing etc as per the standard typography and the headings/values as used for the rest of the work data. Everything should stack on mobile.

Open shelves examples:

<img width="859" alt="Screenshot 2021-07-19 at 18 08 54" src="https://user-images.githubusercontent.com/42490/126204252-fe2935a8-8b40-4209-90ca-49ac1afeeee3.png">

The coloured squares are inspired by the way finding signs in the library. These are only valid for open shelves items and there are five areas with four colours:

![IMG_0032](https://user-images.githubusercontent.com/42490/126204184-b0136377-d35c-41e2-b5c3-5b74f10d6b57.jpg)

This same pattern then extends out to more complex items, with request item button appearing only when the user is signed in:

<img width="841" alt="Screenshot 2021-07-19 at 18 09 01" src="https://user-images.githubusercontent.com/42490/126204255-6d233d7a-aeca-4b5b-8fe8-251fa149625d.png">

This generalises as follows:

<img width="857" alt="Screenshot 2021-07-19 at 18 09 23" src="https://user-images.githubusercontent.com/42490/126204260-f5c4ffd5-39f2-43de-8eb7-10151763131c.png">

**Comment by jtweed** [comment]
One addedum to the above. Whilst we will ultimately only show the request item button when the user is signed in, for now we should always show it and use it to link to Encore.

We can then change this behaviour behind the sign in/requesting toggle as appropriate.

**Comment by davidpmccormick** [comment]
In order to get the colour squares, I'm thinking of checking for `locationType.id === 'open-shelves'` and then maybe looking for one of five string values in the `label` field (e.g. 'History of Medicine', 'Journals' etc.). Is there another (better) way of doing this with the data as it currently is?

**Comment by jtweed** [comment]
Yeah, I talked to @alexwlchan about that and we felt that at least for the first implementation to see how people respond to it, that we shouldn’t add it to the API but do it in the front end exactly how you describe. Ie, look for one of the four known strings in `location.label` if it’s type `open-shelves`.

**Comment by jtweed** [comment]
On the responsiveness, Dom and I haven’t had a chance to think about actual sizing at all, so yep do what you think makes sense and we can always tweak a bit if needed. Keen to try another way of doing this, but get it up for feedback sooner rather than later.

**Comment by alexwlchan** [comment]
I’ve had a quick look through, these are the strings we currently have that look likely:

```
History of Medicine
History of Medicine Collection

Medical Collection
Medicine & Society Collection?

Quick Ref. Collection
Quick Reference

Journals

Student Collection?
Student Coll. (oversize)?
Student Coll (Med Lit)?
Student Coll. (ref only)?
```

I’m not sure if "Student Collection" is the same as "Student Loan", possibly @pollecuttn or @jtweed  knows?

I would match on all the strings above, but I'm thinking it'd be nice to put in some transformer logic that maps these strings to the exact text that is printed on signs in the library.

**Comment by pollecuttn** [comment]
Not all items in the Student Collection are available for loan, so I would assume those are different.

"Medicine & Society Collection" was a separate thing from the "Medical Collection". Pretty sure those should be different.

But @davidpmccormick you could double check those questions with #collections-info in Slack.

**Comment by davidpmccormick** [comment]
> the broad division of Medical Collection and History of Medicine collection is coded in the BIB record location: either medc (medical collection) or homc (history of medicine collection).

https://wellcome.slack.com/archives/CGXDT2GSH/p1626881005204900?thread_ts=1626880787.204300&cid=CGXDT2GSH

Does that distinction make its way into the API (I think probably not)?

**Comment by alexwlchan** [comment]
> Does that distinction make its way into the API (I think probably not)?

I'd have to check, but I don't think so – we use the item record locations, not the bib records.
