### ISSUE TITLE
Requesting: Display location and shelfmark for open shelves items on works pages

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6411]
# What is it and who's it for?

When a researcher visits the library site, they need to be able to easily identify where an item sits on the open shelves so that they are able to orientate themselves before they visit the library.

# User story
As a library member
I need to know where to find an item in the library
So that I can optimise my visit

## Acceptance criteria

- [ ] Open shelves items show their shelf location and shelfmark
- [ ] Users understand that open shelves items are available without requesting
- [ ] Users know how to find a shelf

## Other considerations 
- How do we support someone in finding out where a certain shelf is?
- Can we use Opac messages?

**Comment by alicerichmond** [comment]
Emailed David L to confirm questions from the workshops

1. How many no shows on average does the library tend to have for items that have been requested? Does this happen regularly or relatively infrequently?

2. Does the library team already have messaging about how quarantine is working with items in the library?

3. Is there a list of expected retrieval times for different item types at all? 
	- we would like to at some point be able to indicate to a user how long something might take to order so that it makes life easier when they are arranging travel or that they might know if they  	can order something within a deadline they are working to

4. Are there a clear rule on what items are delivered to the rare materials room and which are sent to the enquiries desk? I understand things changed slightly during lockdown with everything being collected in the rare materials room. Will this carry on?

5. Currently we use the labels open shelves, closed stores and so forth to describe where to locate something in the library. Do you know if there is any simple language that the LE&E team use currently to explain these locations? If not, would you be open to spending some time with us, thinking about how we can communicate these locations in a way that is universal?

6. Are there many enquiries about the location of items within the library when someone is visiting? We are trying to understand if the maps are being found on the current site.

**Comment by DominiqueMarshall** [comment]
**Open shelves + holdings works page example:** https://zpl.io/be3Rldz
**Closed stores example** - includes a 'request item' button so researchers can begin to understand the difference between needing to request closed stores items, and not needing to request open shelf items: https://zpl.io/ad3Old1
