### ISSUE TITLE
1-page/grid view segmented control

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6417]
# What is it and who's it for?
People using digitised content so they can control how many images they see on screen

As depicted in Zeplin https://zpl.io/254NWMJ

# User story
As a researcher
I want to switch between an overview and a detailed view
So that I can move around the digitised item more flexibly

# Implementation 

## Acceptance criteria
- [x] Component created for toolbar
- [x] View state highlighted when selected
- [x] Two versions produced for A/B testing
- [ ] A/B testing run and concluded

## Testing and tracking
A/B test

Version A: Icon only
Version B: Icon + Label : `1-page view` `Grid view`

Hypothesis: Icons can be understood and used without descriptive labels.

**Comment by davidpmccormick** [comment]
a/b testing is blocked while we wait for results from a/b test running on the sidebar toggle.

**Comment by davidpmccormick** [comment]
Closing with test being tracked in #6445
