### ISSUE TITLE
Filters not being properly reset

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#6419]
* searched for a phrase
* filtered by date (from 1490 to 1495)
* clicked "reset filters"
* did my new search
* filtered by "books" 

this added back my original date filter but the filters should have stayed cleared

**Comment by pollecuttn** [comment]
@jamieparkinson I'm still seeing the initial problem reported - can you have a look, please?

**Comment by jamieparkinson** [comment]
Just wasn't deployed to prod yet - I'll wait for that to go through and confirm it works, then close this

**Comment by pollecuttn** [comment]
Great - thanks
