### ISSUE TITLE
iiif manifests served from iiif.wellcomecollection.org

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6428]
**What**
Relates to #6373. When iiif manifests are being served from iiif.wellcomecollection.org we are seeing a few issues on the /works and /items pages.

- [x] 1. where items are '[open with advisory](https://wellcomecollection.org/works/bqd39jxt/items?canvas=1)' / '[restricted](https://wellcomecollection.org/works/jgwhhsz9/items)' only a blank page is showing
- [x] 2. work pages with [videos that are open with advisory ](https://wellcomecollection.org/works/yy8x7tgp), no longer display the message and clickthrough (likely related to the issue above)
- [x] 3. [search functionality](http://localhost:3000/works/re9cyhkt/items?canvas=1) does not work correctly, wrong pages highlight and links from the results don't work
- [ ] 4. where items have [multiple volumes](https://wellcomecollection.org/works/ysmqsfhg) the ability to navigate them is missing
- [ ] 5.[ Items with restricted images](https://wellcomecollection.org/works/pnud3fzb) don't show the restricted text or symbol

**Comment by pollecuttn** [comment]
4. is a bug for Digirati to fix
https://wellcome.slack.com/archives/CBT40CMKQ/p1619106343467900?thread_ts=1619007552.436700&cid=CBT40CMKQ

**Comment by tomcrane** [comment]
(see https://github.com/wellcomecollection/platform/issues/5146 mentioned above for DDS-side fixes)
