### ISSUE TITLE
Viewer intermittently navigating to wrong canvas after opening on correct canvas

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#6434]
**What**
When opening a link to a page in the viewer, it occasionally navigates first to the correct page, then on to a different page (possibly always the second page). Hard to reproduce, but has been seen on Windows 10 in Chrome.

**Where**
https://wellcomecollection.org/works/tmj6mkg3/items?canvas=103

**Comment by pollecuttn** [comment]
Reported on Slack at https://wellcome.slack.com/archives/C8X9YKM5X/p1619104896280400
