### ISSUE TITLE
Requesting: Display access conditions for items

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#6446]
# What is it and who's it for?

When a researcher or library visitor interacts with items on a work page, they need to clearly see if a specific item has any access conditions to guide them in knowing what they can do with the item.

# User story

As a library member
I need to see any access restrictions on an item
So that I know if I can request and make use of it

## Acceptance criteria

- [ ] All access statuses supported for physical items
- [x] Any additional access terms are clearly displayed
- [ ] Users understand what they can do with an item

## Other considerations

- Access conditions are made up of an access status and optional access terms.
- There can also be an optional date that goes with a status, which is when the status applies until.
- This date might only be used on archives, which can also have multiple access conditions to represent different closed and restricted until dates.

## Access statuses

There are several possible access statuses, some of which only apply to digital items:

- Open
- Open with advisory
- Restricted
- By appointment
- Temporarily unavailable
- Unavailable
- Closed
- Licensed resources
- Permission required

## Examples

Library item:

https://api.wellcomecollection.org/catalogue/v2/works/h544fyjg?include=items

Archive item:

https://api.wellcomecollection.org/catalogue/v2/works/x8m5rum8?include=items

Lots of further examples:

https://github.com/wellcomecollection/platform/issues/5150#issuecomment-828518532

**Comment by DominiqueMarshall** [comment]
Concept for rendering the access conditions alongside the 'where to find it' table (using the longest example of terms): https://zpl.io/ad3lx51

**Comment by jtweed** [comment]
This might have to wait until @alexwlchan has done a bit more modelling work, but have we considered what this looks like when there are multiple items with different access conditions on the same work?

**Comment by DominiqueMarshall** [comment]
> This might have to wait until @alexwlchan has done a bit more modelling work, but have we considered what this looks like when there are multiple items with different access conditions on the same work?

it's something I'm thinking about that in the background, related to conversation in this ticket: https://github.com/wellcomecollection/wellcomecollection.org/issues/6492

**Comment by davidpmccormick** [comment]
As we're now showing access conditions inline for each item I think the second point in the acceptance criteria has been covered off.

**Comment by jtweed** [comment]
Closing this, as I think this is covered by the broader items work. It’s looking like we’re going to the show the terms of use at work level and that we can get away with not showing the granular access status at work level (it’s used to help determine the access method).
