### ISSUE TITLE
More filters modal checkbox scroll bug

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6457]
**What**
On desktop when scrolling through _More filters_ on a catalogue search result. The checkboxes display outside the modal window at the bottom

**Where**
e.g. [more filters here](https://wellcomecollection.org/works?query=crick+archive)

<img width="861" alt="more_filters_bug" src="https://user-images.githubusercontent.com/36885440/116524814-b6975600-a8cf-11eb-8ccc-a8a421ea148c.png">

**Comment by jamesgorrie** [comment]
@GarethOrmerod what browser are you using?

**Comment by jamieparkinson** [comment]
Can't reproduce this on latest Chrome/Safari/Firefox - any further hints for reproduction?
