### ISSUE TITLE
Content type to publish access content (audio, BSL, text) for gallery visitors

### ISSUE THREAD

**Issue by dannybirchall** [wellcomecollection/wellcomecollection.org#6461]
# What is it and who's it for?
A new content type to deliver multimedia content (image, audio, video, text) to WC visitors on their own devices

# User story
As a **Gallery visitor with a sensory impairment**
I need to **access audio/BSL/textual interpretation on my own device**
So that I can **understand gallery content and minimise my risk of infection**

# Implementation 
The Story content type contains all the design elements needed to deliver guide content, but using the actual Story content type potentially causes problematic cross-publishing with actual Stories

A new content type would be ideal; a clone of the Story content type with the same elements would probably be able to deliver all the content.

## Acceptance criteria
Ability to deliver multimedia access interpretation to visitors' own devices in the gallery for Joy and Tranquility exhibitions, triggered by QR codes

## Testing and tracking
We will create utm-style URLs for the QR codes to be printed, so the usage of each individual code (but no user data) will be tracked (this will become obsolete when we stop using Google Analytics)
A conversation is beginning with Alice about how to test the in-gallery implementation

## Measurement
In-gallery usage will be the primary thing we want to measure for success

## Other considerations 

- Impact on URL design
potentially new content type in the form
https://wellcomecollection.org/[type]/4lph4nuM3r1c

- Cardigan documentation
no new elements should mean minimal impact

**Comment by dannybirchall** [comment]
Some extra content:

The exhibitions team have commissioned audio tours of both forthcoming Joy and Tranquility exhibitions. Each exhibition has a tour with twelve stops, which they would like to make available in the gallery through QR codes. The team have also commissioned BSL videos and transcripts of the same content.

**Comment by dannybirchall** [comment]
Another thing I have learned: each stop will be written by a different person; crediting this could work in the same way as contributor roles on stories and events.

**Comment by davidpmccormick** [comment]
Is the requirement for the content to be served from a specific url a hard one? I have a working implementation with a modification of the `parent page` work to include the concept of `order` for any children of a parent. This wouldn't affect urls though – all extra content would be at `/page/{someId}` without further modifications.

**Comment by dannybirchall** [comment]
Yes, we need a permanent URL (which will be used to generate a QR code) for each stop on the tour.
