### ISSUE TITLE
Data requirement for reporting online requesting

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6469]
# What is it and who's it for?
Data for Tania Williams

# User story
As a Library Assistant

I need to report on levels of online requesting

So that Collections understand which areas are being accessed and which are not

# Implementation 
Data to be accessable in Kibana conversion* index

## Acceptance criteria

1. User category (eg Graduate/Undergraduate - part of registration data)
2. Staff/non-staff status 
3. ~~Location code (enables more detailed analysis that workType)~~
4. ~~Call num (enables more detailed analysis of type of collection)~~
5. Title
6. Subject (yes, even though these are not standardised)
7. Delivery destination (eg RMR or Library enquiry desk

## Testing and tracking
Tacey to set up Kibana dashboard for Tania and/or provide access to monthly csv

**Comment by taceybadgerbrook** [comment]
I appreciate that not all of this data has been planned as part of online requesting but first I need to understand what is and is not possible so that I can go back and have the conversation with Tania.

**Comment by taceybadgerbrook** [comment]
I have taken out location code and call num from the list above as these are not in the API and there are no plans to include them.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @GarethOrmerod @jamesgorrie could the following be made available in Kibana?

- user category (eg graduate/undergraduate - from registration data)
- staff/non-staff status - from registration data)
- delivery destination

**Comment by taceybadgerbrook** [comment]
Tania would like to use the location code and call num data to produce tables on specific collections and types of works (eg zines, medical books) as workType is not specific enough:

![image](https://user-images.githubusercontent.com/32418070/117431104-be36aa80-af20-11eb-8e5b-327b3125ea47.png)

The staff/non-staff data would be used to provide a filter so that Collections staff can assess whether demand for certain types of material is staff or non-staff led. The delivery destination data is so that Library staff can decide whether or not to change their processes to make them more efficient.

**Comment by taceybadgerbrook** [comment]
@jamesgorrie I'm looking for the field in the sierra indices in Kibana that hold subject information as part of the requirement for the online requesting data. My hunch is that this is somewhere in sierra_varfields but don't know what the marcTag it is.

Also, if we could have a call about how the sierra indices are organised would be great.

**Comment by taceybadgerbrook** [comment]
@jtweed a summary of the data requirement and business case is in [this document](https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7BA9A8C89D-BEFC-4303-86AE-73A284F3E64A%7D&file=6469%20Data%20requirement%20for%20reporting%20online%20requesting.docx&nav=eyJjIjoxMjAyNjg4NzQ0fQ&action=default&mobileredirect=true&cid=35c59dce-53c0-4630-a92a-a4493ee19802).

In a nutshell, Collections and Research need data for operational purposes as well as for developing collection. The plethora of data listed in [this spreadsheet](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/_Collections/Collections%20Data/Online%20requesting%20requirements.xlsx?d=w09a7ded7d1e84cc28a274b5e3d5bef34&csf=1&web=1&e=tB6Ry8) which includes examples in the example tab is due to the fact that Sierra fields have been used for different purposes over time, making it impossible to identify items using just one field.

**Comment by taceybadgerbrook** [comment]
Objectives for the platform and how the Collections and Research business cases support these:

**Researchers find more of what they're looking for in our collections**
- Develop popular Collection areas
- Improve catalogue metadata
- Prioritise areas for cataloguing

**Researchers engage with a broader range of our collections**
- Increase diversity of Collection
- Planning public events

**Build trust and reduce barriers for visiting and online audiences**
- Reduce access restrictions
- Prioritise items for digitisation

**Comment by taceybadgerbrook** [comment]
Business cases outside of platform objectives:

- Suggest additional material for researchers
- Staff planning
- LED/RMR storage planning
- Locate missing items
- Cost-effective retrieval and storage of items
- Saving money on subscriptions

**Comment by taceybadgerbrook** [comment]
Some dummy dashboards:

![image](https://user-images.githubusercontent.com/32418070/122910141-c66e6c00-d34d-11eb-81d4-ca8eddff2e67.png)

![image](https://user-images.githubusercontent.com/32418070/122910179-cff7d400-d34d-11eb-8161-e203ed5b53d1.png)

**Comment by taceybadgerbrook** [comment]
Dummy dashboards:
![image](https://user-images.githubusercontent.com/32418070/123792261-5a08e500-d8d8-11eb-97ed-5a791d4dfa82.png)

**Comment by pollecuttn** [comment]
Awaiting data from requesting
