### ISSUE TITLE
Wellcome library link for physical items

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6470]
# What is it and who's it for?

People who don't want to follow links to find information that is already available on the work page.

When we display the physical item data for a work and that item is on the Open Shelves, then we no longer need to display a link to the item on the Wellcome library site.

# Implementation 

- remove the library link for open shelves items (This functionality should be behind the same toggle as the one for displaying physical items)

**Comment by gestchild** [comment]
This is how we currently create links to the wellcome library:

1. we get the values of all work.indentifiers with identifier.identifierType.id === sierra-system-number
2. we take the first value remove the last digit and append it to http://encore.wellcomelibrary.org/iii/encore/record/C__R

Therefore the link is per work and not related to specific items on a work.

@jtweed Do we want to remove the link if any item on the work is on the open shelves? or should the link be specific to each item (is this possible?) and then not displayed if it's on open shelves

**Comment by jtweed** [comment]
My thought was that the link would be specific to each item, ie it would only appear on items that are closed stores.

But, that it would take you to the "work" [really bib] page on wl.org, as it's not possible to be more granular than that.

This does depend on shorter microcopy that still makes sense within the items list.

**Comment by pollecuttn** [comment]
@gestchild Now that items are out, can this just be closed? Or does any code tidy up need to happen for open access items?

**Comment by gestchild** [comment]
This can be closed, it was only really about the encore link. Any work that needs doing from here on should be new tickets.
