### ISSUE TITLE
Displaying incorrect BSL logo

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6485]
**What**
Last year we updated the access icons. This listing https://wellcomecollection.org/events/YCLmSxIAACUAY7Cv is using the incorrect BSL icon it should be:

![thumbnail_image002](https://user-images.githubusercontent.com/36885440/117669293-a53b2d00-b19e-11eb-89a7-6215ee29785a.png)

The old icon is not relevant for BSL users.

**Comment by jamesgorrie** [comment]
@GarethOrmerod nice! Out of interest, when you say "Not relevant to BSL users" what do you mean?
