### ISSUE TITLE
Data sources and logic for displaying for physical items

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6492]
Having gone through the latest Zeplin designs for displaying physical items, I've made a few assumptions I want to check and have a few questions.

Assumptions:

1. items[0].locations is an array, but in practice there is only one physical location per item
2. items[0].locations[0].accessConditions is an array, but in practice there is only one per location
3. we don't show the 'request item' link when an item has a location of on-exhibition or open-shelves
4. we don't show the 'request item' link when an item has an access condition of by-appointment or restricted

Questions:
1. [Access condition terms are displayed below the table](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098f2aa205ca4143eec0ab5), which detaches them from the items they belong to. This might be a problem if more than one item has access terms associated with it. Will this ever be the case?
2. I'm not sure where the access data should come from in all cases and what logic should determine this. 
 
  In most instances it is the items[0].locations[0].accessConditions.label, but not all items have this - should it then fall back 
  to items[0].locations[0].locationType.label as is the case here:

  https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60940d49e4772b3753a8eebf
  https://api.wellcomecollection.org/catalogue/v2/works/rva7zngc?include=items

  In the following example the data is from the availabilities array and there is no way to tie this to the item

  https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6098e78b47fd4610d32247e6
  https://api.wellcomecollection.org/catalogue/v2/works/xm69apdg?include=items

  In the following example it is not clear where the data should come from

  https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6093a72905f5e03497bf7983
  https://api.wellcomecollection.org/catalogue/v2/works/qg2a795b?include=items

**Comment by gestchild** [comment]
Relates to #6410

**Comment by DominiqueMarshall** [comment]
The assumptions to me look correct, @alexwlchan can you confirm the first two assumptions above?

Question 1 - Probably a question for Alex; have you seen a case where different items within a single work have different access conditions?

**Question 2**
- In the first example, falling back to the locationType makes sense.
- The data in the second example comes from the [OPAC msgs](https://github.com/wellcomecollection/platform/blob/master/ontologies/Reference%20data/opacmsg.csv), which I think are connected to the location type label? (I've updated the designs back to say 'Open shelves'. I had changed it to 'In library' as a microcopy change)

**Comment by alexwlchan** [comment]
> 1. `items[0].locations` is an array, but in practice there is only one physical location per item
> 2. `items[0].locations[0].accessConditions` is an array, but in practice there is only one per location

There's one case where (2) isn't true, but it looks like a data issue we should squash in the API: https://api.wellcomecollection.org/catalogue/v2/works/yedqmmxp?include=items

> have you seen a case where different items within a single work have different access conditions?

I've had a look through the snapshots; this is never the case.

All three could *theoretically* be false in the model, but it's safe to keep these assumptions for now.
