### ISSUE TITLE
Exhibition audio guides: Setting up metrics for monitoring use

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6494]
**What is the problem to solve?**
Are visitors interacting with the new audio guide content either from the website or via QR code?

**What stage of research is it? (discovery/general usability testing/post release)**
discovery/general usability

**What are the objectives?**
To understand quantity of users who interact with the audio guides, how much of the content was interacted with and for how long

**What are the assumptions?**
Visitors will be able to understand and use the QR code in venue
Website users will interact with the audio guides 
Website users will spend time listening to the audio guides
Website users will be able to locate the audio guides

**What research technique is required?**
Analytics 

**Optimal number of participants**
N/A

**Acceptance criteria**
Analytics tracking implimented in the correct areas to ensure we can evaluate usage

**Deadline for results/dependencies:**

**Comment by jamesgorrie** [comment]
@alicerichmond We mentioned tracking the collections public WiFi - is this something we would want?

I'm not 100% sure what that would give us? People could very easily be using their own data, privacy apps etc. Would it be better to rather set what we think might be an in-venue journey and then make sure we tracking and able to analyse that?

If we really want the above, I'll have to make sure that it's not personally identifiable data (it has been flagged up as such previously).

**Comment by taceybadgerbrook** [comment]
I'm happy to cobble together the url if someone can provide me with the url for the guide(s)

**Comment by taceybadgerbrook** [comment]
Here is a summary of the pages the QR codes are pointing to and the associated urls:
![image](https://user-images.githubusercontent.com/32418070/119519312-3a2e5080-bd71-11eb-82c4-6042878dc390.png)

**Comment by taceybadgerbrook** [comment]
88 visitors have used the QR codes to date:
![image](https://user-images.githubusercontent.com/32418070/122913724-b48ec800-d351-11eb-8939-1110b043ecb0.png)

**Comment by taceybadgerbrook** [comment]
The people counters weren’t switched on when the building opened on 17 May. However the figures below reflect the time period when they were operational. QR user numbers are from GA and cover the same periods.

![image](https://user-images.githubusercontent.com/32418070/122913782-ca03f200-d351-11eb-99c1-7d4f16a58c43.png)

**Comment by taceybadgerbrook** [comment]
Homepage QR code url:
https://wellcomecollection.org/?utm_campaign=InGallery&utm_medium=QRCode&utm_source=GroundFloor&utm_content=GalleryTextPanel
 
Changed to: 
https://wellcomecollection.org/pages/YCEq1RIAACMAXBLL?utm_source=eastlobby&utm_medium=qrcode&utm_campaign=beinghumannow

GA report link here:
https://analytics.google.com/analytics/web/?pli=1#/report/trafficsources-campaigns/a55614w23273620p21588879/_u.date00=20210517&_u.date01=20210627&explorer-table.advFilter=%5B%5B0,%22analytics.campaign%22,%22PT%22,%22beinghumannow%22,0%5D%5D&explorer-table.plotKeys=%5B%5D/

QR code users (ground floor) 17 May to 27 June:
![image](https://user-images.githubusercontent.com/32418070/123656361-c11a9100-d827-11eb-9d4d-c35ea66c22ac.png)

QR code users (campaign: InGallery) 17 May to 27 June:
![image](https://user-images.githubusercontent.com/32418070/123656507-e5766d80-d827-11eb-8c03-e18caa3f8318.png)
