### ISSUE TITLE
Moving from Helvetica Light to Regular

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6522]
# What is it and who's it for?
Neue Helvetica Light as our default typeface has issues with legibility and readability which are in conflict with Wellcome’s approach to accessibility and inclusivity.

We currently use Neue Helvetica Light for a large majority of our typographic needs. There are issues which are exaggerated by using the Light cut of the font for purposes other than as a [display font](https://www.myfonts.com/display-fonts): narrow [apertures](https://en.wikipedia.org/wiki/Aperture_(typography)) and display-oriented close letter spacing limit legibility onscreen and aren’t suitable for comfortable reading at text sizes.

Issues associated with the uniformity of the letters in Neue Helvetica e.g. no visible difference between upper-case 'i' and lower-case ‘L’ could only be remedied by using another font but legibility can be improved by using the regular weight as the default. 

n.b. The full set of glyphs included with Helvetica are required for the Collections.

# Line height issues using Neue Helvetica
Web Font Anti-Pattern: using local fonts: https://www.bramstein.com/writing/web-font-anti-patterns-local-fonts.html

Comparison screengrabs between Light and Regular https://zpl.io/29GweJy

**Comment by pollecuttn** [comment]
https://github.com/wellcomecollection/wellcomecollection.org/issues/6119
