### ISSUE TITLE
Requesting: User flow for requesting an item

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#6537]
# What is it and who's it for?

When a researcher finds a work of interest, they need to be able to request physical items so that they can view them in the library.

# User stories
As a library member 
I want to request a physical item 
so that I can view it in the library as part of my research

As a library member 
I need to know how many items I can request 
so that I can plan my research time efficiently

As a library member 
I want to know what the process is for viewing an item 
so I can plan ahead for my library visit

As a library member 
I want to know how long a request might take to be available for pickup 
so I can better plan my library visit

## Acceptance criteria

- [ ] Users can request a physical item (from closed stores) that's available
- [ ] Users know they need to login in order to make a request
- [ ] Users understand that they need to book a ticket to visit the library

**Comment by DominiqueMarshall** [comment]
Initial design prototype for the requesting flow: [Invision requesting prototype](https://dominiquemarshall6595.invisionapp.com/console/share/2U2M041L9R/639088306)

**Comment by DominiqueMarshall** [comment]
Various design ideas for the library members sign-in button/link are viewable in Zeplin. Need to discuss which version to move forward: [Requesting - member sign in](https://zpl.io/bJ87qLD)

**Comment by DominiqueMarshall** [comment]
@gestchild @davidpmccormick  Zeplin designs to take forward:

- [Mobile menu](https://zpl.io/2pRkGlj)
- [Collections page](https://zpl.io/25zABlr)
- [Works page (member needs to sign in)](https://zpl.io/adKNJop)
- [Works page (member signed in)](https://zpl.io/VxpwZWw)
- What the sign in link could look like [with an icon](https://zpl.io/VqznqrN)

FYI I tried changing the full-width background bar to a shorter tab style. Considering the other banners that show up on the site, trying a different style might be a good way to approach this if we can!

**Comment by DominiqueMarshall** [comment]
Latest requesting flow designs:

[Modal 1](https://zpl.io/ag1G6eQ) (after a logged-in member clicks the 'request item' button)
- Need to confirm the 'NeededBy Date' field, is this functionality possible within the modal and what calendar input style is best?

[Modal 2](https://zpl.io/VKBNypA) (request confirmed screen)

**Comment by pollecuttn** [comment]
@DominiqueMarshall awaiting reply from David L re needed by date
