### ISSUE TITLE
Priority 1 accessibility issue: Show hide functionality not operable

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6551]
**What**

The behaviour of components with show/ hide functionality could not be programmatically determined in order for this behaviour to be presented to users by assistive technologies.

There are sections of content with Show/ Hide functionality. However, neither the expandable behaviour of the control nor its expanded or collapsed state are programmatically determinable in order that they could be presented to users by assistive technologies as the aria-expanded attribute has not been utilised. The newly triggered content is inserted into the DOM prior to the triggering component, meaning that screen reader users will not encounter this content as they proceed through the page. There is nothing to programmatically associate the collapsible region with the correspond control so that this relationship may be presented to users.

The button label changes visually but label changes are not automatically relayed to screen reader uses. Additionally, when the label changes to the close button, no text alternative is included for the icon which is hidden from assistive technology meaning that the button no longer has an accessible name.

<img width="523" alt="Screenshot 2021-05-27 at 14 48 03" src="https://user-images.githubusercontent.com/7315126/119837485-8d7fda80-befa-11eb-98cd-7c9962673292.png">

Code ref:

<img width="523" alt="Screenshot 2021-05-27 at 14 48 35" src="https://user-images.githubusercontent.com/7315126/119837581-a092aa80-befa-11eb-9ee0-2a59f28d80aa.png">

Solution

Ensure that the state of a component may be programmatically determined through the mark-up so that it can be presented to the user by assistive technologies. An aria-expanded attribute may be used to act as both an indication that the component has the property that it is expandable, as well as an indication of the expanded/ collapsed state.
Ensure that focus remains on the button and that the new content is inserted immediately after it within the DOM to ensure that it is the next area encountered in both the tab order and screen-reader reading order.
Please include some visually hidden text when the button changes to a close button, so that the component has an accessible name that may be presented to screen reader users and by which the element may be referenced by voice activation users.

Example
<img width="523" alt="Screenshot 2021-05-27 at 14 49 13" src="https://user-images.githubusercontent.com/7315126/119837656-b607d480-befa-11eb-99cf-71459be75b2d.png">

**Where**

URL: https://wellcomecollection.org/articles/XYofFREAACQAp-Vl
Page: Meet the climate emergency | Wellcome Collection
Journey 1 – Step 9
Additional location(s): https://wellcomecollection.org/articles/YBMARRMAACEAk26C https://wellcomecollection.org/pages/Wuw2MSIAACtd3Stq

**Comment by gestchild** [comment]
Fixed by #6597
