### ISSUE TITLE
Copyright not Evaluated addition to license options

### ISSUE THREAD

**Issue by cmhenshaw** [wellcomecollection/wellcomecollection.org#6594]
Need to add text to the website for a new copyright status - "Copyright not Evaluated" https://rightsstatements.org/page/CNE/1.0/?language=en

**Comment by jennpb** [comment]
@cmhenshaw @dannybirchall Do you know if this was done at all? Where on the website would this have been added?

**Comment by dannybirchall** [comment]
I don't think so, and I don't know where -- don't think we have a prismic-controlled list of (c) stati

**Comment by jennpb** [comment]
@dannybirchall Didn't think so. I'll take you off this issue - thanks for the confirm!

**Comment by cmhenshaw** [comment]
We were going to use this as one of our copyright options to display in the viewer - but it wasn't prioritised, so it just fell off the radar. I need to remind myself what we were going to use this for, exactly...

**Comment by jennpb** [comment]
No longer needed
