### ISSUE TITLE
Prismic custom types need updating in code

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6633]
References #6610

- [x] The articles, books, events and exhibitions custom types in code are missing the parents field, but they are present in Prismic
- [x] The books custom type in code doesn't match that in Prismic (specifically the contentList customTypes value)
- [x] The series custom type name and format values in code don't match those in Prismic

**Comment by davidpmccormick** [comment]
I believe I'm seeing more discrepancies in the `books` and `series` models than listed above, so I'm not going to touch those just yet.
