### ISSUE TITLE
Requesting: Mapping the messaging from the library to members

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6639]
**What is the problem to solve?**
Understanding what points of contact we have with library members

**What stage of research is it? (discovery/general usability testing/post release)**
Discovery

**What are the objectives?**
To create a map with view to a service blue print

**What are the assumptions?**

**What research technique is required?**
Interviewing library staff

**Optimal number of participants**

**Acceptance criteria**

**Deadline for results/dependencies:**

**Comment by alicerichmond** [comment]
Emailed the library comms staff to get assistance in knowing when and how members are messaged and what the contents of those messages are

**Comment by pollecuttn** [comment]
Awaiting user testing results
