### ISSUE TITLE
InfoBox padding

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6643]
## What
Current implementation of the [infoBox](https://cardigan.wellcomecollection.org/?path=/docs/components-infobox--basic) needs more padding. Should be 32px.

[Spacing shown on Zeplin](https://zpl.io/2pREM6y)

![Infobox padding](https://user-images.githubusercontent.com/36885440/123643198-0d5fd400-d81c-11eb-8a0f-39bc70d4a029.png)

**Comment by pollecuttn** [comment]
@GarethOrmerod Can you add to this, or delete it if it's not needed, please.
