### ISSUE TITLE
Replace individual cards from latest serial with index cards for last 6 serials on /stories

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#6647]
# What is it and who's it for?
The /stories page currently lists the six cards from the most recent serial, manually updated by a developer, normally when requested by someone in the content team.

Each of our serials has an index page, and in order to keep some older content fresh for longer, we could link to e.g. the last six of these, rather than the individual items from the most recent serial.

This should also be automated at this point so the content team aren't reliant on a developer for updates.

# User story
As a _reader of stories_

I need/want/expect _a depth of content to be readily available_

So that _I can read something that interests me_

# Implementation
Create a card that contains serial overview information and links to the index.

## Acceptance criteria
- Stories page displays six most recent serial cards.
- Heading for the section on the /stories page describing what serials are?

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Do page views for older serials increase?

**Comment by alexwlchan** [comment]
Closing in favour of #8398.
