### ISSUE TITLE
Support IIIF clickthrough auth for digitised audio

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#6654]
We now have examples of digitised audio that are open with advisory, so require the same IIIF clickthrough authentication that we use for other open with advisory items.

Eg:

https://wellcomecollection.org/works/kt2sb8mf

We already have an inline version of the advisory modal that's used for video, so let's reuse that for the audio player too.

**Comment by gestchild** [comment]
[This item doesn't appear to have a digital location](https://api.wellcomecollection.org/catalogue/v2/works/kt2sb8mf?include=identifiers,images,items,subjects,genres,contributors,production,notes,parts,partOf,precededBy,succeededBy,holdings), do we have another example?

**Comment by jtweed** [comment]
The merging rules have changed slightly since I created this ticket. The correct work is now:

https://wellcomecollection.org/works/utuneh9t
