### ISSUE TITLE
Collections Search Results UI display quirks - Arrow control & Select

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6656]
## What

- Arrow control is displaying in `pewter` , correct colour: #007868
- Select menu label not vertically aligned, looks to be slightly lower than it should be

[Reference on Zeplin](https://zpl.io/2jqze9A)

![QA_Search Result filters](https://user-images.githubusercontent.com/36885440/122952889-342e8e00-d376-11eb-9fa3-d7fa59a9a6cc.png)

**Comment by davidpmccormick** [comment]
These quirks are now resolved to  @GarethOrmerod's satisfaction.
