### ISSUE TITLE
Line break on contributors in search results and work header in Safari

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6671]
**What**
In Safari, there is an odd line break in the contributors.

<img width="444" alt="Screenshot 2021-06-22 at 12 00 49" src="https://user-images.githubusercontent.com/1446072/123230043-c3e75000-d4ce-11eb-9d89-63f99cb5b966.png">

https://wellcomecollection.org/works?query=francis%20fish

You can see the issue in the first result above, but it's not there in the second result.

**Where**

Safari. This couldn't be reproduced in Chrome or Firefox.

I don't have Safari so can't check, but I'm assuming this is happening in:
- search results
- work header

More info: https://wellcome.slack.com/archives/C8X9YKM5X/p1624358353008900

**Comment by davidpmccormick** [comment]
I think this is probably a WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=217136

There's an explanation of the issue [here](https://github.com/rsms/inter/issues/321#issuecomment-701576648).

I think there are some things we _could_ do to fix it, but sounds like it might be solved in a nightly build of Safari so (hopefully) the problem will go away with the next Safari release. Not sure if it is worth us putting in a slight hack for it or waiting till it fixes itself. I guess it depends on how bad it can end up looking on screen, and how frequently it occurs.

**Comment by pollecuttn** [comment]
Looks like the next Safari release is [July 2021](https://en.wikipedia.org/wiki/Safari_(web_browser)) so let's check back later that month.

I'll close this for now and we can re-open if we need to do anything else.

**Comment by pollecuttn** [comment]
@davidpmccormick I don't have Safari so can you please check if this is still an issue.

**Comment by davidpmccormick** [comment]
Just checked and this is not an issue in Safari 14.1.1
