### ISSUE TITLE
Requesting: Alternative designs for items table

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#6695]
**Problem to solve**
Based on the level of data now available for items and after a discussion at design review (24 June), the current table design no longer feels fit for purpose, especially on mobile where a lot of scrolling is needed to find the 'request item' button, and for works that have a large number of items (e.g. [The Lancet](https://wellcomecollection.org/works/m3a4d359)).

**Objective:**
Consider alternatives to the table design that can: 
- Make the data easy to scan and digest across different work types on desktop and mobile
- Visually work well for the varying levels of data available across items

**Comment by DominiqueMarshall** [comment]
Zeplin links below for alternative design options. 

**Desktop:**
- Full-width table: https://zpl.io/VqzMPJ4
- List style: https://zpl.io/VOL3qGr
- Open shelves list: https://zpl.io/bLq3mAY
- List style on archives: https://zpl.io/aMw38g3


**Mobile designs**
- Version 1 (card style): https://zpl.io/VOL3qll
- Alternative for the above: https://zpl.io/bLq3mZ6
- Card style (no data labels): https://zpl.io/aBv39XQ
- List style v1: https://zpl.io/bWG3Wl7
- List style (no data labels): https://zpl.io/blOnvQe

The first bit of feedback from Gareth O, Alice and Jonathan - the list style feels like the right approach to move away from the table design.

Need to consider the pros and cons of showing or hiding the labels (location, status, access etc), but to start with they should be included.

**Comment by DominiqueMarshall** [comment]
@gestchild @davidpmccormick Zeplin links are on this ticket as well :)

**Comment by pollecuttn** [comment]
Design review:
- add item note under title
- add access note
- take out structured 'to' field and append to terms where appropriate
