### ISSUE TITLE
Selected colour filter is oval on mobile

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#6707]
**What**

The selected colour filter in image search is getting squashed from a circle into an oval on mobile Safari. Doesn't happen in desktop Safari.

**Where**

![colours filters](https://user-images.githubusercontent.com/42490/124287594-1b796180-db48-11eb-81df-9a77a43908af.jpg)

**Comment by jtweed** [comment]
Cannot reproduce

**Comment by davidpmccormick** [comment]
Was possibly fixed by #6722
