### ISSUE TITLE
Long tags break layout on mobile

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#6712]
**What**

When contributors, subjects or genres are very long, the tag component does not wrap and the page layout breaks on mobile. Tags should wrap onto multiple lines if they are wider than the available width on the page.

**Where**

Contributors:

- https://wellcomecollection.org/works/hm5hrdp5
- https://wellcomecollection.org/works/zqv5kzfb
- https://wellcomecollection.org/works/g5guxheb

Subjects:

- https://wellcomecollection.org/works/c4amh69j
- https://wellcomecollection.org/works/dyt36xwt
- https://wellcomecollection.org/works/g5guxheb

Screenshot:

![file](https://user-images.githubusercontent.com/42490/124307261-79fe0a00-db5f-11eb-8191-8bc155ee47f9.jpeg)

**Comment by DominiqueMarshall** [comment]
@davidpmccormick @gestchild To improve this bug, I would aim for the tags to not go any wider than the dividers we currently use on the works pages (the same max-width that the text and buttons already meet). As long as there are no weird word breaks, the flow of tags should still look consistent.

<img width="513" alt="Screenshot 2021-10-06 at 15 56 16" src="https://user-images.githubusercontent.com/60890140/136229104-dca1ee6d-8a98-4799-ac55-f62c873a82e7.png">



**BEFORE** (the tags run past the divider line)
<img width="528" alt="Screenshot 2021-10-06 at 17 04 54" src="https://user-images.githubusercontent.com/60890140/136241435-313bfe08-8690-42d9-ab17-a0557b9a76bc.png">



**AFTER** (the text wraps before it can break the page)

<img width="592" alt="Screenshot 2021-10-06 at 17 06 41" src="https://user-images.githubusercontent.com/60890140/136241644-53493ad0-6688-49e4-b937-a2e6175487d2.png">
