### ISSUE TITLE
Requesting: Library membership registration form & auth0 pages

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#6746]
### What is it and who's it for?
When a researcher wants to request items, if they're not already a library member they need to go through the registration process. Currently, this involves an online pre-registration phase, then on their first visit to the library, they need to fill in an application form (which library staff then input into Sierra manually) and show two forms of ID before their membership is confirmed.

The ideal scenario (that would help to streamline the process), is to give researchers the opportunity to fill in the whole form online (with the data fields matching the paper forms), reducing the need for library staff to enter their details manually during that first visit.

### User stories
As a non-library member
I want to create an account
so that I can request materials to see on my library visit

#### Long form initial design: 
https://zpl.io/25z0qZW
https://zpl.io/agmDZjZ

#### Multi-step form
https://zpl.io/bWGWq9j
https://zpl.io/blOvjWD
https://zpl.io/V0rWqxm
https://zpl.io/VK7nmr6

**Comment by DominiqueMarshall** [comment]
@alicerichmond @gestchild @jtweed Invision prototype links below for if you want to reference them next week:

[library membership sign in, forgot password and requesting](https://dominiquemarshall6595.invisionapp.com/console/share/PJ2TCV1ZGE)

[Membership application](https://dominiquemarshall6595.invisionapp.com/console/share/3C2TCV1F5W/703203223)

**Comment by jtweed** [comment]
Ace, thanks @DominiqueMarshall !
