### ISSUE TITLE
Queries for popular items view

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6773]
**What is the problem to solve?**
What are people searching for when they view 
- https://wellcomecollection.org/works/fuc864rh
- https://wellcomecollection.org/works/mg56yqa4

**What stage of research is it? (discovery/general usability testing/post release)**
discovery

**What are the objectives?**
- Identify common search behaviour that might benefit from a filter
- Identify odd matches to queries for improvements to search

**What are the assumptions?**
- that the views are by different users

**What research technique is required?**
Python

**Comment by taceybadgerbrook** [comment]
**Investigating views of https://wellcomecollection.org/works/fuc864rh**

Looking at 100,000 observations 28/6 - 1/7, 39 anonymousIds submitted the query, 'art of science' in image search and then used the red filter. No one tried any other filter (this is the first colour) or selected any other (the photo of the flask is the first result.) It's a pretty spectacular photo but still seems strange no one viewed anything else.

**Comment by taceybadgerbrook** [comment]
Investigating views of https://wellcomecollection.org/works/mg56yqa4

Code that worked for above returns only views and no searches. Is it possible to view a work without querying it (eg via Internet Archive) or is there something wrong with the code?

Pull request for review:
https://github.com/wellcomecollection/data-science/pull/86

**Comment by taceybadgerbrook** [comment]
Yes it is possible for users to click on a link on a site like wikipedia and fetch up at the item page. I checked Google Search Console and it seems that this is exactly what viewers of https://wellcomecollection.org/works/mg56yqa4 did. Case closed.

@harrisonpim if you could review the [pull request](wellcomecollection/data-science#86), I'll close this ticket.

**Comment by harrisonpim** [comment]
sorry tacey! will get on that now
