### ISSUE TITLE
Performance monitoring approaches

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#6783]
This ticket is to track progress across various approaches to performance monitoring. We think these are something like the following in terms of effort/benefit:
![image](https://user-images.githubusercontent.com/4429247/125300966-6f433200-e322-11eb-85f8-d442bd2b25c4.png)

- [x] Bundle size diffs
- [ ] Lighthouse reports
- [ ] Elastic APM RUM
- [ ] e2e stress/latency tests
- [ ] API stress/latency tests
- [ ] Distributed tracing
- [ ] ES query profiling
- [ ] Improved visibility of existing tracing

**Comment by jennpb** [comment]
@jamieparkinson Is this something we want to keep open?

**Comment by jamieparkinson** [comment]
I think this can be closed!
