### ISSUE TITLE
Evaluation of online requesting service

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6787]
**We want to know if the following change has improved the user experience**
Online requesting

**Definition of success is**
- Ability to request items online 
- Ability to ~~obtain library membership~~ sign in as a library member online

**We'll know if we're succeeding if we measure the following metric and this happens**
High percentage of:-

1. Successful requests/holds collected
2. ~~Membership applications/confirmed memberships~~ 
  Successful library member logins
~~3. Item now being held email/holds collected~~

**Definition of failure is**
Users unable to complete journey ending in picking up holds
Users unable to log into library accounts

**We'll know if we're failing if we measure the following metric and this happens**
Large numbers of:-

1. Users trying to log in but not getting to library account page
2. Users not understanding they need to confirm request
3. Requests/holds not collected without deleting requests

**Comment by taceybadgerbrook** [comment]
@DominiqueMarshall is this user journey still current? From discussions with @davidpmccormick ages ago, my understanding was that there would be no screen that announces to the user that their request has been successful. How will users know they are finished?

**Comment by DominiqueMarshall** [comment]
When a user makes a request, there should be a confirmation screen to tell them that it's been successful. Not having that confirmation message wouldn't make sense as, like you said, they wouldn't know whether the request has gone through or not. The last design I did for that is on [zeplin here](https://zpl.io/VOLPkOQ)

**Comment by taceybadgerbrook** [comment]
Fab. Thank you!

**Comment by taceybadgerbrook** [comment]
@DominiqueMarshall success "funnel" duly updated.

**Comment by taceybadgerbrook** [comment]
[Notion page ](https://www.notion.so/wellcometrust/Library-Request-and-Registration-messaging-eff07d7fa5e342288b3c765fc048a02d)documenting requesting and registration

**Comment by taceybadgerbrook** [comment]
**Conversion metrics required:**

1. User applies for library membership (pre-registration)
2. Pre-registration confirmed
3. Full library membership confirmed
4. User logs in successfully
5. User requests item
6. Request confirmed
7. Request successful 
8. Item unavailable
9. Email sent, "Item ready for collection"
10. User collects request
11. Overdue notice

**Comment by DominiqueMarshall** [comment]
An important thing to note on this, with "> 9. Email sent, "Item ready for collection", this currently doesn't happen and is out of scope for now. They only know an item is available to collect if they check their library account or contact the library team to ask about it.

**Comment by taceybadgerbrook** [comment]
@DominiqueMarshall thanks for this. I am going to amend the metrics required with this in mind. Also @alicerichmond, as we do not want to aim to increase library membership, the metrics are going to start at 4.

**Comment by taceybadgerbrook** [comment]
Error messaging could definitely be included although a funnel works better if it is sequential. Numbers of error messages could still be tracked as separate metrics. 

Here's a mock up of the Data Studio report: 
![image](https://user-images.githubusercontent.com/32418070/136969138-c66e0dca-d86a-4773-971b-f293040c199e.png)

**Comment by taceybadgerbrook** [comment]
**Events that can be monitored by tagging as GA Event Category/Action/Label or by GA page view:**
- request item (button click on works page)
- confirm request (button click on modal)
- book ticket (button click on modal)
- view library account (link click on different pages) 
- sign in (button on sign in page)
- send password reset (button on reset-password page)

**Comment by taceybadgerbrook** [comment]
Evaluation

|Question|Metrics|
|:--|:--|
|How many people are requesting items?|count of userId when request item button clicked|
|How many people are requesting items who are already library members?|sign in button on works page, create new account page|

**Comment by taceybadgerbrook** [comment]
Evaluating login/account

|Question|Metrics (in bold) and data (italics indicate data not included in above listing)|
|:--|:--|
|How many people are logging in initially (using header link) vs. being driven from works pages?|**Number of sign ins**: Kibana dashboard metric and time series - 1) view library account button after search (maybe source:works page?) and 2) view library account button after search (maybe source:non-works page?) |
|How is having login functionality / requesting increasing the number of memberships requested?|Kibana metric and time series: total number of new memberships, source:works page, cardinality by userId|
What errors are people encountering and where are they struggling in the journey?
How many people are trying to cancel items they have reserved?
How often are people logging into their accounts?
