### ISSUE TITLE
Colour palette refresh

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6795]
# What is it and who's it for?

# User story
As a _(who? user/persona)_

I need/want/expect _(what? to do this thing)_

So that _(why? accomplish a goal/get a benefit)_

# Implementation 

## Testing and tracking
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by alexwlchan** [comment]
Closing as done – we rolled out the new colour palette last year.
