### ISSUE TITLE
Conversion metric for requesting

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#6802]
We would like to measure the journey of someone requesting an item. To do this, we will need to have a conversion metric when someone successfully makes a request.

This is separate from [internal reporting on requesting](https://github.com/wellcomecollection/wellcomecollection.org/issues/6469).

**Comment by taceybadgerbrook** [comment]
Metrics required are in ticket https://github.com/wellcomecollection/wellcomecollection.org/issues/6787. These requirements are based on the user journey set out in [Notion](https://www.notion.so/wellcometrust/Library-Request-and-Registration-messaging-eff07d7fa5e342288b3c765fc048a02d).

@alicerichmond @DominiqueMarshall, could you add anything I've missed?

**Comment by taceybadgerbrook** [comment]
@jamesgorrie metrics have been [revised in this ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/6787#issuecomment-883322749) to include when user pre-registers for a library account and depending on whether online registration in place, confirmation of library account.

**Comment by jamesgorrie** [comment]
Closing in favour of that ticket then
