### ISSUE TITLE
Auth0 login screens

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6805]
Update the Auth0 template and customise the text to match the following designs in Zeplin:

## Login
  Zeplin:
    Large: [https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eeab64fce9adaf01d88693](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eeab64fce9adaf01d88693)
    Small: [https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eeab6309c0da107eb984f3](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eeab6309c0da107eb984f3)
  Auth0 names:
    prompt: login
    screen: login
## Forgotten password
  Zeplin: [https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e7de60890cfefb5297](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e7de60890cfefb5297)
  Auth0 names:
    prompt: reset-password
    screen: reset-password-request
## Forgotten password submitted
  Zeplin:[ https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e8861fc2adeb1ee481]( https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e8861fc2adeb1ee481)
  Auth0 names:
    prompt: reset-password
    screen: reset-password-email
## Reset password
  Zeplin: [https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e9e13adaadfeedbaab](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e9e13adaadfeedbaab)
  Auth0 names:
    prompt: reset-password
    screen: reset-password
## Reset password confirmed
  Zeplin: [https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e899d1260cf2ef0482](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e899d1260cf2ef0482)
  Auth0 names:
    prompt: reset-password
    screen: reset-password-success
## Email verified
  Zeplin: [https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e740cf730eccfa80ba](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/60eff5e740cf730eccfa80ba)
  Auth0 names:
    prompt: email-verification
    screen: email-verification-result

**Comment by gestchild** [comment]
## Login

![login_large](https://user-images.githubusercontent.com/6051896/126357982-c94eec19-2b7f-43c5-9f47-95d1baa3f87e.gif)

## Forgotten password
 
![forgotten_password](https://user-images.githubusercontent.com/6051896/126358002-c38af0c5-ceb3-4277-8109-9ec688917c83.gif)

## Forgotten password submitted
  
![forgotten_password_submitted](https://user-images.githubusercontent.com/6051896/126358019-aa8c8d55-00d2-4604-9e03-43ac987fda38.gif)

## Reset password
 
![reset_password](https://user-images.githubusercontent.com/6051896/126358040-72856c8c-994f-4c16-bc90-213ab8c0cdb3.gif)

## Reset password confirmed
![password_reset_confirmed](https://user-images.githubusercontent.com/6051896/126358062-7dfde0ba-1889-4d47-868f-c96531a36ac2.gif)

## Email verified

**Comment by gestchild** [comment]
@DominiqueMarshall I've got the screens as close to the designs as I can, there are a few things that are difficult to change and we've hit some character limits on the text we can add. Can we have a chat through this next week please?

**Comment by DominiqueMarshall** [comment]
@gestchild on the **Reset password confirmed** screen, can there be a button that takes them to the sign-in page so it's not a dead end?

**Comment by gestchild** [comment]
> @gestchild on the **Reset password confirmed** screen, can there be a button that takes them to the sign-in page so it's not a dead end?

I'll have a look
