### ISSUE TITLE
Seasons hero image aspect ratio

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#6819]
# What
We currently use 16:9 as a standard aspect ratio (alongside 1:1 for square crops) for all images on the site. On a `season` page where the hero image sits above the the title, the information below is being pushed too far down.

**Example:**
<img width="1526" alt="Screenshot 2021-07-22 at 15 20 45" src="https://user-images.githubusercontent.com/36885440/126674254-25b88155-d08d-4951-9967-0bba369db389.png">

The original concept [designs on Zeplin](url) used a wider crop (18:9) to mitigate this
<img width="1539" alt="Screenshot 2021-07-22 at 15 54 29" src="https://user-images.githubusercontent.com/36885440/126674479-40fafb3e-12da-4676-a684-430ce80491f8.png">

**Comment by davidpmccormick** [comment]
We have a `32:15` crop for Prismic images which is close to `18:9`. We could introduce this as e.g. a `superWidescreenImage` for this purpose.
