### ISSUE TITLE
Open with advisory downloads

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6840]
**What**
If a digitised item has an open with advisory access condition e.g. [https://wellcomecollection.org/works/vx7exex2](https://wellcomecollection.org/works/vx7exex2), there is still a download link available on the work page.
Clicking the link results in an error, as there is no way to click a consent message before viewing.

**Where**
<img width="368" alt="Screenshot 2021-07-28 at 09 59 39" src="https://user-images.githubusercontent.com/6051896/127299246-36938e60-d91f-4dd2-94ea-837e5c8eba7e.png">

<img width="289" alt="Screenshot 2021-07-28 at 09 59 10" src="https://user-images.githubusercontent.com/6051896/127299374-ca6ee8b2-e9cd-4ad4-a610-4a5a511bc3ef.png">

**Comment by gestchild** [comment]
I've put in a fix for the problem to stop users from getting an error, but it means the download is not available on the work page, for this type of item. @DominiqueMarshall, do you think this is ok or do we need to come up with something else long term?

**Comment by DominiqueMarshall** [comment]
We probably do wanna have another look at this long term to consider options, but I think for now it makes sense for the download button to not be available on the works page if they need to consent first
