### ISSUE TITLE
Search tabs moving as page loads

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6841]
**What**
Due to work on [improving the accessibility of the search tabs
](https://github.com/wellcomecollection/wellcomecollection.org/pull/6790), we now have a situation where the images tab initially loads below the collections form, until javascript kicks in (which we want to prevent). 

**Where**
<img width="1221" alt="Screenshot 2021-07-28 at 09 49 08" src="https://user-images.githubusercontent.com/6051896/127303392-86d38193-6b35-4bc1-b26e-fb2a78901bae.png">

<img width="1208" alt="Screenshot 2021-07-28 at 09 49 16" src="https://user-images.githubusercontent.com/6051896/127303408-70f5b18b-771d-4932-bb3d-db2190bfdb55.png">

**Comment by pollecuttn** [comment]
Reported at https://wellcome.slack.com/archives/C8X9YKM5X/p1627458649172600
