### ISSUE TITLE
Digital guides: add a hotjar feedback widget to the digital guide pages

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6850]
**What is the problem to solve?**
We need to understand what our visitors think about our digital guides and the QR code process in the gallery. 

**What stage of research is it? (discovery/general usability testing/post release)**
Usability testing/content

**What are the objectives?**
Are visitors enjoying the content?
Are visitors enjoying the way in which they are interacting with the guides e.g. QR codes

**What are the assumptions?**
QR codes may be problematic for users
Low uptake may indicate that visitors are not enjoying the content

**What research technique is required?**
Hot jar widget on the digital guides page for those who interacted with the QR codes

**Optimal number of participants**

**Acceptance criteria**

**Deadline for results/dependencies:**

**Comment by alicerichmond** [comment]
Currently a survey running on all pages of the site for the marketing team so we have to pause to prevent overload

**Comment by cbowskill** [comment]
@alicerichmond - I just spotted your comment about a survey running back in August. Is that now ok / not an issue and we are ok to proceed with this? (sorry, not sure how I didn't spot this!)

**Comment by gestchild** [comment]
@alicerichmond do you have a list of the digital guide pages we want hotjar added to?

**Comment by taceybadgerbrook** [comment]
@gestchild I believe @alicerichmond wanted the homepage (wellcomecollection.org/pages/YLCu9hEAACYAUiJx) and the first page (wellcomecollection.org/pages/YLCzexEAACMAUi41).

**Comment by gestchild** [comment]
Thank you @taceybadgerbrook

**Comment by cbowskill** [comment]
Question: Is the hotjar survey turned on separately to the heat-mapping element? Having seen the associated survey set up in HotJar there's a typo in it and it would be worth reviewing those.

If they're not independent, let's hold off on this until Alice is back on Monday and can address those.

**Comment by taceybadgerbrook** [comment]
Yes, they are independent.

**Comment by cbowskill** [comment]
@alicerichmond - this looks to be live but there's a missing word in the first question still. "Did you use a QR code access this digital guide?" should be "Did you use a QR code to access the digital guide". Can you review/amend and check you're happy with the rest of the set up? (it also looks to be live across all digital guides pages - is this expected?). Finally, do you have a view on how long you'll be leaving this running?
