### ISSUE TITLE
Exhibition engagement metrics

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6852]
**What is the problem to solve?**
How engaged are museum visitors?

**What stage of research is it? (discovery/general usability testing/post release)**
post release

**What are the objectives?**
Create funnel for QR code usage:
- user numbers for exhibition page view
- clicks to book ticket on wc.org
- tickets actually booked online
- visitor numbers
- QR code usage

**What are the assumptions?**
Period 15 - 27 July chosen to avoid counting press visitors

**What research technique is required?**
GA, EventBrite, people counters

**Comment by taceybadgerbrook** [comment]
@alicerichmond Ideally, I'd like to track the same cohort through the funnel but given the unknown time lag between booking online and actually visiting, can we agree to analyse this by total events within the period 15-27/7 as opposed to daily?

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @gestchild Historically we have tracked ticket bookings in GA by Event Action=booking-tickets:click. It doesn't look like this event gets fired when I go to covid-book-your-ticket and click on "check for tickets."

**Comment by taceybadgerbrook** [comment]
@alicerichmond 
Am waiting on Andrew for Eventbrite and on-the-door ticket stats for period 15-27/7.

@jamesgorrie 
Trying to use tracking for clicks on, "check tickets" button on /covid-welcome-back

**Comment by taceybadgerbrook** [comment]
@jamesgorrie can you share the GA link in Github? It doesn't seem to work in Slack.

**Comment by taceybadgerbrook** [comment]
My mistake. I'm after the action when a user is on /covid-book-you-ticket and clicks on the button, "Check for tickets." We usually track bookings by event_category: component, event_action:booking-tickets:click but this doesn't seem to be tracking this event.

**Comment by taceybadgerbrook** [comment]
Summary data for period 17-27 July:

6% of page views result in clicks to book tickets
on average 5 tickets booked per click
on average 31% no shows for online bookings
18% of people who visit don't book their ticket online
18% of visitors use the QR codes 
27% of users who use the QR code view the homepage of the digital guide
10% of users who use the QR code view the first page of the digital guide
7% of users who use the QR code view the last page of the digital guide

The data and analysis summary can be found here:
https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Q4%20202021/6852%20Exhibition%20engagement%20metrics.xlsx?d=wc08c35a6492d4acfba0b0df1e551f8bc&csf=1&web=1&e=belQYP

**Comment by taceybadgerbrook** [comment]
Things to consider when running future QR code campaigns:
- name the campaign according to the room for more accurate tracking against people counters
- monitor dates of posting and removal of QR codes

**Comment by pollecuttn** [comment]
@taceybadgerbrook can this be closed now?

**Comment by taceybadgerbrook** [comment]
And do users of the QR codes go on to view other pages? Below is a summary of the pages viewed by QR code users for 15-27 July. It doesn't look like they make much use of the website after gaining access. This is consistent with analysis of later periods, too.
![image](https://user-images.githubusercontent.com/32418070/139707259-9a4b04f7-f370-4f7f-baf2-1195e3bb926f.png)
