### ISSUE TITLE
Users who arrive at /works from Google 

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6880]
**What is the problem to solve?**
Are we serving these users as well as we might?

**What stage of research is it? (discovery/general usability testing/post release)**
discovery

**What are the objectives?**
Find % who just view vs view and search
Find average time spent on search

**What are the assumptions?**
These users are professional researchers or hobbyists. We should be making the most of their visit

**What research technique is required?**
Jupyter notebook

**Comment by kenoir** [comment]
What's an item view?

**Comment by taceybadgerbrook** [comment]
It’s when users are view the actual item page without conducting a search, viewing search results or works pages.

During investigation of null searches, I saw large numbers of item views without searches or works page views. This ticket is to investigate whether these users leave immediately or stay and use the item.

From: Robert Kenny ***@***.***>
Reply to: "wellcomecollection/wellcomecollection.org" ***@***.***>
Date: Thursday, 9 September 2021 at 10:50
To: "wellcomecollection/wellcomecollection.org" ***@***.***>
Cc: Tacey Laurie ***@***.***>, Assign ***@***.***>
Subject: Re: [wellcomecollection/wellcomecollection.org] Users who Google and land on an item view (#6880)


What's an item view?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwellcomecollection%2Fwellcomecollection.org%2Fissues%2F6880%23issuecomment-915935285&data=04%7C01%7Ct.laurie%40wellcome.org%7C4515c37aaccc456cfb8508d973774d2e%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637667778525470595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mTwlw84pD3YtGlxP2eGjRmU05UoP%2FTC%2BDtbMH%2BwhuBM%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHXKSFUDFE3DBIPL4QGRZPDUBB7PNANCNFSM5B3VBUBQ&data=04%7C01%7Ct.laurie%40wellcome.org%7C4515c37aaccc456cfb8508d973774d2e%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637667778525480554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p%2FcE2WDzL4xSZhVjf37Rj3lECg9EXsWELMY%2FTugJVeg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ct.laurie%40wellcome.org%7C4515c37aaccc456cfb8508d973774d2e%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637667778525480554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bW4CHYdPgt3kPDXVnRCx%2B1fBl9UFXNzLSl4z8MJRGh0%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ct.laurie%40wellcome.org%7C4515c37aaccc456cfb8508d973774d2e%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637667778525480554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sqyWnH5v%2BSOhSqXG5OTEZOy2iKHAbmf4fP2kx6M0Q4o%3D&reserved=0>.

**Comment by taceybadgerbrook** [comment]
# 2 examples of how people come direct to /works: #

## 1. Google search: "further observations on the variolae vaccine Edward Jenner" ##

Clicked on workid rwjcqke4
Site displays works page
left site without further action
Shows up as 2 identical events:
page.name=work
[page.query.id](http://page.query.id/): rwjcqke4

![further obs vv edward jenner](https://user-images.githubusercontent.com/32418070/159470843-f5c27edb-5c29-43d3-949c-395633d56d19.jpg)

## 2. Google search "Edward jenner wellcomecollection" ##

Clicked on search result "Edward jenner catalogue search"
Site displays search results page
left site without further action
Shows up as 2 identical events:
page.name=works
page.query.query: “EDWARD JENNER”
properties.totalResults:notnull

![edward jenner wellcomecollection](https://user-images.githubusercontent.com/32418070/159470929-003b63c1-effa-4f12-9f1b-252f0ba96275.jpg)

**Comment by taceybadgerbrook** [comment]
100,000 most recent observations were analysed to evaluate the percentages of users arriving at wellcomecollection.org/works or /work pages after using Google. The results of the Python code are summarised below:

||All users|Profile 1: users who begin the session on a /works page|Profile 2: users who begin the session on the search results page|
|:--|:-------|:--|:--|
|Counts|14,536|11,171|1,128|
|Percentage of users of total|100%|77%|8%|
|Average session length|2min 19sec|6min 50sec|40min 5sec|

**Comment by taceybadgerbrook** [comment]
In order for an organic search to result in a /works page, users would need to enter very specific search terms which positively identify one work. While the criteria used to identify these events in the data is quite specific, it is impossible to distinguish these from searches generated by tabs left open in browsers on startup. Previous analysis has shown that a fairly large percentage of researchers who use the collection on a regular basis keep tabs open in their browsers. The high percentage of Profile 1. users and longer than average session length appear to confirm this.

**Comment by taceybadgerbrook** [comment]
https://github.com/wellcomecollection/data-science/pull/110

**Comment by taceybadgerbrook** [comment]
67% of all site users come from organic search
![acquisition (all users)](https://user-images.githubusercontent.com/32418070/160874718-da9b23d5-07ce-4b62-a834-70b20cff62b3.jpg)

whereas 79% of users who view collections pages come from organic search ![acquisition (works and searches)](https://user-images.githubusercontent.com/32418070/160874925-90a3f72a-4295-40b5-a040-0fb7d851285c.jpg)

The average bounce rate for all users is 17%. For collection users, the bounce rate is much higher at 22%. So it appears that while a higher percentage of collection users come from organic search, they also bounce more frequently.
