### ISSUE TITLE
Works image modal shows html tags

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6893]
**What**

Works image modal shows html tags instead of e.g. making the text italic

![image](https://user-images.githubusercontent.com/1446072/129016142-7653eea4-2485-45ec-affe-f450bc5fe674.png)

Reported at https://wellcome.slack.com/archives/C8X9YKM5X/p1628672164055700

**Where**

Image modal for images e.g. https://wellcomecollection.org/images?query=wqcyhvp6 

This is not a problem on the related [work page](https://wellcomecollection.org/works/wqcyhvp6) or [item viewer info panel](https://wellcomecollection.org/works/wqcyhvp6/images?id=xp22fdpg)

## To do

- [ ] Render rather than display html tags in the image modal

**Comment by pollecuttn** [comment]
@davidpmccormick I'm not seeing any change in the image modal - has this been deployed yet?

**Comment by davidpmccormick** [comment]
Deploying now.
