### ISSUE TITLE
Error messages from requesting api

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#6916]
# What is it and who's it for?

Displaying informative error messages to people using the requesting service.

The requesting service API can respond with an error under several circumstances. At present we just tell the user that the request failed and ask then to try again.

<img width="664" alt="Screenshot 2021-08-18 at 11 55 33" src="https://user-images.githubusercontent.com/6051896/129886388-1903e30a-e890-4e92-886d-39127230c782.png">

The [possible errors can be found here](https://docs.v1-api.account.wellcomecollection.org/#/User/post_users__userId__item_requests)

Should we be displaying the specific error message returned from the API and, if so, are they descriptive enough or do we want to change the message?

For example, a 403 error which occurs when the provided API key or bearer token does not permit access to the resource method has the message 'Forbidden'.

**Comment by DominiqueMarshall** [comment]
Probably worth changing the messaging where we can to make them more descriptive.

Is there a list of messages that the errors will show, like the 'Forbidden' one? I couldn't see them in the link above.

**Comment by gestchild** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors

**Comment by alexwlchan** [comment]
These are the errors you'd be most likely to see in normal use:

* "You are at your account limit and you cannot request more items"
* "Item $itemNumber is on hold for another reader"
* "You cannot request $itemNumber"

**Comment by cbowskill** [comment]
@DominiqueMarshall  - can you look at the most commonly seen ones of these (cc @alexwlchan for current list)

**Comment by alexwlchan** [comment]
Okay, these are the current messages you'd be likely to see:

Item a222wwjt is on hold for another reader
You are at your account limit and you cannot request more items
You cannot request a222wwjt

(There are other errors, but if we show them to users something has gone extremely wrong.)

**Comment by DominiqueMarshall** [comment]
I would consider editing the first one:
_Item a222wwjt is on hold for another reader_ - should "reader" be "library member" seeing as we have more items than just books?

**Comment by cbowskill** [comment]
We currently use "Item is in use by another reader" when we show a note against an item that can't be requested. So if we change it, we should change how we refer to "readers" elsewhere in the journey.

My only other thoughts are just around the formality of the language use (e.g. cannot) - again, I'm not clear what our approach or style is on these.

**Comment by alexwlchan** [comment]
So am I changing it, or leaving as-is?

**Comment by cbowskill** [comment]
Change please as per Dom's suggestion 'reader' > 'library member'

Formality i've asked for a steer from Danny.

**Comment by cbowskill** [comment]
Also confirmed, can we change instances of 'cannot' in these to 'can't'

So these 3 errors become:
Item a222wwjt is on hold for another library member
You're at your account limit and you can't request more items
You can't request a222wwjt

**Comment by alexwlchan** [comment]
Done, deployed.

**Comment by alexwlchan** [comment]
Okay, so this is deployed in the API, but we still need to pull through the messages in the front end – which should fix https://github.com/wellcomecollection/wellcomecollection.org/issues/7451

**Comment by alexwlchan** [comment]
This is the relevant component: https://github.com/wellcomecollection/wellcomecollection.org/blob/f075c49e435e4211a4be5a7dd842ed9d21edf886/catalogue/webapp/components/ItemRequestModal/ItemRequestModal.tsx#L387-L400
