### ISSUE TITLE
Front-end Identity tests should run in CI

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#6926]
For: https://github.com/wellcomecollection/platform/issues/4811

Make sure we've got reliable tests for long-term project health and ease of development!

Consists of:

- [x] https://github.com/wellcomecollection/wellcomecollection.org/pull/7008
- [x] Fix the tests:
  - https://github.com/wellcomecollection/wellcomecollection.org/pull/7013
  - https://github.com/wellcomecollection/wellcomecollection.org/pull/7012

**Comment by kenoir** [comment]
Closing as done.
