### ISSUE TITLE
Problems with @weco/common

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#6927]
### _[wip]_
Here is an outline of some of the issues with the `@weco/common` package:

- There is stuff in `@weco/common` which is only used in 1 consumer app - these things should be extracted.
- React, Next.JS, etc are dependencies - not peerDependencies. This means we get duplicate reacts in our dependency trees and makes coupling very brittle
- ~Circular dependency between @weco/common and @weco/catalogue~

**Comment by jennpb** [comment]
@jamieparkinson I'm taking the exec decision to close this

**Comment by rcantin-w** [comment]
> There is stuff in @weco/common which is only used in 1 consumer app - these things should be extracted.
tbf this should be addressed by the work @AMBacelar is doing currently in #10164 

> React, Next.JS, etc are dependencies - not peerDependencies. This means we get duplicate reacts in our dependency trees and makes coupling very brittle 
this might be interesting to figure out, I remember talking with you @jamieparkinson about why everything was in dependencies vs devDependencies. Quick chat about it might be interesting?
