### ISSUE TITLE
Fix an HTTP 500 error on https://wellcomecollection.org/works/aka2xr8s/items

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#6933]
**What**
Go to the page. 💥 

**Where**
https://wellcomecollection.org/works/aka2xr8s/items

**Comment by pollecuttn** [comment]
Reported on Slack: https://wellcome.slack.com/archives/C8X9YKM5X/p1629302540086700

**Comment by alexwlchan** [comment]
Having poked around a bit at this, it looks like the issue is in the IIIF Presentation manifest: https://iiif.wellcomecollection.org/presentation/v2/b28117694

We expect there to be something at `structures.canvases`, but none of the objects under `structures` have a `canvases` key. I'm not sure if that's an issue on the DLCS side, or something legitimate our code needs to handle.

**Comment by pollecuttn** [comment]
@davidpmccormick You closed this yesterday but the error on https://wellcomecollection.org/works/aka2xr8s/items is still there. What's needed to fix the error still?

**Comment by davidpmccormick** [comment]
Needs to be deployed but we rolled back. Will be fixed when we deploy again.

**Comment by davidpmccormick** [comment]
This has been re-deployed now.

**Comment by pollecuttn** [comment]
Thanks!
