### ISSUE TITLE
Investigation of cookieless analytics

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#6936]
To comply Privacy and Electronic Communications Regulation [(PECR)](https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/how-do-we-comply-with-the-cookie-rules/),  the website will need to ask for consent if we "store, or gain access to information stored, on user devices."

Not all users will opt out but to capture page views for users who do, we will need to set up a new GA property for account 55614 with storage disabled.

**Comment by taceybadgerbrook** [comment]
@jamesgorrie @gestchild @davidpmccormick This will mean setting up a new property where we change storage to none in the create command. [Here is a link on this.](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies) 

I think this means we can run 2 properties, ensuring the existing GA property keeps capturing behaviour for those who opt in. Is this right?

**Comment by taceybadgerbrook** [comment]
Different ways to run cookieless GA:

1. Set up new GA Account using the same settings as the existing one which uses analytics.js. Disable analytics.js from setting cookies by setting the storage field to 'none'.
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies

2. Set up new GA Account that uses Global Site Tag (gtag.) Disable client side cookie storage
`gtag('config', TRACKING_ID, { client_storage: 'none', anonymize_ip: true })`
https://goenning.net/2021/02/01/cookieless-google-analytics/

Change Consent settings to dynamically change according to opt in/out choice. Marketing uses Google Ads on this account, so need to change ad_storage, too. Using Consent settings allows Google Ads to continue to collect ad conversion metrics.  
```
gtag('consent', 'default', {
  'ad_storage': 'denied',
  'analytics_storage': 'denied'
});
```
https://developers.google.com/tag-platform/devguides/consent

3. To note: the version of GA that we currently use is no longer being updated because of their new product Google Analytics 4. To disable first party cookies in GA4:
https://developers.google.com/analytics/devguides/collection/ga4/disable-analytics

**Comment by taceybadgerbrook** [comment]
@davidpmccormick feel free to edit this:

**What is the problem to solve?**
Prepare for drop in data being collected by GA once cookie banner deployed

**What stage of research is it? (discovery/general usability testing/post release)**
Discovery

**What are the objectives?**
Investigate what kind of GA data gets collected without storing clientIds
Find out if feasible to use cookieless GA data to impute data lost because of opting out

**What are the assumptions?**
User behaviour re pages viewed and time viewing is the same between opt-ins and opt-outs
New GA Property can be used when users given choice of opting out

**What work is required?**
Create new GA Property with storage:none 

**Acceptance criteria**
Existing and new GA Properties can co-exist 
If new Property collects page views and events, then can be used to impute missing data

**Deadline for results/dependencies:**
Investigation of data to be done before tracking needed when cookie banner deployed

**Comment by taceybadgerbrook** [comment]
**What is the problem to solve?**
Can we collect data without using cookies or generating a clientId?

**What stage of research is it? (discovery/general usability testing/post release)**
Discovery

**What are the objectives?**
- find out how to set up a GA Property with storage:none
- check whether it generates a clientId
- see what kind of data gets collected 
- decide whether to set this to collect data for all users or just for those who opt out of cookies once new banner set up

**What are the assumptions?**
- GA will tolerate 2 Properties covering the same account areas
- Users behave similarly on the site whether or not they opt in or out of cookies

**What research technique is required?**
Having a noodle!

**Acceptance criteria**
If the new Property is able to collect data without creating a clientId, we can use this to impute user numbers lost to the current GA Property due to opting out of cookies

**Comment by cbowskill** [comment]
should we split this into 2 separate issues? A discovery ticket (e.g. figuring out what we want to do / how we want to do it) and then an implementation ticket? I think it would be good to make sure we've done enough exploration/digging to be clear on what we're doing/how we're doing it/any implications before implementing anything that could cause us unforeseen issues.

**Comment by taceybadgerbrook** [comment]
[Discovery ticket for cookieless GA](https://github.com/wellcomecollection/wellcomecollection.org/issues/7265).

**Comment by taceybadgerbrook** [comment]
[Implementation ticket for cookieless GA.](https://github.com/wellcomecollection/wellcomecollection.org/issues/7267)

**Comment by davidpmccormick** [comment]
Can this be closed now the other tickets have been split out from it?
