### ISSUE TITLE
Reset password screen copy

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6949]
**What**

<img width="485" alt="Screenshot 2021-08-24 at 11 28 51" src="https://user-images.githubusercontent.com/1446072/130797383-96602b58-e4d9-4576-bcff-21cd1b1c873b.png">

Replace: 
- [ ] "lower case" with "lowercase"
- [ ] "upper case" with "uppercase"

Need consistency for: 
- [ ] sequence of requirements

**Where**

Reset password screen

https://wellcome.slack.com/archives/CUA669WHH/p1629800941163000

**Comment by davidpmccormick** [comment]
The currently built version of this screen is some way off the version in Zeplin, tracked in #6972. Should we close this and track everything in that ticket?

**Comment by pollecuttn** [comment]
@davidpmccormick seems like a good idea
