### ISSUE TITLE
Updating email confirmation: spacing on the (i) looks wrong

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6950]
**What**

Improve spacing around (i)

<img width="980" alt="Screenshot 2021-08-24 at 11 30 43" src="https://user-images.githubusercontent.com/1446072/130798182-8522f079-b7b3-4699-8c50-ce9823da47f8.png">

**Where**

Email update confirmation

https://wellcome.slack.com/archives/CUA669WHH/p1629801052163900

**Comment by davidpmccormick** [comment]
This is likely because these styles use the `gap` property in conjunction with `flexbox` which has only very recently been added to Safari. In any event, `flexbox` with `gap` isn't how we've approached spacing systematically elsewhere, so we should update these syles.
