### ISSUE TITLE
Updating email address confirmation email copy: do not use "the Wellcome Collection"

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6951]
**What**

The confirmation email has "the Wellcome Collection". It should be "Wellcome Collection", without the definite article.

**Where**

On the email received after updating email address.

https://wellcome.slack.com/archives/CUA669WHH/p1629801243164900?thread_ts=1629801230.164600&cid=CUA669WHH

**Comment by davidpmccormick** [comment]
The subject for this email is editable in the Auth0 management console. But it doesn't look like I have sufficient permissions to edit it for the stage tenant.

![image](https://user-images.githubusercontent.com/1394592/134675187-59771d3a-3e64-4017-9310-b61da3040556.png)
