### ISSUE TITLE
Updating email address gave a 'Failed to verify email' screen but had updated email address

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#6952]
**What**

This is the screen I got after updating my email address – but I did then get the “Welcome to the Wellcome Collection” email

<img width="1038" alt="Screenshot 2021-08-24 at 11 33 28" src="https://user-images.githubusercontent.com/1446072/130799620-9726812b-8706-4bea-affe-67d544a0ef9e.png">

**Where**

https://wellcome.slack.com/archives/CUA669WHH/p1629801230164600

**Comment by jamieparkinson** [comment]
@alexwlchan I can't reproduce this now - can you still? if so will require a bit of digging

**Comment by alexwlchan** [comment]
1. Log in to https://wellcomecollection.org/?toggle=enableRequesting
2. Sign in with my wellcome.org username and password in the Auth0 login screen
3. Get returned to the Wellcome Collection homepage
4. Using the profile menu in the top right-hand corner, select "Library account". This takes me to https://wellcomecollection.org/account
5. Click the button "Change email", see the modal dialog
6. Enter my wellcome.ac.uk email address and password
7. Click "Update email". The modal spins for a few moments, then I'm returned to my account page with "Email updated"

    <img width="856" alt="Screenshot 2021-09-24 at 10 27 30" src="https://user-images.githubusercontent.com/301220/134652118-33ded2ee-5465-43dd-a91c-029814d4def2.png">

8. I get an email telling me to "Verify your email address". I click the link using Mail.app on macOS:

    <img width="764" alt="Screenshot 2021-09-24 at 10 28 39" src="https://user-images.githubusercontent.com/301220/134652225-9aa863ec-293b-4bf6-9d9d-1895c252f69d.png">

9. That opens a web page where I see this error message:

    <img width="856" alt="Screenshot 2021-09-24 at 10 28 47" src="https://user-images.githubusercontent.com/301220/134652246-482fc835-72fa-4870-a447-b67c815ad5b6.png">

**Comment by alexwlchan** [comment]
Aha! I wonder if Mail.app is doing something funky here, possibly preloading the URL? If I close Mail.app and open the email from the Outlook Web App, I get the correct behaviour.

**Comment by jamieparkinson** [comment]
That sounds likely - I think the correct solution here is to edit the copy; it's not a failure but rather the email is already verified. We could reference this but to be honest I'd just make the case that the link has already been used identical to the success case. Pinging @DominiqueMarshall for advice!

**Comment by DominiqueMarshall** [comment]
If the address has been verified already, the messaging could be tweaked to say something like:

**Heading:** Email address already verified
**Text:** This link has already been used to verify this email address.
**Button:** Sign in

If you need help, please contact the library team.

**Comment by gestchild** [comment]
In the scenario Alex describes, where it's the mail app possibly causing the failure by preloading the link, wouldn't this messaging be confusing for the user. Since they only clicked the link once and are then told it's already verfiied.

I'm thinking making it the same as the success case, as Jamie suggests, might be better?

**Comment by DominiqueMarshall** [comment]
Sorry, I misunderstood the use case! 🤦🏽‍♀️
