### ISSUE TITLE
Account page design issues

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#6971]
- [x] Buttons are too large and should have bolded text
- [x] Item requests table should handle long titles appropriately (max width on column + text wrapping)
- [x] ~Item requests table should differentiate between work and item titles~ - show item title below work title
- [x] Button spacing on mobile is incorrect
- [x] ~Insufficient spacing below title on modals~ - moved to #6972

**Comment by DominiqueMarshall** [comment]
Item requests table with work title text wrapping examples:

- Iteration 1: https://zpl.io/ag5e1z0
- Iteration 2 (includes work + item titles. An indication of what the page would look like when you have a mixture of items with and without titles): https://zpl.io/a77lpOR

cc @jtweed

**Comment by jtweed** [comment]
I'd rather not make a distinction between the work and item title, as this is going to be suboptimal when there's a mix of items with and without titles. Can we go for something more like iteration 1, where we just have a single title column?

Then we could possibly put the item title underneath the work title, where it exists? I don't think it would necessarily have to link, as we don't make individual physical items addressable.

Do we display the item title in the requesintg modal? If so, I'd be after commonality with that, where we presumably would do something similar.

**Comment by jtweed** [comment]
Perfect, thanks 👍

**Comment by DominiqueMarshall** [comment]
Buttons on the account page should be as seen here: https://zpl.io/ag5e1z0

Mobile button spacing: https://zpl.io/V0NMBZm
