### ISSUE TITLE
Account modals (change password and email) do not match designs

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#6972]
**Designs:**
https://zpl.io/bWy9ld1
https://zpl.io/aMXz6l7

![image](https://user-images.githubusercontent.com/4429247/131122100-eaf48392-143a-44e1-93e5-3bdd2332110b.png)

vs

![image](https://user-images.githubusercontent.com/4429247/131122161-1599de02-c810-4385-846f-a7587b7def4d.png)

- [ ] Insufficient spacing below title on modals - from #6971

**Comment by davidpmccormick** [comment]
I don't think we currently have styles for something like this:

![image](https://user-images.githubusercontent.com/1394592/134348412-98a48246-4c19-4342-bd99-7eaa84232447.png)

I think those are provided on the Auth0-hosted version of these screens. Is it important that we create something similar? If so, we'd have to think about what it actually _is_ (perhaps just a one-off for a list of password validation rules? I dunno).

We can (and probably should) make the inputs look more like our `TextInput` component, but the label behaviour for our `TextInput`s is slightly different from the Auth0 inputs. Also, our shown/hidden eye icons are different – we could live with this, or create more eye icons to match the Auth0 versions closer.
