### ISSUE TITLE
Requesting: Ticket booking info incorrect

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6977]
**What**

The language in the ticket booking modal is incorrect, 

- You no longer need to book a time slot, the ticket is all day 
- The ticket does not need to be booked 72 hours in advance, it should be by 10am the day before your visit

**Where**

The secong modal window that appears when making a request

**Comment by DominiqueMarshall** [comment]
Updated modal text: https://zpl.io/anvOnyO

<img width="1294" alt="Screenshot 2021-08-31 at 08 48 33" src="https://user-images.githubusercontent.com/60890140/131463937-15adee10-5b25-4535-87e7-1989d4b51289.png">

**Comment by pollecuttn** [comment]
Please correct this wording in the modal:
(Rare Materials Room, 2nd Floor) to be (Rare Materials Room, 3rd Floor)
