### ISSUE TITLE
Requesting: All items are being delivered to the rare materials room

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6978]
**What**

In the current designs for account pages, the table of requests in the account area shows that items can be collected from both the rare materials room and the library enquiries desk. 

All items should be collected in the rare materials room

**Where**

Account page

**Comment by gestchild** [comment]
@jtweed is this the one you said needs the underlying data corrected, rather than us trying to compensate on the front end?

**Comment by jtweed** [comment]
Yes, I'd rather build this based on the underlying data rather than constantly in flux, temporary rules that haven't been properly reflected in Sierra. So my vote is to leave this as is. It's exactly the same as OPAC and Encore.
