### ISSUE TITLE
Requesting: Confirmation modal wording

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#6992]
**What**

The second modal that appears when confirming a request states that the rare materials room is on the second floor, it is actually on " Level 2"

**Where**

Confirmation modal on requesting journey

**Comment by DominiqueMarshall** [comment]
Modal text update below:

It will be available to pick up from the library (Rare Materials Room, level 3) for two weeks.

**Before your visit:** you will need to book a 'Rare Materials Room – all day entry ticket' by 10am the day before you wish to visit.
