### ISSUE TITLE
Thumbnail on works page hasn't updated following re-ingest

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#7000]
**What**

The image in the viewer is correct. There should only be one image. The thumbnail [on the works page] with the road sign is wrong and it shouldn't say 2 images to view anymore.

https://wellcome.slack.com/archives/C8X9YKM5X/p1630505086001100

**Where**

https://wellcomecollection.org/works/tr3vxwgx

**To do**
- [ ] Get the correct thumbnail on the works page
- [ ] Selected images from this work - 'View 2 images' shouldn't be on the works page

**Comment by alexwlchan** [comment]
This was fixed by a recent reindex.
