### ISSUE TITLE
Content in Discussion component breaking out of closed state

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#7031]
**What**
The Discussion component isn't quite covering all of the content that should be hidden before the 'show more' button is pressed. This is more/less noticeable depending on how wide the browser is and where the lines wrap.

**Where**
https://wellcomecollection.org/articles/YRU4ExEAAFTsyFIH
<img width="828" alt="Screenshot 2021-09-10 at 10 52 38" src="https://user-images.githubusercontent.com/1394592/132836651-7534590d-4817-46d1-99a6-63eb69b765da.png">

**Comment by pollecuttn** [comment]
Similar to https://github.com/wellcomecollection/wellcomecollection.org/issues/6993 ? Although this is more about things not being hidden, whereas #6993 is more about things being hidden that shouldn't be.
