### ISSUE TITLE
Why did the stories/articles pages suddenly get slower?

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#7052]

**Comment by jamesgorrie** [comment]
@jamieparkinson do you have some dates / graphs showing where this happened?

**Comment by jamieparkinson** [comment]
This was due to the switch to Prismic CDN, which we can't do a lot about - https://github.com/wellcomecollection/wellcomecollection.org/pull/7071 should give us more insight into where things are taking a long time server-side
