### ISSUE TITLE
Requesting: Text changes etc

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7091]
- [x] **When you click 'Forgot password?' on the sign-in screen**, the link at the bottom still says 'Back to account management system'. Can that say 'Back to sign in' instead?
- [x] **Account page 'change email' modal:** the first label should be more explicit and say 'new email address'
- [x] **Item request progress bar and text** - update the text to match the visual cue:
<img width="500" alt="Screenshot 2021-09-29 at 11 03 04" src="https://user-images.githubusercontent.com/60890140/135250614-47ad5da5-1b42-40c9-a6ae-869d382957e6.png">

- [x] **Small text tweak for the requesting modals.** Rather than it saying 12/15 **items** remaining (as it is below), change it to 12/15 **requests** remaining

BEFORE
<img width="275" alt="Screenshot 2021-09-29 at 11 12 24" src="https://user-images.githubusercontent.com/60890140/135251289-4a0d2237-399c-41c1-a178-d47d8a136682.png">

AFTER
<img width="314" alt="Screenshot 2021-09-29 at 11 26 41" src="https://user-images.githubusercontent.com/60890140/135251463-e51439d5-16a6-466f-b996-33bd1bc888ff.png">

- [x] **Second request modal:** the end of the first sentence needs to change to say "one week" rather than two weeks. TBC @alicerichmond 

<img width="854" alt="Screenshot 2021-09-29 at 11 28 24" src="https://user-images.githubusercontent.com/60890140/135251701-0a1089c7-a20e-46a4-b135-648c7df76675.png">

- [x] **Where to find it slice:** Access status and method column widths need extending so the wording is on one line:
<img width="500" alt="Screenshot 2021-09-29 at 10 53 12" src="https://user-images.githubusercontent.com/60890140/135250868-f827ec31-e387-4364-8f10-89beee288f09.png">

**Comment by davidpmccormick** [comment]
First point in [this pr](https://github.com/wellcomecollection/identity/pull/187)
