### ISSUE TITLE
Digitised books - URL should link directly to a specific volume & page

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7102]
**What**
There appears to be a bug whereby when copying a URL of a specific volume & page, that the URL will take you back to the page in the 1st volume (regardless as to whether you were in the 2nd, 3rd, 4th volume etc.)

**Where**
See initial report/example here: https://wellcome.slack.com/archives/C8X9YKM5X/p1632845006052000

For example, viewing page 139 on volume 7, the URL: https://wellcomecollection.org/works/m4exs8m8/items?canvas=139 takes you to page 139 in volume 1.

**Comment by alexwlchan** [comment]
I think I've cracked this, will PR in a bit.

**Comment by alexwlchan** [comment]
Okay, so these are the lines that cause the issue: https://github.com/wellcomecollection/wellcomecollection.org/blob/7ac6c3cd600cf4c5235caf98ae0d2d1f8a4c3c2b/catalogue/webapp/components/IIIFViewer/IIIFViewer.tsx#L383-L405

For some reason, `mainPaginatorProps.link.as` only has the `canvas` query parameter. I could copy across all the URL parameters in that block, but I can't work out where `link.as` is being populated – ideally we'd fix it at source.
