### ISSUE TITLE
Identify IIIF Presentation manifests that are 404'ing

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#7109]
Why is this 500ing?
https://wellcomecollection.org/works/u9engmcv/items

**Comment by alexwlchan** [comment]
Here's the stack trace from around the time we saw this error:

```
"GET /works/xd7g3b6f/download?sierraId=b28122185 HTTP/1.1" 500 37381 "-" "Amazon CloudFront"
FetchError: invalid json response body at https://iiif.wellcomecollection.org/presentation/v2/b28122185 reason: Unexpected token N in JSON at position 0
at /app/node_modules/node-fetch/lib/index.js:272:32
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async getServerSideProps (/app/catalogue/webapp/.next/server/pages/download.js:149:36)
at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:428:24)
at async doRender (/app/node_modules/next/dist/server/next-server.js:1144:38)
at async /app/node_modules/next/dist/server/next-server.js:1236:28
at async /app/node_modules/next/dist/server/response-cache.js:64:36 {
type: 'invalid-json'
}
```

If I try to load `https://iiif.wellcomecollection.org/presentation/v2/b28122185`, I get a 404 and the following text:

```
No IIIF resource found for v2/b28122185
```

**Comment by alexwlchan** [comment]
Note that u9engmcv now points at https://iiif.wellcomecollection.org/presentation/v2/b21497916

But if you look for b28122185, you land on https://wellcomecollection.org/works/xd7g3b6f, where the page is 500'ing.

**Comment by alexwlchan** [comment]
I'm going to have a quick look at how many IIIF Presentation manifests we're pointing to that 404.

**Comment by alexwlchan** [comment]
"quick" ~ well a script is running to poll them all, might take another day or so.

**Comment by alexwlchan** [comment]
BTW, I think a 500 error is appropriate here – we shouldn't be showing a link to a IIIF manifest we aren't able to serve.

**Comment by alexwlchan** [comment]
I've made a list of the 2598 IIIF Presentation manifests we link to in the API but return a 404 for:

[errors.txt](https://github.com/wellcomecollection/wellcomecollection.org/files/7292259/errors.txt)

In at least some cases, it looks like the e-bib associated with the Sierra record has been suppressed, which would explain why it's not available/hasn't been run through DLCS.

This might be an issue:

* in the data (we should unsuppress the e-bib and run the item through DLCS), or
* with the pipeline (we shouldn’t be attaching a METS file if the e-bib is suppressed)

I'm going to check with Ashley.

**Comment by alexwlchan** [comment]
I've opened https://github.com/wellcomecollection/platform/issues/5323, which is a follow-on discussion about restricted IIIF resources.

**Comment by alexwlchan** [comment]
My latest example seems to be working and I don't think we've had issues here for a while, so closing as done. If the issue recurs we can open a new ticket.
