### ISSUE TITLE
Requesting: Load time - Performance

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7118]
**What**
Throughout the requesting journey there are noticeable delays in items loading. 

Not only does this cause disruption in the user journey from a load time perspective but the experience whilst loading is also different throughout the journey (loading bar on login prompt, ... on text fields/button space, pause icon on account page).

We need to:
1. Explore the opportunity to reduce load time
2. Review the experience and at least make this smoother/more aligned across the journeys (Issue: #7120 )

_**Note:** Have been testing on mac / home wi-fi. Will need to check mobile performance._

**Where**
Key locations I've noticed this (low/medium/high in terms of load times)

- After signing in - the login prompt on an item [medium] - loading as a loading bar
- After signing in - the access field/button on an item [high]- loading as previous text status and ...
- After signing in - account page [high] - loading as || icon
- After requesting - on confirmation overlay [high] - loading as || icon
- After requesting an item - the change in note [high] - loading as previous text status
- After signing in - the 'you're logged in' area in header [high] - no indication, showing as blank until loaded in

**Related to**
#7120

**Comment by jamesgorrie** [comment]
As a point here, I think we should implement loading states as well as work on the performance as slow loading times can often be a product of someone's context.

e.g. if someone is on an intermittent connection on a train, good loading times will help, but having load / retry steps would ensure that we are letting people know what's going on.

**Comment by cbowskill** [comment]
@jamesgorrie i think that's a really valid point. Also for scenarios/instances where auth0 may be unresponsive (e.g. what i encountered last week)

@DominiqueMarshall @GarethOrmerod  - could you take a look at the loading states and how they could be improved across the journey?

**Comment by jamieparkinson** [comment]
No performance budgets set yet but we should do so.

As an aside I think some of these are good places for "optimistic UI updates" ([eg](https://simonhearne.com/2021/optimistic-ui-patterns/)) where rather than having a loading state, we change the UI as if the slow action was successful and only roll it back if there's an error.

**Comment by cbowskill** [comment]
They're great examples and show how important those loading states are.
Will steal your link and pop it in the issue so no one misses it in the comments :)

On another note, I'll separate into 2 tickets. One performance focused (this one - #7118, one UI/UX focused for easier tracking - #7120

**Comment by cbowskill** [comment]
@jamieparkinson - are you happy for this to be closed or are there any residual performance issues to resolve?
