### ISSUE TITLE
Change email flow mixed up with membership flow

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#7142]
### Problem

When a user changes their email address from the account page, this puts them into the same email verification flow that happens during new account creation.

* They are redirected to a page that talks about verifying their account.
* The link in the verification email takes them to a confirmation that says they have confirmed their account.
* They get an email verified email that says the library team will confirm their membership within 72 hrs.
* They get a welcome email that thanks them for applying for a membership and repeats the 72 hrs, plus asks them to bring in ID.

I don't think we can go live with this, it's potentially far too confusing for existing members who change their email address.

### Suggestion

We should change the Auth0 email verification templates back to being just that - things that only mention verifying your email address, removing all mentions of library membership and not send the new member email.

We should treat new membership emails, including information about membership approval, as a separate problem that gets looked at as part of the membership work.

**Comment by jamieparkinson** [comment]
After some discussion in Slack: https://wellcome.slack.com/archives/CUA669WHH/p1635945645083300

Auth0's transactional emails have fixed behaviour: 
- a verification request email is sent after an account is created or its email address changes
- a welcome email is sent after an email is verified

The result of this is that (a) verification emails are the same for existing and new users and (b) welcome emails are sent after a user changes their email address. This is the cause of the 'mixed up' flow. 

As described in the Auth0 documentation (for [verification emails](https://auth0.com/docs/brand-and-customize/email/manage-email-flow#send-verification-email-with-rules) and [welcome emails](https://auth0.com/docs/brand-and-customize/email/manage-email-flow#send-welcome-email-using-your-own-api)), this behaviour can be changed by "outsourcing" the transactional emails to an external API, by storing state regarding whether emails have been sent in the user's metadata object, and then by using this state/API with business logic inside a [rule](https://auth0.com/docs/rules) that is triggered by verification events.

Implementing this would involve (at least) the following:
- Writing a custom rule based on the above examples and managing its deployment and state through a combination of scripts and Terraform
- Adding an endpoint to the identity API that would trigger the sending of a 'custom' welcome email.
- Working out the permissions (probably a separate API key) for the API to be callable by the custom rule and not to be exposed to other API consumers.
- Moving the welcome email templates (+ deployment) out of Auth0 into the existing templating framework of the identity API.

I think this is quite a lot of work, and quite a lot of disparate pieces to maintain - I'm strongly of the opinion that we shouldn't do this work right now, and instead we should look for copy changes we can make to cover the small minority of users who'll be affected by this. We may wish to return to this as we look to improve sign-up/onboarding journeys.

**Comment by davidpmccormick** [comment]
@cbowskill Did you mention this was ready to be worked on? Where can we find the updated email copy?

**Comment by cbowskill** [comment]
In discussions with Dom, my understanding is requesting won't change the current new member flow and therefore there shouldn't be anyone receiving a new auth0 version of new member email until we look at membership? (correct me if i'm wrong). Therefore we're happy to just have the same email for now which just covers confirmation of verifying your account (which is the verified email version that Dom has provided above)

**Comment by cbowskill** [comment]
Received a: 'Verify your email address' email, verified and then didn't receive a follow up email. Were we expecting to still see the follow up email just with the generic messaging? My understanding was this was sent by default (based on Jamie's comment) so i was expecting to see a secondary email once my new email address was verified.

With the email that was sent the wording is slightly different to what is specified in Dom's screens.

**Dom's screens:**

> Confirm` your email address by clicking the button below. This link will expire in 24 hours

**Email I received:**

>To activate your online account, please verify your email address below. This link will expire in 24 hours.

Related question - what happens if i don't activate my new email address within 24hrs? (I'll try it out)

@davidpmccormick - putting back into in progress

**Comment by davidpmccormick** [comment]
> My understanding was this was sent by default (based on Jamie's comment) so i was expecting to see a secondary email once my new email address was verified

That's true, but that default is the result of the 'welcome' email being sent. I turned off sending of the welcome email altogether, so you wouldn't get a follow-up.

I think I might have misinterpreted that piece of the requirement then – do we still want to send a follow-up email, but have it be Dom's 'Email verified' screen above?

I think that would mean turning the 'welcome' email back on, but replacing its contents with the 'Email verified' screen, which will be ok for as long as we're not accepting new memberships.

**Comment by cbowskill** [comment]
I would say we leave it on and use it as a verification for email address changed for now, unless @DominiqueMarshall disagrees.

**Comment by davidpmccormick** [comment]
looks like the automation to move things to done if a PR says it closes an issue is a thing. I'll move this back to ready for review

**Comment by cbowskill** [comment]
Looks good!
