### ISSUE TITLE
Account deletion should refer to membership

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#7143]
We need to revisit the account deletion functionality at the bottom of the account page.

This should be broadened out to make it clear that you're not deleting your account, but requesting that your library membership be closed.

We still need to confirm the rights words to use to describe this, including asking the library team how they refer to this currently.

**Comment by DominiqueMarshall** [comment]
Updated copy for the account page. This is more explicit about the action having an effect on both your membership AND your online account.


<img width="1178" alt="Screenshot 2021-10-14 at 15 49 10" src="https://user-images.githubusercontent.com/60890140/137341968-5debbdba-8183-48f5-90f6-4ab787474ec0.png">



Updated modal copy:

<img width="566" alt="Screenshot 2021-10-14 at 15 32 40" src="https://user-images.githubusercontent.com/60890140/137338721-c0a483fd-3f44-42d7-a8c3-c4479bbb59a8.png">


**Question: Is it clearer if the online account is referred to as being "closed" / "deleted" / "deactivated"?**
