### ISSUE TITLE
Requesting: Header shows as logged out but then auto-signs me in without needing my details

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7145]
**What**

There is a lack of clarity on how long an account is meant to remain logged in and how this is working.

From a user perspective:
- I've not logged in recently (around 24hrs-ish)
- When I visit wellcomecollection.org I'm shown a login prompt in the header (as though I'm signed out)
- When I click login I'm auto-redirected to the homepage with the header now showing me as logged in (despite not entering any details)

What is the expected behaviour here and why are we seeing this conflict between the UI treating me as though I'm logged out when it seems as though I am actually still logged in?

**Where**
-Header sign in messaging

**Comment by jamesgorrie** [comment]
Table for reference:

| Cookie       | Domain                         | Expiry         | Reason |
|--------------|--------------------------------|----------------|--------|
| koa.sess     | wellcomecollection.org         | 8 hours        |        |
| koa.sess.sig | wellcomecollection.org         | 8 hours        |        |
| auth0        | account.wellcomecollection.org | 8 hours        |        |
| auth0_compat | account.wellcomecollection.org | 8 hours        |        |
| did          | account.wellcomecollection.org | 1 year 6 hours |        |
| did_compat   | account.wellcomecollection.org | 1 year 6 hours |        |
