### ISSUE TITLE
Recommendations for an improved global navigation and footer

### ISSUE THREAD

**Issue by GarethOrmerod** [wellcomecollection/wellcomecollection.org#7149]
### **Global navigation**

> - The header is feeling quite cramped, if we went down the route of a mega dropdown can we use it to surface more timely info? e.g. latest exhibition, open/closed status etc. (clearly there are reasons to avoid mega dropdowns)
> - The footer - what’s it for? Should some of that info be in a mega dropdown (if we went that way)? Would we be better off trying to subdivide the content by audience?
> - Should the newsletter subscribe be part of the footer?
> - How does the cookie bar fit into all of this?
> - How should message bars fit it?

Looking at options for how we can better accommodate and contextualise the growing site content.

**Comment by jamesgorrie** [comment]
Have we ever thought about what stats we'd want from navigation? Not sure we collect many. For instance:
"How many people are using the main nav"

That way we might be able to see if we're making improvements?

**Comment by pollecuttn** [comment]
To be reviewed on Monday 29 November w/ Carla
