### ISSUE TITLE
Library account modals - Password manager & show password icons overlapping

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7154]
**What**
There's an inconsistency between the positioning of the 'show password' icon on the sign in page, and on the modals within the library account area. This is apparent when using a password manager - there's an overlap which makes it difficult to press one or the other (_I'm using Lastpass on Chrome_):

**Where**

Sign in page (_easy to select both icons_):
<img width="473" alt="Screen Shot 2021-10-12 at 15 03 18" src="https://user-images.githubusercontent.com/60890140/136971560-48f0ac2c-178c-47fa-9ca2-6559953f7850.png">

Library account modals (change email and change password modals):

<img width="527" alt="Screen Shot 2021-10-12 at 15 07 09" src="https://user-images.githubusercontent.com/60890140/136971702-e26e97bb-03c4-4b56-8177-7a95ad4ee011.png">

**Comment by cbowskill** [comment]
How big is a reasonably big refactor? If it's quite a substantial piece of work I wouldn't want to prioritise it over some of the other bugs already raised which effect a high proportion of users (this just impacts those users that are using this browser plugin).
