### ISSUE TITLE
Helping external users to use the API

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7190]
The Developers section contains resources for users who would like to search across the API. In theory, this reduces enquiries and encourages self serve. However, the daily snapshot is too big to open and there is no way of getting just a sample to investigate the kind of data it contains.

The Catalogue API would seem the most sensible tool for creating a sample for investigation but despite the information provided on the 22 query parameters and a schema, basic queries are problematic even for the technologically savvy user. A better understanding of how to use this tool would benefit both external users and internal non-developer staff.

**Comment by jennpb** [comment]
@harrisonpim Is this something that's been resolved in your work with Lewis?

**Comment by taceybadgerbrook** [comment]
@jennpb I don't know whether this was the project with Lewis but this issue has been beautifully addressed by Harrison with lots of examples in the developers section of the site.
