### ISSUE TITLE
Tidy up Prismic custom types

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#7203]
### links
need to work out how to make sure the types we can link to make some sort of sense

### parents & seasons
Should everything be able to have a parent and a season?

### Webcomics
Why are we still using webcomics? We should be using article with format = comic?

Webcomic series is also floating about...

https://github.com/wellcomecollection/wellcomecollection.org/issues/7227

### Installations
~Why are we using installations not exhibition with form = installation?~

~Probably worth following: https://github.com/wellcomecollection/wellcomecollection.org/issues/7227~

Removed as we stopped using them a while back.
https://github.com/wellcomecollection/wellcomecollection.org/pull/7268

## TODO

- [x] Make sure media controls are added to all custom types
- [x] type up HTML types in richtext

**Comment by gestchild** [comment]
The TItledTextList also had a requirement for "[An identifier which lets the user know if the resource is accessed online or in library](https://github.com/wellcomecollection/wellcomecollection.org/issues/6010#issuecomment-775104643)"

but that doesn't appear to be used.

**Comment by jamesgorrie** [comment]
@dannybirchall - it's the:
- `Titled text list` slice on [this page](https://wellcomecollection.org/pages/YDaP2BMAACUAT7DS) that needs editing. You can just create a `Text` slice and add links to the headings.
- `Table` slice on [this page](https://wellcomecollection.org/pages/YBGczxMAACAAjXFz). I'm not sure how we can format this better, maybe a list?
