### ISSUE TITLE
Requesting - Loading - QA comments/changes

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7222]
**What**
Having reviewed the work done so far by @jamieparkinson , list of further refinement we'd like to look at if possible:

- [x] **Loading bar on works pages** - Retain as prompt for login, however, due to new optimistic loading UI, remove blue loading bar to help keep consistent positioning of elements
- [x] **Confirmation within modal** - After requesting an item, re-instate the confirmation modal
- [x] **Item in use** - When an item is in use by self (or another user), the multiple calls mean the previous state/messaging can be seen quite obviously before the correct messaging loads in
- [x] **Items on account page** - No loading state for item requests on the account page causes layout change
- [ ] ~**Logged in header** - Still a large delay between account icon and initials appearing. Reduce down~

I think that's captured everything we discussed. If I missed anything please add @jamieparkinson @DominiqueMarshall

**Comment by jamieparkinson** [comment]
The last point above is superseded by https://github.com/wellcomecollection/wellcomecollection.org/issues/7229
