### ISSUE TITLE
Migrate the Webcomic type to be identical to Article in Prismic

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7227]
We have separate types for "Article" and "Webcomic" in Prismic, but the latter is deprecated. New content should be created as type "Article" with the image in the body and a format of "webcomic".

To reduce the amount of special-case code we need for the now-deprecated webcomic type, we should:

1. Add the fields from Article that are missing from Webcomic
2. Migrate the existing Webcomic articles (~160) into the Article-type fields
3. Set up Webcomic so it's an exact mirror of Article in our Prismic document type definitions
4. Modify the rendering code so it renders Webcomic as an Article

**Comment by jamesgorrie** [comment]
We can also just [disable it](https://prismic.io/docs/core-concepts/version-custom-types#disable) to avoid new ones being created. I think this functionality didn't exist when we shifted over.
