### ISSUE TITLE
`sc:Collection` does not always have manifests

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#7255]
**What**
We 500 when parsing IIIF data from a `sc:Collection` that contains `collections`.
 e.g: https://iiif.wellcomecollection.org/presentation/v2/b10930437

[We assume that any `sc:Collection` should have `manifests`](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/catalogue/webapp/pages/item.tsx#L431) - we're investigating is this is a fair assumption or something gone awry on the digitisation side.

**Where**
https://wellcomecollection.org/works/d6hxn24s/items

**Comment by paul-butcher** [comment]
@alexwlchan I suspect that this issue has expired, unless there are some other known examples where this problem occurs.

https://wellcomecollection.org/works/d6hxn24s/items now returns 410, not 500.

![Image](https://user-images.githubusercontent.com/64621/175257284-158f5106-061e-476f-a478-4a506802fded.png)


The collection in https://iiif.wellcomecollection.org/presentation/v2/b10930437 does have manifests
```
"collections": [
    {
      "@id": "https://iiif.wellcomecollection.org/presentation/v2/b10930437-copy-1",
      "@type": "sc:Collection",
      "label": "Copy 1",
      "within": "",
      "manifests": [
        {
          "@id": "https://iiif.wellcomecollection.org/presentation/v2/b10930437_0001",
          "@type": "sc:Manifest",
          "label": "Copy 1, Volume 1",
          "within": ""
        },...
```

**Comment by alexwlchan** [comment]
Sounds good, another ticket closed. :D
