### ISSUE TITLE
Requesting: User testing

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7260]
<<Placeholder for additional requesting user testing. @alicerichmond have you already got something raised for this that makes this defunct? I couldn't see anything >>

**What is the problem to solve?**

**What stage of research is it? (discovery/general usability testing/post release)**

**What are the objectives?**

**What are the assumptions?**

**What research technique is required?**

**Optimal number of participants**

**Acceptance criteria**

**Deadline for results/dependencies:**

**Comment by cbowskill** [comment]
Thoughts on how we move this forward:
- Find willing internal (or external) volunteers who are most removed from this functionality currently
- Sit in the library for an afternoon/day and try and get volunteers to sit with us and conduct some testing (logistics tbd!)

**Comment by pollecuttn** [comment]
@cbowskill should this be closed? It was in Done.

**Comment by cbowskill** [comment]
@alicerichmond - I might have prematurely moved this to done. Did you still have some commentary/write up to do on this?

**Comment by cbowskill** [comment]
@alicerichmond - I'm closing this ticket as the user testing was done. Is it worthwhile capturing any summary of the results here?
