### ISSUE TITLE
Cookies banner design

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7275]
### Problem to be solved
In line with recent [GDPR rulings](http://eulawanalysis.blogspot.com/2019/10/the-cjeu-rules-on-consent-to-cookies.html) re: cookie consent, we need to make our cookie opt-in process explicit.

We need to aim to bring our cookies banner in line with the wellcome.ac.uk version for organizational alignment.

Related to: #7264 and #4816
### Acceptance Criteria
- [ ] Users can manage preferences, opting in or out of specific cookies or categories of cookies
- [ ] A full list of current cookies is provided
- [x] Design variants of the cookies banner 
- [x] User testing conducted on variant prototypes to see which placement converts best

**Comment by jamesgorrie** [comment]
Just a reference to an issue we had with the overlapping design of the banner that's worth considering
https://github.com/wellcomecollection/wellcomecollection.org/issues/6185

**Comment by DominiqueMarshall** [comment]
@cbowskill @alicerichmond -> Various cookie banner placements as shown this morning are linked below, with the colour variations discussed:

Teal: https://zpl.io/V1Ldj1J - current cookie banner colour
Yellow: https://zpl.io/VqMeBL6 
Purple: https://zpl.io/aM30ZRm

In each screen, the bottom 3 are the ones that I feel would be worth creating initial prototypes of to gauge people's perception and usage (based on our conversation), but let me know what you think 🙂

**Comment by cbowskill** [comment]
I'm really not sure about the purple. To the point I'm not sure it's worth testing.
Is it worth mocking up a side version instead of doing the purple colour testing? (https://ico.org.uk/)

@GarethOrmerod - would be good to get your thoughts on colourway in relation to the cookies banner (particularly as you've been working through the issues with colours)

**Comment by DominiqueMarshall** [comment]
Side panel version: https://zpl.io/293e5lz 
(I adapted the text from the main preferences page)

**Comment by DominiqueMarshall** [comment]
@cbowskill banner updates below...

1) Banner with "manage preferences" option: https://zpl.io/2jKdwmr

2) Cookie banner option with an explicit decline button: https://zpl.io/bA3wEon
Clicking the "Find out more" link would take you to a secondary panel: https://zpl.io/VQ34Ejn / zpl.io/agE5NYO

3) For mobile, I'd like to test a version with the banner in the header area to see how that affects/doesn't affect any integral UI: https://zpl.io/VqM4wGm

After talking this through with Tacey and Alice, having the "accept/decline" banner option as an AB test (with the existing cookie banner as the control) feels like the approach to take as a first iteration.

**Comment by cbowskill** [comment]
Thanks Dom.

I feel the first step, before A-B testing is still understanding the best positioning for the banner (and this can be done pre-dev through some low-fi testing). The purpose is to really define the best positioning before we optimise the wording / button choices within.

In terms of the low-fi testing, have you got a view of which of the variants to test? I'm thinking:
- Top strip
- Bottom strip
- Centre
- Side
-Mobile

I'm not too concerned about colour choices for the testing, maybe retain the same colour, wording and buttons across all of them just to ensure we're testing positioning only.

**Comment by DominiqueMarshall** [comment]
For the user panel test, a centre-aligned banner was used.

![cookie-banner1](https://user-images.githubusercontent.com/60890140/152967649-59e9fbb3-2546-4bc6-ad30-a8a4dc2b3776.jpg)

![cookie-banner2](https://user-images.githubusercontent.com/60890140/152967660-1fbcf640-bcca-4567-9e8b-a47b147d9af1.jpg)


**Research summary:**

- 75% of participants accepted cookies naturally while running through the initial tasks.

- If the website isn’t for profit/educational, participants said they were more likely to accept cookies as they’re not needing to hand over any sensitive data. When visiting commercial/transactional websites (e.g. Amazon), they'll actively read more information about what cookies are being used or what they mean for their browsing experience, or will reject them.

- One participant said they outright reject cookies on _all_ websites, regardless of the company or organization.
- Another participant mentioned that they didn't feel tricked when seeing the explicit 'Reject All', 'Accept All' and 'Confirm my choices' buttons.

The level of understanding of what cookies they are consenting to when they click "Accept" varies. They'll either:
- Say they understand what cookies they’re consenting to, despite not reading the specific information about them.
- Say they understand but will read the information to check the specific details about the cookies.
- Say they don’t understand them, and will naturally accept/reject them based on personal experiences, biases, and past behaviours.
 
- They understand that cookies are necessary for a website to work, but around 40% of participants were not aware of the more technical details.


Low-fi prototype unmoderated testing isn't an ideal choice if we want to include those with accessibility needs. One participant wasn’t able to complete the tasks because it wasn’t a live website; they couldn’t use keyboard navigation like they’re used to doing.

**Secondary test**
A version of the cookie banner in the header was also tested with Wellcome staff:

![header-cookie-banner](https://user-images.githubusercontent.com/60890140/152971317-1d8a6f4b-615f-48cc-bbab-8103575b019c.jpg)

While participants found this to be a good position as it didn’t obstruct anything on the main pages, I feel this approach won’t be feasible on the Wellcome Collection website due to a potential clash with the yellow 'important notice' banner.


**Next Steps:**
- Build a live version of the cookie banner and use A/B testing with a larger quantity of people to garner more data on people's behaviours.
