### ISSUE TITLE
Requesting: Email verification page font issue

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7279]
## What?
The heading on the Email Verified page is too big.

<img width="1414" alt="Screenshot 2021-11-11 at 12 27 06" src="https://user-images.githubusercontent.com/60890140/141298234-5030d825-cede-4fb2-877a-79de9a0b5932.png">

The title on this page is 50px, but should be 24px to be in line with the zeplin design: https://zpl.io/V4XZP98

**Comment by cbowskill** [comment]
@davidpmccormick / @gestchild - new bug added to sprint backlog

**Comment by cbowskill** [comment]
@DominiqueMarshall were you happy with spacing / other font sizes on this now?
![image](https://user-images.githubusercontent.com/91600241/142193203-b0126bba-86c2-47dd-89c9-98b06e050b75.png)

**Comment by DominiqueMarshall** [comment]
Gaah I did actually put a comment on here about it but it hasn't saved 😫

- The padding and margins between the borders and the text isn't consistent with the account page. On the Email Verified screen, can they be amended to match what's on the account page? (Visual below)
- The body font size on the Email Verified screen should be 16px to match elsewhere (it's currently 20px)

<img width="847" alt="Screenshot 2021-11-17 at 12 51 51" src="https://user-images.githubusercontent.com/60890140/142204060-29329ed0-aeaa-4ae9-b6ce-d9d9eac2505c.png">

**Comment by gestchild** [comment]
@DominiqueMarshall should the 'Email verified' heading be above the box of text, same as the 'Cancel library membership' heading

**Comment by DominiqueMarshall** [comment]
Na that can stay within the box
