### ISSUE TITLE
Requesting: colour contrast of error messaging

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7281]
In checking the "Email updated" banner message on the library account page, the colour contrast of the two greens (background and text) is too low.

Current banner:
<img width="800" alt="Screenshot 2021-11-11 at 14 41 50" src="https://user-images.githubusercontent.com/60890140/141316920-0a773a6e-2258-4bc5-8fcf-ca25b4485bf1.png">

The current green text colour is # 007868, but I want to propose changing it to a slightly darker shade, #006B5D, so it meets WCAG AA for Normal Text:

<img width="800" alt="Screenshot 2021-11-11 at 14 58 51" src="https://user-images.githubusercontent.com/60890140/141319714-4b1bd813-a7c5-4648-9c07-8abff7b3d2cb.png">

**Comment by davidpmccormick** [comment]
We have a concept of a dark/light shades of colours in the palette. Dark green is set at `#146a5c` – would that be suitable to use here?

Alternatively, the background green is not part of our design-system at all, so a safer approach in terms of not breaking things that already exist would be to lighten that one further.

**Comment by davidpmccormick** [comment]
I went with the dark shade of green that we already have, because it was the simplest/safest thing to do.

**Comment by DominiqueMarshall** [comment]
The darker shade of green is a better approach than making the background lighter (doing that means the background gets completely lost visually)
