### ISSUE TITLE
Write guide on how to use Prismic API

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7295]
# User story

As a member of the Digital Experience or Editorial team
I need to find articles in Prismic 
So that I can edit them. 

# Background

Prismic allows users to search by type, tag and author and has a search bar but results are returned in date order. Because the search returns any matches against the whole text and not just the title, it takes a lot of ploughing through search results to find anything. 

The API allows for more targeted searches so writing a guide with examples will help everyone use the API and save time searching.

# To do:

- [ ] Read up on Prismic API predicate reference
- [ ] Create list of use cases for searches
- [ ] Create shared How to use Prismic API page in Notion with example queries

**Comment by jamesgorrie** [comment]
On average we leave Prismic functionality to their docs so if things change, the docs are updated.

We store how to's on things that are specific to our model here:
https://www.notion.so/wellcometrust/Prismic-a55a0906191d4910bdee4ac4f96e9b91
