### ISSUE TITLE
Analysis of effect of cookie banner design changes

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7320]
**What is the problem to solve?**
We need to change the appearance of the cookie banner so that more users choose to close the cookie banner (which we are interpreting as consent to cookies) so that we can collect more data from consenting users.

**What stage of research is it? (discovery/general usability testing/post release)**
general usability testing

**What are the objectives?**
collect data for before and after design change to see if % of users who close the banner increases

**What are the assumptions?**
users' decisions are influenced by the placement, size, wording and colouring of banner.

**Acceptance criteria**
At least 2 week's worth of data both before and after design changes.

**Comment by taceybadgerbrook** [comment]
Cookie banner currently looks like this
![cookie banner](https://user-images.githubusercontent.com/32418070/141966407-a35859a0-d5ae-488e-a3b1-7f5a409ac192.jpg)
:

**Comment by taceybadgerbrook** [comment]
GA event set up 15/11/21
Event category: CookieNotice
Event action: click close cookie notice button
Event label: url displayed when banner clicked

**Comment by jennpb** [comment]
Tacey, I'm closing this one because we won't need the data as we're doing a full redesign anyway.
