### ISSUE TITLE
Remove "BETA" label on collections search as part of requesting toggle

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7332]
Remove the "BETA" label and associated "Find out more" text link as part of going live with requesting (e.g. as part of requesting toggle)

![image](https://user-images.githubusercontent.com/91600241/142426380-81ce4387-a9ac-4fec-9f36-5e3eb9ef0385.png)

**Comment by jamesgorrie** [comment]
Out of interest - why not just remove it?

**Comment by cbowskill** [comment]
This was raised based on a conversation in slack that Jonathan initiated:
"Suggestion: should we put removing the beta label behind the requesting toggle? Seems like the last remaining piece to me."

I assume requesting going live is the last remaining element of why it's currently perceived to be in "beta" mode and thus why it makes sense to remove it when requesting goes in.

**Comment by jamesgorrie** [comment]
Makes sense, I was just asking as it seems to be specific for search, which has been the primary search for ages.

**Comment by jamesgorrie** [comment]
And actually, reading the link, it is specific to search.
https://wellcomecollection.org/works/progress

**Comment by cbowskill** [comment]
I think the general ask is that it's removed around the time requesting goes in - which I think will be good as it has been there for quite some time now.

I guess this means it doesn't strictly have to be tied to the requesting toggle (and in fact, it might be better not to be tied to the toggle in case we ever need to switch requesting off for any reason - we wouldn't want this label to re-appear) but it needs to go live when we put in the requesting work.
