### ISSUE TITLE
Helpful information to help you log in to your library account

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7345]
# What is it and who's it for?
Requesting will change the way in which a library member logs into their account.
Rather than using their library number or username they will now need to sign in using the email address associated with their account.

It has been flagged through user testing that this will cause some of the main issues when we put requesting live and anything we can do to mitigate enquiries into the library team and enable users to self serve will be beneficial.

# User story
As an existing library member
I know that I now need to sign in using my email address
So that I can access my account

As an existing library member
I know who to contact when I'm having trouble accessing my account
So that I can use my account successfully

**Comment by DominiqueMarshall** [comment]
Design for the updated sign-in screen: https://zpl.io/bln3BJ0

@cbowskill is it worth adding this to the copy review ticket as well?

**Comment by pollecuttn** [comment]
Ready for dev to pick up
