### ISSUE TITLE
wellcomelibrary.org stats

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7349]
**What are the objectives?**
Getting a picture of impact on users of turning off wellcomelibrary.org.

**What research technique is required?**
GA:

1. Numbers of users of [https://search.wellcomelibrary.org/](https://search.wellcomelibrary.org/)
2. Numbers of users searching [https://search.wellcomelibrary.org/iii/encore/search/C__Schair__Orightresult__U?lang=eng&suite=cobalt](https://search.wellcomelibrary.org/iii/encore/search/C__Schair__Orightresult__U?lang=eng&suite=cobalt)
3. Numbers of users requesting items requesting [https://search.wellcomelibrary.org/iii/encore/search/C__Schair__Orightresult__U?lang=eng&suite=cobalt](https://search.wellcomelibrary.org/iii/encore/search/C__Schair__Orightresult__U?lang=eng&suite=cobalt)
4. Numbers of users accessing library account [https://search.wellcomelibrary.org/iii/encore/myaccount?lang=eng&suite=cobalt](https://search.wellcomelibrary.org/iii/encore/myaccount?lang=eng&suite=cobalt)
5. Any additional activities (eg, Add to saved / Email / Export / Add tag/ Add to list)

**Comment by taceybadgerbrook** [comment]
During the period 1-31/10/21, 10,477 users visited wellcomelibrary.org and viewed 38,271 pages, of which:

1. initial search page views:

|page views | page |
|--:|:--|
|485 | https://search.wellcomelibrary.org/|
|6177|https://catalogue.wellcomelibrary.org/|
|394|https://search.wellcomelibrary.org/iii/encore/?lang=eng&suite=cobalt|
|161|https://catalogue.wellcomelibrary.org/search|
|**7217**|TOTAL|
2. 2,617 viewed pages for searching (pages containing encore/search/)
3. 1,374 items requested
4. 241 views of page https://search.wellcomelibrary.org/iii/encore/myaccount?lang=eng&suite=cobalt
5. 344 page views containing loginReason; 50 views of saved items; Any additional activities (eg, Add to saved / Email / Export / Add tag/ Add to list)

**Comment by taceybadgerbrook** [comment]
In percentage terms, 19% of wl.org page views are catalogue searches. Less than 1% of users request items. Of total views of library accounts, 21% of views are of saved items.

**Comment by cbowskill** [comment]
If there were 38k+ page views, your breakdown only shows around 7k of these. Where are the other 31k views taking place?

**Comment by taceybadgerbrook** [comment]
Looking at the requesting stats that Tania Williams produces, during August, 87 people requested a total 588 items through a combination encore and search.wellcomelibrary.org. Here's what the distribution looks like:
![image](https://user-images.githubusercontent.com/32418070/143032334-5421746d-687d-477e-b349-d0b56d54e813.png)
![image](https://user-images.githubusercontent.com/32418070/143033262-4b3328b3-7ffb-42ea-942f-f52eae12f535.png)

So a quarter of users only requested one item. These types of users might be foxed by a redirect.

Then there are a few users who request lots of items. I think these users are less of an issue because they are in touch all the time and will look at a message delivered to their account.

**Comment by taceybadgerbrook** [comment]
For the period 8/10/21 - 22/11/21 (to miss out the IFL Science spike), here's what the traffic sources are:
![image](https://user-images.githubusercontent.com/32418070/143034472-4cb8be93-8332-47e9-a951-69e991e2c30c.png)

If we assume approximately 4,500 users will continue to arrive from referrals, over half of these users are referred from wellcomecollection.org
![image](https://user-images.githubusercontent.com/32418070/143035469-b9b492bb-d565-489a-9ed8-de7481253fc2.png)
