### ISSUE TITLE
Improve UX when changing your email address

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7358]
# What is it and who's it for?
Feedback from Tom:

**Steps:**

1. Log in
2. Change email address
3. Confirm via email
4. Taken to the following page (screen grab)

Note that the UI indicates I’m logged in (initials top right) and I am logged in but the CTA is ‘sign in’ - if I do click sign in I’m taken to my account page.

![image](https://user-images.githubusercontent.com/91600241/143210189-866a7b80-eadc-4d99-a527-54280a54f1fe.png)

**@DominiqueMarshall  / @gestchild** - what are our options in this scenario? Tom will have been logged in as he will have done it whilst his token was still active (and hence auto logged in). However, there will be some users who interact with the email after their token has expired. Can the button be smart enough to recognise the logged in state and either prompt to view account or login accordingly?

**Comment by DominiqueMarshall** [comment]
Having that extra logic behind the button sounds like a good approach to me (if it is indeed possible!)

There's another weird behaviour I've just spotted when you're **not** signed in.

When you go through the sign-in process from that email verified page, it redirects you _back_ to that email verified page, rather than your library account, which is really confusing as it makes you think you need to sign in twice.

**Comment by cbowskill** [comment]
have created another issue for the issue Dom's mentioned. Can be found here: https://github.com/wellcomecollection/wellcomecollection.org/issues/7361

**Comment by cbowskill** [comment]
Question - I've just re-tested this journey and whilst I can see the extra logic in the button (thank you very much!), when I now go to my account it doesn't clear the 'You've not validated your email address' message until I've logged out / in again. I'm sure previously this cleared immediately in the same log in session?

**Comment by cbowskill** [comment]
Ignore this comment - sounds like Jamie will resolve it as part of some of the work he's doing (as per Slack)
