### ISSUE TITLE
Reset password flow - unknown error

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7359]
I went through the forgotten password flow yesterday afternoon and only used the link from the email today and received an unknown error.
When sending a new forgotten password email today this worked as expected.
Why would the email from yesterday produce an unknown error (we state the link is valid for 5 days - is this correct?)

**Steps:**
1. Go to account
2. Select Forgotten Password
3. Enter email address and submit
4. <<Wait a period of time 12hrs/24hrs >>
5. Select link from email
Observe: An error message on the reset page

<img width="1090" alt="Screenshot 2021-11-24 at 09 45 08" src="https://user-images.githubusercontent.com/91600241/143215484-9a91009c-c95a-4123-84b4-77812dd2d44d.png">

Expected:

- Link to reset password works within the timeframe quoted that the link is active
- Error messaging is helpful, articulates the issue and is displayed in line with other error messages (this looks like it's a different style to what we use elsewhere)

**Comment by davidpmccormick** [comment]
The link _should_ be valid for 5 days (this is the default, and it hasn't been changed from the looks of things).

![image](https://user-images.githubusercontent.com/1394592/147094972-b445e1af-caaf-42fd-a015-2eafe6cab179.png)

**Comment by cbowskill** [comment]
@davidpmccormick - I'll re-test this today and see what happens tomorrow. Will update if this can be closed or if it recurs

**Comment by cbowskill** [comment]
Re-tested and looks fine. Will close.
