### ISSUE TITLE
Journey issue from 'Please verify your email address' email

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7361]
1. Go through change email address process in account
2. Click link in 'Please verify your email address' email to verify new email address
3. Log out of account
4. Re-click link in 'Please verify your email address' and you'll be prompted to login
5. Login successfully
Observe: you're re-directed back to the 'You've verified your email address' confirmation page and not your account page

Expected behaviour
When you login you should be taken to your account page

The URL also appears a little strangley (shows 'This URL can be used only once' message): https://wellcomecollection.org/account/validated?message=This%20URL%20can%20be%20used%20only%20once&success=false

**Comment by gestchild** [comment]
Fixed by #7423
