### ISSUE TITLE
Mapping of as is to new flows for library staff (process mapping)

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7364]
Depending on auth0 implementation there may/will be additional account management activities to undertake in auth0.

Current library processes (related to account/requesting) need to be documented, mapped and translated into a new process for when Requesting/Account goes live.

- [ ] Map existing processes for the management of accounts / requests
- [ ] Highlight where changes have occurred and provide training / documentation on new processes
- [ ] Test E2E processes (including Sierra interactions)

**Comment by pollecuttn** [comment]
@cbowskill This was in 'Done' - can it be closed?
