### ISSUE TITLE
Heuristic evaluation of the site (Usability audit / baseline)

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7366]
We would like to better understand the challenges that exist across the current website.

This evaluation will allow us to conduct a usability audit of the site using a variety of pre-determined measures to highlight key areas to optimise.

This will allow us to populate the backlog with a series of 'optimisation' activities that are designed to drive incremental (positive) change within the current experience and have a backlog of well refined stories to take into sprints. Key to collating, synthesising and prioritising known issues and resolving these.

- [ ] Review initial audit template and agree this is fit for purpose (https://docs.google.com/spreadsheets/d/13hEjqtvWFHzJSYrcj5t2p0gRZEq1Rri72BQ97WZKGbs/edit?usp=sharing)
- [ ] Conduct audit
- [ ] Collate, analyse and determine actions from the results
- [ ] Create new optimisation stories to be delivered in future sprints

**Comment by pollecuttn** [comment]
To do: work out page goals
