### ISSUE TITLE
Display a better error message when a user requests an item and their account has expired

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7451]
Currently users whose accounts have expired get a very generic error:

![screenshot_2021-12-07_at_15 42 26](https://user-images.githubusercontent.com/301220/145062787-637a38b7-654c-4166-b5af-01076f985032.png)

We should replace this with a more explanatory error message. I can do the code, but the error message may need some wordsmithing from @cbowskill and @DominiqueMarshall:

> Your account has expired and you cannot request items. Please contact the library team.

**Comment by cbowskill** [comment]
@DominiqueMarshall - are you ok to have a first attempt at this messaging? I'm thinking a more explicit message and potentially directing them to library enquiries for help renewing their account?

**Comment by DominiqueMarshall** [comment]
"Your account has expired, and you're no longer able to request items. To renew your account, please get in touch with the library team."

**Comment by cbowskill** [comment]
Thanks Dom.

How about (and if there's a way of adding the linking to the email address (where 'contact the library team' is a text link - similar to the message within account)

Your account has expired, and you're no longer able to request items.
To renew your account, please contact the library team

**Comment by alexwlchan** [comment]
This is deployed, we'll just need to test it. (I can't remember if HTML is rendered in those alerts.)

**Comment by pollecuttn** [comment]
@alexwlchan I've just expired my Sierra account to test this, and tried to request something.

I got the same "Request failed" message as you show above when you opened this.

I'm not sure if I'm testing this correctly. I expired my record in Sierra, and have tried requesting https://wellcomecollection.org/works/xy46e72g.

**Comment by alexwlchan** [comment]
Hmm, okay, pretty sure it's deployed. I'll try in a bit – my account has also expired (five years!!), so I should hit the same error path. Thanks for reminding me!

**Comment by jamieparkinson** [comment]
@alexwlchan did you check this?

**Comment by alexwlchan** [comment]
Apparently not:

<img width="523" alt="Screenshot 2022-02-16 at 16 48 19" src="https://user-images.githubusercontent.com/301220/154314660-1045ee81-35df-4cfe-b682-9ce4553ad880.png">

**Comment by alexwlchan** [comment]
\*buzzer sound*

<img width="659" alt="A modal dialog asking me to contact the library team, but the mailto link is rendered as plain text rather than HTML" src="https://user-images.githubusercontent.com/301220/156735798-73d9e598-d21d-496d-85f2-8e6fcdc1ebcd.png">

**Comment by melanierogan** [comment]
Since we mentioned the difficulty in dealing with html being injected along with text here from the api, can we replace this message with: Your account has expired, and you're no longer able to request items. To renew your account, please contact Library Enquiries (library@wellcomecollection.org). 
What do you think @cbowskill?

**Comment by alexwlchan** [comment]
> Since we mentioned the difficulty in dealing with html being injected along with text here from the api, can we replace this message with:

Let's talk about this at standup – Jamie and I have discussed a better way we might do this.

**Comment by cbowskill** [comment]
I think the option you've suggested is absolutely fine. No issues with that. Happy to discuss at stand up if there's an alternate way you want to explore.

**Comment by melanierogan** [comment]
So to try to capture a summary of the stand up chat: we have plans of doing this is in a better way, it will take a little more time, so we all seem happy enough to put the easier fix in (of adjusting the copy) for now. I'll get that done
