### ISSUE TITLE
Filter usage fields in metrics-conversion-prod need changing from text to keyword

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7453]
**What**
Kibana can count keywords but not text. Looking at the[ fields in stack management](https://reporting.wellcomecollection.org/s/search/app/management/kibana/indexPatterns/patterns/f3f3aee0-31c3-11ec-b182-4527f28c3f8f#/?_a=(tab:indexedFields)), keywords show as aggregatable whereas text only shows as searchable. The filter usage fields are text, so none of the histograms in the dashboards are populating.

**Where**
[[](https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/88c2ee40-3b9e-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now))
)](https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/88c2ee40-3b9e-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now)))

**Comment by taceybadgerbrook** [comment]
👆 @harrisonpim @alexwlchan I was working with James on this before he left. Could either of you change the format of these Elasticsearch fields or show me how? This is what is preventing me from sending out the Kibana dashboards:

- [Search](https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/88c2ee40-3b9e-11eb-96c7-bfa81aee2c94?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now)))
- [Conversion](https://reporting.wellcomecollection.org/s/search/app/dashboards#/view/341ef370-832e-11eb-bcd6-c58220746d65?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now)))

**Comment by harrisonpim** [comment]
I'll take a look at this today
