### ISSUE TITLE
Deletion request email

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#7494]
- [x] Update the email template so the design is consistent with the other emails
- [x] Change the wording of the email

**Comment by gestchild** [comment]
@DominiqueMarshall there are a couple of other emails that also get sent, that you may want to look at:

If a user cancels their deletion request:
![Screenshot 2021-12-16 at 10 30 35](https://user-images.githubusercontent.com/6051896/146355939-7d413ca8-beb5-402f-b09b-fe42cd29d1ac.png)

The deletion request sent to library staff:
![Screenshot 2021-12-16 at 10 31 20](https://user-images.githubusercontent.com/6051896/146355952-7bb0d625-e399-49c4-b8aa-74b907fa65ba.png)

**Comment by DominiqueMarshall** [comment]
I think the messaging in the email sent to library staff can stay the same for now. 
I didn't know that users could cancel their deletion request... @cbowskill was this something mentioned by Miriam or David at all?

**Comment by cbowskill** [comment]
I didn't know this was a possibility either? Do we even have the functionality that enables you to cancel your deletion request?

**Comment by DominiqueMarshall** [comment]
Not on the current site, no

**Comment by cbowskill** [comment]
Was it developed as part of the new experience? I've still not tried account deletion yet as I haven't wanted my account to be accidentally deleted. I have some time with Miriam/David when we're back in Jan to go through some of those journeys.

**Comment by gestchild** [comment]
I was only going on the presence of that email template, but now I'm looking I can't actually see anything in the code that would allow you to cancel your deletion request. @jamieparkinson do you know if that functionality was ever there?

**Comment by jamieparkinson** [comment]
Yeah, that was part of the admin app - you're right that there's no way of doing it now. Get rid of it imo, it feels like a really really tiny edge case!

**Comment by DominiqueMarshall** [comment]
**Deletion request email**

Hi [user name],

We've received your request to delete your library account.
A member of the team will review and action this within the next 7 days.

If you have any questions, please let us know.

Thanks,
Library Enquiries


Note - I've confirmed with David L that the library team will want at least 7 days to action a deletion request, but this will need to be run past legal too from a GDPR standpoint/if they need to remove data within a certain timeframe.

**Comment by gestchild** [comment]
@DominiqueMarshall is the current subject line on the email ok?

"We've received your account deletion request"
