### ISSUE TITLE
Thin black line on radius corners of content cards

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#7626]
**What**
Radius corners on the top left and right of our content cards have a thin black line. It only shows up on images with a light coloured background.

![Screenshot 2022-02-01 at 12 57 23](https://user-images.githubusercontent.com/1446072/152144420-2ecab9bf-152b-4f80-b6af-63c0c37e95af.png)
**Where**

![Screenshot 2022-02-01 at 12 57 23](https://user-images.githubusercontent.com/1446072/152144420-2ecab9bf-152b-4f80-b6af-63c0c37e95af.png)

e.g. on https://wellcomecollection.org/articles

Reported via Slack: https://wellcome.slack.com/archives/C8X9YKM5X/p1643793197636559

## To do
- Remove the thin black line from the top left and right corners of content cards

**Comment by melanierogan** [comment]
I am working off a theory that this is happening for 'small' images because we are setting the vw (viewport width) to be 33.33333333333333. I know that the line sometimes just disappears in different browsers, or if you close, reopen or zoom in and out but I think I can consistently remove the line by making sure that the vw is a whole number. I'll see about adjusting this in `PrismicImage`

**Comment by melanierogan** [comment]
![Screenshot 2022-03-31 at 09 56 14](https://user-images.githubusercontent.com/16557524/161728486-073f0270-aaf5-4574-a21a-e1d89c08f680.png)

**Comment by melanierogan** [comment]
Sadly we can still see this issue happening in places in production, and I can track that my fix has gone through to production (side note: I was a little confused as to whether it had or had not based off a backlog of deployments in staging). I'm going to put this ticket back into play. 

Alex mentioned that keeping in mind some styling may change based on whether or not you've visited the site before - so something to keep in mind there when thinking about other possible fixes. David was pretty confident this wouldn't impact things as he was able to replicate the issue in codepen.

What a mean bug eh? Back in the sprint you go!
