### ISSUE TITLE
Updating books featured on Stories landing page

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7640]
## Background

Request via wc-platform-feedback (https://wellcome.slack.com/archives/C8X9YKM5X/p1644337765470989)
The 3 books featured on the Stories landing page need updating.

## User story
As an organisation
We want to promote the most recent/relevant books
So that we drive engagement and interest in the books we support

## Acceptance criteria
The 3 books featured on the stories landing page are changed to:
- 'This Book is a Plant’
- ‘Hybrid Humans’
- ‘Recovery’

## Testing and tracking
- N/A

## Measurement
- N/A

## Other considerations 
- Should we look at making this controllable via CMS?

**Comment by davidpmccormick** [comment]
Closed by #7638

> Should we look at making this controllable via CMS?

I think that would be great.
