### ISSUE TITLE
Odd crop on twitter cards

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#7641]
**What**
We've been getting a really odd crop on the twitter card for Rosie Barnes' piece here: https://wellcomecollection.org/articles/Yd8L-hAAAIAWFxqa 

![image](https://user-images.githubusercontent.com/1446072/153193194-b06a5bee-2dc8-4846-83e5-82089a4fd73c.png)

The odd crop is consistent (everyone who posts the article gets exactly the same crop see eg https://twitter.com/derivadow/status/1491345451777687554) and I assume that it is twitter's saliency algorithm that's doing it.

Looking at our own code, I'm assuming that twitter is taking the image which it crops from the Open Graph tags (specifically the og:image property of the meta tag) at the top of the page, which give us this square image:
[https://images.prismic.io/wellcomecollection/2a42de1c-7954-4ece-be5f-775079c4bc54_Lau[…]utside.jpg?auto=compress%2Cformat&amp;rect=&amp;w=800&amp;h=](https://images.prismic.io/wellcomecollection/2a42de1c-7954-4ece-be5f-775079c4bc54_Lauren+seated+outside.jpg?auto=compress%2Cformat&rect=&w=800&h=)
& I assume that this in turn takes the image from the full square image that [@Ben Gilbert](https://wellcome.slack.com/team/UDC5X9D0T) puts into Prismic. It's square so that we have a variety of crops available for different devices (on mobile, the lead image renders as square).

Any thoughts on what's going on here / if this is a one-off / if there's anything we can do to prevent this happening again?

Reported by @dannybirchall  https://wellcome.slack.com/archives/C8X9YKM5X/p1644400706630219

**Comment by paul-butcher** [comment]
My first reaction to this is it looks like Twitter's face detection bias. https://www.bbc.co.uk/news/technology-54234822

I don't know if they have actually done anything to fix this yet. I don't think there's a way to force it to use a specific crop rectangle.  We may have to provide separate images.

**Comment by paul-butcher** [comment]
We can specify the crop in the URL - Twitter card images are 800x412, the source image is 4000, so something like this should work:

https://images.prismic.io/wellcomecollection/2a42de1c-7954-4ece-be5f-775079c4bc54_Lauren+seated+outside.jpg?auto=compress%2Cformat&rect=0,0,4000,2000&w=800&h=

**Comment by pollecuttn** [comment]
@dannybirchall to check with Ben if the crop needs to be square before we change anything

**Comment by alexwlchan** [comment]
> Looking at our own code, I'm assuming that twitter is taking the image which it crops from the Open Graph tags (specifically the og:image property of the meta tag) at the top of the page, which give us this square image:


Close – it's actually coming from the Twitter card metadata, which is directly below it:

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@ExploreWellcome">
<meta name="twitter:url" content="https://wellcomecollection.org/articles/Yd8L-hAAAIAWFxqa">
<meta name="twitter:title" content="“No you’re not” – a portrait of autistic women">
<meta name="twitter:image" content="https://images.prismic.io/wellcomecollection/2a42de1c-7954-4ece-be5f-775079c4bc54_Lauren+seated+outside.jpg?auto=compress%2Cformat&amp;rect=&amp;w=800&amp;h=">
<meta name="twitter:image:alt" content="Portrait photo of Lauren,  a young woman with black hair, sitting on an orange bench outside. She has several tattoos on her arms and is wearing a black sleeveless top, leopard print shirt and a leopard print skirt. She has large hoop earrings and is wearing an orange red lipstick. Her nails are painted in a variety of colours. She is looking into the distance, slightly smiling. Behind her, there is a building and a tiled wall. ">
```

Pretty similar, but that `summary_large_image` is a clue. It leads you to the [documentation for Twitter cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image), which describes the `twitter:image` attribute like so (emphasis mine):

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. **Images for this Card support an aspect ratio of 2:1** with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

If you supply an overly cropped image, you're at the mercy of the algorithm.

I can see Ben has already provided a 32:15 crop of this image, which is pretty close to 2:1 – I would suggest we use that crop for now (which will work fine for other previews, e.g. in Slack), and then we use the [Twitter Card Validator](https://cards-dev.twitter.com/validator) to refresh the cache and get Twitter to pick up the new image.

This would be a fairly small change with no work required from the Editorial team.

**Comment by dannybirchall** [comment]
Thanks Alex! That would be great.

**Comment by alexwlchan** [comment]
This change is deployed and live. I've run the page through the Twitter card previewer, and I'm seeing the correct behaviour when logged in:

![Image 10-02-2022 at 12 00](https://user-images.githubusercontent.com/301220/153404772-eabe8eff-9eb8-4b8c-8544-b08a7e0fbfcc.jpg)

<img width="724" alt="Screenshot 2022-02-10 at 12 03 20" src="https://user-images.githubusercontent.com/301220/153405165-52f2ddca-664f-4d72-a78b-1c14fe0f5d3d.png">

<img width="565" alt="Screenshot 2022-02-10 at 12 03 38" src="https://user-images.githubusercontent.com/301220/153405199-1bf74f9e-ced5-4a6d-8bb8-a2b8c0a9dfd2.png">

It might take a few minutes to propagate through Twitter's caches, but:

1. This article should be updated shortly
2. For all future stories, whatever is used as the 32:15 crop will be used as the preview image on Twitter and other social platforms
