### ISSUE TITLE
Library membership - form fields

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7648]
cc @cbowskill 
Summary of my chat with David L and Edward about the form fields...

## Current paper form fields:
_This form will need to be updated to align with the digital form:_

- Title
- First Name
- Last Name
- Permanent home address
- Username
- Mobile/Tel
- Email
- University/College/Institution affiliation (if applicable)
- Accessibility and inclusion assistance checkbox
- How did you hear about the service?
- What is your main area of interest?
- Which of these best describes you?
- Library’s Conditions of Use signature and date area
- How you would like to be contacted about your library membership (email or post)
- Checkbox to sign up for information about WC and upcoming events
- Checkbox to receive information about the work of Wellcome

**Staff Use Only Area**
- Patron type
- Geographic area
- Form of ID provided
- Card issued by

## Pre-reg form fields (from Wellcome library site):
- First name (s)
- Last name(s)
- Email address
- Confirm email address
- Username
- Terms and Conditions checkbox

## Proposed changes to digital form fields

**Title** - Remove as this isn't used on library cards. Consider asking for preferred pronouns instead.

**Permanent home address** - This needs to be kept as part of agreements for access to items in the collection and e-resources. Also used for security purposes to check that people are who they say they are. Needs to include the postcode field too.

**Username**  - Remove as no longer needed.

**University/College/Institution affiliation** - This field can be dropped as it has no use after the data is inputted into Sierra. Could possibly be added as a free text field under the Student options within "_Which of these best describes you?_"

**Mandatory fields**
- First and Last name
- Home address (_UK and international addresses_)
- Mobile/tel
- Email address
- Accessibility and inclusion assistance checkbox
- Library’s Conditions of Use signature and date area (_needs to be a required checkbox_)
- Checkbox to sign up for information about WC and upcoming events
- Checkbox to receive information about the work of Wellcome

**These fields should be kept for now too, but Amelia has done some work to help reconsider these questions (which David L will be providing):**
- How did you hear about the service?
- What is your main area of interest?
- Which of these best describes you?

**This field needs to be updated/reworded to only reference email contact:**
- How you would like to be contacted about your library membership (email  ̶o̶r̶ ̶p̶o̶s̶t̶)

## Expectations about post-registration behaviour
- People who fill in the form online would be given pre-reg status until they provide ID.
- In new world + with date picker incoming, the "pre-reg" status will mean that people **won't be able to make any item requests until they've provided/emailed ID and completed registration**, as this will cut down on staff retrievals.
- Need to provide the library team's contact details (email and number) for anyone who may be feeling nervous about sending their ID via email instead of being able to upload images to a secure platform.
- Need messaging somewhere in the flow to let people know that staff will be taking their photo to complete registration and to create their library card when they first visit the library.

### Next steps
- Review the current designs and revise the fields where needed + add new key messaging pieces
- Review the question work by Amelia
- Review tech implications with address fields + the best approach for handling this

**Comment by cbowskill** [comment]
Thanks @DominiqueMarshall . Having a look through at the designs, some feedback:

**General thoughts:**
- We need to split this ticket into a Phase 1 (replicating form as is) / Phase 2 (additional fields required)
- There is an awful lot of additional information / check boxes we're trying to capture. Is this all necessary and is there a better way of doing this? (for example we're asking for 3 different checkboxes about talking to you). Is there a more phased approach as to how and where we capture some of this information? Happy for us to review this together.
- As we spoke about yesterday, I think we clearly need to document the flows. We need to know what the flow is for someone signs up offline vs. online (how does password creation work) and I also believe we may have an issue with the email verification flows/emails? (didn't we have an issue early on in requesting whereby we had to change the email verification wording as it was all about 'thanks for creating an account'. So we may need to revisit this flow if we have a limitation in terms of the email verification email)

**More specific feedback on the designs:**

- Intro - you can access up to 15 materials (not 10)
- 'Wish to use our digital collections' - would this be better as 'Wish to view our digital collections'
- 'Wish to use our digital collections' - do we really want to link people away from a form we're trying to get them to populate?
- First name / Last name - is there a reason these are next to each other and not stacked? What's the character length like and could it cause issues with longer names?
- Email address / Password fields - Should we be asking for confirmation of the email address and password to ensure no mistakes? (isn't this typically the norm?)
- Password field - We're talking about library membership but then asking for a password, is it obvious this is related to your online account? 
- Address fields - As we need this to be international, what considerations are there for postcode field?
- Affiliation / Hear about us / Interests / Describe yourself - I feel these aren't mandatory and we should challenge their inclusion
- Accessible / T&Cs check boxes - Should these be differentiated from each other? The T&Cs signing is mandatory for the account and so needs to be clear you have to select yes to create the account
- Account created confirmation - We've switched from leading to 'Apply for library membership' to 'Account created' we need to lead with the same element (e.g. either membership or account should be the priority throughout)

**Comment by DominiqueMarshall** [comment]
Updated designs on Zeplin:
- account details: https://zpl.io/PqzZ45k 
- personal details v1: https://zpl.io/nolwr0x 
- personal details v2: https://zpl.io/8lkrW6X 
- application received: https://zpl.io/mDXQBYQ
- Email verified: https://zpl.io/7wkrZ6j

The main updates are:
- Removed “On your first visit to the library, a member of staff will take your photo to complete registration and create your library card” from the initial screen → This info could be added to the library membership page under Collections.
- Removed the interest-based questions. These could potentially be asked by staff when they contact the new member about their membership?
- I’ve changed the consent option to be a radio button with an explicit “yes, I agree” statement
- Account created confirmation - the header has been updated to be “application received”
- Simplified the email verified screen to account for the issue with current members changing emails (and the screen being the same)

@cbowskill with the considerations for the postcode field, I think this will be dependent on the dev implementation?

I've also created a secondary approach for the flow with the info loading on the same page section by section (a bit like they do on popular shopping carts at the moment) and with the last page being where they can review their details before confirming:
Screen 1: https://zpl.io/RMgZqPK
Screen 2: https://zpl.io/AmkrvEP
Screen 3: https://zpl.io/z854Mnz
Screen 4: https://zpl.io/g8qwnNM

In terms of going backwards and forward, in the first design approach, I would expect the three checkmark headings at the top to be clickable, and for the information they've entered previously to remain. 
On the second design approach, they would click "change" to be able to edit the info entered.
