### ISSUE TITLE
Improved messages for a requested item's status

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7660]
# Background

When you place a request for an item, the item is shown in your account alongside a status.

These are the potential status' that we receive:
- on hold.
- bib hold ready for pickup.
- volume hold ready for pickup.
- item ready for pickup.
- bib, item or volume in transit to pickup location.

These aren't very useful from a user perspective and can be misleading (e.g. if you see 'on hold' does this mean the item is on hold and I can go and view it or on hold and still in the store). To avoid any confusion we would like to update these to be more explicit.

# User story
As a library member
I want to know the status of my request
So that I know whether or not I should come to the building to view it

# Implementation 
- on hold. --- change to --- Request processing
- bib hold ready for pickup. --- change to --- Available to view
- volume hold ready for pickup. --- change to --- Available to view
- item ready for pickup. --- change to --- Available to view
- bib, item or volume in transit to pickup location. --- change to --- In transit

# Acceptance criteria
- Status are shown as per table above

**Comment by jamieparkinson** [comment]
Status IDs are here: https://techdocs.iii.com/sierraapi/Content/zObjects/holdObjectDescription.htm
