### ISSUE TITLE
Removal of ticketing on requesting

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7726]
# What is it and who's it for?
As we remove the ability to book a ticket for the building, we also need to remove this functionality from the new requesting flows

# Implementation 
Remove reference to booking a ticket from within the requesting flows (remove text and CTA)
<img width="867" alt="image" src="https://user-images.githubusercontent.com/91600241/155955966-eefff6af-7f4d-4d9f-b448-fea7de3910b3.png">

@DominiqueMarshall - do you have a visual for how this confirmation screen should look without the reference to ticketing?

**Comment by DominiqueMarshall** [comment]
![Screenshot 2022-02-28 at 09 18 42](https://user-images.githubusercontent.com/60890140/155957099-c429cd3a-9c81-4360-a1d9-1216d7a8ff44.jpg)
