### ISSUE TITLE
Provide directions to locations specified within an event

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#7729]
## Background

Split out from #7639

Now that events can have multiple locations attached, we need to establish how these (and directions to them) are displayed on an event. Currently, we show information about only the first location in the yellow box, under the heading `Location`.

## User story
As a user
I want to know where an event is scheduled to take place
So I can make the necessary arrangements to attend

## Acceptance criteria
Directions to location(s) are clearly specified within an event

**Comment by pollecuttn** [comment]
@cbowskill Just wanted to make sure you were aware of this issue
