### ISSUE TITLE
Investigate use of graph query

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#7736]
Background:
[GraphQuery](https://prismic.io/docs/technologies/graphquery-rest-api) is a more advanced version of fetchLinks,  that allows us to  do things fetchLinks doesn't, i.e. fetching only required fields and fetching deep fields from linked documents.

However, it doesn't come with all the nice type checking stuff that fetchLinks does. So, if possible, we want to remove our use of graphQuery.

We need to investigate all uses of graph query, and make sure we’re only using it where needed.

**Comment by rcantin-w** [comment]
@gestchild Would this cover it? https://github.com/wellcomecollection/wellcomecollection.org/issues/10148
