### ISSUE TITLE
Sort out the RSS app

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7751]
The RSS feed on wellcomecollection.org/stories works, but it's quite brittle. It lives in [rss/webapp](https://github.com/wellcomecollection/wellcomecollection.org/tree/main/rss/webapp), but it runs in Vercel and there's no documentation about how to deploy it or update it.

It's running an old version of the Prismic client, and it's not tied to the rest of the content app.

😕 

We should tidy up the RSS feed so it's easier to maintain. This means:

- Running it in AWS, rather than in Vercel (what exactly this looks like is up for discussion)
- Wire up the new app to DNS on rss.wellcomecollection.org
- Use the nice typed fetchers from the content app, so we don't duplicate Prismic parsing code
- Document how to deploy it, update it, etc.

Although there's an existing app, it's small enough that we could do a complete rewrite. This would be a nice project for somebody who wanted to build and deploy something from scratch.

**Comment by alexwlchan** [comment]
In the interests of keeping this simple, could we just fold the RSS feed into the `content` app? And get rid of the standalone app?

**Comment by rcantin-w** [comment]
Raised it in [Slack](https://wellcome.slack.com/archives/C3TQSF63C/p1713973306127639), @kenoir suggested to @jcateswellcome it gets discussed in planning, so moving to platform board.

**Comment by rcantin-w** [comment]
🎉
