### ISSUE TITLE
Provide visible feedback that preview.wellcomecollection.org doesn't work in Safari

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7761]
Quoting [Gareth in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1644316472836029?thread_ts=1643991123.344219&cid=C8X9YKM5X):

> Safari blocks cross-site cookies, which Prismic's preview  functionality relies on. So the only solution I'm afraid, is to use a different browser or [enable cross-site cookies](https://community.prismic.io/t/troubleshooting-previews/5449#are-your-previews-not-working-in-safari-12)

Although that's useful for us to know, it’s not always obvious that this is happening.

It would be nice if we could provide a visible warning to the user at the top of the page, say a big red box that says:

> Prismic previews do not work in Safari. Please use a different browser, or enable cross-site cookies.

I think we do (or did) something similar for alt text at one point?

Because it's the preview site this doesn't feel especially urgent, but noting it as an idea for something that would be helpful.

**Comment by rcantin-w** [comment]
in prod
