### ISSUE TITLE
Reset password flow not working correctly

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#7777]
**What**

The email received after asking to reset password is
- no longer pulling in the name (says 'undefined')
- no longer includes the link to reset the password on the button
- no longer includes the link to reset the password in the email text

Therefore the user is unable to reset their password.

**Where**

Password reset email

![image](https://user-images.githubusercontent.com/1446072/157414673-f8fd1eda-bfa7-4ee2-ae17-8dfcb53ac88e.png)

This is what's expected

![image (1)](https://user-images.githubusercontent.com/1446072/157414776-dd5a17c0-dd63-4716-9c00-66316a083138.png)

**Comment by pollecuttn** [comment]
Mitigation for logging in is that people can still reset their password from the 'Forgot password' link via https://search.wellcomlibrary.org.

**Comment by jamieparkinson** [comment]
Oops, this'll be my fault! Will take a look shortly
