### ISSUE TITLE
Requesting: 'Cancel' button places request instead of cancelling it

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#7782]
**What**

The 'cancel' button places a request. It should cancel not place the request.

NB
The x closes the modal as expected
'Confirm request' places the hold as expected

**Where**

![cancel](https://user-images.githubusercontent.com/1446072/157436127-42dca739-987b-4d25-8c44-f892b3a2dd1b.PNG)

### TODO
- [ ] Make the cancel button cancel the request

**Comment by cbowskill** [comment]
Just re-tested and cancel now working as expected.
