### ISSUE TITLE
Phase 1: Membership (replicate existing form)

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7808]
# What is it and who's it for?
We currently have a pre-registration form on https://catalogue.wellcomelibrary.org/selfreg which captures limited information on users applying for library membership. This was designed to enable users to pre-register before coming to the building and allow them to access functionality such as Requesting in advance to being a full library member.

We would like to migrate this sign up process to wellcomecollection.org to sit alongside the new login/requesting flows for existing members and to minimise the disruption and change in experience between signing up/registering and logging in/requesting.

It is likely membership will be formed of multiple phases:
- **Phase 1** will migrate the existing form
- **Phase 2** will look at how to capture additional data fields (e.g. address)
- **Phase 3** will tackle how to align the offline experience.

# User story
As a non-library member
I want to create an account
So that I can request materials to see on my library visit

## Acceptance criteria

1. Introductory text explaining membership, how to apply for it and next steps. This text should be easily amended / managed.
2. The ability to capture multiple, mandatory fields (First name, Last name, Email address, Confirm email address, Password, Confirm password)
3. The ability show, link to and capture acceptance of Terms & Conditions
4. Validation of fields, including clear, error messaging/prompts for users
5. For the form to fail if mandatory fields aren't completed and validated successfully
6. For a clear, comprehensible and actionable error message to show if there are issues with submitting the membership application
7. For the form to progress to confirmation if fields are completed and validated successfully
8. The ability to show and link to Terms & Conditions and Privacy Policy

## Measurement
- Visits to page

## All Phase 1 stories
#7808 - Replicate existing form
#7809 - Confirmation of application
#7811 - Verification of email
#7812 - Update sign in
#7814 - Update editorial content
#7815 - Reporting
#7848 - Temporary member messaging - account

**Comment by DominiqueMarshall** [comment]
Replication of existing online application form:
https://zpl.io/9qkgNnY

I've also included copy (originally from the paper form) about accepting the conditions of use. It's more of an explicit message about what they're accepting (more so for anyone that will inevitably check the box without actually reading the full terms)

**Comment by DominiqueMarshall** [comment]
Thanks Carla, I've updated the designs and added some comments

**Comment by DominiqueMarshall** [comment]
Updated the design slightly to include a line about agreeing to the T&Cs and Privacy Policy above the button: https://zpl.io/NwkyMed

Also created a secondary design option for the page: https://zpl.io/8lkxe8J

**Comment by melanierogan** [comment]
Right now we use auth0 to log users in to request items (i know, stating the obvious). Auth0 gives us different options of how we make that all work, we are currently using what auth0 call :sparkles: [universal login](https://auth0.com/docs/authenticate/login/auth0-universal-login/new-universal-login-vs-classic-universal-login) :sparkles: .
Universal login has restrictions on how users sign up, see the video [here](https://wellcome.slack.com/archives/CUA669WHH/p1649236462824459?thread_ts=1649236026.186489&cid=CUA669WHH) that illustrates it. (we can customise some wording and how this modal looks, as we do for the login currently) 

Basically, using universal login/sign up will mean we only ask a user for an email address and password to sign up. You can add custom actions to show other fields, but the initial part of the flow is someone giving their email and setting a password (auth0 helps us validate both inline). Jamie has illustrated [3 approaches](https://github.com/wellcomecollection/identity/issues/284) to making this work for us but I wanted to show you what it would mean if we continued to use universal login. Taking the bare minimum details (email and password) and then asking for more is progressive profiling, Jamie mentioned [here](https://wellcome.slack.com/archives/CUA669WHH/p1648653119231419).

I did a short spike on how possible option 2 was, more details are in the related ticket [here](https://github.com/wellcomecollection/identity/issues/284). 
The upshot being:  We can continue to use universal login for membership work by just adding one step to the start of the user flow [here](https://wellcome.slack.com/archives/CUA669WHH/p1649253736914659?thread_ts=1649236026.186489&cid=CUA669WHH), email and password first. (To see video of the sign up process from sandbox account click [here](https://wellcome.slack.com/archives/CUA669WHH/p1649253736914659?thread_ts=1649236026.186489&cid=CUA669WHH))

**Comment by pollecuttn** [comment]
Re the phases mentioned above:
phase 1 is definitely worth finishing and getting live
we may then possibly look at 2, depending on how things are starting to settle and how much further change is required in eg content too
3 is i think definitely out of scope for now
(pers comm from Alex)

**Comment by pollecuttn** [comment]
@DominiqueMarshall Question about the wording on the registration form:

> After you complete the registration form, you’ll need to email a form of personal identification (ID) and proof of address to the Library team in order to confirm your membership. Your membership will be confirmed within 72 hours.

As we've just been closed for 96 hours, and the library closes for longer over the Christmas/New Year period, is that wording that LE&E suggested and are happy with? I don't want to get into fiddling with copy for unusual closures, but also don't want to give expectations that we know won't be met.

**Comment by DominiqueMarshall** [comment]
@pollecuttn that was copy written such a long time ago and LE&E were happy with it, but it's probably worth removing the line "Your membership will be confirmed within 72 hours"
