### ISSUE TITLE
Phase 1: Membership (verification of email)

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7811]
# User story
As an organisation
I want to verify a users email address
So that we have a way of contacting them about their account services

As a user
I want to verify my email address
So that I know I've signed up with the correct email address

## Acceptance criteria

- After successfully registering for an account, a user should receive a verification email to their account
- The verification email should contain information that's relevant for both users registering for the first time and users that are changing their email address
- The verification email should have easily editable text
- The verification email should contain a unique url to enable verification to occur
- If the verification URL has previously been used or has expired, a relevant error message should display
- If the verification URL is valid, this should confirm the email address and prompt the user to sign in

## Measurement
- Emails sent, Open rates, Bounce rates (medium)
- Page views (low)
- Clicks on account sign in (low)

## All Phase 1 stories
#7808 - Replicate existing form
#7809 - Confirmation of application
#7811 - Verification of email
#7812 - Update sign in
#7814 - Update editorial content
#7815 - Reporting
#7848 - Temporary member messaging - account

**Comment by DominiqueMarshall** [comment]
Current email verification design: https://zpl.io/7wkrZ6j

**Comment by melanierogan** [comment]
This verification email is sent at the initial part of a user's registration, as soon as they give us their email address and password. They are redirected to the full registration form after they give an email address and password. The email verification copy should be updated to reflect this.
