### ISSUE TITLE
Requesting: Minimise errors relating to changing/reseting password

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7816]
# Background info
We've noticed a small amount of errors whereby Sierra rejects a changed/reset password and shows a generic 'something went wrong' error to the user.
This is because Sierra has rules about 'trivial patterns' in password.

However, we can't replicate the rules using auth0 so need to explore what possibilities exist to improve this.

Note: Whilst it is a relatively low issue now, it will become more of an issue when we create the new membership form.

# User story
As a user
I want to know why my password change isn't working
So that I can provide a password that does work / meets the relevant requirements

## Acceptance criteria
1. When a password is not accepted due to various rules, display a more useful error message

**Comment by melanierogan** [comment]
Conversation around this started in slack https://wellcome.slack.com/archives/CUA669WHH/p1646993784790919

**Comment by melanierogan** [comment]
![Screenshot 2022-04-04 at 16 29 19](https://user-images.githubusercontent.com/16557524/161593490-3b8ff3de-91f8-4ba6-bf6b-cb4ee8d76f99.png)
