### ISSUE TITLE
Stories optimisation

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7819]
# Background
There are a number of challenges that exist around how we currently allow users to access stories on the site. We want to address these challenges and put in place a number of optimisations, being mindful of the work around discoverability / concepts that will be coming at a point in the future.

# User story
As a product owner
I want to understand the current pain points and opportunities that sit within Stories
To enable us to prioritise and implement changes that will improve these

## Acceptance criteria
1. Gain a clear understanding of user needs
2. Gain a clear understanding of organisational needs
3. Prioritised view of changes based on value and feasibility

**Comment by alexwlchan** [comment]
I'm going to close this as done – this was a precursor to the Stories optimisation work we've been doing. There's more work to do here, but we should create a new ticket if/when we want to make the next round of improvements.
