### ISSUE TITLE
Evaluate use of location filters relative to the other filters

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7820]
**We want to know if the following change has improved the user experience**
Provision of separate location filters on search bar

If users use location filters before any other filters, we will know the placement is helpful.

If users don't use location filters until they've tried the other filters, we could move the location filters into More filters and free up some space on the search bar.

**Comment by taceybadgerbrook** [comment]
Analysis of the 100,000 most recent records in Elasticsearch consisted of 551 users who used filters in their searches. Of these, 100 users used the location filters. So it appears these filters are proving useful.

To find out whether they are the first port of call for users, a dataframe of the first filters used was created. Here are the results:

|Filter name|How many times was this the first filter used?|
|:------|:--------|
|subjects|175|
|workType|146|
|contributors|117|
|location|72 (66 online, 6 in-library)|
|genres|47|
|dates_from|46|
|dates_to|44|
|languages|7|

**Comment by taceybadgerbrook** [comment]
[Repo link for Jupyter notebook](https://github.com/wellcomecollection/data-science/blob/main/notebooks/analysis/notebooks/location.ipynb)

**Comment by jtweed** [comment]
Thanks @taceybadgerbrook that's super useful and supports the decision to go back to treating location like any other filter.
