### ISSUE TITLE
Phase 1: Membership (partially-registered member messaging - account)

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7848]
# User story
As a library member
I want to know what I can / can't do online and why
So that I can take any necessary steps

As an organisation
We want to provide useful information about a users membership
So that they know what to expect and how to get access to the things they need

## Acceptance criteria
1. Temporary members are shown a custom message in their account stating what they can/can't do and how to get access to additional services.
2. Custom message shown should be easy to amend / edit and remove
3. When a member is upgraded to a different patron type, this message should no longer display

## All Phase 1 stories
#7808 - Replicate existing form
#7809 - Confirmation of application
#7811 - Verification of email
#7812 - Update sign in
#7814 - Update editorial content
#7815 - Reporting
#7848 - Temporary member messaging - account

**Comment by DominiqueMarshall** [comment]
Initial account page messaging: https://zpl.io/7wzK4QE

**Comment by melanierogan** [comment]
We need to clarify what a user can and cannot do here, there was some confusion.
