### ISSUE TITLE
Audio player appears when item is restricted

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#7861]
**What**

The digitised audio player is not taking into account when items are restricted. This means that the player is added to the page, but the audio stream request is unauthorised and the user gets an error.

**Where**

There is an example of this here:

https://wellcomecollection.org/works/ae9m5mbx

The Catalogue API has the digitised item as restricted and the IIIF manifest describes the item as requiring authentication.

**Comment by alexwlchan** [comment]
Fixed – restricted audio items no longer show a player.
