### ISSUE TITLE
Evaluating new location filter usage

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#7968]
As an analyst,

I need to be able to identify location drop down usage in metrics-conversion-prod:-

Closed stores
Open shelves
Online

So that I can evaluate the user experience.

**Comment by harrisonpim** [comment]
looks like the data was already being collected!

**Comment by taceybadgerbrook** [comment]
page.query.availabilities.keyword=*

can take values: online, closed-stores, open-shelves, (online, closed-stores)
