### ISSUE TITLE
Audio guides: Readying prototype for testing

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#7978]
### Background
Creating a live prototype to align the online and offline experience for those visiting exhibitions. The prototype needs to be able to demonstrate different exhibitions and different tour types within those exhibitions. 

The prototype will show 4 different tour types :
- An audio tour without descriptions
- An audio tour with additional audio descriptions
- BSL content
- Gallery captions and transcriptions of gallery content

### Prototype goals
We need to confirm whether the language used to describe tour types is understandable to users
Confirmation that the journey makes sense to users
That visitors would want the content described within the prototypes
That the prototypes make sense to those using accessibility tools

**Comment by pollecuttn** [comment]
Waiting for testing results to come in.
