### ISSUE TITLE
create terraform files to deploy action

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8006]
We need to make sure terraform is set up to deploy the newest action, and we'll have included env variables/secrets for auth0 action.

**Comment by jamieparkinson** [comment]
For the deployment itself to happen you'll also need to add the name of the action file here: https://github.com/wellcomecollection/identity/blob/main/.buildkite/scripts/auth0-deployment.sh#L10

**Comment by jamieparkinson** [comment]
Ah you've already done it!
