### ISSUE TITLE
Update the 404 and 500 pages with the new copy from the Editorial team

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8032]
Lalita has sent me new copy for the 404 and 500 error pages, which are currently hard-coded in the ErrorPage component. They're several sentences of rich text; longer than the one-line strings we have in the microcopy file. (See [404page_final.docx](https://github.com/wellcomecollection/wellcomecollection.org/files/8778630/404page_final.docx), [500_page.docx](https://github.com/wellcomecollection/wellcomecollection.org/files/8778626/500_page.docx))

It would be nice if the Content team could manage this text themselves, without needing us in the loop.

## Proposal

We store this text in Prismic, and retrieve it as part of the server-data. When we need to render an error page, we return the text from the server-data. (We don't want to fetch it when we render the page, because we might be erroring because Prismic is down!)

How you'd do this:

* Create two new pages in Prismic for `404 Not Found` / `500 Internal Server Error`
* Update the server-data to fetch the body of these pages
* Update the ErrorPage component to use these pages when an error occurs

For neatness, I would redirect the `/pages/<404 page ID>` to `/404`, similarly for `/500`, so users can't find these pages accidentally. Then make those endpoints return the appropriate status codes, which is useful for testing.

**Comment by dannybirchall** [comment]
+1 from the editorial team, I think that this would work for us

**Comment by alexwlchan** [comment]
In hindsight, this ticket is really two things I've coupled unnecessarily:

1. Add the text for the new error pages
2. Make the error pages configurable in Prismic

We can do (1) without touching (2), and we should to unblock this.

**Comment by dannybirchall** [comment]
@alexwlchan sounds good. do you have the text you need from the editorial team?

**Comment by alexwlchan** [comment]
I already have it, Lalita sent it weeks ago!

**Comment by alexwlchan** [comment]
This is done; for now I'm going to drop the bit about making them editable in Prismic.

It's a non-trivial amount of work to add it to the server data block, and you still need some fallback text if the error is that we can't get server data.

I have moved it into the `data` directory, so it'll be easier to find and modify in future.
