### ISSUE TITLE
Create updatePatron method in sierra-http-client (refactoring updateBarcode into a generic updatePatron method)

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8073]
We need a generic sierra-http-client method to `updatePatron` - I can refactor updateBarcode to include this, as well as firstName and lastName

**Comment by jamieparkinson** [comment]
Apologies if I've missed some reasoning/requirement somewhere - what's the reason for creating different use-case-specific mutation functions rather than the client having an all-purpose `updatePatron` function that's used everywhere?

**Comment by melanierogan** [comment]
I got a bit stuck on the specific updating of a barcode and didn't think i'll eventually need the same kind of function for first and lastnames. I think an all-purpose updatePatron method is the better way to go, I'm going to adjust my PR to do that
