### ISSUE TITLE
Audio guide: Data modelling

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8105]
# User story
As a Wellcome dev
I need to devise a data model 
so that the data held in prismic is reused in the correct places on the digital guide

# Implementation

- Look at repetition of data within the digital guides
- Explore whether that data exists currently within the website
- Identify fields we need from the content team
- Identify how the data will be collected

**Comment by gestchild** [comment]
[Proposed data model for discussion](https://docs.google.com/drawings/d/1VWOC3My2FxE3vfp81hbj-YQLQqArr-T19iAA1odI7Ec/edit?usp=sharing)

This should work for most of what is required and covers the prototype functionality. There are some outstanding questions regarding captions that aren't associated to gallery stops and what is required for sections.

![Accessibility Guides model](https://user-images.githubusercontent.com/6051896/178000267-cfef7a1d-8177-4b59-b83e-ae4eb5645139.png)

![Accessibility-Guides-model](https://user-images.githubusercontent.com/6051896/178000318-d70fff38-2650-4254-9700-8322c59a51ba.gif)

**Comment by dannybirchall** [comment]
I *think* that we might be creating more problems than solutions if we try to map the structure of a tour directly to the structure of the gallery labels. Gallery labels can come in groups (one label = several objects) or be simply tombstones (object data only, no interpretation) and sometimes take other forms dependent on physical presence (eg referring to another nearby object).

**Comment by gestchild** [comment]
[Latest model, following meeting to discuss it](https://docs.google.com/drawings/d/1VWOC3My2FxE3vfp81hbj-YQLQqArr-T19iAA1odI7Ec)


![Accessibility Guides model (2)](https://user-images.githubusercontent.com/6051896/178750583-f1d58c4e-e7bd-4e08-9ea3-01e21b15f8a5.png)


There are a few outstanding questions, but we've got enough to start getting this into Prismic, so we can start rendering pages locally and hopefully clarify any outstanding issues.

**Comment by dannybirchall** [comment]
Butting in here to ask -- how much of this model is to do with the way the exhibition is structured, and how much to do with the way that the guide is experienced by users? Are we breaking the scope by trying to model the the exhibition rather than the guide?

**Comment by melanierogan** [comment]
[The model is now in place](https://docs.google.com/drawings/d/1G_NZTRnDLn7WgN8_ZvPMnk9tVF-ws8lnskJXhSJ30c4/edit). We know we will need to make some changes to implement a hierarchy.

![Image](https://user-images.githubusercontent.com/16557524/180953073-19c92052-1ed4-452f-b2a2-c57bff67fb31.jpg)

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
