### ISSUE TITLE
Audio Guides: Data modelling - communication

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8106]
# What is it and who's it for?

# User story
As a Wellcome dev 
I need to communicate the agreed data model 
so that the rest of the team are clear about what content is required and where

# Implementation 
Create a schema of the data model that communicates effectively to the wider team how the data links together and any dependencies

## Acceptance criteria
- [ ] The team understands the data model for guides

Follows https://github.com/wellcomecollection/wellcomecollection.org/issues/8105

**Comment by melanierogan** [comment]
<img width="1220" alt="Screenshot 2022-08-03 at 12 05 07" src="https://user-images.githubusercontent.com/16557524/182593967-8ad625cc-1982-464d-a545-5af2700104db.png">
<img width="1220" alt="Screenshot 2022-08-03 at 11 36 48" src="https://user-images.githubusercontent.com/16557524/182593974-89e4e7ae-3a6f-43cc-9ad2-3c3add8a0954.png">
<img width="1429" alt="Screenshot 2022-08-03 at 11 30 45" src="https://user-images.githubusercontent.com/16557524/182593980-b33a2f06-ac50-431d-9ca6-b406dade653e.png">

**Comment by melanierogan** [comment]
The guidance on creating an exhibition guide in [Notion](https://www.notion.so/wellcometrust/How-to-Add-an-exhibition-guide-in-testing-c31cfc733d4f4ad095b5033ceaae57c5)
