### ISSUE TITLE
Audio guides: play audio guide

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8110]
# User story
As a blind/partially sighted Wellcome visitor
I would like to use my screen reader to play audio guide content on my apple/android phone
so that I can understand what is in the gallery

## Acceptance criteria
- [ ] A visitor can play audio guides on their phone

## Testing and tracking
- [ ] How many have clicked to play
- ~[ ] How long did they play for~
After talking to Tacey it was decided this wasn't required:

"Regarding what we want to track, I'd look at it from the results end. We don't really care about how many times Person A played/paused or how many people made it through to 90%.

We do care whether anyone is listening to audio and using the feature (otherwise why build it.) So I'm thinking if I am analysing this in GA, I'd be looking at the number of users who trigger Event Action = play audio and numbers of users who use pause or skip to get a percentage of users who used the pause and skip functionality. I don't think it makes sense to track the amount that users listen to because of the range in track length."

- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

**Comment by davidpmccormick** [comment]
Moving this back for now. While the AudioPlayer component has been created ready to serve the needs of this ticket, it can't really be _done_ done until we have the templates in place for the exhibition guides.

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
