### ISSUE TITLE
Audio guides: change speed of audio playback

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8111]
# What is it and who's it for?

# User story
As a Wellcome visitor
I would like to use my screen reader to speed up audio content
so that I can listen to the guides at a faster pace

## Acceptance criteria
- [x] A visitor can change the speed of audio playback on their phone

## Testing and tracking
- [ ] Were the speed controls used
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

**Comment by pollecuttn** [comment]
@davidpmccormick can this be closed?

**Comment by davidpmccormick** [comment]
yes
