### ISSUE TITLE
Audio guides: understanding track length

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8112]
# User story
As a Wellcome visitor
I would like to use my screen reader to detect how long a track is in the audio guide
so that I can choose whether to listen or not

## Acceptance criteria
- [ ] A visitor knows how long a track is

## Testing and tracking
- Qual and/or Quant test plan - Alice and Tacey

**Comment by pollecuttn** [comment]
@davidpmccormick can this be closed?

**Comment by davidpmccormick** [comment]
yes
