### ISSUE TITLE
Digital guides: Prototype UX design iteration

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#8147]
## User story
As a Wellcome Product Designer
I need to ascertain what the next iteration of the audio guides prototype will look like based on feedback from user research

## Implementation
- confirm the design aligns with the current WC design system
- review the legibility of the transcripts and captions
- Identify opportunities for increasing the visual accessibility (i.e. adding iconography to match the in-building experience)
- Review the mobile responsiveness/design mobile-first

## Acceptance criteria
 TBD

**Comment by DominiqueMarshall** [comment]
Design iterations are available to [view on Zeplin](https://zpl.io/KGAnw78). As we want to make it clear this is a separate entity from the main WC website, I haven't included the main navigation links or the footer in the designs. Instead, the footer includes links to the other exhibition guides that are available to use.

Also, FYI - the colours used are not set in stone yet and will need formalising.

Exhibition Guides landing page (_the 'Exhibitions Guides' link in the nav would go here_): https://zpl.io/qyAPZkJ
Specific exhibition landing page: https://zpl.io/MdQ8kjJ
Audio guides without descriptions: https://zpl.io/o1R4r0G
BSL videos: https://zpl.io/xmDO5nX
_Audio guides with descriptions page coming soon..._

@davidpmccormick @melanierogan @gestchild @alexwlchan @alicerichmond @dannybirchall - There are 3 design variations of the Captions & Transcripts page below. It would be great to get some feedback on what you feel the most plausible structure would be development-wise, both in the short-term and in the long-term, plus any other feedback/questions you might have.

**Version 1:** https://zpl.io/406Y3Ep
**Mobile:** https://zpl.io/ykdwjW9
This includes headings based on the four main areas within the exhibition In plain sight (following the floor plan). The 'section text' has a full-width background to differentiate it from the item captions and transcripts.

**Version 2:** https://zpl.io/Em6vYdl
**Mobile:** https://zpl.io/YYNZdoE / https://zpl.io/Z04y9n1
This version builds on version 1 and includes a dropdown 'menu' with anchor links to the headings on the page. Ideally, the "show exhibition content" button would remain sticky so it could be accessed no matter how far down the page you reach.

**Version 3:** https://zpl.io/vM5qGne / https://zpl.io/NwG7REQ
**Mobile:** https://zpl.io/096WkwQ / https://zpl.io/r1gnyLX
Chunking up the different content areas into accordion-style navigation, giving users the ability to see in-page how many areas there are in the gallery space.

**Comment by alexwlchan** [comment]
Quick thoughts (having clicked straight through before reading the commentary):

* On version 2, it wasn't clear to me what "Hide/show exhibition content" was doing. Until I'd clicked through the designs a couple of times, I didn't realise what it meant.
* On version 3, I think the tricky part about the accordions will be making sure they auto-expand if somebody scans a QR code (and especially if they don't have JavaScript enabled).

Question for Mel and Gareth: does the current model allow for putting in the section text?

**Comment by davidpmccormick** [comment]
We don't currently (I don't think) have a style for a thing that is a button that looks like a link (e.g. for the "+ Read full transcript" buttons). We can make one if we think it'll be useful elsewhere, or we can do a one-off for this thing, or we can use a solid or outlined button.
