### ISSUE TITLE
Phase 1: membership journey - text updates

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#8160]
A few text updates based on feedback from the library team - new mockups below:

![Image](https://user-images.githubusercontent.com/60890140/179483756-020754e6-acfe-414d-a6a6-1f9d30b443c2.jpg)

### Apply for a library membership
With a library membership and online account, you’ll be able to:

- Request up to 15 items from our closed stores to view in the library
- Access subscription databases, e-journals and e-books

**Note:** To access subscription databases, e-journals and e-books, you’ll need to bring a form of personal identification (ID) and proof of address to the Library admissions desk to confirm your membership.

You don’t need a membership to visit the Library to do your own quiet study. You can collect a day visitor pass from the Library admissions desk on each visit.

![Image](https://user-images.githubusercontent.com/60890140/179483771-2b1f0672-5c95-407d-a39b-267bc1ac2b4d.jpg)

![Image](https://user-images.githubusercontent.com/60890140/179483782-a74aafb6-23b9-4ac5-aeb0-6a88f323cdb6.jpg)

### Application received

Thank you for applying for a library membership.

Please click the verification link in the email we’ve just sent to [USER EMAIL ADDRESS].

Please do this within the next 24 hours.

Once you have verified your email address, you will be able to request up to 15 items from our closed stores to view in the library.

If you want to access subscription databases, e-journals and e-books, you need to bring a form of personal identification (ID) and proof of address to the admissions desk in the library.

**Comment by DominiqueMarshall** [comment]
@davidpmccormick @melanierogan Would it be possible to make these changes to the text today?

**Comment by alexwlchan** [comment]
Closing as done.

**Comment by DominiqueMarshall** [comment]
Another quick update to the Note so it's clearer that ID isn't just needed to access subscription resources.

Note: To complete your membership and access subscription databases, e-journals and e-books, you’ll need to bring two forms of personal identification (ID) to our admissions desk in the library.


![Image](https://user-images.githubusercontent.com/60890140/179952976-d0cd1c9c-e94a-466b-87ff-1d2a4a98adb0.jpg)


To complete your membership and access subscription databases, e-journals and e-books, you’ll need to bring a form of photo identification (ID) and proof of your address to our admissions desk when you visit. The identification we accept is detailed on our Library membership page.

![Image](https://user-images.githubusercontent.com/60890140/179953330-8b6de297-a9fd-41f8-b278-3159383a25f7.jpg)
