### ISSUE TITLE
Image saturation

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#8161]
[As reported by Ben](https://wellcome.slack.com/archives/C8X9YKM5X/p1657903584168429):

"Prismic seems to have started doing something funny with the presentation of colour in images. There seems to be a general desaturation, perhaps it’s stripping out the sRGB colour profile during upload?

See example below. The browser windows both show the same image file. On the left the image is display after Prismic’s done its thing whilst the image on the right is just displaying the original image in the browser, loaded from my desktop."

![Screenshot 2022-07-15 at 17 39 42](https://user-images.githubusercontent.com/6051896/179485560-e0ae98d9-0371-4781-8b6e-e88f91f3d6ca.png)

Prismic shouldn't be doing anything to the uploaded image. For the displayed images, Prismic uses the imgix service, [which can alter the image saturation](https://docs.imgix.com/apis/rendering/adjustment/sat). But the default is to leave the saturation unchanged.

Needs further investigation.

**Comment by LFBaily** [comment]
I have followed up to find out if this is still considered an issue, otherwise I'm closing it.
