### ISSUE TITLE
Spacing around the breadcrumb is wonky

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8184]
See https://wellcomecollection.org/pages/X_2eexEAACQAZLBi:

<img width="940" alt="Screenshot 2022-07-20 at 10 05 21" src="https://user-images.githubusercontent.com/301220/179943293-2233d1b8-097d-4426-adbb-a09b4ef36183.png">

**Comment by alexwlchan** [comment]
`git bisect` points to this commit as the issue: https://github.com/wellcomecollection/wellcomecollection.org/commit/253c79119c4d6109b42f651e2a25738dc867595e

@davidpmccormick one for you?

**Comment by davidpmccormick** [comment]
Fixed in #8186
