### ISSUE TITLE
As Wellcome developer I need to investigate the options for users to set device preferences so that the best solution can be used

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8188]
**Acceptance criteria**

Agree on the choice of approach to allowed users to set preferences
Understand what privacy details we will need to have the visitor to accept for it to be legal

Timebox this ticket to no more than half a day

**Comment by alexwlchan** [comment]
So my rough thinking is:

* We have this URL structure:

     ```
     /guides/exhibitions/<id>
     /guides/exhibitions/<id>#stop
     /guides/exhibitions/<id>/<content-type>
     /guides/exhibitions/<id>/<content-type>#<stop>
     ```

* Whenever somebody visits the content-type for a given exhibition guide, we record something (a cookie, local storage) telling us what they were looking at:

     ```javascript
     window.localStorage.setItem('exhibition-guides:123:format', 'audio-with-description')
     ```

     This follows a simple "latest visit wins" rule – if I look at a BSL page and then I visit a described audio page, this value will be 'described audio'.

* In the QR codes, we include a query parameter to tell us somebody is coming from the in-gallery experience:

    ```
    /guides/exhibitions/<id>/<content-type>#stop?using_qr_code=true
    ```

And then we use the following flow:

```mermaid
graph TD
    URL(user visits /guides/exhibitions/&ltid&gt) --> D{what is the<br/>using_qr_code<br/>query param?}
    D -- false --> F[show the user<br/>a list of options]
    D -- true --> T{does the user<br/>have a pref set?}
    T -- no --> F
    T -- yes --> S[show the user<br/>the specific guide]
```

**Comment by melanierogan** [comment]
I think we can probably use the “cookie-cutter” package we have for this.

**Comment by alexwlchan** [comment]
To recap some discussion at standup: we want to be super-duper conservative about the behaviour here.

We will only remember your media guide preference:

* within a single exhibition (if I visit _Rooted Beings_ and use the BSL guides, and then I visit _In Plain Sight_, I have to pick what sort of guide I want)
* for no more than 24 hours (if I visit on Monday and then I come back on Tuesday, I have to pick what sort of guide I want again)
* if I haven't navigated back to the guide picker (if I use the BSL guide and then I explicitly navigate back to the guide picker, I have to pick what sort of guide I want when I scan the next stop)

**Comment by melanierogan** [comment]
I moved a little further with this and looked at `[cookies-next](https://classic.yarnpkg.com/en/package/cookies-next)` which allows for the getting, setting and removing cookies with next.js. This means we can, in theory, set and get the cookies in either client or server.

**Comment by melanierogan** [comment]
Started to research best way to do this with `cookies-next` in a branch [here](https://github.com/wellcomecollection/wellcomecollection.org/blob/feat/EG-cookie-preferences/content/webapp/pages/exhibition-guide.tsx)

**Comment by alexwlchan** [comment]
Closing as this is in the Done column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
