### ISSUE TITLE
As a Wellcome content team member I need upload video and audio content to Prismic so that it is available to be used in the relevant template

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8189]
**Acceptance criteria**

Ability to upload digital content and use it within a template for a tour type
Identify details around how to name the files 
Identify any opportunities to make finding and choosing the digital guide tracks within the prismic interface easier

**Comment by pollecuttn** [comment]
Reminder of best way to add metadata

**Comment by alicerichmond** [comment]
* Identify good searching tactics in prismic
* What meta data is useful to put against an MP3 file in particular
* Provide a list of suggestions for the content team

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
