### ISSUE TITLE
As a Wellcome content team member I need to be able to set the information for each stop in the audio tour and add the relevant media content

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8190]
**Acceptance criteria**

Exhibition title - automatically?
Exhibition introduction content - automatically?
A content team member is able to set the title for each stop
Ensure that the audio is correct
The stop number
QR code URL

**Comment by pollecuttn** [comment]
Dev + @dannybirchall

**Comment by alicerichmond** [comment]
Tied to the preferences conversation about setting the parameters for the QR codes and URLS

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
