### ISSUE TITLE
As a Wellcome content team member I need to be able to set the information for each stop type in the Video tour and add the relevant media content

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8191]
**Acceptance criteria**

Clear field labelling
All fields are able to be completed by a content team member
Exhibition title - automatically?
Exhibition introduction content - automatically?
A content team member is able to set the title for each stop
Ensure that the Video is correct
The stop number
QR code URL 
Ensure that a content team member is able to successfully upload and add content without having to use work arounds

**Comment by pollecuttn** [comment]
Dev + @dannybirchall

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
