### ISSUE TITLE
Producing YouTube stats for KPI Tracker and quarterly report

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8214]
**What is the problem to solve?**
YouTube organises exported data by video Id, not title. Catch up event videos cannot be identified by url in GA. In the past, I've had to analyse video viewing time by manually updating a lookup table for catch up event videos but this takes at least 1h to compile and is error-prone.

**What are the objectives?**
Produce quarterly totals of:
- unique views 
- watch time

**What research technique is required?**
YouTube Analytics

**Comment by taceybadgerbrook** [comment]
YouTube reporting is problematic due to the enduring popularity of certain videos such as Dissecting Brains. For this reason, reporting total views and total watch time per quarter doesn't actually help when monitoring more recently produced material.

YouTube Studio has a feature called playlists. Including a video in a playlist doesn’t tag the actual video, ie attach any information to help identify it when conducting analysis. What this does is curate videos into a listing that channel viewers can refer to. Any channel owner can add any video (not just their own) in their playlists. One channel can have many playlists.
 
The closest I can get to reporting views and watch time for Catchup events is reporting the playlist index page itself and adding this to the views and watch time for videos referred by the [Events at Wellcome playlist index page](https://www.youtube.com/playlist?list=PL1C12C48F8E360BC2). It’s not perfect (there are 29 videos that are not Catch Up Events in the Events at Wellcome playlist) but it’s better than reporting all video views and watch time.

**Comment by taceybadgerbrook** [comment]
The closest I can get to reporting views and watch time for Catchup events is reporting the playlist index page itself and adding this to the views and watch time for videos referred by the [Events at Wellcome playlist index page](https://www.youtube.com/playlist?list=PL1C12C48F8E360BC2). It’s not perfect (there are 29 videos that are not Catch Up Events in the Events at Wellcome playlist) and it excludes data from viewers who arrive at the videos direct.

Here's a screenshot of what this would look like:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/32418070/180832297-5523725d-6fd0-41c7-91ff-8bd1c7e00919.png">

**Comment by taceybadgerbrook** [comment]
I don’t think this methodology is suitable for KPI reporting as it excludes activity when viewers come to the video direct. By way of comparison, during Q3, the video, “Milk and Whiteness” attracted 652 views for a total of 138h.

**Comment by dannybirchall** [comment]
@taceybadgerbrook does the attached file have all the data we need -- would it be any quicker to filter what we report from that?

[content_2022-06-24_2022-07-22_wellcome_collection.xlsx](https://github.com/wellcomecollection/wellcomecollection.org/files/9188879/content_2022-06-24_2022-07-22_wellcome_collection.xlsx)

**Comment by taceybadgerbrook** [comment]
@dannybirchall Thanks for the file. The problem is it has all the data we need and then some. Tom wants a YouTube report that only tracks Catch Up Events. I can't do this unless I create and maintain a lookup table tagging videos as Catch up. 

This involves scanning the Catch up page for new videos each quarter, exporting the data, matching, fixing the lookup because the video Ids aren't always present and names don't always match, updating for variants on video names and then using a pivot table to compile the data. 

The process is fiddly but more worrying, it is error prone. Hence the interest in reporting by playlist.

**Comment by taceybadgerbrook** [comment]
@dannybirchall I think I've spotted a way forward. Are you the owner of the YouTube channel? If so, can you download the Events at Wellcome video title listing?

**Comment by dannybirchall** [comment]
apparently I'm not a channel owner!

**Comment by taceybadgerbrook** [comment]
Darn.

From: Danny Birchall ***@***.***>
Date: Tuesday, 26 July 2022 at 16:49
To: wellcomecollection/wellcomecollection.org ***@***.***>
Cc: Tacey Kobayashi ***@***.***>, Mention ***@***.***>
Subject: Re: [wellcomecollection/wellcomecollection.org] Producing YouTube stats for KPI Tracker and quarterly report (Issue #8214)

apparently I'm not a channel owner!

**Comment by dannybirchall** [comment]
@taceybadgerbrook what do you need? All the titles (the words in the titles) in this playlist?

https://www.youtube.com/playlist?list=PL1C12C48F8E360BC2

**Comment by taceybadgerbrook** [comment]
That would be the ideal but the problem would be that I'd need this produced each quarter.

I think I've hit upon a better (ie easier on the admin) solution: filter quarterly view data by published date and taking material from 2 years previous in an effort to include the old material recycled for season content.

**Comment by taceybadgerbrook** [comment]
Here's what the data looks like when it's been filtered by publication date:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/32418070/181286041-e385d76d-f0ea-48aa-8fa3-de919113a506.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/32418070/181287526-3b090e42-bb4c-4b09-af6b-b1e7d1fcac2c.png">

Sure, the 2 graphs are similar but the actual figures are much different. The downturn in the second graph is due to decreased views of Dissecting Brains whereas the relatively modest downturn in the first graph is due to fewer videos being release during Q3.

**Comment by taceybadgerbrook** [comment]
New compilation method agreed with Tom. Filter stats via YouTube Analytics/Advanced Mode/Filter by -2 years from start of quarter to end of reporting quarter.

New data for 202122 Q1-Q3 now pasted into Tracker spreadsheet.
[https://wellcomecloud.sharepoint.com/:x:/s/wc2/Ebvgs7ymb4ZBkWogIsgwjUABKfzIH_njm3FlCeDSC7CPnA](https://wellcomecloud.sharepoint.com/:x:/s/wc2/Ebvgs7ymb4ZBkWogIsgwjUABKfzIH_njm3FlCeDSC7CPnA)
