### ISSUE TITLE
Evaluate usage of exhibition guides:  In Plain Sight

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8252]
**We want to know if the following change has improved the user experience**
creation of exhibition guides

**Definition of success is**
guides are used while exhibition is open
guides are used after exhibition closes

**We'll know if we're succeeding if we measure the following metric and this happens**
All guides are on one page, so analysis of GA event category Audio by label.

**Comment by taceybadgerbrook** [comment]
Understand how the In Plain Sight guides are currently being used, identifying any potential pain points.

This analysis may involve setting up additional tracking in order to get the data we need.

Besides the analysis, an output of this work should be a slide deck that communicates the findings so colleagues across WC can read and understand.

Can we identify patterns of drop-off within an exhibition?
Can we identify any performance issues that inhibit page loading/rendering of content in gallery?
Are there differences in use depending on whether a person is using the guides remotely or in gallery (traffic from QR code)?
Are there differences in use depending on whether a person has accessed the guides via the exhibition page, or from QRcode?


Top-level metrics
Pageviews
Sessions
Exits
Page load speed /Last contentful paint https://web.dev/lcp/ (Note, we already have Google Lighthouse set up which could help test the relevant pages for LCP)


Traffic from:
QRCode - stopId
Exhibition page https://wellcomecollection.org/exhibitions/Yv95yBAAAILuCNv6 


On-page activity

Guide landing page
https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau

CTR to each guide type

Audio without descriptions
https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/audio-without-descriptions
28 audio files

Audio plays
Which files?
Which audio is first used?
Any data on avg duration of listen?

Captions and transcripts
https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/captions-and-transcripts

Clicks on show full transcript 
Which transcript?
Hide full transcript
Which transcript?

BSL videos
https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/bsl
28 videos

Video plays
Which videos?
Which video is first used?
Any data on avg duration viewing?

Change guide type CTA
-- goes back to
https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau

%/number of users who use ‘Change guide type’ button
What do they choose next? 

Change exhibition CTA
-- goes back to
https://wellcomecollection.org/guides/exhibitions 

%/number of users who use the ‘Change exhibition’ button
What do they choose next?

**Comment by taceybadgerbrook** [comment]
How many times have users viewed the [guide landing page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau) since the exhibition opened on 20 October?

The page was viewed a total of 7,257 times 20 October - 27 November.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/32418070/204334327-822f6621-ad52-48aa-99ae-88130a6b4133.png">

**Comment by taceybadgerbrook** [comment]
Site visitors who used the QR Code viewed fewer pages on average than those users who did not access the site by the QR Code but their average session duration was much longer. This suggests a higher level of engagement because time has been spent listening to the audio guides instead of browsing the website.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/32418070/204755463-793b2218-7886-41be-b9fe-8472f4f06dad.png">

**Comment by taceybadgerbrook** [comment]
Looking at the guides accessed, the graph below shows a drop off after the introduction which is in keeping with analysis of previous QR code usage. It is interesting to note that only those who accessed the audio guides using the QR code actually went onto the individual guides; those who did not use the QR codes looked at the homepage only.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/32418070/204786379-261e0593-3964-4ce0-b123-f5ed030383b2.png">

Guides which appear to have been unusually unpopular having been used 6 or less times are numbers 17, 19, 20 and 29. This might be because the titles were not sufficiently enticing: Eyes on overtime, What We Wore archive, Let Me Be Seen and Acknowledgements.

**Comment by taceybadgerbrook** [comment]
Not surprisingly, audio player interactions follow a similar pattern to access. Either the novelty of the audio guides wore off after the third guide or the guides were too long to keep playing.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/32418070/204838633-eb3fe029-687f-4a9f-8495-11b5cf0aa99c.png">

Here is the same graph without audio guides 1-3:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/32418070/204838880-fb8c6d69-eb3e-4766-bba9-968f26987789.png">

To understand how useful visitors found the audio controls, here is the raw data:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/32418070/204839766-72f352a2-8261-41e7-817f-9a6527e5091b.png">

**Comment by taceybadgerbrook** [comment]
# 2. Captions and transcripts #

The [Captions and transcripts page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/captions-and-transcripts) has attracted 1,410 pageviews by 393 users since the exhibition opened on 20 October to 27 November.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/32418070/204845328-c9f417ed-9568-4d29-a35c-71614e4693ba.png">

**Comment by taceybadgerbrook** [comment]
Only 12% of users who used the QR Code in Gallery 1 accessed the In Plain Sight Captions and transcripts. The table below shows users who came to the website from organic search to be more engaged, spending more time on site and viewing more pages.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/32418070/205087607-efe83205-305e-4152-a61a-6d4b63b7087e.png">

**Comment by taceybadgerbrook** [comment]
# 3. Watch BSL videos #

The [Watch BSL videos](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/bsl) has attracted 313 pageviews by 122 users since the exhibition opened on 20 October to 27 November.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/32418070/205098611-96370723-6c3b-473f-9fb3-04acc724c21a.png">

**Comment by taceybadgerbrook** [comment]
Only 20 visitors representing 17% of all who viewed the Watch BSL videos page accessed this via the QR Code in Gallery 1.

**Comment by jennpb** [comment]
@taceybadgerbrook Would you mind linking to the Word doc you mentioned, and making edits in that rather than as separate comments on this issue? It'll just help us to review and discuss.

**Comment by taceybadgerbrook** [comment]
# Other observations #

Only 1 visitor who used the QR code in Gallery 1 went on to look at the Caption and transcripts and Audio guides pages for Gallery 2. Only 3 visitors who used the QR code in Gallery 2 went on to look at the Caption and transcripts and Audio guides pages for Gallery 1. None of the audio guides nor any of the BSL videos were played. 8 out of 652 or 7% of Audio guide pageviews for In Plain Sight were followed by clicks to change exhibition. 13 out of 925 or 8% of Captions and transcripts pageviews for In Plain Sight were followed by clicks to change exhibition.

On this basis, providing links to view guides for other exhibitions does not appear to encourage usage. Given that visitors can always go on to scan QR codes in other galleries, providing these links may actually be getting in the way of users navigating to guide content. 

One interaction that doesn't appear to be catered for is switching between guides within an exhibition. For example, if an audio guide user wanted to read more about certain exhibits in Captions and transcripts, it's easy enough to go to the audio guide page and scroll down to go back to the guide. If however, they wanted to return to the Captions and transcripts page later in the exhibition, they would find it very time consuming trying to find the appropriate text or check whether there was even any additional material available. Offering a comprehensive audio/transcript/bsl set of links for each stop might increase usage. For those visitors who require one type of guide over the others, they can still use the page for the one guide.

**Comment by taceybadgerbrook** [comment]
Here is a link to the original analysis guide:
https://docs.google.com/document/d/1H0y15MxidCFxy3bSwHMOCQ0AuEpEZFw6/edit?usp=drive_web&ouid=108386386272730213157&rtpof=true

**Comment by taceybadgerbrook** [comment]
These tickets have been created to try and develop the guides further:
#9007 
#9008 
#9009 
#9010
#9011 
#9012
