### ISSUE TITLE
Evaluate effect of wellcomelibrary.org redirect to wellcomecollection.org

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8253]
This graph shows wellcomelibrary.org user numbers since January 2019 which shows around 1,500 users leaving in March 2021: 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/32418070/190494516-a24f68f7-0910-4912-ba03-5498a09f35f2.png">

This graph shows wellcomecollection.org user numbers for the same period:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/32418070/190496580-7c57568d-c7ec-4987-a0a2-601bf4638a93.png">

Although user numbers do increase during 2021, the 1,500 wellcomelibrary.org users don't appear to have switched to wellcomecollection.org

**Comment by taceybadgerbrook** [comment]
Looking at the same graphs for the effect of the redirection on 8 August, here is wellcomelibrary.org:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/32418070/190495747-43061aa5-b70e-4f4b-a1e1-dbaeb397742b.png">

And here is are the redirects:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/32418070/190495955-1eb94f4b-3d9e-4ff1-b093-9abf33286b99.png">

This time there is a spike on 8 August when users were redirected and a drop in wellcomelibrary.org users but the level of redirection falls back to its pre-redirection levels.

**Comment by taceybadgerbrook** [comment]
Looking at the effect of the redirection on 8 August, here is a graph of wellcomelibrary.org user numbers showing a loss of about 100 users per day after 8 August:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/32418070/190495747-43061aa5-b70e-4f4b-a1e1-dbaeb397742b.png">

The graph of wellcomelibrary.org redirects to wellcomecollection.org below shows a spike on 8 August but the level of redirection quickly falls back to its pre-redirection levels. 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/32418070/190495955-1eb94f4b-3d9e-4ff1-b093-9abf33286b99.png">

**Comment by taceybadgerbrook** [comment]
How do people find wellcomelibrary.org?

**Comment by taceybadgerbrook** [comment]
A Google search for catalogue.wellcomelibrary.org/ or wellcomelibrary.org/moh/ results in links to wellcomelibrary.org.

**Comment by alexwlchan** [comment]
> maybe something happened on 9 August that interferes with the redirect from catalogue.wellcomelibrary.org/ ?

Yup, that's when we started redirecting search.wellcomelibrary.org to wellcomecollection.org.

I don't think the redirect is busted; I think traffic to catalogue.wl.org would have dropped off at that point. There were lots of links from search.wl.org to catalogue.wl.org, and once we started redirecting search.wl.org, nobody would be following those links any more.

**Comment by taceybadgerbrook** [comment]
I know that the redirects started on 8 August so I would assume that if I plug in catalogue.wellcomelibrary.org/ into Google, I would be taken to wellcomecollection.org but this is not the case. This is why I wonder if something - I hate to say -_intermittent_ has happened.

**Comment by alexwlchan** [comment]
> I know that the redirects started on 8 August so I would assume that if I plug in catalogue.wellcomelibrary.org/ into Google, I would be taken to wellcomecollection.org but this is not the case.

Do you mean Google search?

I think that's because we've been returning HTTP 302 Moved Temporarily rather than HTTP 301 Moved Permanently; we should probably change that. That's why Google search results still look a bit funky, I’d guess.

Or is there something else confusing? The graph looks like I’d expect.

**Comment by taceybadgerbrook** [comment]
It's the address bar I mean and not Google search.

I'm using Chrome and let's say I bring up my favourite bookmark, wellcomelibrary.org/. This takes me to wellcomecollection.org. However, if my bookmark is to catalogue.wellcomelibrary.org/ then I get taken to the library site.

**Comment by pollecuttn** [comment]
The redirect is only for external users. If you're in the building or on GlobalProtect, you won't be redirected from catalogue.wellcomelibrayr.org, so that staff can continue to use the catalogue.

**Comment by taceybadgerbrook** [comment]
Clever stuff. I am indeed on GlobalProtect.
