### ISSUE TITLE
Events pages: Create a hardcoded "contact us" component for the events pages

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8284]
The access interpretation content for events has to be manually added to each event, often this is inconsistent and requires regular auditing to ensure that the information is up to date.

Alice W is going through the events to make sure that they all match. The highlighted copy in the below screen shot has to be added manually and it would be more user friendly if we had a standardised block of content for the Accessibility information. 

![Image](https://user-images.githubusercontent.com/7315126/184869313-9d90c3a3-6724-4f6e-ab97-a5e63ee7b069.png)

**Comment by alexwlchan** [comment]
Alice W flagged this again in Slack; we now have some standardised text at the event of the event block. I don't think all the existing interpretation types/event policies have had the text removed though.

**Comment by alexwlchan** [comment]
Done.
