### ISSUE TITLE
Exhibition- guides: "audio" guide UI minor adjustments

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8290]
As a visitor to the Wellcome Collection Museum, I need to be able to play the audio within the exhibition guides and identify the stops that I want to play quickly

Designs: https://zpl.io/o1R4r0G

**Comment by alicerichmond** [comment]
- [ ] Content that does not have a stop associated with it should not show in the audio guides section
- [ ] The number of stops within that section needs to be defined at the top of the page
- [ ] Play button colour needs ammending to green
- [ ] Colours of the play bar need adjusting to the designs
- [ ] Remove the yellow banner displaying on the exhibition guide pages

**Comment by davidpmccormick** [comment]
Updated the Global alert component in Prismic to [not display on pages with `/guides/exhibitions` in the URL](https://regexper.com/#%5E%28%3F!%28.*%5C%2Fitems%29%7C%28.*%5C%2Fimages%29%7C%28.*%5C%2Fguides%5C%2Fexhibitions%29%29.*%24)

**Comment by davidpmccormick** [comment]
The colour of the range input slider currently depends on a combination of system preferences and browser. There isn't a way to have the area before and after the current position have a different colour in Chrome/Safari without JavaScript, and my initial attempt to make this consistent across browsers fell a long way short of the performance and accessibility of the player as it currently is. Agreed to leave this for now, but possibly revisit it in future.
