### ISSUE TITLE
Exhibition- guides: "choose guide" page ui adjustments

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8291]
As a Wellcome Collection visitor I would like to be able to see which types of guide are available for each gallery on my mobile phone

Designs: https://zpl.io/MdQ8kjJ

**Comment by alicerichmond** [comment]
- [ ] Height and width of the guide options consistent  (BSL looks to be adjusting differently to the others)
- [ ] Change the title of "listen without audio descriptions" to just "Listen to audio tracks"
- [ ] There should be no underline of the other Gallery titles in the "other exhibition guides available" section at the bottom of the page

**Comment by alexwlchan** [comment]
Closing as this is in the Done column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
