### ISSUE TITLE
Exhibition - guides: "Captions and transcripts" page UI adjustments

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8292]
As a Wellcome Visitor I would like to be able to quickly identify the correct section of the captions and transcripts to see the relevant information for an item in the gallery

Design: https://zpl.io/406Y3Ep

**Comment by alicerichmond** [comment]
- [ ] Display the "description" field content as sections within the captions and transcripts
- [ ] remove the "Audio transcript" header when there is no information in the transcription field
- [ ] Match the ui to the designs

**Comment by gestchild** [comment]
The design of this page requires a couple of amendments to the model and some logic, based on what is filled out in Prismic, to determine how a stop gets displayed. Please see the attached image for details.

@alicerichmond, @DominiqueMarshall @melanierogan, I'd appreciate your feedback on this when you have a minute.

![captions-transcripts](https://user-images.githubusercontent.com/6051896/186147660-2a374533-74e9-472b-87cf-19bcdacc0c4c.jpeg)

**Comment by DominiqueMarshall** [comment]
Yeah this makes sense to me too, and I agree with Mel that within Prismic it would be good to indicate specifically what the standAlone is for
