### ISSUE TITLE
Exhibition guides: BSL page UI adjustments

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#8296]
As a wellcome collection visitor, I would like to be able to play the BSL guides for Wellcome exhibitions on my mobile device

Designs: https://zpl.io/xmDO5nX

**Comment by alicerichmond** [comment]
- [ ] Ensure that content with no related stop number does not render in the BSL guide
- [ ] Title matches the designs to read "Watch BSL videos"
- [ ] Confirm whether BSL designs should be blue or yellow, Zeplin shows both

**Comment by pollecuttn** [comment]
This was covered by the other guides work.
