### ISSUE TITLE
Opening times don't appear in the footer on error pages

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8327]
**What**
If you look at an error page:

https://wellcomecollection.org/404
https://wellcomecollection.org/500

then there aren't any opening times in the footer.

**Where**
<img width="406" alt="Screenshot 2022-08-24 at 19 41 49" src="https://user-images.githubusercontent.com/301220/186497755-cd419d98-b63a-4e41-ac0a-b3e980120df5.png">

**Comment by rcantin-w** [comment]
I've started looking at this out of curiosity; of course they don't show up as there is no `serverData` on error pages (https://nextjs.org/docs/messages/404-get-initial-props, which we knew when we did the "display activated toggles on error pages" work).

I looked at ways to get them client side etc, but it feels like a lot of hacking to get around something that might not be that big of a problem. So what I'm suggesting is to change "Today's opening times" to a link to the opening times page if we don't have access to venues data. How does that sound?

**Comment by jennpb** [comment]
That sounds like a very sensible option to me.

**Comment by georgiaewhitney** [comment]
@rcantin-w and I discussed these two options the other day - (having Today's opening times as the link or just keeping the opening times link)

Is there a preference?

![Screenshot 2023-09-21 at 11 09 02](https://github.com/wellcomecollection/wellcomecollection.org/assets/81175151/de960d47-d347-45f1-9005-4a39d3fa16f4)


![Screenshot 2023-09-21 at 11 09 56](https://github.com/wellcomecollection/wellcomecollection.org/assets/81175151/08a856b7-e9e6-45c6-902d-9ed3c94fd538)

**Comment by jennpb** [comment]
I'd say just the Opening times link - keep it simple :)

**Comment by georgiaewhitney** [comment]
Now in prod 😃
