### ISSUE TITLE
First pass at cookie message for new user preference cookie

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8335]
As Alex pointed out, we should update our cookie messaging to reflect the existence of the new user preference cookie. I'm going to open a PR to do this, or start the work of getting a draft of the copy so we can review and have it in a point to go live when we turn exhibition guides on for the public.

**Comment by melanierogan** [comment]
Our privacy and terms, https://wellcome.org/who-we-are/privacy-and-terms, is hosted on wellcome.org. We will need to get copy changed by someone with access to managing wellcome.org. I'm going to get copy started, then we can get it edited, pass it through legal for approval (if that is what is needed before something can be added to the privacy terms page) and then finally ask if someone can add the edits to the privacy page.

**Comment by melanierogan** [comment]
Cookies are also set on our websites when you:

++ select a guide type whilst using exhibition guides
watch videos
register for services
take part in surveys and other activities.

**Comment by melanierogan** [comment]
Next steps
- - ask whoever can tell us if this cookie is covered in current policy if we add just the above line
- check if it is considered essential etc
- edit copy
- sign off copy (legal or whoever signs off privacy text and cookie info)
- ask for copy change to be made

**Comment by melanierogan** [comment]
Note this issue is related to https://github.com/wellcomecollection/wellcomecollection.org/issues/7581

**Comment by taceybadgerbrook** [comment]
Carla and I had been speaking with folks from Legal Neha Vyas and James Groak who works in Data Protection but there is no one who rubber stamps how the legislation is supposed to be followed. Someone who might also be helpful is Helen Dodd, Data Protection Officer.

**Comment by melanierogan** [comment]
I have emailed Ysabel Schonegevel and copied in the whole team

`Hello Ysabel,
 
My name is Mel, I’m a software engineer with Digital Engagement in Wellcome Collection. A colleague mentioned that you might be best in helping us get information on a cookie added to https://wellcome.org/who-we-are/privacy-and-terms.
 
Next week we are launching our exhibition guides with the newest exhibition, In Plain Sight. The exhibition guides provide fully accessible information to guide gallery users through the space, the content is split into different guide types, at the moment these include Audio without Description, Captions and Transcripts and BSL. To best help users, we have a short lived (8 hours max life) session cookie that will remember a user’s guide preference, e.g. if they choose BSL, we load BSL content for the rest of the exhibition.
 
We’ve done our research and are confident that collecting such a short-lived session cookie in this context falls under tracking of user input and as such is an exemption category, as per the guidance on the ICO website.
We note though that it is still best practice to let users know we do collect this cookie, and how long it lives for.
 
 
(Image from screenshot of exemptions on ICO website, as seen in github post above)
 
 
Would you be able to help guide us on getting this information updated on https://wellcome.org/who-we-are/privacy-and-terms – Cookies, or know who might be best placed to help get copy changed there?
 
The copy change would be adding this user input session cookie to the list of cookies on site, highlight in bold below:
 
----
 
Cookies are also set on our websites when you:
 
select a guide type whilst using exhibition guides
watch videos
register for services
take part in surveys and other activities. 
 
----
 
 
Many thanks,
 
 
Melanie Rogan`

**Comment by melanierogan** [comment]
Copy change was all sorted by Yssy and is now in production
