### ISSUE TITLE
Mobile exhibition filters bug

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#8349]
Reported in [Slack thread](https://wellcome.slack.com/archives/C8X9YKM5X/p1661936067230199)

Main nav partially covers 'Everything', 'Today', 'This weekend', date options modal on mobile devices, as well as the button to close the modal. The page can be scrolled to reveal the items but 1. this isn't a good experience and 2. the page probably shouldn't be scrollable in that state.

To reproduce: make browser less than 600px wide, visit, https://wellcomecollection.org/whats-on then click 'everything'.

![image](https://user-images.githubusercontent.com/1394592/187641457-610b19da-1f32-4182-a4b8-37fa24e0ae93.png)

**Comment by rcantin-w** [comment]
If of interest, I've worked with this library before: [react-remove-scroll](https://www.npmjs.com/package/react-remove-scroll), it worked nicely for things like this.
