### ISSUE TITLE
SegmentedControl mobile UX

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#8362]
**What**
The mobile version of the SegmentedControl turns into what appears to be a dropdown/select thing, but when you click it it takes over the whole page and hides all other page content. This feels a bit heavy handed.

**Where**
[What's on](https://wellcomecollection.org/whats-on) with a browser-width of < 600px.

Suggest maybe using something similar to where we have dropdowns elsewhere.

**Comment by rcantin-w** [comment]
We will be working on new Tabs for Search. I've got their most basic/two tabs only version in Concept right now, but eventually it'll become more complex with a similar behaviour where it becomes a dropdown on mobile. I wonder if, once created, it could replace SegmentedControl? 

<img width="900" alt="Screenshot 2022-09-16 at 10 05 50" src="https://user-images.githubusercontent.com/110461050/190600989-ab0d89f3-7942-41ae-a888-6a6e65b60b4c.png">

(@GarethOrmerod do you have the mobile version at hand?)

**Comment by rcantin-w** [comment]
Closing this, we replaced SegmentedControl with the new tabs, and whilst they need a bit of work, this issue isn't a problem anymore.
