### ISSUE TITLE
Add an estimated reading time to articles

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8402]
We'd like to add a "read time" component to articles, telling readers how long we estimate it will take to read. This will be especially useful as the content team starts to experiment with longer-form pieces and long-reads.

This needs some design work to decide where this information will go on the page, and some dev work to decide how we estimate read time, and putting it on the page.

<img width="1096" alt="Screenshot 2022-09-06 at 16 51 15" src="https://user-images.githubusercontent.com/301220/188680390-a1398a86-f611-4b5f-9e72-7d34a41a4ed8.png">

**Comment by melanierogan** [comment]
This might be a useful tool https://github.com/lbenie/reading-time-estimator#readme
