### ISSUE TITLE
Investigate social media share buttons on stories

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8404]
We want to investigate putting social media buttons on stories, and see if people use them.

We don't want to spend too much time on this (because we're not sold on their value), so if we do this it should be a quick experiment to gather data.

**Comment by davidpmccormick** [comment]
Could we save time and find any other people's research on whether people use them elsewhere?

My hunch is that people don't use them.

**Comment by alexwlchan** [comment]
I'm going to close this for now; it was always a stretch goal for this round of Stories work, and nobody was that keen on it.
