### ISSUE TITLE
Refactor Footer

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8421]
The current footer is very busy and very long on mobile and could use some TLC on padding/borders being uneven. The green icons are also raising questions. Gareth suggested a [new footer](https://www.sketch.com/s/6ced6ea4-e7c2-4a04-a4b6-6b77a531e35c) as part of some exploration he'd done a few months back, for a cleaner, streamlined footer.

Start with the one without the newsletter, then create a new ticket for the one that has it.

**Comment by rcantin-w** [comment]
A few questions:

- New designs remove the CC icon, are happy with that?
- New designs remove the strapline "The free museum and library from Wellcome", will we miss it?
- Currently the address is a link to Google Maps, but there's also a link to https://wellcomecollection.org/pages/WwabUiAAAHQXGNHB (Getting here), do we want both? 
- Moving forward we were making the links underlined with a hover behaviour that removed the underline. This shows it doesn't work for everything as it doesn't look great/natural on the Address & Phone number. I've kept them on the old behaviour (not underline, green on hover), but am not loving the mix. Maybe something to review later on...

**Comment by jtweed** [comment]
> A few questions:
> 
> * New designs remove the CC icon, are happy with that?

Yes, I'm fine with that. It's important to keep the text but we can drop the icons to remove some of the visual clutter of the current footer, especially on mobile.

> * New designs remove the strapline "The free museum and library from Wellcome", will we miss it?

I will get back to you on this, I see it a lot less than I used to but I want to check whether we still use it/should be using it somewhere.

> * Currently the address is a link to Google Maps, but there's also a link to https://wellcomecollection.org/pages/WwabUiAAAHQXGNHB (Getting here), do we want both?

If we want to drop one, we drop the link to Google Maps. We should definitely keep the link to our page about travelling to the building. But I have no problem keeping as is, unless there's a reason why linking the address is problematic.

> * Moving forward we were making the links underlined with a hover behaviour that removed the underline. This shows it doesn't work for everything as it doesn't look great/natural on the Address & Phone number. I've kept them on the old behaviour (not underline, green on hover), but am not loving the mix. Maybe something to review later on...

This could be that reason! I'd rather we were consistent, so if that means not linking the address then it's ok not to link it.

**Comment by jtweed** [comment]
> * New designs remove the strapline "The free museum and library from Wellcome", will we miss it?

We can remove this.

**Comment by rcantin-w** [comment]
> This could be that reason! I'd rather we were consistent, so if that means not linking the address then it's ok not to link it.
Yeah that was part of it! I see the purpose but there's something off about having it there AND having a "Getting here" link. I'm also just not super happy about what it would look like underlined, same for the phone number... I'll look into if we have to do it for links of that kind. 

Gareth's mockup also removed "UK", so no third line, is that something we can do?

**Comment by rcantin-w** [comment]
Thanks for the look, I'll work on the above.

**Comment by dannybirchall** [comment]
Butting in here, to say:

In the current footer, the links to Privacy and Cookies now point to the same page on the wellcome.org site. I think this is a legacy of them having been previously separate pages). The statement on the wellcome.org site covers the wc.org site.

We need to add a link to the modern slavery statement (https://wellcome.org/who-we-are/modern-slavery-statement), which is again on the w.org site, but covers wc.org, and will be updated to cover the new retail offer.

Is it possible to reconfigure the links (combining privacy and cookies, and adding modern slavery) as part of this work?

I don't think this has any impact on Gareth's design; it's more about the content -- but I also think that the new design w the left-ranged list of links is better suited to accommodating this & possible future changes.

**Comment by rcantin-w** [comment]
> In the current footer, the links to Privacy and Cookies now point to the same page on the wellcome.org site.

Shall I rename it Privacy & Cookies? Or something else?

> We need to add a link to the modern slavery statement 

I'll add it as Modern Slavery Statement

(I like to double check these things as English is not first language and I might not know some simple rules like using "&" in a sentence is grammatically fine, @dannybirchall , so apologies for the silly checks 😅  )

It might make the subnavigation a bit too lengthy on certain screen sizes, but I'll tweak the CSS if needed.

**Comment by rcantin-w** [comment]
<img width="1100" alt="Screenshot 2022-10-03 at 15 27 39" src="https://user-images.githubusercontent.com/110461050/193602474-f5381298-e3b7-47e4-ab48-0eff5945826e.png">

Here, between certain large screen size, socials drop down a bit and realign later. The menu switching to a column list too early looked too big for nothing.

**Comment by rcantin-w** [comment]
> > Gareth's mockup also removed "UK", so no third line, is that something we can do?
> 
> I think we can, as we don't include it here:
> 
> https://wellcomecollection.org/pages/WwabUiAAAHQXGNHB

@jtweed it will remove it from here too as it's the same component

**Comment by dannybirchall** [comment]
Thank you @rcantin-w !

> > In the current footer, the links to Privacy and Cookies now point to the same page on the wellcome.org site.
> 
> Shall I rename it Privacy & Cookies? Or something else?

I'm a big fan of ampersands in my own writing, but not so much on the site; can we use also sentence case, thusly

Privacy and cookies

> > We need to add a link to the modern slavery statement
> 
> I'll add it as Modern Slavery Statement

Likewise, can we use 

Modern slavery statement 

> (I like to double check these things as English is not first language and I might not know some simple rules like using "&" in a sentence is grammatically fine, @dannybirchall , so apologies for the silly checks 😅 )

We're v much here to support All The Words And The Language on the site, so please always do check if needed!
