### ISSUE TITLE
Communicating changeover from UA to GA4 - Q4 data

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8428]
Continuation of #8426 

- [x] After 30 September, create Q4 quarterly data from GA4 for these stats
- [x] After 30 September, create Q4 quarterly data from UA for these stats
~~- [ ] Create charts for using UA only~~
- [x] Create charts for using UA + GA4 only
- [ ] Annotate differences

Part of epic #9101

**Comment by taceybadgerbrook** [comment]
Spreadsheet with monthly and quarterly stats here.
https://docs.google.com/spreadsheets/d/1NyfiQSRtu7DUPhHqwnoQIBOvjzYaFVw_IDDd6WlQwPQ/edit#gid=24181347

**Comment by jennpb** [comment]
@taceybadgerbrook Is this done and dusted?

**Comment by taceybadgerbrook** [comment]
No, not at all. I've created the spreadsheet so that when we start meeting with senior stakeholders I can produce graphs showing how the product has been checked and how the stats compare to GA.
