### ISSUE TITLE
Rebuilding Kibana dashboards

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8437]
Due to reporting cluster issues, certain dashboards in Search space need to be reinstated.

**Comment by taceybadgerbrook** [comment]
[Breadth dashboard](https://github.com/wellcomecollection/wellcomecollection.org/issues/8392)

**Comment by taceybadgerbrook** [comment]
# Breadth dashboard

## Works page views

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|User selects work from search results and views works page. Understood to be analogous to taking a book down from the shelf. Note that index has gap 11-21/10/21 when index metrics-conversion-prod being set up|metrics-conversion-prod|page.name:work|
|Unique works page view|metrics-conversion-prod|page.name:work, cardinality by page.query.id|

# Item page views

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|User actually views work. Does not include views generated by paging through work. Note that stats for period before source:viewer/paginator was created 13/1/21 will include when users page back to page 1 - surprisingly common!|metrics-conversion-prod|(page.name:item or page.name:image) and NOT (source:viewer/paginator)|
|Unique count of actual items viewed, cardinality by page.path. Note that Kibana starts capturing views from 7/12/20.|metrics-conversion-prod|(page.name:item or page.name:image) and NOT (source:viewer/paginator), cardinality by page.query.workId|

# Image viewer views

Researchers often view images without going to the actual item page. I think this is just as valid a measure of engagement as viewing a works page or item page. 

It doesn't look like this event has ever been tracked in metrics-conversion-prod. This work is now captured in #8441

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|User views image by selecting search result or related image from image viewer|metrics-conversion-prod|page.name:?|

For reference, here is James' diagram of paths users can take: 

![image](https://user-images.githubusercontent.com/32418070/106156049-fb004200-6178-11eb-936a-c000ad4f09cb.png)

**Comment by taceybadgerbrook** [comment]
# Collections dashboard

## Sessions: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|New session.id assigned when previous session ends or timeouts. Does not reset after 24h.|metrics-conversion-prod|session.id|

## Total searches with 0 results: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|Searches where no results returned|metrics-conversion-prod||

Investigating criteria: 

(page.name:images or page.name:works)
and
page.query.query:* #this criteria is obsolete
and
properties.totalResults:*
and
(page.query.page:1 OR NOT page.query.page:*) #was introduced to reduce occurrence of duplicates but does not remove duplicates which occur intermittently

**Comment by taceybadgerbrook** [comment]
## Unique items viewed: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|Count of unique items actually viewed.|metrics-conversion-prod|See Breadth dashboard for definition|

**Comment by taceybadgerbrook** [comment]
@jamieparkinson @harrisonpim @alexwlchan I exported 2,125 records and out of 48 searches, 20 triggered duplicate searches less than 1 second directly afterwards. I could filter these out using cardinality = page.path but this risks under reporting common page.paths, eg /works?query=botany. What do you think is going on?

Here is the criteria:

(page.name:images or page.name:works) 
and
page.query.query:* # query submitted
and
properties.totalResults:* # results are returned even if 0
and
(page.query.page:1 OR NOT page.query.page:*) # weeds out paging through results.

**Comment by harrisonpim** [comment]
Just had a chat with @taceybadgerbrook and skimmed through the data together.

Tacey spotted some duplicate searches, but it looks like we're also double counting some pageviews. The dupes all appear a few milliseconds apart from one another. I can't remember the implementation details for the segment stuff, but my guess is that in each of those situations, we're calling the component which fires those events more than once.

I don't think I know the frontend codebase well enough to unpick this myself - is anyone up for some pairing?

**Comment by alexwlchan** [comment]
> I can't remember the implementation details for the segment stuff, but my guess is that in each of those situations, we're calling the component which fires those events more than once.
>
> I don't think I know the frontend codebase well enough to unpick this myself - is anyone up for some pairing?

Happy to have a look, but I don't really know where Segment gets used on the page so we'll have to work it out together.

**Comment by alexwlchan** [comment]
Okay, so looking in the dev tools I can see two requests going to api.segment.io when I load a works page, seems suspicious. Let me dig in a bit.

**Comment by taceybadgerbrook** [comment]
## Searches: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|User submits query or filters query |metrics-conversion-prod|(page.name: works or page.name: images) AND page.query.query: *|

**Comment by taceybadgerbrook** [comment]
# Conversion dashboard

## Works page views/search by session.id: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|Average proportion of number of works page views of total searches, cardinality by session.id |metrics-conversion-prod|see definitions of works page views under Breadth. see definition of searches as queries under Collection|

**Comment by taceybadgerbrook** [comment]
# Conversion dashboard (archive focus)

## Total archive works page views: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|Total number of page views for archive tree works pages |metrics-conversion-prod|page.name:work AND page.query.id: * AND source: archive_tree|

## Archive works page views by anonId: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|Average number of page views for archive tree works pages by anonymousId |metrics-conversion-prod|page.name:work AND page.query.id: * AND source: archive_tree, cardinality by anonymousId|


## Archive works page views by anonId: metric and time series

|Description |Elasticsearch index  | Kibana definition|
|:---|:---|:---|
|Average number of page views for archive tree works pages by anonymousId |metrics-conversion-prod|page.name:work AND page.query.id: * AND source: archive_tree, cardinality by anonymousId|

**Comment by taceybadgerbrook** [comment]
All dashboards have now been reinstated for metrics-conversion-prod.

**Comment by taceybadgerbrook** [comment]
Documentation to go into Collections Discover section of Notion:
https://www.notion.so/wellcometrust/Product-areas-4102c1e29cbd416b97f9e20fcbe8efa8#ff43053ba6d04129b218e9f830463f13

**Comment by taceybadgerbrook** [comment]
These are also recorded in Notion 
https://www.notion.so/wellcometrust/Kibana-dashboard-definitions-4eb8af16a00b4f81955015696d9c25a3
