### ISSUE TITLE
IIIF audio manifests contain placeholder thumbnail images

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/wellcomecollection.org#8440]
There are instances where we would like to display the thumbnail associated with a piece (or group) of audio items – this comes from the IIIF manifest.

Currently, audio that doesn't have a content thumbnail still has a placeholder icon in its place. And each placeholder has a different url, so we aren't able to simply filter out the ones we're not interested in.

Ideally, if we don't have a meaningful thumbnail to display, there shouldn't be anything in the thumbnail in the manifest. That way, we can render the thumbnail if it's present.

**Comment by LFBaily** [comment]
Duplicated by #10543

**Comment by pollecuttn** [comment]
Closing as duplicated
