### ISSUE TITLE
User cannot order other items in a series without going via their library account

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8448]
**What**

When a library user is trying to order several items in a series, e.g., [PP/MCS/B/10-34](https://wellcomecollection.org/works/rm8c9h2z), after requesting an item and then clicking the X to close the popup (see screenshot) instead of 'View your library account' button, all the other items in the archive series have status 'Temporarily unavailable' and Note 'You have requested this item'. The user has to go to their library account and then back to the archives hierarchy to request another one in the series.

![image (1)](https://user-images.githubusercontent.com/1446072/189906528-b968fca1-70fe-44ae-89e4-69b20075a525.png)

This makes it look as though requestable items are not requestable.

Reported at https://wellcome.slack.com/archives/C8X9YKM5X/p1662648863004709

**TODO**
- [ ] If using the 'X' to close the pop up, the rest of that part of the series is requestable

**Comment by pollecuttn** [comment]
@alexwlchan Although I can now go to other items in the series and have a 'Request item' button, when I click it I don't get the modal to select the request date and confirm the request. Instead I go straight to the 'Request confirmed' modal without placing the request. So the request never turns up in my library account nor in Sierra, but I'm being told incorrectly the request is confirmed.

Could you have another look, please?

**Comment by alexwlchan** [comment]
The problem is in the ItemRequestModal component; it moves `requestingState` to `confirmed` and never reverts it.

**Comment by alexwlchan** [comment]
I can't reproduce this issue any more, have we fixed it another way?

**Comment by pollecuttn** [comment]
@alexwlchan I also can't reproduce this issue!

**Comment by pollecuttn** [comment]
Closing as cannot reproduce the problem

**Comment by alexwlchan** [comment]
Sounds like this may [still be an issue](https://wellcome.slack.com/archives/C8X9YKM5X/p1671107657012859):

> Little thing I've noticed while testing some of the requesting for [this collection](https://wellcomecollection.org/works/ssf58qfz): if I request something in one of the linked series (and have to click back on the browser to return to the collection to request more), the correct hardcoded message "you have requested this item" only appears when I refresh the page, otherwise it says "another reader has requested this item".

**Comment by pollecuttn** [comment]
@pollecuttn to retest

**Comment by pollecuttn** [comment]
I retested and couldn't replicate the problem. I've asked the person who reported this to let me know what I'm doing wrong.

**Comment by pollecuttn** [comment]
Original reporter also cannot replicate the issue, so closing this ticket: 

> The back browser thing sounds completely out of date/wrong, as I'd just use the hierarchy on the left to request more. I've tested what I think I was saying originally :smile: and it all looks good.
