### ISSUE TITLE
Wrong month being used on requests

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8457]
**What**

Making a request for e.g. Friday 16 September
![image](https://user-images.githubusercontent.com/1446072/190110998-ee9cb196-06d9-4515-a63f-cb0bbacc506f.png)

shows up in my library account, Sierra, and on request slips as 16 August
![image](https://user-images.githubusercontent.com/1446072/190111261-0ada8116-2e0b-4a3d-85d5-813f3be0acb7.png)

![image](https://user-images.githubusercontent.com/1446072/190111614-2e7791f4-ee02-43ea-8c1c-3d4c9b790bdd.png)

**Where**

Any requestable item e.g. https://wellcomecollection.org/works/xy46e72g

**Comment by alexwlchan** [comment]
Argh. This is almost certainly my fault, let me have a look.

**Comment by alexwlchan** [comment]
Closing as fixed.
