### ISSUE TITLE
Create a proper card for series/serials

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8460]

**Comment by gestchild** [comment]
@alexwlchan did you create this ticket on my behalf when I was talking about needing it for the stories landing page work? If so I think it can be closed. I was mistaken, we use the Card component to display these:

![Image](https://user-images.githubusercontent.com/6051896/193609553-4f6e3e08-1f7d-45ff-b9b2-e950522f24a1.png)

**Comment by alexwlchan** [comment]
I did indeed, so I’ll close it.
