### ISSUE TITLE
Change how anchor links work to make them more consistent

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8463]
This is a follow up to https://github.com/wellcomecollection/wellcomecollection.org/issues/8359

We want to make the anchor links more predictable, not human readable.

**Comment by melanierogan** [comment]
Started a discussion with Alex and Danny on this, summary of which is [here](https://wellcome.slack.com/archives/CUA669WHH/p1663846255786409). The upshot is, two things would be helpful. Predictably shorted anchors, and having a tool that would select all anchor links on a page and put them into a file/make them pastable into a file.

**Comment by pollecuttn** [comment]
@melanierogan this is in 'Done' - should it be closed?
