### ISSUE TITLE
Google Tag Manager course

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8477]
I need to understand how to use Google Tag Manager in order to decide how useful it would be for Stories and Marketing tracking. Google Analytics Academy offer a [free Tag Manager course](https://analytics.google.com/analytics/academy/course/5/unit/1/lesson/1) online.

This ticket is to earmark the amount of concentrate time I would need to spend on this to get anything out of the course.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @gestchild I think I've established that the GTM container wellcomecollection.org has not been set up. It looks like I created the container but it makes sense that the snippets below were never installed because we only used GTM for tracking both wc.org and wl.org.

**Comment by taceybadgerbrook** [comment]
So this code is for pasting into the head of each page:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-53DFWQD');</script>

**Comment by taceybadgerbrook** [comment]
and this code is for pasting into the body of each page:


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-53DFWQD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by taceybadgerbrook** [comment]
It's the same code as was installed for the wc.org + wl.org container but instead of GTM-WV9JS8W, it's GTM-53DFWQD. Maybe it's easier and tidier to just swap these on every page and I'll retire the old container.

**Comment by taceybadgerbrook** [comment]
@jamieparkinson the wc.org + wl.org container has been disabled. Here's GTM's container activity log:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/32418070/191709704-e0010ecc-39a4-4608-9788-828f4e14a584.png">

Seems silly to reinstate when we aren't tracking wl.org. If you come across any Google Tag Manager snippets, I'd say bin them and we'll start over tagging only wc.org.

**Comment by taceybadgerbrook** [comment]
@jamieparkinson I'll get on and close the GTM account that covers wl.org and wc.org.

**Comment by taceybadgerbrook** [comment]
@jamieparkinson wl.org/wc.org container now deleted.

Here is a link to the snippets to install for the wc.org only container: https://tagmanager.google.com/?authuser=0#/admin/accounts/6000872529/containers/31009043/install

**Comment by jennpb** [comment]
@taceybadgerbrook This issue was specific to GTM training. Did you manage to do that, or is that still to be done? If it's tobe done, I should add myself to this as well!

**Comment by taceybadgerbrook** [comment]
@jennpb I did as much training as I could in order to contribute to the GA4/GTM discussion but because I don't have an active GTM container, I couldn't set up tags and test so I think it's worth finding a proper course for both of us.

**Comment by jennpb** [comment]
Then I think this issue can be closed and we can discuss what training is available.
