### ISSUE TITLE
Evaluating new Stories homepage design

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8478]
**We want to know if the following change has improved the user experience**
Stories homepage redesign

**Definition of success is**
More stories clicked on homepage

**We'll know if we're succeeding if we measure the following metric and this happens**
Increased percentage of stories clicked on after homepage

**Definition of failure is**
Users aren't encouraged to click on stories further along in series or further along the page.

**We'll know if we're failing if we measure the following metric and this happens**
Majority of onward clicks are to those stories links above the fold

**Comment by taceybadgerbrook** [comment]
Google Analytics Behaviour/Site Content/All pages/Navigation Summary looks like this when the page of reference is set to the stories homepage:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/32418070/190488933-adfc5062-49a6-4abe-8e9b-4709b000f759.png">

**Comment by taceybadgerbrook** [comment]
The number of rows can be set to 500 (although much past 100 and the numbers thin out considerably) and previous page and next page listings can be exported into csv. In this way, they can be grouped into site areas collection, event, stories, all other.

**Comment by dannybirchall** [comment]
@taceybadgerbrook are we overcomplicating things here? if we can't track the actual clicks themselves (ie, see how many people have clicked on the links in the new editable box) could we not just look at the before and after stats for the six pages that we put in the new editable box?

**Comment by taceybadgerbrook** [comment]
@dannybirchall yes, before and after clicks works for me.
