### ISSUE TITLE
Transcripts and captions should be the same font size on desktop and mobile

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8480]
**What**

On desk top the font for the captions and transcripts seems to be smaller on captions than on the transcriptions. When making it phone size they even out. But not sure if they should be the same regardless

The transcripts and captions should be the same font size on desktop and mobile (only the intro texts on the beige background and headings are larger)

https://wellcome.slack.com/archives/CUA669WHH/p1663248616067859?thread_ts=1663233504.218509&cid=CUA669WHH

**Where**

https://preview.wellcomecollection.org/guides/exhibitions/YyGb2xEAAHzJwTh0/captions-and-transcripts
You will need the exhibition guide toggle turned on to view it

**Comment by melanierogan** [comment]
Alice originally reported: _On desk top the font for the captions and transcripts seems to be smaller on captions than on the transcriptions. When making it phone size they even out. But not sure if they should be the same regardless_

**Comment by pollecuttn** [comment]
@melanierogan this is in 'Done' - should it be closed?
