### ISSUE TITLE
Captions and transcripts grey background stripes in Firefox

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8481]
**What**

C’s&T’s in firefox there are grey background stripes that do not show in chrome (they shouldn’t show on any browser)

https://wellcome.slack.com/archives/CUA669WHH/p1663236385925419?thread_ts=1663233504.218509&cid=CUA669WHH

**Where**

https://preview.wellcomecollection.org/guides/exhibitions/YyGb2xEAAHzJwTh0/captions-and-transcripts
You will need the exhibition guide toggle turned on to view it

**Comment by melanierogan** [comment]
I've been trying this out in firefox but cannot replicate, going to catch up with Alice to see if i can replicate and then fix
