### ISSUE TITLE
Use Title field for BSL and Audio tracks instead of Stand alone title

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8485]
**What**

The logic for the titles is weird, the "Stand alone title" field is handled differently to the “Title" field and allows someone to define where there might be a “group” or “context” stop. The stand alone titles appear in green headers on the captions and transcripts pages. The "Stand alone title" seems to be the one that is being pulled through for the audio tracks, but that is incorrect. The field that should be being used for the titles for the BSL and Audio tracks is Title, else we will see the same thing twice in some places and it will promote a title that is not related to a group to be big and green on the captions pages.

https://wellcome.slack.com/archives/CUA669WHH/p1663253820810199?thread_ts=1663233504.218509&cid=CUA669WHH

**Where**

https://preview.wellcomecollection.org/guides/exhibitions/YyGb2xEAAHzJwTh0/captions-and-transcripts
You will need the exhibition guide toggle turned on to view it

**Comment by gestchild** [comment]
I'm having trouble understanding/replicating the issue here.

From the Slack conversation, "... If the stand alone title is not set, then there is no title on the audio version". I can't see this, the only item without a title, doesn't have the title field filled in in Prismic, so I think this is working as expected?

**Comment by melanierogan** [comment]
I'm a bit confused by this one myself, i can't replicate either. Gonna stick a blocked label on it until we can clarify what we need to sort out.

**Comment by dannybirchall** [comment]
The logic should be something like:

If there's a 'title', use that
If there's no title, use 'standalone title' 
If there's neither, the content eds have messed up

does that make sense? Nothing should have both a title and a standalone title. the blocks that have standalone title are intro blocks, and don't refer to objects.

**Comment by dannybirchall** [comment]
this is also blocking the gather anchor links function on pages like this -- 

https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/audio-without-descriptions

where there are no titles there are no anchors

**Comment by melanierogan** [comment]
Thanks @dannybirchall i'm looking at it now
