### ISSUE TITLE
Images in the context of captions and transcripts pages

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8486]
**What**

The exhibitions team have managed to get more images than expected with loan agreements that allow us to have them online, we need to think about how we present those images in the context of the captions and transcripts pages. These images are really important to partially sighted people as they have the ability to zoom into them on their device. It might be that we show only a tiny thumbnail or slice of the image that allows someone to open it up to be bigger, its worth considering the UX of this and how we can accommodate them. 

https://wellcome.slack.com/archives/CUA669WHH/p1663253702615049?thread_ts=1663233504.218509&cid=CUA669WHH

**Where**

https://preview.wellcomecollection.org/guides/exhibitions/YyGb2xEAAHzJwTh0/captions-and-transcripts
You will need the exhibition guide toggle turned on to view it

**Comment by DominiqueMarshall** [comment]
Here are two design options for expanding image thumbnails to full-screen images; 

1 - an 'expand' icon/button that sits on top of the images 
2 - a more explicit 'view image' button that sits underneath the image caption. 

[Captions with images](https://zpl.io/ew58wgm)
[Image zoomed in](https://zpl.io/09Wk9ZO) - this is similar to the existing image viewer, but adds the image credit info.

It would be great to get some feedback about which of these options is more plausible in the time we've got, or if there are other possibilities that the devs are aware of.

cc @alicerichmond

**Comment by davidpmccormick** [comment]
I know Ben was also interested in the possibility of having zoomable images within stories.

It definitely feels non-trivial to me, and I'm not sure of the feasibility of having it work in the same way as we zoom the catalogue images, because that requires IIIF tiled images, and we'd be dealing with images from Prismic here.

Having an option to zoom images from Prismic definitely feels like something we should aim to provide though – I don't know that there is a good 'quick' option for it, but if we do it, I think it would make sense to consider it in the round for all images, rather than just the exhibition guides images?

**Comment by DominiqueMarshall** [comment]
@davidpmccormick yeah looking at the zoom functionality holistically is a good idea. As the Prismic images work differently, would it be a case of having them open to the biggest image size available then, without the zoom-in/out functionality?

**Comment by DominiqueMarshall** [comment]
That Guardian functionality is similar to the approach in the mockups, so yep, happy to start with that

**Comment by davidpmccormick** [comment]
This is now behind the "Enable images from Prismic to fill the viewport" toggle, limited to images within the exhibition guides captions & transcripts. An appropriate image for the largest available viewport will be generated when the zoom button is clicked. There is currently only one image in the _In Plain Sight_ captions & transcripts, but it should demonstrate the functionality.

**Comment by DominiqueMarshall** [comment]
Works for me on desktop, but the button isn't there on mobile?
