### ISSUE TITLE
Test exhibition guides barcodes works as expected

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8488]
**What**
We should be able to generate some barcodes from the content that is in there currently, it would be great if the team would be able to test out scanning these and it loading the pages appropriately and if there are any snags with the journey. 

I think @dannybirchall can help with generating the barcodes.

**Where**
https://preview.wellcomecollection.org/guides/exhibitions/YyGb2xEAAHzJwTh0/captions-and-transcripts
You will need the exhibition guide toggle turned on to view it

**Comment by dannybirchall** [comment]
@pollecuttn I can do this, but waiting for @melanierogan to refactor the URL structure for the anchors first.

**Comment by melanierogan** [comment]
fyi @dannybirchall and @pollecuttn Just to confirm, url structure all sorted as per our chat in slack and ticket here https://github.com/wellcomecollection/wellcomecollection.org/issues/8463
