### ISSUE TITLE
Add analytics to Concept page

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8501]
After chatting with Tacey, we determined we needed to add some tracking to events in the concept page

- When clicking on an "All images/works" button
- When clicking on an "About/by" tab

we also want to make sure pageviews are being tracked

**Comment by taceybadgerbrook** [comment]
@rcantin-w Do you mean Concepts pageviews? If these have unique ids then, that might be helpful in measuring breadth. If more unique Concepts pages are being viewed, we can say more of the collection is being accessed, especially as images users often don't actually click to view individual items.

**Comment by rcantin-w** [comment]
> @rcantin-w Do you mean Concepts pageviews? If these have unique ids then, that might be helpful in measuring breadth. If more unique Concepts pages are being viewed, we can say more of the collection is being accessed, especially as images users often don't actually click to view individual items.

@taceybadgerbrook they do have unique id, the url looks like `/concept/[id]`, I believe we said that was sufficient? I was trying to remember everything we said we'd like to have tracked!

**Comment by taceybadgerbrook** [comment]
My comment was about

>we also want to make sure pageviews are being tracked

If this is about measuring any increase in item pages being viewed, I can track unique and total item page views in Kibana.

**Comment by rcantin-w** [comment]
@taceybadgerbrook for the tabs, I have added this on the click (when the clicked tab is NOT the current selected tab), as well as with keyboard navigation:
```
                trackEvent({
                  category: 'TabNav',
                  action: 'Tab clicked',
                  label: item.id,
                });
```
where `item.id` is either `images-by`, `images-about`, `works-by` or `works-about`. Does that align with what is required/would we like more or different information?


For the All Images/All works buttons, it goes to a different link (either a pre-filtered `/works` or a prefiltered `/images`), am I right in assuming that could be how it gets tracked?

**Comment by taceybadgerbrook** [comment]
@rcantin-w looks good to me. All we care about is if people click the about (aboot?) / by tabs. If I can show that more works or item pages and being viewed and people are clicking these tabs, we can infer that the tabs have been worth the effort to build them.

I'm less interested if people are clicking the All Images/All Works.

**Comment by rcantin-w** [comment]
@taceybadgerbrook great! Worth keeping in mind that _not all Concept pages_ will have these tabs when doing some stats!

Where would we usually test them? If I do it locally, should it start appearing in our GA? Or would you like it in staging for testing?

**Comment by jtweed** [comment]
Thanks both, looks good to me too. And yes, good point @rcantin-w that not all concept pages will have the tabs, which will affect the stats if it's looked at relative to concept pages views rather than as an absolute metric. Note also @taceybadgerbrook that the URLs are actually at `/concepts/{id}` (ie plural, like everything else).

**Comment by taceybadgerbrook** [comment]
@rcantin-w @jtweed good point. I won't evaluate by/about clicks as percentages although we do have to have some kind of reference point.

As far as testing, I can see pages in GA beginning with www-stage.wellcomecollection.org so I'm thinking this is staging. I don't think GA collects anything from running changes locally.

**Comment by rcantin-w** [comment]
Alright I sent it to code review, I'll let you know when it gets to staging! @taceybadgerbrook

**Comment by rcantin-w** [comment]
@taceybadgerbrook it's on staging, here's an example page: https://www-stage.wellcomecollection.org/concepts/n4fvtc49 

Let me know if I can assist with anything!

**Comment by taceybadgerbrook** [comment]
@rcantin-w apart from verifying that concepts pages work, is there anything you wanted me to evaluate just now?

**Comment by rcantin-w** [comment]
@taceybadgerbrook mainly just checking if  you need me to test anything to do with the new tab events or if we're happy to close the ticket?

**Comment by taceybadgerbrook** [comment]
@rcantin-w So this is just testing whether I can see /concepts pages, then? If so, then yes, you can close the ticket.

**Comment by taceybadgerbrook** [comment]
Tabbing between by/about is visible in GA:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/32418070/191995626-29af14ba-9c5d-4c8e-8053-6704e8b35d89.png">

**Comment by rcantin-w** [comment]
Thanks @taceybadgerbrook ! I'll close the ticket :)
