### ISSUE TITLE
Buttons hover behaviour

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8542]
**For design:**
As we made changes to the colour palette and introduced visual changes in buttons, inputs and body links, it came forth that the buttons looks and hover behaviours should be reviewed and decided upon in a new design system. 
1. What colours should be available to theme buttons?
2. What happens when you hover/click on them?
3. What sizes do they have?

[We've had conversations before](https://wellcome.slack.com/archives/C03SU2ZNR9D/p1661942949102279?thread_ts=1661941324.324289&cid=C03SU2ZNR9D), looking at what solution we could adopt.

[Based on comments and changes made to integrate the new colour palette.](https://github.com/wellcomecollection/wellcomecollection.org/pull/8506/files#r980132831)

We'll need to consider [outlined buttons](https://cardigan.wellcomecollection.org/?path=/story/components-buttons--dropdown-button) as well as [solid ones](https://cardigan.wellcomecollection.org/?path=/story/components-buttons--button-solid).

**For devs:** 
We should rename our ButtonStyles (e.g. `pumiceTransparentCharcoal`) since [the names don't match the new palette](https://github.com/wellcomecollection/wellcomecollection.org/pull/8506/files#diff-915a22d040442a7d9e70b78ed67b40c3a52e88ae9910512dfd070609967b8e6dR161).  

~~(styled-system to make its entrance maybe?)~~

**Comment by rcantin-w** [comment]
@j-jaworski  reckon this can be closed based on https://github.com/wellcomecollection/wellcomecollection.org/issues/10357 ?

**Comment by j-jaworski** [comment]
Agreed, and closed
