### ISSUE TITLE
Weeding out GA4 events migrated from UA

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8564]
I have set up GA4 so that all events being sent to UA are also being sent to GA4. Some time ago I updated the [event tracker sheet](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B3DA23EC9-0EA4-4956-9B05-20E035BDA462%7D&file=GA%20annotated%20event%20tracker%20cheatsheet.xlsx&action=default&mobileredirect=true) with details of event trigger and page containing trigger.

Looking at an export of UA Event Category and Event Action data 1/7/22-27/9/22, it appears that there are many events which were not listed in the original event tracker.

**Comment by taceybadgerbrook** [comment]
Looking at the GA4 data for the same period reveals that events are reported by Event Action only as Event Category and Event Label have been dropped in GA4. This loss of event detail together with a certain amount of duplication (most notably the 13 different events with Event Action = "follow link") raises the question of the value of inclusion of UA events.

Many of these UA events were created for monitoring features. Is this monitoring still necessary?

**Comment by taceybadgerbrook** [comment]
UA can still be used to analyse events which have been tagged already (eg set speed to 0.5x/1.5x etc) but going forward, I recommend we begin to use Google Tag Manager. After July 2023, all tags involving Event Category criteria can be deleted as UA will no longer be collecting these events. This can only speed up the site. 

Regarding Google Tag Manager tags, I suggest we schedule retirement of tags for evaluating features 1 year following analysis.

**Comment by taceybadgerbrook** [comment]
Going forward, I recommend we use Google Tag Manager exclusively for tagging and schedule in a reminder to retire tags for evaluating features 1 year following analysis.

**Comment by jennpb** [comment]
I suggest we raise this one from the dead. @taceybadgerbrook I'd like to run through the recommendations for GTM tagging so I can understand what the transition from UA to GA4+GTM means for our ability to understand how the UI is performing.

I'll move back to sprint backlog

**Comment by taceybadgerbrook** [comment]
@gestchild @davidpmccormick @rcantin-w, I have turned off the tracking of UA events in GA4 because it causes double pageviews and disproportionately low bounce rates (see #8744.) 

I propose we shelve all plans to re-tag events we had set up in UA unless we activate Google Tag Manager in which case I'll be able to tag these events myself.
