### ISSUE TITLE
Tidy up stories landing code once toggle is true by default

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#8592]
Once the newStoriesLanding toggle is switched on for everyone and we're happy that it's ok, we should remove the code responsible for the old landing page content and archive some content and disable the featuredBooks type in Prismic.

Code changes:
- [x] remove newStoriesLanding toggle code from stories.tsx 
- [x] remove code that is no longer needed from stories.tsx, including everything marked OLD in the comments
- [x] remove featuredStoriesSeriesId from /common/data/hardcoded-ids.ts
- [x] remove prismicPageIds.stories from /common/data/hardcoded-ids.ts
- [x] delete '../services/prismic/fetch/featured-books';
- [x] delete '../services/prismic/transformers/featured-books';

Prismic changes:
Once the above is deployed to live:
- [x] disable the FeaturedBooks type in Prismic
- [x] comment on the FeaturedBooks type source code that it has been disabled
- [x] archive the FeaturedBooks content in Prismic
- [x] archive the 'Stories page' content in Prismic

**Comment by alexwlchan** [comment]
> remove prismicPageIds.stories from /common/data/hardcoded-ids.ts

FYI, I think this is also used in the app controller to link `/pages/${prismicPageIds.stories}` to `/stories`.

**Comment by gestchild** [comment]
Do we still need that redirect? or can we remove that too?

**Comment by alexwlchan** [comment]
> Do we still need that redirect?

Ah, good point, you're right, we don't if we remove the page in Prismic also.

**Comment by alexwlchan** [comment]
There's also https://github.com/wellcomecollection/wellcomecollection.org/issues/8516
