### ISSUE TITLE
Adding more 'types' to readingTime

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8601]
The editorial team have flagged that the readingTime should count not just 'Article' or 'Series' formats, but also 'Book extracts', 'In pictures' (tbc). I'll need to get a full list or we risk going back over this a few times.

**Comment by pollecuttn** [comment]
>  I've noticed it's also not pulling through for our brand new type of article the 'Long read'. I'd say we would really like a reading time on these. Our very first one published just this morning, we have our second coming up in November. https://wellcomecollection.org/articles/YxcXNhEAACMAkfYx 

https://wellcome.slack.com/archives/C8X9YKM5X/p1664962912671169?thread_ts=1664892831.195689&cid=C8X9YKM5X
