### ISSUE TITLE
BSL videos not picking up any titles at all

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#8619]
As pointed out by Danny: https://wellcome.slack.com/archives/CUA669WHH/p1664901905638249

![Image](https://user-images.githubusercontent.com/60890140/194264956-830b23c5-fade-436f-b2c5-006dfcaeb8cb.jpg)

**Comment by DominiqueMarshall** [comment]
@pollecuttn No, I think this is a different issue. The titles, as shown in the intro of the videos, aren't rendered on the page. E.g. the first video's actual title is "Protection and Observation introduced by Ligaya Salazar".

I'm not 100% sure how they've been inputted in Prismic, so needs clarification from @dannybirchall

**Comment by dannybirchall** [comment]
I've left a comment on #8485, saying that the logic should be something like:

If there's a 'title', use that
If there's no title, use 'standalone title' 
If there's neither, the content eds have messed up

... the same should apply to BSL titles

**Comment by melanierogan** [comment]
On it...just putting something in staging (then production) for audio titles/standalone titles now, I'll cover BSL in another PR

**Comment by melanierogan** [comment]
Alex is adding this PR into their own work on refactoring and getting ready for tackling default QR code journey
