### ISSUE TITLE
Incorrect numbering of content in Prismic

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#8620]
https://wellcome.slack.com/archives/CUA669WHH/p1664901905638249

The numbering is correct according to what's entered in Prismic, but the ordering follows the order of the components. I know this bc I added the intro as the last component on the page, so item no1 is last in both lists. The Prismic interface makes it nigh-on impossible to move the block up past 150+ other blocks.

Examples:

![Image](https://user-images.githubusercontent.com/60890140/194265783-47458c24-f8ad-4898-a1f4-8369d663ad4f.jpg)

__________________________

![Image](https://user-images.githubusercontent.com/60890140/194265782-8bd83990-e0c6-4588-bd1a-d26897ce79a3.jpg)

__________________________

![Image](https://user-images.githubusercontent.com/60890140/194265781-b987352d-b880-4ac9-824c-bc7847dd47e9.jpg)

**Comment by melanierogan** [comment]
Fixed this by moving up intro content
