### ISSUE TITLE
Run the pa11y tests on stage deployments

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8623]
We should run pa11y tests alongside the e2e tests, and have them block deployments – this would prevent accessibility issues reaching the live site.

**Comment by rcantin-w** [comment]
Sometimes pa11y errors occur for reasons outside of code changes, so it shouldn't prevent deployments. We've not had anything really bad happen so far and Natalie looks at pa11y every day so anything gets flagged quite quickly and gets addressed if a priority. So I think we can close this.
