### ISSUE TITLE
Compile September 2022 data for WC Combined Stats report

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8626]
[WC Combined Stats report](https://wellcomecloud.sharepoint.com/:x:/r/sites/VisitorInsights/_layouts/15/Doc.aspx?sourcedoc=%7B97E28F8D-C866-419A-B260-9238101BAA86%7D&file=WC%20combined%20stats%20report%20template.xlsx&action=default&mobileredirect=true)

**Comment by taceybadgerbrook** [comment]
Needs capacity for annual figures added.

**Comment by taceybadgerbrook** [comment]
Annual figures have now been added but awaiting advice on which periods are of interest. To be revisited 10 November.

**Comment by jennpb** [comment]
@taceybadgerbrook Should this be moved from the backlog into the sprint backlog now?

**Comment by taceybadgerbrook** [comment]
Sorry, this is done!
