### ISSUE TITLE
Tweaks to new footer

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#8636]
After testing the new footer, there are a few tweaks needed mainly to improve it on mobile:

1. Change the `Privacy and cookies` link to `Privacy and terms`
2. Change the order of the second column of links to `Jobs, Media office, Developers, Privacy and terms, Modern slavery statement`
3. On mobile, change the flex basis of the first column of links to 35%, as this is better visually balanced due to padding
4. Increase the line height of the CC licence text
5. I'm not sure if this is new, but I'm getting a thin white line below the footer when scrolling past the bottom of the page on mobile

**Comment by dannybirchall** [comment]
@jtweed Are we using 'privacy and terms' to match the Trust site? Might this have any impact on the cookies work we're doing this 1/4?

**Comment by jtweed** [comment]
Yes. It's also the wording from your email thread, which I think got mixed up with cookies at some point.

We're going to need our own cookies page when we do the consent work, as we use different cookies to the Trust site, so at that point I think we add another separate Cookies link that goes there.

**Comment by rcantin-w** [comment]
@jtweed Just to check, are you saying we're re-adding a Cookies link or only once we create our own?

**Comment by jtweed** [comment]
Once we create our own.

**Comment by jtweed** [comment]
Strangely, neither can I! The only thing I’ve changed is that I’ve updated my phone from iOS 16 to 16.0.2, so potentially it was a small Safari bug.

**Comment by rcantin-w** [comment]
> Strangely, neither can I! The only thing I’ve changed is that I’ve updated my phone from iOS 16 to 16.0.2, so potentially it was a small Safari bug.

OK let's keep an eye out, in the meantime our PR is ready for the other changes 👍
