### ISSUE TITLE
Set up GA4 Prod and Staging Properties

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8643]
GA4 needs to differentiate between Staging and Prod so that:-

1. Prod is not contaminated by Staging data
2. Staging results are not confused by Prod

Part of epic #9101

**Comment by gestchild** [comment]
Is this something we can use [Data filters](https://support.google.com/analytics/answer/13296761?hl=en) and/or [report filters](https://support.google.com/analytics/answer/11377859) to do?

**Comment by taceybadgerbrook** [comment]
It seems it's something that could be set up in Data Streams. Here's an article I'm in the midst of:
https://organicdigital.co/blog/how-to-set-up-google-analytics-and-ga4-on-multiple-environments/

**Comment by taceybadgerbrook** [comment]
The issue is that currently GA is including data from www-stage.wellcomecollection.org as well as previews derived from prismic. This isn't such a big deal overall but when analysing pages with small numbers of views (eg digital guides), I end up having to filter for testing and prismic previews to avoid misleading results. The easy option is to filter these out of our GA4 property.

@alexwlchan do we need GA4 to report on www-stage.wellcomecollection.org?
@dannybirchall do we need GA4 to report on prismic-generated previews?

**Comment by jennpb** [comment]
Answering on behalf of a holidaying @dannybirchall so this issue isn't blocked. I can't see why we'd need to track or report on prismic generated previews, unless it's the only way of spotting when a `preview.wellcomecollection.org` link has made it out into the wild.

**Comment by alexwlchan** [comment]
> do we need GA4 to report on www-stage.wellcomecollection.org?

I don't know, I don't normally look at the GA data. Can't see why we would; it's not public facing.

**Comment by alexwlchan** [comment]
> unless it's the only way of spotting when a preview.wellcomecollection.org link has made it out into the wild

We did an exercise a while back to make sure all our canonical URLs were pointing at wellcomecollection.org, so this is pretty unlikely.

**Comment by taceybadgerbrook** [comment]
@alexwlchan @jennpb I've never been asked to report on www-stage.wellcomecollection.org so I'm thinking this is something that should have been filtered out but maybe just got forgotten about. 

Using Data Streams and lookup, I can divert data from www-stage.wellcomecollection.org and prismic-generated data to a different data stream. This will mean the data is not included in the reporting data stream.

**Comment by taceybadgerbrook** [comment]
@gestchild I've set up a GA4 property called GA4 Staging. This has measurement Id G-HQGTCHD9GX. I've also created a tag called GA4 Reporting Staging Config which uses a lookup table so that page views for www-stage.wellcomecollection.org don't get reported in [Default] Collection. It's in Preview mode just now and seems to be ok.

Other tags like web vitals and tree item click won't be fired if someone is using www-stage.wellcomecollection.org because they are set up for [Default] Collection. Is that ok or do you think there's a case for tagging GA4 Staging, too?

**Comment by taceybadgerbrook** [comment]
@gestchild I'm going to publish this version anyway and see if any pageviews on www-stage.wellcomecollection.org make it into [Default] Collection stats.

**Comment by gestchild** [comment]
> . It seems that web vitals fires even though this is a different property so problem solved.

Yes, these are set up in GTM, so they'll alway fire. The lookup table bit you did just determines which GA4 property they get sent to.

> What is interesting is that setting up a new staging property and a lookup table certainly collects the data from www-stage.wellcomecollection.org _but it doesn't exclude this data from [Default] Collection._

This doesn't make sense to me, it should only be able to send to one or the other. Are you using the lookup table custom variable you set up as the value of the measurement id in the GA4 configuration tag?

**Comment by taceybadgerbrook** [comment]
@gestchild 

> This doesn't make sense to me, it should only be able to send to one or the other. Are you using the lookup table custom variable you set up as the value of the measurement id in the GA4 configuration tag?

Yes, here's a snapshot of how I've set it up:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/32418070/219419713-48ae709d-55b0-4814-aec6-087525fd2fa5.png">

**Comment by gestchild** [comment]
That's the variable config, you then need to use that variable in the GA4 config tag

![Screenshot-2023-02-16-at-16 02 21](https://user-images.githubusercontent.com/6051896/219421465-c9e9d88d-5c47-4ce4-8bed-ab34c9953d92.png)

**Comment by taceybadgerbrook** [comment]
Here's what I've done 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/32418070/219422177-1bf94f51-a181-4bec-bab2-be2b7abeafb9.png">

**Comment by gestchild** [comment]
I'm still seeing the original value not that custom variable?

**Comment by gestchild** [comment]
Ok, I can see now - you've set up a second GA4 configuration tag. We just want to use the original one and replace the measurement id value in that one with the lookup table variable you created.

That way it will send to one or the other.

As it's set up at the moment, we're still sending everything to the original GA4 property and only staging traffic to the new staging GA4 property

**Comment by taceybadgerbrook** [comment]
I did wonder whether I was creating a parallel universe.

Is GA4 Configuration G-206J7SLYFC the tag I edit?

**Comment by gestchild** [comment]
yes, just need to edit the measurement id value to be {{Lookup table reporting vs staging}}

and then delete the 'GA4 reporting staging config' tag

**Comment by taceybadgerbrook** [comment]
Done

**Comment by taceybadgerbrook** [comment]
New GA4 property for data from www-stage.wellcomecollection.org will be able to be viewed here
https://analytics.google.com/analytics/web/#/p353824724/reports/reportinghub?params=_u..nav%3Dmaui

**Comment by taceybadgerbrook** [comment]
GA4 [Default] Collection property now ignores all page views from wellcomecollection.prismic.io generated by Prismic preview facility.

**Comment by jennpb** [comment]
@taceybadgerbrook
Can I confirm that this is what we actually want?

A Prismic preview link looks like this https://preview.wellcomecollection.org/events/Yk7i6xAAACMAYA5B - we don't want to count these

But an outbound link to a PDF that's uploaded to Prismic for publication looks like this https://wellcomecollection.cdn.prismic.io/wellcomecollection%2F4207b8c8-70d1-461e-bea6-f9da13f9a55a_wellcome+collection+who+we+are+and+what+we+do_2.pdf - **which we do want to track**

If we're ignoring page views from wellcomecollection.prismic.io, which type is that?

**Comment by gestchild** [comment]
To clarify, we use a [lookup table variable in Google Tag Manager](https://www.optimizesmart.com/understanding-lookup-table-variable-google-tag-manager/#:~:text=In%20the%20context%20of%20GTM,default%20value%20has%20been%20set) to point to the GA4 property we send data to, based on the hostname.

- If the hostname is wellcomecollection.org the data is sent to the Default property we already had set up.
- If the hostname is www-stage.wellcomecollection.org the data is sent to the new staging property[ Tacey just set up and linked to above](https://github.com/wellcomecollection/wellcomecollection.org/issues/8643#issuecomment-1433478389).
- If the hostname is preview.wellcomecollection.org then the data isn't sent anywhere, as we don't account for this hostname in the lookup table.

Outbound (and Downloads links) on our site, to other domains such as those hosted on wellcomecollection.cdn.prismic.io, will be tracked as part of GA4's enhanced measurements.

We'd never get page views from wellcomecollection.prismic.io in our analytics as this isn't our site and is not running our analytics code.

**Comment by taceybadgerbrook** [comment]
GA4 properties [Default] Collection and GA4 Staging now collecting mutually-exclusive data. Hurrah!

Page views generated by Prismic preview facility now being excluded from [Default] Collection.
