### ISSUE TITLE
adjust apitoolbar for anchor links to pick these up again

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8649]
When you go to an anchor link it doesn't bring you to the point on the page where the video or audio file is. I have tested on mobile view, and on links that should bring you to a point half way down or at the end of the page. Visiting the link just loads the audio/bsl guides page as a whole.

**Comment by alexwlchan** [comment]
I think I fixed this here: https://github.com/wellcomecollection/wellcomecollection.org/pull/8653/files#diff-0416adcd46e8609c6c4828ba02d88be7792fabb784462f3c4885eb78ee461165R75

**Comment by melanierogan** [comment]
Yep, i just need to adjust the api toolbar to pick up the links for video and bsl
