### ISSUE TITLE
Determine routing solutions for Search pages

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8689]
We know we want the URL convention to be `/search/[type]`, but as page header elements get repeated (especially the tabs, which will have to behave more like links than tabs), it begs a bit of a think for the best way to go around it. The initial intention was to do have one file per folder (following the NextJS convention), but is that the best for what we need? [Layouts](https://nextjs.org/blog/layouts-rfc) would have done nicely, but it'll have to be a future change. 

In the meantime, we're discussing different aspects of what is required, like query fetching (could we use [React query](https://www.apollographql.com/docs/react/data/queries/)?) and what different user journeys look like.

**Comment by AMBacelar** [comment]
To have the search subpages exist while passing on the relevant query parameters.
To have reusable layout logic that reduces code repetition
To allow sharable page urls
