### ISSUE TITLE
New search query input

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8701]
Style the new search query input which will then be used on the Search pages + the header search component.

[Mockup; in page](https://www.sketch.com/s/1cc6a024-668b-4d76-9617-115910d3a797/a/qemA41k)
[Mockup; in header](https://www.sketch.com/s/1cc6a024-668b-4d76-9617-115910d3a797/a/GmKPzVE#Version)

![Image](https://user-images.githubusercontent.com/110461050/196480455-3f920ae9-4910-4bc0-8abd-62e8143d9703.png)

**Note:** The version one version doesn't have autocomplete.

**Comment by AMBacelar** [comment]
I assume that the search that's in the header is making use of some for of indexed search tool that will return search results as you type?
I also assume that you _only_ go to the search pages if they click the last option `All search results for [query] ([result count])`?
