### ISSUE TITLE
Refactor/rename TabNav component for list of links

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8703]
After talking about the Search navigation, we decided that what we thought would be tabs should actually behave like a list of links.

We want to redo this component, scrapping about 90% of the `TabNav` code; we just need to replicate its look and behaviour (horizontal scroll on smaller screen sizes). The original version won't be used anywhere else after we:
- Ensure we support the new component in `/concept` instead of `TabNav`;
- Change the links in `contributor` pages to have the "By" tabs pre-selected;

So `TabNav` can then be deleted in favour of the new component (`PageNavigation`?)

**Comment by jtweed** [comment]
I'm not sure if we want to link directly to the "by" tab from contributors. There's a trade off between consistent experience and implying intent. Maybe something to test, possibly during any future user testing by @alicerichmond of new concepts/search/works?

**Comment by rcantin-w** [comment]
We've decided to keep them separate for now. The version in Concept does not need routing (it could get complicated quickly), so we've made the second one, but will look into making visual changes to help differentiate.
