### ISSUE TITLE
Search: Update search box on collections section page

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8708]
Change search tool in https://wellcomecollection.org/collections to have the new searchbar. Once the user click search it opens `/search/works` with the user's query prefilled.

**Comment by rcantin-w** [comment]
@jtweed are we happy to delete this if we're doing it all in one go, now?

**Comment by jtweed** [comment]
I'd like to leave it open for now, as a reminder that we need to confirm what search looks like on:

https://wellcomecollection.org/collections

**Comment by rcantin-w** [comment]
What happens to the tabs that are currently there, do we remove them and just keep the search bar? I'm thinking people are used to accessing `/images` that way (there is no other way?) so they might get confused. Do we want to replace it with a link to `/search/images` until we add the searchbar to the header?

**Comment by rcantin-w** [comment]
So clicking on the "Images" tab takes you to `/search/images`? That would be the behaviour with the redirect anyway so it would default to that. 

Should we have a notice somewhere to warn users about the new search ("...and please send us feedback") so they're not too confused by it all?

**Comment by jtweed** [comment]
As discussed, let's leave this as is and rely on the redirects to take people to the right page on global search. We will refresh as part of a redesign of /collections, probably to limit to catalogue search.
