### ISSUE TITLE
Remove search from a work page

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8735]
Once:
1. The new search page for works has gone out 
2. The search icon has been added to the header 

Remove the searchbox from a work page (for example: https://wellcomecollection.org/works/a222wwjt)
and change the "back to search" link to point to the new search page.

**Comment by jennpb** [comment]
I do have concerns about removing a catalogue search box from the works pages. Researchers who are running multiple searches in a session need to have immediate access to the search bar to iterate their search. By relying solely on the global nav, we potentially add an extra click for every new search. This is unwise.

Before this goes forward, let's chat through what the intended behaviour would be, given the designs from Gareth O. cc @DominiqueMarshall

**Comment by rcantin-w** [comment]
Thanks for that @jennpb ! The context I remember from chats with @jtweed was around saving up space in works as we'd have the search in the header moving forward. That being said, we're not doing that right away - it would make more sense to not action this ticket for the initial release.

Instead, we'd just have to ensure that clicking "Search" leads to the new page moving forward (which it will with a redirect, but it'd be nice if the redirect wasn't needed!)

**Comment by jtweed** [comment]
I think this ticket should probably be closed, with any future decisions and/or work on this to be owned by @jennpb.
