### ISSUE TITLE
Source text field in metrics-conversion-prod index pattern

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8752]
Source contains useful information on how users arrive at various collections pageviews. This used to be a feature of the metrics-conversion-prod index pattern and has been used for interesting Python analysis. This field also forms part of the item page view definition, so reinstatement will allow more accurate dashboard statistics.

Examples of source are:-

"viewer/paginator": indicates when users are paging through online items
"unknown": indicates when user arrives from organic search
"works": user clicked on link in another works page

**Comment by jamieparkinson** [comment]
Can you give some steps to reproduce this? Not all documents have the field, but I can see it fine:
![image](https://user-images.githubusercontent.com/4429247/197779689-eafcf3f3-4c45-4a34-a988-e1de8b530407.png)

**Comment by taceybadgerbrook** [comment]
Ah, foiled by the Popular subgrouping! Thanks for looking at this so quickly.
