### ISSUE TITLE
Image search user journey mapping/jobs to be done

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#8757]
Review the current image search journey to help evaluate where the challenges are within the experience.

**Comment by jennpb** [comment]
Alice and Jenn to support mapping

**Comment by DominiqueMarshall** [comment]
Link to the current state of the image search journey: [Miro board](https://miro.com/app/board/o9J_khZNYIw=/?moveToWidget=3458764536974050725&cot=14)
