### ISSUE TITLE
Search: Add "clear" button to input

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8803]
This was missed, but we currently use it and might want to consider adding it to our new search input.

Ensure we take into account p.40 of the 2021 a11y report which flagged issues with the current one.

![Image](https://user-images.githubusercontent.com/110461050/198335087-031385ce-34f3-4bc8-bc69-c91943923981.png)

**Comment by pollecuttn** [comment]
@AMBacelar Should this be closed?
