### ISSUE TITLE
Search: Create query for Overview results

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8805]
The overview page will query all five categories at the same time (stories, events, exhibitions, images, works)

- What makes up Stories? Articles / webcomics / stories - anything else?

This ticket might need to be split in half as prepping the queries for Content is different than Catalogue, but they all already exist so maybe we can do it all together?

**Comment by rcantin-w** [comment]
@jtweed see the question above, can we get confirmation of what should be queried as part of Stories?

**Comment by jennpb** [comment]
Should that also include `/series` and `/books`?

**Comment by jtweed** [comment]
Good question. I had initially thought it would only be what really articles, but on reflection it should probably include everything that can appear within the stories section. So I think that's a yes, it should, but if that complicates things we might leave it for a future iteration.

**Comment by rcantin-w** [comment]
@melanierogan this is assigned to you but reckon we'll have to take it over :) 

I'm thinking the simplest and possibly only(?) way here is to do our three queries with smaller amount of results... From the mockups 
- 4 stories
- "2 lines" of images, which might be around 12 results
- 5 works

If you have any other ideas having played with the queries a bit more, do shout!

**Comment by rcantin-w** [comment]
Not at all, just noticed we'd assigned it to you! But good to discuss. There won't be pagination on that page, just a button to invite people to the filtered down pages 👍

**Comment by rcantin-w** [comment]
Created a PR for it with the TODOs that are left: https://github.com/wellcomecollection/wellcomecollection.org/pull/8996
