### ISSUE TITLE
Analysis of existing navigation from works page to digitised item

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8827]
**What is the problem to solve?**
We want to offer researchers a more streamlined process when going from the works page to the item page.

**What stage of research is it?**
discovery

**What are the objectives?**
- to benchmark behaviour

**What are the assumptions?**
- that researchers will understand how to use the tab navigation

**What research technique is required?**
Python

**Comment by taceybadgerbrook** [comment]
Assuming that users engage in these kinds of behaviours on a consistent basis, all metrics are calculated for the period 1/9/22-31/10/22 and expressed as percentages so that we can compare behaviour after deployment without having to control for the Christmas lull or January surge.

|Navigating from work to images||
|:--|--:|
|Total number of wellcomecollection/works page views| 207,099|
|Total number of navigations from wellcomecollection/works page to wellcomecollection/images| 9,346| 
|Percentage of wellcomecollection/works page views followed by a journey to wellcomecollection/images|4.5%|

|Navigating from work to full digitised item||
|:--|--:|
|Total number of page views for pages containing "/works/*"| 503,925|
|Total number of navigations from pages containing "/works/*" to pages containing "/works/*/items"| | 
|Percentage of wellcomecollection/works page views followed by a journey to item page view|%|

**Comment by jennpb** [comment]
@taceybadgerbrook Quick question - for `Navigating from works pageview to full digitised item pageview`, is that data limited to those works with digitised items, or is it all works?

**Comment by taceybadgerbrook** [comment]
@jennpb The works pageviews counted are all works pageviews regardless of whether they afford views of digitised items or not. The item pageviews are the pageviews generated when a user clicks, "View."

There is no field available in the metrics-conversion-prod index pattern which I can use to filter for works pages which are linked to digitised items. I think calculating a percentage of item pageviews / all works pageviews will work as a benchmark as long as we used the same calculation after deployment.

**Comment by jennpb** [comment]
> There is no field available in the metrics-conversion-prod index pattern which I can use to filter for works pages which are linked to digitised items

Is there a possibility of getting that information in the future? Anything that can be added to allow filtering by works that have digitised items? That would help us to isolate analysis of digitised material usage, rather than grouping it with all possible works.

**Comment by taceybadgerbrook** [comment]
@jennpb I think this is something to raise at the next planning session. I'll write a ticket.

**Comment by taceybadgerbrook** [comment]
I've raised ticket #8869

**Comment by taceybadgerbrook** [comment]
@jennpb Following our discussion of researcher journeys today and because the new tab navigation is about affording easier transitions, I am going to simplify this analysis by providing percentages of the navigations between:

- search and works page
- works page and item page
- works to images 

This will give us a sense of the relative importance of certain journeys.

As far as success metrics are concerned, this may well rest on UR because we wouldn't want to see fewer journeys or navigations, only easier ones.

**Comment by jennpb** [comment]
Let's loop this into conversation with @DominiqueMarshall next week.

**Comment by taceybadgerbrook** [comment]
These benchmarks work best when viewed as journeys between search/works/item activities. If the percentage of journeys out of total events increases, we will know that changes made to the tabbed navigation have made activities easier.

100,000 events occurring on 26-28/11/22 were analysed. Assuming that users engage in these kinds of behaviours on a consistent basis, all metrics are expressed as percentages so that we can compare behaviour after deployment without having to control for the Christmas lull or the January surge.

|Navigating between search and works pageviews||
|:--|--:|
|Total number of journeys between search and works pageviews|13,144| 
|Total number of events| 100,000|
|Percentage of journeys between search and works pageviews out of total events|13%|

|Navigating between works and item pageviews||
|:--|--:|
|Total number of journeys between works and item pageviews|4,696| 
|Total number of events| 100,000|
|Percentage of journeys between search and works page views out of total events|5%|

|Item pageviews due to pagination||
|:--|--:|
|Total number of journeys between works and item pageviews|18,116| 
|Total number of events| 100,000|
|Percentage of journeys between search and works page views out of total events|18%|

**Comment by taceybadgerbrook** [comment]
@jennpb I've reduced user interactions to their basic form so that it will be easier to detect changes after tabbed navigation gets deployed.

**Comment by jennpb** [comment]
Thanks @taceybadgerbrook. Can you clarify what constitutes an event in this analysis? I'm not fully up to speed on this yet.

**Comment by jennpb** [comment]
Navigating between works and item pageviews |  
-- | --
Total number of journeys between works and item pageviews | 4,696
Total number of events | 100,000
Percentage of journeys between search and works page views out of total events | 5%

- Is the last row meant to be item pageviews?
- Is this out of the total number of works, or the subset of works that have items?

**Comment by taceybadgerbrook** [comment]
@jennpb an event in Elasticsearch data is anything that users do that we track: clicking on the Library catalogue or Images tabs, entering a search term, clicking to page through search results, selecting a search result to view a works page, clicking on View to bring up the viewer, paging through a work or navigating through manifests, downloading, to name but a few!

**Comment by taceybadgerbrook** [comment]
@jennpb 

> <p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Question:</p>
> 
> Navigating between works and item pageviews |  
> -- | --
> Total number of journeys between works and item pageviews | 4,696
> Total number of events | 100,000
> Percentage of journeys between search and works page views out of total events | 5%
> 
> <ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Is the last row meant to be item pageviews?</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Is this out of the total number of works, or the subset of works that have items?</li></ul>
> 

The last row is the percentage of all the journeys users made from works pageviews to item pageviews and vice versa out a total of 100,000 events. It's expressing in numeric terms, "How much does this kind of activity account for in all of the user interactions?"
