### ISSUE TITLE
Add Pageview to more pages

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/wellcomecollection.org#8841]
As part of new tracking for Search, we want to add Pageview information to

- All new search pages
- All stories/events/exhibitions pages
- Concepts(?)

We need to determine which `properties` are useful to pass in and decide on a `name` for each of the above.
```
pageview: {
   name: 'search',
   properties: [TBD]
}
```

**Comment by harrisonpim** [comment]
Scribbling some rough thoughts here before chatting this afternoon.

We've already got a pretty solid foundation in the basic `trackPageview` function; a lot of info is already collected from next's `Router` (path, all query params, etc). In the interest of simplicity (and privacy!) i think any extra data we collect should be tied to specific questions which can't be answered with that foundational stuff.

If we're only interested in measuring conversions from search -> works/images/stories/events/exhibitions/concepts at the moment, I think a direct replication of the existing search tracking will be sufficient, eg something like

```ts
// exhibitions.ts
pageview: {
  name: 'exhibitions',
  properties: exhibitions ? { totalResults: exhibitions.totalResults } : {},
},
```

```ts
// exhibition.ts
pageview: {
  name: 'exhibition',
  properties: {}
},
```

If we figure out some questions which need more data, we can always add to those `properties`!

**Comment by rcantin-w** [comment]
Few questions for @harrisonpim 

1. Turns out I'd already added pageview in `/search/images` and `/search/works`, but the defined `name` is the same as it is in `/images` and `/works`. Would it be better to pass something different as they will exist at the same time for a bit (albeit under a toggle), or is having a different URL enough?
2. For "stories", we have a few different page types that fall under it. "Article", and I think [we also want to get series and books ](https://github.com/wellcomecollection/wellcomecollection.org/issues/8805#issuecomment-1300506745).
Should the pageview name be the same for those 3 (`stories`?), or should they stay individual?

**Comment by harrisonpim** [comment]
>Turns out I'd already added pageview in /search/images and /search/works, but the defined name is the same as it is in /images and /works. Would it be better to pass something different as they will exist at the same time for a bit (albeit under a toggle), or is having a different URL enough?

I think a different URL should be enough! From my pov, there's no need to complicate things by distinguishing between old and new versions of the UI if they're using the same query behind the scenes

> For "stories", we have a few different page types that fall under it. "Article", and I think https://github.com/wellcomecollection/wellcomecollection.org/issues/8805#issuecomment-1300506745.
Should the pageview name be the same for those 3 (stories?), or should they stay individual?

oof, that one's a bit tricky... I think the pageview name should be the same, and if the generic type is `article` then we should probably reflect that?? We could differentiate between the page types by adding the type detail to the properties, as we do for works:

```ts
pageview: {
  name: 'article',
  properties: {
    type: articleResponse.articleType, // could be story, book, etc
    ...
  },
},
```

What do you think? Does that feel reasonable to you?

**Comment by rcantin-w** [comment]
>  I think the pageview name should be the same, and if the generic type is articles then we should probably reflect that?? 

I _think_ it's Stories because it's how we call the section. @melanierogan do you have more info for that?

> We could differentiate between the page types by adding the type detail to the properties

Sounds good to me 👍
