### ISSUE TITLE
Duplicate ids

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#8843]
Our automated accessibility checks are flagging an issue with [this page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/captions-and-transcripts) because there are elements with duplicate ids and ids must be unique. 

The ids are created from titles, which then allow us to link directly to a particular stop (used for the QR codes). The problem is that some of the titles are the same, e.g. "Ojos de dios (God’s eyes)" and "Notes On Blindness: Into Darkness". 

We could make ids unique, by appending the stop number to it, but this would mean all the urls behind the QR codes would need updating. Otherwise is it possible to change these specific titles in some way to make them unique?

**Comment by pollecuttn** [comment]
Due to be updated Monday 28 Nov - see https://wellcome.slack.com/archives/C3N7J05TK/p1668015908793739
