### ISSUE TITLE
Search: Exploration, pagination and Prismic fetch pages

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8860]
Determine if we can make it work with Prismic fetchLinks pages (estimate effort)

e.g. https://www-stage.wellcomecollection.org/articles

**Comment by melanierogan** [comment]
In the case of `/stories` using SearchPagination component works, and I've opened a PR to show that in place. 

I've left the PR in draft as there are issues with `/exhibitions` and `/events`. I'm going to estimate the remaining effort to make events and exhibitions work with SearchPagination, if I can get it working myself, I'll put my workings in the draft PR.

**Comment by rcantin-w** [comment]
So it does work, the branch just fell victim to a bug that was merged in main, but merging the fix in and testing the new pagination in article series, exhibitions, events, it all seems to work nicely. The next steps will be https://github.com/wellcomecollection/wellcomecollection.org/issues/8963 (replacing pagination in content pages) and https://github.com/wellcomecollection/wellcomecollection.org/issues/8964 (replacing catalogue pagination), although I might consider merging them into one ticket. 

I'm leaving the [PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/8948) open as we can use it for the work above - it's already started.
