### ISSUE TITLE
Track Visually Similar Images usage

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8885]
As far as I can tell there is currently no tracking on image modals/visually similar images. Clicking on them doesn't send out a GA Event nor does it change the URL to trigger a pageview.

[See Slack thread](https://wellcome.slack.com/archives/C02ANCYL90E/p1668610825676639)

@harrison to flesh out this ticket regarding the "how we integrate more tracking", but for the "what we track", he'd like:

- the timestamp
- the source image id
- the clicked image id
- the user's session id

**Comment by taceybadgerbrook** [comment]
I'd quite like page.pathname and page.name, too.

**Comment by taceybadgerbrook** [comment]
Yes, that would be expected. Great stuff.
