### ISSUE TITLE
Repairing UA and keeping GA4

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#8892]
**What**
Deployment of GA4 in 2020 and switching on Enhanced Measurement in July 2022 has resulted in double tagging of pageviews and distortion of bounce rate in UA.

**Where**
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/32418070/202501206-466fda30-3eba-4045-ba83-34df52b846d6.png">

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/32418070/202501025-dec21206-5462-4abd-84df-44812c296fbe.png">

**Comment by taceybadgerbrook** [comment]
The PR from November 2020 swapped out the cross-domain (wc.org and wl.org) Google Tag Manager code snippet in the head with a GA4 code snippet. Google Tag Manager also had a code snippet in the body which was not deleted. This has had the effect of "folding" the UA code snippet within GA4.

**Comment by taceybadgerbrook** [comment]
Steps to fix:

1. Document all GA4 Explore reports in existing property. 
2. Export GA4 Explore reports for current month for reference.
3. Revert [PR 5723](https://github.com/wellcomecollection/wellcomecollection.org/pull/5723/files). This will result in removing GA4 and reinstating the cross-domain Google Tag Manager container.
4. Test UA pageviews and bounce rate. They should revert from double back to single tagging.
5. Install the [Google Tag Manager container code head and body snippets](https://tagmanager.google.com/#/admin/accounts/6000872529/containers/31009043/install?containerDraftId=1) for just wellcomecollection.org. Here is a link with [more installation information](https://support.google.com/tagmanager/answer/6103696).
6. Install new GA4 property using Google Tag Manager.
7. Reinstate all GA4 Explore Reports.
8. Compare GA4 report data to previous GA4 report outputs.

**Comment by jennpb** [comment]
We've agreed there's no reason to 'repair' UA. Is there anything relating to the Explore reports that are worth splitting out into different actionable issues @taceybadgerbrook ? 

> Install new GA4 property using Google Tag Manager.
This doesn't need to be done. We can use our existing GA4 property with GTM

**Comment by taceybadgerbrook** [comment]
The Explore reports will be unaffected by the linkage to GTM. However, it is good practice to document the details of these reports in case they get deleted by other users. Once the GA4 property starts being shared, the risk of this happening becomes very high.
