### ISSUE TITLE
Enable prototyping work for Local Contexts information

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#8900]
# Context

The Collections Information team have been working to apply some data to catalogue records to enable us to use the [Local Contexts attribution labels and metadata](https://localcontexts.org/labels/traditional-knowledge-labels/) on objects/items in our collections. This is a framework (a bit like Creative Commons) that allows institutions to signpost objects held by institutions that belong to Indigenous communities.
 
We're participating in a meeting on Tuesday 29 November to understand how Wellcome Collection can implement the Local Contexts labels in the catalogue, and to give the Local Contexts team in NYC our feedback as implementers.
 
## What needs to be done

- Set up a test environment to enable quick, hacky prototyping on 29 November @davidpmccormick @gestchild 
- Basic familiarity with the [Local Contexts API](https://localcontexts.org/api-guide/) @davidpmccormick @gestchild 
- Gather any sketches from previous meeting @DominiqueMarshall 

**What are the assumptions?**

- That the wifi in Wallacespace will be good enough
- That the Local Contexts API endpoint is robust
- That we have a sample set of records to use

**Comment by dannybirchall** [comment]
⬇️ for info if useful. there's a page that references local contexts here:

https://wellcomecollection.org/pages/YgZPOxMAAB4AM-ew

that links to WC's local contexts hub page, here:

https://localcontextshub.org/institutions/view/58/

in part because that's currently the only way that we can list the items that we're currently open to collaboration on

**Comment by davidpmccormick** [comment]
Who has the ability to edit the local contexts item information? Looking at the api docs seems like there should be the option to add a `providers_id` for items, which can be searched on. If we added, e.g., the work id as this value, then we could match works and local contexts with relative ease.
