### ISSUE TITLE
Improve the way we model recurring and multi-day events

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8902]
This is a follow-up to https://github.com/wellcomecollection/wellcomecollection.org/issues/8830; that ticket covered the short-term fix to make that event work; this is to discuss possibly remoddeling these in Prismic.

## Recurring events

This is how recurring events are modelled in Prismic:

```mermaid
graph LR
    L["<b>Lights Up</b><br/>times: 3 Nov &ndash; 9 Feb"]
    L --> L1["<b>Lights Up session 3 Nov</b><br/>times: 3 Nov @ 4pm &ndash; 8pm<br/>delist = true"]
    L --> L2["<b>Lights Up session 15 Nov</b><br/>times: 15 Nov @ 10am &ndash; 2pm<br/>delist = true"]
    L --> L3["<b>Lights Up session 6 Jan</b><br/>times: 6 Jan @ 2pm &ndash; 6pm<br/>delist = true"]

    classDef eventNode text-align:left,fill:#fff9e6,stroke:#ffebad
    class L,L1,L2,L3 eventNode

    classDef mainEvent stroke-width:3,fill:#ffebad,stroke:#ffce3c
    class L mainEvent
```

There's one event which appears on the What's on page, which represents the group of events. There are then individual events for each of the sessions, which are linked via the Schedule tab in Prismic. These events are delisted, so they don't appear on the what's on page.

The Editorial team will put:

* the times for each event on the individual Event document in Prismic
* a range from the earliest start to the latest end on the summary Event document

However, it's a bit weird that each of the individual events is a full event, even though they're not individually addressable and contain a subset of fields.

## Multi-day events

Multi-day events have caused us problems recently:

<img width="772" alt="Screenshot 2022-11-21 at 13 41 31" src="https://user-images.githubusercontent.com/301220/203069854-7bd8a34b-03f6-4e01-9664-7ac228185762.png">

One outstanding problem (possibly among others) is that they don't appear in the "Today" view on an intermediate day; that view only looks for events which start today.

**Comment by LaurenFBaily** [comment]
Closing and adding into the Notion roadmap to be explored: https://www.notion.so/wellcometrust/Child-events-8e5db82feab74315ace88b0c4b3de308?pvs=4
