### ISSUE TITLE
Feedback component: UX/UI and content design

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#8925]
# What is it and who's it for?

* For users to let us know whether they've found a page useful
* For us, to gather feedback on areas of the site where the content or functionality didn't meet user needs.

This allows us to gather input and put it into a place where we can analyse the responses.

Part of epic https://github.com/wellcomecollection/wellcomecollection.org/issues/6114

## User story
As the Digital Access team
We need a way to gather unstructured feedback from users
So that we can identify areas of improvement across the whole site

## Background
Dom's Invision prototype that shows what we would like to aim for when each button is selected: https://wellcometrust.invisionapp.com/console/Content-Feedback-Concepts-cksa9uboe00ia0171bxfg0kcf/cksa9uc6500ib0171ht2w63gq/play

# MVP
Must have:
* A free text field, with contextual instruction, for user comments
* A way to input whether page was helpful or not
* A way to link to the user panel signup 
* A backend connection to an Airtable database 

Must not:
* Ask for personally identifiable information - we want to encourage anonymity with this feedback

# Done when
- [x] Design options using design system colour palette
- [ ] Microcopy agreed btw @DominiqueMarshall @jennpb 
- [ ] Check for any other conflicts/dependencies with Collections Information @jennpb 
- [ ] We've mapped the data collection flow
- [ ] It's been discussed with devs for feasibility

**Exclude it from:**

- homepage
- item pages
- landing pages

**Include it on:**

- Stories pages
- Works pages (TBC)
- Informational pages (accessibility, visiting info)
- Exhibition guides (or on exhibition pages)

**Comment by DominiqueMarshall** [comment]
Here's an updated design of the feedback flow on desktop: https://zpl.io/O096oj1 (@jenn let's use this to review the microcopy, in particular the user panel text and 'report a problem' text)

Example of the form within the new works page design: https://zpl.io/W4P61Jk

Mobile design examples
 - Default form: https://zpl.io/09nXZKE
 - Yes button selected: https://zpl.io/3X7Azml
 - No button selected: https://zpl.io/ewr6gZY
 - Report a problem selected: https://zpl.io/1ymRZPw

**Comment by jennpb** [comment]
Thanks @DominiqueMarshall. Do we also need a confirmation state after feedback is submitted? And would that be the same for all 3 states?

 I've added in one more step to check for any potential conflicts with Collections Info/AE, particularly as there used to be a 'Comments or corrections to this catalogue record' link in the old catalogue > this could have workflow implications for them if we include the form on works pages.

**Comment by DominiqueMarshall** [comment]
I've just updated the first link; I think the confirmation state could be the same for the yes/no responses, but the 'report a problem' confirmation state should have a slightly altered message (The state in the mockup feels like it needs more, but I'm not 100% sure what it should say atm). 

With the confirmation states, do you think that should be where we invite people to join our user panel, rather than having it under the Send Feedback button?

**Comment by jennpb** [comment]
Won't do now, rationale detailed here :https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Research%20operations/Feature%20idea%20Feedback%20Component.docx?d=w465c2be4f94243c684f7c79f700431d9&csf=1&web=1&e=PixOjE

Designs are solid if we can get a robust, shared CRM backend attached to it (so we can more easily triage info to other parts of WC)
