### ISSUE TITLE
Implement a proper schema for our prismic graphql instance

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/wellcomecollection.org#8953]
We get some validation errors on or `gql` graphql queries within our codebase. 
One such error: 
`Unknown field "allEventss": The parent selection or operation does not resolve to a valid schema type`

I did some digging on how best to do this on Prismic instance, one of the Prismic engineers suggested this approach. The caveat being that this isn't exactly 100% stable, and having something flaky in place will mean we have to fix it a lot and future us will not like us. 

https://gist.github.com/angeloashmore/3a08e28c82e9d78ecb645af2258285a9

**Comment by alexwlchan** [comment]
I'm going to close this as WONTFIX – although we are still using GraphQL for our Prismic queries, we're now kicking off the work to replace those queries with an Elasticsearch-backed API populated by our own data pipeline. The current queries work well enough and I don't think we'll change them much before we switch to our own API.
