### ISSUE TITLE
Resolving comics in Safari 

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8971]
**What**

Something odd if going on with resolving comics… on Safari the Prismic content starts to load after 18 seconds and finishes after 31 seconds. The rest of the page loads very quickly. but a process remains running after page load i.e. JS & Events keep firing and the page continues to consume CPU before assets are silently reloaded

**Where**

See fuller conversation at  https://wellcome.slack.com/archives/C8X9YKM5X/p1669391657316569

**Comment by davidpmccormick** [comment]
I replied to the thread where Tom had mentioned it in Slack, saying that I couldn't see this behaviour any more. He noted that it is also faster to load.
