### ISSUE TITLE
Verify the behaviour of opening times in advance of the Christmas/New Year closure

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#8976]
We've had an email from LE&E:

> Expected behaviour:
> December 22 – January 2 unavailable in date picker
 >
> December 21 available until 10 am Tuesday 20 December
> January 3 available until 10 am Wednesday 21 December
>
> Over closure period – requesting possible, but first available date Wednesday 4 January.

I think this will all behave correctly, but we should double-check by ~putting the site in a time machine~ rolling the clock forward in a local instance of the site.

This is possible because the site has a single function that tells it when "now" is, and we can override it: https://github.com/wellcomecollection/wellcomecollection.org/blob/6f8fa4e1aba6cf07bf66013196e9eb30a4d877f7/common/utils/dates.ts#L4-L19

**Comment by alexwlchan** [comment]
<img width="825" alt="Screenshot 2022-12-08 at 12 03 01" src="https://user-images.githubusercontent.com/301220/206442832-08d9db32-a1bc-4e46-a50f-23a6c8948dd0.png">
<img width="822" alt="Screenshot 2022-12-08 at 12 03 11" src="https://user-images.githubusercontent.com/301220/206442840-01603870-7661-408d-81d3-17e9ee7ec1a4.png">
<img width="822" alt="Screenshot 2022-12-08 at 12 03 37" src="https://user-images.githubusercontent.com/301220/206442846-9015d097-d41d-48cc-a55d-885ac254cc7c.png">
<img width="821" alt="Screenshot 2022-12-08 at 12 03 46" src="https://user-images.githubusercontent.com/301220/206442850-f99ca602-de8b-4e6f-a0dd-5da3fae2920d.png">
<img width="820" alt="Screenshot 2022-12-08 at 12 06 49" src="https://user-images.githubusercontent.com/301220/206442902-5e327ca1-be28-493c-8925-522c94ff78fa.png">
<img width="820" alt="Screenshot 2022-12-08 at 12 06 57" src="https://user-images.githubusercontent.com/301220/206442905-1e5a8ca2-8f1d-4199-946c-81d4a3f154f8.png">
<img width="821" alt="Screenshot 2022-12-08 at 12 03 55" src="https://user-images.githubusercontent.com/301220/206442944-d3e38049-7d93-4d62-a578-c22f8d0c3692.png">
<img width="821" alt="Screenshot 2022-12-08 at 12 04 08" src="https://user-images.githubusercontent.com/301220/206442949-8f47e43b-1795-42b7-a877-ba7106e1806d.png">
<img width="820" alt="Screenshot 2022-12-08 at 12 04 17" src="https://user-images.githubusercontent.com/301220/206442951-3e19aa4a-5e8e-4411-99b4-bcd5ab1ce734.png">

**Comment by alexwlchan** [comment]
This all seems to be working correctly and I've replied to LE&E. Closing as done.

**Comment by pollecuttn** [comment]
@alexwlchan The screenshots above are really helpful!
