### ISSUE TITLE
Search: Overview reporting properties

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#8977]
When we added pageview events to the new search, we left this for the "Overview" page:

``` 
        pageview: {
          name: 'search',
          properties: {},
        },
```

@harrison and I thought we'd get back to it, thinking of which properties would be useful. Creating this ticket as I'm going on hols and wanted to track it somewhere! There is a TODO comment there too.

**Comment by harrisonpim** [comment]
Closing as we think the existing data is sufficient for now
