### ISSUE TITLE
Search: Exclude stories/events/exhibitions with the 'delist' tag

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#9003]
See discussion in Slack, including an example: https://wellcome.slack.com/archives/C016NQB58N4/p1671026264776259

**Comment by AMBacelar** [comment]
Editorial have expressed that since search is different to the main page, it is fine for content to be presented next to similar content, and for that reason the stories search page can ignore the `delist` tag
