### ISSUE TITLE
Better handle physical items which (1) can be ordered and (2) have more than a single page of Sierra responses

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#9029]
A reader has flagged an issue with these journals: https://wellcomecollection.org/works/s7edx7vt

The whole series should be requestable online, but everything from 1941 onwards is not requestable. Based on a quick inspection, it looks like this is happening:

1. The front-end renders a page with 100 items (or any large number of items > 50)
2. The items API asks Sierra for all of those items
3. Sierra returns 50 items in the first page of responses
4. The items API returns those 50 items to the front-end
5. The front-end marks items 51 and onwards as "not requestable"

We need to introduce pagination somewhere; I don't have a feeling instinct about where it goes. I think these are the two options:

* **Pagination in the front-end.** Pros: items will fill in gradually from the top, which feels nicer from a UX perspective, you can start taking action more quickly. Cons: pushing the nuances of the Sierra API down a level, more complexity in the browser.
* **Pagination in the items API.** Pros: the API gets to absorb the complexity of Sierra. Cons: blocks rendering any items until the complete set is available.

Given how long it's taken for this problem to emerge, my guess is that we don't have many works like this, and so maybe pagination in the items API is okay?

**Comment by rcantin-w** [comment]
I don't know if any work was done on this but all items have a "Request item" button now expect for one that is marked as missing, so I'd be tempted to close this ticket. We can always unarchive it should we get more feedback on this.

<img width="953" alt="Screenshot 2024-04-25 at 09 24 24" src="https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/165c2d34-9be3-4a14-b1bd-ee37c30a4e50">
