### ISSUE TITLE
A/B testing More info button in item view

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9032]
**We want to know if the following change has improved the user experience**
Changing "Catalogue details" link into button, "More about this item."

**Definition of success is**
Researchers find it easier to go back to the works page from the item view page.

**We'll know if we're succeeding if we measure the following metric and this happens**
Increased numbers of clicks back to a works page view following an item view

**Definition of failure is**
Button serves as a distraction and actually increases the amount of work researchers do. Users click to go back to the works page but do not make use of the links on page. 

**We'll know if we're failing if we measure the following metric and this happens**
Directly after an item page view and a works page view, there are 
- fewer clicks on concepts links,
- fewer clicks on Copy url and possibly
- fewer online requests.

**Comment by taceybadgerbrook** [comment]
# A = "Catalogue details" link #

properties.toggles:itemWorkLink 

# B = "More about this item" button #

source:button_back_link

Note: fields only take these values when part of the A B testing.

**Comment by taceybadgerbrook** [comment]
Quick check to see if A/B toggle is working:

Total A = (count of unique anonymousId with properties.toggles:itemWorkLink) / 2
A conversions = count of unique anonymousId with source:viewer_back_link

Total B = (count of unique anonymousId with properties.toggles:itemWorkLink) / 2
B conversions = count of unique anonymousId with source:button_back_link

**Comment by taceybadgerbrook** [comment]
@gestchild I'm doing some quick checking and have found that of 1,000 observations since 17:44 today, only 13 unique anonymousIds who viewed items have been included in the A/B test while 45 have not. Isn't the test supposed to grab all users who view items?

**Comment by gestchild** [comment]
@taceybadgerbrook can we chat about this tomorrow, I'm confused about why we're using a count of unique anonymousId.

Every user who visits an item page should have the itemWorkLink toggle cookie either set to true or false.  itemWorkLink will show in properties.toggles for anyone who has it set to true, it won't show for anyone who has it set to false. 

As noted before, it's not working quite as expected in that the split isn't happening 50/50.

**Comment by gestchild** [comment]
To clarify, everyone is in the a/b test. If they have properties.toggles:itemWorkLink then they are in the B condition if not they are in the A condition.

So we want to compare:

source:button_back_link / (page.name : "/item" and properties.toggles.keyword : "itemWorkLink")

with 

 source:viewer_back_link / (page.name : "/item" and NOT properties.toggles.keyword : "itemWorkLink")

**Comment by taceybadgerbrook** [comment]
I looked at my code again to try and furnish you with examples and found...it's a bug in my code. Properties.toggles is a list object and my code isn't searching for itemWorkLink properly. Not to worry, though. 100% of item views are being scooped up into the AB test.

**Comment by taceybadgerbrook** [comment]
From what I can see everyone has properties.toggles:itemWorkLink.

**Comment by taceybadgerbrook** [comment]
Here's what I can see for all the users who view an item:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/32418070/212305515-eb8ce77d-733d-4f2a-b138-2cd268beed4d.png">

**Comment by taceybadgerbrook** [comment]
So now I understand that everyone has properties.toggles:[itemWorkLink]=B's and properties.toggles:[]=A's. I'll have to ask Harrison how I can search for values a list object.

**Comment by taceybadgerbrook** [comment]
Ok, so taking 10,000 rows from Elasticsearch, I've counted 2,689 A's and 1,121 B's. I expected them to be roughly equal.

Then I wondered if the numbers are skewed because some users will continue to search and view while others find something and then leave. This was my original rationale for deduping by anonymousId. 

But I count the number of unique A's as 315 and B's as 58!

Maybe the toggle is favouring a certain path over others? Remember, there are a number of users who keep tabs open in their browser which fire each time they restart, so they may well start a session with an item view.

**Comment by taceybadgerbrook** [comment]
Latest run of code gives 2,604 A's, 1,377 B's. Deduping by anonId gives 284 A's and 135 B's.

**Comment by gestchild** [comment]
@taceybadgerbrook is that for data only since I deployed the fix for the 50/50 split. If so, I guess it's not worked. I'll have to think some more.

We should still be able to get results for the A/B test regardless though once the numbers are high enough for each condition to be statistically significant.

**Comment by taceybadgerbrook** [comment]
@gestchild yes, the data is 10,000 rows from today. It doesn't have to be exactly 50/50 but it's the fact that the A's are more than double the B's that concerns me. Even with really high numbers, this would still be an issue.

**Comment by gestchild** [comment]
> the fact that the A's are more than double the B's that concerns me. Even with really high numbers, this would still be an issue.

I don't understand, why does the ratio of As to Bs matter in determining which condition is more successful?

**Comment by taceybadgerbrook** [comment]
@gestchild As an example, say you had two boxes of lightbulbs and wanted to test if faults occur with a similar frequency when comparing boxes. And let's say in reality, 25% of lightbulbs from box A have faults and only 20% of lightbulbs from box B have faults. 

If we scoop out 100 lightbulbs from box A and 200 lightbulbs from box B, it's likely we'll find 25 faulty lightbulbs from box A and 40 faulty lightbulbs from box B. Based on this, we'd say box B was a box to avoid when in reality box B has fewer faulty lightbulbs than box A.

The 2 samples have to be close in size or you end up with unrepresentative numbers (and therefore percentages) of successes.

**Comment by gestchild** [comment]
But we _can_ compare the percentages and not the absolute numbers, as the sample sizes aren't equal. So in your example, we could correctly determine that box A is the one to avoid (25/100) = 25% faulty versus (40/200) = 20% faulty. The value of the denominator doesn't matter as long as it is large enough to be statistically significant.

**Comment by taceybadgerbrook** [comment]
@gestchild sorry - wait. My last comment was rubbish.

**Comment by taceybadgerbrook** [comment]
@gestchild Good news. 

The kind of test we need to apply is called a chi-squared test and compares categorical data. This test doesn't "care" if the category totals are not the same. [Here's an article if you're interested](https://www.theanalysisfactor.com/chi-square-test-of-independence-rule-of-thumb/). 

I got all back to front thinking about the other kind of test which is often used for AB tests: the t-test. This kind of test does ask for similarly-sized samples. Yes, the percentages come out the same but statistical tests are more than just comparing percentages. They measure the variation contained in random samples to check the probability that the results are a fluke or down to unusual circumstances. In our case, an example might be if we told lots of staff to go to an item view and look out for the new button and if they see it, click it to see if it works.

In the meantime, I'll be proceeding with testing...

**Comment by taceybadgerbrook** [comment]
An AB test can only test for relative success between two samples. So here, we are testing to see if more people click on catalogue link or back button. The null hypothesis is that there is no difference in behaviour between when people are presented with the catalogue link or the new back button.

Because so many researchers will already be familiar with the catalogue link, let's set minimum detectable effect (ie % change we want to see) to 5% or lower.

From previous research, the baseline % of item views that are followed by works page view is 67%. I have set the significance level to 5% and the power of the test to 80%.

Using [this tool](https://www.evanmiller.org/ab-testing/sample-size.html), the required samples must contain at least 3,114 observations.

**Comment by taceybadgerbrook** [comment]
Analysis shows there to be 349 successes out of a total of 4,929 unique anonymousIds in the A group. There were 172 successes out of a total of 2,403 unique anonymousIds in the B group.

Running a chi-squared test using [this tool](49 successes out of a total of 4,929 unique anonymousIds in the A group.) found no statistical significance between the behaviour of the two groups.

**Comment by taceybadgerbrook** [comment]
This concludes the A/B test element of this analysis but only really tested whether the link or the button were a more compelling call to action.

As a measure of success, clicking to go back to the works page after viewing an item might not actually indicate an improvement in tools offered to researchers. Reasons for wanting to go back to the works page might be to: 
- find something similar, so if we measure clicks on concepts
- request online, so if we measure clicks to log onto library account or request items or
- copy url, so if we measure clicks on Copy url button

**Comment by jennpb** [comment]
- [ ] Jenn + team to discuss next steps
- [ ] B toggle removed

**Comment by jennpb** [comment]
@taceybadgerbrook Is it possible to write this up as a separate summary document, using screenshots of the two versions so we know what design change we tested?

**Comment by taceybadgerbrook** [comment]
@jennpb Yes, can do that no problem. Do you want the document in Github?

**Comment by taceybadgerbrook** [comment]
Here are the 2 screenshots if you want to use these in your presentation today.

### New button: ###

![New button](https://user-images.githubusercontent.com/32418070/216313862-c5be5dbb-1939-40a4-b252-4fc5ec4de508.jpg)

### Old link: ###

![Old link](https://user-images.githubusercontent.com/32418070/216313869-2646b931-d502-42e7-ae94-6ab56f48e072.jpg)

**Comment by jennpb** [comment]
> @jennpb Yes, can do that no problem. Do you want the document in Github?

Can you please put the word or ppt in the A/B test subfolder in Sharepoint, and then add the sharepoint link to close off the ticket. https://wellcomecloud.sharepoint.com/:f:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/AB%20tests?csf=1&web=1&e=12b9wt

**Comment by taceybadgerbrook** [comment]
Here is the link to the PowerPoint slides summarising the test and results:
https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B89921374-9b48-4eed-890c-badeba5729da%7D&action=edit&wdPreviousSession=125da681-dc8f-302e-483f-50f4114fe781&PreviousSessionID=2d92854f-81fd-71f3-b298-0c903d8b87cb&cid=6d25206f-7ac2-4071-9b1a-22062b6d055a

**Comment by jennpb** [comment]
To sum up:
- Revert to version A
- Remove B toggle and code
- Revisit potential solutions for work/item page transition as part of UX review 
@gestchild @taceybadgerbrook @DominiqueMarshall @pollecuttn
