### ISSUE TITLE
In Plain Sight digital guides: summary of tagging and Hotjar work

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9038]
[In Plain Sight digital guide analysis ](https://github.com/wellcomecollection/wellcomecollection.org/issues/8252)identified areas where additional tagging and hotjar tracking could highlight ways to improve the guides. 

If we are able to improve the guides for the "January surge" in museum attendance, then we will be able to see whether our improvements really do improve the user experience.

**Comment by taceybadgerbrook** [comment]
# Tagging #

Create event for audio guides. Event category=IPS_Audio, Event action=play, Event label=stopId. We have an event category Audio but it is not set up to capture the stopId. 
Create event for captions and transcripts. Event category=IPS_text, Event action=read_full, Event label=stopId. 
Create event for BSL video. Event category=IPS_video, Event action=play, Event label=stopId.

**Comment by taceybadgerbrook** [comment]
# Hotjar #

Track scroll depth on:- 
[audio guides homepage](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/audio-without-descriptions[)
captions and transcripts homepage](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/captions-and-transcripts)
[BSL videos homepage](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/bsl)

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @gestchild @jennpb If we train Hotjar for a limited time only on the captions and transcripts page and prove that users don't scroll very far, then we might be able to make changes to the design of the page before the end of January. This would mean being able to test the new design out on the "January surge" in museum attendance. 

If the changes result in more clicks to "Read full transcript," the new design is a success. If the changes result in the same level of clicks, then we know it's not worth implementing something similar for the audio guides or BSL video pages.

**Comment by davidpmccormick** [comment]
> Create event for captions and transcripts. Event category=IPS_text, Event action=read_full, Event label=stopId.

I'm going to take out the references to In Plain Sight in the `category` so this is generic enough to track any ExhibitionCaptions 'read more' buttons, but you'd know which one you were dealing with because the `id` for the particular exhibition would be in the url associated with the event (e.g. `Y2omihEAAKLNfLar` for In Plain Sight). So something like:

```
category: 'ExhibitionCaptions read more button',
action: 'clicked',
label: stop.Id
```

**Comment by taceybadgerbrook** [comment]
On a separate note:

The placard at the beginning of the exhibition explains that there are audio and BSL formats available and to scan the QR code for instructions on how to use the digital guide. Scanning the QR code takes you to the [Captions and Transcripts homepage](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/captions-and-transcripts). I would expect to scan the code and be presented with a choice of audio or BSL. Instead, the code takes me to the captions and transcripts page which is neither audio nor BSL. There is a button to change "guide type" but this seems an unnecessary step.

**Comment by davidpmccormick** [comment]
I believe if it's the first time you scan that QR code, you should be taken to the page that lists the guide types. If you then choose a guide type, that will be saved and when you use QR codes e.g. later in the exhibition, you'll be taken to the same guide type. Will have to go over this to check that I have it right though.

**Comment by taceybadgerbrook** [comment]
Yes, this is what I experienced. 

Maybe I'm misinterpreting the placard. The icons at the top are for BSL and AD, so it looks like the guide is offering these 2 formats. The text refers to a digital guide that _can_ be accessed in AD or BSL. I read this to mean that once I scan the QR code, I should expect instructions for accessing the AD or BSL guides.

It's a bit of a surprise to scan the code and be presented with the Captions and transcripts guide instead and have to click the button, "Change guide type." At the very least, they should go to either the audio or BSL guides page. 

We could change the wording of the card in future exhibitions or change the guide type that the QR code points to.

**Comment by jennpb** [comment]
That part of the journey needs a rethink outside the scope of this tracking ticket. I have noted it down for future enhancements.

**Comment by davidpmccormick** [comment]
I think the dev work has been done for this now – going to move it into 'Ready for review'.

**Comment by taceybadgerbrook** [comment]
During the period 20/10/22 - 15/1/23, the [In Plain Sight Digital Guides page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau) received 3,768 visits. The [Audio page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/audio-without-descriptions) received 2,285, the [BSL video page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/bsl) 171 and [Captions and transcripts page](https://wellcomecollection.org/guides/exhibitions/YzwsAREAAHylrxau/captions-and-transcripts) 617.

**Comment by taceybadgerbrook** [comment]
Audio guide usage by stopId is shown below. This graph excludes audio guides triggered after browsing the page and clicking on links. The average play time was 3 minutes, 18 seconds. Considering the longest track is 5 minutes, this shows high engagement.
![audio guide usage](https://user-images.githubusercontent.com/32418070/213718826-07ab0e49-e5b3-4d9b-a754-d671e516a3c8.jpg)

**Comment by taceybadgerbrook** [comment]
Hotjar tracking was set up for the Audio guide page on 9 January. This shows 50% of users leaving having scrolled down to just over halfway. The Captions and transcripts page is much longer. If was assume users exhibition the same behaviour when using that page, this would mean 50% only scroll down to the first transcript.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/32418070/213721656-8ac1b423-dd88-409d-bb7f-c08bc261ecd2.png">

**Comment by taceybadgerbrook** [comment]
Audio guide control usage appears to show few users using the mute and unmute buttons.
![Audio guide control usage](https://user-images.githubusercontent.com/32418070/213721828-cdc86ba8-1938-4283-9ae6-99615b781b5e.jpg)
![Audio guide control usage %s](https://user-images.githubusercontent.com/32418070/213721853-f83eb0ca-80d2-4c3f-8c9e-f4815faa1fef.jpg)

**Comment by taceybadgerbrook** [comment]
Audio guide speed control usage shows the most popular control was 1.5X.
![Audio guide speed control usage](https://user-images.githubusercontent.com/32418070/213721998-ee84423b-564d-4fe2-9499-177f7b48a8bd.jpg)
![Audio guide speed control usage %s](https://user-images.githubusercontent.com/32418070/213722016-7388f298-c37f-4f7f-a59d-3a7dcd88d828.jpg)

**Comment by taceybadgerbrook** [comment]
Analysis of BSL guide usage is limited due to the fact that the majority of users scrolled to the next video instead of scanning the QR code. Without the stopId which is contained in the QR code url, it is impossible to identify the stop for which the video was viewed.

We can tell that QR code users spent an average of 2 minutes and 45 seconds viewing the videos. This shows high engagement.

**Comment by taceybadgerbrook** [comment]
The Captions and transcripts page was tagged on 9 January. The graph below shows high engagement with users continuing to click on the Read full transcript links even to the end of the exhibition.

QR code activations show the majority of users activate the code at the beginning of the exhibition and scroll to the next transcript.
![Captions and transcripts usage](https://user-images.githubusercontent.com/32418070/213723363-09371c28-08c3-4165-b315-bddbe9a1430d.jpg)
![Captions activations by QR code](https://user-images.githubusercontent.com/32418070/213723394-02c425aa-0a32-4724-b1bc-a5ecdc6a5ed0.jpg)

**Comment by taceybadgerbrook** [comment]
In conclusion, the QR codes have enhanced the visitor experience for In Plain Sight and users have been sufficiently engaged to keep using them throughout the exhibition. 

Exhibition design may have been a factor in the accessibility of certain QR codes but overall it seems that users are happy to scroll through the guide pages to find later stops. To assist scrolling, longer pages such as Captions and transcripts would benefit from being compressed, possibly using show/hide arrows. 

As a general comment, the placard at the entrance to the exhibition and on the digital guides homepage could have been more explicit that the Audio guides and Captions and transcripts are provided as accessibility features and that they replicate the content on the exhibition cards.

**Comment by taceybadgerbrook** [comment]
@jennpb if it's possible to compress the Captions and transcripts page using show/hide arrows before the exhibition closes on 12 February, I'm happy to revisit the analysis to see if this increases engagement.

**Comment by gestchild** [comment]
> Analysis of BSL guide usage is limited due to the fact that the majority of users scrolled to the next video instead of scanning the QR code. Without the stopId which is contained in the QR code url, it is impossible to identify the stop for which the video was viewed.

Is this something that the video events, that are part of enhanced events in GA4, can help with. One of the property values that gets sent with the event is video_title. I think we have to generate a custom report to get to that data.

Having said that, I've just had a look in GA4 and it looks like the video events stopped being tracked at the beginning of December, not sure why that is.

**Comment by taceybadgerbrook** [comment]
@gestchild GA4 will track videos if they are on YouTube. The BSL videos aren't public so we can't use GA4 for this purpose.

**Comment by gestchild** [comment]
The videos are hosted on YouTube, e.g. https://www.youtube.com/watch?v=aQnpAnvPt2s so this is something I think we should be able to get working. Although, as I said above, it seems something happened at the beginning of December which stopped the events being captured in GA4. Likely it was #8933

**Comment by taceybadgerbrook** [comment]
They are hosted there but YouTube Analytics says they are unlisted, ie. they are not visible to the public, so they are getting views but not very many
<img width="927" alt="image" src="https://user-images.githubusercontent.com/32418070/214051324-99f86d4c-8dfb-4687-b24c-1bf8b118fd7f.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/32418070/214051702-ddbd0511-6e97-4bde-97da-d4354f641f1c.png">

**Comment by gestchild** [comment]
I don't mean the YouTube analytics. But we get video event tracking for embedded YouTube videos, as part of the [enhanced event measurements in GA4](https://support.google.com/analytics/answer/9216061?hl=en&ref_topic=9756175)

Below is a screenshot of these showing up in our GA4 account.

<img width="913" alt="Screenshot 2023-01-23 at 13 57 22" src="https://user-images.githubusercontent.com/6051896/214057710-77a4d8d4-4f28-4634-a593-01360afa8442.png">

Each of these events have a video_title property sent with them, but would need a custom report set up to get to that data.

However, I think [some work we did to improve page performance](https://github.com/wellcomecollection/wellcomecollection.org/pull/8933) has stopped these events from being recorded since the beginning of December. We could look at trying to get this to work again and/or setting up some custom events once tag manager is installed, which may be a better option and is outlined in the link I mentioned above:

> it may be better to [turn off Video Engagement tracking features in Enhanced Measurement and implement custom video tracking events as suggested in this article.](https://www.analyticsmania.com/post/track-videos-with-google-analytics-4-and-google-tag-manager/#:~:text=When%20you%20create%20a%20new,track%20embedded%20Youtube%20video%20players.)

**Comment by taceybadgerbrook** [comment]
@gestchild I think I've hit upon why I can't see all of the YouTube data in GA4.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/32418070/214059043-6e6f075c-78f7-4fd8-a19a-bd012e7301e2.png">

**Comment by taceybadgerbrook** [comment]
I can see video title and views but I can't get at video start, video progress, etc.

**Comment by gestchild** [comment]
They are definitely there, see above screenshot - maybe you need to increase the number of rows you can view in the events  overview table, it defaults to 10.

The following link has useful information about viewing the events and associated properties.

> a [custom report set up to get to that data](https://www.analyticsmania.com/post/where-to-find-video-engagement-data-in-google-analytics-4/).

**Comment by taceybadgerbrook** [comment]
Ok, I was looking in Explore Reports and browsing the dimensions.

I would definitely be up for configuring GA4 à Julius/Analytics Mania but I'll need GTM for this.

**Comment by taceybadgerbrook** [comment]
@gestchild I think we need to put GA4/GTM conversations in #8524. I'm going to close this ticket and open a new one #9145  to cover additional analysis focussing on navigation and device.
