### ISSUE TITLE
Search: Rethink default states

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9041]
I raised this [in Slack](https://wellcome.slack.com/archives/C02ANCYL90E/p1673020552553699):

> OK so question for search: https://wellcomecollection.org/works?workType=k&availabilities=closed-stores is a valid query currently on the Works page: we display all results by default, therefore it just filters them.
Now on Search pages, we require a query to be entered in order to display any results. Therefore, someone who would've bookmarked the page above (who knows) would get redirected to https://wellcomecollection.org/search/works?workType=k&availabilities=closed-stores and see no results at all (because no query string).
Should we change that behaviour?

See conversation for more details. We landed on getting the default results back for now (and re-discuss with @jtweed on his return) on `/search/works` and `/search/images`.

`/search/stories` having not existed before, we could have it behave differently, but if we wanted to align the behaviours, we do get default results back without a query. It's not clear at this stage what they are - latest updated ones perhaps? We could cheat that out if we wanted to have a specific default results list.

`/search` could have nothing but at that point it feels like it should! the question would be what.

**Comment by jtweed** [comment]
Agreed, we need to be able to return results without a query. If that has to be the default state given the tabs are separate pages (as they should be), then I'm ok with that.
