### ISSUE TITLE
Works and items: UX architecture review

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9045]
# What is it and who's it for?
Deconstruct work and item page into its constituent parts, taking stock of what we have and what will be added.

This review should cover:
- What are all of the parts of works pages and item pages
- What they're called
- What's their purpose
- Whether we currently track it in GA; whether we need to in future, either short-term or permanently
- Is this component in the design system, is it documented?

## Why now

- There's a steep learning curve for any new starters
- Enabling future additions of context, metadata and born digital functionality.
- Transition to event-based GA4/GTM requires a thoughtful approach to component and page-based event tracking
- Shared understanding of purpose of works/items and the components that comprise them

## Goals of this work
- Rationalise the information structure, hierarchy and utility of the works and digitised item pages
- Understand what additional metadata we can expect from the API
- Enable anticipated new functionalities and content.

## Outcome 
This work enables users have all of the information available to them to help them decide whether a work is useful for their purposes, understand its context within the collections and to take action to use it.

# Related issues

**Item preview**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5179 

**Licence and credit information**
https://github.com/wellcomecollection/wellcomecollection.org/issues/8907 - removed from download modal, but side panel information is less well formatted

https://github.com/wellcomecollection/wellcomecollection.org/issues/6311 - adding human readable licence info

**Metadata**
IIIF manifest link https://github.com/wellcomecollection/wellcomecollection.org/issues/5273

Archive description body text doesn’t use semantic markup https://github.com/wellcomecollection/wellcomecollection.org/issues/6558 

**Multi-part information**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5948

**Pagination** 
Editable page number https://github.com/wellcomecollection/wellcomecollection.org/issues/6284

**Physical items list**
Long lists of volumes take a while to load https://github.com/wellcomecollection/wellcomecollection.org/issues/8539 

**Segmented controls**
Labels or no labels with icons https://github.com/wellcomecollection/wellcomecollection.org/issues/6445 

**Subject classifications**
Differentiating different concept systems https://github.com/wellcomecollection/wellcomecollection.org/issues/5394 
 
**Tree navigation**
https://github.com/wellcomecollection/wellcomecollection.org/issues/7895

**Comment by DominiqueMarshall** [comment]
Link to the component review spreadsheet: [UX architecture review](https://docs.google.com/spreadsheets/d/1E3Piyq5bHi_2BTSxjq9LFwE2p70cIj6OvtOBCwvBH4c/edit?usp=sharing)


### Recommendations for where the most improvements could be made:

- Confirm what components we want to/need to be tracking when moving to GA4

- **Redesign the “Selected images from this work” slice.**
Having a button that takes people back to a search feels redundant when those images could be shown directly on the works page in the context of the work itself.

- **Microcopy review**
We need to review all of the copy within the Works pages and fix inconsistencies with language, especially with the licencing and credit information, as the current labels and the information shown are misleading. (See comments from Alexandra about this [on Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1674758770207249))


- **Works Page redesign**
With an aim to improve the presentation of the information on works pages, we need to spend some time interrogating where that information is being pulled in from, and explore possibilities on the front end that will improve the visual hierarchy and accessibility. I.e. _Archive description body text doesn’t use semantic markup_ https://github.com/wellcomecollection/wellcomecollection.org/issues/6558. We should also review the last round of design iterations and confirm what we can implement to improve the page structure.


- **Archive Pages / Tree Navigation**
Through user testing and colleague feedback, there’s an underlying issue with the way the tree navigation functions, as people struggle to figure out where the requestable item is, and get confused with how the arrow controls work.


### Duplicate information (between works page and item viewer)
- Item name
- Main contributor
- Date
- Licence and credit
- Download link
- Page/image counter
- On Archives material: Licence, access conditions, can I use this - inconsistencies in language and meaning with how library inquiries describe these.

**Comment by DominiqueMarshall** [comment]
Next steps: review What's On, digital guides, stories (priority) for component usage (related to #9201 )

**Comment by DominiqueMarshall** [comment]
I've put the recommendations above into a powerpoint for future reference when it comes to prioritising those pieces of work individually: https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/Shared%20Documents/Design/UX%20Architecture%20Review%20Recommendations.pptx?d=wbb3ebef8e39f49feabe5157132ff27a8&csf=1&web=1&e=VbI1DF
