### ISSUE TITLE
Search: Design Review

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9049]
As discussed on a call just now, we'd like a design review of the new search pages, how they mesh together, how the new components looks, colour choices, etc. Dom will review them and let us know of any preferred changes, which we can then discuss here if need be.

**Comment by rcantin-w** [comment]
As discussed, the overview page is in review and so isn't yet available on staging/main. Happy to send screenshots or do a screenshare if you did want to do this before it was merged in @DominiqueMarshall

**Comment by DominiqueMarshall** [comment]
@rcantin-w I don't mind waiting until it's on staging/been merged

**Comment by rcantin-w** [comment]
@DominiqueMarshall it was approved quickly 😄 so it's now available.

**Comment by DominiqueMarshall** [comment]
(Comments in progress)

- Stories headings are missing an underline hover state

Images tab - There’s not enough spacing between the bottom of the image filter buttons and the black background. Increase the margin to 32px to match the design: [https://www.sketch.com/s/1cc6a024-668b-4d76-9617-115910d3a797/a/qemAoEy#Version](https://www.sketch.com/s/1cc6a024-668b-4d76-9617-115910d3a797/a/qemAoEy#Version) 


- The ‘Reset filters’ selector needs reworking as it looks like another filter.

- Font sizing between the filters, pagination and sort by are different and should be consistent (14px)

- Border width should be 1px across all filter buttons. It's currently 1px on the sort filter and 2px on the others.

- Image modals aren’t showing any titles 

- The arrows on the Overview buttons (all stories etc) are massive compared to the mockups. Decrease the sizing to 18px

- Consider increasing the padding between the pagination at the bottom of the page and the footer.

**Comment by rcantin-w** [comment]
- Stories headings are missing an underline hover state ✅ 

- Images tab - There’s not enough spacing between the bottom of the image filter buttons and the black background. Increase the margin to 32px to match the design: https://www.sketch.com/s/1cc6a024-668b-4d76-9617-115910d3a797/a/qemAoEy#Version
Done locally, I'll show you when we meet!

- The ‘Reset filters’ selector needs reworking as it looks like another filter.
We can do some live coding together if it helps?

- Font sizing between the filters, pagination and sort by are different and should be consistent (14px)
- Border width should be 1px across all filter buttons. It's currently 1px on the sort filter and 2px on the others.

The two above I'd like to review with you because of the way they are coded. They are currently "buttons" and the padding doesn't match the "small" button. I can explain better when we share screen and discuss! I think a new component might be the way to go, or a different way of styling all the variables we're playing with at the moment.

- Image modals aren’t showing any titles ✅ 

- The arrows on the Overview buttons (all stories etc) are massive compared to the mockups. Decrease the sizing to 18px
This would be a change on all icons in buttons. Do we have other examples where we might think they are too big? otherwise maybe the icon svg itself needs a rework?

- Consider increasing the padding between the pagination at the bottom of the page and the footer.
Let's discuss!

**Comment by rcantin-w** [comment]
![Image](https://user-images.githubusercontent.com/110461050/213165582-9c348703-5b90-4410-8b0f-1e8ffc441c4f.png)

Leaving this here as discussed, need to decide if we want to try something new or stick with this until we've got a set "button strategy".

**Comment by rcantin-w** [comment]
As explained [here](https://wellcome.slack.com/archives/C3TQSF63C/p1674217007834609), we could be ready for round 2! I'll move it out of In progress and back to Next as this is more of a "parent" ticket. Let me know if there's anything!

**Comment by rcantin-w** [comment]
We just had a chat and we're happy to close this! thanks so much @DominiqueMarshall ⭐
