### ISSUE TITLE
Search filters can be repeated indefinitely.

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/wellcomecollection.org#9109]
1. [Search for "Freud"](https://wellcomecollection.org/works?query=freud)
2. Expand the "More filters"
   - There are two entries for "Freud, Sigmund, 1856-1939"
![Screenshot 2023-01-18 at 15 41 49](https://user-images.githubusercontent.com/64621/213217698-f8cc2e8d-b4fb-427e-825b-2918631f52d5.png)
3. Select one, the contributor filter list now contains fewer options, but two of them are "Freud, Sigmund, 1856-1939"
![Screenshot 2023-01-18 at 15 43 03](https://user-images.githubusercontent.com/64621/213218185-1277ed20-f9db-4f49-b2ea-ad1663ef92a1.png)
4. You can carry on choosing to filter on content by the famous psychoanalyst [as many times as you fancy](https://wellcomecollection.org/works?query=freud&subjects.label=%22Freud%2C+Sigmund%2C+1856-1939%22&contributors.agent.label=%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22%2C%22Freud%2C+Sigmund%2C+1856-1939%22)
![Screenshot 2023-01-18 at 15 46 28](https://user-images.githubusercontent.com/64621/213219683-2234c5c2-2127-420c-9ecc-e309ed07e1eb.png)

**Comment by paul-butcher** [comment]
I believe this happens when the term appears twice in the initial filter list (is this an id/label problem?)

Searching for banana and filtering on Tesco behaves as one would expect.

**Comment by rcantin-w** [comment]
As we were testing the new search, we believe a bug that we found was related to this, so it'd be good to check if the fix for this is the same:

> go to https://wellcomecollection.org/search/works?query=fish+custard&sortOrder=asc&sort=production.dates, look at contributor filters “Woolley, Hannah, active 1670 (5)”. Select the filter. You get 6 results!

**Comment by rcantin-w** [comment]
I feel like this has been fixed, @paul-butcher ?
