### ISSUE TITLE
Contributor and subject filter is not preserved when adding format filter

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/wellcomecollection.org#9116]
1. Visit a works list, filtered on contributors or subjects
* https://wellcomecollection.org/works?contributors.agent.label=%22Bishop%2C+Mary%2C+active+approximately+1955-1975.%22
* https://wellcomecollection.org/works?subjects.label=%22Bishop%2C+Mary%2C+active+approximately+1955-1975.%22
2. Use the Formats dropdown to choose "Pictures" (i.e. filtered on both Mary Bishop and Filters)
* <img width="1674" alt="Screenshot 2023-01-19 at 11 47 59" src="https://user-images.githubusercontent.com/64621/213435112-63405405-0c6f-4e4d-a5fd-842a6bbd6f3c.png">
3. The page briefly shows the expected result count, then becomes a view of all the pictures, not filtered by Mary Bishop
<img width="1674" alt="Screenshot 2023-01-19 at 11 48 25" src="https://user-images.githubusercontent.com/64621/213435215-b09ad0cf-a398-4a8f-9637-1f24d24caba4.png">
<img width="1674" alt="Screenshot 2023-01-19 at 11 48 30" src="https://user-images.githubusercontent.com/64621/213435236-f5f955e0-dc9d-449f-a479-7e8abb24e3e3.png">

**Comment by rcantin-w** [comment]
Not great, I was able to replicate this in the new search (in the branch with default results) as well, so if we could ensure it's fixed in both.

Hard to test outside of that branch as if you enter a query string, that behaviour does not happen and everything is kept in.

**Comment by rcantin-w** [comment]
I investigated to find out when it happened and it seems to be from [when we changed up our filters](https://github.com/wellcomecollection/wellcomecollection.org/commit/458be734022b4852493be69d26fa0727fdc76c6b).

@AMBacelar I'll keep investigating, but if something rings an immediate bell, let me know! I'm thinking maybe a rogue `useEffect` refreshing something too early?
