### ISSUE TITLE
Fix a typo on podcast subscription button

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9132]
**What**

The button for `Libsyn` has a typo. The second letter is capitalised: `LIbsyn`

<img width="474" alt="Screenshot 2023-01-20 at 15 39 01" src="https://user-images.githubusercontent.com/1446139/213741670-63443be3-e33b-4964-aa5b-391a31b6ca72.png">

**Where**
https://wellcomecollection.org/articles/YsQZbhEAACEAWVE8

This seems to be affecting all podcasts in the 'Root of the Matter' podcast series https://wellcomecollection.org/series/YsQLZxEAACAAWQ4J

**Action**
Change `LIbsyn` to `Libsyn`

**Comment by alexwlchan** [comment]
These labels come from Prismic, not the front-end codebase.

**Comment by alexwlchan** [comment]
(Apparently I spotted this five months ago and never hit publish!)

**Comment by alexwlchan** [comment]
Fixed, along with the three other instances of faulty capitalisation in that series.

I've checked; there aren't any other instances of this mistake in other podcasts.

**Comment by dannybirchall** [comment]
Apologies for sloppy editing! Thank for fixing @alexwlchan 

In an ideal world, the subscribe list would be a separate content type per-podcast, that you could attach as a slice, per-episode.
