### ISSUE TITLE
Former frequency and designation field labels appearing even without a field value

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9134]
**What**
The works pages are showing 'Former frequency' and 'Designation' fields when there is no content to display.

We shouldn't show labels in the absence of a field value. 

**Where**
![Screenshot 2023-01-20 at 17 33 48](https://user-images.githubusercontent.com/1446139/213765988-f50a7b34-f299-4fc5-9e31-2f1c5488478d.png)
https://wellcomecollection.org/works/htgtvgts

**Comment by alexwlchan** [comment]
This is a known issue, tracked in https://github.com/wellcomecollection/platform/issues/5600 – it’s a bug in the new fields I’ve added.

**Comment by jennpb** [comment]
Duplicate issue
