### ISSUE TITLE
Stories with no promo images

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9184]
Working on this bug https://github.com/wellcomecollection/wellcomecollection.org/pull/9183, I found out some stories didn't have a promo image, or had one but had no `rich` or `simple` `Crops` information and therefore didn't get rendered out (or they wouldn't be the same size as their sibling results).

Would we like to have a default image? Would we want to allow for uncropped images? Are we happy as is?

See PR for screenshot and example pages.

**Comment by alexwlchan** [comment]
> Would we like to have a default image? Would we want to allow for uncropped images? Are we happy as is?

This feels like a question for the Editorial team, maybe? Do we know how many stories it affects?

We'll need to tackle this more fully if/when we allow searching all the site content (e.g. press releases), but it feels like we could take several approaches for Stories.

**Comment by rcantin-w** [comment]
>  Do we know how many stories it affects? 

Seems quite rare as I'd never come across it before today and I've done a _lot_ of searches. The examples we found today were from 2017, too.  But it does happen, and [as seen here](https://wellcomecollection.org/series/WcpOjygAAJsLEXTc), it didn't seem to be much of an issue in the past. So I'm thinking a minimal fix (nothing fancy/time consuming) would be best for what this is worth. 

You're also right that other content types might have different needs, which we'll have to consider.

**Comment by rcantin-w** [comment]
An update; there were four results without an image, which are all ones that could be archived/shouldn't be a story ([see convo here](https://wellcome.slack.com/archives/C3N7J05TK/p1675162512486869)). It is required, but[ from what I've read](https://prismic.io/blog/required-fields), no Prismic field can be set to "required" and therefore it could always happen. Plus, other content types (like your example of press releases) don't necessarily have an image. I think this ticket could serve as basis for a convo with design to see if we want a fallback image or are happy with the current behaviour.

**Comment by jennpb** [comment]
Happy with current behaviour.
