### ISSUE TITLE
Create tests for the new Search Pages

### ISSUE THREAD

**Issue by AMBacelar** [wellcomecollection/wellcomecollection.org#9193]
things to consider with regards to the tests
- test that the query (but not the filters) are maintained when switching through tabs
- clicking on "All Stories/All Images/Catalogue" on the Overview page takes us to the correct page on click
- check that the no results message shows if needed as well? (with/without a reference to filters)
- ensure that the search bar in collections sends us to the works tab _**(as of writing, this isn't functional)**_

**Comment by rcantin-w** [comment]
We also had discussed using this to review the `<PlainList role="list">` that is used as a selector in one of the tests since `PlainList` in this case is a `ul` already, so maybe using this to review the selectors we use in search in general?
