### ISSUE TITLE
Investigate GA4 training options

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9200]
# What is it and who's it for?
Users of GA4

Identify training options e.g. online training, to do the technical work and get the understanding of where to find the info when we’ve switched to GA4 for reporting.

**Comment by taceybadgerbrook** [comment]
## Online training ##

- YouTube channel: [https://www.youtube.com/c/AnalyticsMania](https://www.youtube.com/c/AnalyticsMania)
- Google's documentation: [https://support.google.com/analytics/answer/10089681?hl=en](https://support.google.com/analytics/answer/10089681?hl=en)
- Neil Patel: [https://neilpatel.com/blog/google-analytics-4/](https://neilpatel.com/blog/google-analytics-4/)

## Slide decks ##

- [Guide to GA4](https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA4/Guide%20to%20GA4.docx?d=wf83c030a9169447985d39c3dcd548d3b&csf=1&web=1&e=Ah19jZ)
- [Introduction to Google Analytics 4](https://wellcomecloud.sharepoint.com/:b:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA4/[introduction-to-google-analytics-4-3-11-22.pdf](https://wellcomecloud.sharepoint.com/:b:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA4/introduction-to-google-analytics-4-3-11-22.pdf?csf=1&web=1&e=hmZCId)?csf=1&web=1&e=hmZCId)

## Training courses ##

- Jellyfish Training (£499): [https://www.jellyfish.com/en-gb/training/courses/google-analytics-4-reporting](https://www.jellyfish.com/en-gb/training/courses/google-analytics-4-reporting)

**Comment by pollecuttn** [comment]
From Tacey:

> Elizabeth Atkin has organised a digital marketing GA4 training session with their consultant digital marketeers Ethix.

https://wellcome.slack.com/archives/C04KB3PFGCV/p1675852744987699
