### ISSUE TITLE
Comms plan re: GA4 transition

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9203]
# What

Make a plan to communicate the migration to everyone who needs to know.

# Why
- No surprises, to them or to us
- Help transition colleagues who are not superusers into the new property

# Done when
- [x] Stakeholder mapping carried out
- [x] Document all of the stakeholders and what they need to know, and when
- [x] We've shared information about training (if relevant)
~~- [x] Identify which users need to be added to GA4 property, and their access levels; users added at appropriate access level with @taceybadgerbrook~~
~~- [x] Kanuka training brief @jennpb~~

# Other info
Jenn created a spreadsheet with the account holders and permissions as of 12 Feb. It's in the Digital Experience Sharepoint folder. Not sharing here as it contains email addresses.

Part of epic #9101

**Comment by jennpb** [comment]
Work in progress https://docs.google.com/document/d/1EvQWXnPu5T24hVuikMSZVDS4AGuV-MSp4Z2G8niLWdY/edit?usp=sharing

What I've done so far:
- Tidying up our account access: Contacted people with existing GA access to determine whether they still need it (awaiting some responses); Deleted users who no longer require access; updated the access spreadsheet 
- Had a chat with Danny B about his team's training needs

**Comment by taceybadgerbrook** [comment]
@jennpb there are the following people from ethix who I'd like to give access. Are we going to issue them with a Wellcome email address?

bhavik@ethixdigital.com
jonatas@ethixdigital.com
kate@ethixdigital.com
martina@ethixdigital.com

**Comment by taceybadgerbrook** [comment]
@jennpb also, wellcomecollection183@gmail.com appears to have had access to GA. Is this the Visitor Insights team?

**Comment by jennpb** [comment]
Re: Ethix and other 3rd party contractors, they should use their business address.

I've emailed wellcomecollection183 but haven't had a response yet. I'll check with Visitor Experience. If I don't get a response I suggest we delete. Then if access is needed someone will have to let us know.

**Comment by jennpb** [comment]
14/3 Update:
- Jenn still to contact Diana from Commercial/Venue Hire
