### ISSUE TITLE
Make me an alumni 😿

### ISSUE THREAD

**Issue by derivadow** [wellcomecollection/wellcomecollection.org#9227]
**What**

It is almost time to update /humans.txt once more and move Tom Scott's name to the list of wellcomecollection.org alumni.

---

Maybe our paths will cross
when this universe folds in and makes another.
Maybe, at the point

when all that is, and all that’s ever been,
collapses into everything else and is remade,
our paths will cross, however briefly, and

our terminus become a junction.
It may be a long shot. I will take it
and hope and trust our paths will cross again.

-- Oliver Tearle 2022

**Where**
https://wellcomecollection.org/humans.txt

**Comment by jennpb** [comment]
https://github.com/wellcomecollection/wellcomecollection.org/pull/9229
