### ISSUE TITLE
Add event in GTM for global search click

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9238]
Whilst working on #8736 and discussing it with @harrisonpim and @taceybadgerbrook, we've landed on adding an event when:

- User clicks the magnifying glass (search icon) in the header (which opens the search box)
- User clicks the X icon that replaces the search icon when the search box is active. Worth noting this might need to be two events as clicking on the overlay also closes the search box.

**Comment by jennpb** [comment]
Do we still need this? I'm not sure what value we get from tracking this component. Any memory of what we were trying to learn about usage?

**Comment by jennpb** [comment]
@harrisonpim @rcantin-w @taceybadgerbrook Is this still needed?

**Comment by rcantin-w** [comment]
@harrisonpim I think we wanted to know if people were using the global search bar over the works search bar? And if they were closing it after seeing that the placeholder was specifying it wasn't for functional searching?

**Comment by jennpb** [comment]
After discussion with @jtweed we agreed this can be closed with no further action.
