### ISSUE TITLE
Don't track codebase internals as part of the analytics

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#9240]
When we send events to Segment, we send several properties about the page:

https://github.com/wellcomecollection/wellcomecollection.org/blob/e6a8ad06b732868e5e1ffc2ba46b00be1d080485/common/services/conversion/track.ts#L93-L104

The `Router.pathname` value tells you the [path for the current route file](https://nextjs.org/docs/api-reference/next/router#router-object), and our recent routing refactor means this value has changed in the analytics, e.g. we moved `/pages/items.tsx` to `/pages/works/[workId]/items.tsx` – the external path stayed the same, but this value changed in analytics.

This feels like an odd coupling – we shouldn't be using implicit properties of our code structure to Segment. We should be using values that we change more intentionally, e.g. the external pathname or hard-coded strings.

**Comment by taceybadgerbrook** [comment]
@alexwlchan Thanks. This looks like a good start.

**Comment by alexwlchan** [comment]
I've had a chat with Tacey about this, we're going to do two things:

* Stop sending the `pathname` value to analytics, because she doesn't need it, and it's liable to cause confusion by implying the presence of stability where none exists
* Add some comments to the `name` values which she does rely on to explain where it's used outside the codebase context
