### ISSUE TITLE
Source:archive_tree not updating for archive tree works pages

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9257]
**What**
When a user clicks on a link in the archive tree, they view a works page. Elasticsearch is supposed to differentiate between archive tree works pages and regular library catalogue works pages. Should be source:archive_tree but is showing source:unknown.

**Where**
metrics-conversion-prod

<img width="666" alt="image" src="https://user-images.githubusercontent.com/32418070/218476007-dfb89915-1030-4a07-bc39-b696542b9426.png">

**Comment by alexwlchan** [comment]
This is another unintended consequence of the routing refactor; fix available.

**Comment by taceybadgerbrook** [comment]
@alexwlchan I'd like to learn more about the refactoring that is affecting metrics-conversion-prod. Could we have a chat sometime?
