### ISSUE TITLE
Document our GA setup in Gitbook

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9266]
# What is it and who's it for?

- Gitbook documentation to outline how we've set up GA4
- For Digital Engagement and anyone else we work with internally

# What's included

- Property-level information (inc GTM and Google Ads linkages)
- How to get access + what access permissions we allow
- A link to, or inclusion of, a glossary/list of all the events we use
- Any information for marketing colleagues on getting access for 3rd party partners
- Point to any vetted training material (see #9200 )

# Done when

- First draft document reviewed by team
- Document published in Gitbook

## Documentation

[GA4 and GTM documentation](https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/GA4/GA4%20and%20GTM%20configuration.docx?d=we3d0380005664a0987cfc48b59bb72d5&csf=1&web=1&e=Didv4T) (Tacey's doc on Sharepoint)

**Comment by pollecuttn** [comment]
GitBook link: https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/

**Comment by jennpb** [comment]
https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/using-google-analytics-4-ga4

**Comment by jennpb** [comment]
It would be helpful to get a list of Segment events to include on this page: https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/google-analytics/analytics-event-tracking

@gestchild probably knows most about how to get this most efficiently

**Comment by alexwlchan** [comment]
> It would be helpful to get a list of Segment events to include on this page

So almost my coincidence, I was looking at something similar to this in https://github.com/wellcomecollection/wellcomecollection.org/pull/9691

It doesn't give you the documentation you need, but it does take a step in that direction.
