### ISSUE TITLE
Final sort and filtering changes for global search release

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#9285]
- Reorder stories sort to put “Oldest to newest” above “Newest to oldest” but leave “Newest to oldest” as the default
- Remove “Z-A” from stories sort and change “A-Z” to “Title”
- Leave disabled filters in place, but change the design to light grey with arrow icon and remove hover state

**Comment by rcantin-w** [comment]
> Remove “Z-A” from stories sort and change “A-Z” to “Title”

Do you mean only having A-Z as an option?
Also the no Javascript sort always has "ascending/descending" so it might still be available on there.

**Comment by jtweed** [comment]
As just discussed, let's remove the A-Z filter completely for now as it doesn't seem to work reliably as implemented in Prismic. We can revisit once the data is in Elasticsearch if we'd had people ask for it.

**Comment by rcantin-w** [comment]
![Image](https://user-images.githubusercontent.com/110461050/219093540-65a041de-9005-4c44-bc6d-5bef5df6bf67.png)

For reference
