### ISSUE TITLE
Create developer view in GA4 [Default] Collection property

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9339]
We want developers to be able to use GA4 to debug features.

If we exclude all internal users by 215's IP addresses, this means GA4 won't collect any data from activity triggered by someone in 215 including developers trying to debug tracking.

**Comment by taceybadgerbrook** [comment]
Here is an article on this
https://www.vakulski-group.com/blog/post/why-should-you-use-a-developer-traffic-filter-in-ga4-google-analytics-4/

**Comment by taceybadgerbrook** [comment]
@gestchild I've just created a GTM tag called, "test" that fires on all pages and clicked Preview and as you would imagine being in the office, I was asked to connect to GA Staging. Before I did this, I set GA debug to ON.

I can see my initial connection and then navigation to Stories in GA4 Staging Admin/DebugView:

![image](https://user-images.githubusercontent.com/32418070/220613967-bd8481c1-8962-4dd4-ba2a-419f92ec30d0.png)

**Comment by taceybadgerbrook** [comment]
@gestchild I think the GA4 Staging property gives you everything you need to debug when you are in the office and creating a Developer property isn't going to add anything. What do you think?

**Comment by gestchild** [comment]
I don't think we need a new property, but I'm not up to speed with the GA debug stuff yet - next on my reading list

**Comment by pollecuttn** [comment]
To be tested by @gestchild next time on premises

**Comment by taceybadgerbrook** [comment]
@gestchild @davidpmccormick Have you used this property at all? Any problems?

**Comment by taceybadgerbrook** [comment]
@gestchild @davidpmccormick I guess if nothing else, siphoning off testing to this property means I won't be counting cachebusting activity. I'm going to close this ticket now.
