### ISSUE TITLE
Tzitzit source link incorrect when arriving from an image search

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9345]
**What**

If I arrive at an image by using the 'image' search field, my Tzitzit has an 'images' suffix. If I arrive at the same image through the 'Library catalogue' search, my Tzitzit ends up with an 'items' suffix.

e.g.

https://wellcomecollection.org/works/pu2psz76/images link doesn't work
https://wellcomecollection.org/works/pu2psz76/items link works
 

**Where**

See https://wellcome.slack.com/archives/C3N7J05TK/p1676998601384309

**To do**
-[ ] Fix the tzitzit so it gives a source link with an `/items` suffix regardless of how you arrive at the image

**Comment by alexwlchan** [comment]
I'm going to pick this up ASAP because it's going to keep causing issues for Stories until it's fixed.
