### ISSUE TITLE
Update search box on Collections landing and works pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9351]
# What?

Updating the search form and CTA on `/collections` and `/works` so users have an experience that's consistent with sitewide search

## Questions/considerations
- Default scope for search from Collections landing page - search works by default
- Monitoring impact of change to user journey
- Mobile scale and usability

# Background  

https://wellcome.slack.com/archives/C3TQSF63C/p1677156053697059?thread_ts=1677143892.994629&cid=C3TQSF63C
Builds on https://github.com/wellcomecollection/wellcomecollection.org/issues/8735

# Done when
- [x] Mockups of desktop and mobile in Zeplin ready
- [x] Mapped basic search journey for discussion
- [x] Decided on the approach to move forward with

**Comment by DominiqueMarshall** [comment]
Mockups of desktop and mobile view for the Collections page and Works:

- Collections page: https://zpl.io/O0gqyyP 
- Works page: https://zpl.io/Mdz8XXK
- Mobile: https://zpl.io/qy0PQQl 

I explored adding the tabs for All, Stories, Images and Catalogue to these pages, but it felt clunky and didn't make much sense. With this update, I suggest following the global search pattern and add the search box, defaulting to the Catalogue tab within the search result.
 
We'll need to keep an eye on if we receive any feedback about the loss of the Images tab and how/if it affects researchers in any way. 

Here's a very basic mapped search journey as well: https://zpl.io/1yvrAr5

I'd like to discuss the journey from a works page back to the search results page. Currently, when the ‘back to search’ link is clicked, a user is met with an empty search box and a full list of new results. I feel like this might cause some frustration, as people would most likely expect to see their previous search term still visible so they can continue browsing/refining their search. @rcantin-w can you remember if this behaviour was changed with the new search implementation? Or was it never like that before? (I can't remember!)

Would be good to chat this through next week after Easter cc @davidpmccormick @gestchild @jennpb

**Comment by DominiqueMarshall** [comment]
Design update:

**Alternatively to the above** - we keep the Catalogue and Images tab, but in the new search design style:

https://zpl.io/PqQQx7D (catalogue search)
https://zpl.io/KG11Dv6 (image search - stays on the Collections page when clicked, search box placeholder text updates to match).

This approach would reduce any user frustration that might happen with removing the Images tab, but does it then feel weird when you search something and see the 'All' and 'Stories' tabs on the main search results page? @jennpb This might be a good candidate for some future content design research?

**Comment by DominiqueMarshall** [comment]
Review update - the ideal state to move forward is following the global search pattern on the Collections and Work pages (zeplin designs in first comment). 
cc @rcantin-w

**Comment by DominiqueMarshall** [comment]
@rcantin-w, yep I'd aim for 17px on desktop, 15px on mobile - the zeplin screens should be updated
