### ISSUE TITLE
Investigating audio and video tracking in GA4

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9356]
**What is the problem to solve?**
Audio and video plays were tracked as UA events. GA4 seems to track these as standard. GA4 advice on websites recommend using GTM to track these events instead of relying on the default setup.

**What stage of research is it? (discovery/general usability testing/post release)**
Discovery

**What are the objectives?**
If audio events in GA4 match those of Soundcloud + navigation to works with sound links, then we use the GA4 default set up. If not, another ticket needs to be raised to tag these in GTM
If video events in GA4 match those of YouTube analytics, then we use GA4 default set up. If not, another ticket needs to be raised to tag these in GTM.

**What are the assumptions?**

**What research technique is required?**

**Optimal number of participants**

**Acceptance criteria**

**Deadline for results/dependencies:**

**Comment by taceybadgerbrook** [comment]
A sample of video viewing data was taken for the period 13-22 February from YouTube analytics compared to GA4 data for the same period. The total number of video views according to YouTube analytics was 13,482. Total for GA4 was 14.

YouTube analytics counts views of all videos belonging to the Wellcome Collection channel. This includes videos which formed part of exhibition content (eg the Dissecting Brains video from the exhibition, Brains: The Mind is Matter), trailers (eg Festival of Minds and Bodies.) If we are interested in measuring engagement with wellcomecollection.org, then YouTube analytics data looks like this will not be focussed enough to be useful.

GA4 data only appears to count video views for videos posted during the specified period which is a significant barrier to effective tracking.

**Comment by taceybadgerbrook** [comment]
GA4 video view data only collects data for videos posted on the website. It also collects video views for content that does not belong to the wellcomecollection.org channel, eg the trailer for the film, "Electricity" posted on https://wellcomecollection.org/articles/XlP2bhEAACQAlIzT.

There are some videos which do not appear to be tracked by GA4:
- Getting Started with Creative Research on https://wellcomecollection.org/events/Y5HALREAACIAi29G
- Experiences of Recovery
- Hybrid Humans with Harry Parker on https://wellcomecollection.org/events/Yp3iyhEAACIAwZlk

**Comment by taceybadgerbrook** [comment]
[PR of 22/2/23](https://github.com/wellcomecollection/wellcomecollection.org/pull/9337) will affect video data available for collection. Data from 23-27 February has now been collected.

**Comment by taceybadgerbrook** [comment]
Total YouTube Analytics video views for the period 23-27 February were 6,116 compared to total GA4 video views of 109.

GA4 events which are not picked up by YouTube Analytics are of types below. This makes sense and seems to be fine.
- material not owned by wellcomecollection.org, eg trailers, commercials
- material only accessible from the website, not part of wellcomecollection.org's public YouTube channel
- videos that form part of the Collection

YouTube Analytics counts will always be greater than GA4 due to trailers and content posted in the wellcomecollection.org YouTube channel but not on the website. Videos that YouTube includes which should be picked up by GA4 are videos of catch up events:
- https://wellcomecollection.org/events/YCLmSxIAACUAY7Cv
- https://wellcomecollection.org/events/YDUlIhAAAB8AWlPB
- https://wellcomecollection.org/events/Y3O5kRAAAPepSOpU

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @gestchild 

I can see event videos such as these in GA4 video stats:
- https://wellcomecollection.org/events/X7KY0RMAACMAdqae
- https://wellcomecollection.org/events/YzHNAhEAAEAKgIvV
- https://wellcomecollection.org/events/Y5HALREAACIAi29G

but not these:
- https://wellcomecollection.org/events/YCLmSxIAACUAY7Cv
- https://wellcomecollection.org/events/YDUlIhAAAB8AWlPB
- https://wellcomecollection.org/events/Y3O5kRAAAPepSOpU

Any ideas?

**Comment by davidpmccormick** [comment]
what I found: https://wellcome.slack.com/archives/CUA669WHH/p1677665342745509?thread_ts=1677583293.192169&cid=CUA669WHH

**Comment by taceybadgerbrook** [comment]
The issue affecting video count was fixed on 23/2/2023 by https://github.com/wellcomecollection/wellcomecollection.org/pull/9337

YouTube video view counts will continue to be higher than GA4 video start counts because viewers are able to access videos through Wellcome's YouTube channel whereas GA4 will only count video starts generated by users who are clicking on the link in wellcomecollection.org.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick I am assigning the tracking of html audio files in GTM to you.

**Comment by taceybadgerbrook** [comment]
@davidpmccormick @jennpb  I don't think #9337 has fixed the video tracking. GA4 reports shows video start which is great:
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/32418070/230045192-dd3cd9f9-bdd5-4282-a4d7-7fe34d490521.png">

but when I look for which videos are being viewed, I need to go to Explore reports and I can't get video start as a metric.  I've built [this](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/GIIRhaziRkyaHdShgMd-TA):
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/32418070/230045645-44b747bb-ef27-47b1-a332-20e384588497.png">

**Comment by taceybadgerbrook** [comment]
I've tried treating videos like an event but here are the stats for that Professor Shirley Ann Tate video from YouTube, 
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/32418070/230045886-7f1afba4-5e54-43a7-8e94-eea49d679aa1.png">

**Comment by gestchild** [comment]
@taceybadgerbrook you can filter by [event name exactly matching 'video_start', I've created an example here](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/4AClFNArQ-KtFL0NfF7grg) 

[This article](https://www.analyticsmania.com/post/where-to-find-video-engagement-data-in-google-analytics-4/) explains it further

**Comment by taceybadgerbrook** [comment]
Cool, thanks. I see we could produce a table with percentage duration as well but have you seen anything that might be used instead of total viewing time?

**Comment by gestchild** [comment]
> I see we could produce a table with percentage duration as well but have you seen anything that might be used instead of total viewing time?

I'm not sure I understand. What is it that we want to know exactly?

**Comment by taceybadgerbrook** [comment]
The metric I currently report using YouTube analytics is total viewing time. I can't see anything that would give me this. Have you come across anything?

**Comment by jennpb** [comment]
Would this work?
- dimensions:  `event_name` and`video_provider` 
- metric: `user_engagement` 
- filtered by `video_start`

<img width="486" alt="Screenshot 2023-04-05 at 17 11 27" src="https://user-images.githubusercontent.com/1446139/230140968-52bf87e3-b75c-45fe-8ab6-eda249928318.png">

**Comment by gestchild** [comment]
I don't _think_ so. User engagement as I understand it is essentially time on page (not time the video was played). I'm not sure how it relates to the video_start event when presented in this way, but I think it's just the amount of time users who started a video spent on pages.

**Comment by gestchild** [comment]
Thinking about this some more. We have percentage played and video duration, so it should be something you could calculate. Having googled a bit it doesn't look like GA4 has calculated metrics, like Universal Analytics did, but it may be possible in [Lookup Studio](https://lookerstudio.google.com/navigation/reporting).

Alternatively, you could export the data as a csv and do calculations in Excel - although that's quite a manual process.

N.B. You'd need to bear in mind that anyone reaching 75% played, for example, would be included in the data collected for lower percentages too, so that would need to be accounted for in any calculations.

**Comment by taceybadgerbrook** [comment]
@gestchild Thanks for this. You are right that YouTube reports on videos viewed from the wellcomecollection YouTube channel. The problem is that there is quite a bit of content that is either leftover from an exhibition (eg Dissecting Brains) or posted by Public Programmes (eg trailers.) 

> Thinking about this some more. We have percentage played and video duration, so it should be something you could calculate. Having googled a bit it doesn't look like GA4 has calculated metrics, like Universal Analytics did, but it may be possible in [Looker Studio](https://lookerstudio.google.com/navigation/reporting). See ['About calculated fields'](https://support.google.com/looker-studio/answer/6299685?hl=en#what-you-can-do-with-calculated-fields&zippy=%2Cin-this-article).

Good idea. I'll look into this and report back here.

> Alternatively, you could export the data as a csv and do calculations in Excel - although that's quite a manual process.

For sure. I guess we'd have to have a discussion with the board whether they are happy with percentage played. Personally, I think it's a better metric because videos are of wildly different lengths. 

> N.B. You'd need to bear in mind that anyone reaching 75% played, for example, would be included in the data collected for lower percentages too, so that would need to be accounted for in any calculations.

True. That would be part of the "user instructions" :joy:

**Comment by jennpb** [comment]
@taceybadgerbrook I've discussed what we want to track from a product angle with Jonathan. Would you prefer that we continue to use this issue, and edit the top-level description accordingly, or would you prefer a new clean issue?

**Comment by taceybadgerbrook** [comment]
@jennpb I think closing this and opening a new issue would be better.
