### ISSUE TITLE
Push comics slice to 100% of users

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9412]
# What?

Get the new comics series slice out from behind the toggle

# Why? 

So users can actually see it and we can collect some data!

# Background  

We discussed whether to A/B test an alternative https://github.com/wellcomecollection/wellcomecollection.org/issues/9083
The testing will happen after we get Prismic data into Elasticsearch.

# Done when
-  Comics slice on Stories page appears for 100% of users
-  Toggle removed

**Comment by gestchild** [comment]
I've changed the default toggle value to true, so everyone will now be seeing the comic series slice. The toggle code still needs removing at some point though.

**Comment by gestchild** [comment]
> Drop a note about it in the editorial channel in Slack? I know Ben was asking about it earlier in the week.

Already have :)

**Comment by alexwlchan** [comment]
> Already have :)

Ah I see, in the original thread, not just the top level channel. Somebody is more on the ball than me today, thanks 😅

**Comment by gestchild** [comment]
I think [David's work on changing how we request for the series](https://github.com/wellcomecollection/wellcomecollection.org/pull/9362) negates any need to wait for getting Prismic data into Elasticsearch before running an A/B test, which I seem to recall we didn't want to so while relying on the editorial team having to add the delist tag to comic series.
