### ISSUE TITLE
Events to be set up in GTM

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9471]
The following events have been selected from the Sharepoint spreadsheet, ["8564 UA vs GA4 events"](https://wellcomecloud.sharepoint.com/:x:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B01F0CF66-5BDB-4DBE-9956-B3CF7E872412%7D&file=8564%20UA%20vs%20GA4%20events.xlsx&action=default&mobileredirect=true&cid=cecd2ebe-2cda-4449-9f45-b40e7d6bc204) as requiring set up in Google Tag Manager:

**Comment by taceybadgerbrook** [comment]
|UA Event Category|UA Event Action|GTM variable name|
|:-|:-|:-|
|library_account|view|library_account_view|
|library_account|login|library_account_login|
|requesting|confirm_request|requesting_confirm|
|requesting|initiate_request|requesting_intiate|
|component|booking-tickets:click|click_to_book|
|Audio|pause audio|audio_pause|
|Audio|play audio|audio_play|

Note that audio file tagging is confined to html files (eg digital guides.) It does not include playing works audio files or Soundcloud. #9356

**Comment by taceybadgerbrook** [comment]
|UA Event Category|UA Event Action|GTM variable name|
|:-|:-|:-|
|Multipart navigation (/item)|||
|Archive tree||Gareth was looking into tracking level of tree|
|Archive tree|Chevron clicked|archive_chevron|
|Archive tree|Link clicked|archive_link|

**Comment by gestchild** [comment]
We have and event set up that is tracking tree item clicks, including the level at which the click occurs. See ['Website data collection' for details](https://docs.google.com/document/d/1m0ARLrfGtNA4dSHq10hpIRvOnwlExnuK62T4ADxPNKo/edit#heading=h.13g6bnbyk83n)

**Comment by gestchild** [comment]
We have and event set up that is tracking tree item clicks, including the level at which the click occurs. See ['Website data collection' for details](https://docs.google.com/document/d/1m0ARLrfGtNA4dSHq10hpIRvOnwlExnuK62T4ADxPNKo/edit#heading=h.13g6bnbyk83n)

**Comment by gestchild** [comment]
We have and event set up that is tracking tree item clicks, including the level at which the click occurs. See ['Website data collection' for details](https://docs.google.com/document/d/1m0ARLrfGtNA4dSHq10hpIRvOnwlExnuK62T4ADxPNKo/edit#heading=h.13g6bnbyk83n)

**Comment by taceybadgerbrook** [comment]
@gestchild Thanks. Jenn has asked that all events be documented in Gitbook. Could I ask you to [fill in this link](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/google-tag-manager-events)?

**Comment by davidpmccormick** [comment]
I've updated GitBook with the events and all the relevant GTM data

**Comment by gestchild** [comment]
Hi @jennpb and @taceybadgerbrook,

I just need to confirm something with you both.

We started setting up GTM custom events based on this issue, but we should have been using the [Tracking requirements document](https://docs.google.com/document/d/1hTDviYfwEE7mZGVD41bQztjX2MDcnYy1oGCmbf0EUt4/edit#) as the source of truth.

The majority of events in this Github issue have an equivalent in the google doc, but there are a couple that don't and therefore I think we can remove from GTM:

1) library_account_view - sent when a signed-in user clicks, 'Library account' from the top-right dropdown. I think this is redundant anyway as we can look at page views of /account.
2) audio_pause - sent when a user pauses the AudioPlayer component

Do you agree it is ok to remove these two custom events?

**Comment by taceybadgerbrook** [comment]
@gestchild That's fine with me. Could you add these to the [Gitbook page](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/google-tag-manager-events-not-included-in-enhanced-measurement)? Cheers

**Comment by taceybadgerbrook** [comment]
I think this ticket can be closed. However, @jennpb we will need to write a ticket to about what kind of duration metrics we want to set up. As of today, I can get the number of audio plays, number of users and average session duration (although this might be for the user and not the audio...) by page url.

 [Here is a link to the GA4 report I've made](https://analytics.google.com/analytics/web/#/analysis/p250634548/edit/GIIRhaziRkyaHdShgMd-TA). It uses the filter, "Event contains audio_play."

![image](https://user-images.githubusercontent.com/32418070/231722157-833e2d46-0243-4700-923c-d1a94be33cbc.png)

**Comment by jennpb** [comment]
Everything covered except for audio and video tracking - to be discussed next week.

@jennpb to set up meeting

**Comment by taceybadgerbrook** [comment]
@jennpb

> Audio + video tracking ([Discussion](https://docs.google.com/document/d/15nng7xHBx1lbaCltCShpQqDZ4gHt-lGc0b6Z9IocJLQ/edit?usp=sharing), https://github.com/wellcomecollection/wellcomecollection.org/issues/9630)

 the [github](https://github.com/wellcomecollection/wellcomecollection.org/issues/9630) ticket for audio and video contains the agreed approach after discussion.

> All the various work page clickthroughs - comments in doc for TK - Is this already enabled by Segment?
> -- Click through from /works to /item page
> -- Click through from /works to ‘online resource’ outbound link (example) - GA4
> -- Click through from /works to /concepts via tags

I have commented on your [Tracking requirements doc](https://docs.google.com/document/d/1hTDviYfwEE7mZGVD41bQztjX2MDcnYy1oGCmbf0EUt4/edit), "I can see click through from /works to /item page and click through from /works/ to /concepts but I can't see what the tag was I clicked on to go from /works to /concepts and there is not event registering an outbound click on a works page."
