### ISSUE TITLE
Improve jumping to a page in search

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#9508]
Improve jumping to a specific page of results in search by:

- Letting the user enter a specific page number
- Keeping it clear how many pages of results there are
- Keeping the ability to page through results one at a time

Approach:

- Revisit the previous design of making the current page a text input
- Ensure that this is accessible, though it can be JS only as it is enhanced functionality and pagination is still available

**Comment by pollecuttn** [comment]
@AMBacelar Nice to see this on prod! But when I use the arrows to page forward and back the search results list updates but the number 'Showing page' doesn't update (stays at `1`).

I can use the page number box to change to e.g. page 2 as described above.

**Comment by jtweed** [comment]
Reopening this, as I'm also seeing the above. If you put in a number that's bigger than the number of pages you also get an empty resultset. I think it should 404.

**Comment by rcantin-w** [comment]
Tagging this nitpicky-UI-police question on here (if we're reopening..!), think we'd landed on using square corners only on our inputs fields and it might've been a leftover in the designs, but one for @DominiqueMarshall !

<img width="642" alt="Screenshot 2023-04-21 at 15 19 49" src="https://user-images.githubusercontent.com/110461050/233659906-a1bc0e5f-14d0-4e1c-b654-9cfec4809f0e.png">

**Comment by DominiqueMarshall** [comment]
> Tagging this nitpicky-UI-police question on here (if we're reopening..!), think we'd landed on using square corners only on our inputs fields and it might've been a leftover in the designs, but one for @DominiqueMarshall !
> 
> <img alt="Screenshot 2023-04-21 at 15 19 49" width="642" src="https://user-images.githubusercontent.com/110461050/233659906-a1bc0e5f-14d0-4e1c-b654-9cfec4809f0e.png">

Square corners on all input fields 👍🏽

**Comment by jamieparkinson** [comment]
> If you put in a number that's bigger than the number of pages you also get an empty resultset. I think it should 404.

@jtweed this is an API change really - and not a straightforward choice imo! We wouldn't expect a query which returned 0 results to 404, we would expect it to return 0 results. I don't feel there's a particularly strong argument for pagination query parameters having a different behaviour to other ones; I think they should return 0 results as well (afaik this is standard practice).

What we might want to do is add client-side validation for the page number being `<=` the final page?

**Comment by jtweed** [comment]
As discussed. let's not 404 and instead look at some client side validation. If that's not easily practicable, let's not worry about it too much now until we know whether it's really a problem or not.
