### ISSUE TITLE
Clean up use of 'plain-button' class

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9541]
```
  .plain-button {
    appearance: none;
    font-family: inherit;
    letter-spacing: inherit;
    background: transparent;
    border: 0;
    text-align: left;
  }
```

- Set to button element as default styles
```
  button {
    appearance: none;
    font-family: inherit;
    letter-spacing: inherit;
    background: transparent;
    border: 0;
    text-align: left;
  }
```

- Check if anything that uses this class should be using ButtonSolid instead
- Check if any `button` styles can then be cleaned up (as the default might now cover what they were styling)
- Delete this class declaration

**Comment by alexwlchan** [comment]
I had a look at this awhile back; I think there’s a case we apply this class to a Space.

**Comment by rcantin-w** [comment]
> I had a look at this awhile back; I think there’s a case we apply this class to a Space.
 
Indeed, we looked and there's even a span that uses it! It should all get cleaned up.
