### ISSUE TITLE
Change hardcoded h2 on Exhibitions page

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9565]
# What?

Changing the hardcoded heading on Exhibition pages from 'About this exhibition' to 'Related stories'

# Why? 

Content commissioned for an exhibition isn't always 'about' an exhibition, but tends to be more thematically linked. This new heading will match the intent of commissioned content.

# Background  

https://wellcome.slack.com/archives/C8X9YKM5X/p1680595964412099

# Done when
-  `h2` heading 'About this exhibition' changed to 'Related stories' and displays on all exhibition pages
- Danny informed that change has been made

**Comment by georgiaewhitney** [comment]
This is now merged - hope this is the correct way to close this
