### ISSUE TITLE
Adi Update

### ISSUE THREAD

**Issue by AMBacelar** [wellcomecollection/wellcomecollection.org#9606]
I am today feeling well enough to work.

I still need to get my SIM card (I need my phone number to get past the 2FA on the account since I'm using it on a new phone), so I can't log into Slack/Teams/Outlook/etc... Going into the branch solved nothing since the thieves used my SIM card after stealing my phone, so my account is going through many processes now (I hate Three UK). I believe things should be resolved soon. I am waiting on the new SIM to be delivered.

I am currently reading up on the conversations in #8350 since there may be some insight as to why the context breaks. This could help with  #9452, but I am looking for ideas if that also leads to a dead-end.

I will also look through and see what can be done with my tickets in ready for review

I also will go and clean up the current PRs caused by dependabot

**Comment by jamieparkinson** [comment]
I've opened a ticket with D&T asking if they can help you get round the 2FA issue (have given them your gmail address) - hopefully that can make things a bit easier!

**Comment by AMBacelar** [comment]
Thank you!
