### ISSUE TITLE
Design system consultant brief

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#9615]
## What

Get a proposal from a design system consultant to help form ideas/a roadmap for the design system's structure, documentation process and future maintenance.

## Done when

- [x] Brief written and shared with team for feedback
- [ ]  Brief emailed to consultant

**Comment by jennpb** [comment]
@DominiqueMarshall Do you mind sharing the brief so I can make an agenda for the call with Amy?

**Comment by DominiqueMarshall** [comment]
https://docs.google.com/document/d/1-gGq719fY2b9mTxrpLsHfbtrORvzW0WwGMJPhdVMwGc/edit?usp=sharing

**Comment by jennpb** [comment]
Jason adding some detail re: wellcome.org needs.

Jenn will share this with consultant by Friday 19 May

**Comment by jennpb** [comment]
Emailed brief to Amy on 19/5/23
