### ISSUE TITLE
Audio and video tracking to set up

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9630]
## What

Agreeing what to measure and track for audio and video content on wellcomecollection.org.

This includes
**Editorial + programme content**
- Youtube embeds > YT frame
- Other embeds (very few instances: [here’s an example](https://wellcomecollection.org/articles/YKtzcBQAACUA68uW)) > HTML5 video player
- Audio files > audio player

**Collections content**
- Digitised video (IIIF) > HTML5 video player
- Digitised audio (IIIF) > audio player

Discussion document here: https://docs.google.com/document/d/15nng7xHBx1lbaCltCShpQqDZ4gHt-lGc0b6Z9IocJLQ/edit?usp=sharing

__@davidpmccormick @gestchild @taceybadgerbrook agreed:__
- We should use the standard video events that GA4 tracks for YouTube (`video_start`, `video_progress`, `video_complete`)
- We should piggyback on these _same_ events for tracking non-YouTube video, but change the `Video Provider` parameter to `iiif` or `prismic` – this should be done from within the codebase rather than through GTM (where it would be hard to debug/maintain)
- We should create equivalent events for audio (`audio_start`, `audio_progress`, `audio_complete`) with equivalent parameters (e.g. `Audio Provider`, which could be `iiif` or `prismic`)

__parameters to be sent with each event:__
- {Audio/Video} Current Time
- {Audio/Video} Duration
- {Audio/Video} Percent
- {Audio/Video} Provider
- {Audio/Video} Status
- {Audio/Video} Title
- {Audio/Video} URL

## Done when
- [x] Indicators agreed
- [x] Tracking set up where appropriate
- [x] Documented in Gitbook

**Comment by taceybadgerbrook** [comment]
## Why ##

1. We want to track ROI separately for Collections and non-Collections material, so it is not necessary to track count video or audio usage across the site in one metric. If non-Collections material is YouTube or audio player and Collections material is IIIF or Prismic, filtering by page url and Provider will return the metrics required.

2. We want to be able to evaluate the number of unique videos / audio tracks played to evaluate breadth of material accessed. If url is one of the parameters collected, this will enable this analysis.
 
3. We want our metrics to be consistent with any external data we might use as benchmark data. For this reason the pre-set GA4 video events are being used as the gold standard for extending tracking to IIIF and Prismic for both video and audio.
