### ISSUE TITLE
Analyse A B test data for Comics link formats

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/wellcomecollection.org#9633]
**What is the problem to solve?**
We introduced a new section on the Stories landing page to feature comics series. This first version linked to the comic series page, which includes the whole list of comics in that series. The user journey is Stories landing page > Series page > Individual comic.

The problem is that users have to click through a navigation page before they read a comic. This could be an extra click that users don’t want to make.

**What stage of research is it? (discovery/general usability testing/post release)**
general usability testing

**What are the objectives?**
To compare:

A version (LIVE)
Series 1 > Series 1 landing > Comic
Series 2 > Series 2 landing > Comic
Series 3 > Series 3 landing > Comic

C version
First comic from Series 1 > Comic
First comic from Series 2 > Comic
First comic from Series 3 > Comic

**What are the assumptions?**
If the cards in the comics slice link to a comic instead of a series page
Users will read more comics during their visit
Because there’s one less navigation stage to click through

**What research technique is required?**
A/B testing: 2-sample t-test

**Optimal number of participants**
Must be 20 or more data points

**Acceptance criteria**
Data must be normally distributed, with similar variance

**Deadline for results/dependencies:**

**Comment by taceybadgerbrook** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/taceykobayashi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/taceykobayashi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Total daily page views
-- | --
Day | Toggle on | Toggle off
1 | 17 | 21
2 | 12 | 20
3 | 48 | 28
4 | 28 | 55
5 | 18 | 22
6 | 82 | 34
7 | 13 | 13
8 | 16 | 34
9 | 11 | 22
10 | 63 | 23
11 | 21 | 54
12 | 26 | 36
13 | 92 | 51
14 | 67 | 23
15 | 16 | 17
16 | 27 | 10
17 | 61 | 87
18 | 30 | 41
19 | 73 | 53
20 | 62 | 39



</body>

</html>

**Comment by taceybadgerbrook** [comment]
## T-test set up ##

The null hypothesis is that the format of the comics links served makes no difference to the number of articles (comic and non-comic) users view. Confidence interval = 95%

## Results ##

The test returned a p-value of 0.49. This indicates there is no evidence in support of rejecting the null hypothesis, ie despite differences in average numbers of pages read over the period (39 for those with toggle on and 34 for those with the toggle off), statistical analysis returned no statistically significant difference between the behaviour of the two groups.

## Recommendations ##

As there is no statistical reason to choose one format over the other, the recommendation is to opt for the format which is easier to maintain or has wider utility.

**Comment by taceybadgerbrook** [comment]
@dannybirchall testing found no difference between the two formats for comic links. How would you like to proceed?

**Comment by pollecuttn** [comment]
@gestchild / @davidpmccormick Danny has decided we go with option B. Can we please get the toggle removed and everything using the B option.

**Comment by davidpmccormick** [comment]
Double-checked with @dannybirchall and we're actually keeping the A condition (three cards that link to the _series_ pages for the three most recent comic series-es)
