### ISSUE TITLE
Enabling analysis of 'search within' functionality

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9650]
# What?

Some digitised books have 'search within' functionality. This means that users can 
- search inside the contents of a digitised item using the OCR-generated text
- see number of results with that search query
- see highlighted snippets
- navigate to part of item using the snippet

![Screenshot 2023-04-21 at 14 58 12](https://user-images.githubusercontent.com/1446139/233655119-da7d6506-36eb-41f8-b7c8-d500ab8c44e9.png)

We want to be able to understand more about how users use this functionality, including:
- search behaviour and search queries
- use of search + navigation components: search box, search snippets

This will require some tracking in GA or Segment so data can be analysed.

# Why? 

So we can learn more about how users find, understand and interpret this functionality.

# Done when
-  Tracking mechanism agreed and set up in appropriate tool
-  Documented in Gitbook

**Comment by gestchild** [comment]
Waiting for #9743 before continuing with this
