### ISSUE TITLE
Tracking concept tabs

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#9665]
Relates to #9471

- [ X] clarify what needs doing, should this be tracked in GA4 like other tabs or via Segment?

After discussing with @taceybadgerbrook, we've determined that clicks on these tabs are best tracked with Segment rather than GTM/GA4

TODO:
- [x] add a trackWithSegment prop to the TabNav component
- [x] if the trackWithSegment prop is true then send a Segment tracking event when tabs are clicked

**Comment by taceybadgerbrook** [comment]
@gestchild If you could track these in Segment, would be great. It would allow me to include these actions when analysing search behaviour in Python.
