### ISSUE TITLE
Long breadcrumbs don't display well on mobile

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9763]
**What**

This breadcrumb is sad on mobile Safari https://wellcomecollection.org/articles/XzqMThEAACEA5LhA

https://wellcome.slack.com/archives/C8X9YKM5X/p1683800386314419

**Where**

https://wellcomecollection.org/articles/XzqMThEAACEA5LhA

Safari:
![IMG_3789](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/a598b639-1327-4a1e-b70c-c0cc743545c0)

Also on Brave / Android:
![Screenshot_20230511-115922](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/0768172c-5f2a-45f7-aeab-c2b9d6313118)

**Comment by pollecuttn** [comment]
Not sure if this is a dev fix or if a designer needs to look at this first.

**Comment by rcantin-w** [comment]
In prod
