### ISSUE TITLE
Add a redirect (by Monday 22 May)

### ISSUE THREAD

**Issue by dannybirchall** [wellcomecollection/wellcomecollection.org#9765]
# What?

A website redirect from 
/lbe-festival
to 
/event-series/ZFt3UBQAAMFmEIya

(NB the target page is not yet live)

# Why? 

Ease of use for marketing on instagram and with blind/partially-sighted influencers

# Background  

See conversation at
https://wellcome.slack.com/archives/C8X9YKM5X/p1683740321562319

# Done when

By Monday 22 May at the latest

## Testing and tracking

No additional tracking

## What does success look like?

if the shortcut URL is used

**Comment by rcantin-w** [comment]
@dannybirchall the redirect is in staging (https://www-stage.wellcomecollection.org/lbe-festival) if you'd like to see it. I'll prepare the change to production and merge it in ASAP so it's all done for Monday.
