### ISSUE TITLE
Modelling relationships between exhibition, venue and related access content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9790]
# What?

Review the logic and intent of the current content relationships for exhibition, venue and related access content. 
Consider whether the existing `guides` model meets the needs of visual stories.

# Why? 

When the exhibition guides were modelled, the concept of `guide` was established with the intent that different types of guide could have different data models.

We are introducing visual stories as a new content type. This content type can be used to support exhibitions, events, places within the building, and the whole building itself.

We have started discussing whether visual stories are a type of guide and how they might relate to the established 'guide' model and URL structure.

We need to make some decisions about the relationships we want to create between all the content types as this impacts the whole navigation and discovery architecture, including:
- breadcrumbs
- index pages
- content groupings (series, event series, exhibition guides, seasons)
- onward journeys

# Background  

Discussion from July 2022 in Slack: https://wellcome.slack.com/archives/CUA669WHH/p1658323877677509

# Done when
- Team agrees a conceptual model for content relationships that is technically feasible
- System constraits are understood and taken into account
- URL pattern for visual stories is agreed

**Comment by jennpb** [comment]
Working draft https://miro.com/app/board/uXjVME3nANE=/?share_link_id=746146659831

**Comment by jennpb** [comment]
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446139/60874639-8f96-4ea0-9a3f-900c5433463a)

**Comment by jennpb** [comment]
Needs review with @gestchild https://docs.google.com/spreadsheets/d/1q2Kqe55VIzOzrKzcESpWFlNKPgqw7HYwgB8tNUYK9kI/edit?usp=sharing

May turn into an RFC

**Comment by jennpb** [comment]
What to do about guides and visual stories: https://docs.google.com/document/d/17xPEfOFAFzBeFopkKUAWUTyBo89lPzoSSV5o_4Ri8NQ/edit

This is ready for review + comment from @wellcomecollection/product-project-ux 

Happy to take any questions!

**Comment by j-jaworski** [comment]
Moving this to blocked and will talk with new PM when they start

**Comment by LaurenFBaily** [comment]
I think this ticket should be closed now. My understanding is that:

- the visual stories relating to exhibitions follow Jenn's recommendation for the url structure
- we need to update the url for the generic visual story, however I would like us to look at urls holistically very soon anyway so we should wait to update this as part of that piece of work
- The work to design an index page is documented here https://www.notion.so/wellcometrust/Visual-stories-landing-page-f0bfedcbe62c4b79b49d37e931acf4f9?pvs=4 and includes where these link, how visual stories link to each other and what happens with visual stories for past exhibitions

@gestchild @j-jaworski
