### ISSUE TITLE
Zoom controls not working dev mode

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#9805]
**What**
If you run the site locally in dev mode and visit an item page (e.g. http://localhost:3001/works/vh8erxee/items), click the zoom button the try to use the zoom or rotate controls, in the zoomed view, they don't work. 

It's not an issue on live because if you build the project first, then run it, they do work.

However, we should get to the bottom of it because it will make working on the controls difficult and may be a symptom of something that we need to fix.

**Comment by davidpmccormick** [comment]
Fixed by #10635 which prevented multiple `openseadragon-container` elements being rendered on the page in dev.
