### ISSUE TITLE
Don't load thumbnail image when scrolling the viewer

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#9814]
**What**
If you scroll the viewer quickly we show a loading icon in place of the images.
As the scrolling slows we load in a thumbnail image (displayed large, so it is pixelated).
When the user stops on an image we load in the full resolution image.

![scrolling](https://github.com/wellcomecollection/wellcomecollection.org/assets/6051896/0245428e-f925-49b1-829d-82f8d88b4f7d)

I think the pixelated thumbnail image doesn't really add anything to the experience, but it does add more http requests and data transfer, so we should remove it. 

Furthermore, when the screen is wide enough the thumbnail displays larger than the full image, which creates quite a jarring effect when they switch (see below).

I also think showing the loading icon while waiting for the full resolution to load is more indicative of what is happening, than showing a pixelated image.

@DominiqueMarshall @davidpmccormick would be interested to get your thoughts?

Oversized thumbnail:

![large-thumbnail](https://github.com/wellcomecollection/wellcomecollection.org/assets/6051896/c9be036e-ac18-4cf1-9e8d-381573cdb7f9)

**Comment by DominiqueMarshall** [comment]
Yeah, I agree with this, especially if it means less data transfer and requests 👍🏽
