### ISSUE TITLE
Keyboard navigation in search is broken

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9826]
**What**
Probably closely related, if not the same issue as #9825 
The keyboard navigation behaves differently (and definitely in a buggy way) on various browsers.

**Where**
Try to keyboard navigate on https://wellcomecollection.org/search/works in various browser. Chrome, Safari and Firefox all have different behaviours, skipping various section. We sometimes have
1. Open the page in Safari
2. Enter a query term and submit
3. Focus on the input field and tab
4. It goes straight to Sorting.

**Comment by AMBacelar** [comment]
Just sharing that if this is an MacOS/Safari combo issue, this can be due to Apples decisions for default settings.
https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html

**Comment by rcantin-w** [comment]
@AMBacelar was looking at older tickets and for this one I went back to the [Slack conversation](https://wellcome.slack.com/archives/C02ANCYL90E/p1687166658365419) and it was still happening in FF too I _think_. Could we make sure to update this ticket with all the info for Chrome, Safari and FF and fix or close it as won't fix if it's not doable?

**Comment by rcantin-w** [comment]
@AMBacelar do you remember what the status of this is? (See previous comment too)
