### ISSUE TITLE
Create hard-coded Getting Here  Visual Story (V1)

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9846]
[Mockup](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/646e323278832d17d2d286cc)

We want this page in the website, under a toggle ([to be created](https://github.com/wellcomecollection/wellcomecollection.org/issues/9842)).
We suggest building the newer components in Storybook first to review them as we go with Dom, but if it's simple enough, it might not be that necessary.

Do review what could match components in [the simple version](https://github.com/wellcomecollection/wellcomecollection.org/issues/9848) of the page

# What/why

Building a hard-coded visual story will enable us to 
- get valuable peer review
- use the content ourselves on a variety of devices and screen sizes
- identify design optimizations including spacing, image sizing and composition

# Done when
- Live prototype using existing content is available for review

**Comment by davidpmccormick** [comment]
see https://www-stage.wellcomecollection.org/visual-stories/v1 with `visualStories` toggle on
