### ISSUE TITLE
Review MediaObjectList

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9849]
This is a component that was built in an effort to be multi-functional but ended up being too convoluted and confusing to modify/fix. We'd like to review where it is used in an effort to see if we could use something simpler instead, that could also be useful for the new Visual Stories components.

Alex brought to our attention the deprecated Image List slice component, which could eventually be brought back from deprecation and used.

This ticket serves as a way to document what we find from this discovery piece.

Might relate to https://github.com/wellcomecollection/wellcomecollection.org/issues/7680

- [ ] Add TextAndIcons to Page content type (#10107)
- [ ] Use TextAndIcons for existing page Media Object Lists
- [ ] Use links for existing events/event-series Media Object Lists
- [ ] Remove queries to Media Object List
- [ ] Remove Media Object List from Page/event/event-series content model

**Comment by rcantin-w** [comment]
MediaObjectList is used in 7 nodes, 13 times. Again I've added the URLs.
```
[
  {
    id: 'YgZPOxMAAB4AM-ew',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/YgZPOxMAAB4AM-ew',
    websiteUrl: 'https://wellcomecollection.org/pages/YgZPOxMAAB4AM-ew',
    type: 'pages',
    format: undefined,
    title: 'An invitation to Indigenous communities'
  },
  {
    id: 'YqdICREAAMXL68GJ',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/YqdICREAAMXL68GJ',
    websiteUrl: 'https://wellcomecollection.org/events/YqdICREAAMXL68GJ',
    type: 'events',
    format: 'festival',
    title: 'Invisible Touch'
  },
  {
    id: 'YrSVkREAACIAoger',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/YrSVkREAACIAoger',
    websiteUrl: 'https://wellcomecollection.org/events/YrSVkREAACIAoger',
    type: 'events',
    format: 'festival',
    title: 'A Breath of Fresh Air Festival'
  },
  {
    id: 'Ys11qhEAACEAgsTe',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/Ys11qhEAACEAgsTe',
    websiteUrl: 'https://wellcomecollection.org/event-series/Ys11qhEAACEAgsTe',
    type: 'event-series',
    format: undefined,
    title: 'A Breath of Fresh Air'
  },
  {
    id: 'X5amzBIAAB0Aq6Gm',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/X5amzBIAAB0Aq6Gm',
    websiteUrl: 'https://wellcomecollection.org/pages/X5amzBIAAB0Aq6Gm',
    type: 'pages',
    format: undefined,
    title: 'Keeping you safe'
  },
  {
    id: 'YqdQ7BEAACEA6-O3',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/YqdQ7BEAACEA6-O3',
    websiteUrl: 'https://wellcomecollection.org/pages/YqdQ7BEAACEA6-O3',
    type: 'pages',
    format: undefined,
    title: 'Invisible Touch Trail'
  },
  {
    id: 'Yjm3IBEAACIAd_pL',
    prismicUrl: 'https://wellcomecollection.prismic.io/documents~b=working&c=unclassified&l=en-gb/Yjm3IBEAACIAd_pL',
    websiteUrl: 'https://wellcomecollection.org/events/Yjm3IBEAACIAd_pL',
    type: 'events',
    format: 'festival',
    title: 'Personal Touch'
  }
]
```

**Comment by rcantin-w** [comment]
Made a dashboard to try and outline a possible plan: https://miro.com/app/board/uXjVMFYKs3Y=/?share_link_id=703019992871

**Comment by rcantin-w** [comment]
I'm tempted to move this back to the backlog instead of closing it.
1) We've determined we weren't going to be using MediaObjectList for Visual Stories, so this loses its priority.
2) There is nothing that would replace it as is
     a) I do suggest creating a new, simplified component to render it, but keeping this ticket open to investigate the doability
3) We did find out more about ImageList though, and [a new ticket has been created to work on completely removing it](https://github.com/wellcomecollection/wellcomecollection.org/issues/9868).

**Comment by davidpmccormick** [comment]
I think the work that needs to be done in order to get where we want with this is now being tracked in #9955. Going to move this to the backlog and we can convert the 12 MediaObjectList instances to the new thing we create or rich text.

**Comment by davidpmccormick** [comment]
I _think_ this is all done done done.
