### ISSUE TITLE
Download button is missing from image pages

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#9869]
**What**

Download button is missing from image pages, although it is still available on the catalogue page.

See https://wellcome.slack.com/archives/C8X9YKM5X/p1685442176097839

**Where**

https://wellcomecollection.org/works/hc2bkbes/images?id=jayhbytr

Also
https://wellcomecollection.org/works/fr7j2q34/items

**Comment by gestchild** [comment]
fixed in #9871
