### ISSUE TITLE
Switch to London-comparisons everywhere for isSameDay

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#9874]
The isSameDay function is a bit of a weird historical artefact: it was created in the aftermath of removing the Moment.js dependency from the codebase, and so it supports two definitions of "is it the same day":

* is it the same day in UTC?
* is it the same day in London?

and when you call the function, you have to say which one you want.

I'm ~95% sure we want London comparisons everywhere, but everything involving datetime logic needs care and attention – we need to make sure what the expected behaviour of the calling code is.

This is a tracking ticket for all the small pieces to gradually refactor this away.

**Comment by rcantin-w** [comment]
@alexwlchan this one is scary because time based is scary, would be good to catch up on its status! Maybe it's even done?

**Comment by alexwlchan** [comment]
> would be good to catch up on its status

So there are only three places left where we call `isSameDay()` with UTC (excluding the tests):

https://github.com/wellcomecollection/wellcomecollection.org/blob/01060ff98ea5a5507b537fa405a2a6f93bbe9bf5/common/services/prismic/opening-times.ts#L57C1-L59

https://github.com/wellcomecollection/wellcomecollection.org/blob/01060ff98ea5a5507b537fa405a2a6f93bbe9bf5/common/services/prismic/opening-times.ts#L260C1-L265

https://github.com/wellcomecollection/wellcomecollection.org/blob/01060ff98ea5a5507b537fa405a2a6f93bbe9bf5/content/webapp/services/prismic/transformers/events.ts#L457-L463

All of these are used for grouping events rather than the precise boundary of midnight so I _think_ it would be fine to switch them and nothing bad would happen.

The reason I haven't done it yet is because I've yet to think of a good test case that "proves" London is the correct thing to do. I could change them without changing any of the tests, but that feels a bit icky. In other cases, I was able to find an obvious edge case which differentiated between London/UTC.

I'm going to have a quick look at it this morning; look at how these functions are tested and whether that's a sufficient safety net.
