### ISSUE TITLE
Review the Contact component for Visual Stories

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9886]
We currently have a [Contact component](https://cardigan.wellcomecollection.org/?path=/story/components-contact--basic). 
We'd like to use it for Visual Stories ([as seen in mockups](https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/6464eb699533ae1eab900714)), but it would need to allow icons before the information, and kind of refactor how it's displayed.

We've discussed allowing this using a checkbox (current layout vs new layout), but also just using the new layouts across the site. I need to confirm this as part of this ticket.

![Image](https://user-images.githubusercontent.com/110461050/242603544-b09a638f-972b-49e3-abaf-91a56f505620.png)

![Image](https://user-images.githubusercontent.com/110461050/242603642-4713cdf6-7d3e-4895-a98e-3cfb8e5cf87c.png)

**Comment by rcantin-w** [comment]
@DominiqueMarshall can I confirm with you the last paragraph?

**Comment by DominiqueMarshall** [comment]
In the future yes, but I wouldn't want to use the new layout across the site just yet. I need to spend some time looking at where the current component is used to see if the new layout would work well elsewhere before we consider completely switching over

**Comment by DominiqueMarshall** [comment]
Looks good! Thanks @rcantin-w  😊
