### ISSUE TITLE
Modify phone and email icons

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9906]
We have the new SVGs but they need to be set on a gris that is in line with our other SVGs (viewboxes of 0 0 24 24). Once we have that, we can replace the current ones with the new ones (and ensure they get changed in `Contact.V2` as they are currently PNGs).

**Comment by DominiqueMarshall** [comment]
@rcantin-w can you check if these are the right size? I've saved them myself but not sure how to check the viewbox grid:



![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/60890140/4c47d82e-a944-4dd5-95c4-a44195c8fa10)
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/60890140/060c8676-b35d-4857-b582-a02fd5a7fe13)

**Comment by rcantin-w** [comment]
@DominiqueMarshall [you can look at them here against other icons](https://62f13cdbd0ff140768a8d87b-fmlvcihkco.chromatic.com/?path=/story/global-icons--page), and in the [ContactV2 component](https://62f13cdbd0ff140768a8d87b-fmlvcihkco.chromatic.com/?path=/story/components-contact--contactv-2).

It looks ok to me so far! The email icon is thicker than it was in the image, and now that the phone and the email are within the same viewbox, they now have a more similar width/height


Before
---
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/f275082e-ee4d-44cd-ab4c-c79270797fe3)


After
---
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/8076e394-ae82-4509-80d1-c3f268d88171)


Should we make a decision on the Contact V2 component and decide if we're officially replacing the current version with it?

**Comment by rcantin-w** [comment]
Now in production; next steps would be to check if we want the new Contact component to be made official, but it's not really part of this ticket so I'll close it. Convo to be had with @DominiqueMarshall and @jennpb
