### ISSUE TITLE
Discovery: H3s listed in OnThisPage component

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9907]
From Visual Stories chats:
The behaviour on the mockups (listing h2/h3) isn't the current one (only lists h2). 
1. Toggle behaviour (tweaks to component to allow it)
2. Use inline anchors, as in just have it in a paragraph at the start of the section to link to h3s (not currently possible?)
3. Only show h2s in VS (current behaviour - no work needed)
4. Show h3s too, but only on certain content types (needs works, maybe similar to (a) but done in-code instead of manual)

[See Slack conversation here as we're considering option 1](https://wellcome.slack.com/archives/C054304EVL5/p1685618483928259). We discussed updating the designs across the website as well, so there is a design component as well as a developer one.

**Comment by gestchild** [comment]
Work that was done for this #9937
