### ISSUE TITLE
Arrange accessibility audit with Hassell Inclusion

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9914]
# What?

Get an accessibility audit booked in with Hassell Inclusion, covering key areas and user journeys (areas to be decided).

There's a lot of prep work to be done to get this audit going:
- Briefing the work to be done
- Sorting out contract/procurement
- Organising any meetings and dates for follow-ups

# Why? 

- Identify where we need to improve accessibility and bring the site into WCAG 2.1 compliance

# Background  

We previously contracted Digital Accessibility Centre to do an partial site accessibility audit in 2021. We still have some [open issues](https://github.com/wellcomecollection/wellcomecollection.org/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22DAC+Audit+%282021%29%22) but many more things that were fixed post-audit [closed issues](https://github.com/wellcomecollection/wellcomecollection.org/issues?q=is%3Aissue+milestone%3A%22DAC+Audit+%282021%29%22+is%3Aclosed).

Colleagues in DD&D have commissioned Hassell Inclusion to audit other wellcome sites. We have approval to use them for future audits.

Areas to cover in audit:
- Search, filters and pagination
- Digital content viewer
- Tree navigation
- Open with advisory
- Exhibition guides
- Concepts pages and tabs
- Marked up PDFs (sensory maps, visual story PDFs)
... and whatever else we decide

# Done when
-  [ ] User journeys and features to be tested are agreed within team, and narrowed down to priorities
-  [ ] Workpackage and timeline agreed with contractor

**Comment by jennpb** [comment]
Contact made with Liam Hassell - organising a meeting for 29 June tbc

**Comment by pollecuttn** [comment]
29/6/2023 Team meeting to look at journeys and prioritisation

29/6/2023 HI + Wellcome audit discussion

**Comment by pollecuttn** [comment]
User journeys and features prioritised at https://miro.com/app/board/uXjVM8eY3W0=/?moveToWidget=3458764557840272508&cot=14

These are being used to create the journeys for HI at https://wellcomecollection.org/exhibitions/Y8VNbhEAAPJM-oki

**Comment by jennpb** [comment]
Statement of Work approved - to be signed.

Further scheduling to happen after NP back from leave.
