### ISSUE TITLE
Run a test/survey to learn more about user needs for printing

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9915]
**What is the problem to solve?**

Do people really want to print webpages? Can we run a test or a pop-up survey on specific pages to gauge interest/need?

**What stage of research is it?**

Discovery (quant)

**What are the assumptions?**

People want to print some website content to help them navigate the building or share with others

Test brief https://docs.google.com/document/d/1AJVqVd2cyGW1foH9vjXX4ASIG-vLCJ2Z6Vpio3ltkzw/edit?usp=sharing

**Comment by pollecuttn** [comment]
e.g.
- accessibility page
- visual story

**Comment by LFBaily** [comment]
This is relevant to visual stories as we used to provide this as a downloadable pdf, however work has been done to optimise this page for printing. Closing.
