### ISSUE TITLE
Identify body text differently when in a Body slice.

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9918]
This ticket is a follow up to https://github.com/wellcomecollection/wellcomecollection.org/pull/9916, where we are looking to style slices based off of what slice it is followed/preceded by.

@davidpmccormick and I had that chat a few times while discussing Visual Stories components; there is currently no way, with CSS selectors, to identify components within a page, unless you're reading through the class list (Styled Component names showing up there) and trying some magic there - which we don't want.

We've found a few use case where this would be very useful, but want to do it properly and cleanly. 
- IDs need to be unique, so doesn't work.
- I think using a class name would be wrong as there wouldn't necessarily be styles attached to it and classes should be for styling.
- We thought about using a data-attribute? We'll discuss this in the next catch-up.

Once something is agreed upon, we should review the work done in the mentioned PR and ensure those styles are only applied to SpaceComponents paragraphs used within a Body slice. The current selectors can be used elsewhere and styles could break where we don't want them to.

**Comment by davidpmccormick** [comment]
Picking this up as it's related to work in #9849

**Comment by davidpmccormick** [comment]
Done in #9935
