### ISSUE TITLE
Milk exhibition visual story prototype

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#9926]
Create another visual story mockup/prototype using the Milk exhibition visual story content to help identify whether the patterns used in the Getting Here visual story are easily reusable.

**Comment by DominiqueMarshall** [comment]
Static desktop and mobile mockups for the Milk exhibition:

Desktop - https://zpl.io/vMrjKxP
Mobile - https://zpl.io/xmypREw

**Comment by jennpb** [comment]
Need to figure out how to fit this into the user research + navigation testing

**Comment by jennpb** [comment]
Closing this in preference for testing a live page with Content team
