### ISSUE TITLE
Break up event pages with a long list of scheduled items

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#9949]
[Slack convo in feedback channel](https://wellcome.slack.com/archives/C8X9YKM5X/p1686753847728889) where it was asked "whether past events can be dimmed, minimise or disappear, so that visitors don’t need to page down through past events before getting to the ‘live’ ones "

[Slack conversation for solutioning](https://wellcome.slack.com/archives/CUA669WHH/p1687161340728489)

**Comment by rcantin-w** [comment]
I know there's a PR for this, but what's the status of this since it's ready for approval but the Slack conversation (adding the link in ticket description) says it's parked? Should the PR be reviewed, was there Design approval on this?

**Comment by alexwlchan** [comment]
> what's the status of this

"parked" was referring to the specific question of whether we'd remove any information from past events, not the idea of rearranging this page slightly. I don't know if Dom has reviewed it specifically, but Jenn has given it the nod.

**Comment by alexwlchan** [comment]
Done, deployed!
