### ISSUE TITLE
Add to deployType Prismic script

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9953]
As per the [retrospective actions](https://github.com/wellcomecollection/docs/blob/main/incident_retros/2023-06-12_prismic_model_changes.md):

- Put a warning in the deploy tool to warn when deleting fields, including a prompt to publish
- Change the deploy tool to update all types in one go

**Comment by rcantin-w** [comment]
@pollecuttn all actions from the incident retro have been done with this now being in production.

**Comment by pollecuttn** [comment]
@rcantin-w Great stuff - thanks for the update
