### ISSUE TITLE
Tidy up headings on event series

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9960]
# What?

Event series pages organise the upcoming and past events using h2 headings. The way they're currently phrased is more conversational rather than useful for navigable headings. I suggest changing to the proposed labels, pending review by @dannybirchall 

| State  | Now | Proposed |
| ------------- | ------------- | ------------- |
| Scheduled events  | What's next | Coming up  |
| No scheduled events  | No events scheduled at the moment, check back soon... | No upcoming events | 
| Events in past | What we've done before | Past events | 

Example https://wellcomecollection.org/event-series/WoK-NioAACkANeWK
![Library-Insights-Wellcome-Collection](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446139/15e25f78-97a3-4491-ad52-5fd4c736dc52)

# Why? 

- Greater applicability to all states
- Makes text more scannable
- Plain language

# Background  

This is a legacy holdover from our first design iteration.

# Done when
-  [x] Danny gives the ok or suggests alternatives 
-  [x] Headings changed for each state

**Comment by dannybirchall** [comment]
yes, this makes sense to me!
