### ISSUE TITLE
Temporary hack to hide incorrect attribution for in copyright material

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#9964]
# What?

Collections have started to ingest born digital material relating to exhibitions that is IN COPYRIGHT. The current 'Can I use this?' component, using the autogenerated credit line, misattributes the work to Wellcome Collection. Here's an example: https://wellcomecollection.org/works/wys2bdym

At the moment there are a small number of items that we need to fix so they don't show the misconstructed credit line.

b32881691 / wys2bdym
b32496485 / avqn5jd8
b32496497 / vsp8ce9z
b32892056 / a3v24ekj
b33054721 / ex597wgz
b3305471x / erqm9zxq
b32892068 / y2w42fqa
b32880571 / uzcvr64w
b3288929x / b5m8zwvd

# Why? 

This is a risk for Wellcome Collection in that it creates distrust with living contributors, leading to reputational damage and potential unwillingness to work with WC on projects in the future.

# Background  

Linked to #9963 

https://wellcome.slack.com/archives/C8X9YKM5X/p1686925927988869

**Comment by jennpb** [comment]
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446139/babeaebf-0c64-4662-a330-1f24e815a1dc)

**Comment by pollecuttn** [comment]
Use on all In Copyright works

**Comment by rcantin-w** [comment]
We went a different direction just in case some other works would still benefit from it, we're only hiding "Can I use" from the works mentioned in the ticket description.

It is very much a hack and we'll now focus on doing this properly - but in the meantime, we're not claiming any credit!

**Comment by jennpb** [comment]
I've been sent two more that need to be hidden. Ashley thinks these should be the last for a long while

https://wellcomecollection.org/works/y6ntecuu
https://wellcomecollection.org/works/bbbwbh85
