### ISSUE TITLE
Audit Pages content type

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9987]
## Description
The breadcrumbs work needs us to figure out how the Pages content type fits into a hierarchal vision of the website.

We'll get together a list and aim to group them - from this we might find new ways to group things together that are better for a  futureproof website.

Who knows... Might find a lot to delete as well 👀 

## Definition of Done
- We have a list of all Pages
- We have a decision on if they can be logically grouped or not

**Comment by rcantin-w** [comment]
As I started working on this (and as mentioned in standup), this audit can only cover **live** pages, drafts and archives are not snapshotted by Prismic. It'd take too much time to go through them manually (which is at least 150 of them), so they won't be part of the audit.

**Comment by rcantin-w** [comment]
I've done a first draft and split the 267 live pages by TAGS. I've yet to understand the purpose of all tags and have uncovered that some might be missing. Next steps; I'll share on Slack and eventually discuss with people who have a wider (and older) understanding. Hopefully we can find patterns in there for breadcrumbs.

[Here is the report](https://docs.google.com/spreadsheets/d/1RSIaJFpF9SEcaYO_xeL-Ann3ixZhBwvIt_sWJQFPYz4/edit?usp=sharing).

**Comment by jennpb** [comment]
@jennpb Better description of `descriptive links list`

**Comment by rcantin-w** [comment]
marking this is as done, next steps will most likely be taken in the next sprint.
